## (0) Parameters and Constants

- Service region 20x20 [mile sq.]
- #Demand nodes, $n = 10$ (uniformly distributed)
- Manhattan distance ($l1$)
- Vehicle speed, $v = 20$ [mile/hr], $c_{(i,j)} = \frac{1}{20}(|x_{i}-x_{j}|+|y_{i}-y_{j}|)$ [hr]
- $s_{0}=0.5$ [hr], $s_{1} = 0$ 
- $q_{i} \in \{1,2,3,4,5\}$ [packges/hr]
- Maximum carrying capacity, $Q = 20$ [packages]

In [7]:
no_dock = 0 
no_layer = 1
no_demand_node = 5
truck_capacity = 20
fixed_setup_time = 0.5
truck_speed = 20

constant_dict = { 'truck_capacity' : truck_capacity,'fixed_setup_time' : fixed_setup_time,
                    'truck_speed': truck_speed,'max_vehicles':6}

In [8]:
# Create visualization instance
docking,customers,depot,depot_s,depot_t,all_depot,nodes,arcs=vis_sol.create_nodes(no_dock,no_demand_node)

[] ['customer_1', 'customer_2', 'customer_3', 'customer_4', 'customer_5'] ['depot'] ['customer_4', 'customer_1', 'depot', 'customer_2', 'customer_3', 'customer_5']

In [376]:
## SKIP THIS IF DON'T WANT TO USE NEW RANDOM MAP

# Random distance matrix
distance_matrix, node_position = rand_dis_mat(nodes)
# Random customer demand
_depot_demand = pd.Series([0,0], index =all_depot)
customer_demand = random_customer_demand(customers).append(_depot_demand)
# Visualization 
color_list = vis_sol.create_color_list(list(nodes_position.keys()))
node_trace = vis_sol.create_node_trace(list(nodes_position.values()),list(nodes_position.keys()),
                                 Color=color_list)

### Save Instance to pickle

In [377]:
instance_name='DemoInstanceCus{0}_1'.format(no_demand_node);print(instance_name);
instance_data = {'distance_matrix':distance_matrix,
               'node_position':node_position,
               'node_trace':node_trace,
                'customer_demand_df':customer_demand}
# instance_data

DemoInstanceCus5_1

In [378]:
with open('./Instances/%s.pickle'%instance_name,'wb') as f1:
    pk.dump(instance_data,f1)
    print(instance_name+" is saved succuessfully!")

DemoInstanceCus5_1 is saved succuessfully!

### Import instance

In [11]:
instance_name='DemoInstanceCus{0}_1'.format(no_demand_node);print(instance_name);
with open('./Instances/%s.pickle'%instance_name,'rb') as f1:
    r_instance = pk.load(f1)

distance_matrix = r_instance['distance_matrix']
node_trace = r_instance['node_trace']
customer_demand = r_instance['customer_demand_df']

DemoInstanceCus5_1

In [16]:
vis_sol.plot_solution([['customer_1,customer_2']],node_trace, None,"Demo Instance", customer_demand)

['customer_1', 'customer_2', 'T']

## (1) Initial solution set $\mathcal{R}^{+}$

In [381]:
initializer = InitialRouteGenerator(no_layer,no_dock,no_demand_node,customer_demand,constant_dict,distance_matrix)
# Generate node
(docking,customers,depot,depot_s,
 depot_t,all_depot,nodes,arcs) = initializer.generateNodeSet()

[] ['customer_1', 'customer_2', 'customer_3', 'customer_4', 'customer_5'] ['depot'] ['customer_3', 'customer_1', 'depot', 'customer_2', 'customer_4', 'customer_5']

In [382]:
# Generate initial feasilble routes
row_labels = ['lr','m']+all_depot+customers+arcs
x = pd.DataFrame(data =row_labels,columns=['labels'])
initializer.generateRoutes(initRouteDf=x,
                           truck_cap_limit=truck_capacity,
                           max_visited_nodes=4, max_vehicles_per_route=3)
x = x.set_index('labels')

nbInitRoute is set to 205
progress: 0 / 205
progress: 41 / 205
progress: 82 / 205
progress: 123 / 205
progress: 164 / 205
#Feasible Cols: 457
Elased-time: 0.5013868808746338

In [383]:
# Reformatting
feasibleCols = x.shape[1]
init_route = initializer.generateBasicInitialPatterns(feasibleCols,initRouteDf=x)
init_route.rename(index=lambda x:'route[%d]'%x,inplace=True)

In [384]:
x.head(20)

,route[0],route[1],route[2],route[3],route[4],route[5],route[6],route[7],route[8],route[9],...,route[447],route[448],route[449],route[450],route[451],route[452],route[453],route[454],route[455],route[456]
labels,,,,,,,,,,,,,,,,,,,,,
lr,1.777405,1.777405,1.777405,0.808164,0.808164,0.808164,1.730476,1.730476,1.730476,1.718187,...,2.170864,2.170864,2.852985,2.852985,2.08621,2.08621,2.852985,2.852985,2.08621,2.08621
m,1.000000,2.000000,3.000000,1.000000,2.000000,3.000000,1.000000,2.000000,3.000000,1.000000,...,2.000000,3.000000,2.000000,3.000000,2.00000,3.00000,2.000000,3.000000,2.00000,3.00000
depot_s,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.00000,1.00000
depot_t,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.00000,1.00000
customer_1,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000
customer_2,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.00000,1.00000
customer_3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.00000,1.00000
customer_4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.00000,1.00000
customer_5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.00000,1.00000
"customer_3,customer_1",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000
"customer_1,customer_3",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000
"customer_3,depot_t",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,0.00000,0.00000,1.000000,1.000000,0.00000,0.00000
"depot_s,customer_3",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000
"customer_3,customer_2",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,0.00000,0.00000,0.000000,0.000000,1.00000,1.00000
"customer_2,customer_3",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,1.000000,1.000000,0.00000,0.00000
"customer_3,customer_4",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.00000,1.00000,0.000000,0.000000,0.00000,0.00000
"customer_4,customer_3",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,1.00000,1.00000
"customer_3,customer_5",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000
"customer_5,customer_3",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.00000,1.00000,0.000000,0.000000,0.00000,0.00000
"customer_1,depot_t",1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.00000,0.00000

### Plot sample of route

In [386]:
sample_r = x['route[89]']
sample_arcs = sample_r[sample_r.index.isin(arcs)][sample_r==1]
reformatted_arcs = [merge_depot_arcs_var([t],depot,depot_s,depot_t) for t in sample_arcs.index.to_list()]
print('mr:',sample_r['m'], 'lr:',sample_r['lr'])
vis_sol.plot_solution(reformatted_arcs,node_trace, None,"Demo Instance", customer_demand)

mr: 3.0 lr: 2.503583148490494
['customer_3', 'customer_1', 'T']
['depot', 'customer_3', 'T']
['customer_1', 'customer_2', 'T']
['customer_2', 'depot', 'T']

In [387]:
# feasibleCols = x.shape[1]
# init_route = initializer.generateBasicInitialPatterns(feasibleCols,initRouteDf=x)
# init_route.rename(index=lambda x:'route[%d]'%x,inplace=True)
# route_idx_labels = x.index.values

In [388]:
# init_route

## (2) Phase I: Minimize #vehicle

In [389]:
phaseI_model = phaseIModel(init_route, initializer,
                 distance_matrix,constant_dict)

In [390]:
phaseI_model.buildModel()

Finish generating variables!
Finish generating constrains!
Finish generating objective!

In [391]:
phaseI_model.solveModel(np.inf,0.1)

Changed value of parameter PoolSearchMode to 2
   Prev: 0  Min: 0  Max: 2  Default: 0
Parameter TImeLimit unchanged
   Value: inf  Min: 0.0  Max: inf  Default: inf
Changed value of parameter MIPGap to 0.1
   Prev: 0.0001  Min: 0.0  Max: inf  Default: 0.0001
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (mac64)
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 5 rows, 457 columns and 1509 nonzeros
Model fingerprint: 0x754433b6
Variable types: 0 continuous, 457 integer (457 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 3e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 5.0000000
Presolve time: 0.01s
Presolved: 5 rows, 457 columns, 1509 nonzeros
Variable types: 0 continuous, 457 integer (457 binary)

Root relaxation: objective 2.000000e+00, 8 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0       2.0000000    2.00000  0.00%     -    0s

Optimal solution found at node 0 - now completing solution pool...

    Nodes    |    Current Node    |      Pool Obj. Bounds     |     Work
             |                    |   Worst                   |
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0          -    0               -    2.00000      -     -    0s
     0     0          -    0               -    2.00000      -     -    0s
     0     2          -    0               -    2.00000      -     -    0s

Explored 41 nodes (35 simplex iterations) in 0.06 seconds
Thread count was 8 (of 8 available processors)

Solution count 10: 2 2 2 ... 2

Optimal solution found (tolerance 1.00e-01)
Best objective 2.000000000000e+00, best bound 2.000000000000e+00, gap 0.0000%

In [392]:
sol_obj_phaseI = pd.Series(phaseI_model.model.getVars())
sol_vec_phaseI = pd.DataFrame(index = sol_obj_phaseI.apply(lambda x:x.VarName))
sol_vec_phaseI['value'] = sol_obj_phaseI.apply(lambda x:x.X).values
optimal_routes_phaseI = sol_vec_phaseI.loc[sol_vec_phaseI['value']==1]
optimal_routes_phaseI.index

Index(['route[57]', 'route[111]'], dtype='object')

In [393]:
reformatted_arcs = prep_for_plot(x,optimal_routes_phaseI,arcs)
print(x.loc[['m','lr']][optimal_routes_phaseI.index])
vis_sol.plot_solution(reformatted_arcs,node_trace, None,"Demo Instance", customer_demand)

        route[57]  route[111]
labels
m        1.000000     1.00000
lr       1.979967     1.86206
['depot', 'customer_3', 'T']
['customer_3', 'customer_4', 'T']
['customer_4', 'depot', 'T']
['depot', 'customer_1', 'T']
['customer_1', 'customer_2', 'T']
['customer_5', 'depot', 'T']
['customer_2', 'customer_5', 'T']

## (3) Phase II: Cycle time VRP
(Set partitioning)

In [394]:
phaseII_model = phaseIIModel(init_route, initializer,
                 distance_matrix,constant_dict)

In [395]:
phaseII_model.buildModel()

Finish generating variables!
Finish generating constrains!
Finish generating cost vector!....Elapsed-time: 0.5797119140625
Finish generating objective!

In [396]:
phaseII_model.route_cost

route[0]       1.527405
route[1]       1.083054
route[2]       0.934937
route[3]       0.558164
route[4]       0.356123
                ...
route[452]    12.469845
route[453]    20.403062
route[454]    17.312329
route[455]    14.680751
route[456]    12.420691
Length: 457, dtype: float64

In [397]:
# phaseII_model.route_cost['route[0]']

In [398]:
phaseII_model.solveModel(120,0.1)

Changed value of parameter PoolSearchMode to 2
   Prev: 0  Min: 0  Max: 2  Default: 0
Changed value of parameter TImeLimit to 120.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Changed value of parameter MIPGap to 0.1
   Prev: 0.0001  Min: 0.0  Max: inf  Default: 0.0001
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (mac64)
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 6 rows, 457 columns and 1966 nonzeros
Model fingerprint: 0x60bdc0c4
Variable types: 0 continuous, 457 integer (457 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [3e-01, 3e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 6e+00]
Presolve time: 0.00s
Presolved: 6 rows, 457 columns, 1966 nonzeros
Variable types: 0 continuous, 457 integer (457 binary)
Found heuristic solution: objective 59.6688995
Found heuristic solution: objective 26.4684985
Found heuristic solution: objective 18.5967121

Root relaxation: objective 1.154998e+01, 15 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   11.54998    0    4   18.59671   11.54998  37.9%     -    0s
H    0     0                      12.6680264   11.54998  8.83%     -    0s
H    0     0                      11.8136283   11.54998  2.23%     -    0s
     0     0   11.81363    0    7   11.81363   11.81363  0.00%     -    0s

Optimal solution found at node 0 - now completing solution pool...
Total elapsed time = 0.04s

    Nodes    |    Current Node    |      Pool Obj. Bounds     |     Work
             |                    |   Worst                   |
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0   11.81363    0    7          -   11.81363      -     -    0s
     0     2   11.81363    0    7          -   11.81363      -     -    0s

Cutting planes:
  Cover: 2
  MIR: 3
  Zero half: 3

Explored 47 nodes (84 simplex iterations) in 0.07 seconds
Thread count was 8 (of 8 available processors)

Solution count 10: 11.8136 11.8628 11.9326 ... 12.832

Optimal solution found (tolerance 1.00e-01)
Best objective 1.181362830467e+01, best bound 1.181362830467e+01, gap 0.0000%

In [399]:
sol_obj_phaseII = pd.Series(phaseII_model.model.getVars())
sol_vec_phaseII = pd.DataFrame(index = sol_obj_phaseII.apply(lambda x:x.VarName))
sol_vec_phaseII['value'] = sol_obj_phaseII.apply(lambda x:x.X).values
optimal_routes_phaseII = sol_vec_phaseII.loc[sol_vec_phaseII['value']==1]
optimal_routes_phaseII.index

Index(['route[20]', 'route[228]'], dtype='object')

In [400]:
reformatted_arcs_II = prep_for_plot(x,optimal_routes_phaseII,arcs)
print(x.loc[['m','lr']][optimal_routes_phaseII.index])
vis_sol.plot_solution(reformatted_arcs_II,node_trace, None,"Demo Instance", customer_demand)

        route[20]  route[228]
labels
m        3.000000    3.000000
lr       1.777405    1.979967
['customer_1', 'depot', 'T']
['customer_2', 'customer_1', 'T']
['depot', 'customer_2', 'T']
['customer_3', 'depot', 'T']
['customer_4', 'customer_3', 'T']
['depot', 'customer_5', 'T']
['customer_5', 'customer_4', 'T']

In [401]:
distance_matrix[('customer_2','depot')]

3.0816386272185206

In [402]:
total_cost_phaseI_sol = phaseII_model.route_cost[optimal_routes_phaseI.index].sum()
total_cost_phaseII_sol = phaseII_model.route_cost[optimal_routes_phaseII.index].sum()
print('cost of phase I sol:',total_cost_phaseI_sol,
                              ", Avg mins:",total_cost_phaseI_sol*60/customer_demand.sum(),
     '\ncost of phase II sol:', total_cost_phaseII_sol,
                                  ", Avg mins:",total_cost_phaseII_sol*60/customer_demand.sum())

cost of phase I sol: 26.087605434513364 , Avg mins: 111.80402329077155
cost of phase II sol: 11.81362830466631 , Avg mins: 50.62983559142704

In [ ]:
# ans[optimal_routes_phaseII.index].iloc[phaseII_model.arcs_index]

In [ ]:
# x = ans[optimal_routes_phaseII.index[0]]
# x.loc[x>0]

In [ ]:
# customer_demand.sum()

## (4) DP subproblem
State:= ()

In [403]:
phaseII_model.solveRelaxedModel()

Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (mac64)
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 6 rows, 457 columns and 1966 nonzeros
Model fingerprint: 0x133aa9a0
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [3e-01, 3e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 6e+00]
Presolve time: 0.01s
Presolved: 6 rows, 457 columns, 1966 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    5.7755182e-01   5.000000e+00   0.000000e+00      0s
      15    1.1549976e+01   0.000000e+00   0.000000e+00      0s

Solved in 15 iterations and 0.01 seconds
Optimal objective  1.154997600e+01

In [472]:
duals_vect = pd.DataFrame(phaseII_model.getDuals(), index = phaseII_model.customers + ['m'])
duals_vect

                   0
customer_1  1.946862
customer_2  1.118050
customer_3  5.127934
customer_4  5.086972
customer_5  1.893129
m          -0.559887

In [474]:
distance_matrix

{('customer_1', 'customer_3'): 14.992853661630734,
 ('customer_3', 'customer_1'): 14.992853661630734,
 ('depot', 'customer_3'): 12.304756752027492,
 ('customer_3', 'depot'): 12.304756752027492,
 ('depot', 'customer_1'): 12.774052556151645,
 ('customer_1', 'depot'): 12.774052556151645,
 ('customer_2', 'customer_3'): 11.34797647844474,
 ('customer_3', 'customer_2'): 11.34797647844474,
 ('customer_2', 'customer_1'): 9.692413928933124,
 ('customer_1', 'customer_2'): 9.692413928933124,
 ('customer_2', 'depot'): 3.0816386272185206,
 ('depot', 'customer_2'): 3.0816386272185206,
 ('customer_4', 'customer_3'): 5.1127094862779865,
 ('customer_3', 'customer_4'): 5.1127094862779865,
 ('customer_4', 'customer_1'): 14.499276756380642,
 ('customer_1', 'customer_4'): 14.499276756380642,
 ('customer_4', 'depot'): 12.181871954271454,
 ('depot', 'customer_4'): 12.181871954271454,
 ('customer_4', 'customer_2'): 11.225091680688703,
 ('customer_2', 'customer_4'): 11.225091680688703,
 ('customer_5', 'customer_3'): 9.439002608339784,
 ('customer_3', 'customer_5'): 9.439002608339784,
 ('customer_5', 'customer_1'): 10.15754618390399,
 ('customer_1', 'customer_5'): 10.15754618390399,
 ('customer_5', 'depot'): 2.865754143687708,
 ('depot', 'customer_5'): 2.865754143687708,
 ('customer_5', 'customer_2'): 1.9089738701049566,
 ('customer_2', 'customer_5'): 1.9089738701049566,
 ('customer_5', 'customer_4'): 9.316117810583744,
 ('customer_4', 'customer_5'): 9.316117810583744}

In [424]:
m_veh = 2

In [502]:
#Initialization
s_0 = SPPState('depot_s', 0,0,0,0)
prev = dict(); reward = dict()
prev[s_0] = -1
reward[s_0] = m_veh*duals_vect.loc['m',0]
L = [s_0]
P = []

arcs_ss = pd.Series(phaseII_model.arcs)

return_arcs = arcs_ss[arcs_ss.str.contains(depot_t[0])]            
return_arcs_cost_dict = pd.Series(index = return_arcs, data = return_arcs.apply(lambda x: distance_matrix[tuple(x.replace('_t','').split(','))]/constant_dict['truck_speed']).values).to_dict()

What needed in DP:
- dual_vectors
- distance_matrix

In [503]:
label_counter = 0
print('DP subproblem for m =', m_veh)
while len(L) != 0:
    currState = L.pop(0)
    if currState.resNode == 'depot_s': delta_plus = arcs_ss[arcs_ss.str.contains(currState.resNode)].apply(lambda x: tuple(x.replace('_s','').split(',')))
    else: delta_plus = arcs_ss[arcs_ss.str.contains(currState.resNode+',')].apply(lambda x: tuple(x.split(',')))
    for arc in delta_plus.to_list():
        label_counter +=1; print(label_counter,currState.resNode, arc)
        if arc[-1] == depot_t[0]:
            ext_node = depot[0]
            formatted_arc = (currState.resNode,ext_node)
            return_cost = 0
        else:
            ext_node = arc[-1]
            formatted_arc = arc
            return_cost = return_arcs_cost_dict[','.join([arc[-1]]+depot_t)]

        extState = SPPState(arc[-1], currState.accDemand+customer_demand[arc[-1]], 
                           currState.accDistance+(phaseII_model.distance_matrix[formatted_arc]/20), 
                            currState.nodeVisited+1,label_counter)
        print(currState.label, currState.resNode,reward[currState])

        if checkFeasibility(extState, phaseII_model.vehicle_capacity,m_veh,return_cost):
            prev[extState] = currState
            #Can be improved!
            reward[extState] = reward[currState]+transitionReward(currState,extState,duals_vect,m_veh)
            L.append(extState)
#             if reward[extState] > 0: break
        else: continue
    P.append(currState)
    #     print(checkFeasibility(extState, phaseII_model.vehicle_capacity, phaseII_model.max_vehicles,return_cost))

DP subproblem for m = 2
1 depot_s ('depot', 'customer_3')
0 depot_s -1.119773023916526
resNode: customer_3 deliver_cap: 4.921902700810997 cap_limit: 40
2 depot_s ('depot', 'customer_1')
0 depot_s -1.119773023916526
resNode: customer_1 deliver_cap: 1.2774052556151645 cap_limit: 40
3 depot_s ('depot', 'customer_2')
0 depot_s -1.119773023916526
resNode: customer_2 deliver_cap: 0.30816386272185203 cap_limit: 40
4 depot_s ('depot', 'customer_4')
0 depot_s -1.119773023916526
resNode: customer_4 deliver_cap: 4.872748781708582 cap_limit: 40
5 depot_s ('depot', 'customer_5')
0 depot_s -1.119773023916526
resNode: customer_5 deliver_cap: 1.146301657475083 cap_limit: 40
6 customer_3 ('customer_3', 'customer_1')
1 customer_3 -0.18326620272671934
resNode: customer_1 deliver_cap: 10.017915742452468 cap_limit: 40
7 customer_3 ('customer_3', 'depot_t')
1 customer_3 -0.18326620272671934
resNode: depot_t deliver_cap: 4.921902700810997 cap_limit: 40
8 customer_3 ('customer_3', 'customer_2')
1 customer_3 -0.18326620272671934
resNode: customer_2 deliver_cap: 6.683592964422688 cap_limit: 40
9 customer_3 ('customer_3', 'customer_4')
1 customer_3 -0.18326620272671934
resNode: customer_4 deliver_cap: 11.839735277030773 cap_limit: 40
10 customer_3 ('customer_3', 'customer_5')
1 customer_3 -0.18326620272671934
resNode: customer_5 deliver_cap: 9.843805401621994 cap_limit: 40
11 customer_1 ('customer_1', 'customer_3')
2 customer_1 -0.25596482672632925
resNode: customer_3 deliver_cap: 10.017915742452468 cap_limit: 40
12 customer_1 ('customer_1', 'depot_t')
2 customer_1 -0.25596482672632925
resNode: depot_t deliver_cap: 1.2774052556151645 cap_limit: 40
13 customer_1 ('customer_1', 'customer_2')
2 customer_1 -0.25596482672632925
resNode: customer_2 deliver_cap: 2.554810511230329 cap_limit: 40
14 customer_1 ('customer_1', 'customer_4')
2 customer_1 -0.25596482672632925
resNode: customer_4 deliver_cap: 9.863800316700935 cap_limit: 40
15 customer_1 ('customer_1', 'customer_5')
2 customer_1 -0.25596482672632925
resNode: customer_5 deliver_cap: 6.449338220935836 cap_limit: 40
16 customer_2 ('customer_2', 'customer_3')
3 customer_2 -0.35784554627779996
resNode: customer_3 deliver_cap: 6.683592964422688 cap_limit: 40
17 customer_2 ('customer_2', 'customer_1')
3 customer_2 -0.35784554627779996
resNode: customer_1 deliver_cap: 2.554810511230329 cap_limit: 40
18 customer_2 ('customer_2', 'depot_t')
3 customer_2 -0.35784554627779996
resNode: depot_t deliver_cap: 0.30816386272185203 cap_limit: 40
19 customer_2 ('customer_2', 'customer_4')
3 customer_2 -0.35784554627779996
resNode: customer_4 deliver_cap: 6.62215056554467 cap_limit: 40
20 customer_2 ('customer_2', 'customer_5')
3 customer_2 -0.35784554627779996
resNode: customer_5 deliver_cap: 1.964091660252796 cap_limit: 40
21 customer_4 ('customer_4', 'customer_3')
4 customer_4 -0.18736236265192074
resNode: customer_3 deliver_cap: 11.839735277030773 cap_limit: 40
22 customer_4 ('customer_4', 'customer_1')
4 customer_4 -0.18736236265192074
resNode: customer_1 deliver_cap: 9.863800316700935 cap_limit: 40
23 customer_4 ('customer_4', 'depot_t')
4 customer_4 -0.18736236265192074
resNode: depot_t deliver_cap: 4.872748781708582 cap_limit: 40
24 customer_4 ('customer_4', 'customer_2')
4 customer_4 -0.18736236265192074
resNode: customer_2 deliver_cap: 6.62215056554467 cap_limit: 40
25 customer_4 ('customer_4', 'customer_5')
4 customer_4 -0.18736236265192074
resNode: customer_5 deliver_cap: 9.745497563417162 cap_limit: 40
26 customer_5 ('customer_5', 'customer_3')
5 customer_5 -0.5863704985327322
resNode: customer_3 deliver_cap: 9.843805401621992 cap_limit: 40
27 customer_5 ('customer_5', 'customer_1')
5 customer_5 -0.5863704985327322
resNode: customer_1 deliver_cap: 6.449338220935836 cap_limit: 40
28 customer_5 ('customer_5', 'depot_t')
5 customer_5 -0.5863704985327322
resNode: depot_t deliver_cap: 1.146301657475083 cap_limit: 40
29 customer_5 ('customer_5', 'customer_2')
5 customer_5 -0.5863704985327322
resNode: customer_2 deliver_cap: 1.964091660252796 cap_limit: 40
30 customer_5 ('customer_5', 'customer_4')
5 customer_5 -0.5863704985327322
resNode: customer_4 deliver_cap: 9.745497563417162 cap_limit: 40
31 customer_1 ('customer_1', 'customer_3')
6 customer_1 -1.0002878449184283
resNode: customer_3 deliver_cap: 24.567849372292404 cap_limit: 40
32 customer_1 ('customer_1', 'depot_t')
6 customer_1 -1.0002878449184283
resNode: depot_t deliver_cap: 10.017915742452468 cap_limit: 40
33 customer_1 ('customer_1', 'customer_2')
6 customer_1 -1.0002878449184283
resNode: customer_2 deliver_cap: 12.021498890942961 cap_limit: 40
34 customer_1 ('customer_1', 'customer_4')
6 customer_1 -1.0002878449184283
resNode: customer_4 deliver_cap: 24.290441605939648 cap_limit: 40
35 customer_1 ('customer_1', 'customer_5')
6 customer_1 -1.0002878449184283
resNode: customer_5 deliver_cap: 18.144409833562467 cap_limit: 40
36 customer_2 ('customer_2', 'customer_3')
8 customer_2 -0.8132750554731385
resNode: customer_3 deliver_cap: 21.28745990742501 cap_limit: 40
37 customer_2 ('customer_2', 'customer_1')
8 customer_2 -0.8132750554731385
resNode: customer_1 deliver_cap: 13.8357599146671 cap_limit: 40
38 customer_2 ('customer_2', 'depot_t')
8 customer_2 -0.8132750554731385
resNode: depot_t deliver_cap: 6.683592964422688 cap_limit: 40
39 customer_2 ('customer_2', 'customer_4')
8 customer_2 -0.8132750554731385
resNode: customer_4 deliver_cap: 21.17686358944458 cap_limit: 40
40 customer_2 ('customer_2', 'customer_5')
8 customer_2 -0.8132750554731385
resNode: customer_5 deliver_cap: 12.792357559919205 cap_limit: 40
41 customer_4 ('customer_4', 'customer_3')
9 customer_4 -0.8092453468967173
resNode: customer_3 deliver_cap: 20.900959485966574 cap_limit: 40
42 customer_4 ('customer_4', 'customer_1')
9 customer_4 -0.8092453468967173
resNode: customer_1 deliver_cap: 20.110857997876998 cap_limit: 40
43 customer_4 ('customer_4', 'depot_t')
9 customer_4 -0.8092453468967173
resNode: depot_t deliver_cap: 11.839735277030773 cap_limit: 40
44 customer_4 ('customer_4', 'customer_2')
9 customer_4 -0.8092453468967173
resNode: customer_2 deliver_cap: 14.275888445795715 cap_limit: 40
45 customer_4 ('customer_4', 'customer_5')
9 customer_4 -0.8092453468967173
resNode: customer_5 deliver_cap: 17.75960291554616 cap_limit: 40
46 customer_5 ('customer_5', 'customer_3')
10 customer_5 -4.369364981512818
resNode: customer_3 deliver_cap: 26.09251123244073 cap_limit: 40
47 customer_5 ('customer_5', 'customer_1')
10 customer_5 -4.369364981512818
resNode: customer_1 deliver_cap: 20.10391114519031 cap_limit: 40
48 customer_5 ('customer_5', 'depot_t')
10 customer_5 -4.369364981512818
resNode: depot_t deliver_cap: 9.843805401621994 cap_limit: 40
49 customer_5 ('customer_5', 'customer_2')
10 customer_5 -4.369364981512818
resNode: customer_2 deliver_cap: 12.03046733596084 cap_limit: 40
50 customer_5 ('customer_5', 'customer_4')
10 customer_5 -4.369364981512818
resNode: customer_4 deliver_cap: 25.945049475133484 cap_limit: 40
51 customer_3 ('customer_3', 'customer_1')
11 customer_3 -3.366539845194077
resNode: customer_1 deliver_cap: 16.66014373066943 cap_limit: 40
52 customer_3 ('customer_3', 'depot_t')
11 customer_3 -3.366539845194077
resNode: depot_t deliver_cap: 10.017915742452468 cap_limit: 40
53 customer_3 ('customer_3', 'customer_2')
11 customer_3 -3.366539845194077
resNode: customer_2 deliver_cap: 12.658956397033691 cap_limit: 40
54 customer_3 ('customer_3', 'customer_4')
11 customer_3 -3.366539845194077
resNode: customer_4 deliver_cap: 20.27766944624932 cap_limit: 40
55 customer_3 ('customer_3', 'customer_5')
11 customer_3 -3.366539845194077
resNode: customer_5 deliver_cap: 18.03224833641444 cap_limit: 40
56 customer_2 ('customer_2', 'customer_3')
13 customer_2 -0.7055890902042437
resNode: customer_3 deliver_cap: 13.8357599146671 cap_limit: 40
57 customer_2 ('customer_2', 'customer_1')
13 customer_2 -0.7055890902042437
resNode: customer_1 deliver_cap: 6.73993994552543 cap_limit: 40
58 customer_2 ('customer_2', 'depot_t')
13 customer_2 -0.7055890902042437
resNode: depot_t deliver_cap: 2.554810511230329 cap_limit: 40
59 customer_2 ('customer_2', 'customer_4')
13 customer_2 -0.7055890902042437
resNode: customer_4 deliver_cap: 13.762029036013477 cap_limit: 40
60 customer_2 ('customer_2', 'customer_5')
13 customer_2 -0.7055890902042437
resNode: customer_5 deliver_cap: 8.17235834966323 cap_limit: 40
61 customer_4 ('customer_4', 'customer_3')
14 customer_4 -3.2702572069581883
resNode: customer_3 deliver_cap: 20.110857997876998 cap_limit: 40
62 customer_4 ('customer_4', 'customer_1')
14 customer_4 -3.2702572069581883
resNode: customer_1 deliver_cap: 16.36399758751937 cap_limit: 40
63 customer_4 ('customer_4', 'depot_t')
14 customer_4 -3.2702572069581883
resNode: depot_t deliver_cap: 9.863800316700935 cap_limit: 40
64 customer_4 ('customer_4', 'customer_2')
14 customer_4 -3.2702572069581883
resNode: customer_2 deliver_cap: 12.474017886131854 cap_limit: 40
65 customer_4 ('customer_4', 'customer_5')
14 customer_4 -3.2702572069581883
resNode: customer_5 deliver_cap: 17.754840570061685 cap_limit: 40
66 customer_5 ('customer_5', 'customer_3')
15 customer_5 -4.742139047577519
resNode: customer_3 deliver_cap: 20.10391114519031 cap_limit: 40
67 customer_5 ('customer_5', 'customer_1')
15 customer_5 -4.742139047577519
resNode: customer_1 deliver_cap: 13.758959244033381 cap_limit: 40
68 customer_5 ('customer_5', 'depot_t')
15 customer_5 -4.742139047577519
resNode: depot_t deliver_cap: 6.449338220935836 cap_limit: 40
69 customer_5 ('customer_5', 'customer_2')
15 customer_5 -4.742139047577519
resNode: customer_2 deliver_cap: 8.376663371213734 cap_limit: 40
70 customer_5 ('customer_5', 'customer_4')
15 customer_5 -4.742139047577519
resNode: customer_4 deliver_cap: 19.993314827209872 cap_limit: 40
71 customer_3 ('customer_3', 'customer_1')
16 customer_3 -0.20969199603760671
resNode: customer_1 deliver_cap: 12.658956397033691 cap_limit: 40
72 customer_3 ('customer_3', 'depot_t')
16 customer_3 -0.20969199603760671
resNode: depot_t deliver_cap: 6.683592964422688 cap_limit: 40
73 customer_3 ('customer_3', 'customer_2')
16 customer_3 -0.20969199603760671
resNode: customer_2 deliver_cap: 8.657769063397957 cap_limit: 40
74 customer_3 ('customer_3', 'customer_4')
16 customer_3 -0.20969199603760671
resNode: customer_4 deliver_cap: 14.275888445795715 cap_limit: 40
75 customer_3 ('customer_3', 'customer_5')
16 customer_3 -0.20969199603760671
resNode: customer_5 deliver_cap: 12.030467335960838 cap_limit: 40
76 customer_1 ('customer_1', 'customer_3')
17 customer_1 0.2636523026890687
resNode: customer_3 deliver_cap: 12.021498890942961 cap_limit: 40
77 customer_1 ('customer_1', 'depot_t')
17 customer_1 0.2636523026890687
resNode: depot_t deliver_cap: 2.554810511230329 cap_limit: 40
78 customer_1 ('customer_1', 'customer_2')
17 customer_1 0.2636523026890687
resNode: customer_2 deliver_cap: 3.8322157668454935 cap_limit: 40
79 customer_1 ('customer_1', 'customer_4')
17 customer_1 0.2636523026890687
resNode: customer_4 deliver_cap: 11.836560380041123 cap_limit: 40
80 customer_1 ('customer_1', 'customer_5')
17 customer_1 0.2636523026890687
resNode: customer_5 deliver_cap: 7.739205865123004 cap_limit: 40
81 customer_4 ('customer_4', 'customer_3')
19 customer_4 -0.2107160360189078
resNode: customer_3 deliver_cap: 14.275888445795719 cap_limit: 40
82 customer_4 ('customer_4', 'customer_1')
19 customer_4 -0.2107160360189078
resNode: customer_1 deliver_cap: 12.474017886131854 cap_limit: 40
83 customer_4 ('customer_4', 'depot_t')
19 customer_4 -0.2107160360189078
resNode: depot_t deliver_cap: 6.62215056554467 cap_limit: 40
84 customer_4 ('customer_4', 'customer_2')
19 customer_4 -0.2107160360189078
resNode: customer_2 deliver_cap: 8.584038184744335 cap_limit: 40
85 customer_4 ('customer_4', 'customer_5')
19 customer_4 -0.2107160360189078
resNode: customer_5 deliver_cap: 11.919871017980405 cap_limit: 40
86 customer_5 ('customer_5', 'customer_3')
20 customer_5 -0.3768212266351252
resNode: customer_3 deliver_cap: 12.03046733596084 cap_limit: 40
87 customer_5 ('customer_5', 'customer_1')
20 customer_5 -0.3768212266351252
resNode: customer_1 deliver_cap: 8.376663371213734 cap_limit: 40
88 customer_5 ('customer_5', 'depot_t')
20 customer_5 -0.3768212266351252
resNode: depot_t deliver_cap: 1.964091660252796 cap_limit: 40
89 customer_5 ('customer_5', 'customer_2')
20 customer_5 -0.3768212266351252
resNode: customer_2 deliver_cap: 2.994367498394086 cap_limit: 40
90 customer_5 ('customer_5', 'customer_4')
20 customer_5 -0.3768212266351252
resNode: customer_4 deliver_cap: 11.919871017980403 cap_limit: 40
91 customer_3 ('customer_3', 'customer_1')
21 customer_3 -0.7600914277943023
resNode: customer_1 deliver_cap: 20.27766944624932 cap_limit: 40
92 customer_3 ('customer_3', 'depot_t')
21 customer_3 -0.7600914277943023
resNode: depot_t deliver_cap: 11.839735277030773 cap_limit: 40
93 customer_3 ('customer_3', 'customer_2')
21 customer_3 -0.7600914277943023
resNode: customer_2 deliver_cap: 14.275888445795715 cap_limit: 40
94 customer_3 ('customer_3', 'customer_4')
21 customer_3 -0.7600914277943023
resNode: customer_4 deliver_cap: 20.75349772865933 cap_limit: 40
95 customer_3 ('customer_3', 'customer_5')
21 customer_3 -0.7600914277943023
resNode: customer_5 deliver_cap: 17.75960291554616 cap_limit: 40
96 customer_1 ('customer_1', 'customer_3')
22 customer_1 -0.9473205430310436
resNode: customer_3 deliver_cap: 24.290441605939645 cap_limit: 40
97 customer_1 ('customer_1', 'depot_t')
22 customer_1 -0.9473205430310436
resNode: depot_t deliver_cap: 9.863800316700935 cap_limit: 40
98 customer_1 ('customer_1', 'customer_2')
22 customer_1 -0.9473205430310436
resNode: customer_2 deliver_cap: 11.83656038004112 cap_limit: 40
99 customer_1 ('customer_1', 'customer_4')
22 customer_1 -0.9473205430310436
resNode: customer_4 deliver_cap: 24.013033839586885 cap_limit: 40
100 customer_1 ('customer_1', 'customer_5')
22 customer_1 -0.9473205430310436
resNode: customer_5 deliver_cap: 17.867002067209707 cap_limit: 40
101 customer_2 ('customer_2', 'customer_3')
24 customer_2 -0.8020106156788356
resNode: customer_3 deliver_cap: 21.176863589444576 cap_limit: 40
102 customer_2 ('customer_2', 'customer_1')
24 customer_2 -0.8020106156788356
resNode: customer_1 deliver_cap: 13.762029036013477 cap_limit: 40
103 customer_2 ('customer_2', 'depot_t')
24 customer_2 -0.8020106156788356
resNode: depot_t deliver_cap: 6.62215056554467 cap_limit: 40
104 customer_2 ('customer_2', 'customer_4')
24 customer_2 -0.8020106156788356
resNode: customer_4 deliver_cap: 21.06626727146414 cap_limit: 40
105 customer_2 ('customer_2', 'customer_5')
24 customer_2 -0.8020106156788356
resNode: customer_5 deliver_cap: 12.681761241938771 cap_limit: 40
106 customer_5 ('customer_5', 'customer_3')
25 customer_5 -4.312018742559999
resNode: customer_3 deliver_cap: 25.945049475133484 cap_limit: 40
107 customer_5 ('customer_5', 'customer_1')
25 customer_5 -4.312018742559999
resNode: customer_1 deliver_cap: 19.993314827209872 cap_limit: 40
108 customer_5 ('customer_5', 'depot_t')
25 customer_5 -4.312018742559999
resNode: depot_t deliver_cap: 9.745497563417162 cap_limit: 40
109 customer_5 ('customer_5', 'customer_2')
25 customer_5 -4.312018742559999
resNode: customer_2 deliver_cap: 11.919871017980403 cap_limit: 40
110 customer_5 ('customer_5', 'customer_4')
25 customer_5 -4.312018742559999
resNode: customer_4 deliver_cap: 25.797587717826236 cap_limit: 40
111 customer_3 ('customer_3', 'customer_1')
26 customer_3 -0.5937639381769031
resNode: customer_1 deliver_cap: 18.03224833641444 cap_limit: 40
112 customer_3 ('customer_3', 'depot_t')
26 customer_3 -0.5937639381769031
resNode: depot_t deliver_cap: 9.843805401621992 cap_limit: 40
113 customer_3 ('customer_3', 'customer_2')
26 customer_3 -0.5937639381769031
resNode: customer_2 deliver_cap: 12.030467335960838 cap_limit: 40
114 customer_3 ('customer_3', 'customer_4')
26 customer_3 -0.5937639381769031
resNode: customer_4 deliver_cap: 17.75960291554616 cap_limit: 40
115 customer_3 ('customer_3', 'customer_5')
26 customer_3 -0.5937639381769031
resNode: customer_5 deliver_cap: 14.765708102432992 cap_limit: 40
116 customer_1 ('customer_1', 'customer_3')
27 customer_1 -0.7414325168759353
resNode: customer_3 deliver_cap: 18.144409833562467 cap_limit: 40
117 customer_1 ('customer_1', 'depot_t')
27 customer_1 -0.7414325168759353
resNode: depot_t deliver_cap: 6.449338220935836 cap_limit: 40
118 customer_1 ('customer_1', 'customer_2')
27 customer_1 -0.7414325168759353
resNode: customer_2 deliver_cap: 7.739205865123004 cap_limit: 40
119 customer_1 ('customer_1', 'customer_4')
27 customer_1 -0.7414325168759353
resNode: customer_4 deliver_cap: 17.86700206720971 cap_limit: 40
120 customer_1 ('customer_1', 'customer_5')
27 customer_1 -0.7414325168759353
resNode: customer_5 deliver_cap: 11.72097029483253 cap_limit: 40
121 customer_2 ('customer_2', 'customer_3')
29 customer_2 -0.036504025236678506
resNode: customer_3 deliver_cap: 12.792357559919203 cap_limit: 40
122 customer_2 ('customer_2', 'customer_1')
29 customer_2 -0.036504025236678506
resNode: customer_1 deliver_cap: 8.17235834966323 cap_limit: 40
123 customer_2 ('customer_2', 'depot_t')
29 customer_2 -0.036504025236678506
resNode: depot_t deliver_cap: 1.964091660252796 cap_limit: 40
124 customer_2 ('customer_2', 'customer_4')
29 customer_2 -0.036504025236678506
resNode: customer_4 deliver_cap: 12.681761241938771 cap_limit: 40
125 customer_2 ('customer_2', 'customer_5')
29 customer_2 -0.036504025236678506
resNode: customer_5 deliver_cap: 4.297255212413398 cap_limit: 40
126 customer_4 ('customer_4', 'customer_3')
30 customer_4 -0.5855716183265003
resNode: customer_3 deliver_cap: 17.75960291554616 cap_limit: 40
127 customer_4 ('customer_4', 'customer_1')
30 customer_4 -0.5855716183265003
resNode: customer_1 deliver_cap: 17.75484057006168 cap_limit: 40
128 customer_4 ('customer_4', 'depot_t')
30 customer_4 -0.5855716183265003
resNode: depot_t deliver_cap: 9.745497563417162 cap_limit: 40
129 customer_4 ('customer_4', 'customer_2')
30 customer_4 -0.5855716183265003
resNode: customer_2 deliver_cap: 11.919871017980403 cap_limit: 40
130 customer_4 ('customer_4', 'customer_5')
30 customer_4 -0.5855716183265003
resNode: customer_5 deliver_cap: 14.618246345125744 cap_limit: 40
131 customer_3 ('customer_3', 'customer_1')
31 customer_3 -8.46793022063815
resNode: customer_1 deliver_cap: 35.02868514653567 cap_limit: 40
132 customer_3 ('customer_3', 'depot_t')
31 customer_3 -8.46793022063815
resNode: depot_t deliver_cap: 24.567849372292404 cap_limit: 40
133 customer_3 ('customer_3', 'customer_2')
31 customer_3 -8.46793022063815
resNode: customer_2 deliver_cap: 28.36003959047611 cap_limit: 40
134 customer_3 ('customer_3', 'customer_4')
31 customer_3 -8.46793022063815
resNode: customer_4 deliver_cap: 38.73027958529496 cap_limit: 40
135 customer_3 ('customer_3', 'customer_5')
31 customer_3 -8.46793022063815
resNode: customer_5 deliver_cap: 35.48689353775569 cap_limit: 40
136 customer_2 ('customer_2', 'customer_3')
33 customer_2 -2.357634474490504
resNode: customer_3 deliver_cap: 30.321378786531792 cap_limit: 40
137 customer_2 ('customer_2', 'customer_1')
33 customer_2 -2.357634474490504
resNode: customer_1 deliver_cap: 20.809771789686643 cap_limit: 40
138 customer_2 ('customer_2', 'depot_t')
33 customer_2 -2.357634474490504
resNode: depot_t deliver_cap: 12.021498890942961 cap_limit: 40
139 customer_2 ('customer_2', 'customer_4')
33 customer_2 -2.357634474490504
resNode: customer_4 deliver_cap: 30.198493988775752 cap_limit: 40
140 customer_2 ('customer_2', 'customer_5')
33 customer_2 -2.357634474490504
resNode: customer_5 deliver_cap: 20.882376178192004 cap_limit: 40
141 customer_4 ('customer_4', 'customer_3')
34 customer_4 -8.340824497251957
resNode: customer_3 deliver_cap: 38.48932971542383 cap_limit: 40
142 customer_4 ('customer_4', 'customer_1')
34 customer_4 -8.340824497251957

174 customer_3 ('customer_3', 'customer_4')
41 customer_3 -2.952652697249306
resNode: customer_4 deliver_cap: 31.859805732106324 cap_limit: 40
175 customer_3 ('customer_3', 'customer_5')
41 customer_3 -2.952652697249306
resNode: customer_5 deliver_cap: 27.867945981288766 cap_limit: 40
176 customer_1 ('customer_1', 'customer_3')
42 customer_1 -2.6510010379410094
resNode: customer_3 deliver_cap: 38.48932971542382 cap_limit: 40
177 customer_1 ('customer_1', 'depot_t')
42 customer_1 -2.6510010379410094
resNode: depot_t deliver_cap: 20.110857997876998 cap_limit: 40
178 customer_1 ('customer_1', 'customer_2')
42 customer_1 -2.6510010379410094
resNode: customer_2 deliver_cap: 22.34539777541888 cap_limit: 40
179 customer_1 ('customer_1', 'customer_4')
42 customer_1 -2.6510010379410094
resNode: customer_4 deliver_cap: 38.08862960846984 cap_limit: 40
180 customer_1 ('customer_1', 'customer_5')
42 customer_1 -2.6510010379410094
resNode: customer_5 deliver_cap: 29.21102815948058 cap_limit: 40
181 customer_2 ('customer_2', 'customer_3')
44 customer_2 -1.8573611603575477
resNode: customer_3 deliver_cap: 33.99193924715317 cap_limit: 40
182 customer_2 ('customer_2', 'customer_1')
44 customer_2 -1.8573611603575477
resNode: customer_1 deliver_cap: 25.554512202039472 cap_limit: 40
183 customer_2 ('customer_2', 'depot_t')
44 customer_2 -1.8573611603575477
resNode: depot_t deliver_cap: 14.275888445795715 cap_limit: 40
184 customer_2 ('customer_2', 'customer_4')
44 customer_2 -1.8573611603575477
resNode: customer_4 deliver_cap: 33.83218901007032 cap_limit: 40
185 customer_2 ('customer_2', 'customer_5')
44 customer_2 -1.8573611603575477
resNode: customer_5 deliver_cap: 21.721235856311452 cap_limit: 40
186 customer_5 ('customer_5', 'customer_3')
45 customer_5 -6.242800297813304
resNode: customer_3 deliver_cap: 38.781874727405196 cap_limit: 40
187 customer_5 ('customer_5', 'customer_1')
45 customer_5 -6.242800297813304
resNode: customer_1 deliver_cap: 32.282368812814155 cap_limit: 40
188 customer_5 ('customer_5', 'depot_t')
45 customer_5 -6.242800297813304
resNode: depot_t deliver_cap: 17.75960291554616 cap_limit: 40
189 customer_5 ('customer_5', 'customer_2')
45 customer_5 -6.242800297813304
resNode: customer_2 deliver_cap: 20.620727755038256 cap_limit: 40
190 customer_5 ('customer_5', 'customer_4')
45 customer_5 -6.242800297813304
resNode: customer_4 deliver_cap: 38.58525905099553 cap_limit: 40
191 customer_3 ('customer_3', 'customer_1')
46 customer_3 -10.040159986160859
resNode: customer_1 deliver_cap: 38.31728432121814 cap_limit: 40
192 customer_3 ('customer_3', 'depot_t')
46 customer_3 -10.040159986160859
resNode: depot_t deliver_cap: 26.09251123244073 cap_limit: 40
193 customer_3 ('customer_3', 'customer_2')
46 customer_3 -10.040159986160859
resNode: customer_2 deliver_cap: 29.648045098340706 cap_limit: 40
194 customer_3 ('customer_3', 'customer_4')
46 customer_3 -10.040159986160859
resNode: customer_4 deliver_cap: 38.7818747274052 cap_limit: 40
195 customer_3 ('customer_3', 'customer_5')
46 customer_3 -10.040159986160859
resNode: customer_5 deliver_cap: 34.79001497658764 cap_limit: 40
196 customer_1 ('customer_1', 'customer_3')
47 customer_1 -6.70759455571689
resNode: customer_3 deliver_cap: 38.47929537265417 cap_limit: 40
197 customer_1 ('customer_1', 'depot_t')
47 customer_1 -6.70759455571689
resNode: depot_t deliver_cap: 20.10391114519031 cap_limit: 40
198 customer_1 ('customer_1', 'customer_2')
47 customer_1 -6.70759455571689
resNode: customer_2 deliver_cap: 22.337679050211456 cap_limit: 40
199 customer_1 ('customer_1', 'customer_4')
47 customer_1 -6.70759455571689
resNode: customer_4 deliver_cap: 38.07859526570019 cap_limit: 40
200 customer_1 ('customer_1', 'customer_5')
47 customer_1 -6.70759455571689
resNode: customer_5 deliver_cap: 29.200993816710927 cap_limit: 40
201 customer_2 ('customer_2', 'customer_3')
49 customer_2 -5.105616751941026
resNode: customer_3 deliver_cap: 30.748553199613905 cap_limit: 40
202 customer_2 ('customer_2', 'customer_1')
49 customer_2 -5.105616751941026
resNode: customer_1 deliver_cap: 23.0595998577785 cap_limit: 40
203 customer_2 ('customer_2', 'depot_t')
49 customer_2 -5.105616751941026
resNode: depot_t deliver_cap: 12.03046733596084 cap_limit: 40
204 customer_2 ('customer_2', 'customer_4')
49 customer_2 -5.105616751941026
resNode: customer_4 deliver_cap: 30.58880296253106 cap_limit: 40
205 customer_2 ('customer_2', 'customer_5')
49 customer_2 -5.105616751941026
resNode: customer_5 deliver_cap: 18.477849808772184 cap_limit: 40
206 customer_4 ('customer_4', 'customer_3')
50 customer_4 -10.019679186534852
resNode: customer_3 deliver_cap: 38.7818747274052 cap_limit: 40
207 customer_4 ('customer_4', 'customer_1')
50 customer_4 -10.019679186534852
resNode: customer_1 deliver_cap: 37.916584214264155 cap_limit: 40
208 customer_4 ('customer_4', 'depot_t')
50 customer_4 -10.019679186534852
resNode: depot_t deliver_cap: 25.945049475133484 cap_limit: 40
209 customer_4 ('customer_4', 'customer_2')
50 customer_4 -10.019679186534852
resNode: customer_2 deliver_cap: 29.488294861257856 cap_limit: 40
210 customer_4 ('customer_4', 'customer_5')
50 customer_4 -10.019679186534852
resNode: customer_5 deliver_cap: 34.59339930017798 cap_limit: 40
211 customer_1 ('customer_1', 'customer_3')
51 customer_1 -5.343222697317403
resNode: customer_3 deliver_cap: 35.02868514653567 cap_limit: 40
212 customer_1 ('customer_1', 'depot_t')
51 customer_1 -5.343222697317403
resNode: depot_t deliver_cap: 16.66014373066943 cap_limit: 40
213 customer_1 ('customer_1', 'customer_2')
51 customer_1 -5.343222697317403
resNode: customer_2 deliver_cap: 19.43683435244767 cap_limit: 40
214 customer_1 ('customer_1', 'customer_4')
51 customer_1 -5.343222697317403
resNode: customer_4 deliver_cap: 34.72045429503261 cap_limit: 40
215 customer_1 ('customer_1', 'customer_5')
51 customer_1 -5.343222697317403
resNode: customer_5 deliver_cap: 27.891530103502408 cap_limit: 40
216 customer_2 ('customer_2', 'customer_3')
53 customer_2 -4.989493768970624
resNode: customer_3 deliver_cap: 31.383807963349675 cap_limit: 40
217 customer_2 ('customer_2', 'customer_1')
53 customer_2 -4.989493768970624
resNode: customer_1 deliver_cap: 21.553472213459163 cap_limit: 40
218 customer_2 ('customer_2', 'depot_t')
53 customer_2 -4.989493768970624
resNode: depot_t deliver_cap: 12.658956397033691 cap_limit: 40
219 customer_2 ('customer_2', 'customer_4')
53 customer_2 -4.989493768970624
resNode: customer_4 deliver_cap: 31.260923165593635 cap_limit: 40
220 customer_2 ('customer_2', 'customer_5')
53 customer_2 -4.989493768970624
resNode: customer_5 deliver_cap: 21.94480535500989 cap_limit: 40
221 customer_4 ('customer_4', 'customer_3')
54 customer_4 -7.920429164409321
resNode: customer_3 deliver_cap: 32.6931032625378 cap_limit: 40
222 customer_4 ('customer_4', 'customer_1')
54 customer_4 -7.920429164409321
resNode: customer_1 deliver_cap: 30.076472508296327 cap_limit: 40
223 customer_4 ('customer_4', 'depot_t')
54 customer_4 -7.920429164409321
resNode: depot_t deliver_cap: 20.27766944624932 cap_limit: 40
224 customer_4 ('customer_4', 'customer_2')
54 customer_4 -7.920429164409321
resNode: customer_2 deliver_cap: 23.593173005983793 cap_limit: 40
225 customer_4 ('customer_4', 'customer_5')
54 customer_4 -7.920429164409321
resNode: customer_5 deliver_cap: 29.28996697791568 cap_limit: 40
226 customer_5 ('customer_5', 'customer_3')
55 customer_5 -11.418175990418899
resNode: customer_3 deliver_cap: 38.31728432121814 cap_limit: 40
227 customer_5 ('customer_5', 'customer_1')
55 customer_5 -11.418175990418899
resNode: customer_1 deliver_cap: 30.0687537830889 cap_limit: 40
228 customer_5 ('customer_5', 'depot_t')
55 customer_5 -11.418175990418899
resNode: depot_t deliver_cap: 18.03224833641444 cap_limit: 40
229 customer_5 ('customer_5', 'customer_2')
55 customer_5 -11.418175990418899
resNode: customer_2 deliver_cap: 21.098260661722822 cap_limit: 40
230 customer_5 ('customer_5', 'customer_4')
55 customer_5 -11.418175990418899
resNode: customer_4 deliver_cap: 38.157534084135285 cap_limit: 40
231 customer_3 ('customer_3', 'customer_1')
56 customer_3 -5.660781186971285
resNode: customer_1 deliver_cap: 21.553472213459163 cap_limit: 40
232 customer_3 ('customer_3', 'depot_t')
56 customer_3 -5.660781186971285
resNode: depot_t deliver_cap: 13.8357599146671 cap_limit: 40
233 customer_3 ('customer_3', 'customer_2')
56 customer_3 -5.660781186971285
resNode: customer_2 deliver_cap: 16.88542032421747 cap_limit: 40
234 customer_3 ('customer_3', 'customer_4')
56 customer_3 -5.660781186971285
resNode: customer_4 deliver_cap: 25.554512202039476 cap_limit: 40
235 customer_3 ('customer_3', 'customer_5')
56 customer_3 -5.660781186971285
resNode: customer_5 deliver_cap: 23.0595998577785 cap_limit: 40
236 customer_1 ('customer_1', 'customer_3')
57 customer_1 -1.5379533305773434
resNode: customer_3 deliver_cap: 20.809771789686643 cap_limit: 40
237 customer_1 ('customer_1', 'depot_t')
57 customer_1 -1.5379533305773434
resNode: depot_t deliver_cap: 6.73993994552543 cap_limit: 40
238 customer_1 ('customer_1', 'customer_2')
57 customer_1 -1.5379533305773434
resNode: customer_2 deliver_cap: 8.986586594033907 cap_limit: 40
239 customer_1 ('customer_1', 'customer_4')
57 customer_1 -1.5379533305773434
resNode: customer_4 deliver_cap: 20.594010193634496 cap_limit: 40
240 customer_1 ('customer_1', 'customer_5')
57 customer_1 -1.5379533305773434
resNode: customer_5 deliver_cap: 15.813763259563354 cap_limit: 40
241 customer_4 ('customer_4', 'customer_3')
59 customer_4 -5.6587331070086835
resNode: customer_3 deliver_cap: 25.554512202039476 cap_limit: 40
242 customer_4 ('customer_4', 'customer_1')
59 customer_4 -5.6587331070086835
resNode: customer_1 deliver_cap: 21.337710617407016 cap_limit: 40
243 customer_4 ('customer_4', 'depot_t')
59 customer_4 -5.6587331070086835
resNode: depot_t deliver_cap: 13.762029036013477 cap_limit: 40
244 customer_4 ('customer_4', 'customer_2')
59 customer_4 -5.6587331070086835
resNode: customer_2 deliver_cap: 16.79940096578824 cap_limit: 40
245 customer_4 ('customer_4', 'customer_5')
59 customer_4 -5.6587331070086835
resNode: customer_5 deliver_cap: 22.93671506002246 cap_limit: 40
246 customer_5 ('customer_5', 'customer_3')
60 customer_5 -5.591935352360308
resNode: customer_3 deliver_cap: 23.0595998577785 cap_limit: 40
247 customer_5 ('customer_5', 'customer_1')
60 customer_5 -5.591935352360308
resNode: customer_1 deliver_cap: 16.557463683335875 cap_limit: 40
248 customer_5 ('customer_5', 'depot_t')
60 customer_5 -5.591935352360308
resNode: depot_t deliver_cap: 8.17235834966323 cap_limit: 40
249 customer_5 ('customer_5', 'customer_2')
60 customer_5 -5.591935352360308
resNode: customer_2 deliver_cap: 10.278118498379621 cap_limit: 40
250 customer_5 ('customer_5', 'customer_4')
60 customer_5 -5.591935352360308
resNode: customer_4 deliver_cap: 22.93671506002246 cap_limit: 40
251 customer_3 ('customer_3', 'customer_1')
61 customer_3 -7.681295540216205
resNode: customer_1 deliver_cap: 30.076472508296327 cap_limit: 40
252 customer_3 ('customer_3', 'depot_t')
61 customer_3 -7.681295540216205
resNode: depot_t deliver_cap: 20.110857997876998 cap_limit: 40
253 customer_3 ('customer_3', 'customer_2')
61 customer_3 -7.681295540216205
resNode: customer_2 deliver_cap: 23.407826952236768 cap_limit: 40
254 customer_3 ('customer_3', 'customer_4')
61 customer_3 -7.681295540216205
resNode: customer_4 deliver_cap: 32.29240315558381 cap_limit: 40
255 customer_3 ('customer_3', 'customer_5')
61 customer_3 -7.681295540216205
resNode: customer_5 deliver_cap: 29.049017108044545 cap_limit: 40
256 customer_1 ('customer_1', 'customer_3')
62 customer_1 -5.162074689206873
resNode: customer_3 deliver_cap: 34.53510824128558 cap_limit: 40
257 customer_1 ('customer_1', 'depot_t')
62 customer_1 -5.162074689206873
resNode: depot_t deliver_cap: 16.36399758751937 cap_limit: 40
258 customer_1 ('customer_1', 'customer_2')
62 customer_1 -5.162074689206873
resNode: customer_2 deliver_cap: 19.0913305187726 cap_limit: 40
259 customer_1 ('customer_1', 'customer_4')
62 customer_1 -5.162074689206873
resNode: customer_4 deliver_cap: 34.226877389782516 cap_limit: 40
260 customer_1 ('customer_1', 'customer_5')
62 customer_1 -5.162074689206873
resNode: customer_5 deliver_cap: 27.397953198252317 cap_limit: 40
261 customer_2 ('customer_2', 'customer_3')
64 customer_2 -4.854682274296852
resNode: customer_3 deliver_cap: 31.075577111846613 cap_limit: 40
262 customer_2 ('customer_2', 'customer_1')
64 customer_2 -4.854682274296852
resNode: customer_1 deliver_cap: 21.337710617407016 cap_limit: 40
263 customer_2 ('customer_2', 'depot_t')
64 customer_2 -4.854682274296852
resNode: depot_t deliver_cap: 12.474017886131854 cap_limit: 40
264 customer_2 ('customer_2', 'customer_4')
64 customer_2 -4.854682274296852
resNode: customer_4 deliver_cap: 30.952692314090573 cap_limit: 40
265 customer_2 ('customer_2', 'customer_5')
64 customer_2 -4.854682274296852
resNode: customer_5 deliver_cap: 21.63657450350683 cap_limit: 40
266 customer_5 ('customer_5', 'customer_3')
65 customer_5 -11.167777926431476
resNode: customer_3 deliver_cap: 37.916584214264155 cap_limit: 40
267 customer_5 ('customer_5', 'customer_1')
65 customer_5 -11.167777926431476
resNode: customer_1 deliver_cap: 29.76052293158584 cap_limit: 40
268 customer_5 ('customer_5', 'depot_t')
65 customer_5 -11.167777926431476
resNode: depot_t deliver_cap: 17.754840570061685 cap_limit: 40
269 customer_5 ('customer_5', 'customer_2')
65 customer_5 -11.167777926431476
resNode: customer_2 deliver_cap: 20.790029810219757 cap_limit: 40
270 customer_5 ('customer_5', 'customer_4')
65 customer_5 -11.167777926431476
resNode: customer_4 deliver_cap: 37.75683397718131 cap_limit: 40
271 customer_3 ('customer_3', 'customer_1')
66 customer_3 -10.001968701522166
resNode: customer_1 deliver_cap: 30.0687537830889 cap_limit: 40
272 customer_3 ('customer_3', 'depot_t')
66 customer_3 -10.001968701522166
resNode: depot_t deliver_cap: 20.10391114519031 cap_limit: 40
273 customer_3 ('customer_3', 'customer_2')
66 customer_3 -10.001968701522166
resNode: customer_2 deliver_cap: 23.400108227029335 cap_limit: 40
274 customer_3 ('customer_3', 'customer_4')
66 customer_3 -10.001968701522166
resNode: customer_4 deliver_cap: 32.282368812814155 cap_limit: 40
275 customer_3 ('customer_3', 'customer_5')
66 customer_3 -10.001968701522166
resNode: customer_5 deliver_cap: 29.03898276527489 cap_limit: 40
276 customer_1 ('customer_1', 'customer_3')
67 customer_1 -6.402139410648316
resNode: customer_3 deliver_cap: 30.193377668808928 cap_limit: 40
277 customer_1 ('customer_1', 'depot_t')
67 customer_1 -6.402139410648316
resNode: depot_t deliver_cap: 13.758959244033381 cap_limit: 40
278 customer_1 ('customer_1', 'customer_2')
67 customer_1 -6.402139410648316
resNode: customer_2 deliver_cap: 16.052119118038945 cap_limit: 40
279 customer_1 ('customer_1', 'customer_4')
67 customer_1 -6.402139410648316
resNode: customer_4 deliver_cap: 29.88514681730586 cap_limit: 40
280 customer_1 ('customer_1', 'customer_5')
67 customer_1 -6.402139410648316
resNode: customer_5 deliver_cap: 23.05622262577566 cap_limit: 40
281 customer_2 ('customer_2', 'customer_3')
69 customer_2 -5.472948590974908
resNode: customer_3 deliver_cap: 24.24665292031641 cap_limit: 40
282 customer_2 ('customer_2', 'customer_1')
69 customer_2 -5.472948590974908
resNode: customer_1 deliver_cap: 16.557463683335875 cap_limit: 40
283 customer_2 ('customer_2', 'depot_t')
69 customer_2 -5.472948590974908
resNode: depot_t deliver_cap: 8.376663371213734 cap_limit: 40
284 customer_2 ('customer_2', 'customer_4')
69 customer_2 -5.472948590974908
resNode: customer_4 deliver_cap: 24.123768122560378 cap_limit: 40
285 customer_2 ('customer_2', 'customer_5')
69 customer_2 -5.472948590974908
resNode: customer_5 deliver_cap: 14.80765031197663 cap_limit: 40
286 customer_4 ('customer_4', 'customer_3')
70 customer_4 -9.990704261727862
resNode: customer_3 deliver_cap: 32.282368812814155 cap_limit: 40
287 customer_4 ('customer_4', 'customer_1')
70 customer_4 -9.990704261727862
resNode: customer_1 deliver_cap: 29.760522931585832 cap_limit: 40
288 customer_4 ('customer_4', 'depot_t')
70 customer_4 -9.990704261727862
resNode: depot_t deliver_cap: 19.993314827209872 cap_limit: 40
289 customer_4 ('customer_4', 'customer_2')
70 customer_4 -9.990704261727862
resNode: customer_2 deliver_cap: 23.2772234292733 cap_limit: 40
290 customer_4 ('customer_4', 'customer_5')
70 customer_4 -9.990704261727862
resNode: customer_5 deliver_cap: 28.879232528192038 cap_limit: 40
291 customer_1 ('customer_1', 'customer_3')
71 customer_1 -1.3527941536534869
resNode: customer_3 deliver_cap: 28.36003959047611 cap_limit: 40
292 customer_1 ('customer_1', 'depot_t')
71 customer_1 -1.3527941536534869
resNode: depot_t deliver_cap: 12.658956397033691 cap_limit: 40
293 customer_1 ('customer_1', 'customer_2')
71 customer_1 -1.3527941536534869
resNode: customer_2 deliver_cap: 14.768782463205973 cap_limit: 40
294 customer_1 ('customer_1', 'customer_4')
71 customer_1 -1.3527941536534869
resNode: customer_4 deliver_cap: 28.051808738973047 cap_limit: 40
295 customer_1 ('customer_1', 'customer_5')
71 customer_1 -1.3527941536534869
resNode: customer_5 deliver_cap: 21.222884547442845 cap_limit: 40
296 customer_2 ('customer_2', 'customer_3')
73 customer_2 -0.9990652253067089
resNode: customer_3 deliver_cap: 24.715162407290116 cap_limit: 40
297 customer_2 ('customer_2', 'customer_1')
73 customer_2 -0.9990652253067089
resNode: customer_1 deliver_cap: 16.88542032421747 cap_limit: 40
298 customer_2 ('customer_2', 'depot_t')
73 customer_2 -0.9990652253067089
resNode: depot_t deliver_cap: 8.657769063397957 cap_limit: 40
299 customer_2 ('customer_2', 'customer_4')
73 customer_2 -0.9990652253067089
resNode: customer_4 deliver_cap: 24.59227760953408 cap_limit: 40
300 customer_2 ('customer_2', 'customer_5')
73 customer_2 -0.9990652253067089
resNode: customer_5 deliver_cap: 15.276159798950335 cap_limit: 40
301 customer_4 ('customer_4', 'customer_3')
74 customer_4 -1.429258537223072
resNode: customer_3 deliver_cap: 24.023864039660374 cap_limit: 40
302 customer_4 ('customer_4', 'customer_1')
74 customer_4 -1.429258537223072
resNode: customer_1 deliver_cap: 23.407826952236768 cap_limit: 40
303 customer_4 ('customer_4', 'depot_t')
74 customer_4 -1.429258537223072
resNode: depot_t deliver_cap: 14.275888445795715 cap_limit: 40
304 customer_4 ('customer_4', 'customer_2')
74 customer_4 -1.429258537223072
resNode: customer_2 deliver_cap: 16.924527449924234 cap_limit: 40
305 customer_4 ('customer_4', 'customer_5')
74 customer_4 -1.429258537223072
resNode: customer_5 deliver_cap: 20.620727755038256 cap_limit: 40
306 customer_5 ('customer_5', 'customer_3')
75 customer_5 -4.927005363232646
resNode: customer_3 deliver_cap: 29.648045098340706 cap_limit: 40
307 customer_5 ('customer_5', 'customer_1')
75 customer_5 -4.927005363232646
resNode: customer_1 deliver_cap: 23.400108227029335 cap_limit: 40
308 customer_5 ('customer_5', 'depot_t')
75 customer_5 -4.927005363232646
resNode: depot_t deliver_cap: 12.030467335960838 cap_limit: 40
309 customer_5 ('customer_5', 'customer_2')
75 customer_5 -4.927005363232646
resNode: customer_2 deliver_cap: 14.42961510566326 cap_limit: 40
310 customer_5 ('customer_5', 'customer_4')
75 customer_5 -4.927005363232646
resNode: customer_4 deliver_cap: 29.488294861257856 cap_limit: 40
311 customer_3 ('customer_3', 'customer_1')
76 customer_3 -3.028467188997511
resNode: customer_1 deliver_cap: 19.43683435244767 cap_limit: 40
312 customer_3 ('customer_3', 'depot_t')
76 customer_3 -3.028467188997511
resNode: depot_t deliver_cap: 12.021498890942961 cap_limit: 40
313 customer_3 ('customer_3', 'customer_2')
76 customer_3 -3.028467188997511
resNode: customer_2 deliver_cap: 14.768782463205973 cap_limit: 40
314 customer_3 ('customer_3', 'customer_4')
76 customer_3 -3.028467188997511
resNode: customer_4 deliver_cap: 22.53074382916591 cap_limit: 40

resNode: customer_5 deliver_cap: 20.914653695939784 cap_limit: 40
341 customer_2 ('customer_2', 'customer_3')
84 customer_2 -0.9847286655685055
resNode: customer_3 deliver_cap: 24.59227760953408 cap_limit: 40
342 customer_2 ('customer_2', 'customer_1')
84 customer_2 -0.9847286655685055
resNode: customer_1 deliver_cap: 16.799400965788244 cap_limit: 40
343 customer_2 ('customer_2', 'depot_t')
84 customer_2 -0.9847286655685055
resNode: depot_t deliver_cap: 8.584038184744335 cap_limit: 40
344 customer_2 ('customer_2', 'customer_4')
84 customer_2 -0.9847286655685055
resNode: customer_4 deliver_cap: 24.469392811778043 cap_limit: 40
345 customer_2 ('customer_2', 'customer_5')
84 customer_2 -0.9847286655685055
resNode: customer_5 deliver_cap: 15.153275001194297 cap_limit: 40
346 customer_5 ('customer_5', 'customer_3')
85 customer_5 -4.866587004335929
resNode: customer_3 deliver_cap: 29.48829486125786 cap_limit: 40
347 customer_5 ('customer_5', 'customer_1')
85 customer_5 -4.866587004335929
resNode: customer_1 deliver_cap: 23.277223429273306 cap_limit: 40
348 customer_5 ('customer_5', 'depot_t')
85 customer_5 -4.866587004335929
resNode: depot_t deliver_cap: 11.919871017980405 cap_limit: 40
349 customer_5 ('customer_5', 'customer_2')
85 customer_5 -4.866587004335929
resNode: customer_2 deliver_cap: 14.306730307907225 cap_limit: 40
350 customer_5 ('customer_5', 'customer_4')
85 customer_5 -4.866587004335929
resNode: customer_4 deliver_cap: 29.328544624175017 cap_limit: 40
351 customer_3 ('customer_3', 'customer_1')
86 customer_3 -1.1514043198967336
resNode: customer_1 deliver_cap: 21.09826066172282 cap_limit: 40
352 customer_3 ('customer_3', 'depot_t')
86 customer_3 -1.1514043198967336
resNode: depot_t deliver_cap: 12.03046733596084 cap_limit: 40
353 customer_3 ('customer_3', 'customer_2')
86 customer_3 -1.1514043198967336
resNode: customer_2 deliver_cap: 14.429615105663263 cap_limit: 40
354 customer_3 ('customer_3', 'customer_4')
86 customer_3 -1.1514043198967336
resNode: customer_4 deliver_cap: 20.620727755038256 cap_limit: 40
355 customer_3 ('customer_3', 'customer_5')
86 customer_3 -1.1514043198967336
resNode: customer_5 deliver_cap: 17.37734170749899 cap_limit: 40
356 customer_1 ('customer_1', 'customer_3')
87 customer_1 -0.9155099495351628
resNode: customer_3 deliver_cap: 21.222884547442845 cap_limit: 40
357 customer_1 ('customer_1', 'depot_t')
87 customer_1 -0.9155099495351628
resNode: depot_t deliver_cap: 8.376663371213734 cap_limit: 40
358 customer_1 ('customer_1', 'customer_2')
87 customer_1 -0.9155099495351628
resNode: customer_2 deliver_cap: 9.772773933082691 cap_limit: 40
359 customer_1 ('customer_1', 'customer_4')
87 customer_1 -0.9155099495351628
resNode: customer_4 deliver_cap: 20.91465369593978 cap_limit: 40
360 customer_1 ('customer_1', 'customer_5')
87 customer_1 -0.9155099495351628
resNode: customer_5 deliver_cap: 14.085729504409585 cap_limit: 40
361 customer_2 ('customer_2', 'customer_3')
89 customer_2 0.013680870138246037
resNode: customer_3 deliver_cap: 15.276159798950335 cap_limit: 40
362 customer_2 ('customer_2', 'customer_1')
89 customer_2 0.013680870138246037
resNode: customer_1 deliver_cap: 10.278118498379621 cap_limit: 40
363 customer_2 ('customer_2', 'depot_t')
89 customer_2 0.013680870138246037
resNode: depot_t deliver_cap: 2.994367498394086 cap_limit: 40
364 customer_2 ('customer_2', 'customer_4')
89 customer_2 0.013680870138246037
resNode: customer_4 deliver_cap: 15.153275001194295 cap_limit: 40
365 customer_2 ('customer_2', 'customer_5')
89 customer_2 0.013680870138246037
resNode: customer_5 deliver_cap: 5.837157190610549 cap_limit: 40
366 customer_4 ('customer_4', 'customer_3')
90 customer_4 -1.1401398801024298
resNode: customer_3 deliver_cap: 20.620727755038253 cap_limit: 40
367 customer_4 ('customer_4', 'customer_1')
90 customer_4 -1.1401398801024298
resNode: customer_1 deliver_cap: 20.790029810219753 cap_limit: 40
368 customer_4 ('customer_4', 'depot_t')
90 customer_4 -1.1401398801024298
resNode: depot_t deliver_cap: 11.919871017980403 cap_limit: 40
369 customer_4 ('customer_4', 'customer_2')
90 customer_4 -1.1401398801024298
resNode: customer_2 deliver_cap: 14.306730307907223 cap_limit: 40
370 customer_4 ('customer_4', 'customer_5')
90 customer_4 -1.1401398801024298
resNode: customer_5 deliver_cap: 17.217591470416135 cap_limit: 40
371 customer_1 ('customer_1', 'customer_3')
91 customer_1 -2.662084586306378
resNode: customer_3 deliver_cap: 38.730279585294966 cap_limit: 40
372 customer_1 ('customer_1', 'depot_t')
91 customer_1 -2.662084586306378
resNode: depot_t deliver_cap: 20.27766944624932 cap_limit: 40
373 customer_1 ('customer_1', 'customer_2')
91 customer_1 -2.662084586306378
resNode: customer_2 deliver_cap: 22.53074382916591 cap_limit: 40
374 customer_1 ('customer_1', 'customer_4')
91 customer_1 -2.662084586306378
resNode: customer_4 deliver_cap: 38.329579478340975 cap_limit: 40
375 customer_1 ('customer_1', 'customer_5')
91 customer_1 -2.662084586306378
resNode: customer_5 deliver_cap: 29.451978029351714 cap_limit: 40
376 customer_2 ('customer_2', 'customer_3')
93 customer_2 -1.8082072412551327
resNode: customer_3 deliver_cap: 33.99193924715317 cap_limit: 40
377 customer_2 ('customer_2', 'customer_1')
93 customer_2 -1.8082072412551327
resNode: customer_1 deliver_cap: 25.554512202039472 cap_limit: 40
378 customer_2 ('customer_2', 'depot_t')
93 customer_2 -1.8082072412551327
resNode: depot_t deliver_cap: 14.275888445795715 cap_limit: 40
379 customer_2 ('customer_2', 'customer_4')
93 customer_2 -1.8082072412551327
resNode: customer_4 deliver_cap: 33.83218901007032 cap_limit: 40
380 customer_2 ('customer_2', 'customer_5')
93 customer_2 -1.8082072412551327
resNode: customer_5 deliver_cap: 21.721235856311452 cap_limit: 40
381 customer_4 ('customer_4', 'customer_3')
94 customer_4 -2.8830179785208854
resNode: customer_3 deliver_cap: 31.859805732106324 cap_limit: 40
382 customer_4 ('customer_4', 'customer_1')
94 customer_4 -2.8830179785208854
resNode: customer_1 deliver_cap: 32.29240315558381 cap_limit: 40
383 customer_4 ('customer_4', 'depot_t')
94 customer_4 -2.8830179785208854
resNode: depot_t deliver_cap: 20.75349772865933 cap_limit: 40
384 customer_4 ('customer_4', 'customer_2')
94 customer_4 -2.8830179785208854
resNode: customer_2 deliver_cap: 23.864113802577524 cap_limit: 40
385 customer_4 ('customer_4', 'customer_5')
94 customer_4 -2.8830179785208854
resNode: customer_5 deliver_cap: 27.671330304879103 cap_limit: 40
386 customer_5 ('customer_5', 'customer_3')
95 customer_5 -6.193646378710889
resNode: customer_3 deliver_cap: 38.7818747274052 cap_limit: 40
387 customer_5 ('customer_5', 'customer_1')
95 customer_5 -6.193646378710889
resNode: customer_1 deliver_cap: 32.28236881281416 cap_limit: 40
388 customer_5 ('customer_5', 'depot_t')
95 customer_5 -6.193646378710889
resNode: depot_t deliver_cap: 17.75960291554616 cap_limit: 40
389 customer_5 ('customer_5', 'customer_2')
95 customer_5 -6.193646378710889
resNode: customer_2 deliver_cap: 20.62072775503826 cap_limit: 40
390 customer_5 ('customer_5', 'customer_4')
95 customer_5 -6.193646378710889
resNode: customer_4 deliver_cap: 38.585259050995546 cap_limit: 40
391 customer_3 ('customer_3', 'customer_1')
96 customer_3 -8.260847492999233
resNode: customer_1 deliver_cap: 34.7204542950326 cap_limit: 40
392 customer_3 ('customer_3', 'depot_t')
96 customer_3 -8.260847492999233
resNode: depot_t deliver_cap: 24.290441605939645 cap_limit: 40
393 customer_3 ('customer_3', 'customer_2')
96 customer_3 -8.260847492999233
resNode: customer_2 deliver_cap: 28.051808738973044 cap_limit: 40
394 customer_3 ('customer_3', 'customer_4')
96 customer_3 -8.260847492999233
resNode: customer_4 deliver_cap: 38.329579478340975 cap_limit: 40
395 customer_3 ('customer_3', 'customer_5')
96 customer_3 -8.260847492999233
resNode: customer_5 deliver_cap: 35.08619343080171 cap_limit: 40
396 customer_2 ('customer_2', 'customer_3')
98 customer_2 -2.266138316165236
resNode: customer_3 deliver_cap: 30.013147935028726 cap_limit: 40
397 customer_2 ('customer_2', 'customer_1')
98 customer_2 -2.266138316165236
resNode: customer_1 deliver_cap: 20.594010193634496 cap_limit: 40
398 customer_2 ('customer_2', 'depot_t')
98 customer_2 -2.266138316165236
resNode: depot_t deliver_cap: 11.83656038004112 cap_limit: 40
399 customer_2 ('customer_2', 'customer_4')
98 customer_2 -2.266138316165236
resNode: customer_4 deliver_cap: 29.89026313727269 cap_limit: 40
400 customer_2 ('customer_2', 'customer_5')
98 customer_2 -2.266138316165236
resNode: customer_5 deliver_cap: 20.57414532668894 cap_limit: 40
401 customer_4 ('customer_4', 'customer_3')
99 customer_4 -8.133741769613039
resNode: customer_3 deliver_cap: 38.08862960846984 cap_limit: 40
402 customer_4 ('customer_4', 'customer_1')
99 customer_4 -8.133741769613039
resNode: customer_1 deliver_cap: 34.226877389782516 cap_limit: 40
403 customer_4 ('customer_4', 'depot_t')
99 customer_4 -8.133741769613039
resNode: depot_t deliver_cap: 24.013033839586885 cap_limit: 40
404 customer_4 ('customer_4', 'customer_2')
99 customer_4 -8.133741769613039
resNode: customer_2 deliver_cap: 27.743577887469975 cap_limit: 40
405 customer_4 ('customer_4', 'customer_5')
99 customer_4 -8.133741769613039
resNode: customer_5 deliver_cap: 34.68549332384772 cap_limit: 40
406 customer_5 ('customer_5', 'customer_3')
100 customer_5 -8.922731191079347
resNode: customer_3 deliver_cap: 38.07859526570018 cap_limit: 40
407 customer_5 ('customer_5', 'customer_1')
100 customer_5 -8.922731191079347
resNode: customer_1 deliver_cap: 29.88514681730586 cap_limit: 40
408 customer_5 ('customer_5', 'depot_t')
100 customer_5 -8.922731191079347
resNode: depot_t deliver_cap: 17.867002067209707 cap_limit: 40
409 customer_5 ('customer_5', 'customer_2')
100 customer_5 -8.922731191079347
resNode: customer_2 deliver_cap: 20.91465369593978 cap_limit: 40
410 customer_5 ('customer_5', 'customer_4')
100 customer_5 -8.922731191079347
resNode: customer_4 deliver_cap: 37.91884502861733 cap_limit: 40
411 customer_3 ('customer_3', 'customer_1')
101 customer_3 -6.763743047536735
resNode: customer_1 deliver_cap: 31.26092316559364 cap_limit: 40
412 customer_3 ('customer_3', 'depot_t')
101 customer_3 -6.763743047536735
resNode: depot_t deliver_cap: 21.176863589444576 cap_limit: 40
413 customer_3 ('customer_3', 'customer_2')
101 customer_3 -6.763743047536735
resNode: customer_2 deliver_cap: 24.592277609534076 cap_limit: 40
414 customer_3 ('customer_3', 'customer_4')
101 customer_3 -6.763743047536735
resNode: customer_4 deliver_cap: 33.83218901007032 cap_limit: 40
415 customer_3 ('customer_3', 'customer_5')
101 customer_3 -6.763743047536735
resNode: customer_5 deliver_cap: 30.58880296253105 cap_limit: 40
416 customer_1 ('customer_1', 'customer_3')
102 customer_1 -2.4200869725891314
resNode: customer_3 deliver_cap: 30.198493988775752 cap_limit: 40
417 customer_1 ('customer_1', 'depot_t')
102 customer_1 -2.4200869725891314
resNode: depot_t deliver_cap: 13.762029036013477 cap_limit: 40
418 customer_1 ('customer_1', 'customer_2')
102 customer_1 -2.4200869725891314
resNode: customer_2 deliver_cap: 16.05570054201572 cap_limit: 40
419 customer_1 ('customer_1', 'customer_4')
102 customer_1 -2.4200869725891314
resNode: customer_4 deliver_cap: 29.89026313727269 cap_limit: 40
420 customer_1 ('customer_1', 'customer_5')
102 customer_1 -2.4200869725891314
resNode: customer_5 deliver_cap: 23.061338945742488 cap_limit: 40
421 customer_4 ('customer_4', 'customer_3')
104 customer_4 -6.752478607742432
resNode: customer_3 deliver_cap: 33.83218901007032 cap_limit: 40
422 customer_4 ('customer_4', 'customer_1')
104 customer_4 -6.752478607742432
resNode: customer_1 deliver_cap: 30.952692314090573 cap_limit: 40
423 customer_4 ('customer_4', 'depot_t')
104 customer_4 -6.752478607742432
resNode: depot_t deliver_cap: 21.06626727146414 cap_limit: 40
424 customer_4 ('customer_4', 'customer_2')
104 customer_4 -6.752478607742432
resNode: customer_2 deliver_cap: 24.469392811778043 cap_limit: 40
425 customer_4 ('customer_4', 'customer_5')
104 customer_4 -6.752478607742432
resNode: customer_5 deliver_cap: 30.4290527254482 cap_limit: 40
426 customer_5 ('customer_5', 'customer_3')
105 customer_5 -5.986972017300278
resNode: customer_3 deliver_cap: 30.58880296253105 cap_limit: 40
427 customer_5 ('customer_5', 'customer_1')
105 customer_5 -5.986972017300278
resNode: customer_1 deliver_cap: 24.123768122560378 cap_limit: 40
428 customer_5 ('customer_5', 'depot_t')
105 customer_5 -5.986972017300278
resNode: depot_t deliver_cap: 12.681761241938771 cap_limit: 40
429 customer_5 ('customer_5', 'customer_2')
105 customer_5 -5.986972017300278
resNode: customer_2 deliver_cap: 15.153275001194297 cap_limit: 40
430 customer_5 ('customer_5', 'customer_4')
105 customer_5 -5.986972017300278
resNode: customer_4 deliver_cap: 30.429052725448205 cap_limit: 40
431 customer_3 ('customer_3', 'customer_1')
106 customer_3 -9.921371348330023
resNode: customer_1 deliver_cap: 38.157534084135285 cap_limit: 40
432 customer_3 ('customer_3', 'depot_t')
106 customer_3 -9.921371348330023
resNode: depot_t deliver_cap: 25.945049475133484 cap_limit: 40
433 customer_3 ('customer_3', 'customer_2')
106 customer_3 -9.921371348330023
resNode: customer_2 deliver_cap: 29.488294861257856 cap_limit: 40
434 customer_3 ('customer_3', 'customer_4')
106 customer_3 -9.921371348330023
resNode: customer_4 deliver_cap: 38.58525905099554 cap_limit: 40
435 customer_3 ('customer_3', 'customer_5')
106 customer_3 -9.921371348330023
resNode: customer_5 deliver_cap: 34.59339930017798 cap_limit: 40
436 customer_1 ('customer_1', 'customer_3')
107 customer_1 -6.634887717044567
resNode: customer_3 deliver_cap: 38.31954513557132 cap_limit: 40
437 customer_1 ('customer_1', 'depot_t')
107 customer_1 -6.634887717044567
resNode: depot_t deliver_cap: 19.993314827209872 cap_limit: 40
438 customer_1 ('customer_1', 'customer_2')
107 customer_1 -6.634887717044567
resNode: customer_2 deliver_cap: 22.214794252455413 cap_limit: 40
439 customer_1 ('customer_1', 'customer_4')
107 customer_1 -6.634887717044567
resNode: customer_4 deliver_cap: 37.91884502861733 cap_limit: 40
440 customer_1 ('customer_1', 'customer_5')
107 customer_1 -6.634887717044567
resNode: customer_5 deliver_cap: 29.041243579628073 cap_limit: 40
441 customer_2 ('customer_2', 'customer_3')
109 customer_2 -5.032909913268703
resNode: customer_3 deliver_cap: 30.58880296253105 cap_limit: 40
442 customer_2 ('customer_2', 'customer_1')
109 customer_2 -5.032909913268703
resNode: customer_1 deliver_cap: 22.93671506002246 cap_limit: 40
443 customer_2 ('customer_2', 'depot_t')
109 customer_2 -5.032909913268703
resNode: depot_t deliver_cap: 11.919871017980403 cap_limit: 40
444 customer_2 ('customer_2', 'customer_4')
109 customer_2 -5.032909913268703
resNode: customer_4 deliver_cap: 30.429052725448205 cap_limit: 40
445 customer_2 ('customer_2', 'customer_5')
109 customer_2 -5.032909913268703
resNode: customer_5 deliver_cap: 18.318099571689334 cap_limit: 40
446 customer_4 ('customer_4', 'customer_3')
110 customer_4 -9.900890548704016
resNode: customer_3 deliver_cap: 38.58525905099554 cap_limit: 40
447 customer_4 ('customer_4', 'customer_1')
110 customer_4 -9.900890548704016
resNode: customer_1 deliver_cap: 37.7568339771813 cap_limit: 40
448 customer_4 ('customer_4', 'depot_t')
110 customer_4 -9.900890548704016
resNode: depot_t deliver_cap: 25.797587717826236 cap_limit: 40
449 customer_4 ('customer_4', 'customer_2')
110 customer_4 -9.900890548704016
resNode: customer_2 deliver_cap: 29.328544624175002 cap_limit: 40
450 customer_4 ('customer_4', 'customer_5')
110 customer_4 -9.900890548704016
resNode: customer_5 deliver_cap: 34.396783623768314 cap_limit: 40
451 customer_1 ('customer_1', 'customer_3')
111 customer_1 -2.183893053656356
resNode: customer_3 deliver_cap: 35.48689353775569 cap_limit: 40
452 customer_1 ('customer_1', 'depot_t')
111 customer_1 -2.183893053656356
resNode: depot_t deliver_cap: 18.03224833641444 cap_limit: 40
453 customer_1 ('customer_1', 'customer_2')
111 customer_1 -2.183893053656356
resNode: customer_2 deliver_cap: 20.035831484904936 cap_limit: 40
454 customer_1 ('customer_1', 'customer_4')
111 customer_1 -2.183893053656356
resNode: customer_4 deliver_cap: 35.086193430801714 cap_limit: 40
455 customer_1 ('customer_1', 'customer_5')
111 customer_1 -2.183893053656356
resNode: customer_5 deliver_cap: 26.208591981812454 cap_limit: 40
456 customer_2 ('customer_2', 'customer_3')
113 customer_2 -1.3300157086051108
resNode: customer_3 deliver_cap: 30.748553199613898 cap_limit: 40
457 customer_2 ('customer_2', 'customer_1')
113 customer_2 -1.3300157086051108
resNode: customer_1 deliver_cap: 23.0595998577785 cap_limit: 40
458 customer_2 ('customer_2', 'depot_t')
113 customer_2 -1.3300157086051108
resNode: depot_t deliver_cap: 12.030467335960838 cap_limit: 40
459 customer_2 ('customer_2', 'customer_4')
113 customer_2 -1.3300157086051108
resNode: customer_4 deliver_cap: 30.58880296253105 cap_limit: 40
460 customer_2 ('customer_2', 'customer_5')
113 customer_2 -1.3300157086051108
resNode: customer_5 deliver_cap: 18.47784980877218 cap_limit: 40
461 customer_4 ('customer_4', 'customer_3')
114 customer_4 -1.4692343167729989
resNode: customer_3 deliver_cap: 27.867945981288763 cap_limit: 40
462 customer_4 ('customer_4', 'customer_1')
114 customer_4 -1.4692343167729989
resNode: customer_1 deliver_cap: 29.049017108044545 cap_limit: 40
463 customer_4 ('customer_4', 'depot_t')
114 customer_4 -1.4692343167729989
resNode: depot_t deliver_cap: 17.75960291554616 cap_limit: 40
464 customer_4 ('customer_4', 'customer_2')
114 customer_4 -1.4692343167729989
resNode: customer_2 deliver_cap: 20.620727755038256 cap_limit: 40
465 customer_4 ('customer_4', 'customer_5')
114 customer_4 -1.4692343167729989

resNode: customer_5 deliver_cap: 23.67947055406154 cap_limit: 40
466 customer_5 ('customer_5', 'customer_3')
115 customer_5 -4.779862716963002
resNode: customer_3 deliver_cap: 34.79001497658764 cap_limit: 40
467 customer_5 ('customer_5', 'customer_1')
115 customer_5 -4.779862716963002
resNode: customer_1 deliver_cap: 29.03898276527489 cap_limit: 40
468 customer_5 ('customer_5', 'depot_t')
115 customer_5 -4.779862716963002
resNode: depot_t deliver_cap: 14.765708102432992 cap_limit: 40
469 customer_5 ('customer_5', 'customer_2')
115 customer_5 -4.779862716963002
resNode: customer_2 deliver_cap: 17.377341707498992 cap_limit: 40
470 customer_5 ('customer_5', 'customer_4')
115 customer_5 -4.779862716963002
resNode: customer_4 deliver_cap: 34.59339930017798 cap_limit: 40
471 customer_3 ('customer_3', 'customer_1')
116 customer_3 -4.640497371079026
resNode: customer_1 deliver_cap: 27.891530103502408 cap_limit: 40
472 customer_3 ('customer_3', 'depot_t')
116 customer_3 -4.640497371079026
resNode: depot_t deliver_cap: 18.144409833562467 cap_limit: 40
473 customer_3 ('customer_3', 'customer_2')
116 customer_3 -4.640497371079026
resNode: customer_2 deliver_cap: 21.222884547442845 cap_limit: 40
474 customer_3 ('customer_3', 'customer_4')
116 customer_3 -4.640497371079026
resNode: customer_4 deliver_cap: 29.45197802935172 cap_limit: 40
475 customer_3 ('customer_3', 'customer_5')
116 customer_3 -4.640497371079026
resNode: customer_5 deliver_cap: 26.208591981812454 cap_limit: 40
476 customer_2 ('customer_2', 'customer_3')
118 customer_2 -1.2066347660688537
resNode: customer_3 deliver_cap: 23.184223743498528 cap_limit: 40
477 customer_2 ('customer_2', 'customer_1')
118 customer_2 -1.2066347660688537
resNode: customer_1 deliver_cap: 15.813763259563357 cap_limit: 40
478 customer_2 ('customer_2', 'depot_t')
118 customer_2 -1.2066347660688537
resNode: depot_t deliver_cap: 7.739205865123004 cap_limit: 40
479 customer_2 ('customer_2', 'customer_4')
118 customer_2 -1.2066347660688537
resNode: customer_4 deliver_cap: 23.06133894574249 cap_limit: 40
480 customer_2 ('customer_2', 'customer_5')
118 customer_2 -1.2066347660688537
resNode: customer_5 deliver_cap: 13.745221135158745 cap_limit: 40
481 customer_4 ('customer_4', 'customer_3')
119 customer_4 -4.51339164769283
resNode: customer_3 deliver_cap: 29.211028159480588 cap_limit: 40
482 customer_4 ('customer_4', 'customer_1')
119 customer_4 -4.51339164769283
resNode: customer_1 deliver_cap: 27.397953198252317 cap_limit: 40
483 customer_4 ('customer_4', 'depot_t')
119 customer_4 -4.51339164769283
resNode: depot_t deliver_cap: 17.86700206720971 cap_limit: 40
484 customer_4 ('customer_4', 'customer_2')
119 customer_4 -4.51339164769283
resNode: customer_2 deliver_cap: 20.914653695939784 cap_limit: 40
485 customer_4 ('customer_4', 'customer_5')
119 customer_4 -4.51339164769283
resNode: customer_5 deliver_cap: 25.80789187485847 cap_limit: 40
486 customer_5 ('customer_5', 'customer_3')
120 customer_5 -5.302381069159141
resNode: customer_3 deliver_cap: 29.200993816710927 cap_limit: 40
487 customer_5 ('customer_5', 'customer_1')
120 customer_5 -5.302381069159141
resNode: customer_1 deliver_cap: 23.056222625775664 cap_limit: 40
488 customer_5 ('customer_5', 'depot_t')
120 customer_5 -5.302381069159141
resNode: depot_t deliver_cap: 11.72097029483253 cap_limit: 40
489 customer_5 ('customer_5', 'customer_2')
120 customer_5 -5.302381069159141
resNode: customer_2 deliver_cap: 14.085729504409585 cap_limit: 40
490 customer_5 ('customer_5', 'customer_4')
120 customer_5 -5.302381069159141
resNode: customer_4 deliver_cap: 29.04124357962808 cap_limit: 40
491 customer_3 ('customer_3', 'customer_1')
121 customer_3 -1.3401775518027068
resNode: customer_1 deliver_cap: 21.944805355009894 cap_limit: 40
492 customer_3 ('customer_3', 'depot_t')
121 customer_3 -1.3401775518027068
resNode: depot_t deliver_cap: 12.792357559919203 cap_limit: 40
493 customer_3 ('customer_3', 'customer_2')
121 customer_3 -1.3401775518027068
resNode: customer_2 deliver_cap: 15.276159798950333 cap_limit: 40
494 customer_3 ('customer_3', 'customer_4')
121 customer_3 -1.3401775518027068
resNode: customer_4 deliver_cap: 21.721235856311452 cap_limit: 40
495 customer_3 ('customer_3', 'customer_5')
121 customer_3 -1.3401775518027068
resNode: customer_5 deliver_cap: 18.477849808772184 cap_limit: 40
496 customer_1 ('customer_1', 'customer_3')
122 customer_1 -0.4900656558240065
resNode: customer_3 deliver_cap: 20.882376178192004 cap_limit: 40
497 customer_1 ('customer_1', 'depot_t')
122 customer_1 -0.4900656558240065
resNode: depot_t deliver_cap: 8.17235834966323 cap_limit: 40
498 customer_1 ('customer_1', 'customer_2')
122 customer_1 -0.4900656558240065
resNode: customer_2 deliver_cap: 9.534418074607101 cap_limit: 40
499 customer_1 ('customer_1', 'customer_4')
122 customer_1 -0.4900656558240065
resNode: customer_4 deliver_cap: 20.574145326688942 cap_limit: 40
500 customer_1 ('customer_1', 'customer_5')
122 customer_1 -0.4900656558240065
resNode: customer_5 deliver_cap: 13.745221135158745 cap_limit: 40
501 customer_4 ('customer_4', 'customer_3')
124 customer_4 -1.3289131120084043
resNode: customer_3 deliver_cap: 21.721235856311452 cap_limit: 40
502 customer_4 ('customer_4', 'customer_1')
124 customer_4 -1.3289131120084043
resNode: customer_1 deliver_cap: 21.63657450350683 cap_limit: 40
503 customer_4 ('customer_4', 'depot_t')
124 customer_4 -1.3289131120084043
resNode: depot_t deliver_cap: 12.681761241938771 cap_limit: 40
504 customer_4 ('customer_4', 'customer_2')
124 customer_4 -1.3289131120084043
resNode: customer_2 deliver_cap: 15.153275001194297 cap_limit: 40
505 customer_4 ('customer_4', 'customer_5')
124 customer_4 -1.3289131120084043
resNode: customer_5 deliver_cap: 18.318099571689334 cap_limit: 40
506 customer_5 ('customer_5', 'customer_3')
125 customer_5 -0.5634065215662466
resNode: customer_3 deliver_cap: 18.47784980877218 cap_limit: 40
507 customer_5 ('customer_5', 'customer_1')
125 customer_5 -0.5634065215662466
resNode: customer_1 deliver_cap: 14.807650311976628 cap_limit: 40
508 customer_5 ('customer_5', 'depot_t')
125 customer_5 -0.5634065215662466
resNode: depot_t deliver_cap: 4.297255212413398 cap_limit: 40
509 customer_5 ('customer_5', 'customer_2')
125 customer_5 -0.5634065215662466
resNode: customer_2 deliver_cap: 5.837157190610549 cap_limit: 40
510 customer_5 ('customer_5', 'customer_4')
125 customer_5 -0.5634065215662466
resNode: customer_4 deliver_cap: 18.318099571689334 cap_limit: 40
511 customer_3 ('customer_3', 'customer_1')
126 customer_3 -1.420080397670583
resNode: customer_1 deliver_cap: 29.28996697791568 cap_limit: 40
512 customer_3 ('customer_3', 'depot_t')
126 customer_3 -1.420080397670583
resNode: depot_t deliver_cap: 17.75960291554616 cap_limit: 40
513 customer_3 ('customer_3', 'customer_2')
126 customer_3 -1.420080397670583
resNode: customer_2 deliver_cap: 20.620727755038256 cap_limit: 40
514 customer_3 ('customer_3', 'customer_4')
126 customer_3 -1.420080397670583
resNode: customer_4 deliver_cap: 27.671330304879103 cap_limit: 40
515 customer_3 ('customer_3', 'customer_5')
126 customer_3 -1.420080397670583
resNode: customer_5 deliver_cap: 23.67947055406154 cap_limit: 40
516 customer_1 ('customer_1', 'customer_3')
127 customer_1 -2.100102666618665
resNode: customer_3 deliver_cap: 35.08619343080171 cap_limit: 40
517 customer_1 ('customer_1', 'depot_t')
127 customer_1 -2.100102666618665
resNode: depot_t deliver_cap: 17.75484057006168 cap_limit: 40
518 customer_1 ('customer_1', 'customer_2')
127 customer_1 -2.100102666618665
resNode: customer_2 deliver_cap: 19.72760063340187 cap_limit: 40
519 customer_1 ('customer_1', 'customer_4')
127 customer_1 -2.100102666618665
resNode: customer_4 deliver_cap: 34.68549332384772 cap_limit: 40
520 customer_1 ('customer_1', 'customer_5')
127 customer_1 -2.100102666618665
resNode: customer_5 deliver_cap: 25.807891874858466 cap_limit: 40
521 customer_2 ('customer_2', 'customer_3')
129 customer_2 -1.3064627890352039
resNode: customer_3 deliver_cap: 30.58880296253105 cap_limit: 40
522 customer_2 ('customer_2', 'customer_1')
129 customer_2 -1.3064627890352039
resNode: customer_1 deliver_cap: 22.93671506002246 cap_limit: 40
523 customer_2 ('customer_2', 'depot_t')
129 customer_2 -1.3064627890352039
resNode: depot_t deliver_cap: 11.919871017980403 cap_limit: 40
524 customer_2 ('customer_2', 'customer_4')
129 customer_2 -1.3064627890352039
resNode: customer_4 deliver_cap: 30.429052725448205 cap_limit: 40
525 customer_2 ('customer_2', 'customer_5')
129 customer_2 -1.3064627890352039
resNode: customer_5 deliver_cap: 18.318099571689334 cap_limit: 40
526 customer_5 ('customer_5', 'customer_3')
130 customer_5 -4.710227998234578
resNode: customer_3 deliver_cap: 34.59339930017798 cap_limit: 40
527 customer_5 ('customer_5', 'customer_1')
130 customer_5 -4.710227998234578
resNode: customer_1 deliver_cap: 28.879232528192038 cap_limit: 40
528 customer_5 ('customer_5', 'depot_t')
130 customer_5 -4.710227998234578
resNode: depot_t deliver_cap: 14.618246345125744 cap_limit: 40
529 customer_5 ('customer_5', 'customer_2')
130 customer_5 -4.710227998234578
resNode: customer_2 deliver_cap: 17.21759147041614 cap_limit: 40
530 customer_5 ('customer_5', 'customer_4')
130 customer_5 -4.710227998234578
resNode: customer_4 deliver_cap: 34.396783623768314 cap_limit: 40
531 customer_1 ('customer_1', 'customer_3')
131 customer_1 -12.12544291214338
resNode: customer_3 deliver_cap: 59.206649705404544 cap_limit: 40
532 customer_1 ('customer_1', 'depot_t')
131 customer_1 -12.12544291214338
resNode: depot_t deliver_cap: 35.02868514653567 cap_limit: 40
533 customer_1 ('customer_1', 'customer_2')
131 customer_1 -12.12544291214338
resNode: customer_2 deliver_cap: 38.531553661189236 cap_limit: 40
534 customer_1 ('customer_1', 'customer_4')
131 customer_1 -12.12544291214338
resNode: customer_4 deliver_cap: 58.775126513300265 cap_limit: 40
535 customer_1 ('customer_1', 'customer_5')
131 customer_1 -12.12544291214338
resNode: customer_5 deliver_cap: 49.21463264515798 cap_limit: 40
536 customer_2 ('customer_2', 'customer_3')
133 customer_2 -11.104849428190647
resNode: customer_3 deliver_cap: 54.10382164894415 cap_limit: 40
537 customer_2 ('customer_2', 'customer_1')
133 customer_2 -11.104849428190647
resNode: customer_1 deliver_cap: 41.85769887135016 cap_limit: 40
538 customer_2 ('customer_2', 'depot_t')
133 customer_2 -11.104849428190647
resNode: depot_t deliver_cap: 28.36003959047611 cap_limit: 40
539 customer_2 ('customer_2', 'customer_4')
133 customer_2 -11.104849428190647
resNode: customer_4 deliver_cap: 53.931782932085696 cap_limit: 40
540 customer_2 ('customer_2', 'customer_5')
133 customer_2 -11.104849428190647
resNode: customer_5 deliver_cap: 40.88921799726845 cap_limit: 40
541 customer_4 ('customer_4', 'customer_3')
134 customer_4 -16.902200238656135
resNode: customer_3 deliver_cap: 55.097543829891556 cap_limit: 40
542 customer_4 ('customer_4', 'customer_1')
134 customer_4 -16.902200238656135
resNode: customer_1 deliver_cap: 52.27355201186946 cap_limit: 40
543 customer_4 ('customer_4', 'depot_t')
134 customer_4 -16.902200238656135
resNode: depot_t deliver_cap: 38.73027958529496 cap_limit: 40
544 customer_4 ('customer_4', 'customer_2')
134 customer_4 -16.902200238656135
resNode: customer_2 deliver_cap: 43.19693270863191 cap_limit: 40
545 customer_4 ('customer_4', 'customer_5')
134 customer_4 -16.902200238656135
resNode: customer_5 deliver_cap: 50.64728868846264 cap_limit: 40
546 customer_5 ('customer_5', 'customer_3')
135 customer_5 -20.150455830239615
resNode: customer_3 deliver_cap: 62.452242137396624 cap_limit: 40
547 customer_5 ('customer_5', 'customer_1')
135 customer_5 -20.150455830239615
resNode: customer_1 deliver_cap: 52.26274579657907 cap_limit: 40
548 customer_5 ('customer_5', 'depot_t')
135 customer_5 -20.150455830239615
resNode: depot_t deliver_cap: 35.48689353775569 cap_limit: 40
549 customer_5 ('customer_5', 'customer_2')
135 customer_5 -20.150455830239615
resNode: customer_2 deliver_cap: 39.70405542666656 cap_limit: 40
550 customer_5 ('customer_5', 'customer_4')
135 customer_5 -20.150455830239615
resNode: customer_4 deliver_cap: 62.243337981211354 cap_limit: 40
551 customer_3 ('customer_3', 'customer_1')
136 customer_3 -11.972270765796875
resNode: customer_1 deliver_cap: 41.85769887135016 cap_limit: 40
552 customer_3 ('customer_3', 'depot_t')
136 customer_3 -11.972270765796875
resNode: depot_t deliver_cap: 30.321378786531792 cap_limit: 40
553 customer_3 ('customer_3', 'customer_2')
136 customer_3 -11.972270765796875
resNode: customer_2 deliver_cap: 34.52218875968464 cap_limit: 40
554 customer_3 ('customer_3', 'customer_4')
136 customer_3 -11.972270765796875
resNode: customer_4 deliver_cap: 45.94280758310987 cap_limit: 40
555 customer_3 ('customer_3', 'customer_5')
136 customer_3 -11.972270765796875
resNode: customer_5 deliver_cap: 42.449930301144505 cap_limit: 40
556 customer_1 ('customer_1', 'customer_3')
137 customer_1 -5.066962473851078
resNode: customer_3 deliver_cap: 40.68902677685048 cap_limit: 40
557 customer_1 ('customer_1', 'depot_t')
137 customer_1 -5.066962473851078
resNode: depot_t deliver_cap: 20.809771789686643 cap_limit: 40
558 customer_1 ('customer_1', 'customer_2')
137 customer_1 -5.066962473851078
resNode: customer_2 deliver_cap: 23.782596331070447 cap_limit: 40
559 customer_1 ('customer_1', 'customer_4')
137 customer_1 -5.066962473851078
resNode: customer_4 deliver_cap: 40.34997284019711 cap_limit: 40
560 customer_1 ('customer_1', 'customer_5')
137 customer_1 -5.066962473851078
resNode: customer_5 deliver_cap: 32.83815622951389 cap_limit: 40
561 customer_4 ('customer_4', 'customer_3')
139 customer_4 -11.95793420605867
resNode: customer_3 deliver_cap: 45.94280758310987 cap_limit: 40
562 customer_4 ('customer_4', 'customer_1')
139 customer_4 -11.95793420605867
resNode: customer_1 deliver_cap: 41.51864493469679 cap_limit: 40
563 customer_4 ('customer_4', 'depot_t')
139 customer_4 -11.95793420605867
resNode: depot_t deliver_cap: 30.198493988775752 cap_limit: 40
564 customer_4 ('customer_4', 'customer_2')
139 customer_4 -11.95793420605867
resNode: customer_2 deliver_cap: 34.387015482153 cap_limit: 40
565 customer_4 ('customer_4', 'customer_5')
139 customer_4 -11.95793420605867
resNode: customer_5 deliver_cap: 42.27789158428605 cap_limit: 40
566 customer_5 ('customer_5', 'customer_3')
140 customer_5 -10.959524670351918
resNode: customer_3 deliver_cap: 42.449930301144505 cap_limit: 40
567 customer_5 ('customer_5', 'customer_1')
140 customer_5 -10.959524670351918
resNode: customer_1 deliver_cap: 34.00682832401357 cap_limit: 40
568 customer_5 ('customer_5', 'depot_t')
140 customer_5 -10.959524670351918
resNode: depot_t deliver_cap: 20.882376178192004 cap_limit: 40
569 customer_5 ('customer_5', 'customer_2')
140 customer_5 -10.959524670351918
resNode: customer_2 deliver_cap: 24.139285890510877 cap_limit: 40
570 customer_5 ('customer_5', 'customer_4')
140 customer_5 -10.959524670351918
resNode: customer_4 deliver_cap: 42.27789158428605 cap_limit: 40
571 customer_3 ('customer_3', 'customer_1')
141 customer_3 -16.64453200908832
resNode: customer_1 deliver_cap: 52.27355201186947 cap_limit: 40
572 customer_3 ('customer_3', 'depot_t')
141 customer_3 -16.64453200908832
resNode: depot_t deliver_cap: 38.48932971542383 cap_limit: 40
573 customer_3 ('customer_3', 'customer_2')
141 customer_3 -16.64453200908832
resNode: customer_2 deliver_cap: 42.93744823338608 cap_limit: 40
574 customer_3 ('customer_3', 'customer_4')
141 customer_3 -16.64453200908832
resNode: customer_4 deliver_cap: 54.57355138233635 cap_limit: 40
575 customer_3 ('customer_3', 'customer_5')
141 customer_3 -16.64453200908832
resNode: customer_5 deliver_cap: 50.3322003970927 cap_limit: 40
576 customer_1 ('customer_1', 'customer_3')
142 customer_1 -11.894937213507845
resNode: customer_3 deliver_cap: 58.515642038054416 cap_limit: 40
577 customer_1 ('customer_1', 'depot_t')
142 customer_1 -11.894937213507845
resNode: depot_t deliver_cap: 34.53510824128558 cap_limit: 40
578 customer_1 ('customer_1', 'customer_2')
142 customer_1 -11.894937213507845
resNode: customer_2 deliver_cap: 37.988619065414134 cap_limit: 40
579 customer_1 ('customer_1', 'customer_4')
142 customer_1 -11.894937213507845
resNode: customer_4 deliver_cap: 58.08411884595013 cap_limit: 40
580 customer_1 ('customer_1', 'customer_5')
142 customer_1 -11.894937213507845
resNode: customer_5 deliver_cap: 48.52362497780785 cap_limit: 40
581 customer_2 ('customer_2', 'customer_3')
144 customer_2 -10.939214848366571
resNode: customer_3 deliver_cap: 53.67229845683987 cap_limit: 40
582 customer_2 ('customer_2', 'customer_1')
144 customer_2 -10.939214848366571
resNode: customer_1 deliver_cap: 41.518644934696795 cap_limit: 40
583 customer_2 ('customer_2', 'depot_t')
144 customer_2 -10.939214848366571
resNode: depot_t deliver_cap: 28.051808738973047 cap_limit: 40
584 customer_2 ('customer_2', 'customer_4')
144 customer_2 -10.939214848366571
resNode: customer_4 deliver_cap: 53.50025973998141 cap_limit: 40
585 customer_2 ('customer_2', 'customer_5')
144 customer_2 -10.939214848366571
resNode: customer_5 deliver_cap: 40.45769480516417 cap_limit: 40
586 customer_5 ('customer_5', 'customer_3')
145 customer_5 -19.869234681101887
resNode: customer_3 deliver_cap: 61.92824968984141 cap_limit: 40
587 customer_5 ('customer_5', 'customer_1')
145 customer_5 -19.869234681101887
resNode: customer_1 deliver_cap: 51.83122260447478 cap_limit: 40
588 customer_5 ('customer_5', 'depot_t')
145 customer_5 -19.869234681101887
resNode: depot_t deliver_cap: 35.08619343080171 cap_limit: 40
589 customer_5 ('customer_5', 'customer_2')
145 customer_5 -19.869234681101887
resNode: customer_2 deliver_cap: 39.27253223456226 cap_limit: 40
590 customer_5 ('customer_5', 'customer_4')
145 customer_5 -19.869234681101887
resNode: customer_4 deliver_cap: 61.719345533656146 cap_limit: 40
591 customer_3 ('customer_3', 'customer_1')
146 customer_3 -18.964433297873537
resNode: customer_1 deliver_cap: 52.26274579657907 cap_limit: 40
592 customer_3 ('customer_3', 'depot_t')
146 customer_3 -18.964433297873537
resNode: depot_t deliver_cap: 38.47929537265417 cap_limit: 40
593 customer_3 ('customer_3', 'customer_2')
146 customer_3 -18.964433297873537
resNode: customer_2 deliver_cap: 42.92664201809568 cap_limit: 40
594 customer_3 ('customer_3', 'customer_4')
146 customer_3 -18.964433297873537
resNode: customer_4 deliver_cap: 54.560429549483715 cap_limit: 40
595 customer_3 ('customer_3', 'customer_5')
146 customer_3 -18.964433297873537
resNode: customer_5 deliver_cap: 50.319078564240066 cap_limit: 40
596 customer_1 ('customer_1', 'customer_3')
147 customer_1 -12.700828877701621
resNode: customer_3 deliver_cap: 52.437219236587104 cap_limit: 40
597 customer_1 ('customer_1', 'depot_t')
147 customer_1 -12.700828877701621
resNode: depot_t deliver_cap: 30.193377668808928 cap_limit: 40
598 customer_1 ('customer_1', 'customer_2')
147 customer_1 -12.700828877701621
resNode: customer_2 deliver_cap: 33.21271543568982 cap_limit: 40
599 customer_1 ('customer_1', 'customer_4')
147 customer_1 -12.700828877701621
resNode: customer_4 deliver_cap: 52.00569604448281 cap_limit: 40
600 customer_1 ('customer_1', 'customer_5')
147 customer_1 -12.700828877701621
resNode: customer_5 deliver_cap: 42.44520217634053 cap_limit: 40
601 customer_2 ('customer_2', 'customer_3')
149 customer_2 -10.874588745891604
resNode: customer_3 deliver_cap: 44.11180458869758 cap_limit: 40
602 customer_2 ('customer_2', 'customer_1')
149 customer_2 -10.874588745891604
resNode: customer_1 deliver_cap: 34.00682832401357 cap_limit: 40
603 customer_2 ('customer_2', 'depot_t')
149 customer_2 -10.874588745891604
resNode: depot_t deliver_cap: 21.222884547442845 cap_limit: 40
604 customer_2 ('customer_2', 'customer_4')
149 customer_2 -10.874588745891604
resNode: customer_4 deliver_cap: 43.939765871839136 cap_limit: 40
605 customer_2 ('customer_2', 'customer_5')
149 customer_2 -10.874588745891604

156 customer_3 -11.607783047478277
resNode: depot_t deliver_cap: 30.321378786531792 cap_limit: 40
633 customer_3 ('customer_3', 'customer_2')
156 customer_3 -11.607783047478277
resNode: customer_2 deliver_cap: 34.52218875968464 cap_limit: 40
634 customer_3 ('customer_3', 'customer_4')
156 customer_3 -11.607783047478277
resNode: customer_4 deliver_cap: 45.94280758310987 cap_limit: 40
635 customer_3 ('customer_3', 'customer_5')
156 customer_3 -11.607783047478277
resNode: customer_5 deliver_cap: 42.449930301144505 cap_limit: 40
636 customer_2 ('customer_2', 'customer_3')
158 customer_2 -4.18202968828421
resNode: customer_3 deliver_cap: 36.67966187534589 cap_limit: 40
637 customer_2 ('customer_2', 'customer_1')
158 customer_2 -4.18202968828421
resNode: customer_1 deliver_cap: 26.201611029369303 cap_limit: 40
638 customer_2 ('customer_2', 'depot_t')
158 customer_2 -4.18202968828421
resNode: depot_t deliver_cap: 16.14171990044495 cap_limit: 40
639 customer_2 ('customer_2', 'customer_4')
158 customer_2 -4.18202968828421
resNode: customer_4 deliver_cap: 36.54448859781425 cap_limit: 40
640 customer_2 ('customer_2', 'customer_5')
158 customer_2 -4.18202968828421
resNode: customer_5 deliver_cap: 26.296759006172127 cap_limit: 40
641 customer_4 ('customer_4', 'customer_3')
159 customer_4 -11.472971552804504
resNode: customer_3 deliver_cap: 45.68332310786404 cap_limit: 40
642 customer_4 ('customer_4', 'customer_1')
159 customer_4 -11.472971552804504
resNode: customer_1 deliver_cap: 41.31476427557506 cap_limit: 40
643 customer_4 ('customer_4', 'depot_t')
159 customer_4 -11.472971552804504
resNode: depot_t deliver_cap: 30.01314793502873 cap_limit: 40
644 customer_4 ('customer_4', 'customer_2')
159 customer_4 -11.472971552804504
resNode: customer_2 deliver_cap: 34.183134823031274 cap_limit: 40
645 customer_4 ('customer_4', 'customer_5')
159 customer_4 -11.472971552804504
resNode: customer_5 deliver_cap: 42.01840710904022 cap_limit: 40
646 customer_5 ('customer_5', 'customer_3')
160 customer_5 -12.09123786948256
resNode: customer_3 deliver_cap: 45.67251689257364 cap_limit: 40
647 customer_5 ('customer_5', 'customer_1')
160 customer_5 -12.09123786948256
resNode: customer_1 deliver_cap: 36.53886064585075 cap_limit: 40
648 customer_5 ('customer_5', 'depot_t')
160 customer_5 -12.09123786948256
resNode: depot_t deliver_cap: 23.184223743498528 cap_limit: 40
649 customer_5 ('customer_5', 'customer_2')
160 customer_5 -12.09123786948256
resNode: customer_2 deliver_cap: 26.67131821234805 cap_limit: 40
650 customer_5 ('customer_5', 'customer_4')
160 customer_5 -12.09123786948256
resNode: customer_4 deliver_cap: 45.50047817571519 cap_limit: 40
651 customer_3 ('customer_3', 'customer_1')
161 customer_3 -13.399127393531636
resNode: customer_1 deliver_cap: 47.43020843065491 cap_limit: 40
652 customer_3 ('customer_3', 'depot_t')
161 customer_3 -13.399127393531636
resNode: depot_t deliver_cap: 33.99193924715317 cap_limit: 40
653 customer_3 ('customer_3', 'customer_2')
161 customer_3 -13.399127393531636
resNode: customer_2 deliver_cap: 38.09410465217153 cap_limit: 40
654 customer_3 ('customer_3', 'customer_4')
161 customer_3 -13.399127393531636
resNode: customer_4 deliver_cap: 48.692348462290106 cap_limit: 40
655 customer_3 ('customer_3', 'customer_5')
161 customer_3 -13.399127393531636
resNode: customer_5 deliver_cap: 44.45099747704645 cap_limit: 40
656 customer_1 ('customer_1', 'customer_3')
162 customer_1 -9.946856771490774
resNode: customer_3 deliver_cap: 53.67229845683987 cap_limit: 40
657 customer_1 ('customer_1', 'depot_t')
162 customer_1 -9.946856771490774
resNode: depot_t deliver_cap: 31.075577111846613 cap_limit: 40
658 customer_1 ('customer_1', 'customer_2')
162 customer_1 -9.946856771490774
resNode: customer_2 deliver_cap: 34.183134823031274 cap_limit: 40
659 customer_1 ('customer_1', 'customer_4')
162 customer_1 -9.946856771490774
resNode: customer_4 deliver_cap: 53.240775264735575 cap_limit: 40
660 customer_1 ('customer_1', 'customer_5')
162 customer_1 -9.946856771490774
resNode: customer_5 deliver_cap: 43.680281396593294 cap_limit: 40
661 customer_2 ('customer_2', 'customer_3')
164 customer_2 -8.991134406349499
resNode: customer_3 deliver_cap: 48.828954875625314 cap_limit: 40
662 customer_2 ('customer_2', 'customer_1')
164 customer_2 -8.991134406349499
resNode: customer_1 deliver_cap: 37.71316069231393 cap_limit: 40
663 customer_2 ('customer_2', 'depot_t')
164 customer_2 -8.991134406349499
resNode: depot_t deliver_cap: 24.59227760953408 cap_limit: 40
664 customer_2 ('customer_2', 'customer_4')
164 customer_2 -8.991134406349499
resNode: customer_4 deliver_cap: 48.656916158766855 cap_limit: 40
665 customer_2 ('customer_2', 'customer_5')
164 customer_2 -8.991134406349499
resNode: customer_5 deliver_cap: 35.61435122394961 cap_limit: 40
666 customer_5 ('customer_5', 'customer_3')
165 customer_5 -16.623830065545206
resNode: customer_3 deliver_cap: 56.047046769795166 cap_limit: 40
667 customer_5 ('customer_5', 'customer_1')
165 customer_5 -16.623830065545206
resNode: customer_1 deliver_cap: 46.98787902326023 cap_limit: 40
668 customer_5 ('customer_5', 'depot_t')
165 customer_5 -16.623830065545206
resNode: depot_t deliver_cap: 30.58880296253105 cap_limit: 40
669 customer_5 ('customer_5', 'customer_2')
165 customer_5 -16.623830065545206
resNode: customer_2 deliver_cap: 34.42918865334771 cap_limit: 40
670 customer_5 ('customer_5', 'customer_4')
165 customer_5 -16.623830065545206
resNode: customer_4 deliver_cap: 55.838142613609904 cap_limit: 40
671 customer_3 ('customer_3', 'customer_1')
166 customer_3 -12.920935860881615
resNode: customer_1 deliver_cap: 43.93733114868955 cap_limit: 40
672 customer_3 ('customer_3', 'depot_t')
166 customer_3 -12.920935860881615
resNode: depot_t deliver_cap: 30.748553199613905 cap_limit: 40
673 customer_3 ('customer_3', 'customer_2')
166 customer_3 -12.920935860881615
resNode: customer_2 deliver_cap: 34.60122737020616 cap_limit: 40
674 customer_3 ('customer_3', 'customer_4')
166 customer_3 -12.920935860881615
resNode: customer_4 deliver_cap: 44.45099747704646 cap_limit: 40
675 customer_3 ('customer_3', 'customer_5')
166 customer_3 -12.920935860881615
resNode: customer_5 deliver_cap: 40.2096464918028 cap_limit: 40
676 customer_1 ('customer_1', 'customer_3')
167 customer_1 -8.887353221394392
resNode: customer_3 deliver_cap: 44.11180458869758 cap_limit: 40
677 customer_1 ('customer_1', 'depot_t')
167 customer_1 -8.887353221394392
resNode: depot_t deliver_cap: 24.246652920316414 cap_limit: 40
678 customer_1 ('customer_1', 'customer_2')
167 customer_1 -8.887353221394392
resNode: customer_2 deliver_cap: 26.67131821234805 cap_limit: 40
679 customer_1 ('customer_1', 'customer_4')
167 customer_1 -8.887353221394392
resNode: customer_4 deliver_cap: 43.68028139659329 cap_limit: 40
680 customer_1 ('customer_1', 'customer_5')
167 customer_1 -8.887353221394392
resNode: customer_5 deliver_cap: 34.11978752845101 cap_limit: 40
681 customer_2 ('customer_2', 'customer_3')
169 customer_2 -7.061113089584374
resNode: customer_3 deliver_cap: 35.786389940808064 cap_limit: 40
682 customer_2 ('customer_2', 'customer_1')
169 customer_2 -7.061113089584374
resNode: customer_1 deliver_cap: 27.465431100671804 cap_limit: 40
683 customer_2 ('customer_2', 'depot_t')
169 customer_2 -7.061113089584374
resNode: depot_t deliver_cap: 15.276159798950335 cap_limit: 40
684 customer_2 ('customer_2', 'customer_4')
169 customer_2 -7.061113089584374
resNode: customer_4 deliver_cap: 35.61435122394961 cap_limit: 40
685 customer_2 ('customer_2', 'customer_5')
169 customer_2 -7.061113089584374
resNode: customer_5 deliver_cap: 22.57178628913237 cap_limit: 40
686 customer_4 ('customer_4', 'customer_3')
170 customer_4 -12.897382941311708
resNode: customer_3 deliver_cap: 44.45099747704646 cap_limit: 40
687 customer_4 ('customer_4', 'customer_1')
170 customer_4 -12.897382941311708
resNode: customer_1 deliver_cap: 43.50580795658526 cap_limit: 40
688 customer_4 ('customer_4', 'depot_t')
170 customer_4 -12.897382941311708
resNode: depot_t deliver_cap: 30.58880296253106 cap_limit: 40
689 customer_4 ('customer_4', 'customer_2')
170 customer_4 -12.897382941311708
resNode: customer_2 deliver_cap: 34.429188653347715 cap_limit: 40
690 customer_4 ('customer_4', 'customer_5')
170 customer_4 -12.897382941311708
resNode: customer_5 deliver_cap: 40.00074233561753 cap_limit: 40
691 customer_1 ('customer_1', 'customer_3')
171 customer_1 -5.9549779718012505
resNode: customer_3 deliver_cap: 55.09754382989156 cap_limit: 40
692 customer_1 ('customer_1', 'depot_t')
171 customer_1 -5.9549779718012505
resNode: depot_t deliver_cap: 32.6931032625378 cap_limit: 40
693 customer_1 ('customer_1', 'customer_2')
171 customer_1 -5.9549779718012505
resNode: customer_2 deliver_cap: 35.20795735965609 cap_limit: 40
694 customer_1 ('customer_1', 'customer_4')
171 customer_1 -5.9549779718012505
resNode: customer_4 deliver_cap: 54.57355138233635 cap_limit: 40
695 customer_1 ('customer_1', 'customer_5')
171 customer_1 -5.9549779718012505
resNode: customer_5 deliver_cap: 42.964380256735005 cap_limit: 40
696 customer_2 ('customer_2', 'customer_3')
173 customer_2 -4.434236071144051
resNode: customer_3 deliver_cap: 48.90125261847537 cap_limit: 40
697 customer_2 ('customer_2', 'customer_1')
173 customer_2 -4.434236071144051
resNode: customer_1 deliver_cap: 39.44123308167908 cap_limit: 40
698 customer_2 ('customer_2', 'depot_t')
173 customer_2 -4.434236071144051
resNode: depot_t deliver_cap: 24.02386403966037 cap_limit: 40
699 customer_2 ('customer_2', 'customer_4')
173 customer_2 -4.434236071144051
resNode: customer_4 deliver_cap: 48.692348462290106 cap_limit: 40
700 customer_2 ('customer_2', 'customer_5')
173 customer_2 -4.434236071144051
resNode: customer_5 deliver_cap: 32.85494818429774 cap_limit: 40
701 customer_4 ('customer_4', 'customer_3')
174 customer_4 -6.633969053410491
resNode: customer_3 deliver_cap: 45.06035144916693 cap_limit: 40
702 customer_4 ('customer_4', 'customer_1')
174 customer_4 -6.633969053410491
resNode: customer_1 deliver_cap: 46.678782344884674 cap_limit: 40
703 customer_4 ('customer_4', 'depot_t')
174 customer_4 -6.633969053410491
resNode: depot_t deliver_cap: 31.859805732106324 cap_limit: 40
704 customer_4 ('customer_4', 'customer_2')
174 customer_4 -6.633969053410491
resNode: customer_2 deliver_cap: 35.65717319095337 cap_limit: 40
705 customer_4 ('customer_4', 'customer_5')
174 customer_4 -6.633969053410491
resNode: customer_5 deliver_cap: 39.8247571651329 cap_limit: 40
706 customer_5 ('customer_5', 'customer_3')
175 customer_5 -9.695106219174399
resNode: customer_3 deliver_cap: 53.71293769329053 cap_limit: 40
707 customer_5 ('customer_5', 'customer_1')
175 customer_5 -9.695106219174399
resNode: customer_1 deliver_cap: 46.665660512032055 cap_limit: 40
708 customer_5 ('customer_5', 'depot_t')
175 customer_5 -9.695106219174399
resNode: depot_t deliver_cap: 27.867945981288766 cap_limit: 40
709 customer_5 ('customer_5', 'customer_2')
175 customer_5 -9.695106219174399
resNode: customer_2 deliver_cap: 31.41582220570972 cap_limit: 40
710 customer_5 ('customer_5', 'customer_4')
175 customer_5 -9.695106219174399
resNode: customer_4 deliver_cap: 53.467168097778455 cap_limit: 40
711 customer_3 ('customer_3', 'customer_1')
176 customer_3 -11.999604451793031
resNode: customer_1 deliver_cap: 52.27355201186946 cap_limit: 40
712 customer_3 ('customer_3', 'depot_t')
176 customer_3 -11.999604451793031
resNode: depot_t deliver_cap: 38.48932971542382 cap_limit: 40
713 customer_3 ('customer_3', 'customer_2')
176 customer_3 -11.999604451793031
resNode: customer_2 deliver_cap: 42.93744823338608 cap_limit: 40
714 customer_3 ('customer_3', 'customer_4')
176 customer_3 -11.999604451793031
resNode: customer_4 deliver_cap: 54.57355138233635 cap_limit: 40
715 customer_3 ('customer_3', 'customer_5')
176 customer_3 -11.999604451793031
resNode: customer_5 deliver_cap: 50.33220039709269 cap_limit: 40
716 customer_2 ('customer_2', 'customer_3')
178 customer_2 -4.297043453827327
resNode: customer_3 deliver_cap: 45.683323107864034 cap_limit: 40
717 customer_2 ('customer_2', 'customer_1')
178 customer_2 -4.297043453827327
resNode: customer_1 deliver_cap: 35.24159287478721 cap_limit: 40
718 customer_2 ('customer_2', 'depot_t')
178 customer_2 -4.297043453827327
resNode: depot_t deliver_cap: 22.34539777541888 cap_limit: 40
719 customer_2 ('customer_2', 'customer_4')
178 customer_2 -4.297043453827327
resNode: customer_4 deliver_cap: 45.51128439100558 cap_limit: 40
720 customer_2 ('customer_2', 'customer_5')
178 customer_2 -4.297043453827327
resNode: customer_5 deliver_cap: 32.46871945618833 cap_limit: 40
721 customer_4 ('customer_4', 'customer_3')
179 customer_4 -11.84167564325653
resNode: customer_3 deliver_cap: 54.258463090966394 cap_limit: 40
722 customer_4 ('customer_4', 'customer_1')
179 customer_4 -11.84167564325653
resNode: customer_1 deliver_cap: 51.582544344519334 cap_limit: 40
723 customer_4 ('customer_4', 'depot_t')
179 customer_4 -11.84167564325653
resNode: depot_t deliver_cap: 38.08862960846984 cap_limit: 40
724 customer_4 ('customer_4', 'customer_2')
179 customer_4 -11.84167564325653
resNode: customer_2 deliver_cap: 42.505925041281785 cap_limit: 40
725 customer_4 ('customer_4', 'customer_5')
179 customer_4 -11.84167564325653
resNode: customer_5 deliver_cap: 49.808207949537476 cap_limit: 40
726 customer_5 ('customer_5', 'customer_3')
180 customer_5 -11.94777264556982
resNode: customer_3 deliver_cap: 54.24534125811378 cap_limit: 40
727 customer_5 ('customer_5', 'customer_1')
180 customer_5 -11.94777264556982
resNode: customer_1 deliver_cap: 45.50412154305202 cap_limit: 40
728 customer_5 ('customer_5', 'depot_t')
180 customer_5 -11.94777264556982
resNode: depot_t deliver_cap: 29.21102815948058 cap_limit: 40
729 customer_5 ('customer_5', 'customer_2')
180 customer_5 -11.94777264556982
resNode: customer_2 deliver_cap: 32.94543117313951 cap_limit: 40
730 customer_5 ('customer_5', 'customer_4')
180 customer_5 -11.94777264556982
resNode: customer_4 deliver_cap: 54.03643710192851 cap_limit: 40
731 customer_3 ('customer_3', 'customer_1')
181 customer_3 -10.15654689338664
resNode: customer_1 deliver_cap: 47.43020843065491 cap_limit: 40
732 customer_3 ('customer_3', 'depot_t')
181 customer_3 -10.15654689338664
resNode: depot_t deliver_cap: 33.99193924715317 cap_limit: 40
733 customer_3 ('customer_3', 'customer_2')
181 customer_3 -10.15654689338664
resNode: customer_2 deliver_cap: 38.094104652171524 cap_limit: 40
734 customer_3 ('customer_3', 'customer_4')
181 customer_3 -10.15654689338664
resNode: customer_4 deliver_cap: 48.692348462290106 cap_limit: 40
735 customer_3 ('customer_3', 'customer_5')
181 customer_3 -10.15654689338664
resNode: customer_5 deliver_cap: 44.45099747704645 cap_limit: 40
736 customer_1 ('customer_1', 'customer_3')
182 customer_1 -4.771903552913281
resNode: customer_3 deliver_cap: 45.94280758310987 cap_limit: 40
737 customer_1 ('customer_1', 'depot_t')
182 customer_1 -4.771903552913281
resNode: depot_t deliver_cap: 25.554512202039472 cap_limit: 40
738 customer_1 ('customer_1', 'customer_2')
182 customer_1 -4.771903552913281
resNode: customer_2 deliver_cap: 28.109963422243418 cap_limit: 40
739 customer_1 ('customer_1', 'customer_4')
182 customer_1 -4.771903552913281
resNode: customer_4 deliver_cap: 45.51128439100558 cap_limit: 40
740 customer_1 ('customer_1', 'customer_5')
182 customer_1 -4.771903552913281
resNode: customer_5 deliver_cap: 35.9507905228633 cap_limit: 40
741 customer_4 ('customer_4', 'customer_3')
184 customer_4 -10.132993973816735
resNode: customer_3 deliver_cap: 48.692348462290106 cap_limit: 40
742 customer_4 ('customer_4', 'customer_1')
184 customer_4 -10.132993973816735
resNode: customer_1 deliver_cap: 46.99868523855062 cap_limit: 40
743 customer_4 ('customer_4', 'depot_t')
184 customer_4 -10.132993973816735
resNode: depot_t deliver_cap: 33.83218901007032 cap_limit: 40
744 customer_4 ('customer_4', 'customer_2')
184 customer_4 -10.132993973816735
resNode: customer_2 deliver_cap: 37.92206593531307 cap_limit: 40
745 customer_4 ('customer_4', 'customer_5')
184 customer_4 -10.132993973816735
resNode: customer_5 deliver_cap: 44.24209332086118 cap_limit: 40
746 customer_5 ('customer_5', 'customer_3')
185 customer_5 -8.435875602316203
resNode: customer_3 deliver_cap: 44.45099747704645 cap_limit: 40
747 customer_5 ('customer_5', 'customer_1')
185 customer_5 -8.435875602316203
resNode: customer_1 deliver_cap: 37.43819137040834 cap_limit: 40
748 customer_5 ('customer_5', 'depot_t')
185 customer_5 -8.435875602316203
resNode: depot_t deliver_cap: 21.721235856311452 cap_limit: 40
749 customer_5 ('customer_5', 'customer_2')
185 customer_5 -8.435875602316203
resNode: customer_2 deliver_cap: 24.879501000495832 cap_limit: 40
750 customer_5 ('customer_5', 'customer_4')
185 customer_5 -8.435875602316203
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
751 customer_3 ('customer_3', 'customer_1')
186 customer_3 -14.104951735425809
resNode: customer_1 deliver_cap: 54.34856894375968 cap_limit: 40
752 customer_3 ('customer_3', 'depot_t')
186 customer_3 -14.104951735425809
resNode: depot_t deliver_cap: 38.781874727405196 cap_limit: 40
753 customer_3 ('customer_3', 'customer_2')
186 customer_3 -14.104951735425809
resNode: customer_2 deliver_cap: 43.01187149845842 cap_limit: 40
754 customer_3 ('customer_3', 'customer_4')
186 customer_3 -14.104951735425809
resNode: customer_4 deliver_cap: 53.46716809777844 cap_limit: 40
755 customer_3 ('customer_3', 'customer_5')
186 customer_3 -14.104951735425809
resNode: customer_5 deliver_cap: 48.47734340925649 cap_limit: 40
756 customer_1 ('customer_1', 'customer_3')
187 customer_1 -9.896186144868393
resNode: customer_3 deliver_cap: 54.56042954948372 cap_limit: 40
757 customer_1 ('customer_1', 'depot_t')
187 customer_1 -9.896186144868393
resNode: depot_t deliver_cap: 32.282368812814155 cap_limit: 40
758 customer_1 ('customer_1', 'customer_2')
187 customer_1 -9.896186144868393
resNode: customer_2 deliver_cap: 34.765627952261404 cap_limit: 40
759 customer_1 ('customer_1', 'customer_4')
187 customer_1 -9.896186144868393
resNode: customer_4 deliver_cap: 54.03643710192851 cap_limit: 40
760 customer_1 ('customer_1', 'customer_5')
187 customer_1 -9.896186144868393
resNode: customer_5 deliver_cap: 42.42726597632717 cap_limit: 40
761 customer_2 ('customer_2', 'customer_3')
189 customer_2 -7.397159028955922
resNode: customer_3 deliver_cap: 44.45099747704645 cap_limit: 40
762 customer_2 ('customer_2', 'customer_1')
189 customer_2 -7.397159028955922
resNode: customer_1 deliver_cap: 35.77631708285526 cap_limit: 40
763 customer_2 ('customer_2', 'depot_t')
189 customer_2 -7.397159028955922
resNode: depot_t deliver_cap: 20.620727755038256 cap_limit: 40
764 customer_2 ('customer_2', 'customer_4')
189 customer_2 -7.397159028955922
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
765 customer_2 ('customer_2', 'customer_5')
189 customer_2 -7.397159028955922
resNode: customer_5 deliver_cap: 28.40469304286882 cap_limit: 40
766 customer_4 ('customer_4', 'customer_3')
190 customer_4 -14.072182456024198
resNode: customer_3 deliver_cap: 53.46716809777844 cap_limit: 40
767 customer_4 ('customer_4', 'customer_1')
190 customer_4 -14.072182456024198
resNode: customer_1 deliver_cap: 53.824576496204465 cap_limit: 40
768 customer_4 ('customer_4', 'depot_t')
190 customer_4 -14.072182456024198
resNode: depot_t deliver_cap: 38.58525905099553 cap_limit: 40
769 customer_4 ('customer_4', 'customer_2')
190 customer_4 -14.072182456024198
resNode: customer_2 deliver_cap: 42.802967342273156 cap_limit: 40
770 customer_4 ('customer_4', 'customer_5')
190 customer_4 -14.072182456024198
resNode: customer_5 deliver_cap: 48.23157381374442 cap_limit: 40
771 customer_1 ('customer_1', 'customer_3')
191 customer_1 -13.583271900970532
resNode: customer_3 deliver_cap: 62.452242137396624 cap_limit: 40
772 customer_1 ('customer_1', 'depot_t')
191 customer_1 -13.583271900970532

resNode: customer_5 deliver_cap: 49.79508611668486 cap_limit: 40
841 customer_2 ('customer_2', 'customer_3')
209 customer_2 -12.026688600967816
resNode: customer_3 deliver_cap: 56.04704676979516 cap_limit: 40
842 customer_2 ('customer_2', 'customer_1')
209 customer_2 -12.026688600967816
resNode: customer_1 deliver_cap: 45.326004735707144 cap_limit: 40
843 customer_2 ('customer_2', 'depot_t')
209 customer_2 -12.026688600967816
resNode: depot_t deliver_cap: 29.488294861257856 cap_limit: 40
844 customer_2 ('customer_2', 'customer_4')
209 customer_2 -12.026688600967816
resNode: customer_4 deliver_cap: 55.83814261360989 cap_limit: 40
845 customer_2 ('customer_2', 'customer_5')
209 customer_2 -12.026688600967816
resNode: customer_5 deliver_cap: 40.000742335617524 cap_limit: 40
846 customer_5 ('customer_5', 'customer_3')
210 customer_5 -18.863836870612822
resNode: customer_3 deliver_cap: 62.119754341902045 cap_limit: 40
847 customer_5 ('customer_5', 'customer_1')
210 customer_5 -18.863836870612822
resNode: customer_1 deliver_cap: 53.81145466335184 cap_limit: 40
848 customer_5 ('customer_5', 'depot_t')
210 customer_5 -18.863836870612822
resNode: depot_t deliver_cap: 34.59339930017798 cap_limit: 40
849 customer_5 ('customer_5', 'customer_2')
210 customer_5 -18.863836870612822
resNode: customer_2 deliver_cap: 38.5616163570295 cap_limit: 40
850 customer_5 ('customer_5', 'customer_4')
210 customer_5 -18.863836870612822
resNode: customer_4 deliver_cap: 61.873984746389965 cap_limit: 40
851 customer_3 ('customer_3', 'customer_1')
211 customer_3 -16.85794691269468
resNode: customer_1 deliver_cap: 47.03573586735443 cap_limit: 40
852 customer_3 ('customer_3', 'depot_t')
211 customer_3 -16.85794691269468
resNode: depot_t deliver_cap: 35.02868514653567 cap_limit: 40
853 customer_3 ('customer_3', 'customer_2')
211 customer_3 -16.85794691269468
resNode: customer_2 deliver_cap: 39.70022575568891 cap_limit: 40
854 customer_3 ('customer_3', 'customer_4')
211 customer_3 -16.85794691269468
resNode: customer_4 deliver_cap: 52.5330364871153 cap_limit: 40
855 customer_3 ('customer_3', 'customer_5')
211 customer_3 -16.85794691269468
resNode: customer_5 deliver_cap: 49.04015920514994 cap_limit: 40
856 customer_2 ('customer_2', 'customer_3')
213 customer_2 -7.66695366849916
resNode: customer_3 deliver_cap: 41.85769887135016 cap_limit: 40
857 customer_2 ('customer_2', 'customer_1')
213 customer_2 -7.66695366849916
resNode: customer_1 deliver_cap: 29.967456117372407 cap_limit: 40
858 customer_2 ('customer_2', 'depot_t')
213 customer_2 -7.66695366849916
resNode: depot_t deliver_cap: 19.43683435244767 cap_limit: 40
859 customer_2 ('customer_2', 'customer_4')
213 customer_2 -7.66695366849916
resNode: customer_4 deliver_cap: 41.72252559381852 cap_limit: 40
860 customer_2 ('customer_2', 'customer_5')
213 customer_2 -7.66695366849916
resNode: customer_5 deliver_cap: 31.474796002176397 cap_limit: 40
861 customer_4 ('customer_4', 'customer_3')
214 customer_4 -16.72313541802091
resNode: customer_3 deliver_cap: 52.27355201186947 cap_limit: 40
862 customer_4 ('customer_4', 'customer_1')
214 customer_4 -16.72313541802091
resNode: customer_1 deliver_cap: 46.492801271579324 cap_limit: 40
863 customer_4 ('customer_4', 'depot_t')
214 customer_4 -16.72313541802091
resNode: depot_t deliver_cap: 34.72045429503261 cap_limit: 40
864 customer_4 ('customer_4', 'customer_2')
214 customer_4 -16.72313541802091
resNode: customer_2 deliver_cap: 39.36117181903554 cap_limit: 40
865 customer_4 ('customer_4', 'customer_5')
214 customer_4 -16.72313541802091
resNode: customer_5 deliver_cap: 48.60863601304565 cap_limit: 40
866 customer_5 ('customer_5', 'customer_3')
215 customer_5 -17.341401734698962
resNode: customer_3 deliver_cap: 52.262745796579075 cap_limit: 40
867 customer_5 ('customer_5', 'customer_1')
215 customer_5 -17.341401734698962
resNode: customer_1 deliver_cap: 41.71689764185501 cap_limit: 40
868 customer_5 ('customer_5', 'depot_t')
215 customer_5 -17.341401734698962
resNode: depot_t deliver_cap: 27.891530103502408 cap_limit: 40
869 customer_5 ('customer_5', 'customer_2')
215 customer_5 -17.341401734698962
resNode: customer_2 deliver_cap: 31.84935520835232 cap_limit: 40
870 customer_5 ('customer_5', 'customer_4')
215 customer_5 -17.341401734698962
resNode: customer_4 deliver_cap: 52.09070707972062 cap_limit: 40
871 customer_3 ('customer_3', 'customer_1')
216 customer_3 -15.135344648685937
resNode: customer_1 deliver_cap: 43.026370965849836 cap_limit: 40
872 customer_3 ('customer_3', 'depot_t')
216 customer_3 -15.135344648685937
resNode: depot_t deliver_cap: 31.383807963349675 cap_limit: 40
873 customer_3 ('customer_3', 'customer_2')
216 customer_3 -15.135344648685937
resNode: customer_2 deliver_cap: 35.690860854184315 cap_limit: 40
874 customer_3 ('customer_3', 'customer_4')
216 customer_3 -15.135344648685937
resNode: customer_4 deliver_cap: 47.4302084306549 cap_limit: 40
875 customer_3 ('customer_3', 'customer_5')
216 customer_3 -15.135344648685937
resNode: customer_5 deliver_cap: 43.937331148689545 cap_limit: 40
876 customer_1 ('customer_1', 'customer_3')
217 customer_1 -7.831625415433434
resNode: customer_3 deliver_cap: 41.85769887135016 cap_limit: 40
877 customer_1 ('customer_1', 'depot_t')
217 customer_1 -7.831625415433434
resNode: depot_t deliver_cap: 21.553472213459163 cap_limit: 40
878 customer_1 ('customer_1', 'customer_2')
217 customer_1 -7.831625415433434
resNode: customer_2 deliver_cap: 24.632539672524757 cap_limit: 40
879 customer_1 ('customer_1', 'customer_4')
217 customer_1 -7.831625415433434
resNode: customer_4 deliver_cap: 41.518644934696795 cap_limit: 40
880 customer_1 ('customer_1', 'customer_5')
217 customer_1 -7.831625415433434
resNode: customer_5 deliver_cap: 34.00682832401357 cap_limit: 40
881 customer_4 ('customer_4', 'customer_3')
219 customer_4 -15.121008088947733
resNode: customer_3 deliver_cap: 47.4302084306549 cap_limit: 40
882 customer_4 ('customer_4', 'customer_1')
219 customer_4 -15.121008088947733
resNode: customer_1 deliver_cap: 42.68731702919646 cap_limit: 40
883 customer_4 ('customer_4', 'depot_t')
219 customer_4 -15.121008088947733
resNode: depot_t deliver_cap: 31.260923165593635 cap_limit: 40
884 customer_4 ('customer_4', 'customer_2')
219 customer_4 -15.121008088947733
resNode: customer_2 deliver_cap: 35.55568757665267 cap_limit: 40
885 customer_4 ('customer_4', 'customer_5')
219 customer_4 -15.121008088947733
resNode: customer_5 deliver_cap: 43.765292431831085 cap_limit: 40
886 customer_5 ('customer_5', 'customer_3')
220 customer_5 -14.122598553240982
resNode: customer_3 deliver_cap: 43.937331148689545 cap_limit: 40
887 customer_5 ('customer_5', 'customer_1')
220 customer_5 -14.122598553240982
resNode: customer_1 deliver_cap: 35.17550041851324 cap_limit: 40
888 customer_5 ('customer_5', 'depot_t')
220 customer_5 -14.122598553240982
resNode: depot_t deliver_cap: 21.94480535500989 cap_limit: 40
889 customer_5 ('customer_5', 'customer_2')
220 customer_5 -14.122598553240982
resNode: customer_2 deliver_cap: 25.30795798501055 cap_limit: 40
890 customer_5 ('customer_5', 'customer_4')
220 customer_5 -14.122598553240982
resNode: customer_4 deliver_cap: 43.765292431831085 cap_limit: 40
891 customer_3 ('customer_3', 'customer_1')
221 customer_3 -13.994818809751056
resNode: customer_1 deliver_cap: 46.031461985684516 cap_limit: 40
892 customer_3 ('customer_3', 'depot_t')
221 customer_3 -13.994818809751056
resNode: depot_t deliver_cap: 32.6931032625378 cap_limit: 40
893 customer_3 ('customer_3', 'customer_2')
221 customer_3 -13.994818809751056
resNode: customer_2 deliver_cap: 36.695358207201124 cap_limit: 40
894 customer_3 ('customer_3', 'customer_4')
221 customer_3 -13.994818809751056
resNode: customer_4 deliver_cap: 46.99387063625463 cap_limit: 40
895 customer_3 ('customer_3', 'customer_5')
221 customer_3 -13.994818809751056
resNode: customer_5 deliver_cap: 42.75251965101097 cap_limit: 40
896 customer_1 ('customer_1', 'customer_3')
222 customer_1 -10.917212414041554
resNode: customer_3 deliver_cap: 52.27355201186946 cap_limit: 40
897 customer_1 ('customer_1', 'depot_t')
222 customer_1 -10.917212414041554
resNode: depot_t deliver_cap: 30.076472508296327 cap_limit: 40
898 customer_1 ('customer_1', 'customer_2')
222 customer_1 -10.917212414041554
resNode: customer_2 deliver_cap: 33.08411975912596 cap_limit: 40
899 customer_1 ('customer_1', 'customer_4')
222 customer_1 -10.917212414041554
resNode: customer_4 deliver_cap: 51.84202881976517 cap_limit: 40
900 customer_1 ('customer_1', 'customer_5')
222 customer_1 -10.917212414041554
resNode: customer_5 deliver_cap: 42.28153495162289 cap_limit: 40
901 customer_2 ('customer_2', 'customer_3')
224 customer_2 -9.961490048900277
resNode: customer_3 deliver_cap: 47.43020843065491 cap_limit: 40
902 customer_2 ('customer_2', 'customer_1')
224 customer_2 -9.961490048900277
resNode: customer_1 deliver_cap: 36.614145628408615 cap_limit: 40
903 customer_2 ('customer_2', 'depot_t')
224 customer_2 -9.961490048900277
resNode: depot_t deliver_cap: 23.593173005983793 cap_limit: 40
904 customer_2 ('customer_2', 'customer_4')
224 customer_2 -9.961490048900277
resNode: customer_4 deliver_cap: 47.25816971379646 cap_limit: 40
905 customer_2 ('customer_2', 'customer_5')
224 customer_2 -9.961490048900277
resNode: customer_5 deliver_cap: 34.21560477897921 cap_limit: 40
906 customer_5 ('customer_5', 'customer_3')
225 customer_5 -17.219521481764627
resNode: customer_3 deliver_cap: 54.34856894375968 cap_limit: 40
907 customer_5 ('customer_5', 'customer_1')
225 customer_5 -17.219521481764627
resNode: customer_1 deliver_cap: 45.58913257828982 cap_limit: 40
908 customer_5 ('customer_5', 'depot_t')
225 customer_5 -17.219521481764627
resNode: depot_t deliver_cap: 29.28996697791568 cap_limit: 40
909 customer_5 ('customer_5', 'customer_2')
225 customer_5 -17.219521481764627
resNode: customer_2 deliver_cap: 33.03044220837731 cap_limit: 40
910 customer_5 ('customer_5', 'customer_4')
225 customer_5 -17.219521481764627
resNode: customer_4 deliver_cap: 54.13966478757441 cap_limit: 40
911 customer_3 ('customer_3', 'customer_1')
226 customer_3 -21.19048342671416
resNode: customer_1 deliver_cap: 52.08827235657103 cap_limit: 40
912 customer_3 ('customer_3', 'depot_t')
226 customer_3 -21.19048342671416
resNode: depot_t deliver_cap: 38.31728432121814 cap_limit: 40
913 customer_3 ('customer_3', 'customer_2')
226 customer_3 -21.19048342671416
resNode: customer_2 deliver_cap: 42.75216857808765 cap_limit: 40
914 customer_3 ('customer_3', 'customer_4')
226 customer_3 -21.19048342671416
resNode: customer_4 deliver_cap: 54.34856894375968 cap_limit: 40
915 customer_3 ('customer_3', 'customer_5')
226 customer_3 -21.19048342671416
resNode: customer_5 deliver_cap: 50.107217958516024 cap_limit: 40
916 customer_1 ('customer_1', 'customer_3')
227 customer_1 -14.973612963687252
resNode: customer_3 deliver_cap: 52.26274579657907 cap_limit: 40
917 customer_1 ('customer_1', 'depot_t')
227 customer_1 -14.973612963687252
resNode: depot_t deliver_cap: 30.0687537830889 cap_limit: 40
918 customer_1 ('customer_1', 'customer_2')
227 customer_1 -14.973612963687252
resNode: customer_2 deliver_cap: 33.07562916139779 cap_limit: 40
919 customer_1 ('customer_1', 'customer_4')
227 customer_1 -14.973612963687252
resNode: customer_4 deliver_cap: 51.83122260447478 cap_limit: 40
920 customer_1 ('customer_1', 'customer_5')
227 customer_1 -14.973612963687252
resNode: customer_5 deliver_cap: 42.2707287363325 cap_limit: 40
921 customer_2 ('customer_2', 'customer_3')
229 customer_2 -13.147372831877234
resNode: customer_3 deliver_cap: 43.93733114868955 cap_limit: 40
922 customer_2 ('customer_2', 'customer_1')
229 customer_2 -13.147372831877234
resNode: customer_1 deliver_cap: 33.86974204972154 cap_limit: 40
923 customer_2 ('customer_2', 'depot_t')
229 customer_2 -13.147372831877234
resNode: depot_t deliver_cap: 21.098260661722822 cap_limit: 40
924 customer_2 ('customer_2', 'customer_4')
229 customer_2 -13.147372831877234
resNode: customer_4 deliver_cap: 43.7652924318311 cap_limit: 40
925 customer_2 ('customer_2', 'customer_5')
229 customer_2 -13.147372831877234
resNode: customer_5 deliver_cap: 30.72272749701385 cap_limit: 40
926 customer_4 ('customer_4', 'customer_3')
230 customer_4 -21.16693050714425
resNode: customer_3 deliver_cap: 54.34856894375968 cap_limit: 40
927 customer_4 ('customer_4', 'customer_1')
230 customer_4 -21.16693050714425
resNode: customer_1 deliver_cap: 51.65674916446674 cap_limit: 40
928 customer_4 ('customer_4', 'depot_t')
230 customer_4 -21.16693050714425
resNode: depot_t deliver_cap: 38.157534084135285 cap_limit: 40
929 customer_4 ('customer_4', 'customer_2')
230 customer_4 -21.16693050714425
resNode: customer_2 deliver_cap: 42.58012986122919 cap_limit: 40
930 customer_4 ('customer_4', 'customer_5')
230 customer_4 -21.16693050714425
resNode: customer_5 deliver_cap: 49.89831380233076 cap_limit: 40
931 customer_1 ('customer_1', 'customer_3')
231 customer_1 -8.208711954025743
resNode: customer_3 deliver_cap: 41.85769887135016 cap_limit: 40
932 customer_1 ('customer_1', 'depot_t')
231 customer_1 -8.208711954025743
resNode: depot_t deliver_cap: 21.553472213459163 cap_limit: 40
933 customer_1 ('customer_1', 'customer_2')
231 customer_1 -8.208711954025743
resNode: customer_2 deliver_cap: 24.632539672524757 cap_limit: 40
934 customer_1 ('customer_1', 'customer_4')
231 customer_1 -8.208711954025743
resNode: customer_4 deliver_cap: 41.518644934696795 cap_limit: 40
935 customer_1 ('customer_1', 'customer_5')
231 customer_1 -8.208711954025743
resNode: customer_5 deliver_cap: 34.00682832401357 cap_limit: 40
936 customer_2 ('customer_2', 'customer_3')
233 customer_2 -7.688266886777475
resNode: customer_3 deliver_cap: 37.84833396984556 cap_limit: 40
937 customer_2 ('customer_2', 'customer_1')
233 customer_2 -7.688266886777475
resNode: customer_1 deliver_cap: 27.05155437082361 cap_limit: 40
938 customer_2 ('customer_2', 'depot_t')
233 customer_2 -7.688266886777475
resNode: depot_t deliver_cap: 16.88542032421747 cap_limit: 40
939 customer_2 ('customer_2', 'customer_4')
233 customer_2 -7.688266886777475
resNode: customer_4 deliver_cap: 37.71316069231392 cap_limit: 40
940 customer_2 ('customer_2', 'customer_5')
233 customer_2 -7.688266886777475
resNode: customer_5 deliver_cap: 27.4654311006718 cap_limit: 40
941 customer_4 ('customer_4', 'customer_3')
234 customer_4 -11.788927501229837
resNode: customer_3 deliver_cap: 39.44123308167908 cap_limit: 40
942 customer_4 ('customer_4', 'customer_1')
234 customer_4 -11.788927501229837
resNode: customer_1 deliver_cap: 36.41026496928688 cap_limit: 40
943 customer_4 ('customer_4', 'depot_t')
234 customer_4 -11.788927501229837
resNode: depot_t deliver_cap: 25.554512202039476 cap_limit: 40
944 customer_4 ('customer_4', 'customer_2')
234 customer_4 -11.788927501229837
resNode: customer_2 deliver_cap: 29.278635516743094 cap_limit: 40
945 customer_4 ('customer_4', 'customer_5')
234 customer_4 -11.788927501229837
resNode: customer_5 deliver_cap: 35.77631708285526 cap_limit: 40
946 customer_5 ('customer_5', 'customer_3')
235 customer_5 -15.224301518632888
resNode: customer_3 deliver_cap: 45.498043452565604 cap_limit: 40
947 customer_5 ('customer_5', 'customer_1')
235 customer_5 -15.224301518632888
resNode: customer_1 deliver_cap: 36.40177437155871 cap_limit: 40
948 customer_5 ('customer_5', 'depot_t')
235 customer_5 -15.224301518632888
resNode: depot_t deliver_cap: 23.0595998577785 cap_limit: 40
949 customer_5 ('customer_5', 'customer_2')
235 customer_5 -15.224301518632888
resNode: customer_2 deliver_cap: 26.534231938056024 cap_limit: 40
950 customer_5 ('customer_5', 'customer_4')
235 customer_5 -15.224301518632888
resNode: customer_4 deliver_cap: 45.326004735707144 cap_limit: 40
951 customer_3 ('customer_3', 'customer_1')
236 customer_3 -9.857824259949318
resNode: customer_1 deliver_cap: 29.967456117372404 cap_limit: 40
952 customer_3 ('customer_3', 'depot_t')
236 customer_3 -9.857824259949318
resNode: depot_t deliver_cap: 20.809771789686643 cap_limit: 40
953 customer_3 ('customer_3', 'customer_2')
236 customer_3 -9.857824259949318
resNode: customer_2 deliver_cap: 24.632539672524754 cap_limit: 40
954 customer_3 ('customer_3', 'customer_4')
236 customer_3 -9.857824259949318
resNode: customer_4 deliver_cap: 35.44547353390894 cap_limit: 40
955 customer_3 ('customer_3', 'customer_5')
236 customer_3 -9.857824259949318
resNode: customer_5 deliver_cap: 32.70106995522187 cap_limit: 40
956 customer_2 ('customer_2', 'customer_3')
238 customer_2 -3.1991293351718983
resNode: customer_3 deliver_cap: 26.2016110293693 cap_limit: 40
957 customer_2 ('customer_2', 'customer_1')
238 customer_2 -3.1991293351718983
resNode: customer_1 deliver_cap: 16.079440207008947 cap_limit: 40
958 customer_2 ('customer_2', 'depot_t')
238 customer_2 -3.1991293351718983
resNode: depot_t deliver_cap: 8.986586594033907 cap_limit: 40
959 customer_2 ('customer_2', 'customer_4')
238 customer_2 -3.1991293351718983
resNode: customer_4 deliver_cap: 26.10330319116447 cap_limit: 40
960 customer_2 ('customer_2', 'customer_5')
238 customer_2 -3.1991293351718983
resNode: customer_5 deliver_cap: 18.65040894269747 cap_limit: 40
961 customer_4 ('customer_4', 'customer_3')
239 customer_4 -9.746130079138275
resNode: customer_3 deliver_cap: 35.2415928747872 cap_limit: 40
962 customer_4 ('customer_4', 'customer_1')
239 customer_4 -9.746130079138275
resNode: customer_1 deliver_cap: 29.57259459317233 cap_limit: 40
963 customer_4 ('customer_4', 'depot_t')
239 customer_4 -9.746130079138275
resNode: depot_t deliver_cap: 20.594010193634496 cap_limit: 40
964 customer_4 ('customer_4', 'customer_2')
239 customer_4 -9.746130079138275
resNode: customer_2 deliver_cap: 24.3859549913223 cap_limit: 40
965 customer_4 ('customer_4', 'customer_5')
239 customer_4 -9.746130079138275
resNode: customer_5 deliver_cap: 32.36201601856849 cap_limit: 40
966 customer_5 ('customer_5', 'customer_3')
240 customer_5 -10.876565710181094
resNode: customer_3 deliver_cap: 35.23310227705903 cap_limit: 40
967 customer_5 ('customer_5', 'customer_1')
240 customer_5 -10.876565710181094
resNode: customer_1 deliver_cap: 26.099210135191008 cap_limit: 40
968 customer_5 ('customer_5', 'depot_t')
240 customer_5 -10.876565710181094
resNode: depot_t deliver_cap: 15.813763259563354 cap_limit: 40
969 customer_5 ('customer_5', 'customer_2')
240 customer_5 -10.876565710181094
resNode: customer_2 deliver_cap: 18.92281563809814 cap_limit: 40
970 customer_5 ('customer_5', 'customer_4')
240 customer_5 -10.876565710181094
resNode: customer_4 deliver_cap: 35.0979289995274 cap_limit: 40
971 customer_3 ('customer_3', 'customer_1')
241 customer_3 -11.73977358212742
resNode: customer_1 deliver_cap: 36.61414562840861 cap_limit: 40
972 customer_3 ('customer_3', 'depot_t')
241 customer_3 -11.73977358212742
resNode: depot_t deliver_cap: 25.554512202039476 cap_limit: 40
973 customer_3 ('customer_3', 'customer_2')
241 customer_3 -11.73977358212742
resNode: customer_2 deliver_cap: 29.278635516743094 cap_limit: 40
974 customer_3 ('customer_3', 'customer_4')
241 customer_3 -11.73977358212742
resNode: customer_4 deliver_cap: 39.269194364820635 cap_limit: 40
975 customer_3 ('customer_3', 'customer_5')
241 customer_3 -11.73977358212742
resNode: customer_5 deliver_cap: 35.77631708285526 cap_limit: 40
976 customer_1 ('customer_1', 'customer_3')
242 customer_1 -8.140333109563205
resNode: customer_3 deliver_cap: 41.51864493469679 cap_limit: 40
977 customer_1 ('customer_1', 'depot_t')
242 customer_1 -8.140333109563205
resNode: depot_t deliver_cap: 21.337710617407016 cap_limit: 40
978 customer_1 ('customer_1', 'customer_2')
242 customer_1 -8.140333109563205
resNode: customer_2 deliver_cap: 24.385954991322304 cap_limit: 40
979 customer_1 ('customer_1', 'customer_4')
242 customer_1 -8.140333109563205
resNode: customer_4 deliver_cap: 41.179590998043416 cap_limit: 40
980 customer_1 ('customer_1', 'customer_5')
242 customer_1 -8.140333109563205

1049 customer_5 ('customer_5', 'customer_2')
260 customer_5 -16.91346527396339
resNode: customer_2 deliver_cap: 31.30642061257722 cap_limit: 40
1050 customer_5 ('customer_5', 'customer_4')
260 customer_5 -16.91346527396339
resNode: customer_4 deliver_cap: 51.399699412370495 cap_limit: 40
1051 customer_3 ('customer_3', 'customer_1')
261 customer_3 -14.846417728260635
resNode: customer_1 deliver_cap: 42.687317029196464 cap_limit: 40
1052 customer_3 ('customer_3', 'depot_t')
261 customer_3 -14.846417728260635
resNode: depot_t deliver_cap: 31.075577111846613 cap_limit: 40
1053 customer_3 ('customer_3', 'customer_2')
261 customer_3 -14.846417728260635
resNode: customer_2 deliver_cap: 35.35180691753094 cap_limit: 40
1054 customer_3 ('customer_3', 'customer_4')
261 customer_3 -14.846417728260635
resNode: customer_4 deliver_cap: 46.99868523855062 cap_limit: 40
1055 customer_3 ('customer_3', 'customer_5')
261 customer_3 -14.846417728260635
resNode: customer_5 deliver_cap: 43.50580795658526 cap_limit: 40
1056 customer_1 ('customer_1', 'customer_3')
262 customer_1 -7.658285064321778
resNode: customer_3 deliver_cap: 41.51864493469679 cap_limit: 40
1057 customer_1 ('customer_1', 'depot_t')
262 customer_1 -7.658285064321778
resNode: depot_t deliver_cap: 21.337710617407016 cap_limit: 40
1058 customer_1 ('customer_1', 'customer_2')
262 customer_1 -7.658285064321778
resNode: customer_2 deliver_cap: 24.385954991322304 cap_limit: 40
1059 customer_1 ('customer_1', 'customer_4')
262 customer_1 -7.658285064321778
resNode: customer_4 deliver_cap: 41.179590998043416 cap_limit: 40
1060 customer_1 ('customer_1', 'customer_5')
262 customer_1 -7.658285064321778
resNode: customer_5 deliver_cap: 33.6677743873602 cap_limit: 40
1061 customer_4 ('customer_4', 'customer_3')
264 customer_4 -14.832081168522429
resNode: customer_3 deliver_cap: 46.99868523855062 cap_limit: 40
1062 customer_4 ('customer_4', 'customer_1')
264 customer_4 -14.832081168522429
resNode: customer_1 deliver_cap: 42.34826309254309 cap_limit: 40
1063 customer_4 ('customer_4', 'depot_t')
264 customer_4 -14.832081168522429
resNode: depot_t deliver_cap: 30.952692314090573 cap_limit: 40
1064 customer_4 ('customer_4', 'customer_2')
264 customer_4 -14.832081168522429
resNode: customer_2 deliver_cap: 35.2166336399993 cap_limit: 40
1065 customer_4 ('customer_4', 'customer_5')
264 customer_4 -14.832081168522429
resNode: customer_5 deliver_cap: 43.333769239726806 cap_limit: 40
1066 customer_5 ('customer_5', 'customer_3')
265 customer_5 -13.83367163281568
resNode: customer_3 deliver_cap: 43.50580795658526 cap_limit: 40
1067 customer_5 ('customer_5', 'customer_1')
265 customer_5 -13.83367163281568
resNode: customer_1 deliver_cap: 34.836446481859866 cap_limit: 40
1068 customer_5 ('customer_5', 'depot_t')
265 customer_5 -13.83367163281568
resNode: depot_t deliver_cap: 21.63657450350683 cap_limit: 40
1069 customer_5 ('customer_5', 'customer_2')
265 customer_5 -13.83367163281568
resNode: customer_2 deliver_cap: 24.96890404835718 cap_limit: 40
1070 customer_5 ('customer_5', 'customer_4')
265 customer_5 -13.83367163281568
resNode: customer_4 deliver_cap: 43.333769239726806 cap_limit: 40
1071 customer_3 ('customer_3', 'customer_1')
266 customer_3 -20.785969936975203
resNode: customer_1 deliver_cap: 51.65674916446674 cap_limit: 40
1072 customer_3 ('customer_3', 'depot_t')
266 customer_3 -20.785969936975203
resNode: depot_t deliver_cap: 37.916584214264155 cap_limit: 40
1073 customer_3 ('customer_3', 'customer_2')
266 customer_3 -20.785969936975203
resNode: customer_2 deliver_cap: 42.320645385983354 cap_limit: 40
1074 customer_3 ('customer_3', 'customer_4')
266 customer_3 -20.785969936975203
resNode: customer_4 deliver_cap: 53.82457649620447 cap_limit: 40
1075 customer_3 ('customer_3', 'customer_5')
266 customer_3 -20.785969936975203
resNode: customer_5 deliver_cap: 49.583225510960816 cap_limit: 40
1076 customer_1 ('customer_1', 'customer_3')
267 customer_1 -14.684686043261946
resNode: customer_3 deliver_cap: 51.83122260447478 cap_limit: 40
1077 customer_1 ('customer_1', 'depot_t')
267 customer_1 -14.684686043261946
resNode: depot_t deliver_cap: 29.76052293158584 cap_limit: 40
1078 customer_1 ('customer_1', 'customer_2')
267 customer_1 -14.684686043261946
resNode: customer_2 deliver_cap: 32.73657522474442 cap_limit: 40
1079 customer_1 ('customer_1', 'customer_4')
267 customer_1 -14.684686043261946
resNode: customer_4 deliver_cap: 51.399699412370495 cap_limit: 40
1080 customer_1 ('customer_1', 'customer_5')
267 customer_1 -14.684686043261946
resNode: customer_5 deliver_cap: 41.839205544228214 cap_limit: 40
1081 customer_2 ('customer_2', 'customer_3')
269 customer_2 -12.858445911451927
resNode: customer_3 deliver_cap: 43.50580795658526 cap_limit: 40
1082 customer_2 ('customer_2', 'customer_1')
269 customer_2 -12.858445911451927
resNode: customer_1 deliver_cap: 33.530688113068166 cap_limit: 40
1083 customer_2 ('customer_2', 'depot_t')
269 customer_2 -12.858445911451927
resNode: depot_t deliver_cap: 20.790029810219757 cap_limit: 40
1084 customer_2 ('customer_2', 'customer_4')
269 customer_2 -12.858445911451927
resNode: customer_4 deliver_cap: 43.333769239726806 cap_limit: 40
1085 customer_2 ('customer_2', 'customer_5')
269 customer_2 -12.858445911451927
resNode: customer_5 deliver_cap: 30.291204304909556 cap_limit: 40
1086 customer_4 ('customer_4', 'customer_3')
270 customer_4 -20.762417017405298
resNode: customer_3 deliver_cap: 53.82457649620447 cap_limit: 40
1087 customer_4 ('customer_4', 'customer_1')
270 customer_4 -20.762417017405298
resNode: customer_1 deliver_cap: 51.22522597236245 cap_limit: 40
1088 customer_4 ('customer_4', 'depot_t')
270 customer_4 -20.762417017405298
resNode: depot_t deliver_cap: 37.75683397718131 cap_limit: 40
1089 customer_4 ('customer_4', 'customer_2')
270 customer_4 -20.762417017405298
resNode: customer_2 deliver_cap: 42.1486066691249 cap_limit: 40
1090 customer_4 ('customer_4', 'customer_5')
270 customer_4 -20.762417017405298
resNode: customer_5 deliver_cap: 49.374321354775546 cap_limit: 40
1091 customer_1 ('customer_1', 'customer_3')
271 customer_1 -13.039489972596552
resNode: customer_3 deliver_cap: 52.26274579657907 cap_limit: 40
1092 customer_1 ('customer_1', 'depot_t')
271 customer_1 -13.039489972596552
resNode: depot_t deliver_cap: 30.0687537830889 cap_limit: 40
1093 customer_1 ('customer_1', 'customer_2')
271 customer_1 -13.039489972596552
resNode: customer_2 deliver_cap: 33.07562916139779 cap_limit: 40
1094 customer_1 ('customer_1', 'customer_4')
271 customer_1 -13.039489972596552
resNode: customer_4 deliver_cap: 51.83122260447478 cap_limit: 40
1095 customer_1 ('customer_1', 'customer_5')
271 customer_1 -13.039489972596552
resNode: customer_5 deliver_cap: 42.2707287363325 cap_limit: 40
1096 customer_2 ('customer_2', 'customer_3')
273 customer_2 -12.018896488643815
resNode: customer_3 deliver_cap: 47.15991774011867 cap_limit: 40
1097 customer_2 ('customer_2', 'customer_1')
273 customer_2 -12.018896488643815
resNode: customer_1 deliver_cap: 36.40177437155871 cap_limit: 40
1098 customer_2 ('customer_2', 'depot_t')
273 customer_2 -12.018896488643815
resNode: depot_t deliver_cap: 23.400108227029335 cap_limit: 40
1099 customer_2 ('customer_2', 'customer_4')
273 customer_2 -12.018896488643815
resNode: customer_4 deliver_cap: 46.98787902326021 cap_limit: 40
1100 customer_2 ('customer_2', 'customer_5')
273 customer_2 -12.018896488643815
resNode: customer_5 deliver_cap: 33.94531408844297 cap_limit: 40
1101 customer_4 ('customer_4', 'customer_3')
274 customer_4 -15.956273037816768
resNode: customer_3 deliver_cap: 46.66566051203205 cap_limit: 40
1102 customer_4 ('customer_4', 'customer_1')
274 customer_4 -15.956273037816768
resNode: customer_1 deliver_cap: 45.32964810304398 cap_limit: 40
1103 customer_4 ('customer_4', 'depot_t')
274 customer_4 -15.956273037816768
resNode: depot_t deliver_cap: 32.282368812814155 cap_limit: 40
1104 customer_4 ('customer_4', 'customer_2')
274 customer_4 -15.956273037816768
resNode: customer_2 deliver_cap: 36.25302879980644 cap_limit: 40
1105 customer_4 ('customer_4', 'customer_5')
274 customer_4 -15.956273037816768
resNode: customer_5 deliver_cap: 42.21540537060312 cap_limit: 40
1106 customer_5 ('customer_5', 'customer_3')
275 customer_5 -19.204528629400244
resNode: customer_3 deliver_cap: 54.02035881953711 cap_limit: 40
1107 customer_5 ('customer_5', 'customer_1')
275 customer_5 -19.204528629400244
resNode: customer_1 deliver_cap: 45.318841887753585 cap_limit: 40
1108 customer_5 ('customer_5', 'depot_t')
275 customer_5 -19.204528629400244
resNode: depot_t deliver_cap: 29.03898276527489 cap_limit: 40
1109 customer_5 ('customer_5', 'customer_2')
275 customer_5 -19.204528629400244
resNode: customer_2 deliver_cap: 32.760151517841074 cap_limit: 40
1110 customer_5 ('customer_5', 'customer_4')
275 customer_5 -19.204528629400244
resNode: customer_4 deliver_cap: 53.81145466335184 cap_limit: 40
1111 customer_3 ('customer_3', 'customer_1')
276 customer_3 -15.499209887162223
resNode: customer_1 deliver_cap: 41.71689764185501 cap_limit: 40
1112 customer_3 ('customer_3', 'depot_t')
276 customer_3 -15.499209887162223
resNode: depot_t deliver_cap: 30.193377668808928 cap_limit: 40
1113 customer_3 ('customer_3', 'customer_2')
276 customer_3 -15.499209887162223
resNode: customer_2 deliver_cap: 34.38138753018949 cap_limit: 40
1114 customer_3 ('customer_3', 'customer_4')
276 customer_3 -15.499209887162223
resNode: customer_4 deliver_cap: 45.763606018297864 cap_limit: 40
1115 customer_3 ('customer_3', 'customer_5')
276 customer_3 -15.499209887162223
resNode: customer_5 deliver_cap: 42.2707287363325 cap_limit: 40
1116 customer_2 ('customer_2', 'customer_3')
278 customer_2 -8.121456947114229
resNode: customer_3 deliver_cap: 36.53886064585074 cap_limit: 40
1117 customer_2 ('customer_2', 'customer_1')
278 customer_2 -8.121456947114229
resNode: customer_1 deliver_cap: 26.09921013519101 cap_limit: 40
1118 customer_2 ('customer_2', 'depot_t')
278 customer_2 -8.121456947114229
resNode: depot_t deliver_cap: 16.052119118038945 cap_limit: 40
1119 customer_2 ('customer_2', 'customer_4')
278 customer_2 -8.121456947114229
resNode: customer_4 deliver_cap: 36.403687368319105 cap_limit: 40
1120 customer_2 ('customer_2', 'customer_5')
278 customer_2 -8.121456947114229
resNode: customer_5 deliver_cap: 26.155957776676978 cap_limit: 40
1121 customer_4 ('customer_4', 'customer_3')
279 customer_4 -15.36439839248845
resNode: customer_3 deliver_cap: 45.50412154305202 cap_limit: 40
1122 customer_4 ('customer_4', 'customer_1')
279 customer_4 -15.36439839248845
resNode: customer_1 deliver_cap: 41.173963046079905 cap_limit: 40
1123 customer_4 ('customer_4', 'depot_t')
279 customer_4 -15.36439839248845
resNode: depot_t deliver_cap: 29.88514681730586 cap_limit: 40
1124 customer_4 ('customer_4', 'customer_2')
279 customer_4 -15.36439839248845
resNode: customer_2 deliver_cap: 34.04233359353612 cap_limit: 40
1125 customer_4 ('customer_4', 'customer_5')
279 customer_4 -15.36439839248845
resNode: customer_5 deliver_cap: 41.83920554422821 cap_limit: 40
1126 customer_5 ('customer_5', 'customer_3')
280 customer_5 -15.982664709166503
resNode: customer_3 deliver_cap: 45.49331532776162 cap_limit: 40
1127 customer_5 ('customer_5', 'customer_1')
280 customer_5 -15.982664709166503
resNode: customer_1 deliver_cap: 36.39805941635559 cap_limit: 40
1128 customer_5 ('customer_5', 'depot_t')
280 customer_5 -15.982664709166503
resNode: depot_t deliver_cap: 23.05622262577566 cap_limit: 40
1129 customer_5 ('customer_5', 'customer_2')
280 customer_5 -15.982664709166503
resNode: customer_2 deliver_cap: 26.530516982852898 cap_limit: 40
1130 customer_5 ('customer_5', 'customer_4')
280 customer_5 -15.982664709166503
resNode: customer_4 deliver_cap: 45.321276610903176 cap_limit: 40
1131 customer_3 ('customer_3', 'customer_1')
281 customer_3 -12.05022194917359
resNode: customer_1 deliver_cap: 35.175500418513245 cap_limit: 40
1132 customer_3 ('customer_3', 'depot_t')
281 customer_3 -12.05022194917359
resNode: depot_t deliver_cap: 24.24665292031641 cap_limit: 40
1133 customer_3 ('customer_3', 'customer_2')
281 customer_3 -12.05022194917359
resNode: customer_2 deliver_cap: 27.839990306847724 cap_limit: 40
1134 customer_3 ('customer_3', 'customer_4')
281 customer_3 -12.05022194917359
resNode: customer_4 deliver_cap: 37.43819137040834 cap_limit: 40
1135 customer_3 ('customer_3', 'customer_5')
281 customer_3 -12.05022194917359
resNode: customer_5 deliver_cap: 33.94531408844298 cap_limit: 40
1136 customer_1 ('customer_1', 'customer_3')
282 customer_1 -7.422935857058559
resNode: customer_3 deliver_cap: 34.00682832401357 cap_limit: 40
1137 customer_1 ('customer_1', 'depot_t')
282 customer_1 -7.422935857058559
resNode: depot_t deliver_cap: 16.557463683335875 cap_limit: 40
1138 customer_1 ('customer_1', 'customer_2')
282 customer_1 -7.422935857058559
resNode: customer_2 deliver_cap: 18.922815638098143 cap_limit: 40
1139 customer_1 ('customer_1', 'customer_4')
282 customer_1 -7.422935857058559
resNode: customer_4 deliver_cap: 33.6677743873602 cap_limit: 40
1140 customer_1 ('customer_1', 'customer_5')
282 customer_1 -7.422935857058559
resNode: customer_5 deliver_cap: 26.155957776676978 cap_limit: 40
1141 customer_4 ('customer_4', 'customer_3')
284 customer_4 -12.035885389435386
resNode: customer_3 deliver_cap: 37.43819137040834 cap_limit: 40
1142 customer_4 ('customer_4', 'customer_1')
284 customer_4 -12.035885389435386
resNode: customer_1 deliver_cap: 34.836446481859866 cap_limit: 40
1143 customer_4 ('customer_4', 'depot_t')
284 customer_4 -12.035885389435386
resNode: depot_t deliver_cap: 24.123768122560378 cap_limit: 40
1144 customer_4 ('customer_4', 'customer_2')
284 customer_4 -12.035885389435386
resNode: customer_2 deliver_cap: 27.704817029316086 cap_limit: 40
1145 customer_4 ('customer_4', 'customer_5')
284 customer_4 -12.035885389435386
resNode: customer_5 deliver_cap: 33.77327537158452 cap_limit: 40
1146 customer_5 ('customer_5', 'customer_3')
285 customer_5 -11.037475853728637
resNode: customer_3 deliver_cap: 33.94531408844298 cap_limit: 40
1147 customer_5 ('customer_5', 'customer_1')
285 customer_5 -11.037475853728637
resNode: customer_1 deliver_cap: 27.324629871176654 cap_limit: 40
1148 customer_5 ('customer_5', 'depot_t')
285 customer_5 -11.037475853728637
resNode: depot_t deliver_cap: 14.80765031197663 cap_limit: 40
1149 customer_5 ('customer_5', 'customer_2')
285 customer_5 -11.037475853728637
resNode: customer_2 deliver_cap: 17.457087437673966 cap_limit: 40
1150 customer_5 ('customer_5', 'customer_4')
285 customer_5 -11.037475853728637
resNode: customer_4 deliver_cap: 33.773275371584525 cap_limit: 40
1151 customer_3 ('customer_3', 'customer_1')
286 customer_3 -15.90711911871435
resNode: customer_1 deliver_cap: 45.58913257828982 cap_limit: 40
1152 customer_3 ('customer_3', 'depot_t')
286 customer_3 -15.90711911871435
resNode: depot_t deliver_cap: 32.282368812814155 cap_limit: 40
1153 customer_3 ('customer_3', 'customer_2')
286 customer_3 -15.90711911871435
resNode: customer_2 deliver_cap: 36.25302879980644 cap_limit: 40
1154 customer_3 ('customer_3', 'customer_4')
286 customer_3 -15.90711911871435
resNode: customer_4 deliver_cap: 46.45675635584679 cap_limit: 40
1155 customer_3 ('customer_3', 'customer_5')
286 customer_3 -15.90711911871435
resNode: customer_5 deliver_cap: 42.21540537060312 cap_limit: 40
1156 customer_1 ('customer_1', 'customer_3')
287 customer_1 -12.947993814271284
resNode: customer_3 deliver_cap: 51.831222604474775 cap_limit: 40
1157 customer_1 ('customer_1', 'depot_t')
287 customer_1 -12.947993814271284
resNode: depot_t deliver_cap: 29.760522931585832 cap_limit: 40
1158 customer_1 ('customer_1', 'customer_2')
287 customer_1 -12.947993814271284
resNode: customer_2 deliver_cap: 32.73657522474441 cap_limit: 40
1159 customer_1 ('customer_1', 'customer_4')
287 customer_1 -12.947993814271284
resNode: customer_4 deliver_cap: 51.39969941237048 cap_limit: 40
1160 customer_1 ('customer_1', 'customer_5')
287 customer_1 -12.947993814271284
resNode: customer_5 deliver_cap: 41.8392055442282 cap_limit: 40
1161 customer_2 ('customer_2', 'customer_3')
289 customer_2 -11.992271449130007
resNode: customer_3 deliver_cap: 46.98787902326021 cap_limit: 40
1162 customer_2 ('customer_2', 'customer_1')
289 customer_2 -11.992271449130007
resNode: customer_1 deliver_cap: 36.26660109402707 cap_limit: 40
1163 customer_2 ('customer_2', 'depot_t')
289 customer_2 -11.992271449130007
resNode: depot_t deliver_cap: 23.2772234292733 cap_limit: 40
1164 customer_2 ('customer_2', 'customer_4')
289 customer_2 -11.992271449130007
resNode: customer_4 deliver_cap: 46.81584030640176 cap_limit: 40
1165 customer_2 ('customer_2', 'customer_5')
289 customer_2 -11.992271449130007
resNode: customer_5 deliver_cap: 33.77327537158452 cap_limit: 40
1166 customer_5 ('customer_5', 'customer_3')
290 customer_5 -19.131821790727923
resNode: customer_3 deliver_cap: 53.81145466335184 cap_limit: 40
1167 customer_5 ('customer_5', 'customer_1')
290 customer_5 -19.131821790727923
resNode: customer_1 deliver_cap: 45.146803170895126 cap_limit: 40
1168 customer_5 ('customer_5', 'depot_t')
290 customer_5 -19.131821790727923
resNode: depot_t deliver_cap: 28.879232528192038 cap_limit: 40
1169 customer_5 ('customer_5', 'customer_2')
290 customer_5 -19.131821790727923
resNode: customer_2 deliver_cap: 32.588112800982614 cap_limit: 40
1170 customer_5 ('customer_5', 'customer_4')
290 customer_5 -19.131821790727923
resNode: customer_4 deliver_cap: 53.60255050716657 cap_limit: 40
1171 customer_3 ('customer_3', 'customer_1')
291 customer_3 -9.533195591000982
resNode: customer_1 deliver_cap: 39.70022575568891 cap_limit: 40
1172 customer_3 ('customer_3', 'depot_t')
291 customer_3 -9.533195591000982
resNode: depot_t deliver_cap: 28.36003959047611 cap_limit: 40
1173 customer_3 ('customer_3', 'customer_2')
291 customer_3 -9.533195591000982
resNode: customer_2 deliver_cap: 32.36471564402339 cap_limit: 40
1174 customer_3 ('customer_3', 'customer_4')
291 customer_3 -9.533195591000982
resNode: customer_4 deliver_cap: 43.19693270863191 cap_limit: 40
1175 customer_3 ('customer_3', 'customer_5')
291 customer_3 -9.533195591000982
resNode: customer_5 deliver_cap: 39.70405542666656 cap_limit: 40
1176 customer_2 ('customer_2', 'customer_3')
293 customer_2 -2.8429444303277975
resNode: customer_3 deliver_cap: 34.52218875968464 cap_limit: 40
1177 customer_2 ('customer_2', 'customer_1')
293 customer_2 -2.8429444303277975
resNode: customer_1 deliver_cap: 24.632539672524754 cap_limit: 40
1178 customer_2 ('customer_2', 'depot_t')
293 customer_2 -2.8429444303277975
resNode: depot_t deliver_cap: 14.768782463205973 cap_limit: 40
1179 customer_2 ('customer_2', 'customer_4')
293 customer_2 -2.8429444303277975
resNode: customer_4 deliver_cap: 34.387015482153 cap_limit: 40
1180 customer_2 ('customer_2', 'customer_5')
293 customer_2 -2.8429444303277975
resNode: customer_5 deliver_cap: 24.139285890510877 cap_limit: 40
1181 customer_4 ('customer_4', 'customer_3')
294 customer_4 -9.398384096327213
resNode: customer_3 deliver_cap: 42.93744823338608 cap_limit: 40
1182 customer_4 ('customer_4', 'customer_1')
294 customer_4 -9.398384096327213
resNode: customer_1 deliver_cap: 39.15729115991381 cap_limit: 40
1183 customer_4 ('customer_4', 'depot_t')
294 customer_4 -9.398384096327213
resNode: depot_t deliver_cap: 28.051808738973047 cap_limit: 40
1184 customer_4 ('customer_4', 'customer_2')
294 customer_4 -9.398384096327213
resNode: customer_2 deliver_cap: 32.02566170737002 cap_limit: 40
1185 customer_4 ('customer_4', 'customer_5')
294 customer_4 -9.398384096327213
resNode: customer_5 deliver_cap: 39.27253223456226 cap_limit: 40
1186 customer_5 ('customer_5', 'customer_3')
295 customer_5 -10.016650413005266
resNode: customer_3 deliver_cap: 42.92664201809568 cap_limit: 40
1187 customer_5 ('customer_5', 'customer_1')
295 customer_5 -10.016650413005266
resNode: customer_1 deliver_cap: 34.38138753018949 cap_limit: 40

313 customer_2 -4.677981842194505
resNode: customer_1 deliver_cap: 24.632539672524757 cap_limit: 40
1258 customer_2 ('customer_2', 'depot_t')
313 customer_2 -4.677981842194505
resNode: depot_t deliver_cap: 14.768782463205973 cap_limit: 40
1259 customer_2 ('customer_2', 'customer_4')
313 customer_2 -4.677981842194505
resNode: customer_4 deliver_cap: 34.387015482153 cap_limit: 40
1260 customer_2 ('customer_2', 'customer_5')
313 customer_2 -4.677981842194505
resNode: customer_5 deliver_cap: 24.139285890510877 cap_limit: 40
1261 customer_4 ('customer_4', 'customer_3')
314 customer_4 -7.64472931681928
resNode: customer_3 deliver_cap: 35.20795735965609 cap_limit: 40
1262 customer_4 ('customer_4', 'customer_1')
314 customer_4 -7.64472931681928
resNode: customer_1 deliver_cap: 33.08411975912596 cap_limit: 40
1263 customer_4 ('customer_4', 'depot_t')
314 customer_4 -7.64472931681928
resNode: depot_t deliver_cap: 22.53074382916591 cap_limit: 40
1264 customer_4 ('customer_4', 'customer_2')
314 customer_4 -7.64472931681928
resNode: customer_2 deliver_cap: 25.952490306582174 cap_limit: 40
1265 customer_4 ('customer_4', 'customer_5')
314 customer_4 -7.64472931681928
resNode: customer_5 deliver_cap: 31.54304136083227 cap_limit: 40
1266 customer_5 ('customer_5', 'customer_3')
315 customer_5 -11.08010333422233
resNode: customer_3 deliver_cap: 41.26476773054261 cap_limit: 40
1267 customer_5 ('customer_5', 'customer_1')
315 customer_5 -11.08010333422233
resNode: customer_1 deliver_cap: 33.07562916139779 cap_limit: 40
1268 customer_5 ('customer_5', 'depot_t')
315 customer_5 -11.08010333422233
resNode: depot_t deliver_cap: 20.035831484904936 cap_limit: 40
1269 customer_5 ('customer_5', 'customer_2')
315 customer_5 -11.08010333422233
resNode: customer_2 deliver_cap: 23.208086727895104 cap_limit: 40
1270 customer_5 ('customer_5', 'customer_4')
315 customer_5 -11.08010333422233
resNode: customer_4 deliver_cap: 41.092729013684156 cap_limit: 40
1271 customer_3 ('customer_3', 'customer_1')
316 customer_3 -5.3983027400965575
resNode: customer_1 deliver_cap: 24.632539672524757 cap_limit: 40
1272 customer_3 ('customer_3', 'depot_t')
316 customer_3 -5.3983027400965575
resNode: depot_t deliver_cap: 16.14171990044495 cap_limit: 40
1273 customer_3 ('customer_3', 'customer_2')
316 customer_3 -5.3983027400965575
resNode: customer_2 deliver_cap: 19.297623227677107 cap_limit: 40
1274 customer_3 ('customer_3', 'customer_4')
316 customer_3 -5.3983027400965575
resNode: customer_4 deliver_cap: 28.109963422243425 cap_limit: 40
1275 customer_3 ('customer_3', 'customer_5')
316 customer_3 -5.3983027400965575
resNode: customer_5 deliver_cap: 25.36555984355635 cap_limit: 40
1276 customer_1 ('customer_1', 'customer_3')
317 customer_1 -1.2606465493852737
resNode: customer_3 deliver_cap: 23.782596331070447 cap_limit: 40
1277 customer_1 ('customer_1', 'depot_t')
317 customer_1 -1.2606465493852737
resNode: depot_t deliver_cap: 8.986586594033907 cap_limit: 40
1278 customer_1 ('customer_1', 'customer_2')
317 customer_1 -1.2606465493852737
resNode: customer_2 deliver_cap: 11.233233242542385 cap_limit: 40
1279 customer_1 ('customer_1', 'customer_4')
317 customer_1 -1.2606465493852737
resNode: customer_4 deliver_cap: 23.536011649867994 cap_limit: 40
1280 customer_1 ('customer_1', 'customer_5')
317 customer_1 -1.2606465493852737
resNode: customer_5 deliver_cap: 18.072872296643833 cap_limit: 40
1281 customer_4 ('customer_4', 'customer_3')
319 customer_4 -5.393182540190056
resNode: customer_3 deliver_cap: 28.109963422243425 cap_limit: 40
1282 customer_4 ('customer_4', 'customer_1')
319 customer_4 -5.393182540190056
resNode: customer_1 deliver_cap: 24.385954991322304 cap_limit: 40
1283 customer_4 ('customer_4', 'depot_t')
319 customer_4 -5.393182540190056
resNode: depot_t deliver_cap: 16.05570054201572 cap_limit: 40
1284 customer_4 ('customer_4', 'customer_2')
319 customer_4 -5.393182540190056
resNode: customer_2 deliver_cap: 19.199315389472275 cap_limit: 40
1285 customer_4 ('customer_4', 'customer_5')
319 customer_4 -5.393182540190056
resNode: customer_5 deliver_cap: 25.230386566024706 cap_limit: 40
1286 customer_5 ('customer_5', 'customer_3')
320 customer_5 -5.093481840277088
resNode: customer_3 deliver_cap: 25.36555984355635 cap_limit: 40
1287 customer_5 ('customer_5', 'customer_1')
320 customer_5 -5.093481840277088
resNode: customer_1 deliver_cap: 18.922815638098143 cap_limit: 40
1288 customer_5 ('customer_5', 'depot_t')
320 customer_5 -5.093481840277088
resNode: depot_t deliver_cap: 9.534418074607101 cap_limit: 40
1289 customer_5 ('customer_5', 'customer_2')
320 customer_5 -5.093481840277088
resNode: customer_2 deliver_cap: 11.746421141005282 cap_limit: 40
1290 customer_5 ('customer_5', 'customer_4')
320 customer_5 -5.093481840277088
resNode: customer_4 deliver_cap: 25.230386566024706 cap_limit: 40
1291 customer_3 ('customer_3', 'customer_1')
321 customer_3 -7.400962041282487
resNode: customer_1 deliver_cap: 33.08411975912596 cap_limit: 40
1292 customer_3 ('customer_3', 'depot_t')
321 customer_3 -7.400962041282487
resNode: depot_t deliver_cap: 22.345397775418885 cap_limit: 40
1293 customer_3 ('customer_3', 'customer_2')
321 customer_3 -7.400962041282487
resNode: customer_2 deliver_cap: 25.748609647460444 cap_limit: 40
1294 customer_3 ('customer_3', 'customer_4')
321 customer_3 -7.400962041282487
resNode: customer_4 deliver_cap: 34.7764341675518 cap_limit: 40
1295 customer_3 ('customer_3', 'customer_5')
321 customer_3 -7.400962041282487
resNode: customer_5 deliver_cap: 31.28355688558643 cap_limit: 40
1296 customer_1 ('customer_1', 'customer_3')
322 customer_1 -5.004939478700992
resNode: customer_3 deliver_cap: 37.988619065414134 cap_limit: 40
1297 customer_1 ('customer_1', 'depot_t')
322 customer_1 -5.004939478700992
resNode: depot_t deliver_cap: 19.0913305187726 cap_limit: 40
1298 customer_1 ('customer_1', 'customer_2')
322 customer_1 -5.004939478700992
resNode: customer_2 deliver_cap: 21.81866345002583 cap_limit: 40
1299 customer_1 ('customer_1', 'customer_4')
322 customer_1 -5.004939478700992
resNode: customer_4 deliver_cap: 37.64956512876077 cap_limit: 40
1300 customer_1 ('customer_1', 'customer_5')
322 customer_1 -5.004939478700992
resNode: customer_5 deliver_cap: 30.137748518077547 cap_limit: 40
1301 customer_2 ('customer_2', 'customer_3')
324 customer_2 -4.5354645762331565
resNode: customer_3 deliver_cap: 34.183134823031274 cap_limit: 40
1302 customer_2 ('customer_2', 'customer_1')
324 customer_2 -4.5354645762331565
resNode: customer_1 deliver_cap: 24.385954991322304 cap_limit: 40
1303 customer_2 ('customer_2', 'depot_t')
324 customer_2 -4.5354645762331565
resNode: depot_t deliver_cap: 14.55302086715383 cap_limit: 40
1304 customer_2 ('customer_2', 'customer_4')
324 customer_2 -4.5354645762331565
resNode: customer_4 deliver_cap: 34.04796154549963 cap_limit: 40
1305 customer_2 ('customer_2', 'customer_5')
324 customer_2 -4.5354645762331565
resNode: customer_5 deliver_cap: 23.80023195385751 cap_limit: 40
1306 customer_5 ('customer_5', 'customer_3')
325 customer_5 -10.821999498947333
resNode: customer_3 deliver_cap: 40.833244538438315 cap_limit: 40
1307 customer_5 ('customer_5', 'customer_1')
325 customer_5 -10.821999498947333
resNode: customer_1 deliver_cap: 32.73657522474442 cap_limit: 40
1308 customer_5 ('customer_5', 'depot_t')
325 customer_5 -10.821999498947333
resNode: depot_t deliver_cap: 19.72760063340187 cap_limit: 40
1309 customer_5 ('customer_5', 'customer_2')
325 customer_5 -10.821999498947333
resNode: customer_2 deliver_cap: 22.869032791241732 cap_limit: 40
1310 customer_5 ('customer_5', 'customer_4')
325 customer_5 -10.821999498947333
resNode: customer_4 deliver_cap: 40.66120582157987 cap_limit: 40
1311 customer_3 ('customer_3', 'customer_1')
326 customer_3 -9.721442234458262
resNode: customer_1 deliver_cap: 33.07562916139779 cap_limit: 40
1312 customer_3 ('customer_3', 'depot_t')
326 customer_3 -9.721442234458262
resNode: depot_t deliver_cap: 22.337679050211456 cap_limit: 40
1313 customer_3 ('customer_3', 'customer_2')
326 customer_3 -9.721442234458262
resNode: customer_2 deliver_cap: 25.74011904973227 cap_limit: 40
1314 customer_3 ('customer_3', 'customer_4')
326 customer_3 -9.721442234458262
resNode: customer_4 deliver_cap: 34.765627952261404 cap_limit: 40
1315 customer_3 ('customer_3', 'customer_5')
326 customer_3 -9.721442234458262
resNode: customer_5 deliver_cap: 31.272750670296034 cap_limit: 40
1316 customer_1 ('customer_1', 'customer_3')
327 customer_1 -6.1364609358305175
resNode: customer_3 deliver_cap: 33.21271543568982 cap_limit: 40
1317 customer_1 ('customer_1', 'depot_t')
327 customer_1 -6.1364609358305175
resNode: depot_t deliver_cap: 16.052119118038945 cap_limit: 40
1318 customer_1 ('customer_1', 'customer_2')
327 customer_1 -6.1364609358305175
resNode: customer_2 deliver_cap: 18.34527899204451 cap_limit: 40
1319 customer_1 ('customer_1', 'customer_4')
327 customer_1 -6.1364609358305175
resNode: customer_4 deliver_cap: 32.873661499036444 cap_limit: 40
1320 customer_1 ('customer_1', 'customer_5')
327 customer_1 -6.1364609358305175
resNode: customer_5 deliver_cap: 25.361844888353225 cap_limit: 40
1321 customer_2 ('customer_2', 'customer_3')
329 customer_2 -4.983007788122958
resNode: customer_3 deliver_cap: 26.67131821234805 cap_limit: 40
1322 customer_2 ('customer_2', 'customer_1')
329 customer_2 -4.983007788122958
resNode: customer_1 deliver_cap: 18.922815638098143 cap_limit: 40
1323 customer_2 ('customer_2', 'depot_t')
329 customer_2 -4.983007788122958
resNode: depot_t deliver_cap: 9.772773933082691 cap_limit: 40
1324 customer_2 ('customer_2', 'customer_4')
329 customer_2 -4.983007788122958
resNode: customer_4 deliver_cap: 26.536144934816413 cap_limit: 40
1325 customer_2 ('customer_2', 'customer_5')
329 customer_2 -4.983007788122958
resNode: customer_5 deliver_cap: 16.288415343174293 cap_limit: 40
1326 customer_4 ('customer_4', 'customer_3')
330 customer_4 -9.707105674720058
resNode: customer_3 deliver_cap: 34.765627952261404 cap_limit: 40
1327 customer_4 ('customer_4', 'customer_1')
330 customer_4 -9.707105674720058
resNode: customer_1 deliver_cap: 32.73657522474441 cap_limit: 40
1328 customer_4 ('customer_4', 'depot_t')
330 customer_4 -9.707105674720058
resNode: depot_t deliver_cap: 22.214794252455413 cap_limit: 40
1329 customer_4 ('customer_4', 'customer_2')
330 customer_4 -9.707105674720058
resNode: customer_2 deliver_cap: 25.604945772200626 cap_limit: 40
1330 customer_4 ('customer_4', 'customer_5')
330 customer_4 -9.707105674720058
resNode: customer_5 deliver_cap: 31.10071195343758 cap_limit: 40
1331 customer_1 ('customer_1', 'customer_3')
331 customer_1 -3.6081782920569037
resNode: customer_3 deliver_cap: 43.19693270863192 cap_limit: 40
1332 customer_1 ('customer_1', 'depot_t')
331 customer_1 -3.6081782920569037
resNode: depot_t deliver_cap: 23.593173005983793 cap_limit: 40
1333 customer_1 ('customer_1', 'customer_2')
331 customer_1 -3.6081782920569037
resNode: customer_2 deliver_cap: 25.952490306582174 cap_limit: 40
1334 customer_1 ('customer_1', 'customer_4')
331 customer_1 -3.6081782920569037
resNode: customer_4 deliver_cap: 42.765409516527626 cap_limit: 40
1335 customer_1 ('customer_1', 'customer_5')
331 customer_1 -3.6081782920569037
resNode: customer_5 deliver_cap: 33.204915648385345 cap_limit: 40
1336 customer_2 ('customer_2', 'customer_3')
333 customer_2 -2.587584808104169
resNode: customer_3 deliver_cap: 38.09410465217153 cap_limit: 40
1337 customer_2 ('customer_2', 'customer_1')
333 customer_2 -2.587584808104169
resNode: customer_1 deliver_cap: 29.2786355167431 cap_limit: 40
1338 customer_2 ('customer_2', 'depot_t')
333 customer_2 -2.587584808104169
resNode: depot_t deliver_cap: 16.924527449924238 cap_limit: 40
1339 customer_2 ('customer_2', 'customer_4')
333 customer_2 -2.587584808104169
resNode: customer_4 deliver_cap: 37.92206593531307 cap_limit: 40
1340 customer_2 ('customer_2', 'customer_5')
333 customer_2 -2.587584808104169
resNode: customer_5 deliver_cap: 24.879501000495836 cap_limit: 40
1341 customer_4 ('customer_4', 'customer_3')
334 customer_4 -4.096618565862706
resNode: customer_3 deliver_cap: 35.65717319095338 cap_limit: 40
1342 customer_4 ('customer_4', 'customer_1')
334 customer_4 -4.096618565862706
resNode: customer_1 deliver_cap: 36.26383501509684 cap_limit: 40
1343 customer_4 ('customer_4', 'depot_t')
334 customer_4 -4.096618565862706
resNode: depot_t deliver_cap: 23.864113802577524 cap_limit: 40
1344 customer_4 ('customer_4', 'customer_2')
334 customer_4 -4.096618565862706
resNode: customer_2 deliver_cap: 27.187215711859295 cap_limit: 40
1345 customer_4 ('customer_4', 'customer_5')
334 customer_4 -4.096618565862706
resNode: customer_5 deliver_cap: 31.206918049524454 cap_limit: 40
1346 customer_5 ('customer_5', 'customer_3')
335 customer_5 -7.344874157446186
resNode: customer_3 deliver_cap: 43.011871498458426 cap_limit: 40
1347 customer_5 ('customer_5', 'customer_1')
335 customer_5 -7.344874157446186
resNode: customer_1 deliver_cap: 36.253028799806444 cap_limit: 40
1348 customer_5 ('customer_5', 'depot_t')
335 customer_5 -7.344874157446186
resNode: depot_t deliver_cap: 20.620727755038256 cap_limit: 40
1349 customer_5 ('customer_5', 'customer_2')
335 customer_5 -7.344874157446186
resNode: customer_2 deliver_cap: 23.694338429893932 cap_limit: 40
1350 customer_5 ('customer_5', 'customer_4')
335 customer_5 -7.344874157446186
resNode: customer_4 deliver_cap: 42.80296734227317 cap_limit: 40
1351 customer_3 ('customer_3', 'customer_1')
336 customer_3 -9.318407092074493
resNode: customer_1 deliver_cap: 39.36117181903554 cap_limit: 40
1352 customer_3 ('customer_3', 'depot_t')
336 customer_3 -9.318407092074493
resNode: depot_t deliver_cap: 28.051808738973047 cap_limit: 40
1353 customer_3 ('customer_3', 'customer_2')
336 customer_3 -9.318407092074493
resNode: customer_2 deliver_cap: 32.02566170737002 cap_limit: 40
1354 customer_3 ('customer_3', 'customer_4')
336 customer_3 -9.318407092074493
resNode: customer_4 deliver_cap: 42.765409516527626 cap_limit: 40
1355 customer_3 ('customer_3', 'customer_5')
336 customer_3 -9.318407092074493
resNode: customer_5 deliver_cap: 39.27253223456226 cap_limit: 40
1356 customer_2 ('customer_2', 'customer_3')
338 customer_2 -2.743742500714955
resNode: customer_3 deliver_cap: 34.183134823031274 cap_limit: 40
1357 customer_2 ('customer_2', 'customer_1')
338 customer_2 -2.743742500714955
resNode: customer_1 deliver_cap: 24.385954991322304 cap_limit: 40
1358 customer_2 ('customer_2', 'depot_t')
338 customer_2 -2.743742500714955
resNode: depot_t deliver_cap: 14.55302086715383 cap_limit: 40
1359 customer_2 ('customer_2', 'customer_4')
338 customer_2 -2.743742500714955
resNode: customer_4 deliver_cap: 34.04796154549963 cap_limit: 40
1360 customer_2 ('customer_2', 'customer_5')
338 customer_2 -2.743742500714955
resNode: customer_5 deliver_cap: 23.80023195385751 cap_limit: 40
1361 customer_4 ('customer_4', 'customer_3')
339 customer_4 -9.18359559740072
resNode: customer_3 deliver_cap: 42.5059250412818 cap_limit: 40
1362 customer_4 ('customer_4', 'customer_1')
339 customer_4 -9.18359559740072
resNode: customer_1 deliver_cap: 38.81823722326044 cap_limit: 40
1363 customer_4 ('customer_4', 'depot_t')
339 customer_4 -9.18359559740072
resNode: depot_t deliver_cap: 27.743577887469986 cap_limit: 40
1364 customer_4 ('customer_4', 'customer_2')
339 customer_4 -9.18359559740072
resNode: customer_2 deliver_cap: 31.686607770716655 cap_limit: 40
1365 customer_4 ('customer_4', 'customer_5')
339 customer_4 -9.18359559740072
resNode: customer_5 deliver_cap: 38.841009042457976 cap_limit: 40
1366 customer_5 ('customer_5', 'customer_3')
340 customer_5 -9.801861914078776
resNode: customer_3 deliver_cap: 42.49511882599139 cap_limit: 40
1367 customer_5 ('customer_5', 'customer_1')
340 customer_5 -9.801861914078776
resNode: customer_1 deliver_cap: 34.04233359353612 cap_limit: 40
1368 customer_5 ('customer_5', 'depot_t')
340 customer_5 -9.801861914078776
resNode: depot_t deliver_cap: 20.914653695939784 cap_limit: 40
1369 customer_5 ('customer_5', 'customer_2')
340 customer_5 -9.801861914078776
resNode: customer_2 deliver_cap: 24.174791160033433 cap_limit: 40
1370 customer_5 ('customer_5', 'customer_4')
340 customer_5 -9.801861914078776
resNode: customer_4 deliver_cap: 42.32308010913294 cap_limit: 40
1371 customer_3 ('customer_3', 'customer_1')
341 customer_3 -7.734814368376021
resNode: customer_1 deliver_cap: 35.55568757665268 cap_limit: 40
1372 customer_3 ('customer_3', 'depot_t')
341 customer_3 -7.734814368376021
resNode: depot_t deliver_cap: 24.59227760953408 cap_limit: 40
1373 customer_3 ('customer_3', 'customer_2')
341 customer_3 -7.734814368376021
resNode: customer_2 deliver_cap: 28.22017746498716 cap_limit: 40
1374 customer_3 ('customer_3', 'customer_4')
341 customer_3 -7.734814368376021
resNode: customer_4 deliver_cap: 37.92206593531307 cap_limit: 40
1375 customer_3 ('customer_3', 'customer_5')
341 customer_3 -7.734814368376021
resNode: customer_5 deliver_cap: 34.429188653347715 cap_limit: 40
1376 customer_1 ('customer_1', 'customer_3')
342 customer_1 -2.977919017804365
resNode: customer_3 deliver_cap: 34.387015482153004 cap_limit: 40
1377 customer_1 ('customer_1', 'depot_t')
342 customer_1 -2.977919017804365
resNode: depot_t deliver_cap: 16.799400965788244 cap_limit: 40
1378 customer_1 ('customer_1', 'customer_2')
342 customer_1 -2.977919017804365
resNode: customer_2 deliver_cap: 19.19931538947228 cap_limit: 40
1379 customer_1 ('customer_1', 'customer_4')
342 customer_1 -2.977919017804365
resNode: customer_4 deliver_cap: 34.04796154549963 cap_limit: 40
1380 customer_1 ('customer_1', 'customer_5')
342 customer_1 -2.977919017804365
resNode: customer_5 deliver_cap: 26.53614493481641 cap_limit: 40
1381 customer_4 ('customer_4', 'customer_3')
344 customer_4 -7.720477808637817
resNode: customer_3 deliver_cap: 37.92206593531307 cap_limit: 40
1382 customer_4 ('customer_4', 'customer_1')
344 customer_4 -7.720477808637817
resNode: customer_1 deliver_cap: 35.21663363999931 cap_limit: 40
1383 customer_4 ('customer_4', 'depot_t')
344 customer_4 -7.720477808637817
resNode: depot_t deliver_cap: 24.469392811778043 cap_limit: 40
1384 customer_4 ('customer_4', 'customer_2')
344 customer_4 -7.720477808637817
resNode: customer_2 deliver_cap: 28.085004187455517 cap_limit: 40
1385 customer_4 ('customer_4', 'customer_5')
344 customer_4 -7.720477808637817
resNode: customer_5 deliver_cap: 34.257149936489256 cap_limit: 40
1386 customer_5 ('customer_5', 'customer_3')
345 customer_5 -6.722068272931066
resNode: customer_3 deliver_cap: 34.429188653347715 cap_limit: 40
1387 customer_5 ('customer_5', 'customer_1')
345 customer_5 -6.722068272931066
resNode: customer_1 deliver_cap: 27.704817029316086 cap_limit: 40
1388 customer_5 ('customer_5', 'depot_t')
345 customer_5 -6.722068272931066
resNode: depot_t deliver_cap: 15.153275001194297 cap_limit: 40
1389 customer_5 ('customer_5', 'customer_2')
345 customer_5 -6.722068272931066
resNode: customer_2 deliver_cap: 17.8372745958134 cap_limit: 40
1390 customer_5 ('customer_5', 'customer_4')
345 customer_5 -6.722068272931066
resNode: customer_4 deliver_cap: 34.257149936489256 cap_limit: 40
1391 customer_3 ('customer_3', 'customer_1')
346 customer_3 -11.24312926372339
resNode: customer_1 deliver_cap: 42.580129861229196 cap_limit: 40
1392 customer_3 ('customer_3', 'depot_t')
346 customer_3 -11.24312926372339
resNode: depot_t deliver_cap: 29.48829486125786 cap_limit: 40
1393 customer_3 ('customer_3', 'customer_2')
346 customer_3 -11.24312926372339
resNode: customer_2 deliver_cap: 33.24402608274581 cap_limit: 40
1394 customer_3 ('customer_3', 'customer_4')
346 customer_3 -11.24312926372339
resNode: customer_4 deliver_cap: 42.80296734227317 cap_limit: 40
1395 customer_3 ('customer_3', 'customer_5')
346 customer_3 -11.24312926372339
resNode: customer_5 deliver_cap: 38.56161635702951 cap_limit: 40
1396 customer_1 ('customer_1', 'customer_3')
347 customer_1 -7.573082683377332

resNode: customer_5 deliver_cap: 21.21458500167201 cap_limit: 40
1466 customer_5 ('customer_5', 'customer_3')
365 customer_5 -1.0655998319324416
resNode: customer_3 deliver_cap: 21.386623718530466 cap_limit: 40
1467 customer_5 ('customer_5', 'customer_1')
365 customer_5 -1.0655998319324416
resNode: customer_1 deliver_cap: 17.457087437673962 cap_limit: 40
1468 customer_5 ('customer_5', 'depot_t')
365 customer_5 -1.0655998319324416
resNode: depot_t deliver_cap: 5.837157190610549 cap_limit: 40
1469 customer_5 ('customer_5', 'customer_2')
365 customer_5 -1.0655998319324416
resNode: customer_2 deliver_cap: 7.589545004171278 cap_limit: 40
1470 customer_5 ('customer_5', 'customer_4')
365 customer_5 -1.0655998319324416
resNode: customer_4 deliver_cap: 21.214585001672013 cap_limit: 40
1471 customer_3 ('customer_3', 'customer_1')
366 customer_3 -2.5713081764058785
resNode: customer_1 deliver_cap: 33.03044220837731 cap_limit: 40
1472 customer_3 ('customer_3', 'depot_t')
366 customer_3 -2.5713081764058785
resNode: depot_t deliver_cap: 20.620727755038253 cap_limit: 40
1473 customer_3 ('customer_3', 'customer_2')
366 customer_3 -2.5713081764058785
resNode: customer_2 deliver_cap: 23.69433842989393 cap_limit: 40
1474 customer_3 ('customer_3', 'customer_4')
366 customer_3 -2.5713081764058785
resNode: customer_4 deliver_cap: 31.20691804952445 cap_limit: 40
1475 customer_3 ('customer_3', 'customer_5')
366 customer_3 -2.5713081764058785
resNode: customer_5 deliver_cap: 26.965567064280798 cap_limit: 40
1476 customer_1 ('customer_1', 'customer_3')
367 customer_1 -2.9761177924750895
resNode: customer_3 deliver_cap: 39.27253223456226 cap_limit: 40
1477 customer_1 ('customer_1', 'depot_t')
367 customer_1 -2.9761177924750895
resNode: depot_t deliver_cap: 20.790029810219753 cap_limit: 40
1478 customer_1 ('customer_1', 'customer_2')
367 customer_1 -2.9761177924750895
resNode: customer_2 deliver_cap: 22.86903279124173 cap_limit: 40
1479 customer_1 ('customer_1', 'customer_4')
367 customer_1 -2.9761177924750895
resNode: customer_4 deliver_cap: 38.84100904245797 cap_limit: 40
1480 customer_1 ('customer_1', 'customer_5')
367 customer_1 -2.9761177924750895
resNode: customer_5 deliver_cap: 29.280515174315692 cap_limit: 40
1481 customer_2 ('customer_2', 'customer_3')
369 customer_2 -2.020395427333815
resNode: customer_3 deliver_cap: 34.42918865334771 cap_limit: 40
1482 customer_2 ('customer_2', 'customer_1')
369 customer_2 -2.020395427333815
resNode: customer_1 deliver_cap: 26.39905866052438 cap_limit: 40
1483 customer_2 ('customer_2', 'depot_t')
369 customer_2 -2.020395427333815
resNode: depot_t deliver_cap: 14.306730307907223 cap_limit: 40
1484 customer_2 ('customer_2', 'customer_4')
369 customer_2 -2.020395427333815
resNode: customer_4 deliver_cap: 34.257149936489256 cap_limit: 40
1485 customer_2 ('customer_2', 'customer_5')
369 customer_2 -2.020395427333815
resNode: customer_5 deliver_cap: 21.214585001672013 cap_limit: 40
1486 customer_5 ('customer_5', 'customer_3')
370 customer_5 -5.796010848419449
resNode: customer_3 deliver_cap: 38.5616163570295 cap_limit: 40
1487 customer_5 ('customer_5', 'customer_1')
370 customer_5 -5.796010848419449
resNode: customer_1 deliver_cap: 32.588112800982614 cap_limit: 40
1488 customer_5 ('customer_5', 'depot_t')
370 customer_5 -5.796010848419449
resNode: depot_t deliver_cap: 17.217591470416135 cap_limit: 40
1489 customer_5 ('customer_5', 'customer_2')
370 customer_5 -5.796010848419449
resNode: customer_2 deliver_cap: 20.02942243107011 cap_limit: 40
1490 customer_5 ('customer_5', 'customer_4')
370 customer_5 -5.796010848419449
resNode: customer_4 deliver_cap: 38.35271220084424 cap_limit: 40
1491 customer_3 ('customer_3', 'customer_1')
371 customer_3 -12.103361027031918
resNode: customer_1 deliver_cap: 52.533036487115304 cap_limit: 40
1492 customer_3 ('customer_3', 'depot_t')
371 customer_3 -12.103361027031918
resNode: depot_t deliver_cap: 38.730279585294966 cap_limit: 40
1493 customer_3 ('customer_3', 'customer_2')
371 customer_3 -12.103361027031918
resNode: customer_2 deliver_cap: 43.19693270863192 cap_limit: 40
1494 customer_3 ('customer_3', 'customer_4')
371 customer_3 -12.103361027031918
resNode: customer_4 deliver_cap: 54.8886396737063 cap_limit: 40
1495 customer_3 ('customer_3', 'customer_5')
371 customer_3 -12.103361027031918
resNode: customer_5 deliver_cap: 50.647288688462645 cap_limit: 40
1496 customer_2 ('customer_2', 'customer_3')
373 customer_2 -4.331295258911076
resNode: customer_3 deliver_cap: 45.942807583109875 cap_limit: 40
1497 customer_2 ('customer_2', 'customer_1')
373 customer_2 -4.331295258911076
resNode: customer_1 deliver_cap: 35.445473533908945 cap_limit: 40
1498 customer_2 ('customer_2', 'depot_t')
373 customer_2 -4.331295258911076
resNode: depot_t deliver_cap: 22.53074382916591 cap_limit: 40
1499 customer_2 ('customer_2', 'customer_4')
373 customer_2 -4.331295258911076
resNode: customer_4 deliver_cap: 45.77076886625142 cap_limit: 40
1500 customer_2 ('customer_2', 'customer_5')
373 customer_2 -4.331295258911076
resNode: customer_5 deliver_cap: 32.72820393143417 cap_limit: 40
1501 customer_4 ('customer_4', 'customer_3')
374 customer_4 -11.945432218495414
resNode: customer_3 deliver_cap: 54.57355138233635 cap_limit: 40
1502 customer_4 ('customer_4', 'customer_1')
374 customer_4 -11.945432218495414
resNode: customer_1 deliver_cap: 51.842028819765176 cap_limit: 40
1503 customer_4 ('customer_4', 'depot_t')
374 customer_4 -11.945432218495414
resNode: depot_t deliver_cap: 38.329579478340975 cap_limit: 40
1504 customer_4 ('customer_4', 'customer_2')
374 customer_4 -11.945432218495414
resNode: customer_2 deliver_cap: 42.765409516527626 cap_limit: 40
1505 customer_4 ('customer_4', 'customer_5')
374 customer_4 -11.945432218495414
resNode: customer_5 deliver_cap: 50.12329624090743 cap_limit: 40
1506 customer_5 ('customer_5', 'customer_3')
375 customer_5 -12.051529220808703
resNode: customer_3 deliver_cap: 54.56042954948372 cap_limit: 40
1507 customer_5 ('customer_5', 'customer_1')
375 customer_5 -12.051529220808703
resNode: customer_1 deliver_cap: 45.763606018297864 cap_limit: 40
1508 customer_5 ('customer_5', 'depot_t')
375 customer_5 -12.051529220808703
resNode: depot_t deliver_cap: 29.451978029351714 cap_limit: 40
1509 customer_5 ('customer_5', 'customer_2')
375 customer_5 -12.051529220808703
resNode: customer_2 deliver_cap: 33.204915648385345 cap_limit: 40
1510 customer_5 ('customer_5', 'customer_4')
375 customer_5 -12.051529220808703
resNode: customer_4 deliver_cap: 54.351525393298466 cap_limit: 40
1511 customer_3 ('customer_3', 'customer_1')
376 customer_3 -10.107392974284224
resNode: customer_1 deliver_cap: 47.43020843065491 cap_limit: 40
1512 customer_3 ('customer_3', 'depot_t')
376 customer_3 -10.107392974284224
resNode: depot_t deliver_cap: 33.99193924715317 cap_limit: 40
1513 customer_3 ('customer_3', 'customer_2')
376 customer_3 -10.107392974284224
resNode: customer_2 deliver_cap: 38.094104652171524 cap_limit: 40
1514 customer_3 ('customer_3', 'customer_4')
376 customer_3 -10.107392974284224
resNode: customer_4 deliver_cap: 48.692348462290106 cap_limit: 40
1515 customer_3 ('customer_3', 'customer_5')
376 customer_3 -10.107392974284224
resNode: customer_5 deliver_cap: 44.45099747704645 cap_limit: 40
1516 customer_1 ('customer_1', 'customer_3')
377 customer_1 -4.722749633810866
resNode: customer_3 deliver_cap: 45.94280758310987 cap_limit: 40
1517 customer_1 ('customer_1', 'depot_t')
377 customer_1 -4.722749633810866
resNode: depot_t deliver_cap: 25.554512202039472 cap_limit: 40
1518 customer_1 ('customer_1', 'customer_2')
377 customer_1 -4.722749633810866
resNode: customer_2 deliver_cap: 28.109963422243418 cap_limit: 40
1519 customer_1 ('customer_1', 'customer_4')
377 customer_1 -4.722749633810866
resNode: customer_4 deliver_cap: 45.51128439100558 cap_limit: 40
1520 customer_1 ('customer_1', 'customer_5')
377 customer_1 -4.722749633810866
resNode: customer_5 deliver_cap: 35.9507905228633 cap_limit: 40
1521 customer_4 ('customer_4', 'customer_3')
379 customer_4 -10.083840054714319
resNode: customer_3 deliver_cap: 48.692348462290106 cap_limit: 40
1522 customer_4 ('customer_4', 'customer_1')
379 customer_4 -10.083840054714319
resNode: customer_1 deliver_cap: 46.99868523855062 cap_limit: 40
1523 customer_4 ('customer_4', 'depot_t')
379 customer_4 -10.083840054714319
resNode: depot_t deliver_cap: 33.83218901007032 cap_limit: 40
1524 customer_4 ('customer_4', 'customer_2')
379 customer_4 -10.083840054714319
resNode: customer_2 deliver_cap: 37.92206593531307 cap_limit: 40
1525 customer_4 ('customer_4', 'customer_5')
379 customer_4 -10.083840054714319
resNode: customer_5 deliver_cap: 44.24209332086118 cap_limit: 40
1526 customer_5 ('customer_5', 'customer_3')
380 customer_5 -8.38672168321379
resNode: customer_3 deliver_cap: 44.45099747704645 cap_limit: 40
1527 customer_5 ('customer_5', 'customer_1')
380 customer_5 -8.38672168321379
resNode: customer_1 deliver_cap: 37.43819137040834 cap_limit: 40
1528 customer_5 ('customer_5', 'depot_t')
380 customer_5 -8.38672168321379
resNode: depot_t deliver_cap: 21.721235856311452 cap_limit: 40
1529 customer_5 ('customer_5', 'customer_2')
380 customer_5 -8.38672168321379
resNode: customer_2 deliver_cap: 24.879501000495832 cap_limit: 40
1530 customer_5 ('customer_5', 'customer_4')
380 customer_5 -8.38672168321379
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
1531 customer_3 ('customer_3', 'customer_1')
381 customer_3 -6.535661215205662
resNode: customer_1 deliver_cap: 46.99387063625463 cap_limit: 40
1532 customer_3 ('customer_3', 'depot_t')
381 customer_3 -6.535661215205662
resNode: depot_t deliver_cap: 31.859805732106324 cap_limit: 40
1533 customer_3 ('customer_3', 'customer_2')
381 customer_3 -6.535661215205662
resNode: customer_2 deliver_cap: 35.65717319095337 cap_limit: 40
1534 customer_3 ('customer_3', 'customer_4')
381 customer_3 -6.535661215205662
resNode: customer_4 deliver_cap: 44.81458185365486 cap_limit: 40
1535 customer_3 ('customer_3', 'customer_5')
381 customer_3 -6.535661215205662
resNode: customer_5 deliver_cap: 39.82475716513291 cap_limit: 40
1536 customer_1 ('customer_1', 'customer_3')
382 customer_1 -5.791210580510839
resNode: customer_3 deliver_cap: 54.57355138233635 cap_limit: 40
1537 customer_1 ('customer_1', 'depot_t')
382 customer_1 -5.791210580510839
resNode: depot_t deliver_cap: 32.29240315558381 cap_limit: 40
1538 customer_1 ('customer_1', 'customer_2')
382 customer_1 -5.791210580510839
resNode: customer_2 deliver_cap: 34.7764341675518 cap_limit: 40
1539 customer_1 ('customer_1', 'customer_4')
382 customer_1 -5.791210580510839
resNode: customer_4 deliver_cap: 54.049558934781146 cap_limit: 40
1540 customer_1 ('customer_1', 'customer_5')
382 customer_1 -5.791210580510839
resNode: customer_5 deliver_cap: 42.4403878091798 cap_limit: 40
1541 customer_2 ('customer_2', 'customer_3')
384 customer_2 -4.349240752696124
resNode: customer_3 deliver_cap: 48.692348462290106 cap_limit: 40
1542 customer_2 ('customer_2', 'customer_1')
384 customer_2 -4.349240752696124
resNode: customer_1 deliver_cap: 39.269194364820635 cap_limit: 40
1543 customer_2 ('customer_2', 'depot_t')
384 customer_2 -4.349240752696124
resNode: depot_t deliver_cap: 23.864113802577524 cap_limit: 40
1544 customer_2 ('customer_2', 'customer_4')
384 customer_2 -4.349240752696124
resNode: customer_4 deliver_cap: 48.483444306104836 cap_limit: 40
1545 customer_2 ('customer_2', 'customer_5')
384 customer_2 -4.349240752696124
resNode: customer_5 deliver_cap: 32.64604402811248 cap_limit: 40
1546 customer_5 ('customer_5', 'customer_3')
385 customer_5 -9.564029101567957
resNode: customer_3 deliver_cap: 53.46716809777845 cap_limit: 40
1547 customer_5 ('customer_5', 'customer_1')
385 customer_5 -9.564029101567957
resNode: customer_1 deliver_cap: 46.45675635584679 cap_limit: 40
1548 customer_5 ('customer_5', 'depot_t')
385 customer_5 -9.564029101567957
resNode: depot_t deliver_cap: 27.671330304879103 cap_limit: 40
1549 customer_5 ('customer_5', 'customer_2')
385 customer_5 -9.564029101567957
resNode: customer_2 deliver_cap: 31.20691804952445 cap_limit: 40
1550 customer_5 ('customer_5', 'customer_4')
385 customer_5 -9.564029101567957
resNode: customer_4 deliver_cap: 53.221398502266375 cap_limit: 40
1551 customer_3 ('customer_3', 'customer_1')
386 customer_3 -14.055797816323398
resNode: customer_1 deliver_cap: 54.34856894375969 cap_limit: 40
1552 customer_3 ('customer_3', 'depot_t')
386 customer_3 -14.055797816323398
resNode: depot_t deliver_cap: 38.7818747274052 cap_limit: 40
1553 customer_3 ('customer_3', 'customer_2')
386 customer_3 -14.055797816323398
resNode: customer_2 deliver_cap: 43.011871498458426 cap_limit: 40
1554 customer_3 ('customer_3', 'customer_4')
386 customer_3 -14.055797816323398
resNode: customer_4 deliver_cap: 53.467168097778455 cap_limit: 40
1555 customer_3 ('customer_3', 'customer_5')
386 customer_3 -14.055797816323398
resNode: customer_5 deliver_cap: 48.477343409256505 cap_limit: 40
1556 customer_1 ('customer_1', 'customer_3')
387 customer_1 -9.847032225765979
resNode: customer_3 deliver_cap: 54.56042954948372 cap_limit: 40
1557 customer_1 ('customer_1', 'depot_t')
387 customer_1 -9.847032225765979
resNode: depot_t deliver_cap: 32.28236881281416 cap_limit: 40
1558 customer_1 ('customer_1', 'customer_2')
387 customer_1 -9.847032225765979
resNode: customer_2 deliver_cap: 34.765627952261404 cap_limit: 40
1559 customer_1 ('customer_1', 'customer_4')
387 customer_1 -9.847032225765979
resNode: customer_4 deliver_cap: 54.03643710192851 cap_limit: 40
1560 customer_1 ('customer_1', 'customer_5')
387 customer_1 -9.847032225765979
resNode: customer_5 deliver_cap: 42.42726597632718 cap_limit: 40
1561 customer_2 ('customer_2', 'customer_3')
389 customer_2 -7.348005109853507
resNode: customer_3 deliver_cap: 44.45099747704646 cap_limit: 40
1562 customer_2 ('customer_2', 'customer_1')
389 customer_2 -7.348005109853507
resNode: customer_1 deliver_cap: 35.776317082855265 cap_limit: 40
1563 customer_2 ('customer_2', 'depot_t')
389 customer_2 -7.348005109853507
resNode: depot_t deliver_cap: 20.62072775503826 cap_limit: 40
1564 customer_2 ('customer_2', 'customer_4')
389 customer_2 -7.348005109853507
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
1565 customer_2 ('customer_2', 'customer_5')
389 customer_2 -7.348005109853507
resNode: customer_5 deliver_cap: 28.404693042868825 cap_limit: 40
1566 customer_4 ('customer_4', 'customer_3')
390 customer_4 -14.023028536921789
resNode: customer_3 deliver_cap: 53.467168097778455 cap_limit: 40
1567 customer_4 ('customer_4', 'customer_1')
390 customer_4 -14.023028536921789
resNode: customer_1 deliver_cap: 53.82457649620447 cap_limit: 40
1568 customer_4 ('customer_4', 'depot_t')
390 customer_4 -14.023028536921789
resNode: depot_t deliver_cap: 38.585259050995546 cap_limit: 40
1569 customer_4 ('customer_4', 'customer_2')
390 customer_4 -14.023028536921789
resNode: customer_2 deliver_cap: 42.80296734227317 cap_limit: 40
1570 customer_4 ('customer_4', 'customer_5')
390 customer_4 -14.023028536921789
resNode: customer_5 deliver_cap: 48.231573813744426 cap_limit: 40
1571 customer_1 ('customer_1', 'customer_3')
391 customer_1 -11.87983132806658
resNode: customer_3 deliver_cap: 58.775126513300265 cap_limit: 40
1572 customer_1 ('customer_1', 'depot_t')
391 customer_1 -11.87983132806658
resNode: depot_t deliver_cap: 34.7204542950326 cap_limit: 40
1573 customer_1 ('customer_1', 'customer_2')
391 customer_1 -11.87983132806658
resNode: customer_2 deliver_cap: 38.192499724535864 cap_limit: 40
1574 customer_1 ('customer_1', 'customer_4')
391 customer_1 -11.87983132806658
resNode: customer_4 deliver_cap: 58.343603321195964 cap_limit: 40
1575 customer_1 ('customer_1', 'customer_5')
391 customer_1 -11.87983132806658
resNode: customer_5 deliver_cap: 48.78310945305368 cap_limit: 40
1576 customer_2 ('customer_2', 'customer_3')
393 customer_2 -10.859237844113846
resNode: customer_3 deliver_cap: 53.67229845683986 cap_limit: 40
1577 customer_2 ('customer_2', 'customer_1')
393 customer_2 -10.859237844113846
resNode: customer_1 deliver_cap: 41.51864493469679 cap_limit: 40
1578 customer_2 ('customer_2', 'depot_t')
393 customer_2 -10.859237844113846
resNode: depot_t deliver_cap: 28.051808738973044 cap_limit: 40
1579 customer_2 ('customer_2', 'customer_4')
393 customer_2 -10.859237844113846
resNode: customer_4 deliver_cap: 53.50025973998141 cap_limit: 40
1580 customer_2 ('customer_2', 'customer_5')
393 customer_2 -10.859237844113846
resNode: customer_5 deliver_cap: 40.45769480516416 cap_limit: 40
1581 customer_4 ('customer_4', 'customer_3')
394 customer_4 -16.54100208526569
resNode: customer_3 deliver_cap: 54.57355138233635 cap_limit: 40
1582 customer_4 ('customer_4', 'customer_1')
394 customer_4 -16.54100208526569
resNode: customer_1 deliver_cap: 51.842028819765176 cap_limit: 40
1583 customer_4 ('customer_4', 'depot_t')
394 customer_4 -16.54100208526569
resNode: depot_t deliver_cap: 38.329579478340975 cap_limit: 40
1584 customer_4 ('customer_4', 'customer_2')
394 customer_4 -16.54100208526569
resNode: customer_2 deliver_cap: 42.765409516527626 cap_limit: 40
1585 customer_4 ('customer_4', 'customer_5')
394 customer_4 -16.54100208526569
resNode: customer_5 deliver_cap: 50.12329624090743 cap_limit: 40
1586 customer_5 ('customer_5', 'customer_3')
395 customer_5 -19.789257676849164
resNode: customer_3 deliver_cap: 61.92824968984141 cap_limit: 40
1587 customer_5 ('customer_5', 'customer_1')
395 customer_5 -19.789257676849164
resNode: customer_1 deliver_cap: 51.83122260447478 cap_limit: 40
1588 customer_5 ('customer_5', 'depot_t')
395 customer_5 -19.789257676849164
resNode: depot_t deliver_cap: 35.08619343080171 cap_limit: 40
1589 customer_5 ('customer_5', 'customer_2')
395 customer_5 -19.789257676849164
resNode: customer_2 deliver_cap: 39.27253223456226 cap_limit: 40
1590 customer_5 ('customer_5', 'customer_4')
395 customer_5 -19.789257676849164
resNode: customer_4 deliver_cap: 61.719345533656146 cap_limit: 40
1591 customer_3 ('customer_3', 'customer_1')
396 customer_3 -11.726659181720075
resNode: customer_1 deliver_cap: 41.51864493469679 cap_limit: 40
1592 customer_3 ('customer_3', 'depot_t')
396 customer_3 -11.726659181720075
resNode: depot_t deliver_cap: 30.013147935028726 cap_limit: 40
1593 customer_3 ('customer_3', 'customer_2')
396 customer_3 -11.726659181720075
resNode: customer_2 deliver_cap: 34.18313482303127 cap_limit: 40
1594 customer_3 ('customer_3', 'customer_4')
396 customer_3 -11.726659181720075
resNode: customer_4 deliver_cap: 45.51128439100558 cap_limit: 40
1595 customer_3 ('customer_3', 'customer_5')
396 customer_3 -11.726659181720075
resNode: customer_5 deliver_cap: 42.01840710904022 cap_limit: 40
1596 customer_1 ('customer_1', 'customer_3')
397 customer_1 -4.936937459087927
resNode: customer_3 deliver_cap: 40.34997284019711 cap_limit: 40
1597 customer_1 ('customer_1', 'depot_t')
397 customer_1 -4.936937459087927
resNode: depot_t deliver_cap: 20.594010193634496 cap_limit: 40
1598 customer_1 ('customer_1', 'customer_2')
397 customer_1 -4.936937459087927
resNode: customer_2 deliver_cap: 23.536011649867994 cap_limit: 40
1599 customer_1 ('customer_1', 'customer_4')
397 customer_1 -4.936937459087927
resNode: customer_4 deliver_cap: 40.01091890354375 cap_limit: 40
1600 customer_1 ('customer_1', 'customer_5')
397 customer_1 -4.936937459087927
resNode: customer_5 deliver_cap: 32.49910229286052 cap_limit: 40
1601 customer_4 ('customer_4', 'customer_3')
399 customer_4 -11.71232262198187
resNode: customer_3 deliver_cap: 45.51128439100558 cap_limit: 40
1602 customer_4 ('customer_4', 'customer_1')
399 customer_4 -11.71232262198187
resNode: customer_1 deliver_cap: 41.179590998043416 cap_limit: 40
1603 customer_4 ('customer_4', 'depot_t')
399 customer_4 -11.71232262198187
resNode: depot_t deliver_cap: 29.89026313727269 cap_limit: 40
1604 customer_4 ('customer_4', 'customer_2')
399 customer_4 -11.71232262198187

resNode: customer_2 deliver_cap: 34.387015482153 cap_limit: 40
1674 customer_3 ('customer_3', 'customer_4')
416 customer_3 -11.51971560908645
resNode: customer_4 deliver_cap: 45.770768866251416 cap_limit: 40
1675 customer_3 ('customer_3', 'customer_5')
416 customer_3 -11.51971560908645
resNode: customer_5 deliver_cap: 42.27789158428605 cap_limit: 40
1676 customer_2 ('customer_2', 'customer_3')
418 customer_2 -4.140044049050898
resNode: customer_3 deliver_cap: 36.54448859781425 cap_limit: 40
1677 customer_2 ('customer_2', 'customer_1')
418 customer_2 -4.140044049050898
resNode: customer_1 deliver_cap: 26.10330319116447 cap_limit: 40
1678 customer_2 ('customer_2', 'depot_t')
418 customer_2 -4.140044049050898
resNode: depot_t deliver_cap: 16.05570054201572 cap_limit: 40
1679 customer_2 ('customer_2', 'customer_4')
418 customer_2 -4.140044049050898
resNode: customer_4 deliver_cap: 36.4093153202826 cap_limit: 40
1680 customer_2 ('customer_2', 'customer_5')
418 customer_2 -4.140044049050898
resNode: customer_5 deliver_cap: 26.161585728640485 cap_limit: 40
1681 customer_4 ('customer_4', 'customer_3')
419 customer_4 -11.384904114412677
resNode: customer_3 deliver_cap: 45.51128439100558 cap_limit: 40
1682 customer_4 ('customer_4', 'customer_1')
419 customer_4 -11.384904114412677
resNode: customer_1 deliver_cap: 41.179590998043416 cap_limit: 40
1683 customer_4 ('customer_4', 'depot_t')
419 customer_4 -11.384904114412677
resNode: depot_t deliver_cap: 29.89026313727269 cap_limit: 40
1684 customer_4 ('customer_4', 'customer_2')
419 customer_4 -11.384904114412677
resNode: customer_2 deliver_cap: 34.04796154549963 cap_limit: 40
1685 customer_4 ('customer_4', 'customer_5')
419 customer_4 -11.384904114412677
resNode: customer_5 deliver_cap: 41.84636839218176 cap_limit: 40
1686 customer_5 ('customer_5', 'customer_3')
420 customer_5 -12.003170431090734
resNode: customer_3 deliver_cap: 45.50047817571519 cap_limit: 40
1687 customer_5 ('customer_5', 'customer_1')
420 customer_5 -12.003170431090734
resNode: customer_1 deliver_cap: 36.403687368319105 cap_limit: 40
1688 customer_5 ('customer_5', 'depot_t')
420 customer_5 -12.003170431090734
resNode: depot_t deliver_cap: 23.061338945742488 cap_limit: 40
1689 customer_5 ('customer_5', 'customer_2')
420 customer_5 -12.003170431090734
resNode: customer_2 deliver_cap: 26.53614493481641 cap_limit: 40
1690 customer_5 ('customer_5', 'customer_4')
420 customer_5 -12.003170431090734
resNode: customer_4 deliver_cap: 45.328439458856735 cap_limit: 40
1691 customer_3 ('customer_3', 'customer_1')
421 customer_3 -13.264978155981293
resNode: customer_1 deliver_cap: 47.25816971379646 cap_limit: 40
1692 customer_3 ('customer_3', 'depot_t')
421 customer_3 -13.264978155981293
resNode: depot_t deliver_cap: 33.83218901007032 cap_limit: 40
1693 customer_3 ('customer_3', 'customer_2')
421 customer_3 -13.264978155981293
resNode: customer_2 deliver_cap: 37.92206593531307 cap_limit: 40
1694 customer_3 ('customer_3', 'customer_4')
421 customer_3 -13.264978155981293
resNode: customer_4 deliver_cap: 48.483444306104836 cap_limit: 40
1695 customer_3 ('customer_3', 'customer_5')
421 customer_3 -13.264978155981293
resNode: customer_5 deliver_cap: 44.24209332086119 cap_limit: 40
1696 customer_1 ('customer_1', 'customer_3')
422 customer_1 -9.858789333098944
resNode: customer_3 deliver_cap: 53.50025973998141 cap_limit: 40
1697 customer_1 ('customer_1', 'depot_t')
422 customer_1 -9.858789333098944
resNode: depot_t deliver_cap: 30.952692314090573 cap_limit: 40
1698 customer_1 ('customer_1', 'customer_2')
422 customer_1 -9.858789333098944
resNode: customer_2 deliver_cap: 34.04796154549963 cap_limit: 40
1699 customer_1 ('customer_1', 'customer_4')
422 customer_1 -9.858789333098944
resNode: customer_4 deliver_cap: 53.06873654787712 cap_limit: 40
1700 customer_1 ('customer_1', 'customer_5')
422 customer_1 -9.858789333098944
resNode: customer_5 deliver_cap: 43.50824267973484 cap_limit: 40
1701 customer_2 ('customer_2', 'customer_3')
424 customer_2 -8.90306696795767
resNode: customer_3 deliver_cap: 48.656916158766855 cap_limit: 40
1702 customer_2 ('customer_2', 'customer_1')
424 customer_2 -8.90306696795767
resNode: customer_1 deliver_cap: 37.577987414782285 cap_limit: 40
1703 customer_2 ('customer_2', 'depot_t')
424 customer_2 -8.90306696795767
resNode: depot_t deliver_cap: 24.469392811778043 cap_limit: 40
1704 customer_2 ('customer_2', 'customer_4')
424 customer_2 -8.90306696795767
resNode: customer_4 deliver_cap: 48.4848774419084 cap_limit: 40
1705 customer_2 ('customer_2', 'customer_5')
424 customer_2 -8.90306696795767
resNode: customer_5 deliver_cap: 35.44231250709116 cap_limit: 40
1706 customer_5 ('customer_5', 'customer_3')
425 customer_5 -16.48968082799486
resNode: customer_3 deliver_cap: 55.8381426136099 cap_limit: 40
1707 customer_5 ('customer_5', 'customer_1')
425 customer_5 -16.48968082799486
resNode: customer_1 deliver_cap: 46.81584030640177 cap_limit: 40
1708 customer_5 ('customer_5', 'depot_t')
425 customer_5 -16.48968082799486
resNode: depot_t deliver_cap: 30.4290527254482 cap_limit: 40
1709 customer_5 ('customer_5', 'customer_2')
425 customer_5 -16.48968082799486
resNode: customer_2 deliver_cap: 34.25714993648925 cap_limit: 40
1710 customer_5 ('customer_5', 'customer_4')
425 customer_5 -16.48968082799486
resNode: customer_4 deliver_cap: 55.629238457424634 cap_limit: 40
1711 customer_3 ('customer_3', 'customer_1')
426 customer_3 -12.786786623331274
resNode: customer_1 deliver_cap: 43.76529243183109 cap_limit: 40
1712 customer_3 ('customer_3', 'depot_t')
426 customer_3 -12.786786623331274
resNode: depot_t deliver_cap: 30.58880296253105 cap_limit: 40
1713 customer_3 ('customer_3', 'customer_2')
426 customer_3 -12.786786623331274
resNode: customer_2 deliver_cap: 34.42918865334771 cap_limit: 40
1714 customer_3 ('customer_3', 'customer_4')
426 customer_3 -12.786786623331274
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
1715 customer_3 ('customer_3', 'customer_5')
426 customer_3 -12.786786623331274
resNode: customer_5 deliver_cap: 40.00074233561753 cap_limit: 40
1716 customer_1 ('customer_1', 'customer_3')
427 customer_1 -8.799285783002565
resNode: customer_3 deliver_cap: 43.939765871839136 cap_limit: 40
1717 customer_1 ('customer_1', 'depot_t')
427 customer_1 -8.799285783002565
resNode: depot_t deliver_cap: 24.123768122560378 cap_limit: 40
1718 customer_1 ('customer_1', 'customer_2')
427 customer_1 -8.799285783002565
resNode: customer_2 deliver_cap: 26.536144934816413 cap_limit: 40
1719 customer_1 ('customer_1', 'customer_4')
427 customer_1 -8.799285783002565
resNode: customer_4 deliver_cap: 43.50824267973485 cap_limit: 40
1720 customer_1 ('customer_1', 'customer_5')
427 customer_1 -8.799285783002565
resNode: customer_5 deliver_cap: 33.94774881159257 cap_limit: 40
1721 customer_2 ('customer_2', 'customer_3')
429 customer_2 -6.973045651192548
resNode: customer_3 deliver_cap: 35.61435122394961 cap_limit: 40
1722 customer_2 ('customer_2', 'customer_1')
429 customer_2 -6.973045651192548
resNode: customer_1 deliver_cap: 27.330257823140165 cap_limit: 40
1723 customer_2 ('customer_2', 'depot_t')
429 customer_2 -6.973045651192548
resNode: depot_t deliver_cap: 15.153275001194297 cap_limit: 40
1724 customer_2 ('customer_2', 'customer_4')
429 customer_2 -6.973045651192548
resNode: customer_4 deliver_cap: 35.44231250709116 cap_limit: 40
1725 customer_2 ('customer_2', 'customer_5')
429 customer_2 -6.973045651192548
resNode: customer_5 deliver_cap: 22.399747572273917 cap_limit: 40
1726 customer_4 ('customer_4', 'customer_3')
430 customer_4 -12.763233703761367
resNode: customer_3 deliver_cap: 44.24209332086119 cap_limit: 40
1727 customer_4 ('customer_4', 'customer_1')
430 customer_4 -12.763233703761367
resNode: customer_1 deliver_cap: 43.333769239726806 cap_limit: 40
1728 customer_4 ('customer_4', 'depot_t')
430 customer_4 -12.763233703761367
resNode: depot_t deliver_cap: 30.429052725448205 cap_limit: 40
1729 customer_4 ('customer_4', 'customer_2')
430 customer_4 -12.763233703761367
resNode: customer_2 deliver_cap: 34.257149936489256 cap_limit: 40
1730 customer_4 ('customer_4', 'customer_5')
430 customer_4 -12.763233703761367
resNode: customer_5 deliver_cap: 39.79183817943226 cap_limit: 40
1731 customer_1 ('customer_1', 'customer_3')
431 customer_1 -13.44912266342019
resNode: customer_3 deliver_cap: 62.243337981211354 cap_limit: 40
1732 customer_1 ('customer_1', 'depot_t')
431 customer_1 -13.44912266342019
resNode: depot_t deliver_cap: 38.157534084135285 cap_limit: 40
1733 customer_1 ('customer_1', 'customer_2')
431 customer_1 -13.44912266342019
resNode: customer_2 deliver_cap: 41.092729013684156 cap_limit: 40
1734 customer_1 ('customer_1', 'customer_4')
431 customer_1 -13.44912266342019
resNode: customer_4 deliver_cap: 61.719345533656146 cap_limit: 40
1735 customer_1 ('customer_1', 'customer_5')
431 customer_1 -13.44912266342019
resNode: customer_5 deliver_cap: 50.1101744080548 cap_limit: 40
1736 customer_2 ('customer_2', 'customer_3')
433 customer_2 -11.928380762762988
resNode: customer_3 deliver_cap: 56.04704676979516 cap_limit: 40
1737 customer_2 ('customer_2', 'customer_1')
433 customer_2 -11.928380762762988
resNode: customer_1 deliver_cap: 45.326004735707144 cap_limit: 40
1738 customer_2 ('customer_2', 'depot_t')
433 customer_2 -11.928380762762988
resNode: depot_t deliver_cap: 29.488294861257856 cap_limit: 40
1739 customer_2 ('customer_2', 'customer_4')
433 customer_2 -11.928380762762988
resNode: customer_4 deliver_cap: 55.83814261360989 cap_limit: 40
1740 customer_2 ('customer_2', 'customer_5')
433 customer_2 -11.928380762762988
resNode: customer_5 deliver_cap: 40.000742335617524 cap_limit: 40
1741 customer_4 ('customer_4', 'customer_3')
434 customer_4 -15.704391866644087
resNode: customer_3 deliver_cap: 53.46716809777845 cap_limit: 40
1742 customer_4 ('customer_4', 'customer_1')
434 customer_4 -15.704391866644087
resNode: customer_1 deliver_cap: 53.824576496204465 cap_limit: 40
1743 customer_4 ('customer_4', 'depot_t')
434 customer_4 -15.704391866644087
resNode: depot_t deliver_cap: 38.58525905099554 cap_limit: 40
1744 customer_4 ('customer_4', 'customer_2')
434 customer_4 -15.704391866644087
resNode: customer_2 deliver_cap: 42.80296734227316 cap_limit: 40
1745 customer_4 ('customer_4', 'customer_5')
434 customer_4 -15.704391866644087
resNode: customer_5 deliver_cap: 48.23157381374442 cap_limit: 40
1746 customer_5 ('customer_5', 'customer_3')
435 customer_5 -18.765529032407994
resNode: customer_3 deliver_cap: 62.119754341902045 cap_limit: 40
1747 customer_5 ('customer_5', 'customer_1')
435 customer_5 -18.765529032407994
resNode: customer_1 deliver_cap: 53.81145466335184 cap_limit: 40
1748 customer_5 ('customer_5', 'depot_t')
435 customer_5 -18.765529032407994
resNode: depot_t deliver_cap: 34.59339930017798 cap_limit: 40
1749 customer_5 ('customer_5', 'customer_2')
435 customer_5 -18.765529032407994
resNode: customer_2 deliver_cap: 38.5616163570295 cap_limit: 40
1750 customer_5 ('customer_5', 'customer_4')
435 customer_5 -18.765529032407994
resNode: customer_4 deliver_cap: 61.873984746389965 cap_limit: 40
1751 customer_3 ('customer_3', 'customer_1')
436 customer_3 -15.918189369414858
resNode: customer_1 deliver_cap: 52.09070707972061 cap_limit: 40
1752 customer_3 ('customer_3', 'depot_t')
436 customer_3 -15.918189369414858
resNode: depot_t deliver_cap: 38.31954513557132 cap_limit: 40
1753 customer_3 ('customer_3', 'customer_2')
436 customer_3 -15.918189369414858
resNode: customer_2 deliver_cap: 42.754603301237225 cap_limit: 40
1754 customer_3 ('customer_3', 'customer_4')
436 customer_3 -15.918189369414858
resNode: customer_4 deliver_cap: 54.35152539329845 cap_limit: 40
1755 customer_3 ('customer_3', 'customer_5')
436 customer_3 -15.918189369414858
resNode: customer_5 deliver_cap: 50.110174408054796 cap_limit: 40
1756 customer_2 ('customer_2', 'customer_3')
438 customer_2 -8.264604692560452
resNode: customer_3 deliver_cap: 45.50047817571518 cap_limit: 40
1757 customer_2 ('customer_2', 'customer_1')
438 customer_2 -8.264604692560452
resNode: customer_1 deliver_cap: 35.0979289995274 cap_limit: 40
1758 customer_2 ('customer_2', 'depot_t')
438 customer_2 -8.264604692560452
resNode: depot_t deliver_cap: 22.214794252455413 cap_limit: 40
1759 customer_2 ('customer_2', 'customer_4')
438 customer_2 -8.264604692560452
resNode: customer_4 deliver_cap: 45.32843945885672 cap_limit: 40
1760 customer_2 ('customer_2', 'customer_5')
438 customer_2 -8.264604692560452
resNode: customer_5 deliver_cap: 32.28587452403948 cap_limit: 40
1761 customer_4 ('customer_4', 'customer_3')
439 customer_4 -15.760260560878356
resNode: customer_3 deliver_cap: 54.03643710192851 cap_limit: 40
1762 customer_4 ('customer_4', 'customer_1')
439 customer_4 -15.760260560878356
resNode: customer_1 deliver_cap: 51.39969941237048 cap_limit: 40
1763 customer_4 ('customer_4', 'depot_t')
439 customer_4 -15.760260560878356
resNode: depot_t deliver_cap: 37.91884502861733 cap_limit: 40
1764 customer_4 ('customer_4', 'customer_2')
439 customer_4 -15.760260560878356
resNode: customer_2 deliver_cap: 42.32308010913294 cap_limit: 40
1765 customer_4 ('customer_4', 'customer_5')
439 customer_4 -15.760260560878356
resNode: customer_5 deliver_cap: 49.58618196049959 cap_limit: 40
1766 customer_5 ('customer_5', 'customer_3')
440 customer_5 -15.866357563191647
resNode: customer_3 deliver_cap: 54.02331526907589 cap_limit: 40
1767 customer_5 ('customer_5', 'customer_1')
440 customer_5 -15.866357563191647
resNode: customer_1 deliver_cap: 45.321276610903176 cap_limit: 40
1768 customer_5 ('customer_5', 'depot_t')
440 customer_5 -15.866357563191647
resNode: depot_t deliver_cap: 29.041243579628073 cap_limit: 40
1769 customer_5 ('customer_5', 'customer_2')
440 customer_5 -15.866357563191647
resNode: customer_2 deliver_cap: 32.76258624099066 cap_limit: 40
1770 customer_5 ('customer_5', 'customer_4')
440 customer_5 -15.866357563191647
resNode: customer_4 deliver_cap: 53.814411112890625 cap_limit: 40
1771 customer_3 ('customer_3', 'customer_1')
441 customer_3 -12.023197075289291
resNode: customer_1 deliver_cap: 43.76529243183109 cap_limit: 40
1772 customer_3 ('customer_3', 'depot_t')
441 customer_3 -12.023197075289291
resNode: depot_t deliver_cap: 30.58880296253105 cap_limit: 40
1773 customer_3 ('customer_3', 'customer_2')
441 customer_3 -12.023197075289291
resNode: customer_2 deliver_cap: 34.42918865334771 cap_limit: 40
1774 customer_3 ('customer_3', 'customer_4')
441 customer_3 -12.023197075289291
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
1775 customer_3 ('customer_3', 'customer_5')
441 customer_3 -12.023197075289291
resNode: customer_5 deliver_cap: 40.00074233561753 cap_limit: 40
1776 customer_1 ('customer_1', 'customer_3')
442 customer_1 -7.620227663072312
resNode: customer_3 deliver_cap: 42.27789158428605 cap_limit: 40
1777 customer_1 ('customer_1', 'depot_t')
442 customer_1 -7.620227663072312
resNode: depot_t deliver_cap: 22.93671506002246 cap_limit: 40
1778 customer_1 ('customer_1', 'customer_2')
442 customer_1 -7.620227663072312
resNode: customer_2 deliver_cap: 25.230386566024706 cap_limit: 40
1779 customer_1 ('customer_1', 'customer_4')
442 customer_1 -7.620227663072312
resNode: customer_4 deliver_cap: 41.846368392181766 cap_limit: 40
1780 customer_1 ('customer_1', 'customer_5')
442 customer_1 -7.620227663072312
resNode: customer_5 deliver_cap: 32.285874524039485 cap_limit: 40
1781 customer_4 ('customer_4', 'customer_3')
444 customer_4 -11.999644155719384
resNode: customer_3 deliver_cap: 44.24209332086119 cap_limit: 40
1782 customer_4 ('customer_4', 'customer_1')
444 customer_4 -11.999644155719384
resNode: customer_1 deliver_cap: 43.333769239726806 cap_limit: 40
1783 customer_4 ('customer_4', 'depot_t')
444 customer_4 -11.999644155719384
resNode: depot_t deliver_cap: 30.429052725448205 cap_limit: 40
1784 customer_4 ('customer_4', 'customer_2')
444 customer_4 -11.999644155719384
resNode: customer_2 deliver_cap: 34.257149936489256 cap_limit: 40
1785 customer_4 ('customer_4', 'customer_5')
444 customer_4 -11.999644155719384
resNode: customer_5 deliver_cap: 39.79183817943226 cap_limit: 40
1786 customer_5 ('customer_5', 'customer_3')
445 customer_5 -10.302525784218853
resNode: customer_3 deliver_cap: 40.00074233561753 cap_limit: 40
1787 customer_5 ('customer_5', 'customer_1')
445 customer_5 -10.302525784218853
resNode: customer_1 deliver_cap: 33.773275371584525 cap_limit: 40
1788 customer_5 ('customer_5', 'depot_t')
445 customer_5 -10.302525784218853
resNode: depot_t deliver_cap: 18.318099571689334 cap_limit: 40
1789 customer_5 ('customer_5', 'customer_2')
445 customer_5 -10.302525784218853
resNode: customer_2 deliver_cap: 21.214585001672013 cap_limit: 40
1790 customer_5 ('customer_5', 'customer_4')
445 customer_5 -10.302525784218853
resNode: customer_4 deliver_cap: 39.79183817943227 cap_limit: 40
1791 customer_3 ('customer_3', 'customer_1')
446 customer_3 -15.655237947541675
resNode: customer_1 deliver_cap: 54.13966478757441 cap_limit: 40
1792 customer_3 ('customer_3', 'depot_t')
446 customer_3 -15.655237947541675
resNode: depot_t deliver_cap: 38.58525905099554 cap_limit: 40
1793 customer_3 ('customer_3', 'customer_2')
446 customer_3 -15.655237947541675
resNode: customer_2 deliver_cap: 42.80296734227316 cap_limit: 40
1794 customer_3 ('customer_3', 'customer_4')
446 customer_3 -15.655237947541675
resNode: customer_4 deliver_cap: 53.221398502266375 cap_limit: 40
1795 customer_3 ('customer_3', 'customer_5')
446 customer_3 -15.655237947541675
resNode: customer_5 deliver_cap: 48.23157381374442 cap_limit: 40
1796 customer_1 ('customer_1', 'customer_3')
447 customer_1 -13.334509191232193
resNode: customer_3 deliver_cap: 61.71934553365614 cap_limit: 40
1797 customer_1 ('customer_1', 'depot_t')
447 customer_1 -13.334509191232193
resNode: depot_t deliver_cap: 37.7568339771813 cap_limit: 40
1798 customer_1 ('customer_1', 'customer_2')
447 customer_1 -13.334509191232193
resNode: customer_2 deliver_cap: 40.66120582157986 cap_limit: 40
1799 customer_1 ('customer_1', 'customer_4')
447 customer_1 -13.334509191232193
resNode: customer_4 deliver_cap: 61.19535308610093 cap_limit: 40
1800 customer_1 ('customer_1', 'customer_5')
447 customer_1 -13.334509191232193
resNode: customer_5 deliver_cap: 49.58618196049959 cap_limit: 40
1801 customer_2 ('customer_2', 'customer_3')
449 customer_2 -11.892539363417473
resNode: customer_3 deliver_cap: 55.83814261360989 cap_limit: 40
1802 customer_2 ('customer_2', 'customer_1')
449 customer_2 -11.892539363417473
resNode: customer_1 deliver_cap: 45.15396601884869 cap_limit: 40
1803 customer_2 ('customer_2', 'depot_t')
449 customer_2 -11.892539363417473
resNode: depot_t deliver_cap: 29.328544624175002 cap_limit: 40
1804 customer_2 ('customer_2', 'customer_4')
449 customer_2 -11.892539363417473
resNode: customer_4 deliver_cap: 55.62923845742462 cap_limit: 40
1805 customer_2 ('customer_2', 'customer_5')
449 customer_2 -11.892539363417473
resNode: customer_5 deliver_cap: 39.791838179432254 cap_limit: 40
1806 customer_5 ('customer_5', 'customer_3')
450 customer_5 -18.683605833903968
resNode: customer_3 deliver_cap: 61.873984746389965 cap_limit: 40
1807 customer_5 ('customer_5', 'customer_1')
450 customer_5 -18.683605833903968
resNode: customer_1 deliver_cap: 53.60255050716657 cap_limit: 40
1808 customer_5 ('customer_5', 'depot_t')
450 customer_5 -18.683605833903968
resNode: depot_t deliver_cap: 34.396783623768314 cap_limit: 40
1809 customer_5 ('customer_5', 'customer_2')
450 customer_5 -18.683605833903968
resNode: customer_2 deliver_cap: 38.35271220084424 cap_limit: 40
1810 customer_5 ('customer_5', 'customer_4')
450 customer_5 -18.683605833903968
resNode: customer_4 deliver_cap: 61.628215150877885 cap_limit: 40
1811 customer_3 ('customer_3', 'customer_1')
451 customer_3 -10.377713322251406
resNode: customer_1 deliver_cap: 49.04015920514994 cap_limit: 40
1812 customer_3 ('customer_3', 'depot_t')
451 customer_3 -10.377713322251406

1882 customer_2 ('customer_2', 'customer_1')
469 customer_2 -5.622357405072999
resNode: customer_1 deliver_cap: 32.2834398008899 cap_limit: 40
1883 customer_2 ('customer_2', 'depot_t')
469 customer_2 -5.622357405072999
resNode: depot_t deliver_cap: 17.377341707498992 cap_limit: 40
1884 customer_2 ('customer_2', 'customer_4')
469 customer_2 -5.622357405072999
resNode: customer_4 deliver_cap: 40.00074233561754 cap_limit: 40
1885 customer_2 ('customer_2', 'customer_5')
469 customer_2 -5.622357405072999
resNode: customer_5 deliver_cap: 24.163342057625165 cap_limit: 40
1886 customer_4 ('customer_4', 'customer_3')
470 customer_4 -11.361788703043413
resNode: customer_3 deliver_cap: 48.477343409256505 cap_limit: 40
1887 customer_4 ('customer_4', 'customer_1')
470 customer_4 -11.361788703043413
resNode: customer_1 deliver_cap: 49.583225510960816 cap_limit: 40
1888 customer_4 ('customer_4', 'depot_t')
470 customer_4 -11.361788703043413
resNode: depot_t deliver_cap: 34.59339930017798 cap_limit: 40
1889 customer_4 ('customer_4', 'customer_2')
470 customer_4 -11.361788703043413
resNode: customer_2 deliver_cap: 38.5616163570295 cap_limit: 40
1890 customer_4 ('customer_4', 'customer_5')
470 customer_4 -11.361788703043413
resNode: customer_5 deliver_cap: 43.24174912522247 cap_limit: 40
1891 customer_1 ('customer_1', 'customer_3')
471 customer_1 -7.4058656822051
resNode: customer_3 deliver_cap: 49.21463264515798 cap_limit: 40
1892 customer_1 ('customer_1', 'depot_t')
471 customer_1 -7.4058656822051
resNode: depot_t deliver_cap: 27.891530103502408 cap_limit: 40
1893 customer_1 ('customer_1', 'customer_2')
471 customer_1 -7.4058656822051
resNode: customer_2 deliver_cap: 30.68068311385265 cap_limit: 40
1894 customer_1 ('customer_1', 'customer_4')
471 customer_1 -7.4058656822051
resNode: customer_4 deliver_cap: 48.78310945305368 cap_limit: 40
1895 customer_1 ('customer_1', 'customer_5')
471 customer_1 -7.4058656822051
resNode: customer_5 deliver_cap: 39.2226155849114 cap_limit: 40
1896 customer_2 ('customer_2', 'customer_3')
473 customer_2 -6.385272198252364
resNode: customer_3 deliver_cap: 44.11180458869758 cap_limit: 40
1897 customer_2 ('customer_2', 'customer_1')
473 customer_2 -6.385272198252364
resNode: customer_1 deliver_cap: 34.00682832401357 cap_limit: 40
1898 customer_2 ('customer_2', 'depot_t')
473 customer_2 -6.385272198252364
resNode: depot_t deliver_cap: 21.222884547442845 cap_limit: 40
1899 customer_2 ('customer_2', 'customer_4')
473 customer_2 -6.385272198252364
resNode: customer_4 deliver_cap: 43.939765871839136 cap_limit: 40
1900 customer_2 ('customer_2', 'customer_5')
473 customer_2 -6.385272198252364
resNode: customer_5 deliver_cap: 30.897200937021882 cap_limit: 40
1901 customer_4 ('customer_4', 'customer_3')
474 customer_4 -9.506189867580382
resNode: customer_3 deliver_cap: 42.96438025673501 cap_limit: 40
1902 customer_4 ('customer_4', 'customer_1')
474 customer_4 -9.506189867580382
resNode: customer_1 deliver_cap: 42.281534951622895 cap_limit: 40
1903 customer_4 ('customer_4', 'depot_t')
474 customer_4 -9.506189867580382
resNode: depot_t deliver_cap: 29.45197802935172 cap_limit: 40
1904 customer_4 ('customer_4', 'customer_2')
474 customer_4 -9.506189867580382
resNode: customer_2 deliver_cap: 33.20491564838535 cap_limit: 40
1905 customer_4 ('customer_4', 'customer_5')
474 customer_4 -9.506189867580382
resNode: customer_5 deliver_cap: 38.514125115306086 cap_limit: 40
1906 customer_5 ('customer_5', 'customer_3')
475 customer_5 -12.754445459163861
resNode: customer_3 deliver_cap: 50.31907856424007 cap_limit: 40
1907 customer_5 ('customer_5', 'customer_1')
475 customer_5 -12.754445459163861
resNode: customer_1 deliver_cap: 42.2707287363325 cap_limit: 40
1908 customer_5 ('customer_5', 'depot_t')
475 customer_5 -12.754445459163861
resNode: depot_t deliver_cap: 26.208591981812454 cap_limit: 40
1909 customer_5 ('customer_5', 'customer_2')
475 customer_5 -12.754445459163861
resNode: customer_2 deliver_cap: 29.71203836641999 cap_limit: 40
1910 customer_5 ('customer_5', 'customer_4')
475 customer_5 -12.754445459163861
resNode: customer_4 deliver_cap: 50.11017440805482 cap_limit: 40
1911 customer_3 ('customer_3', 'customer_1')
476 customer_3 -7.252693535858594
resNode: customer_1 deliver_cap: 34.00682832401357 cap_limit: 40
1912 customer_3 ('customer_3', 'depot_t')
476 customer_3 -7.252693535858594
resNode: depot_t deliver_cap: 23.184223743498528 cap_limit: 40
1913 customer_3 ('customer_3', 'customer_2')
476 customer_3 -7.252693535858594
resNode: customer_2 deliver_cap: 26.67131821234805 cap_limit: 40
1914 customer_3 ('customer_3', 'customer_4')
476 customer_3 -7.252693535858594
resNode: customer_4 deliver_cap: 35.95079052286331 cap_limit: 40
1915 customer_3 ('customer_3', 'customer_5')
476 customer_3 -7.252693535858594
resNode: customer_5 deliver_cap: 32.45791324089794 cap_limit: 40
1916 customer_1 ('customer_1', 'customer_3')
477 customer_1 -3.0238183850502693
resNode: customer_3 deliver_cap: 32.8381562295139 cap_limit: 40
1917 customer_1 ('customer_1', 'depot_t')
477 customer_1 -3.0238183850502693
resNode: depot_t deliver_cap: 15.813763259563357 cap_limit: 40
1918 customer_1 ('customer_1', 'customer_2')
477 customer_1 -3.0238183850502693
resNode: customer_2 deliver_cap: 18.072872296643837 cap_limit: 40
1919 customer_1 ('customer_1', 'customer_4')
477 customer_1 -3.0238183850502693
resNode: customer_4 deliver_cap: 32.49910229286053 cap_limit: 40
1920 customer_1 ('customer_1', 'customer_5')
477 customer_1 -3.0238183850502693
resNode: customer_5 deliver_cap: 24.987285682177305 cap_limit: 40
1921 customer_4 ('customer_4', 'customer_3')
479 customer_4 -7.238356976120389
resNode: customer_3 deliver_cap: 35.95079052286331 cap_limit: 40
1922 customer_4 ('customer_4', 'customer_1')
479 customer_4 -7.238356976120389
resNode: customer_1 deliver_cap: 33.6677743873602 cap_limit: 40
1923 customer_4 ('customer_4', 'depot_t')
479 customer_4 -7.238356976120389
resNode: depot_t deliver_cap: 23.06133894574249 cap_limit: 40
1924 customer_4 ('customer_4', 'customer_2')
479 customer_4 -7.238356976120389
resNode: customer_2 deliver_cap: 26.536144934816413 cap_limit: 40
1925 customer_4 ('customer_4', 'customer_5')
479 customer_4 -7.238356976120389
resNode: customer_5 deliver_cap: 32.285874524039485 cap_limit: 40
1926 customer_5 ('customer_5', 'customer_3')
480 customer_5 -6.239947440413639
resNode: customer_3 deliver_cap: 32.45791324089794 cap_limit: 40
1927 customer_5 ('customer_5', 'customer_1')
480 customer_5 -6.239947440413639
resNode: customer_1 deliver_cap: 26.15595777667698 cap_limit: 40
1928 customer_5 ('customer_5', 'depot_t')
480 customer_5 -6.239947440413639
resNode: depot_t deliver_cap: 13.745221135158745 cap_limit: 40
1929 customer_5 ('customer_5', 'customer_2')
480 customer_5 -6.239947440413639
resNode: customer_2 deliver_cap: 16.288415343174293 cap_limit: 40
1930 customer_5 ('customer_5', 'customer_4')
480 customer_5 -6.239947440413639
resNode: customer_4 deliver_cap: 32.28587452403949 cap_limit: 40
1931 customer_3 ('customer_3', 'customer_1')
481 customer_3 -9.248521638012562
resNode: customer_1 deliver_cap: 42.281534951622895 cap_limit: 40
1932 customer_3 ('customer_3', 'depot_t')
481 customer_3 -9.248521638012562
resNode: depot_t deliver_cap: 29.211028159480588 cap_limit: 40
1933 customer_3 ('customer_3', 'customer_2')
481 customer_3 -9.248521638012562
resNode: customer_2 deliver_cap: 32.94543117313951 cap_limit: 40
1934 customer_3 ('customer_3', 'customer_4')
481 customer_3 -9.248521638012562
resNode: customer_4 deliver_cap: 42.44038780917981 cap_limit: 40
1935 customer_3 ('customer_3', 'customer_5')
481 customer_3 -9.248521638012562
resNode: customer_5 deliver_cap: 38.19903682393614 cap_limit: 40
1936 customer_1 ('customer_1', 'customer_3')
482 customer_1 -7.175359983569562
resNode: customer_3 deliver_cap: 48.52362497780785 cap_limit: 40
1937 customer_1 ('customer_1', 'depot_t')
482 customer_1 -7.175359983569562
resNode: depot_t deliver_cap: 27.397953198252317 cap_limit: 40
1938 customer_1 ('customer_1', 'customer_2')
482 customer_1 -7.175359983569562
resNode: customer_2 deliver_cap: 30.137748518077547 cap_limit: 40
1939 customer_1 ('customer_1', 'customer_4')
482 customer_1 -7.175359983569562
resNode: customer_4 deliver_cap: 48.092101785703555 cap_limit: 40
1940 customer_1 ('customer_1', 'customer_5')
482 customer_1 -7.175359983569562
resNode: customer_5 deliver_cap: 38.531607917561274 cap_limit: 40
1941 customer_2 ('customer_2', 'customer_3')
484 customer_2 -6.219637618428287
resNode: customer_3 deliver_cap: 43.680281396593294 cap_limit: 40
1942 customer_2 ('customer_2', 'customer_1')
484 customer_2 -6.219637618428287
resNode: customer_1 deliver_cap: 33.6677743873602 cap_limit: 40
1943 customer_2 ('customer_2', 'depot_t')
484 customer_2 -6.219637618428287
resNode: depot_t deliver_cap: 20.914653695939784 cap_limit: 40
1944 customer_2 ('customer_2', 'customer_4')
484 customer_2 -6.219637618428287
resNode: customer_4 deliver_cap: 43.50824267973485 cap_limit: 40
1945 customer_2 ('customer_2', 'customer_5')
484 customer_2 -6.219637618428287
resNode: customer_5 deliver_cap: 30.465677744917596 cap_limit: 40
1946 customer_5 ('customer_5', 'customer_3')
485 customer_5 -12.473224310026133
resNode: customer_3 deliver_cap: 49.795086116684864 cap_limit: 40
1947 customer_5 ('customer_5', 'customer_1')
485 customer_5 -12.473224310026133
resNode: customer_1 deliver_cap: 41.83920554422821 cap_limit: 40
1948 customer_5 ('customer_5', 'depot_t')
485 customer_5 -12.473224310026133
resNode: depot_t deliver_cap: 25.80789187485847 cap_limit: 40
1949 customer_5 ('customer_5', 'customer_2')
485 customer_5 -12.473224310026133
resNode: customer_2 deliver_cap: 29.2805151743157 cap_limit: 40
1950 customer_5 ('customer_5', 'customer_4')
485 customer_5 -12.473224310026133
resNode: customer_4 deliver_cap: 49.586181960499594 cap_limit: 40
1951 customer_3 ('customer_3', 'customer_1')
486 customer_3 -11.56842292679778
resNode: customer_1 deliver_cap: 42.2707287363325 cap_limit: 40
1952 customer_3 ('customer_3', 'depot_t')
486 customer_3 -11.56842292679778
resNode: depot_t deliver_cap: 29.200993816710927 cap_limit: 40
1953 customer_3 ('customer_3', 'customer_2')
486 customer_3 -11.56842292679778
resNode: customer_2 deliver_cap: 32.93462495784911 cap_limit: 40
1954 customer_3 ('customer_3', 'customer_4')
486 customer_3 -11.56842292679778
resNode: customer_4 deliver_cap: 42.42726597632718 cap_limit: 40
1955 customer_3 ('customer_3', 'customer_5')
486 customer_3 -11.56842292679778
resNode: customer_5 deliver_cap: 38.18591499108352 cap_limit: 40
1956 customer_1 ('customer_1', 'customer_3')
487 customer_1 -7.981251647763339
resNode: customer_3 deliver_cap: 42.44520217634054 cap_limit: 40
1957 customer_1 ('customer_1', 'depot_t')
487 customer_1 -7.981251647763339
resNode: depot_t deliver_cap: 23.056222625775664 cap_limit: 40
1958 customer_1 ('customer_1', 'customer_2')
487 customer_1 -7.981251647763339
resNode: customer_2 deliver_cap: 25.361844888353232 cap_limit: 40
1959 customer_1 ('customer_1', 'customer_4')
487 customer_1 -7.981251647763339
resNode: customer_4 deliver_cap: 42.01367898423625 cap_limit: 40
1960 customer_1 ('customer_1', 'customer_5')
487 customer_1 -7.981251647763339
resNode: customer_5 deliver_cap: 32.45318511609397 cap_limit: 40
1961 customer_2 ('customer_2', 'customer_3')
489 customer_2 -6.155011515953322
resNode: customer_3 deliver_cap: 34.11978752845101 cap_limit: 40
1962 customer_2 ('customer_2', 'customer_1')
489 customer_2 -6.155011515953322
resNode: customer_1 deliver_cap: 26.15595777667698 cap_limit: 40
1963 customer_2 ('customer_2', 'depot_t')
489 customer_2 -6.155011515953322
resNode: depot_t deliver_cap: 14.085729504409585 cap_limit: 40
1964 customer_2 ('customer_2', 'customer_4')
489 customer_2 -6.155011515953322
resNode: customer_4 deliver_cap: 33.94774881159257 cap_limit: 40
1965 customer_2 ('customer_2', 'customer_5')
489 customer_2 -6.155011515953322
resNode: customer_5 deliver_cap: 20.90518387677532 cap_limit: 40
1966 customer_4 ('customer_4', 'customer_3')
490 customer_4 -11.544870007227875
resNode: customer_3 deliver_cap: 42.42726597632718 cap_limit: 40
1967 customer_4 ('customer_4', 'customer_1')
490 customer_4 -11.544870007227875
resNode: customer_1 deliver_cap: 41.83920554422821 cap_limit: 40
1968 customer_4 ('customer_4', 'depot_t')
490 customer_4 -11.544870007227875
resNode: depot_t deliver_cap: 29.04124357962808 cap_limit: 40
1969 customer_4 ('customer_4', 'customer_2')
490 customer_4 -11.544870007227875
resNode: customer_2 deliver_cap: 32.76258624099066 cap_limit: 40
1970 customer_4 ('customer_4', 'customer_5')
490 customer_4 -11.544870007227875
resNode: customer_5 deliver_cap: 37.97701083489825 cap_limit: 40
1971 customer_1 ('customer_1', 'customer_3')
491 customer_1 -3.3622052693672164
resNode: customer_3 deliver_cap: 40.88921799726846 cap_limit: 40
1972 customer_1 ('customer_1', 'depot_t')
491 customer_1 -3.3622052693672164
resNode: depot_t deliver_cap: 21.944805355009894 cap_limit: 40
1973 customer_1 ('customer_1', 'customer_2')
491 customer_1 -3.3622052693672164
resNode: customer_2 deliver_cap: 24.139285890510884 cap_limit: 40
1974 customer_1 ('customer_1', 'customer_4')
491 customer_1 -3.3622052693672164
resNode: customer_4 deliver_cap: 40.45769480516417 cap_limit: 40
1975 customer_1 ('customer_1', 'customer_5')
491 customer_1 -3.3622052693672164
resNode: customer_5 deliver_cap: 30.897200937021882 cap_limit: 40
1976 customer_2 ('customer_2', 'customer_3')
493 customer_2 -2.341611785414482
resNode: customer_3 deliver_cap: 35.786389940808064 cap_limit: 40
1977 customer_2 ('customer_2', 'customer_1')
493 customer_2 -2.341611785414482
resNode: customer_1 deliver_cap: 27.4654311006718 cap_limit: 40
1978 customer_2 ('customer_2', 'depot_t')
493 customer_2 -2.341611785414482
resNode: depot_t deliver_cap: 15.276159798950333 cap_limit: 40
1979 customer_2 ('customer_2', 'customer_4')
493 customer_2 -2.341611785414482
resNode: customer_4 deliver_cap: 35.61435122394961 cap_limit: 40
1980 customer_2 ('customer_2', 'customer_5')
493 customer_2 -2.341611785414482
resNode: customer_5 deliver_cap: 22.57178628913237 cap_limit: 40
1981 customer_4 ('customer_4', 'customer_3')
494 customer_4 -3.2325076740578056
resNode: customer_3 deliver_cap: 32.85494818429774 cap_limit: 40
1982 customer_4 ('customer_4', 'customer_1')
494 customer_4 -3.2325076740578056
resNode: customer_1 deliver_cap: 33.95612030373337 cap_limit: 40
1983 customer_4 ('customer_4', 'depot_t')
494 customer_4 -3.2325076740578056
resNode: depot_t deliver_cap: 21.721235856311452 cap_limit: 40
1984 customer_4 ('customer_4', 'customer_2')
494 customer_4 -3.2325076740578056
resNode: customer_2 deliver_cap: 24.879501000495832 cap_limit: 40
1985 customer_4 ('customer_4', 'customer_5')
494 customer_4 -3.2325076740578056
resNode: customer_5 deliver_cap: 28.404693042868814 cap_limit: 40
1986 customer_5 ('customer_5', 'customer_3')
495 customer_5 -6.480763265641285
resNode: customer_3 deliver_cap: 40.2096464918028 cap_limit: 40
1987 customer_5 ('customer_5', 'customer_1')
495 customer_5 -6.480763265641285
resNode: customer_1 deliver_cap: 33.945314088442984 cap_limit: 40
1988 customer_5 ('customer_5', 'depot_t')
495 customer_5 -6.480763265641285
resNode: depot_t deliver_cap: 18.477849808772184 cap_limit: 40
1989 customer_5 ('customer_5', 'customer_2')
495 customer_5 -6.480763265641285
resNode: customer_2 deliver_cap: 21.38662371853047 cap_limit: 40
1990 customer_5 ('customer_5', 'customer_4')
495 customer_5 -6.480763265641285
resNode: customer_4 deliver_cap: 40.00074233561754 cap_limit: 40
1991 customer_3 ('customer_3', 'customer_1')
496 customer_3 -4.931635387029449
resNode: customer_1 deliver_cap: 31.474796002176397 cap_limit: 40
1992 customer_3 ('customer_3', 'depot_t')
496 customer_3 -4.931635387029449
resNode: depot_t deliver_cap: 20.882376178192004 cap_limit: 40
1993 customer_3 ('customer_3', 'customer_2')
496 customer_3 -4.931635387029449
resNode: customer_2 deliver_cap: 24.139285890510877 cap_limit: 40
1994 customer_3 ('customer_3', 'customer_4')
496 customer_3 -4.931635387029449
resNode: customer_4 deliver_cap: 32.72820393143417 cap_limit: 40
1995 customer_3 ('customer_3', 'customer_5')
496 customer_3 -4.931635387029449
resNode: customer_5 deliver_cap: 29.23532664946881 cap_limit: 40
1996 customer_2 ('customer_2', 'customer_3')
498 customer_2 -1.0455080059628048
resNode: customer_3 deliver_cap: 26.296759006172127 cap_limit: 40
1997 customer_2 ('customer_2', 'customer_1')
498 customer_2 -1.0455080059628048
resNode: customer_1 deliver_cap: 18.650408942697474 cap_limit: 40
1998 customer_2 ('customer_2', 'depot_t')
498 customer_2 -1.0455080059628048
resNode: depot_t deliver_cap: 9.534418074607101 cap_limit: 40
1999 customer_2 ('customer_2', 'customer_4')
498 customer_2 -1.0455080059628048
resNode: customer_4 deliver_cap: 26.16158572864049 cap_limit: 40
2000 customer_2 ('customer_2', 'customer_5')
498 customer_2 -1.0455080059628048
resNode: customer_5 deliver_cap: 15.913856136998369 cap_limit: 40
2001 customer_4 ('customer_4', 'customer_3')
499 customer_4 -4.796823892355678
resNode: customer_3 deliver_cap: 32.46871945618834 cap_limit: 40
2002 customer_4 ('customer_4', 'customer_1')
499 customer_4 -4.796823892355678
resNode: customer_1 deliver_cap: 30.931861406401296 cap_limit: 40
2003 customer_4 ('customer_4', 'depot_t')
499 customer_4 -4.796823892355678
resNode: depot_t deliver_cap: 20.574145326688942 cap_limit: 40
2004 customer_4 ('customer_4', 'customer_2')
499 customer_4 -4.796823892355678
resNode: customer_2 deliver_cap: 23.80023195385751 cap_limit: 40
2005 customer_4 ('customer_4', 'customer_5')
499 customer_4 -4.796823892355678
resNode: customer_5 deliver_cap: 28.803803457364516 cap_limit: 40
2006 customer_5 ('customer_5', 'customer_3')
500 customer_5 -5.4150902090337345
resNode: customer_3 deliver_cap: 32.45791324089794 cap_limit: 40
2007 customer_5 ('customer_5', 'customer_1')
500 customer_5 -5.4150902090337345
resNode: customer_1 deliver_cap: 26.15595777667698 cap_limit: 40
2008 customer_5 ('customer_5', 'depot_t')
500 customer_5 -5.4150902090337345
resNode: depot_t deliver_cap: 13.745221135158745 cap_limit: 40
2009 customer_5 ('customer_5', 'customer_2')
500 customer_5 -5.4150902090337345
resNode: customer_2 deliver_cap: 16.288415343174293 cap_limit: 40
2010 customer_5 ('customer_5', 'customer_4')
500 customer_5 -5.4150902090337345
resNode: customer_4 deliver_cap: 32.28587452403949 cap_limit: 40
2011 customer_3 ('customer_3', 'customer_1')
501 customer_3 -3.183353754955391
resNode: customer_1 deliver_cap: 34.21560477897921 cap_limit: 40
2012 customer_3 ('customer_3', 'depot_t')
501 customer_3 -3.183353754955391
resNode: depot_t deliver_cap: 21.721235856311452 cap_limit: 40
2013 customer_3 ('customer_3', 'customer_2')
501 customer_3 -3.183353754955391
resNode: customer_2 deliver_cap: 24.879501000495832 cap_limit: 40
2014 customer_3 ('customer_3', 'customer_4')
501 customer_3 -3.183353754955391
resNode: customer_4 deliver_cap: 32.64604402811248 cap_limit: 40
2015 customer_3 ('customer_3', 'customer_5')
501 customer_3 -3.183353754955391
resNode: customer_5 deliver_cap: 28.404693042868825 cap_limit: 40
2016 customer_1 ('customer_1', 'customer_3')
502 customer_1 -3.270709111041949
resNode: customer_3 deliver_cap: 40.45769480516417 cap_limit: 40
2017 customer_1 ('customer_1', 'depot_t')
502 customer_1 -3.270709111041949
resNode: depot_t deliver_cap: 21.63657450350683 cap_limit: 40
2018 customer_1 ('customer_1', 'customer_2')
502 customer_1 -3.270709111041949

resNode: customer_2 deliver_cap: 23.80023195385751 cap_limit: 40
2019 customer_1 ('customer_1', 'customer_4')
502 customer_1 -3.270709111041949
resNode: customer_4 deliver_cap: 40.02617161305988 cap_limit: 40
2020 customer_1 ('customer_1', 'customer_5')
502 customer_1 -3.270709111041949
resNode: customer_5 deliver_cap: 30.465677744917596 cap_limit: 40
2021 customer_2 ('customer_2', 'customer_3')
504 customer_2 -2.314986745900674
resNode: customer_3 deliver_cap: 35.61435122394961 cap_limit: 40
2022 customer_2 ('customer_2', 'customer_1')
504 customer_2 -2.314986745900674
resNode: customer_1 deliver_cap: 27.330257823140165 cap_limit: 40
2023 customer_2 ('customer_2', 'depot_t')
504 customer_2 -2.314986745900674
resNode: depot_t deliver_cap: 15.153275001194297 cap_limit: 40
2024 customer_2 ('customer_2', 'customer_4')
504 customer_2 -2.314986745900674
resNode: customer_4 deliver_cap: 35.44231250709116 cap_limit: 40
2025 customer_2 ('customer_2', 'customer_5')
504 customer_2 -2.314986745900674
resNode: customer_5 deliver_cap: 22.399747572273917 cap_limit: 40
2026 customer_5 ('customer_5', 'customer_3')
505 customer_5 -6.408056426968962
resNode: customer_3 deliver_cap: 40.00074233561753 cap_limit: 40
2027 customer_5 ('customer_5', 'customer_1')
505 customer_5 -6.408056426968962
resNode: customer_1 deliver_cap: 33.773275371584525 cap_limit: 40
2028 customer_5 ('customer_5', 'depot_t')
505 customer_5 -6.408056426968962
resNode: depot_t deliver_cap: 18.318099571689334 cap_limit: 40
2029 customer_5 ('customer_5', 'customer_2')
505 customer_5 -6.408056426968962
resNode: customer_2 deliver_cap: 21.214585001672013 cap_limit: 40
2030 customer_5 ('customer_5', 'customer_4')
505 customer_5 -6.408056426968962
resNode: customer_4 deliver_cap: 39.79183817943227 cap_limit: 40
2031 customer_3 ('customer_3', 'customer_1')
506 customer_3 -2.7051622223053693
resNode: customer_1 deliver_cap: 30.72272749701385 cap_limit: 40
2032 customer_3 ('customer_3', 'depot_t')
506 customer_3 -2.7051622223053693
resNode: depot_t deliver_cap: 18.47784980877218 cap_limit: 40
2033 customer_3 ('customer_3', 'customer_2')
506 customer_3 -2.7051622223053693
resNode: customer_2 deliver_cap: 21.386623718530466 cap_limit: 40
2034 customer_3 ('customer_3', 'customer_4')
506 customer_3 -2.7051622223053693
resNode: customer_4 deliver_cap: 28.40469304286882 cap_limit: 40
2035 customer_3 ('customer_3', 'customer_5')
506 customer_3 -2.7051622223053693
resNode: customer_5 deliver_cap: 24.163342057625165 cap_limit: 40
2036 customer_1 ('customer_1', 'customer_3')
507 customer_1 -2.2112055609455643
resNode: customer_3 deliver_cap: 30.897200937021882 cap_limit: 40
2037 customer_1 ('customer_1', 'depot_t')
507 customer_1 -2.2112055609455643
resNode: depot_t deliver_cap: 14.807650311976628 cap_limit: 40
2038 customer_1 ('customer_1', 'customer_2')
507 customer_1 -2.2112055609455643
resNode: customer_2 deliver_cap: 16.28841534317429 cap_limit: 40
2039 customer_1 ('customer_1', 'customer_4')
507 customer_1 -2.2112055609455643
resNode: customer_4 deliver_cap: 30.465677744917592 cap_limit: 40
2040 customer_1 ('customer_1', 'customer_5')
507 customer_1 -2.2112055609455643
resNode: customer_5 deliver_cap: 20.905183876775318 cap_limit: 40
2041 customer_2 ('customer_2', 'customer_3')
509 customer_2 -0.38496542913554854
resNode: customer_3 deliver_cap: 22.57178628913237 cap_limit: 40
2042 customer_2 ('customer_2', 'customer_1')
509 customer_2 -0.38496542913554854
resNode: customer_1 deliver_cap: 17.08252823149804 cap_limit: 40
2043 customer_2 ('customer_2', 'depot_t')
509 customer_2 -0.38496542913554854
resNode: depot_t deliver_cap: 5.837157190610549 cap_limit: 40
2044 customer_2 ('customer_2', 'customer_4')
509 customer_2 -0.38496542913554854
resNode: customer_4 deliver_cap: 22.399747572273913 cap_limit: 40
2045 customer_2 ('customer_2', 'customer_5')
509 customer_2 -0.38496542913554854
resNode: customer_5 deliver_cap: 9.35718263745667 cap_limit: 40
2046 customer_4 ('customer_4', 'customer_3')
510 customer_4 -2.6816093027354624
resNode: customer_3 deliver_cap: 28.40469304286882 cap_limit: 40
2047 customer_4 ('customer_4', 'customer_1')
510 customer_4 -2.6816093027354624
resNode: customer_1 deliver_cap: 30.291204304909556 cap_limit: 40
2048 customer_4 ('customer_4', 'depot_t')
510 customer_4 -2.6816093027354624
resNode: depot_t deliver_cap: 18.318099571689334 cap_limit: 40
2049 customer_4 ('customer_4', 'customer_2')
510 customer_4 -2.6816093027354624
resNode: customer_2 deliver_cap: 21.214585001672013 cap_limit: 40
2050 customer_4 ('customer_4', 'customer_5')
510 customer_4 -2.6816093027354624
resNode: customer_5 deliver_cap: 23.954437901439896 cap_limit: 40
2051 customer_1 ('customer_1', 'customer_3')
511 customer_1 -4.095181029470401
resNode: customer_3 deliver_cap: 50.64728868846264 cap_limit: 40
2052 customer_1 ('customer_1', 'depot_t')
511 customer_1 -4.095181029470401
resNode: depot_t deliver_cap: 29.28996697791568 cap_limit: 40
2053 customer_1 ('customer_1', 'customer_2')
511 customer_1 -4.095181029470401
resNode: customer_2 deliver_cap: 31.54304136083227 cap_limit: 40
2054 customer_1 ('customer_1', 'customer_4')
511 customer_1 -4.095181029470401
resNode: customer_4 deliver_cap: 50.12329624090743 cap_limit: 40
2055 customer_1 ('customer_1', 'customer_5')
511 customer_1 -4.095181029470401
resNode: customer_5 deliver_cap: 38.514125115306086 cap_limit: 40
2056 customer_2 ('customer_2', 'customer_3')
513 customer_2 -2.574439128813202
resNode: customer_3 deliver_cap: 44.45099747704645 cap_limit: 40
2057 customer_2 ('customer_2', 'customer_1')
513 customer_2 -2.574439128813202
resNode: customer_1 deliver_cap: 35.77631708285526 cap_limit: 40
2058 customer_2 ('customer_2', 'depot_t')
513 customer_2 -2.574439128813202
resNode: depot_t deliver_cap: 20.620727755038256 cap_limit: 40
2059 customer_2 ('customer_2', 'customer_4')
513 customer_2 -2.574439128813202
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
2060 customer_2 ('customer_2', 'customer_5')
513 customer_2 -2.574439128813202
resNode: customer_5 deliver_cap: 28.40469304286882 cap_limit: 40
2061 customer_4 ('customer_4', 'customer_3')
514 customer_4 -3.7924981828232625
resNode: customer_3 deliver_cap: 39.82475716513291 cap_limit: 40
2062 customer_4 ('customer_4', 'customer_1')
514 customer_4 -3.7924981828232625
resNode: customer_1 deliver_cap: 42.228527203455755 cap_limit: 40
2063 customer_4 ('customer_4', 'depot_t')
514 customer_4 -3.7924981828232625
resNode: depot_t deliver_cap: 27.671330304879103 cap_limit: 40
2064 customer_4 ('customer_4', 'customer_2')
514 customer_4 -3.7924981828232625
resNode: customer_2 deliver_cap: 31.20691804952445 cap_limit: 40
2065 customer_4 ('customer_4', 'customer_5')
514 customer_4 -3.7924981828232625
resNode: customer_5 deliver_cap: 34.58916288109888 cap_limit: 40
2066 customer_5 ('customer_5', 'customer_3')
515 customer_5 -6.853635348587165
resNode: customer_3 deliver_cap: 48.47734340925649 cap_limit: 40
2067 customer_5 ('customer_5', 'customer_1')
515 customer_5 -6.853635348587165
resNode: customer_1 deliver_cap: 42.21540537060312 cap_limit: 40
2068 customer_5 ('customer_5', 'depot_t')
515 customer_5 -6.853635348587165
resNode: depot_t deliver_cap: 23.67947055406154 cap_limit: 40
2069 customer_5 ('customer_5', 'customer_2')
515 customer_5 -6.853635348587165
resNode: customer_2 deliver_cap: 26.965567064280794 cap_limit: 40
2070 customer_5 ('customer_5', 'customer_4')
515 customer_5 -6.853635348587165
resNode: customer_4 deliver_cap: 48.23157381374442 cap_limit: 40
2071 customer_3 ('customer_3', 'customer_1')
516 customer_3 -10.139807509462184
resNode: customer_1 deliver_cap: 48.60863601304565 cap_limit: 40
2072 customer_3 ('customer_3', 'depot_t')
516 customer_3 -10.139807509462184
resNode: depot_t deliver_cap: 35.08619343080171 cap_limit: 40
2073 customer_3 ('customer_3', 'customer_2')
516 customer_3 -10.139807509462184
resNode: customer_2 deliver_cap: 39.27253223456226 cap_limit: 40
2074 customer_3 ('customer_3', 'customer_4')
516 customer_3 -10.139807509462184
resNode: customer_4 deliver_cap: 50.12329624090743 cap_limit: 40
2075 customer_3 ('customer_3', 'customer_5')
516 customer_3 -10.139807509462184
resNode: customer_5 deliver_cap: 45.88194525566377 cap_limit: 40
2076 customer_2 ('customer_2', 'customer_3')
518 customer_2 -3.418920439752858
resNode: customer_3 deliver_cap: 42.01840710904022 cap_limit: 40
2077 customer_2 ('customer_2', 'customer_1')
518 customer_2 -3.418920439752858
resNode: customer_1 deliver_cap: 32.36201601856849 cap_limit: 40
2078 customer_2 ('customer_2', 'depot_t')
518 customer_2 -3.418920439752858
resNode: depot_t deliver_cap: 19.72760063340187 cap_limit: 40
2079 customer_2 ('customer_2', 'customer_4')
518 customer_2 -3.418920439752858
resNode: customer_4 deliver_cap: 41.846368392181766 cap_limit: 40
2080 customer_2 ('customer_2', 'customer_5')
518 customer_2 -3.418920439752858
resNode: customer_5 deliver_cap: 28.803803457364516 cap_limit: 40
2081 customer_4 ('customer_4', 'customer_3')
519 customer_4 -9.98187870092568
resNode: customer_3 deliver_cap: 49.808207949537476 cap_limit: 40
2082 customer_4 ('customer_4', 'customer_1')
519 customer_4 -9.98187870092568
resNode: customer_1 deliver_cap: 47.91762834569552 cap_limit: 40
2083 customer_4 ('customer_4', 'depot_t')
519 customer_4 -9.98187870092568
resNode: depot_t deliver_cap: 34.68549332384772 cap_limit: 40
2084 customer_4 ('customer_4', 'customer_2')
519 customer_4 -9.98187870092568
resNode: customer_2 deliver_cap: 38.84100904245797 cap_limit: 40
2085 customer_4 ('customer_4', 'customer_5')
519 customer_4 -9.98187870092568
resNode: customer_5 deliver_cap: 45.35795280810856 cap_limit: 40
2086 customer_5 ('customer_5', 'customer_3')
520 customer_5 -10.087975703238975
resNode: customer_3 deliver_cap: 49.79508611668486 cap_limit: 40
2087 customer_5 ('customer_5', 'customer_1')
520 customer_5 -10.087975703238975
resNode: customer_1 deliver_cap: 41.83920554422821 cap_limit: 40
2088 customer_5 ('customer_5', 'depot_t')
520 customer_5 -10.087975703238975
resNode: depot_t deliver_cap: 25.807891874858466 cap_limit: 40
2089 customer_5 ('customer_5', 'customer_2')
520 customer_5 -10.087975703238975
resNode: customer_2 deliver_cap: 29.280515174315692 cap_limit: 40
2090 customer_5 ('customer_5', 'customer_4')
520 customer_5 -10.087975703238975
resNode: customer_4 deliver_cap: 49.586181960499594 cap_limit: 40
2091 customer_3 ('customer_3', 'customer_1')
521 customer_3 -8.29674995105579
resNode: customer_1 deliver_cap: 43.76529243183109 cap_limit: 40
2092 customer_3 ('customer_3', 'depot_t')
521 customer_3 -8.29674995105579
resNode: depot_t deliver_cap: 30.58880296253105 cap_limit: 40
2093 customer_3 ('customer_3', 'customer_2')
521 customer_3 -8.29674995105579
resNode: customer_2 deliver_cap: 34.42918865334771 cap_limit: 40
2094 customer_3 ('customer_3', 'customer_4')
521 customer_3 -8.29674995105579
resNode: customer_4 deliver_cap: 44.24209332086119 cap_limit: 40
2095 customer_3 ('customer_3', 'customer_5')
521 customer_3 -8.29674995105579
resNode: customer_5 deliver_cap: 40.00074233561753 cap_limit: 40
2096 customer_1 ('customer_1', 'customer_3')
522 customer_1 -3.8937805388388123
resNode: customer_3 deliver_cap: 42.27789158428605 cap_limit: 40
2097 customer_1 ('customer_1', 'depot_t')
522 customer_1 -3.8937805388388123
resNode: depot_t deliver_cap: 22.93671506002246 cap_limit: 40
2098 customer_1 ('customer_1', 'customer_2')
522 customer_1 -3.8937805388388123
resNode: customer_2 deliver_cap: 25.230386566024706 cap_limit: 40
2099 customer_1 ('customer_1', 'customer_4')
522 customer_1 -3.8937805388388123
resNode: customer_4 deliver_cap: 41.846368392181766 cap_limit: 40
2100 customer_1 ('customer_1', 'customer_5')
522 customer_1 -3.8937805388388123
resNode: customer_5 deliver_cap: 32.285874524039485 cap_limit: 40
2101 customer_4 ('customer_4', 'customer_3')
524 customer_4 -8.273197031485884
resNode: customer_3 deliver_cap: 44.24209332086119 cap_limit: 40
2102 customer_4 ('customer_4', 'customer_1')
524 customer_4 -8.273197031485884
resNode: customer_1 deliver_cap: 43.333769239726806 cap_limit: 40
2103 customer_4 ('customer_4', 'depot_t')
524 customer_4 -8.273197031485884
resNode: depot_t deliver_cap: 30.429052725448205 cap_limit: 40
2104 customer_4 ('customer_4', 'customer_2')
524 customer_4 -8.273197031485884
resNode: customer_2 deliver_cap: 34.257149936489256 cap_limit: 40
2105 customer_4 ('customer_4', 'customer_5')
524 customer_4 -8.273197031485884
resNode: customer_5 deliver_cap: 39.79183817943226 cap_limit: 40
2106 customer_5 ('customer_5', 'customer_3')
525 customer_5 -6.576078659985353
resNode: customer_3 deliver_cap: 40.00074233561753 cap_limit: 40
2107 customer_5 ('customer_5', 'customer_1')
525 customer_5 -6.576078659985353
resNode: customer_1 deliver_cap: 33.773275371584525 cap_limit: 40
2108 customer_5 ('customer_5', 'depot_t')
525 customer_5 -6.576078659985353
resNode: depot_t deliver_cap: 18.318099571689334 cap_limit: 40
2109 customer_5 ('customer_5', 'customer_2')
525 customer_5 -6.576078659985353
resNode: customer_2 deliver_cap: 21.214585001672013 cap_limit: 40
2110 customer_5 ('customer_5', 'customer_4')
525 customer_5 -6.576078659985353
resNode: customer_4 deliver_cap: 39.79183817943227 cap_limit: 40
2111 customer_3 ('customer_3', 'customer_1')
526 customer_3 -11.263480864838579
resNode: customer_1 deliver_cap: 49.89831380233076 cap_limit: 40
2112 customer_3 ('customer_3', 'depot_t')
526 customer_3 -11.263480864838579
resNode: depot_t deliver_cap: 34.59339930017798 cap_limit: 40
2113 customer_3 ('customer_3', 'customer_2')
526 customer_3 -11.263480864838579
resNode: customer_2 deliver_cap: 38.5616163570295 cap_limit: 40
2114 customer_3 ('customer_3', 'customer_4')
526 customer_3 -11.263480864838579
resNode: customer_4 deliver_cap: 48.231573813744426 cap_limit: 40
2115 customer_3 ('customer_3', 'customer_5')
526 customer_3 -11.263480864838579
resNode: customer_5 deliver_cap: 43.24174912522247 cap_limit: 40
2116 customer_1 ('customer_1', 'customer_3')
527 customer_1 -8.036389202537542
resNode: customer_3 deliver_cap: 50.110174408054796 cap_limit: 40
2117 customer_1 ('customer_1', 'depot_t')
527 customer_1 -8.036389202537542
resNode: depot_t deliver_cap: 28.879232528192038 cap_limit: 40
2118 customer_1 ('customer_1', 'customer_2')
527 customer_1 -8.036389202537542
resNode: customer_2 deliver_cap: 31.10071195343758 cap_limit: 40
2119 customer_1 ('customer_1', 'customer_4')
527 customer_1 -8.036389202537542
resNode: customer_4 deliver_cap: 49.586181960499594 cap_limit: 40
2120 customer_1 ('customer_1', 'customer_5')
527 customer_1 -8.036389202537542
resNode: customer_5 deliver_cap: 37.97701083489825 cap_limit: 40
2121 customer_2 ('customer_2', 'customer_3')
529 customer_2 -5.53736208662507
resNode: customer_3 deliver_cap: 40.00074233561753 cap_limit: 40
2122 customer_2 ('customer_2', 'customer_1')
529 customer_2 -5.53736208662507
resNode: customer_1 deliver_cap: 32.11140108403144 cap_limit: 40
2123 customer_2 ('customer_2', 'depot_t')
529 customer_2 -5.53736208662507
resNode: depot_t deliver_cap: 17.21759147041614 cap_limit: 40
2124 customer_2 ('customer_2', 'customer_4')
529 customer_2 -5.53736208662507
resNode: customer_4 deliver_cap: 39.79183817943227 cap_limit: 40
2125 customer_2 ('customer_2', 'customer_5')
529 customer_2 -5.53736208662507
resNode: customer_5 deliver_cap: 23.954437901439896 cap_limit: 40
2126 customer_4 ('customer_4', 'customer_3')
530 customer_4 -11.230711585436968
resNode: customer_3 deliver_cap: 48.231573813744426 cap_limit: 40
2127 customer_4 ('customer_4', 'customer_1')
530 customer_4 -11.230711585436968
resNode: customer_1 deliver_cap: 49.374321354775546 cap_limit: 40
2128 customer_4 ('customer_4', 'depot_t')
530 customer_4 -11.230711585436968
resNode: depot_t deliver_cap: 34.396783623768314 cap_limit: 40
2129 customer_4 ('customer_4', 'customer_2')
530 customer_4 -11.230711585436968
resNode: customer_2 deliver_cap: 38.35271220084424 cap_limit: 40
2130 customer_4 ('customer_4', 'customer_5')
530 customer_4 -11.230711585436968
resNode: customer_5 deliver_cap: 42.9959795297104 cap_limit: 40
2131 customer_2 ('customer_2', 'customer_3')
533 customer_2 -15.356896249419298
resNode: customer_3 deliver_cap: 67.97134867224379 cap_limit: 40
2132 customer_2 ('customer_2', 'customer_1')
533 customer_2 -15.356896249419298
resNode: customer_1 deliver_cap: 53.66531889056256 cap_limit: 40
2133 customer_2 ('customer_2', 'depot_t')
533 customer_2 -15.356896249419298
resNode: depot_t deliver_cap: 38.531553661189236 cap_limit: 40
2134 customer_2 ('customer_2', 'customer_4')
533 customer_2 -15.356896249419298
resNode: customer_4 deliver_cap: 67.78702147560973 cap_limit: 40
2135 customer_2 ('customer_2', 'customer_5')
533 customer_2 -15.356896249419298
resNode: customer_5 deliver_cap: 53.81284475973411 cap_limit: 40
2136 customer_2 ('customer_2', 'customer_3')
549 customer_2 -22.8936179554739
resNode: customer_3 deliver_cap: 69.56205640578534 cap_limit: 40
2137 customer_2 ('customer_2', 'customer_1')
549 customer_2 -22.8936179554739
resNode: customer_1 deliver_cap: 57.078680279113854 cap_limit: 40
2138 customer_2 ('customer_2', 'depot_t')
549 customer_2 -22.8936179554739
resNode: depot_t deliver_cap: 39.70405542666656 cap_limit: 40
2139 customer_2 ('customer_2', 'customer_4')
549 customer_2 -22.8936179554739
resNode: customer_4 deliver_cap: 69.34086376982447 cap_limit: 40
2140 customer_2 ('customer_2', 'customer_5')
549 customer_2 -22.8936179554739
resNode: customer_5 deliver_cap: 52.57185171077372 cap_limit: 40
2141 customer_2 ('customer_2', 'customer_3')
553 customer_2 -15.013721749379012
resNode: customer_3 deliver_cap: 62.504032897464796 cap_limit: 40
2142 customer_2 ('customer_2', 'customer_1')
553 customer_2 -15.013721749379012
resNode: customer_1 deliver_cap: 49.29146627073936 cap_limit: 40
2143 customer_2 ('customer_2', 'depot_t')
553 customer_2 -15.013721749379012
resNode: depot_t deliver_cap: 34.52218875968464 cap_limit: 40
2144 customer_2 ('customer_2', 'customer_4')
553 customer_2 -15.013721749379012
resNode: customer_4 deliver_cap: 62.31970570083074 cap_limit: 40
2145 customer_2 ('customer_2', 'customer_5')
553 customer_2 -15.013721749379012
resNode: customer_5 deliver_cap: 48.345528984955116 cap_limit: 40
2146 customer_2 ('customer_2', 'customer_3')
558 customer_2 -7.635860844539794
resNode: customer_3 deliver_cap: 48.016551258557904 cap_limit: 40
2147 customer_2 ('customer_2', 'customer_1')
558 customer_2 -7.635860844539794
resNode: customer_1 deliver_cap: 35.47859340849407 cap_limit: 40
2148 customer_2 ('customer_2', 'depot_t')
558 customer_2 -7.635860844539794
resNode: depot_t deliver_cap: 23.782596331070447 cap_limit: 40
2149 customer_2 ('customer_2', 'customer_4')
558 customer_2 -7.635860844539794
resNode: customer_4 deliver_cap: 47.869089501250656 cap_limit: 40
2150 customer_2 ('customer_2', 'customer_5')
558 customer_2 -7.635860844539794
resNode: customer_5 deliver_cap: 36.68974812855016 cap_limit: 40
2151 customer_5 ('customer_5', 'customer_3')
560 customer_5 -18.048926706403478
resNode: customer_3 deliver_cap: 58.9378078618468 cap_limit: 40
2152 customer_5 ('customer_5', 'customer_1')
560 customer_5 -18.048926706403478
resNode: customer_1 deliver_cap: 47.862949917290464 cap_limit: 40
2153 customer_5 ('customer_5', 'depot_t')
560 customer_5 -18.048926706403478
resNode: depot_t deliver_cap: 32.83815622951389 cap_limit: 40
2154 customer_5 ('customer_5', 'customer_2')
560 customer_5 -18.048926706403478
resNode: customer_2 deliver_cap: 37.09835817165116 cap_limit: 40
2155 customer_5 ('customer_5', 'customer_4')
560 customer_5 -18.048926706403478
resNode: customer_4 deliver_cap: 58.75348066521275 cap_limit: 40
2156 customer_2 ('customer_2', 'customer_3')
564 customer_2 -14.984024589921304
resNode: customer_3 deliver_cap: 62.31970570083074 cap_limit: 40
2157 customer_2 ('customer_2', 'customer_1')
564 customer_2 -14.984024589921304

624 customer_2 -16.047697833002708
resNode: customer_5 deliver_cap: 50.50191500070869 cap_limit: 40
2216 customer_2 ('customer_2', 'customer_3')
629 customer_2 -18.984089381553567
resNode: customer_3 deliver_cap: 63.001277476050554 cap_limit: 40
2217 customer_2 ('customer_2', 'customer_1')
629 customer_2 -18.984089381553567
resNode: customer_1 deliver_cap: 51.611364504334865 cap_limit: 40
2218 customer_2 ('customer_2', 'depot_t')
629 customer_2 -18.984089381553567
resNode: depot_t deliver_cap: 34.60122737020616 cap_limit: 40
2219 customer_2 ('customer_2', 'customer_4')
629 customer_2 -18.984089381553567
resNode: customer_4 deliver_cap: 62.780084840089685 cap_limit: 40
2220 customer_2 ('customer_2', 'customer_5')
629 customer_2 -18.984089381553567
resNode: customer_5 deliver_cap: 46.01107278103893 cap_limit: 40
2221 customer_2 ('customer_2', 'customer_3')
633 customer_2 -14.649234031060415
resNode: customer_3 deliver_cap: 62.504032897464796 cap_limit: 40
2222 customer_2 ('customer_2', 'customer_1')
633 customer_2 -14.649234031060415
resNode: customer_1 deliver_cap: 49.29146627073936 cap_limit: 40
2223 customer_2 ('customer_2', 'depot_t')
633 customer_2 -14.649234031060415
resNode: depot_t deliver_cap: 34.52218875968464 cap_limit: 40
2224 customer_2 ('customer_2', 'customer_4')
633 customer_2 -14.649234031060415
resNode: customer_4 deliver_cap: 62.31970570083074 cap_limit: 40
2225 customer_2 ('customer_2', 'customer_5')
633 customer_2 -14.649234031060415
resNode: customer_5 deliver_cap: 48.345528984955116 cap_limit: 40
2226 customer_3 ('customer_3', 'customer_1')
636 customer_3 -15.565688848568033
resNode: customer_1 deliver_cap: 49.29146627073936 cap_limit: 40
2227 customer_3 ('customer_3', 'depot_t')
636 customer_3 -15.565688848568033
resNode: depot_t deliver_cap: 36.67966187534589 cap_limit: 40
2228 customer_3 ('customer_3', 'customer_2')
636 customer_3 -15.565688848568033
resNode: customer_2 deliver_cap: 41.28909160346789 cap_limit: 40
2229 customer_3 ('customer_3', 'customer_4')
636 customer_3 -15.565688848568033
resNode: customer_4 deliver_cap: 53.760089255499494 cap_limit: 40
2230 customer_3 ('customer_3', 'customer_5')
636 customer_3 -15.565688848568033
resNode: customer_5 deliver_cap: 50.017720739108036 cap_limit: 40
2231 customer_1 ('customer_1', 'customer_3')
637 customer_1 -7.511639082477308
resNode: customer_3 deliver_cap: 48.016551258557904 cap_limit: 40
2232 customer_1 ('customer_1', 'depot_t')
637 customer_1 -7.511639082477308
resNode: depot_t deliver_cap: 26.201611029369303 cap_limit: 40
2233 customer_1 ('customer_1', 'customer_2')
637 customer_1 -7.511639082477308
resNode: customer_2 deliver_cap: 29.476812408040466 cap_limit: 40
2234 customer_1 ('customer_1', 'customer_4')
637 customer_1 -7.511639082477308
resNode: customer_4 deliver_cap: 47.64667423675423 cap_limit: 40
2235 customer_1 ('customer_1', 'customer_5')
637 customer_1 -7.511639082477308
resNode: customer_5 deliver_cap: 39.45196520691799 cap_limit: 40
2236 customer_4 ('customer_4', 'customer_3')
639 customer_4 -15.548280168885928
resNode: customer_3 deliver_cap: 53.760089255499494 cap_limit: 40
2237 customer_4 ('customer_4', 'customer_1')
639 customer_4 -15.548280168885928
resNode: customer_1 deliver_cap: 48.92158924893569 cap_limit: 40
2238 customer_4 ('customer_4', 'depot_t')
639 customer_4 -15.548280168885928
resNode: depot_t deliver_cap: 36.54448859781425 cap_limit: 40
2239 customer_4 ('customer_4', 'customer_2')
639 customer_4 -15.548280168885928
resNode: customer_2 deliver_cap: 41.14162984616064 cap_limit: 40
2240 customer_4 ('customer_4', 'customer_5')
639 customer_4 -15.548280168885928
resNode: customer_5 deliver_cap: 49.83339354247398 cap_limit: 40
2241 customer_5 ('customer_5', 'customer_3')
640 customer_5 -14.316967687914584
resNode: customer_3 deliver_cap: 50.017720739108036 cap_limit: 40
2242 customer_5 ('customer_5', 'customer_1')
640 customer_5 -14.316967687914584
resNode: customer_1 deliver_cap: 40.72688021909944 cap_limit: 40
2243 customer_5 ('customer_5', 'depot_t')
640 customer_5 -14.316967687914584
resNode: depot_t deliver_cap: 26.296759006172127 cap_limit: 40
2244 customer_5 ('customer_5', 'customer_2')
640 customer_5 -14.316967687914584
resNode: customer_2 deliver_cap: 29.962288473460145 cap_limit: 40
2245 customer_5 ('customer_5', 'customer_4')
640 customer_5 -14.316967687914584
resNode: customer_4 deliver_cap: 49.83339354247398 cap_limit: 40
2246 customer_2 ('customer_2', 'customer_3')
644 customer_2 -14.475893679948761
resNode: customer_3 deliver_cap: 62.0416866202102 cap_limit: 40
2247 customer_2 ('customer_2', 'customer_1')
644 customer_2 -14.475893679948761
resNode: customer_1 deliver_cap: 48.92158924893569 cap_limit: 40
2248 customer_2 ('customer_2', 'depot_t')
644 customer_2 -14.475893679948761
resNode: depot_t deliver_cap: 34.183134823031274 cap_limit: 40
2249 customer_2 ('customer_2', 'customer_4')
644 customer_2 -14.475893679948761
resNode: customer_4 deliver_cap: 61.85735942357614 cap_limit: 40
2250 customer_2 ('customer_2', 'customer_5')
644 customer_2 -14.475893679948761
resNode: customer_5 deliver_cap: 47.88318270770053 cap_limit: 40
2251 customer_1 ('customer_1', 'customer_3')
647 customer_1 -16.29104693252971
resNode: customer_3 deliver_cap: 60.718387455653684 cap_limit: 40
2252 customer_1 ('customer_1', 'depot_t')
647 customer_1 -16.29104693252971
resNode: depot_t deliver_cap: 36.53886064585075 cap_limit: 40
2253 customer_1 ('customer_1', 'customer_2')
647 customer_1 -16.29104693252971
resNode: customer_2 deliver_cap: 39.860575250019 cap_limit: 40
2254 customer_1 ('customer_1', 'customer_4')
647 customer_1 -16.29104693252971
resNode: customer_4 deliver_cap: 60.25604117839909 cap_limit: 40
2255 customer_1 ('customer_1', 'customer_5')
647 customer_1 -16.29104693252971
resNode: customer_5 deliver_cap: 50.012654891103786 cap_limit: 40
2256 customer_2 ('customer_2', 'customer_3')
649 customer_2 -14.240544472685542
resNode: customer_3 deliver_cap: 51.7983003329149 cap_limit: 40
2257 customer_2 ('customer_2', 'customer_1')
649 customer_2 -14.240544472685542
resNode: customer_1 deliver_cap: 40.72688021909945 cap_limit: 40
2258 customer_2 ('customer_2', 'depot_t')
649 customer_2 -14.240544472685542
resNode: depot_t deliver_cap: 26.67131821234805 cap_limit: 40
2259 customer_2 ('customer_2', 'customer_4')
649 customer_2 -14.240544472685542
resNode: customer_4 deliver_cap: 51.61397313628085 cap_limit: 40
2260 customer_2 ('customer_2', 'customer_5')
649 customer_2 -14.240544472685542
resNode: customer_5 deliver_cap: 37.639796420405226 cap_limit: 40
2261 customer_2 ('customer_2', 'customer_3')
653 customer_2 -15.998543913900294
resNode: customer_3 deliver_cap: 67.4921196957203 cap_limit: 40
2262 customer_2 ('customer_2', 'customer_1')
653 customer_2 -15.998543913900294
resNode: customer_1 deliver_cap: 55.35373302072633 cap_limit: 40
2263 customer_2 ('customer_2', 'depot_t')
653 customer_2 -15.998543913900294
resNode: depot_t deliver_cap: 38.09410465217153 cap_limit: 40
2264 customer_2 ('customer_2', 'customer_4')
653 customer_2 -15.998543913900294
resNode: customer_4 deliver_cap: 67.27092705975943 cap_limit: 40
2265 customer_2 ('customer_2', 'customer_5')
653 customer_2 -15.998543913900294
resNode: customer_5 deliver_cap: 50.50191500070869 cap_limit: 40
2266 customer_2 ('customer_2', 'customer_3')
658 customer_2 -12.68417160443056
resNode: customer_3 deliver_cap: 62.0416866202102 cap_limit: 40
2267 customer_2 ('customer_2', 'customer_1')
658 customer_2 -12.68417160443056
resNode: customer_1 deliver_cap: 48.92158924893569 cap_limit: 40
2268 customer_2 ('customer_2', 'depot_t')
658 customer_2 -12.68417160443056
resNode: depot_t deliver_cap: 34.183134823031274 cap_limit: 40
2269 customer_2 ('customer_2', 'customer_4')
658 customer_2 -12.68417160443056
resNode: customer_4 deliver_cap: 61.85735942357614 cap_limit: 40
2270 customer_2 ('customer_2', 'customer_5')
658 customer_2 -12.68417160443056
resNode: customer_5 deliver_cap: 47.88318270770053 cap_limit: 40
2271 customer_1 ('customer_1', 'customer_3')
662 customer_1 -13.23925956418203
resNode: customer_3 deliver_cap: 62.31970570083075 cap_limit: 40
2272 customer_1 ('customer_1', 'depot_t')
662 customer_1 -13.23925956418203
resNode: depot_t deliver_cap: 37.71316069231393 cap_limit: 40
2273 customer_1 ('customer_1', 'customer_2')
662 customer_1 -13.23925956418203
resNode: customer_2 deliver_cap: 41.141629846160654 cap_limit: 40
2274 customer_1 ('customer_1', 'customer_4')
662 customer_1 -13.23925956418203
resNode: customer_4 deliver_cap: 61.857359423576156 cap_limit: 40
2275 customer_1 ('customer_1', 'customer_5')
662 customer_1 -13.23925956418203
resNode: customer_5 deliver_cap: 51.613973136280855 cap_limit: 40
2276 customer_5 ('customer_5', 'customer_3')
665 customer_5 -19.955902133854195
resNode: customer_3 deliver_cap: 62.780084840089685 cap_limit: 40
2277 customer_5 ('customer_5', 'customer_1')
665 customer_5 -19.955902133854195
resNode: customer_1 deliver_cap: 53.20761690150767 cap_limit: 40
2278 customer_5 ('customer_5', 'depot_t')
665 customer_5 -19.955902133854195
resNode: depot_t deliver_cap: 35.61435122394961 cap_limit: 40
2279 customer_5 ('customer_5', 'customer_2')
665 customer_5 -19.955902133854195
resNode: customer_2 deliver_cap: 39.75187721945855 cap_limit: 40
2280 customer_5 ('customer_5', 'customer_4')
665 customer_5 -19.955902133854195
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
2281 customer_2 ('customer_2', 'customer_3')
669 customer_2 -18.896021943161735
resNode: customer_3 deliver_cap: 62.78008484008968 cap_limit: 40
2282 customer_2 ('customer_2', 'customer_1')
669 customer_2 -18.896021943161735
resNode: customer_1 deliver_cap: 51.42703730770081 cap_limit: 40
2283 customer_2 ('customer_2', 'depot_t')
669 customer_2 -18.896021943161735
resNode: depot_t deliver_cap: 34.42918865334771 cap_limit: 40
2284 customer_2 ('customer_2', 'customer_4')
669 customer_2 -18.896021943161735
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
2285 customer_2 ('customer_2', 'customer_5')
669 customer_2 -18.896021943161735
resNode: customer_5 deliver_cap: 45.789880145078065 cap_limit: 40
2286 customer_2 ('customer_2', 'customer_3')
673 customer_2 -15.20848833821765
resNode: customer_3 deliver_cap: 63.001277476050554 cap_limit: 40
2287 customer_2 ('customer_2', 'customer_1')
673 customer_2 -15.20848833821765
resNode: customer_1 deliver_cap: 51.611364504334865 cap_limit: 40
2288 customer_2 ('customer_2', 'depot_t')
673 customer_2 -15.20848833821765
resNode: depot_t deliver_cap: 34.60122737020616 cap_limit: 40
2289 customer_2 ('customer_2', 'customer_4')
673 customer_2 -15.20848833821765
resNode: customer_4 deliver_cap: 62.780084840089685 cap_limit: 40
2290 customer_2 ('customer_2', 'customer_5')
673 customer_2 -15.20848833821765
resNode: customer_5 deliver_cap: 46.01107278103893 cap_limit: 40
2291 customer_2 ('customer_2', 'customer_3')
678 customer_2 -10.771052530392902
resNode: customer_3 deliver_cap: 51.7983003329149 cap_limit: 40
2292 customer_2 ('customer_2', 'customer_1')
678 customer_2 -10.771052530392902
resNode: customer_1 deliver_cap: 40.72688021909945 cap_limit: 40
2293 customer_2 ('customer_2', 'depot_t')
678 customer_2 -10.771052530392902
resNode: depot_t deliver_cap: 26.67131821234805 cap_limit: 40
2294 customer_2 ('customer_2', 'customer_4')
678 customer_2 -10.771052530392902
resNode: customer_4 deliver_cap: 51.61397313628085 cap_limit: 40
2295 customer_2 ('customer_2', 'customer_5')
678 customer_2 -10.771052530392902
resNode: customer_5 deliver_cap: 37.639796420405226 cap_limit: 40
2296 customer_5 ('customer_5', 'customer_3')
680 customer_5 -19.137867998614972
resNode: customer_3 deliver_cap: 60.858502945877206 cap_limit: 40
2297 customer_5 ('customer_5', 'customer_1')
680 customer_5 -19.137867998614972
resNode: customer_1 deliver_cap: 51.60629865633061 cap_limit: 40
2298 customer_5 ('customer_5', 'depot_t')
680 customer_5 -19.137867998614972
resNode: depot_t deliver_cap: 34.11978752845101 cap_limit: 40
2299 customer_5 ('customer_5', 'customer_2')
680 customer_5 -19.137867998614972
resNode: customer_2 deliver_cap: 38.15055897428148 cap_limit: 40
2300 customer_5 ('customer_5', 'customer_4')
680 customer_5 -19.137867998614972
resNode: customer_4 deliver_cap: 60.63731030991633 cap_limit: 40
2301 customer_3 ('customer_3', 'customer_1')
681 customer_3 -15.324468268076131
resNode: customer_1 deliver_cap: 49.93917275018195 cap_limit: 40
2302 customer_3 ('customer_3', 'depot_t')
681 customer_3 -15.324468268076131
resNode: depot_t deliver_cap: 35.786389940808064 cap_limit: 40
2303 customer_3 ('customer_3', 'customer_2')
681 customer_3 -15.324468268076131
resNode: customer_2 deliver_cap: 39.93620441609261 cap_limit: 40
2304 customer_3 ('customer_3', 'customer_4')
681 customer_3 -15.324468268076131
resNode: customer_4 deliver_cap: 50.50191500070869 cap_limit: 40
2305 customer_3 ('customer_3', 'customer_5')
681 customer_3 -15.324468268076131
resNode: customer_5 deliver_cap: 46.01107278103895 cap_limit: 40
2306 customer_1 ('customer_1', 'customer_3')
682 customer_1 -10.144723521093937
resNode: customer_3 deliver_cap: 48.34552898495512 cap_limit: 40
2307 customer_1 ('customer_1', 'depot_t')
682 customer_1 -10.144723521093937
resNode: depot_t deliver_cap: 27.465431100671804 cap_limit: 40
2308 customer_1 ('customer_1', 'customer_2')
682 customer_1 -10.144723521093937
resNode: customer_2 deliver_cap: 29.96228847346015 cap_limit: 40
2309 customer_1 ('customer_1', 'customer_4')
682 customer_1 -10.144723521093937
resNode: customer_4 deliver_cap: 47.88318270770053 cap_limit: 40
2310 customer_1 ('customer_1', 'customer_5')
682 customer_1 -10.144723521093937
resNode: customer_5 deliver_cap: 37.639796420405226 cap_limit: 40
2311 customer_4 ('customer_4', 'customer_3')
684 customer_4 -15.297843228562321
resNode: customer_3 deliver_cap: 50.50191500070869 cap_limit: 40
2312 customer_4 ('customer_4', 'customer_1')
684 customer_4 -15.297843228562321
resNode: customer_1 deliver_cap: 49.47682647292736 cap_limit: 40
2313 customer_4 ('customer_4', 'depot_t')
684 customer_4 -15.297843228562321
resNode: depot_t deliver_cap: 35.61435122394961 cap_limit: 40
2314 customer_4 ('customer_4', 'customer_2')
684 customer_4 -15.297843228562321
resNode: customer_2 deliver_cap: 39.75187721945855 cap_limit: 40
2315 customer_4 ('customer_4', 'customer_5')
684 customer_4 -15.297843228562321
resNode: customer_5 deliver_cap: 45.78988014507807 cap_limit: 40
2316 customer_5 ('customer_5', 'customer_3')
685 customer_5 -13.367821911797197
resNode: customer_3 deliver_cap: 46.01107278103895 cap_limit: 40
2317 customer_5 ('customer_5', 'customer_1')
685 customer_5 -13.367821911797197
resNode: customer_1 deliver_cap: 39.233440185632055 cap_limit: 40
2318 customer_5 ('customer_5', 'depot_t')
685 customer_5 -13.367821911797197
resNode: depot_t deliver_cap: 22.57178628913237 cap_limit: 40
2319 customer_5 ('customer_5', 'customer_2')
685 customer_5 -13.367821911797197
resNode: customer_2 deliver_cap: 25.77770050358294 cap_limit: 40
2320 customer_5 ('customer_5', 'customer_4')
685 customer_5 -13.367821911797197
resNode: customer_4 deliver_cap: 45.78988014507807 cap_limit: 40
2321 customer_2 ('customer_2', 'customer_3')
689 customer_2 -15.16957481892824
resNode: customer_3 deliver_cap: 62.780084840089685 cap_limit: 40
2322 customer_2 ('customer_2', 'customer_1')
689 customer_2 -15.16957481892824
resNode: customer_1 deliver_cap: 51.427037307700814 cap_limit: 40
2323 customer_2 ('customer_2', 'depot_t')
689 customer_2 -15.16957481892824
resNode: depot_t deliver_cap: 34.429188653347715 cap_limit: 40
2324 customer_2 ('customer_2', 'customer_4')
689 customer_2 -15.16957481892824
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
2325 customer_2 ('customer_2', 'customer_5')
689 customer_2 -15.16957481892824
resNode: customer_5 deliver_cap: 45.78988014507807 cap_limit: 40
2326 customer_2 ('customer_2', 'customer_3')
693 customer_2 -7.951413287158076
resNode: customer_3 deliver_cap: 63.7813588910576 cap_limit: 40
2327 customer_2 ('customer_2', 'customer_1')
693 customer_2 -7.951413287158076
resNode: customer_1 deliver_cap: 52.261432350174076 cap_limit: 40
2328 customer_2 ('customer_2', 'depot_t')
693 customer_2 -7.951413287158076
resNode: depot_t deliver_cap: 35.20795735965609 cap_limit: 40
2329 customer_2 ('customer_2', 'customer_4')
693 customer_2 -7.951413287158076
resNode: customer_4 deliver_cap: 63.56016625509674 cap_limit: 40
2330 customer_2 ('customer_2', 'customer_5')
693 customer_2 -7.951413287158076
resNode: customer_5 deliver_cap: 46.79115419604599 cap_limit: 40
2331 customer_1 ('customer_1', 'customer_3')
697 customer_1 -8.645244499345225
resNode: customer_3 deliver_cap: 63.7813588910576 cap_limit: 40
2332 customer_1 ('customer_1', 'depot_t')
697 customer_1 -8.645244499345225
resNode: depot_t deliver_cap: 39.44123308167908 cap_limit: 40
2333 customer_1 ('customer_1', 'customer_2')
697 customer_1 -8.645244499345225
resNode: customer_2 deliver_cap: 42.25846401608473 cap_limit: 40
2334 customer_1 ('customer_1', 'customer_4')
697 customer_1 -8.645244499345225
resNode: customer_4 deliver_cap: 63.22654335835208 cap_limit: 40
2335 customer_1 ('customer_1', 'customer_5')
697 customer_1 -8.645244499345225
resNode: customer_5 deliver_cap: 50.93447981359772 cap_limit: 40
2336 customer_5 ('customer_5', 'customer_3')
700 customer_5 -12.406303553439919
resNode: customer_3 deliver_cap: 60.40742970517545 cap_limit: 40
2337 customer_5 ('customer_5', 'customer_1')
700 customer_5 -12.406303553439919
resNode: customer_1 deliver_cap: 52.84685233186992 cap_limit: 40
2338 customer_5 ('customer_5', 'depot_t')
700 customer_5 -12.406303553439919
resNode: depot_t deliver_cap: 32.85494818429774 cap_limit: 40
2339 customer_5 ('customer_5', 'customer_2')
700 customer_5 -12.406303553439919
resNode: customer_2 deliver_cap: 36.69996471341097 cap_limit: 40
2340 customer_5 ('customer_5', 'customer_4')
700 customer_5 -12.406303553439919
resNode: customer_4 deliver_cap: 60.14937162988778 cap_limit: 40
2341 customer_2 ('customer_2', 'customer_3')
704 customer_2 -8.533659388019645
resNode: customer_3 deliver_cap: 65.6467456281235 cap_limit: 40
2342 customer_2 ('customer_2', 'customer_1')
704 customer_2 -8.533659388019645
resNode: customer_1 deliver_cap: 55.20099903897143 cap_limit: 40
2343 customer_2 ('customer_2', 'depot_t')
704 customer_2 -8.533659388019645
resNode: depot_t deliver_cap: 35.65717319095337 cap_limit: 40
2344 customer_2 ('customer_2', 'customer_4')
704 customer_2 -8.533659388019645
resNode: customer_4 deliver_cap: 65.38868755283582 cap_limit: 40
2345 customer_2 ('customer_2', 'customer_5')
704 customer_2 -8.533659388019645
resNode: customer_5 deliver_cap: 45.82484015060995 cap_limit: 40
2346 customer_5 ('customer_5', 'customer_3')
705 customer_5 -14.62387874746607
resNode: customer_3 deliver_cap: 70.44331485817496 cap_limit: 40
2347 customer_5 ('customer_5', 'customer_1')
705 customer_5 -14.62387874746607
resNode: customer_1 deliver_cap: 62.88513184957587 cap_limit: 40
2348 customer_5 ('customer_5', 'depot_t')
705 customer_5 -14.62387874746607
resNode: depot_t deliver_cap: 39.8247571651329 cap_limit: 40
2349 customer_5 ('customer_5', 'customer_2')
705 customer_5 -14.62387874746607
resNode: customer_2 deliver_cap: 44.0470962947071 cap_limit: 40
2350 customer_5 ('customer_5', 'customer_4')
705 customer_5 -14.62387874746607
resNode: customer_4 deliver_cap: 70.14839134356048 cap_limit: 40
2351 customer_2 ('customer_2', 'customer_3')
709 customer_2 -11.28293251075093
resNode: customer_3 deliver_cap: 60.40742970517546 cap_limit: 40
2352 customer_2 ('customer_2', 'customer_1')
709 customer_2 -11.28293251075093
resNode: customer_1 deliver_cap: 50.71015681930168 cap_limit: 40
2353 customer_2 ('customer_2', 'depot_t')
709 customer_2 -11.28293251075093
resNode: depot_t deliver_cap: 31.41582220570972 cap_limit: 40
2354 customer_2 ('customer_2', 'customer_4')
709 customer_2 -11.28293251075093

resNode: customer_2 deliver_cap: 38.436111574973495 cap_limit: 40
2424 customer_1 ('customer_1', 'customer_4')
797 customer_1 -12.318972468869482
resNode: customer_4 deliver_cap: 58.47546158459222 cap_limit: 40
2425 customer_1 ('customer_1', 'customer_5')
797 customer_1 -12.318972468869482
resNode: customer_5 deliver_cap: 48.232075297296916 cap_limit: 40
2426 customer_5 ('customer_5', 'customer_3')
800 customer_5 -18.190140578795663
resNode: customer_3 deliver_cap: 58.72180743330896 cap_limit: 40
2427 customer_5 ('customer_5', 'customer_1')
800 customer_5 -18.190140578795663
resNode: customer_1 deliver_cap: 49.82571906252373 cap_limit: 40
2428 customer_5 ('customer_5', 'depot_t')
800 customer_5 -18.190140578795663
resNode: depot_t deliver_cap: 32.45791324089794 cap_limit: 40
2429 customer_5 ('customer_5', 'customer_2')
800 customer_5 -18.190140578795663
resNode: customer_2 deliver_cap: 36.36997938047461 cap_limit: 40
2430 customer_5 ('customer_5', 'customer_4')
800 customer_5 -18.190140578795663
resNode: customer_4 deliver_cap: 58.500614797348085 cap_limit: 40
2431 customer_2 ('customer_2', 'customer_3')
809 customer_2 -18.13925549126043
resNode: customer_3 deliver_cap: 60.8585029458772 cap_limit: 40
2432 customer_2 ('customer_2', 'customer_1')
809 customer_2 -18.13925549126043
resNode: customer_1 deliver_cap: 49.82571906252374 cap_limit: 40
2433 customer_2 ('customer_2', 'depot_t')
809 customer_2 -18.13925549126043
resNode: depot_t deliver_cap: 32.93462495784911 cap_limit: 40
2434 customer_2 ('customer_2', 'customer_4')
809 customer_2 -18.13925549126043
resNode: customer_4 deliver_cap: 60.63731030991633 cap_limit: 40
2435 customer_2 ('customer_2', 'customer_5')
809 customer_2 -18.13925549126043
resNode: customer_5 deliver_cap: 43.868298250865585 cap_limit: 40
2436 customer_2 ('customer_2', 'customer_3')
813 customer_2 -14.444898790175667
resNode: customer_3 deliver_cap: 63.001277476050554 cap_limit: 40
2437 customer_2 ('customer_2', 'customer_1')
813 customer_2 -14.444898790175667
resNode: customer_1 deliver_cap: 51.611364504334865 cap_limit: 40
2438 customer_2 ('customer_2', 'depot_t')
813 customer_2 -14.444898790175667
resNode: depot_t deliver_cap: 34.60122737020616 cap_limit: 40
2439 customer_2 ('customer_2', 'customer_4')
813 customer_2 -14.444898790175667
resNode: customer_4 deliver_cap: 62.780084840089685 cap_limit: 40
2440 customer_2 ('customer_2', 'customer_5')
813 customer_2 -14.444898790175667
resNode: customer_5 deliver_cap: 46.01107278103893 cap_limit: 40
2441 customer_2 ('customer_2', 'customer_3')
818 customer_2 -9.44361277764541
resNode: customer_3 deliver_cap: 50.017720739108036 cap_limit: 40
2442 customer_2 ('customer_2', 'customer_1')
818 customer_2 -9.44361277764541
resNode: customer_1 deliver_cap: 39.302416544053955 cap_limit: 40
2443 customer_2 ('customer_2', 'depot_t')
818 customer_2 -9.44361277764541
resNode: depot_t deliver_cap: 25.36555984355635 cap_limit: 40
2444 customer_2 ('customer_2', 'customer_4')
818 customer_2 -9.44361277764541
resNode: customer_4 deliver_cap: 49.83339354247398 cap_limit: 40
2445 customer_2 ('customer_2', 'customer_5')
818 customer_2 -9.44361277764541
resNode: customer_5 deliver_cap: 35.859216826598356 cap_limit: 40
2446 customer_5 ('customer_5', 'customer_3')
820 customer_5 -17.36528334741576
resNode: customer_3 deliver_cap: 58.72180743330897 cap_limit: 40
2447 customer_5 ('customer_5', 'customer_1')
820 customer_5 -17.36528334741576
resNode: customer_1 deliver_cap: 49.825719062523746 cap_limit: 40
2448 customer_5 ('customer_5', 'depot_t')
820 customer_5 -17.36528334741576
resNode: depot_t deliver_cap: 32.45791324089794 cap_limit: 40
2449 customer_5 ('customer_5', 'customer_2')
820 customer_5 -17.36528334741576
resNode: customer_2 deliver_cap: 36.36997938047462 cap_limit: 40
2450 customer_5 ('customer_5', 'customer_4')
820 customer_5 -17.36528334741576
resNode: customer_4 deliver_cap: 58.500614797348106 cap_limit: 40
2451 customer_2 ('customer_2', 'customer_3')
824 customer_2 -14.405985270886259
resNode: customer_3 deliver_cap: 62.780084840089685 cap_limit: 40
2452 customer_2 ('customer_2', 'customer_1')
824 customer_2 -14.405985270886259
resNode: customer_1 deliver_cap: 51.427037307700814 cap_limit: 40
2453 customer_2 ('customer_2', 'depot_t')
824 customer_2 -14.405985270886259
resNode: depot_t deliver_cap: 34.429188653347715 cap_limit: 40
2454 customer_2 ('customer_2', 'customer_4')
824 customer_2 -14.405985270886259
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
2455 customer_2 ('customer_2', 'customer_5')
824 customer_2 -14.405985270886259
resNode: customer_5 deliver_cap: 45.78988014507807 cap_limit: 40
2456 customer_1 ('customer_1', 'customer_3')
827 customer_1 -14.267641617009383
resNode: customer_3 deliver_cap: 56.71517732832547 cap_limit: 40
2457 customer_1 ('customer_1', 'depot_t')
827 customer_1 -14.267641617009383
resNode: depot_t deliver_cap: 33.945314088442984 cap_limit: 40
2458 customer_1 ('customer_1', 'customer_2')
827 customer_1 -14.267641617009383
resNode: customer_2 deliver_cap: 36.36997938047462 cap_limit: 40
2459 customer_1 ('customer_1', 'customer_4')
827 customer_1 -14.267641617009383
resNode: customer_4 deliver_cap: 56.16036179561995 cap_limit: 40
2460 customer_1 ('customer_1', 'customer_5')
827 customer_1 -14.267641617009383
resNode: customer_5 deliver_cap: 43.86829825086559 cap_limit: 40
2461 customer_2 ('customer_2', 'customer_3')
829 customer_2 -11.544352173062757
resNode: customer_3 deliver_cap: 46.01107278103895 cap_limit: 40
2462 customer_2 ('customer_2', 'customer_1')
829 customer_2 -11.544352173062757
resNode: customer_1 deliver_cap: 37.452860591825186 cap_limit: 40
2463 customer_2 ('customer_2', 'depot_t')
829 customer_2 -11.544352173062757
resNode: depot_t deliver_cap: 21.38662371853047 cap_limit: 40
2464 customer_2 ('customer_2', 'customer_4')
829 customer_2 -11.544352173062757
resNode: customer_4 deliver_cap: 45.78988014507807 cap_limit: 40
2465 customer_2 ('customer_2', 'customer_5')
829 customer_2 -11.544352173062757
resNode: customer_5 deliver_cap: 29.020868086027335 cap_limit: 40
2466 customer_2 ('customer_2', 'customer_3')
849 customer_2 -20.977089202727573
resNode: customer_3 deliver_cap: 69.23458718621755 cap_limit: 40
2467 customer_2 ('customer_2', 'customer_1')
849 customer_2 -20.977089202727573
resNode: customer_1 deliver_cap: 58.27629180305205 cap_limit: 40
2468 customer_2 ('customer_2', 'depot_t')
849 customer_2 -20.977089202727573
resNode: depot_t deliver_cap: 38.5616163570295 cap_limit: 40
2469 customer_2 ('customer_2', 'customer_4')
849 customer_2 -20.977089202727573
resNode: customer_4 deliver_cap: 68.97652911092986 cap_limit: 40
2470 customer_2 ('customer_2', 'customer_5')
849 customer_2 -20.977089202727573
resNode: customer_5 deliver_cap: 49.412681708704 cap_limit: 40
2471 customer_2 ('customer_2', 'customer_3')
853 customer_2 -20.487811191277302
resNode: customer_3 deliver_cap: 69.56499243747062 cap_limit: 40
2472 customer_2 ('customer_2', 'customer_1')
853 customer_2 -20.487811191277302
resNode: customer_1 deliver_cap: 54.94023390274402 cap_limit: 40
2473 customer_2 ('customer_2', 'depot_t')
853 customer_2 -20.487811191277302
resNode: depot_t deliver_cap: 39.70022575568891 cap_limit: 40
2474 customer_2 ('customer_2', 'customer_4')
853 customer_2 -20.487811191277302
resNode: customer_4 deliver_cap: 69.38066524083655 cap_limit: 40
2475 customer_2 ('customer_2', 'customer_5')
853 customer_2 -20.487811191277302
resNode: customer_5 deliver_cap: 55.406488524960935 cap_limit: 40
2476 customer_1 ('customer_1', 'customer_3')
857 customer_1 -11.584976357692742
resNode: customer_3 deliver_cap: 53.66531889056256 cap_limit: 40
2477 customer_1 ('customer_1', 'depot_t')
857 customer_1 -11.584976357692742
resNode: depot_t deliver_cap: 29.967456117372407 cap_limit: 40
2478 customer_1 ('customer_1', 'customer_2')
857 customer_1 -11.584976357692742
resNode: customer_2 deliver_cap: 33.71338813204396 cap_limit: 40
2479 customer_1 ('customer_1', 'customer_4')
857 customer_1 -11.584976357692742
resNode: customer_4 deliver_cap: 53.295441868758886 cap_limit: 40
2480 customer_1 ('customer_1', 'customer_5')
857 customer_1 -11.584976357692742
resNode: customer_5 deliver_cap: 45.100732838922646 cap_limit: 40
2481 customer_5 ('customer_5', 'customer_3')
860 customer_5 -20.155544848131477
resNode: customer_3 deliver_cap: 57.078680279113854 cap_limit: 40
2482 customer_5 ('customer_5', 'customer_1')
860 customer_5 -20.155544848131477
resNode: customer_1 deliver_cap: 46.3756478511041 cap_limit: 40
2483 customer_5 ('customer_5', 'depot_t')
860 customer_5 -20.155544848131477
resNode: depot_t deliver_cap: 31.474796002176397 cap_limit: 40
2484 customer_5 ('customer_5', 'customer_2')
860 customer_5 -20.155544848131477
resNode: customer_2 deliver_cap: 35.6110561054648 cap_limit: 40
2485 customer_5 ('customer_5', 'customer_4')
860 customer_5 -20.155544848131477
resNode: customer_4 deliver_cap: 56.894353082479796 cap_limit: 40
2486 customer_2 ('customer_2', 'customer_3')
864 customer_2 -20.31447084016565
resNode: customer_3 deliver_cap: 69.10264616021603 cap_limit: 40
2487 customer_2 ('customer_2', 'customer_1')
864 customer_2 -20.31447084016565
resNode: customer_1 deliver_cap: 54.570356880940345 cap_limit: 40
2488 customer_2 ('customer_2', 'depot_t')
864 customer_2 -20.31447084016565
resNode: depot_t deliver_cap: 39.36117181903554 cap_limit: 40
2489 customer_2 ('customer_2', 'customer_4')
864 customer_2 -20.31447084016565
resNode: customer_4 deliver_cap: 68.91831896358197 cap_limit: 40
2490 customer_2 ('customer_2', 'customer_5')
864 customer_2 -20.31447084016565
resNode: customer_5 deliver_cap: 54.944142247706345 cap_limit: 40
2491 customer_2 ('customer_2', 'customer_3')
869 customer_2 -20.079121632902428
resNode: customer_3 deliver_cap: 58.859259872920724 cap_limit: 40
2492 customer_2 ('customer_2', 'customer_1')
869 customer_2 -20.079121632902428
resNode: customer_1 deliver_cap: 46.375647851104105 cap_limit: 40
2493 customer_2 ('customer_2', 'depot_t')
869 customer_2 -20.079121632902428
resNode: depot_t deliver_cap: 31.84935520835232 cap_limit: 40
2494 customer_2 ('customer_2', 'customer_4')
869 customer_2 -20.079121632902428
resNode: customer_4 deliver_cap: 58.674932676286666 cap_limit: 40
2495 customer_2 ('customer_2', 'customer_5')
869 customer_2 -20.079121632902428
resNode: customer_5 deliver_cap: 44.700755960411044 cap_limit: 40
2496 customer_2 ('customer_2', 'customer_3')
873 customer_2 -18.30959927937031
resNode: customer_3 deliver_cap: 64.09767666269163 cap_limit: 40
2497 customer_2 ('customer_2', 'customer_1')
873 customer_2 -18.30959927937031
resNode: customer_1 deliver_cap: 50.56638128292082 cap_limit: 40
2498 customer_2 ('customer_2', 'depot_t')
873 customer_2 -18.30959927937031
resNode: depot_t deliver_cap: 35.690860854184315 cap_limit: 40
2499 customer_2 ('customer_2', 'customer_4')
873 customer_2 -18.30959927937031
resNode: customer_4 deliver_cap: 63.91334946605756 cap_limit: 40
2500 customer_2 ('customer_2', 'customer_5')
873 customer_2 -18.30959927937031
resNode: customer_5 deliver_cap: 49.93917275018194 cap_limit: 40
2501 customer_2 ('customer_2', 'customer_3')
878 customer_2 -10.533327433224386
resNode: customer_3 deliver_cap: 49.29146627073936 cap_limit: 40
2502 customer_2 ('customer_2', 'customer_1')
878 customer_2 -10.533327433224386
resNode: customer_1 deliver_cap: 36.43477966763017 cap_limit: 40
2503 customer_2 ('customer_2', 'depot_t')
878 customer_2 -10.533327433224386
resNode: depot_t deliver_cap: 24.632539672524757 cap_limit: 40
2504 customer_2 ('customer_2', 'customer_4')
878 customer_2 -10.533327433224386
resNode: customer_4 deliver_cap: 49.144004513432115 cap_limit: 40
2505 customer_2 ('customer_2', 'customer_5')
878 customer_2 -10.533327433224386
resNode: customer_5 deliver_cap: 37.964663140731616 cap_limit: 40
2506 customer_5 ('customer_5', 'customer_3')
880 customer_5 -21.34480423639478
resNode: customer_3 deliver_cap: 60.53145162707365 cap_limit: 40
2507 customer_5 ('customer_5', 'customer_1')
880 customer_5 -21.34480423639478
resNode: customer_1 deliver_cap: 49.13786492947193 cap_limit: 40
2508 customer_5 ('customer_5', 'depot_t')
880 customer_5 -21.34480423639478
resNode: depot_t deliver_cap: 34.00682832401357 cap_limit: 40
2509 customer_5 ('customer_5', 'customer_2')
880 customer_5 -21.34480423639478
resNode: customer_2 deliver_cap: 38.37327318383263 cap_limit: 40
2510 customer_5 ('customer_5', 'customer_4')
880 customer_5 -21.34480423639478
resNode: customer_4 deliver_cap: 60.347124430439585 cap_limit: 40
2511 customer_2 ('customer_2', 'customer_3')
884 customer_2 -18.279902119912602
resNode: customer_3 deliver_cap: 63.91334946605756 cap_limit: 40
2512 customer_2 ('customer_2', 'customer_1')
884 customer_2 -18.279902119912602
resNode: customer_1 deliver_cap: 50.418919525613575 cap_limit: 40
2513 customer_2 ('customer_2', 'depot_t')
884 customer_2 -18.279902119912602
resNode: depot_t deliver_cap: 35.55568757665267 cap_limit: 40
2514 customer_2 ('customer_2', 'customer_4')
884 customer_2 -18.279902119912602
resNode: customer_4 deliver_cap: 63.7290222694235 cap_limit: 40
2515 customer_2 ('customer_2', 'customer_5')
884 customer_2 -18.279902119912602
resNode: customer_5 deliver_cap: 49.75484555354788 cap_limit: 40
2516 customer_1 ('customer_1', 'customer_3')
887 customer_1 -18.16748031772705
resNode: customer_3 deliver_cap: 58.85925987292072 cap_limit: 40
2517 customer_1 ('customer_1', 'depot_t')
887 customer_1 -18.16748031772705
resNode: depot_t deliver_cap: 35.17550041851324 cap_limit: 40
2518 customer_1 ('customer_1', 'customer_2')
887 customer_1 -18.16748031772705
resNode: customer_2 deliver_cap: 38.37327318383262 cap_limit: 40
2519 customer_1 ('customer_1', 'customer_4')
887 customer_1 -18.16748031772705
resNode: customer_4 deliver_cap: 58.39691359566612 cap_limit: 40
2520 customer_1 ('customer_1', 'customer_5')
887 customer_1 -18.16748031772705
resNode: customer_5 deliver_cap: 48.15352730837082 cap_limit: 40
2521 customer_2 ('customer_2', 'customer_3')
889 customer_2 -16.116977857882883
resNode: customer_3 deliver_cap: 49.93917275018194 cap_limit: 40
2522 customer_2 ('customer_2', 'customer_1')
889 customer_2 -16.116977857882883
resNode: customer_1 deliver_cap: 39.23957815291308 cap_limit: 40
2523 customer_2 ('customer_2', 'depot_t')
889 customer_2 -16.116977857882883
resNode: depot_t deliver_cap: 25.30795798501055 cap_limit: 40
2524 customer_2 ('customer_2', 'customer_4')
889 customer_2 -16.116977857882883
resNode: customer_4 deliver_cap: 49.75484555354788 cap_limit: 40
2525 customer_2 ('customer_2', 'customer_5')
889 customer_2 -16.116977857882883
resNode: customer_5 deliver_cap: 35.780668837672266 cap_limit: 40
2526 customer_2 ('customer_2', 'customer_3')
893 customer_2 -16.469347254675927
resNode: customer_3 deliver_cap: 65.69373140932979 cap_limit: 40
2527 customer_2 ('customer_2', 'customer_1')
893 customer_2 -16.469347254675927
resNode: customer_1 deliver_cap: 53.8550761154009 cap_limit: 40
2528 customer_2 ('customer_2', 'depot_t')
893 customer_2 -16.469347254675927
resNode: depot_t deliver_cap: 36.695358207201124 cap_limit: 40
2529 customer_2 ('customer_2', 'customer_4')
893 customer_2 -16.469347254675927
resNode: customer_4 deliver_cap: 65.47253877336892 cap_limit: 40
2530 customer_2 ('customer_2', 'customer_5')
893 customer_2 -16.469347254675927
resNode: customer_5 deliver_cap: 48.70352671431817 cap_limit: 40
2531 customer_2 ('customer_2', 'customer_3')
898 customer_2 -13.529639171537555
resNode: customer_3 deliver_cap: 60.54302971488478 cap_limit: 40
2532 customer_2 ('customer_2', 'customer_1')
898 customer_2 -13.529639171537555
resNode: customer_1 deliver_cap: 47.72266372467534 cap_limit: 40
2533 customer_2 ('customer_2', 'depot_t')
898 customer_2 -13.529639171537555
resNode: depot_t deliver_cap: 33.08411975912596 cap_limit: 40
2534 customer_2 ('customer_2', 'customer_4')
898 customer_2 -13.529639171537555
resNode: customer_4 deliver_cap: 60.35870251825072 cap_limit: 40
2535 customer_2 ('customer_2', 'customer_5')
898 customer_2 -13.529639171537555
resNode: customer_5 deliver_cap: 46.384525802375094 cap_limit: 40
2536 customer_1 ('customer_1', 'customer_3')
902 customer_1 -14.084727131289023
resNode: customer_3 deliver_cap: 60.82104879550533 cap_limit: 40
2537 customer_1 ('customer_1', 'depot_t')
902 customer_1 -14.084727131289023
resNode: depot_t deliver_cap: 36.614145628408615 cap_limit: 40
2538 customer_1 ('customer_1', 'customer_2')
902 customer_1 -14.084727131289023
resNode: customer_2 deliver_cap: 39.94270432190031 cap_limit: 40
2539 customer_1 ('customer_1', 'customer_4')
902 customer_1 -14.084727131289023
resNode: customer_4 deliver_cap: 60.35870251825072 cap_limit: 40
2540 customer_1 ('customer_1', 'customer_5')
902 customer_1 -14.084727131289023
resNode: customer_5 deliver_cap: 50.115316230955415 cap_limit: 40
2541 customer_5 ('customer_5', 'customer_3')
905 customer_5 -20.426705474629834
resNode: customer_3 deliver_cap: 60.98169655369917 cap_limit: 40
2542 customer_5 ('customer_5', 'customer_1')
905 customer_5 -20.426705474629834
resNode: customer_1 deliver_cap: 51.70895999618225 cap_limit: 40
2543 customer_5 ('customer_5', 'depot_t')
905 customer_5 -20.426705474629834
resNode: depot_t deliver_cap: 34.21560477897921 cap_limit: 40
2544 customer_5 ('customer_5', 'customer_2')
905 customer_5 -20.426705474629834
resNode: customer_2 deliver_cap: 38.253220314133124 cap_limit: 40
2545 customer_5 ('customer_5', 'customer_4')
905 customer_5 -20.426705474629834
resNode: customer_4 deliver_cap: 60.760503917738305 cap_limit: 40
2546 customer_2 ('customer_2', 'customer_3')
909 customer_2 -19.366825283937374
resNode: customer_3 deliver_cap: 60.981696553699166 cap_limit: 40
2547 customer_2 ('customer_2', 'customer_1')
909 customer_2 -19.366825283937374
resNode: customer_1 deliver_cap: 49.928380402375375 cap_limit: 40
2548 customer_2 ('customer_2', 'depot_t')
909 customer_2 -19.366825283937374
resNode: depot_t deliver_cap: 33.03044220837731 cap_limit: 40
2549 customer_2 ('customer_2', 'customer_4')
909 customer_2 -19.366825283937374
resNode: customer_4 deliver_cap: 60.76050391773829 cap_limit: 40
2550 customer_2 ('customer_2', 'customer_5')
909 customer_2 -19.366825283937374
resNode: customer_5 deliver_cap: 43.991491858687546 cap_limit: 40
2551 customer_2 ('customer_2', 'customer_3')
918 customer_2 -17.585074880532325
resNode: customer_3 deliver_cap: 60.531451627073636 cap_limit: 40
2552 customer_2 ('customer_2', 'customer_1')
918 customer_2 -17.585074880532325
resNode: customer_1 deliver_cap: 47.71340125442643 cap_limit: 40
2553 customer_2 ('customer_2', 'depot_t')
918 customer_2 -17.585074880532325
resNode: depot_t deliver_cap: 33.07562916139779 cap_limit: 40
2554 customer_2 ('customer_2', 'customer_4')
918 customer_2 -17.585074880532325
resNode: customer_4 deliver_cap: 60.34712443043957 cap_limit: 40
2555 customer_2 ('customer_2', 'customer_5')
918 customer_2 -17.585074880532325
resNode: customer_5 deliver_cap: 46.372947714563956 cap_limit: 40
2556 customer_1 ('customer_1', 'customer_3')
922 customer_1 -16.958745871233354
resNode: customer_3 deliver_cap: 57.078680279113854 cap_limit: 40
2557 customer_1 ('customer_1', 'depot_t')
922 customer_1 -16.958745871233354
resNode: depot_t deliver_cap: 33.86974204972154 cap_limit: 40
2558 customer_1 ('customer_1', 'customer_2')
922 customer_1 -16.958745871233354
resNode: customer_2 deliver_cap: 36.948809508787136 cap_limit: 40
2559 customer_1 ('customer_1', 'customer_4')
922 customer_1 -16.958745871233354
resNode: customer_4 deliver_cap: 56.616334001859265 cap_limit: 40
2560 customer_1 ('customer_1', 'customer_5')
922 customer_1 -16.958745871233354
resNode: customer_5 deliver_cap: 46.37294771456396 cap_limit: 40
2561 customer_5 ('customer_5', 'customer_3')
925 customer_5 -22.3651320854763
resNode: customer_3 deliver_cap: 56.49085433402942 cap_limit: 40
2562 customer_5 ('customer_5', 'customer_1')
925 customer_5 -22.3651320854763

2632 customer_2 ('customer_2', 'customer_1')
953 customer_2 -12.745451383683399
resNode: customer_1 deliver_cap: 36.43477966763017 cap_limit: 40
2633 customer_2 ('customer_2', 'depot_t')
953 customer_2 -12.745451383683399
resNode: depot_t deliver_cap: 24.632539672524754 cap_limit: 40
2634 customer_2 ('customer_2', 'customer_4')
953 customer_2 -12.745451383683399
resNode: customer_4 deliver_cap: 49.144004513432115 cap_limit: 40
2635 customer_2 ('customer_2', 'customer_5')
953 customer_2 -12.745451383683399
resNode: customer_5 deliver_cap: 37.964663140731616 cap_limit: 40
2636 customer_4 ('customer_4', 'customer_3')
954 customer_4 -19.382666160844174
resNode: customer_3 deliver_cap: 52.26143235017407 cap_limit: 40
2637 customer_4 ('customer_4', 'customer_1')
954 customer_4 -19.382666160844174
resNode: customer_1 deliver_cap: 47.72266372467534 cap_limit: 40
2638 customer_4 ('customer_4', 'depot_t')
954 customer_4 -19.382666160844174
resNode: depot_t deliver_cap: 35.44547353390894 cap_limit: 40
2639 customer_4 ('customer_4', 'customer_2')
954 customer_4 -19.382666160844174
resNode: customer_2 deliver_cap: 39.9427043219003 cap_limit: 40
2640 customer_4 ('customer_4', 'customer_5')
954 customer_4 -19.382666160844174
resNode: customer_5 deliver_cap: 48.33473663714855 cap_limit: 40
2641 customer_5 ('customer_5', 'customer_3')
955 customer_5 -22.755667369640705
resNode: customer_3 deliver_cap: 58.750872033266766 cap_limit: 40
2642 customer_5 ('customer_5', 'customer_1')
955 customer_5 -22.755667369640705
resNode: customer_1 deliver_cap: 47.71340125442643 cap_limit: 40
2643 customer_5 ('customer_5', 'depot_t')
955 customer_5 -22.755667369640705
resNode: depot_t deliver_cap: 32.70106995522187 cap_limit: 40
2644 customer_5 ('customer_5', 'customer_2')
955 customer_5 -22.755667369640705
resNode: customer_2 deliver_cap: 36.94880950878713 cap_limit: 40
2645 customer_5 ('customer_5', 'customer_4')
955 customer_5 -22.755667369640705
resNode: customer_4 deliver_cap: 58.566544836632715 cap_limit: 40
2646 customer_3 ('customer_3', 'customer_1')
956 customer_3 -13.514805761486842
resNode: customer_1 deliver_cap: 36.43477966763017 cap_limit: 40
2647 customer_3 ('customer_3', 'depot_t')
956 customer_3 -13.514805761486842
resNode: depot_t deliver_cap: 26.2016110293693 cap_limit: 40
2648 customer_3 ('customer_3', 'customer_2')
956 customer_3 -13.514805761486842
resNode: customer_2 deliver_cap: 30.432998667176555 cap_limit: 40
2649 customer_3 ('customer_3', 'customer_4')
956 customer_3 -13.514805761486842
resNode: customer_4 deliver_cap: 42.29631135716712 cap_limit: 40
2650 customer_3 ('customer_3', 'customer_5')
956 customer_3 -13.514805761486842
resNode: customer_5 deliver_cap: 39.30241654405395 cap_limit: 40
2651 customer_1 ('customer_1', 'customer_3')
957 customer_1 -5.727666013108296
resNode: customer_3 deliver_cap: 35.47859340849407 cap_limit: 40
2652 customer_1 ('customer_1', 'depot_t')
957 customer_1 -5.727666013108296
resNode: depot_t deliver_cap: 16.079440207008947 cap_limit: 40
2653 customer_1 ('customer_1', 'customer_2')
957 customer_1 -5.727666013108296
resNode: customer_2 deliver_cap: 19.295328248410737 cap_limit: 40
2654 customer_1 ('customer_1', 'customer_4')
957 customer_1 -5.727666013108296
resNode: customer_4 deliver_cap: 35.20118564214131 cap_limit: 40
2655 customer_1 ('customer_1', 'customer_5')
957 customer_1 -5.727666013108296
resNode: customer_5 deliver_cap: 29.055153869764126 cap_limit: 40
2656 customer_4 ('customer_4', 'customer_3')
959 customer_4 -13.506613441636443
resNode: customer_3 deliver_cap: 42.29631135716712 cap_limit: 40
2657 customer_4 ('customer_4', 'customer_1')
959 customer_4 -13.506613441636443
resNode: customer_1 deliver_cap: 36.157371901277415 cap_limit: 40
2658 customer_4 ('customer_4', 'depot_t')
959 customer_4 -13.506613441636443
resNode: depot_t deliver_cap: 26.10330319116447 cap_limit: 40
2659 customer_4 ('customer_4', 'customer_2')
959 customer_4 -13.506613441636443
resNode: customer_2 deliver_cap: 30.322402349196125 cap_limit: 40
2660 customer_4 ('customer_4', 'customer_5')
959 customer_4 -13.506613441636443
resNode: customer_5 deliver_cap: 39.15495478674671 cap_limit: 40
2661 customer_5 ('customer_5', 'customer_3')
960 customer_5 -12.974009796458878
resNode: customer_3 deliver_cap: 39.30241654405395 cap_limit: 40
2662 customer_5 ('customer_5', 'customer_1')
960 customer_5 -12.974009796458878
resNode: customer_1 deliver_cap: 30.011340128900226 cap_limit: 40
2663 customer_5 ('customer_5', 'depot_t')
960 customer_5 -12.974009796458878
resNode: depot_t deliver_cap: 18.65040894269747 cap_limit: 40
2664 customer_5 ('customer_5', 'customer_2')
960 customer_5 -12.974009796458878
resNode: customer_2 deliver_cap: 21.93789631967075 cap_limit: 40
2665 customer_5 ('customer_5', 'customer_4')
960 customer_5 -12.974009796458878
resNode: customer_4 deliver_cap: 39.15495478674671 cap_limit: 40
2666 customer_3 ('customer_3', 'customer_1')
961 customer_3 -19.134265233963703
resNode: customer_1 deliver_cap: 47.72266372467534 cap_limit: 40
2667 customer_3 ('customer_3', 'depot_t')
961 customer_3 -19.134265233963703
resNode: depot_t deliver_cap: 35.2415928747872 cap_limit: 40
2668 customer_3 ('customer_3', 'customer_2')
961 customer_3 -19.134265233963703
resNode: customer_2 deliver_cap: 39.72028905740386 cap_limit: 40
2669 customer_3 ('customer_3', 'customer_4')
961 customer_3 -19.134265233963703
resNode: customer_4 deliver_cap: 51.799086072919465 cap_limit: 40
2670 customer_3 ('customer_3', 'customer_5')
961 customer_3 -19.134265233963703
resNode: customer_5 deliver_cap: 48.05671755652801 cap_limit: 40
2671 customer_1 ('customer_1', 'customer_3')
962 customer_1 -13.226785736460121
resNode: customer_3 deliver_cap: 53.07302660426245 cap_limit: 40
2672 customer_1 ('customer_1', 'depot_t')
962 customer_1 -13.226785736460121
resNode: depot_t deliver_cap: 29.57259459317233 cap_limit: 40
2673 customer_1 ('customer_1', 'customer_2')
962 customer_1 -13.226785736460121
resNode: customer_2 deliver_cap: 33.26916891731887 cap_limit: 40
2674 customer_1 ('customer_1', 'customer_4')
962 customer_1 -13.226785736460121
resNode: customer_4 deliver_cap: 52.703149582458764 cap_limit: 40
2675 customer_1 ('customer_1', 'customer_5')
962 customer_1 -13.226785736460121
resNode: customer_5 deliver_cap: 44.508440552622524 cap_limit: 40
2676 customer_2 ('customer_2', 'customer_3')
964 customer_2 -12.595228346434473
resNode: customer_3 deliver_cap: 48.921589248935675 cap_limit: 40
2677 customer_2 ('customer_2', 'customer_1')
964 customer_2 -12.595228346434473
resNode: customer_1 deliver_cap: 36.1573719012774 cap_limit: 40
2678 customer_2 ('customer_2', 'depot_t')
964 customer_2 -12.595228346434473
resNode: depot_t deliver_cap: 24.3859549913223 cap_limit: 40
2679 customer_2 ('customer_2', 'customer_4')
964 customer_2 -12.595228346434473
resNode: customer_4 deliver_cap: 48.774127491628434 cap_limit: 40
2680 customer_2 ('customer_2', 'customer_5')
964 customer_2 -12.595228346434473
resNode: customer_5 deliver_cap: 37.594786118927935 cap_limit: 40
2681 customer_5 ('customer_5', 'customer_3')
965 customer_5 -22.489857763078128
resNode: customer_3 deliver_cap: 58.28852575601217 cap_limit: 40
2682 customer_5 ('customer_5', 'customer_1')
965 customer_5 -22.489857763078128
resNode: customer_1 deliver_cap: 47.34352423262275 cap_limit: 40
2683 customer_5 ('customer_5', 'depot_t')
965 customer_5 -22.489857763078128
resNode: depot_t deliver_cap: 32.36201601856849 cap_limit: 40
2684 customer_5 ('customer_5', 'customer_2')
965 customer_5 -22.489857763078128
resNode: customer_2 deliver_cap: 36.57893248698345 cap_limit: 40
2685 customer_5 ('customer_5', 'customer_4')
965 customer_5 -22.489857763078128
resNode: customer_4 deliver_cap: 58.104198559378105 cap_limit: 40
2686 customer_3 ('customer_3', 'customer_1')
966 customer_3 -21.454552459009292
resNode: customer_1 deliver_cap: 47.71340125442643 cap_limit: 40
2687 customer_3 ('customer_3', 'depot_t')
966 customer_3 -21.454552459009292
resNode: depot_t deliver_cap: 35.23310227705903 cap_limit: 40
2688 customer_3 ('customer_3', 'customer_2')
966 customer_3 -21.454552459009292
resNode: customer_2 deliver_cap: 39.711026587154954 cap_limit: 40
2689 customer_3 ('customer_3', 'customer_4')
966 customer_3 -21.454552459009292
resNode: customer_4 deliver_cap: 51.78750798510833 cap_limit: 40
2690 customer_3 ('customer_3', 'customer_5')
966 customer_3 -21.454552459009292
resNode: customer_5 deliver_cap: 48.04513946871687 cap_limit: 40
2691 customer_1 ('customer_1', 'customer_3')
967 customer_1 -14.24976392927773
resNode: customer_3 deliver_cap: 47.862949917290464 cap_limit: 40
2692 customer_1 ('customer_1', 'depot_t')
967 customer_1 -14.24976392927773
resNode: depot_t deliver_cap: 26.099210135191008 cap_limit: 40
2693 customer_1 ('customer_1', 'customer_2')
967 customer_1 -14.24976392927773
resNode: customer_2 deliver_cap: 29.361611402089885 cap_limit: 40
2694 customer_1 ('customer_1', 'customer_4')
967 customer_1 -14.24976392927773
resNode: customer_4 deliver_cap: 47.49307289548679 cap_limit: 40
2695 customer_1 ('customer_1', 'customer_5')
967 customer_1 -14.24976392927773
resNode: customer_5 deliver_cap: 39.29836386565054 cap_limit: 40
2696 customer_2 ('customer_2', 'customer_3')
969 customer_2 -12.872048453536017
resNode: customer_3 deliver_cap: 40.726880219099435 cap_limit: 40
2697 customer_2 ('customer_2', 'customer_1')
969 customer_2 -12.872048453536017
resNode: customer_1 deliver_cap: 30.011340128900223 cap_limit: 40
2698 customer_2 ('customer_2', 'depot_t')
969 customer_2 -12.872048453536017
resNode: depot_t deliver_cap: 18.92281563809814 cap_limit: 40
2699 customer_2 ('customer_2', 'customer_4')
969 customer_2 -12.872048453536017
resNode: customer_4 deliver_cap: 40.579418461792194 cap_limit: 40
2700 customer_2 ('customer_2', 'customer_5')
969 customer_2 -12.872048453536017
resNode: customer_5 deliver_cap: 29.400077089091695 cap_limit: 40
2701 customer_4 ('customer_4', 'customer_3')
970 customer_4 -21.437143779327187
resNode: customer_3 deliver_cap: 51.78750798510833 cap_limit: 40
2702 customer_4 ('customer_4', 'customer_1')
970 customer_4 -21.437143779327187
resNode: customer_1 deliver_cap: 47.34352423262275 cap_limit: 40
2703 customer_4 ('customer_4', 'depot_t')
970 customer_4 -21.437143779327187
resNode: depot_t deliver_cap: 35.0979289995274 cap_limit: 40
2704 customer_4 ('customer_4', 'customer_2')
970 customer_4 -21.437143779327187
resNode: customer_2 deliver_cap: 39.56356482984771 cap_limit: 40
2705 customer_4 ('customer_4', 'customer_5')
970 customer_4 -21.437143779327187
resNode: customer_5 deliver_cap: 47.8608122720828 cap_limit: 40
2706 customer_1 ('customer_1', 'customer_3')
971 customer_1 -15.372675865502242
resNode: customer_3 deliver_cap: 60.82104879550531 cap_limit: 40
2707 customer_1 ('customer_1', 'depot_t')
971 customer_1 -15.372675865502242
resNode: depot_t deliver_cap: 36.61414562840861 cap_limit: 40
2708 customer_1 ('customer_1', 'customer_2')
971 customer_1 -15.372675865502242
resNode: customer_2 deliver_cap: 39.9427043219003 cap_limit: 40
2709 customer_1 ('customer_1', 'customer_4')
971 customer_1 -15.372675865502242
resNode: customer_4 deliver_cap: 60.35870251825072 cap_limit: 40
2710 customer_1 ('customer_1', 'customer_5')
971 customer_1 -15.372675865502242
resNode: customer_5 deliver_cap: 50.115316230955415 cap_limit: 40
2711 customer_2 ('customer_2', 'customer_3')
973 customer_2 -14.18536624264802
resNode: customer_3 deliver_cap: 55.353733020726324 cap_limit: 40
2712 customer_2 ('customer_2', 'customer_1')
973 customer_2 -14.18536624264802
resNode: customer_1 deliver_cap: 43.57122636934859 cap_limit: 40
2713 customer_2 ('customer_2', 'depot_t')
973 customer_2 -14.18536624264802
resNode: depot_t deliver_cap: 29.278635516743094 cap_limit: 40
2714 customer_2 ('customer_2', 'customer_4')
973 customer_2 -14.18536624264802
resNode: customer_4 deliver_cap: 55.16940582409227 cap_limit: 40
2715 customer_2 ('customer_2', 'customer_5')
973 customer_2 -14.18536624264802
resNode: customer_5 deliver_cap: 41.195229108216644 cap_limit: 40
2716 customer_4 ('customer_4', 'customer_3')
974 customer_4 -19.364867302942557
resNode: customer_3 deliver_cap: 55.20099903897143 cap_limit: 40
2717 customer_4 ('customer_4', 'customer_1')
974 customer_4 -19.364867302942557
resNode: customer_1 deliver_cap: 53.3927298381463 cap_limit: 40
2718 customer_4 ('customer_4', 'depot_t')
974 customer_4 -19.364867302942557
resNode: depot_t deliver_cap: 39.269194364820635 cap_limit: 40
2719 customer_4 ('customer_4', 'customer_2')
974 customer_4 -19.364867302942557
resNode: customer_2 deliver_cap: 43.6677805846775 cap_limit: 40
2720 customer_4 ('customer_4', 'customer_5')
974 customer_4 -19.364867302942557
resNode: customer_5 deliver_cap: 50.488964183340805 cap_limit: 40
2721 customer_5 ('customer_5', 'customer_3')
975 customer_5 -22.550750085919507
resNode: customer_3 deliver_cap: 62.98832665868267 cap_limit: 40
2722 customer_5 ('customer_5', 'customer_1')
975 customer_5 -22.550750085919507
resNode: customer_1 deliver_cap: 53.38115175033516 cap_limit: 40
2723 customer_5 ('customer_5', 'depot_t')
975 customer_5 -22.550750085919507
resNode: depot_t deliver_cap: 35.77631708285526 cap_limit: 40
2724 customer_5 ('customer_5', 'customer_2')
975 customer_5 -22.550750085919507
resNode: customer_2 deliver_cap: 39.925412068286036 cap_limit: 40
2725 customer_5 ('customer_5', 'customer_4')
975 customer_5 -22.550750085919507
resNode: customer_4 deliver_cap: 62.76713402272179 cap_limit: 40
2726 customer_2 ('customer_2', 'customer_3')
978 customer_2 -10.803506270916273
resNode: customer_3 deliver_cap: 48.92158924893569 cap_limit: 40
2727 customer_2 ('customer_2', 'customer_1')
978 customer_2 -10.803506270916273
resNode: customer_1 deliver_cap: 36.157371901277415 cap_limit: 40
2728 customer_2 ('customer_2', 'depot_t')
978 customer_2 -10.803506270916273
resNode: depot_t deliver_cap: 24.385954991322304 cap_limit: 40
2729 customer_2 ('customer_2', 'customer_4')
978 customer_2 -10.803506270916273
resNode: customer_4 deliver_cap: 48.77412749162844 cap_limit: 40
2730 customer_2 ('customer_2', 'customer_5')
978 customer_2 -10.803506270916273
resNode: customer_5 deliver_cap: 37.59478611892794 cap_limit: 40
2731 customer_5 ('customer_5', 'customer_3')
980 customer_5 -21.499396504773017
resNode: customer_3 deliver_cap: 60.06910534981904 cap_limit: 40
2732 customer_5 ('customer_5', 'customer_1')
980 customer_5 -21.499396504773017
resNode: customer_1 deliver_cap: 48.76798790766824 cap_limit: 40
2733 customer_5 ('customer_5', 'depot_t')
980 customer_5 -21.499396504773017
resNode: depot_t deliver_cap: 33.6677743873602 cap_limit: 40
2734 customer_5 ('customer_5', 'customer_2')
980 customer_5 -21.499396504773017
resNode: customer_2 deliver_cap: 38.00339616202894 cap_limit: 40
2735 customer_5 ('customer_5', 'customer_4')
980 customer_5 -21.499396504773017
resNode: customer_4 deliver_cap: 59.88477815318498 cap_limit: 40
2736 customer_3 ('customer_3', 'customer_1')
981 customer_3 -19.524289556910116
resNode: customer_1 deliver_cap: 50.418919525613575 cap_limit: 40
2737 customer_3 ('customer_3', 'depot_t')
981 customer_3 -19.524289556910116
resNode: depot_t deliver_cap: 37.71316069231392 cap_limit: 40
2738 customer_3 ('customer_3', 'customer_2')
981 customer_3 -19.524289556910116
resNode: customer_2 deliver_cap: 42.4165448583421 cap_limit: 40
2739 customer_3 ('customer_3', 'customer_4')
981 customer_3 -19.524289556910116
resNode: customer_4 deliver_cap: 55.16940582409226 cap_limit: 40
2740 customer_3 ('customer_3', 'customer_5')
981 customer_3 -19.524289556910116
resNode: customer_5 deliver_cap: 51.4270373077008 cap_limit: 40
2741 customer_1 ('customer_1', 'customer_3')
982 customer_1 -11.117910648671195
resNode: customer_3 deliver_cap: 49.144004513432115 cap_limit: 40
2742 customer_1 ('customer_1', 'depot_t')
982 customer_1 -11.117910648671195
resNode: depot_t deliver_cap: 26.953246532618778 cap_limit: 40
2743 customer_1 ('customer_1', 'customer_2')
982 customer_1 -11.117910648671195
resNode: customer_2 deliver_cap: 30.322402349196125 cap_limit: 40
2744 customer_1 ('customer_1', 'customer_4')
982 customer_1 -11.117910648671195
resNode: customer_4 deliver_cap: 48.77412749162844 cap_limit: 40
2745 customer_1 ('customer_1', 'customer_5')
982 customer_1 -11.117910648671195
resNode: customer_5 deliver_cap: 40.5794184617922 cap_limit: 40
2746 customer_4 ('customer_4', 'customer_3')
984 customer_4 -19.50688087722801
resNode: customer_3 deliver_cap: 55.16940582409226 cap_limit: 40
2747 customer_4 ('customer_4', 'customer_1')
984 customer_4 -19.50688087722801
resNode: customer_1 deliver_cap: 50.0490425038099 cap_limit: 40
2748 customer_4 ('customer_4', 'depot_t')
984 customer_4 -19.50688087722801
resNode: depot_t deliver_cap: 37.57798741478228 cap_limit: 40
2749 customer_4 ('customer_4', 'customer_2')
984 customer_4 -19.50688087722801
resNode: customer_2 deliver_cap: 42.26908310103485 cap_limit: 40
2750 customer_4 ('customer_4', 'customer_5')
984 customer_4 -19.50688087722801
resNode: customer_5 deliver_cap: 51.24271011106674 cap_limit: 40
2751 customer_5 ('customer_5', 'customer_3')
985 customer_5 -18.275568396256666
resNode: customer_3 deliver_cap: 51.4270373077008 cap_limit: 40
2752 customer_5 ('customer_5', 'customer_1')
985 customer_5 -18.275568396256666
resNode: customer_1 deliver_cap: 41.854333473973654 cap_limit: 40
2753 customer_5 ('customer_5', 'depot_t')
985 customer_5 -18.275568396256666
resNode: depot_t deliver_cap: 27.330257823140155 cap_limit: 40
2754 customer_5 ('customer_5', 'customer_2')
985 customer_5 -18.275568396256666
resNode: customer_2 deliver_cap: 31.089741728334356 cap_limit: 40
2755 customer_5 ('customer_5', 'customer_4')
985 customer_5 -18.275568396256666
resNode: customer_4 deliver_cap: 51.24271011106674 cap_limit: 40
2756 customer_1 ('customer_1', 'customer_3')
987 customer_1 -19.32968151740491
resNode: customer_3 deliver_cap: 60.34712443043957 cap_limit: 40
2757 customer_1 ('customer_1', 'depot_t')
987 customer_1 -19.32968151740491
resNode: depot_t deliver_cap: 36.26660109402707 cap_limit: 40
2758 customer_1 ('customer_1', 'customer_2')
987 customer_1 -19.32968151740491
resNode: customer_2 deliver_cap: 39.56356482984771 cap_limit: 40
2759 customer_1 ('customer_1', 'customer_4')
987 customer_1 -19.32968151740491
resNode: customer_4 deliver_cap: 59.88477815318498 cap_limit: 40
2760 customer_1 ('customer_1', 'customer_5')
987 customer_1 -19.32968151740491
resNode: customer_5 deliver_cap: 49.64139186588968 cap_limit: 40
2761 customer_2 ('customer_2', 'customer_3')
989 customer_2 -17.27917905756074
resNode: customer_3 deliver_cap: 51.4270373077008 cap_limit: 40
2762 customer_2 ('customer_2', 'customer_1')
989 customer_2 -17.27917905756074
resNode: customer_1 deliver_cap: 40.429869798928166 cap_limit: 40
2763 customer_2 ('customer_2', 'depot_t')
989 customer_2 -17.27917905756074
resNode: depot_t deliver_cap: 26.39905866052438 cap_limit: 40
2764 customer_2 ('customer_2', 'customer_4')
989 customer_2 -17.27917905756074
resNode: customer_4 deliver_cap: 51.24271011106674 cap_limit: 40
2765 customer_2 ('customer_2', 'customer_5')
989 customer_2 -17.27917905756074
resNode: customer_5 deliver_cap: 37.26853339519112 cap_limit: 40
2766 customer_1 ('customer_1', 'customer_3')
991 customer_1 -14.769738715639175
resNode: customer_3 deliver_cap: 57.078680279113854 cap_limit: 40
2767 customer_1 ('customer_1', 'depot_t')
991 customer_1 -14.769738715639175
resNode: depot_t deliver_cap: 33.86974204972154 cap_limit: 40
2768 customer_1 ('customer_1', 'customer_2')
991 customer_1 -14.769738715639175
resNode: customer_2 deliver_cap: 36.948809508787136 cap_limit: 40
2769 customer_1 ('customer_1', 'customer_4')
991 customer_1 -14.769738715639175
resNode: customer_4 deliver_cap: 56.616334001859265 cap_limit: 40
2770 customer_1 ('customer_1', 'customer_5')
991 customer_1 -14.769738715639175
resNode: customer_5 deliver_cap: 46.37294771456396 cap_limit: 40

1009 customer_2 -13.552731933327241
resNode: customer_5 deliver_cap: 37.26853339519112 cap_limit: 40
2841 customer_5 ('customer_5', 'customer_3')
1010 customer_5 -20.936441848342348
resNode: customer_3 deliver_cap: 58.27629180305205 cap_limit: 40
2842 customer_5 ('customer_5', 'customer_1')
1010 customer_5 -20.936441848342348
resNode: customer_1 deliver_cap: 49.45445603730964 cap_limit: 40
2843 customer_5 ('customer_5', 'depot_t')
1010 customer_5 -20.936441848342348
resNode: depot_t deliver_cap: 32.11140108403144 cap_limit: 40
2844 customer_5 ('customer_5', 'customer_2')
1010 customer_5 -20.936441848342348
resNode: customer_2 deliver_cap: 35.99871635526051 cap_limit: 40
2845 customer_5 ('customer_5', 'customer_4')
1010 customer_5 -20.936441848342348
resNode: customer_4 deliver_cap: 58.05509916709117 cap_limit: 40
2846 customer_2 ('customer_2', 'customer_3')
1013 customer_2 -13.332208409437518
resNode: customer_3 deliver_cap: 60.54302971488478 cap_limit: 40
2847 customer_2 ('customer_2', 'customer_1')
1013 customer_2 -13.332208409437518
resNode: customer_1 deliver_cap: 47.72266372467534 cap_limit: 40
2848 customer_2 ('customer_2', 'depot_t')
1013 customer_2 -13.332208409437518
resNode: depot_t deliver_cap: 33.08411975912596 cap_limit: 40
2849 customer_2 ('customer_2', 'customer_4')
1013 customer_2 -13.332208409437518
resNode: customer_4 deliver_cap: 60.35870251825072 cap_limit: 40
2850 customer_2 ('customer_2', 'customer_5')
1013 customer_2 -13.332208409437518
resNode: customer_5 deliver_cap: 46.384525802375094 cap_limit: 40
2851 customer_1 ('customer_1', 'customer_3')
1017 customer_1 -13.79925699365915
resNode: customer_3 deliver_cap: 60.54302971488478 cap_limit: 40
2852 customer_1 ('customer_1', 'depot_t')
1017 customer_1 -13.79925699365915
resNode: depot_t deliver_cap: 36.410264969286885 cap_limit: 40
2853 customer_1 ('customer_1', 'customer_2')
1017 customer_1 -13.79925699365915
resNode: customer_2 deliver_cap: 39.720289057403875 cap_limit: 40
2854 customer_1 ('customer_1', 'customer_4')
1017 customer_1 -13.79925699365915
resNode: customer_4 deliver_cap: 60.080683437630185 cap_limit: 40
2855 customer_1 ('customer_1', 'customer_5')
1017 customer_1 -13.79925699365915
resNode: customer_5 deliver_cap: 49.837297150334884 cap_limit: 40
2856 customer_5 ('customer_5', 'customer_3')
1020 customer_5 -20.07173056684482
resNode: customer_3 deliver_cap: 60.64807365695452 cap_limit: 40
2857 customer_5 ('customer_5', 'customer_1')
1020 customer_5 -20.07173056684482
resNode: customer_1 deliver_cap: 51.430940915561706 cap_limit: 40
2858 customer_5 ('customer_5', 'depot_t')
1020 customer_5 -20.07173056684482
resNode: depot_t deliver_cap: 33.95612030373337 cap_limit: 40
2859 customer_5 ('customer_5', 'customer_2')
1020 customer_5 -20.07173056684482
resNode: customer_2 deliver_cap: 37.97520123351258 cap_limit: 40
2860 customer_5 ('customer_5', 'customer_4')
1020 customer_5 -20.07173056684482
resNode: customer_4 deliver_cap: 60.42688102099365 cap_limit: 40
2861 customer_2 ('customer_2', 'customer_3')
1024 customer_2 -16.07545882760151
resNode: customer_3 deliver_cap: 65.13891587662427 cap_limit: 40
2862 customer_2 ('customer_2', 'customer_1')
1024 customer_2 -16.07545882760151
resNode: customer_1 deliver_cap: 53.3927298381463 cap_limit: 40
2863 customer_2 ('customer_2', 'depot_t')
1024 customer_2 -16.07545882760151
resNode: depot_t deliver_cap: 36.26383501509683 cap_limit: 40
2864 customer_2 ('customer_2', 'customer_4')
1024 customer_2 -16.07545882760151
resNode: customer_4 deliver_cap: 64.9177232406634 cap_limit: 40
2865 customer_2 ('customer_2', 'customer_5')
1024 customer_2 -16.07545882760151
resNode: customer_5 deliver_cap: 48.148711181612654 cap_limit: 40
2866 customer_2 ('customer_2', 'customer_3')
1029 customer_2 -19.01185037615236
resNode: customer_3 deliver_cap: 60.648073656954516 cap_limit: 40
2867 customer_2 ('customer_2', 'customer_1')
1029 customer_2 -19.01185037615236
resNode: customer_1 deliver_cap: 49.650361321754836 cap_limit: 40
2868 customer_2 ('customer_2', 'depot_t')
1029 customer_2 -19.01185037615236
resNode: depot_t deliver_cap: 32.77095773313147 cap_limit: 40
2869 customer_2 ('customer_2', 'customer_4')
1029 customer_2 -19.01185037615236
resNode: customer_4 deliver_cap: 60.42688102099365 cap_limit: 40
2870 customer_2 ('customer_2', 'customer_5')
1029 customer_2 -19.01185037615236
resNode: customer_5 deliver_cap: 43.6578689619429 cap_limit: 40
2871 customer_2 ('customer_2', 'customer_3')
1033 customer_2 -19.99817761738547
resNode: customer_3 deliver_cap: 68.82462707959547 cap_limit: 40
2872 customer_2 ('customer_2', 'customer_1')
1033 customer_2 -19.99817761738547
resNode: customer_1 deliver_cap: 54.347941616443904 cap_limit: 40
2873 customer_2 ('customer_2', 'depot_t')
1033 customer_2 -19.99817761738547
resNode: depot_t deliver_cap: 39.15729115991381 cap_limit: 40
2874 customer_2 ('customer_2', 'customer_4')
1033 customer_2 -19.99817761738547
resNode: customer_4 deliver_cap: 68.64029988296141 cap_limit: 40
2875 customer_2 ('customer_2', 'customer_5')
1033 customer_2 -19.99817761738547
resNode: customer_5 deliver_cap: 54.6661231670858 cap_limit: 40
2876 customer_1 ('customer_1', 'customer_3')
1037 customer_1 -11.280434123269691
resNode: customer_3 deliver_cap: 53.07302660426245 cap_limit: 40
2877 customer_1 ('customer_1', 'depot_t')
1037 customer_1 -11.280434123269691
resNode: depot_t deliver_cap: 29.572594593172333 cap_limit: 40
2878 customer_1 ('customer_1', 'customer_2')
1037 customer_1 -11.280434123269691
resNode: customer_2 deliver_cap: 33.26916891731887 cap_limit: 40
2879 customer_1 ('customer_1', 'customer_4')
1037 customer_1 -11.280434123269691
resNode: customer_4 deliver_cap: 52.70314958245878 cap_limit: 40
2880 customer_1 ('customer_1', 'customer_5')
1037 customer_1 -11.280434123269691
resNode: customer_5 deliver_cap: 44.50844055262253 cap_limit: 40
2881 customer_5 ('customer_5', 'customer_3')
1040 customer_5 -19.66591127423964
resNode: customer_3 deliver_cap: 56.33831492123872 cap_limit: 40
2882 customer_5 ('customer_5', 'customer_1')
1040 customer_5 -19.66591127423964
resNode: customer_1 deliver_cap: 45.78335556480398 cap_limit: 40
2883 customer_5 ('customer_5', 'depot_t')
1040 customer_5 -19.66591127423964
resNode: depot_t deliver_cap: 30.931861406401296 cap_limit: 40
2884 customer_5 ('customer_5', 'customer_2')
1040 customer_5 -19.66591127423964
resNode: customer_2 deliver_cap: 35.01876381916469 cap_limit: 40
2885 customer_5 ('customer_5', 'customer_4')
1040 customer_5 -19.66591127423964
resNode: customer_4 deliver_cap: 56.153987724604654 cap_limit: 40
2886 customer_2 ('customer_2', 'customer_3')
1044 customer_2 -19.82483726627381
resNode: customer_3 deliver_cap: 68.36228080234089 cap_limit: 40
2887 customer_2 ('customer_2', 'customer_1')
1044 customer_2 -19.82483726627381
resNode: customer_1 deliver_cap: 53.97806459464023 cap_limit: 40
2888 customer_2 ('customer_2', 'depot_t')
1044 customer_2 -19.82483726627381
resNode: depot_t deliver_cap: 38.81823722326044 cap_limit: 40
2889 customer_2 ('customer_2', 'customer_4')
1044 customer_2 -19.82483726627381
resNode: customer_4 deliver_cap: 68.17795360570682 cap_limit: 40
2890 customer_2 ('customer_2', 'customer_5')
1044 customer_2 -19.82483726627381
resNode: customer_5 deliver_cap: 54.203776889831204 cap_limit: 40
2891 customer_2 ('customer_2', 'customer_3')
1049 customer_2 -19.58948805901059
resNode: customer_3 deliver_cap: 58.11889451504558 cap_limit: 40
2892 customer_2 ('customer_2', 'customer_1')
1049 customer_2 -19.58948805901059
resNode: customer_1 deliver_cap: 45.78335556480399 cap_limit: 40
2893 customer_2 ('customer_2', 'depot_t')
1049 customer_2 -19.58948805901059
resNode: depot_t deliver_cap: 31.30642061257722 cap_limit: 40
2894 customer_2 ('customer_2', 'customer_4')
1049 customer_2 -19.58948805901059
resNode: customer_4 deliver_cap: 57.93456731841153 cap_limit: 40
2895 customer_2 ('customer_2', 'customer_5')
1049 customer_2 -19.58948805901059
resNode: customer_5 deliver_cap: 43.9603906025359 cap_limit: 40
2896 customer_2 ('customer_2', 'customer_3')
1053 customer_2 -17.982143502507128
resNode: customer_3 deliver_cap: 63.63533038543703 cap_limit: 40
2897 customer_2 ('customer_2', 'customer_1')
1053 customer_2 -17.982143502507128
resNode: customer_1 deliver_cap: 50.19650426111715 cap_limit: 40
2898 customer_2 ('customer_2', 'depot_t')
1053 customer_2 -17.982143502507128
resNode: depot_t deliver_cap: 35.35180691753094 cap_limit: 40
2899 customer_2 ('customer_2', 'customer_4')
1053 customer_2 -17.982143502507128
resNode: customer_4 deliver_cap: 63.45100318880297 cap_limit: 40
2900 customer_2 ('customer_2', 'customer_5')
1053 customer_2 -17.982143502507128
resNode: customer_5 deliver_cap: 49.47682647292735 cap_limit: 40
2901 customer_2 ('customer_2', 'customer_3')
1058 customer_2 -10.321458225674847
resNode: customer_3 deliver_cap: 48.92158924893569 cap_limit: 40
2902 customer_2 ('customer_2', 'customer_1')
1058 customer_2 -10.321458225674847
resNode: customer_1 deliver_cap: 36.157371901277415 cap_limit: 40
2903 customer_2 ('customer_2', 'depot_t')
1058 customer_2 -10.321458225674847
resNode: depot_t deliver_cap: 24.385954991322304 cap_limit: 40
2904 customer_2 ('customer_2', 'customer_4')
1058 customer_2 -10.321458225674847
resNode: customer_4 deliver_cap: 48.77412749162844 cap_limit: 40
2905 customer_2 ('customer_2', 'customer_5')
1058 customer_2 -10.321458225674847
resNode: customer_5 deliver_cap: 37.59478611892794 cap_limit: 40
2906 customer_5 ('customer_5', 'customer_3')
1060 customer_5 -21.01734845953159
resNode: customer_3 deliver_cap: 60.06910534981904 cap_limit: 40
2907 customer_5 ('customer_5', 'customer_1')
1060 customer_5 -21.01734845953159
resNode: customer_1 deliver_cap: 48.76798790766824 cap_limit: 40
2908 customer_5 ('customer_5', 'depot_t')
1060 customer_5 -21.01734845953159
resNode: depot_t deliver_cap: 33.6677743873602 cap_limit: 40
2909 customer_5 ('customer_5', 'customer_2')
1060 customer_5 -21.01734845953159
resNode: customer_2 deliver_cap: 38.00339616202894 cap_limit: 40
2910 customer_5 ('customer_5', 'customer_4')
1060 customer_5 -21.01734845953159
resNode: customer_4 deliver_cap: 59.88477815318498 cap_limit: 40
2911 customer_2 ('customer_2', 'customer_3')
1064 customer_2 -17.952446343049417
resNode: customer_3 deliver_cap: 63.45100318880297 cap_limit: 40
2912 customer_2 ('customer_2', 'customer_1')
1064 customer_2 -17.952446343049417
resNode: customer_1 deliver_cap: 50.0490425038099 cap_limit: 40
2913 customer_2 ('customer_2', 'depot_t')
1064 customer_2 -17.952446343049417
resNode: depot_t deliver_cap: 35.2166336399993 cap_limit: 40
2914 customer_2 ('customer_2', 'customer_4')
1064 customer_2 -17.952446343049417
resNode: customer_4 deliver_cap: 63.266675992168906 cap_limit: 40
2915 customer_2 ('customer_2', 'customer_5')
1064 customer_2 -17.952446343049417
resNode: customer_5 deliver_cap: 49.29249927629329 cap_limit: 40
2916 customer_1 ('customer_1', 'customer_3')
1067 customer_1 -17.840024540863865
resNode: customer_3 deliver_cap: 58.39691359566612 cap_limit: 40
2917 customer_1 ('customer_1', 'depot_t')
1067 customer_1 -17.840024540863865
resNode: depot_t deliver_cap: 34.836446481859866 cap_limit: 40
2918 customer_1 ('customer_1', 'customer_2')
1067 customer_1 -17.840024540863865
resNode: customer_2 deliver_cap: 38.00339616202895 cap_limit: 40
2919 customer_1 ('customer_1', 'customer_4')
1067 customer_1 -17.840024540863865
resNode: customer_4 deliver_cap: 57.93456731841153 cap_limit: 40
2920 customer_1 ('customer_1', 'customer_5')
1067 customer_1 -17.840024540863865
resNode: customer_5 deliver_cap: 47.69118103111623 cap_limit: 40
2921 customer_2 ('customer_2', 'customer_3')
1069 customer_2 -15.789522081019697
resNode: customer_3 deliver_cap: 49.47682647292735 cap_limit: 40
2922 customer_2 ('customer_2', 'customer_1')
1069 customer_2 -15.789522081019697
resNode: customer_1 deliver_cap: 38.86970113110941 cap_limit: 40
2923 customer_2 ('customer_2', 'depot_t')
1069 customer_2 -15.789522081019697
resNode: depot_t deliver_cap: 24.96890404835718 cap_limit: 40
2924 customer_2 ('customer_2', 'customer_4')
1069 customer_2 -15.789522081019697
resNode: customer_4 deliver_cap: 49.29249927629329 cap_limit: 40
2925 customer_2 ('customer_2', 'customer_5')
1069 customer_2 -15.789522081019697
resNode: customer_5 deliver_cap: 35.31832256041767 cap_limit: 40
2926 customer_2 ('customer_2', 'customer_3')
1078 customer_2 -17.257619103669136
resNode: customer_3 deliver_cap: 60.06910534981904 cap_limit: 40
2927 customer_2 ('customer_2', 'customer_1')
1078 customer_2 -17.257619103669136
resNode: customer_1 deliver_cap: 47.343524232622755 cap_limit: 40
2928 customer_2 ('customer_2', 'depot_t')
1078 customer_2 -17.257619103669136
resNode: depot_t deliver_cap: 32.73657522474442 cap_limit: 40
2929 customer_2 ('customer_2', 'customer_4')
1078 customer_2 -17.257619103669136
resNode: customer_4 deliver_cap: 59.88477815318498 cap_limit: 40
2930 customer_2 ('customer_2', 'customer_5')
1078 customer_2 -17.257619103669136
resNode: customer_5 deliver_cap: 45.91060143730936 cap_limit: 40
2931 customer_1 ('customer_1', 'customer_3')
1082 customer_1 -16.631290094370165
resNode: customer_3 deliver_cap: 56.61633400185926 cap_limit: 40
2932 customer_1 ('customer_1', 'depot_t')
1082 customer_1 -16.631290094370165
resNode: depot_t deliver_cap: 33.530688113068166 cap_limit: 40
2933 customer_1 ('customer_1', 'customer_2')
1082 customer_1 -16.631290094370165
resNode: customer_2 deliver_cap: 36.578932486983454 cap_limit: 40
2934 customer_1 ('customer_1', 'customer_4')
1082 customer_1 -16.631290094370165
resNode: customer_4 deliver_cap: 56.153987724604654 cap_limit: 40
2935 customer_1 ('customer_1', 'customer_5')
1082 customer_1 -16.631290094370165
resNode: customer_5 deliver_cap: 45.91060143730935 cap_limit: 40
2936 customer_5 ('customer_5', 'customer_3')
1085 customer_5 -21.92208973929946
resNode: customer_3 deliver_cap: 55.9360388013239 cap_limit: 40
2937 customer_5 ('customer_5', 'customer_1')
1085 customer_5 -21.92208973929946
resNode: customer_1 deliver_cap: 47.50424520253618 cap_limit: 40
2938 customer_5 ('customer_5', 'depot_t')
1085 customer_5 -21.92208973929946
resNode: depot_t deliver_cap: 30.291204304909556 cap_limit: 40
2939 customer_5 ('customer_5', 'customer_2')
1085 customer_5 -21.92208973929946
resNode: customer_2 deliver_cap: 34.04850552048706 cap_limit: 40
2940 customer_5 ('customer_5', 'customer_4')
1085 customer_5 -21.92208973929946
resNode: customer_4 deliver_cap: 55.71484616536303 cap_limit: 40
2941 customer_2 ('customer_2', 'customer_3')
1093 customer_2 -15.650951889441624
resNode: customer_3 deliver_cap: 60.531451627073636 cap_limit: 40
2942 customer_2 ('customer_2', 'customer_1')
1093 customer_2 -15.650951889441624
resNode: customer_1 deliver_cap: 47.71340125442643 cap_limit: 40
2943 customer_2 ('customer_2', 'depot_t')
1093 customer_2 -15.650951889441624
resNode: depot_t deliver_cap: 33.07562916139779 cap_limit: 40
2944 customer_2 ('customer_2', 'customer_4')
1093 customer_2 -15.650951889441624
resNode: customer_4 deliver_cap: 60.34712443043957 cap_limit: 40
2945 customer_2 ('customer_2', 'customer_5')
1093 customer_2 -15.650951889441624
resNode: customer_5 deliver_cap: 46.372947714563956 cap_limit: 40
2946 customer_1 ('customer_1', 'customer_3')
1097 customer_1 -16.11800047366325
resNode: customer_3 deliver_cap: 60.531451627073636 cap_limit: 40
2947 customer_1 ('customer_1', 'depot_t')
1097 customer_1 -16.11800047366325
resNode: depot_t deliver_cap: 36.40177437155871 cap_limit: 40
2948 customer_1 ('customer_1', 'customer_2')
1097 customer_1 -16.11800047366325
resNode: customer_2 deliver_cap: 39.71102658715496 cap_limit: 40
2949 customer_1 ('customer_1', 'customer_4')
1097 customer_1 -16.11800047366325
resNode: customer_4 deliver_cap: 60.06910534981904 cap_limit: 40
2950 customer_1 ('customer_1', 'customer_5')
1097 customer_1 -16.11800047366325
resNode: customer_5 deliver_cap: 49.82571906252374 cap_limit: 40
2951 customer_5 ('customer_5', 'customer_3')
1100 customer_5 -22.38757952489614
resNode: customer_3 deliver_cap: 60.634179951581146 cap_limit: 40
2952 customer_5 ('customer_5', 'customer_1')
1100 customer_5 -22.38757952489614
resNode: customer_1 deliver_cap: 51.419362827750554 cap_limit: 40
2953 customer_5 ('customer_5', 'depot_t')
1100 customer_5 -22.38757952489614
resNode: depot_t deliver_cap: 33.94531408844297 cap_limit: 40
2954 customer_5 ('customer_5', 'customer_2')
1100 customer_5 -22.38757952489614
resNode: customer_2 deliver_cap: 37.96362314570143 cap_limit: 40
2955 customer_5 ('customer_5', 'customer_4')
1100 customer_5 -22.38757952489614
resNode: customer_4 deliver_cap: 60.41298731562028 cap_limit: 40
2956 customer_2 ('customer_2', 'customer_3')
1104 customer_2 -18.391307785652828
resNode: customer_3 deliver_cap: 65.1250221712509 cap_limit: 40
2957 customer_2 ('customer_2', 'customer_1')
1104 customer_2 -18.391307785652828
resNode: customer_1 deliver_cap: 53.381151750335164 cap_limit: 40
2958 customer_2 ('customer_2', 'depot_t')
1104 customer_2 -18.391307785652828
resNode: depot_t deliver_cap: 36.25302879980644 cap_limit: 40
2959 customer_2 ('customer_2', 'customer_4')
1104 customer_2 -18.391307785652828
resNode: customer_4 deliver_cap: 64.90382953529004 cap_limit: 40
2960 customer_2 ('customer_2', 'customer_5')
1104 customer_2 -18.391307785652828
resNode: customer_5 deliver_cap: 48.13481747623929 cap_limit: 40
2961 customer_2 ('customer_2', 'customer_3')
1109 customer_2 -21.327699334203682
resNode: customer_3 deliver_cap: 60.634179951581146 cap_limit: 40
2962 customer_2 ('customer_2', 'customer_1')
1109 customer_2 -21.327699334203682
resNode: customer_1 deliver_cap: 49.6387832339437 cap_limit: 40
2963 customer_2 ('customer_2', 'depot_t')
1109 customer_2 -21.327699334203682
resNode: depot_t deliver_cap: 32.760151517841074 cap_limit: 40
2964 customer_2 ('customer_2', 'customer_4')
1109 customer_2 -21.327699334203682
resNode: customer_4 deliver_cap: 60.41298731562028 cap_limit: 40
2965 customer_2 ('customer_2', 'customer_5')
1109 customer_2 -21.327699334203682
resNode: customer_5 deliver_cap: 43.64397525656953 cap_limit: 40
2966 customer_2 ('customer_2', 'customer_3')
1113 customer_2 -18.524660731029
resNode: customer_3 deliver_cap: 62.312031220880506 cap_limit: 40
2967 customer_2 ('customer_2', 'customer_1')
1113 customer_2 -18.524660731029
resNode: customer_1 deliver_cap: 49.13786492947193 cap_limit: 40
2968 customer_2 ('customer_2', 'depot_t')
1113 customer_2 -18.524660731029
resNode: depot_t deliver_cap: 34.38138753018949 cap_limit: 40
2969 customer_2 ('customer_2', 'customer_4')
1113 customer_2 -18.524660731029
resNode: customer_4 deliver_cap: 62.12770402424645 cap_limit: 40
2970 customer_2 ('customer_2', 'customer_5')
1113 customer_2 -18.524660731029
resNode: customer_5 deliver_cap: 48.15352730837082 cap_limit: 40
2971 customer_3 ('customer_3', 'customer_1')
1116 customer_3 -19.441115548536622
resNode: customer_1 deliver_cap: 49.13786492947193 cap_limit: 40
2972 customer_3 ('customer_3', 'depot_t')
1116 customer_3 -19.441115548536622
resNode: depot_t deliver_cap: 36.53886064585074 cap_limit: 40
2973 customer_3 ('customer_3', 'customer_2')
1116 customer_3 -19.441115548536622
resNode: customer_2 deliver_cap: 41.13549026220045 cap_limit: 40
2974 customer_3 ('customer_3', 'customer_4')
1116 customer_3 -19.441115548536622
resNode: customer_4 deliver_cap: 53.568087578915204 cap_limit: 40
2975 customer_3 ('customer_3', 'customer_5')
1116 customer_3 -19.441115548536622
resNode: customer_5 deliver_cap: 49.82571906252374 cap_limit: 40
2976 customer_1 ('customer_1', 'customer_3')
1117 customer_1 -11.435066201591969
resNode: customer_3 deliver_cap: 47.862949917290464 cap_limit: 40
2977 customer_1 ('customer_1', 'depot_t')
1117 customer_1 -11.435066201591969
resNode: depot_t deliver_cap: 26.09921013519101 cap_limit: 40
2978 customer_1 ('customer_1', 'customer_2')
1117 customer_1 -11.435066201591969

resNode: customer_2 deliver_cap: 41.705991662092906 cap_limit: 40
3049 customer_3 ('customer_3', 'customer_4')
1141 customer_3 -18.972232110024777
resNode: customer_4 deliver_cap: 52.62565969590904 cap_limit: 40
3050 customer_3 ('customer_3', 'customer_5')
1141 customer_3 -18.972232110024777
resNode: customer_5 deliver_cap: 48.1348174762393 cap_limit: 40
3051 customer_1 ('customer_1', 'customer_3')
1142 customer_1 -15.420439892720184
resNode: customer_3 deliver_cap: 58.39691359566612 cap_limit: 40
3052 customer_1 ('customer_1', 'depot_t')
1142 customer_1 -15.420439892720184
resNode: depot_t deliver_cap: 34.836446481859866 cap_limit: 40
3053 customer_1 ('customer_1', 'customer_2')
1142 customer_1 -15.420439892720184
resNode: customer_2 deliver_cap: 38.00339616202895 cap_limit: 40
3054 customer_1 ('customer_1', 'customer_4')
1142 customer_1 -15.420439892720184
resNode: customer_4 deliver_cap: 57.93456731841153 cap_limit: 40
3055 customer_1 ('customer_1', 'customer_5')
1142 customer_1 -15.420439892720184
resNode: customer_5 deliver_cap: 47.69118103111623 cap_limit: 40
3056 customer_2 ('customer_2', 'customer_3')
1144 customer_2 -14.302635040021096
resNode: customer_3 deliver_cap: 53.20761690150767 cap_limit: 40
3057 customer_2 ('customer_2', 'customer_1')
1144 customer_2 -14.302635040021096
resNode: customer_1 deliver_cap: 41.85433347397367 cap_limit: 40
3058 customer_2 ('customer_2', 'depot_t')
1144 customer_2 -14.302635040021096
resNode: depot_t deliver_cap: 27.704817029316086 cap_limit: 40
3059 customer_2 ('customer_2', 'customer_4')
1144 customer_2 -14.302635040021096
resNode: customer_4 deliver_cap: 53.02328970487361 cap_limit: 40
3060 customer_2 ('customer_2', 'customer_5')
1144 customer_2 -14.302635040021096
resNode: customer_5 deliver_cap: 39.04911298899799 cap_limit: 40
3061 customer_5 ('customer_5', 'customer_3')
1145 customer_5 -22.131489853487924
resNode: customer_3 deliver_cap: 60.412987315620285 cap_limit: 40
3062 customer_5 ('customer_5', 'customer_1')
1145 customer_5 -22.131489853487924
resNode: customer_1 deliver_cap: 51.23503563111651 cap_limit: 40
3063 customer_5 ('customer_5', 'depot_t')
1145 customer_5 -22.131489853487924
resNode: depot_t deliver_cap: 33.77327537158452 cap_limit: 40
3064 customer_5 ('customer_5', 'customer_2')
1145 customer_5 -22.131489853487924
resNode: customer_2 deliver_cap: 37.77929594906738 cap_limit: 40
3065 customer_5 ('customer_5', 'customer_4')
1145 customer_5 -22.131489853487924
resNode: customer_4 deliver_cap: 60.191794679659424 cap_limit: 40
3066 customer_3 ('customer_3', 'customer_1')
1146 customer_3 -18.431667768768236
resNode: customer_1 deliver_cap: 47.966591479790786 cap_limit: 40
3067 customer_3 ('customer_3', 'depot_t')
1146 customer_3 -18.431667768768236
resNode: depot_t deliver_cap: 33.94531408844298 cap_limit: 40
3068 customer_3 ('customer_3', 'customer_2')
1146 customer_3 -18.431667768768236
resNode: customer_2 deliver_cap: 37.96362314570144 cap_limit: 40
3069 customer_3 ('customer_3', 'customer_4')
1146 customer_3 -18.431667768768236
resNode: customer_4 deliver_cap: 48.1348174762393 cap_limit: 40
3070 customer_3 ('customer_3', 'customer_5')
1146 customer_3 -18.431667768768236
resNode: customer_5 deliver_cap: 43.64397525656954 cap_limit: 40
3071 customer_1 ('customer_1', 'customer_3')
1147 customer_1 -14.19021323783555
resNode: customer_3 deliver_cap: 48.153527308370826 cap_limit: 40
3072 customer_1 ('customer_1', 'depot_t')
1147 customer_1 -14.19021323783555
resNode: depot_t deliver_cap: 27.324629871176654 cap_limit: 40
3073 customer_1 ('customer_1', 'customer_2')
1147 customer_1 -14.19021323783555
resNode: customer_2 deliver_cap: 29.808687132192713 cap_limit: 40
3074 customer_1 ('customer_1', 'customer_4')
1147 customer_1 -14.19021323783555
resNode: customer_4 deliver_cap: 47.69118103111624 cap_limit: 40
3075 customer_1 ('customer_1', 'customer_5')
1147 customer_1 -14.19021323783555
resNode: customer_5 deliver_cap: 37.447794743820936 cap_limit: 40
3076 customer_2 ('customer_2', 'customer_3')
1149 customer_2 -12.13971077799138
resNode: customer_3 deliver_cap: 39.233440185632055 cap_limit: 40
3077 customer_2 ('customer_2', 'customer_1')
1149 customer_2 -12.13971077799138
resNode: customer_1 deliver_cap: 30.67499210127317 cap_limit: 40
3078 customer_2 ('customer_2', 'depot_t')
1149 customer_2 -12.13971077799138
resNode: depot_t deliver_cap: 17.457087437673966 cap_limit: 40
3079 customer_2 ('customer_2', 'customer_4')
1149 customer_2 -12.13971077799138
resNode: customer_4 deliver_cap: 39.049112988998 cap_limit: 40
3080 customer_2 ('customer_2', 'customer_5')
1149 customer_2 -12.13971077799138
resNode: customer_5 deliver_cap: 25.074936273122383 cap_limit: 40
3081 customer_4 ('customer_4', 'customer_3')
1150 customer_4 -18.405042729254426
resNode: customer_3 deliver_cap: 48.1348174762393 cap_limit: 40
3082 customer_4 ('customer_4', 'customer_1')
1150 customer_4 -18.405042729254426
resNode: customer_1 deliver_cap: 47.50424520253618 cap_limit: 40
3083 customer_4 ('customer_4', 'depot_t')
1150 customer_4 -18.405042729254426
resNode: depot_t deliver_cap: 33.773275371584525 cap_limit: 40
3084 customer_4 ('customer_4', 'customer_2')
1150 customer_4 -18.405042729254426
resNode: customer_2 deliver_cap: 37.77929594906739 cap_limit: 40
3085 customer_4 ('customer_4', 'customer_5')
1150 customer_4 -18.405042729254426
resNode: customer_5 deliver_cap: 43.42278262060867 cap_limit: 40
3086 customer_2 ('customer_2', 'customer_3')
1153 customer_2 -18.34215386655041
resNode: customer_3 deliver_cap: 65.1250221712509 cap_limit: 40
3087 customer_2 ('customer_2', 'customer_1')
1153 customer_2 -18.34215386655041
resNode: customer_1 deliver_cap: 53.381151750335164 cap_limit: 40
3088 customer_2 ('customer_2', 'depot_t')
1153 customer_2 -18.34215386655041
resNode: depot_t deliver_cap: 36.25302879980644 cap_limit: 40
3089 customer_2 ('customer_2', 'customer_4')
1153 customer_2 -18.34215386655041
resNode: customer_4 deliver_cap: 64.90382953529004 cap_limit: 40
3090 customer_2 ('customer_2', 'customer_5')
1153 customer_2 -18.34215386655041
resNode: customer_5 deliver_cap: 48.13481747623929 cap_limit: 40
3091 customer_2 ('customer_2', 'customer_3')
1158 customer_2 -15.520926874678471
resNode: customer_3 deliver_cap: 60.06910534981904 cap_limit: 40
3092 customer_2 ('customer_2', 'customer_1')
1158 customer_2 -15.520926874678471
resNode: customer_1 deliver_cap: 47.343524232622755 cap_limit: 40
3093 customer_2 ('customer_2', 'depot_t')
1158 customer_2 -15.520926874678471
resNode: depot_t deliver_cap: 32.73657522474441 cap_limit: 40
3094 customer_2 ('customer_2', 'customer_4')
1158 customer_2 -15.520926874678471
resNode: customer_4 deliver_cap: 59.88477815318498 cap_limit: 40
3095 customer_2 ('customer_2', 'customer_5')
1158 customer_2 -15.520926874678471
resNode: customer_5 deliver_cap: 45.91060143730935 cap_limit: 40
3096 customer_1 ('customer_1', 'customer_3')
1162 customer_1 -16.07601483442994
resNode: customer_3 deliver_cap: 60.34712443043957 cap_limit: 40
3097 customer_1 ('customer_1', 'depot_t')
1162 customer_1 -16.07601483442994
resNode: depot_t deliver_cap: 36.26660109402707 cap_limit: 40
3098 customer_1 ('customer_1', 'customer_2')
1162 customer_1 -16.07601483442994
resNode: customer_2 deliver_cap: 39.56356482984771 cap_limit: 40
3099 customer_1 ('customer_1', 'customer_4')
1162 customer_1 -16.07601483442994
resNode: customer_4 deliver_cap: 59.88477815318498 cap_limit: 40
3100 customer_1 ('customer_1', 'customer_5')
1162 customer_1 -16.07601483442994
resNode: customer_5 deliver_cap: 49.64139186588968 cap_limit: 40
3101 customer_5 ('customer_5', 'customer_3')
1165 customer_5 -22.29951208650431
resNode: customer_3 deliver_cap: 60.41298731562028 cap_limit: 40
3102 customer_5 ('customer_5', 'customer_1')
1165 customer_5 -22.29951208650431
resNode: customer_1 deliver_cap: 51.235035631116496 cap_limit: 40
3103 customer_5 ('customer_5', 'depot_t')
1165 customer_5 -22.29951208650431
resNode: depot_t deliver_cap: 33.77327537158452 cap_limit: 40
3104 customer_5 ('customer_5', 'customer_2')
1165 customer_5 -22.29951208650431
resNode: customer_2 deliver_cap: 37.779295949067375 cap_limit: 40
3105 customer_5 ('customer_5', 'customer_4')
1165 customer_5 -22.29951208650431
resNode: customer_4 deliver_cap: 60.1917946796594 cap_limit: 40
3106 customer_2 ('customer_2', 'customer_3')
1169 customer_2 -21.239631895811854
resNode: customer_3 deliver_cap: 60.41298731562028 cap_limit: 40
3107 customer_2 ('customer_2', 'customer_1')
1169 customer_2 -21.239631895811854
resNode: customer_1 deliver_cap: 49.45445603730964 cap_limit: 40
3108 customer_2 ('customer_2', 'depot_t')
1169 customer_2 -21.239631895811854
resNode: depot_t deliver_cap: 32.588112800982614 cap_limit: 40
3109 customer_2 ('customer_2', 'customer_4')
1169 customer_2 -21.239631895811854
resNode: customer_4 deliver_cap: 60.1917946796594 cap_limit: 40
3110 customer_2 ('customer_2', 'customer_5')
1169 customer_2 -21.239631895811854
resNode: customer_5 deliver_cap: 43.42278262060866 cap_limit: 40
3111 customer_1 ('customer_1', 'customer_3')
1171 customer_1 -13.516788797930387
resNode: customer_3 deliver_cap: 65.02933987816027 cap_limit: 40
3112 customer_1 ('customer_1', 'depot_t')
1171 customer_1 -13.516788797930387
resNode: depot_t deliver_cap: 39.70022575568891 cap_limit: 40
3113 customer_1 ('customer_1', 'customer_2')
1171 customer_1 -13.516788797930387
resNode: customer_2 deliver_cap: 43.309337188024266 cap_limit: 40
3114 customer_1 ('customer_1', 'customer_4')
1171 customer_1 -13.516788797930387
resNode: customer_4 deliver_cap: 64.56699360090568 cap_limit: 40
3115 customer_1 ('customer_1', 'customer_5')
1171 customer_1 -13.516788797930387
resNode: customer_5 deliver_cap: 54.323607313610374 cap_limit: 40
3116 customer_2 ('customer_2', 'customer_3')
1173 customer_2 -12.329479175076163
resNode: customer_3 deliver_cap: 59.562024103381276 cap_limit: 40
3117 customer_2 ('customer_2', 'customer_1')
1173 customer_2 -12.329479175076163
resNode: customer_1 deliver_cap: 46.937859235472544 cap_limit: 40
3118 customer_2 ('customer_2', 'depot_t')
1173 customer_2 -12.329479175076163
resNode: depot_t deliver_cap: 32.36471564402339 cap_limit: 40
3119 customer_2 ('customer_2', 'customer_4')
1173 customer_2 -12.329479175076163
resNode: customer_4 deliver_cap: 59.37769690674721 cap_limit: 40
3120 customer_2 ('customer_2', 'customer_5')
1173 customer_2 -12.329479175076163
resNode: customer_5 deliver_cap: 45.403520190871596 cap_limit: 40
3121 customer_5 ('customer_5', 'customer_3')
1175 customer_5 -21.746935789011392
resNode: customer_3 deliver_cap: 68.0382759578686 cap_limit: 40
3122 customer_5 ('customer_5', 'customer_1')
1175 customer_5 -21.746935789011392
resNode: customer_1 deliver_cap: 57.58944283299011 cap_limit: 40
3123 customer_5 ('customer_5', 'depot_t')
1175 customer_5 -21.746935789011392
resNode: depot_t deliver_cap: 39.70405542666656 cap_limit: 40
3124 customer_5 ('customer_5', 'customer_2')
1175 customer_5 -21.746935789011392
resNode: customer_2 deliver_cap: 44.13370315094099 cap_limit: 40
3125 customer_5 ('customer_5', 'customer_4')
1175 customer_5 -21.746935789011392
resNode: customer_4 deliver_cap: 67.81708332190775 cap_limit: 40
3126 customer_3 ('customer_3', 'customer_1')
1176 customer_3 -13.245933992583781
resNode: customer_1 deliver_cap: 46.937859235472544 cap_limit: 40
3127 customer_3 ('customer_3', 'depot_t')
1176 customer_3 -13.245933992583781
resNode: depot_t deliver_cap: 34.52218875968464 cap_limit: 40
3128 customer_3 ('customer_3', 'customer_2')
1176 customer_3 -13.245933992583781
resNode: customer_2 deliver_cap: 38.93548456820107 cap_limit: 40
3129 customer_3 ('customer_3', 'customer_4')
1176 customer_3 -13.245933992583781
resNode: customer_4 deliver_cap: 50.81808046141597 cap_limit: 40
3130 customer_3 ('customer_3', 'customer_5')
1176 customer_3 -13.245933992583781
resNode: customer_5 deliver_cap: 47.07571194502451 cap_limit: 40
3131 customer_1 ('customer_1', 'customer_3')
1177 customer_1 -5.9273864250139345
resNode: customer_3 deliver_cap: 45.66294422329108 cap_limit: 40
3132 customer_1 ('customer_1', 'depot_t')
1177 customer_1 -5.9273864250139345
resNode: depot_t deliver_cap: 24.632539672524754 cap_limit: 40
3133 customer_1 ('customer_1', 'customer_2')
1177 customer_1 -5.9273864250139345
resNode: customer_2 deliver_cap: 27.71160713159035 cap_limit: 40
3134 customer_1 ('customer_1', 'customer_4')
1177 customer_1 -5.9273864250139345
resNode: customer_4 deliver_cap: 45.2930672014874 cap_limit: 40
3135 customer_1 ('customer_1', 'customer_5')
1177 customer_1 -5.9273864250139345
resNode: customer_5 deliver_cap: 37.09835817165116 cap_limit: 40
3136 customer_4 ('customer_4', 'customer_3')
1179 customer_4 -13.228525312901676
resNode: customer_3 deliver_cap: 50.81808046141597 cap_limit: 40
3137 customer_4 ('customer_4', 'customer_1')
1179 customer_4 -13.228525312901676
resNode: customer_1 deliver_cap: 46.56798221366886 cap_limit: 40
3138 customer_4 ('customer_4', 'depot_t')
1179 customer_4 -13.228525312901676
resNode: depot_t deliver_cap: 34.387015482153 cap_limit: 40
3139 customer_4 ('customer_4', 'customer_2')
1179 customer_4 -13.228525312901676
resNode: customer_2 deliver_cap: 38.78802281089382 cap_limit: 40
3140 customer_4 ('customer_4', 'customer_5')
1179 customer_4 -13.228525312901676
resNode: customer_5 deliver_cap: 46.89138474839045 cap_limit: 40
3141 customer_5 ('customer_5', 'customer_3')
1180 customer_5 -11.997212831930332
resNode: customer_3 deliver_cap: 47.07571194502451 cap_limit: 40
3142 customer_5 ('customer_5', 'customer_1')
1180 customer_5 -11.997212831930332
resNode: customer_1 deliver_cap: 38.37327318383262 cap_limit: 40
3143 customer_5 ('customer_5', 'depot_t')
1180 customer_5 -11.997212831930332
resNode: depot_t deliver_cap: 24.139285890510877 cap_limit: 40
3144 customer_5 ('customer_5', 'customer_2')
1180 customer_5 -11.997212831930332
resNode: customer_2 deliver_cap: 27.608681438193326 cap_limit: 40
3145 customer_5 ('customer_5', 'customer_4')
1180 customer_5 -11.997212831930332
resNode: customer_4 deliver_cap: 46.89138474839045 cap_limit: 40
3146 customer_1 ('customer_1', 'customer_3')
1182 customer_1 -13.273943676663597
resNode: customer_3 deliver_cap: 64.28897452028512 cap_limit: 40
3147 customer_1 ('customer_1', 'depot_t')
1182 customer_1 -13.273943676663597
resNode: depot_t deliver_cap: 39.15729115991381 cap_limit: 40
3148 customer_1 ('customer_1', 'customer_2')
1182 customer_1 -13.273943676663597
resNode: customer_2 deliver_cap: 42.71704490172415 cap_limit: 40
3149 customer_1 ('customer_1', 'customer_4')
1182 customer_1 -13.273943676663597
resNode: customer_4 deliver_cap: 63.826628243030534 cap_limit: 40
3150 customer_1 ('customer_1', 'customer_5')
1182 customer_1 -13.273943676663597
resNode: customer_5 deliver_cap: 53.58324195573523 cap_limit: 40
3151 customer_2 ('customer_2', 'customer_3')
1184 customer_2 -12.156138823964508
resNode: customer_3 deliver_cap: 59.09967782612668 cap_limit: 40
3152 customer_2 ('customer_2', 'customer_1')
1184 customer_2 -12.156138823964508
resNode: customer_1 deliver_cap: 46.56798221366887 cap_limit: 40
3153 customer_2 ('customer_2', 'depot_t')
1184 customer_2 -12.156138823964508
resNode: depot_t deliver_cap: 32.02566170737002 cap_limit: 40
3154 customer_2 ('customer_2', 'customer_4')
1184 customer_2 -12.156138823964508
resNode: customer_4 deliver_cap: 58.91535062949262 cap_limit: 40
3155 customer_2 ('customer_2', 'customer_5')
1184 customer_2 -12.156138823964508
resNode: customer_5 deliver_cap: 44.941173913617 cap_limit: 40
3156 customer_5 ('customer_5', 'customer_3')
1185 customer_5 -21.458008868586084
resNode: customer_3 deliver_cap: 67.48346042516309 cap_limit: 40
3157 customer_5 ('customer_5', 'customer_1')
1185 customer_5 -21.458008868586084
resNode: customer_1 deliver_cap: 57.12709655573552 cap_limit: 40
3158 customer_5 ('customer_5', 'depot_t')
1185 customer_5 -21.458008868586084
resNode: depot_t deliver_cap: 39.27253223456226 cap_limit: 40
3159 customer_5 ('customer_5', 'customer_2')
1185 customer_5 -21.458008868586084
resNode: customer_2 deliver_cap: 43.67135687368639 cap_limit: 40
3160 customer_5 ('customer_5', 'customer_4')
1185 customer_5 -21.458008868586084
resNode: customer_4 deliver_cap: 67.26226778920223 cap_limit: 40
3161 customer_1 ('customer_1', 'customer_3')
1187 customer_1 -13.971292076545456
resNode: customer_3 deliver_cap: 57.77637866157015 cap_limit: 40
3162 customer_1 ('customer_1', 'depot_t')
1187 customer_1 -13.971292076545456
resNode: depot_t deliver_cap: 34.38138753018949 cap_limit: 40
3163 customer_1 ('customer_1', 'customer_2')
1187 customer_1 -13.971292076545456
resNode: customer_2 deliver_cap: 37.50696821475217 cap_limit: 40
3164 customer_1 ('customer_1', 'customer_4')
1187 customer_1 -13.971292076545456
resNode: customer_4 deliver_cap: 57.31403238431555 cap_limit: 40
3165 customer_1 ('customer_1', 'customer_5')
1187 customer_1 -13.971292076545456
resNode: customer_5 deliver_cap: 47.07064609702025 cap_limit: 40
3166 customer_2 ('customer_2', 'customer_3')
1189 customer_2 -11.920789616701287
resNode: customer_3 deliver_cap: 48.85629153883138 cap_limit: 40
3167 customer_2 ('customer_2', 'customer_1')
1189 customer_2 -11.920789616701287
resNode: customer_1 deliver_cap: 38.37327318383263 cap_limit: 40
3168 customer_2 ('customer_2', 'depot_t')
1189 customer_2 -11.920789616701287
resNode: depot_t deliver_cap: 24.5138450966868 cap_limit: 40
3169 customer_2 ('customer_2', 'customer_4')
1189 customer_2 -11.920789616701287
resNode: customer_4 deliver_cap: 48.67196434219733 cap_limit: 40
3170 customer_2 ('customer_2', 'customer_5')
1189 customer_2 -11.920789616701287
resNode: customer_5 deliver_cap: 34.6977876263217 cap_limit: 40
3171 customer_1 ('customer_1', 'customer_3')
1191 customer_1 -11.338576886023397
resNode: customer_3 deliver_cap: 59.562024103381276 cap_limit: 40
3172 customer_1 ('customer_1', 'depot_t')
1191 customer_1 -11.338576886023397
resNode: depot_t deliver_cap: 35.690860854184315 cap_limit: 40
3173 customer_1 ('customer_1', 'customer_2')
1191 customer_1 -11.338576886023397
resNode: customer_2 deliver_cap: 38.935484568201076 cap_limit: 40
3174 customer_1 ('customer_1', 'customer_4')
1191 customer_1 -11.338576886023397
resNode: customer_4 deliver_cap: 59.09967782612668 cap_limit: 40
3175 customer_1 ('customer_1', 'customer_5')
1191 customer_1 -11.338576886023397
resNode: customer_5 deliver_cap: 48.85629153883138 cap_limit: 40
3176 customer_2 ('customer_2', 'customer_3')
1193 customer_2 -10.151267263169174
resNode: customer_3 deliver_cap: 54.09470832860228 cap_limit: 40
3177 customer_2 ('customer_2', 'customer_1')
1193 customer_2 -10.151267263169174
resNode: customer_1 deliver_cap: 42.564006615649355 cap_limit: 40
3178 customer_2 ('customer_2', 'depot_t')
1193 customer_2 -10.151267263169174
resNode: depot_t deliver_cap: 28.355350742518798 cap_limit: 40
3179 customer_2 ('customer_2', 'customer_4')
1193 customer_2 -10.151267263169174
resNode: customer_4 deliver_cap: 53.91038113196823 cap_limit: 40
3180 customer_2 ('customer_2', 'customer_5')
1193 customer_2 -10.151267263169174
resNode: customer_5 deliver_cap: 39.93620441609261 cap_limit: 40
3181 customer_4 ('customer_4', 'customer_3')
1194 customer_4 -15.0160121504327
resNode: customer_3 deliver_cap: 53.690169408422584 cap_limit: 40
3182 customer_4 ('customer_4', 'customer_1')
1194 customer_4 -15.0160121504327
resNode: customer_1 deliver_cap: 52.133705146022265 cap_limit: 40
3183 customer_4 ('customer_4', 'depot_t')
1194 customer_4 -15.0160121504327
resNode: depot_t deliver_cap: 38.09410465217153 cap_limit: 40
3184 customer_4 ('customer_4', 'customer_2')
1194 customer_4 -15.0160121504327
resNode: customer_2 deliver_cap: 42.408755892553465 cap_limit: 40
3185 customer_4 ('customer_4', 'customer_5')
1194 customer_4 -15.0160121504327
resNode: customer_5 deliver_cap: 48.978134552791964 cap_limit: 40
3186 customer_5 ('customer_5', 'customer_3')
1195 customer_5 -18.201894933409655

resNode: customer_3 deliver_cap: 53.690169408422584 cap_limit: 40
3257 customer_2 ('customer_2', 'customer_1')
1213 customer_2 -5.810273154952455
resNode: customer_1 deliver_cap: 43.85210778131156 cap_limit: 40
3258 customer_2 ('customer_2', 'depot_t')
1213 customer_2 -5.810273154952455
resNode: depot_t deliver_cap: 27.359254428717747 cap_limit: 40
3259 customer_2 ('customer_2', 'customer_4')
1213 customer_2 -5.810273154952455
resNode: customer_4 deliver_cap: 53.468976772461716 cap_limit: 40
3260 customer_2 ('customer_2', 'customer_5')
1213 customer_2 -5.810273154952455
resNode: customer_5 deliver_cap: 36.69996471341098 cap_limit: 40
3261 customer_4 ('customer_4', 'customer_3')
1214 customer_4 -8.44422915771168
resNode: customer_3 deliver_cap: 49.54447029294283 cap_limit: 40
3262 customer_4 ('customer_4', 'customer_1')
1214 customer_4 -8.44422915771168
resNode: customer_1 deliver_cap: 51.33696558932656 cap_limit: 40
3263 customer_4 ('customer_4', 'depot_t')
1214 customer_4 -8.44422915771168
resNode: depot_t deliver_cap: 35.65717319095337 cap_limit: 40
3264 customer_4 ('customer_4', 'customer_2')
1214 customer_4 -8.44422915771168
resNode: customer_2 deliver_cap: 39.667026485163994 cap_limit: 40
3265 customer_4 ('customer_4', 'customer_5')
1214 customer_4 -8.44422915771168
resNode: customer_5 deliver_cap: 44.0470962947071 cap_limit: 40
3266 customer_5 ('customer_5', 'customer_3')
1215 customer_5 -11.44299351486906
resNode: customer_3 deliver_cap: 58.629685849272605 cap_limit: 40
3267 customer_5 ('customer_5', 'customer_1')
1215 customer_5 -11.44299351486906
resNode: customer_1 deliver_cap: 51.32307188395319 cap_limit: 40
3268 customer_5 ('customer_5', 'depot_t')
1215 customer_5 -11.44299351486906
resNode: depot_t deliver_cap: 31.415822205709716 cap_limit: 40
3269 customer_5 ('customer_5', 'customer_2')
1215 customer_5 -11.44299351486906
resNode: customer_2 deliver_cap: 35.17618426549424 cap_limit: 40
3270 customer_5 ('customer_5', 'customer_4')
1215 customer_5 -11.44299351486906
resNode: customer_4 deliver_cap: 58.37162777398493 cap_limit: 40
3271 customer_2 ('customer_2', 'customer_3')
1218 customer_2 -5.371307155336413
resNode: customer_3 deliver_cap: 50.540061380795436 cap_limit: 40
3272 customer_2 ('customer_2', 'customer_1')
1218 customer_2 -5.371307155336413
resNode: customer_1 deliver_cap: 39.720289057403875 cap_limit: 40
3273 customer_2 ('customer_2', 'depot_t')
1218 customer_2 -5.371307155336413
resNode: depot_t deliver_cap: 25.748609647460444 cap_limit: 40
3274 customer_2 ('customer_2', 'customer_4')
1218 customer_2 -5.371307155336413
resNode: customer_4 deliver_cap: 50.35573418416138 cap_limit: 40
3275 customer_2 ('customer_2', 'customer_5')
1218 customer_2 -5.371307155336413
resNode: customer_5 deliver_cap: 36.381557468285756 cap_limit: 40
3276 customer_5 ('customer_5', 'customer_3')
1220 customer_5 -13.423562885528618
resNode: customer_3 deliver_cap: 59.34861620333385 cap_limit: 40
3277 customer_5 ('customer_5', 'customer_1')
1220 customer_5 -13.423562885528618
resNode: customer_1 deliver_cap: 50.348059704211146 cap_limit: 40
3278 customer_5 ('customer_5', 'depot_t')
1220 customer_5 -13.423562885528618
resNode: depot_t deliver_cap: 32.94543117313951 cap_limit: 40
3279 customer_5 ('customer_5', 'customer_2')
1220 customer_5 -13.423562885528618
resNode: customer_2 deliver_cap: 36.89232002216202 cap_limit: 40
3280 customer_5 ('customer_5', 'customer_4')
1220 customer_5 -13.423562885528618
resNode: customer_4 deliver_cap: 59.127423567372986 cap_limit: 40
3281 customer_3 ('customer_3', 'customer_1')
1221 customer_3 -11.724277731185293
resNode: customer_1 deliver_cap: 52.411724226642804 cap_limit: 40
3282 customer_3 ('customer_3', 'depot_t')
1221 customer_3 -11.724277731185293
resNode: depot_t deliver_cap: 38.09410465217153 cap_limit: 40
3283 customer_3 ('customer_3', 'customer_2')
1221 customer_3 -11.724277731185293
resNode: customer_2 deliver_cap: 42.408755892553465 cap_limit: 40
3284 customer_3 ('customer_3', 'customer_4')
1221 customer_3 -11.724277731185293
resNode: customer_4 deliver_cap: 53.468976772461716 cap_limit: 40
3285 customer_3 ('customer_3', 'customer_5')
1221 customer_3 -11.724277731185293
resNode: customer_5 deliver_cap: 48.978134552791964 cap_limit: 40
3286 customer_1 ('customer_1', 'customer_3')
1222 customer_1 -5.926395115087883
resNode: customer_3 deliver_cap: 50.818080461415974 cap_limit: 40
3287 customer_1 ('customer_1', 'depot_t')
1222 customer_1 -5.926395115087883
resNode: depot_t deliver_cap: 29.278635516743094 cap_limit: 40
3288 customer_1 ('customer_1', 'customer_2')
1222 customer_1 -5.926395115087883
resNode: customer_2 deliver_cap: 31.940329654628833 cap_limit: 40
3289 customer_1 ('customer_1', 'customer_4')
1222 customer_1 -5.926395115087883
resNode: customer_4 deliver_cap: 50.35573418416138 cap_limit: 40
3290 customer_1 ('customer_1', 'customer_5')
1222 customer_1 -5.926395115087883
resNode: customer_5 deliver_cap: 40.112347896866076 cap_limit: 40
3291 customer_4 ('customer_4', 'customer_3')
1224 customer_4 -11.697652691671482
resNode: customer_3 deliver_cap: 53.468976772461716 cap_limit: 40
3292 customer_4 ('customer_4', 'customer_1')
1224 customer_4 -11.697652691671482
resNode: customer_1 deliver_cap: 51.94937794938821 cap_limit: 40
3293 customer_4 ('customer_4', 'depot_t')
1224 customer_4 -11.697652691671482
resNode: depot_t deliver_cap: 37.92206593531307 cap_limit: 40
3294 customer_4 ('customer_4', 'customer_2')
1224 customer_4 -11.697652691671482
resNode: customer_2 deliver_cap: 42.2244286959194 cap_limit: 40
3295 customer_4 ('customer_4', 'customer_5')
1224 customer_4 -11.697652691671482
resNode: customer_5 deliver_cap: 48.756941916831096 cap_limit: 40
3296 customer_5 ('customer_5', 'customer_3')
1225 customer_5 -9.767631374906358
resNode: customer_3 deliver_cap: 48.978134552791964 cap_limit: 40
3297 customer_5 ('customer_5', 'customer_1')
1225 customer_5 -9.767631374906358
resNode: customer_1 deliver_cap: 41.705991662092906 cap_limit: 40
3298 customer_5 ('customer_5', 'depot_t')
1225 customer_5 -9.767631374906358
resNode: depot_t deliver_cap: 24.879501000495832 cap_limit: 40
3299 customer_5 ('customer_5', 'customer_2')
1225 customer_5 -9.767631374906358
resNode: customer_2 deliver_cap: 28.25025198004379 cap_limit: 40
3300 customer_5 ('customer_5', 'customer_4')
1225 customer_5 -9.767631374906358
resNode: customer_4 deliver_cap: 48.756941916831096 cap_limit: 40
3301 customer_1 ('customer_1', 'customer_3')
1227 customer_1 -11.431040628160524
resNode: customer_3 deliver_cap: 59.68223910007848 cap_limit: 40
3302 customer_1 ('customer_1', 'depot_t')
1227 customer_1 -11.431040628160524
resNode: depot_t deliver_cap: 36.253028799806444 cap_limit: 40
3303 customer_1 ('customer_1', 'customer_2')
1227 customer_1 -11.431040628160524
resNode: customer_2 deliver_cap: 38.84253085693547 cap_limit: 40
3304 customer_1 ('customer_1', 'customer_4')
1227 customer_1 -11.431040628160524
resNode: customer_4 deliver_cap: 59.127423567372965 cap_limit: 40
3305 customer_1 ('customer_1', 'customer_5')
1227 customer_1 -11.431040628160524
resNode: customer_5 deliver_cap: 46.835360022618616 cap_limit: 40
3306 customer_2 ('customer_2', 'customer_3')
1229 customer_2 -8.707751184213901
resNode: customer_3 deliver_cap: 48.978134552791964 cap_limit: 40
3307 customer_2 ('customer_2', 'customer_1')
1229 customer_2 -8.707751184213901
resNode: customer_1 deliver_cap: 39.925412068286036 cap_limit: 40
3308 customer_2 ('customer_2', 'depot_t')
1229 customer_2 -8.707751184213901
resNode: depot_t deliver_cap: 23.694338429893932 cap_limit: 40
3309 customer_2 ('customer_2', 'customer_4')
1229 customer_2 -8.707751184213901
resNode: customer_4 deliver_cap: 48.756941916831096 cap_limit: 40
3310 customer_2 ('customer_2', 'customer_5')
1229 customer_2 -8.707751184213901
resNode: customer_5 deliver_cap: 31.987929857780355 cap_limit: 40
3311 customer_2 ('customer_2', 'customer_3')
1233 customer_2 -13.546724412173274
resNode: customer_3 deliver_cap: 61.47749702813382 cap_limit: 40
3312 customer_2 ('customer_2', 'customer_1')
1233 customer_2 -13.546724412173274
resNode: customer_1 deliver_cap: 50.34154746440426 cap_limit: 40
3313 customer_2 ('customer_2', 'depot_t')
1233 customer_2 -13.546724412173274
resNode: depot_t deliver_cap: 33.41606479960426 cap_limit: 40
3314 customer_2 ('customer_2', 'customer_4')
1233 customer_2 -13.546724412173274
resNode: customer_4 deliver_cap: 61.25630439217294 cap_limit: 40
3315 customer_2 ('customer_2', 'customer_5')
1233 customer_2 -13.546724412173274
resNode: customer_5 deliver_cap: 44.4872923331222 cap_limit: 40
3316 customer_5 ('customer_5', 'customer_3')
1235 customer_5 -20.801804692863058
resNode: customer_3 deliver_cap: 67.71490140560239 cap_limit: 40
3317 customer_5 ('customer_5', 'customer_1')
1235 customer_5 -20.801804692863058
resNode: customer_1 deliver_cap: 59.110399503664425 cap_limit: 40
3318 customer_5 ('customer_5', 'depot_t')
1235 customer_5 -20.801804692863058
resNode: depot_t deliver_cap: 38.77052051321477 cap_limit: 40
3319 customer_5 ('customer_5', 'customer_2')
1235 customer_5 -20.801804692863058
resNode: customer_2 deliver_cap: 42.96351188520548 cap_limit: 40
3320 customer_5 ('customer_5', 'customer_4')
1235 customer_5 -20.801804692863058
resNode: customer_4 deliver_cap: 67.4568433303147 cap_limit: 40
3321 customer_2 ('customer_2', 'customer_3')
1238 customer_2 -9.426742864331178
resNode: customer_3 deliver_cap: 50.52848329298429 cap_limit: 40
3322 customer_2 ('customer_2', 'customer_1')
1238 customer_2 -9.426742864331178
resNode: customer_1 deliver_cap: 39.71102658715496 cap_limit: 40
3323 customer_2 ('customer_2', 'depot_t')
1238 customer_2 -9.426742864331178
resNode: depot_t deliver_cap: 25.74011904973227 cap_limit: 40
3324 customer_2 ('customer_2', 'customer_4')
1238 customer_2 -9.426742864331178
resNode: customer_4 deliver_cap: 50.34415609635023 cap_limit: 40
3325 customer_2 ('customer_2', 'customer_5')
1238 customer_2 -9.426742864331178
resNode: customer_5 deliver_cap: 36.36997938047461 cap_limit: 40
3326 customer_5 ('customer_5', 'customer_3')
1240 customer_5 -17.476104072570596
resNode: customer_3 deliver_cap: 59.33472249796047 cap_limit: 40
3327 customer_5 ('customer_5', 'customer_1')
1240 customer_5 -17.476104072570596
resNode: customer_1 deliver_cap: 50.3364816164 cap_limit: 40
3328 customer_5 ('customer_5', 'depot_t')
1240 customer_5 -17.476104072570596
resNode: depot_t deliver_cap: 32.93462495784911 cap_limit: 40
3329 customer_5 ('customer_5', 'customer_2')
1240 customer_5 -17.476104072570596
resNode: customer_2 deliver_cap: 36.88074193435087 cap_limit: 40
3330 customer_5 ('customer_5', 'customer_4')
1240 customer_5 -17.476104072570596
resNode: customer_4 deliver_cap: 59.11352986199961 cap_limit: 40
3331 customer_3 ('customer_3', 'customer_1')
1241 customer_3 -13.662704342031756
resNode: customer_1 deliver_cap: 48.669355710251345 cap_limit: 40
3332 customer_3 ('customer_3', 'depot_t')
1241 customer_3 -13.662704342031756
resNode: depot_t deliver_cap: 34.60122737020616 cap_limit: 40
3333 customer_3 ('customer_3', 'customer_2')
1241 customer_3 -13.662704342031756
resNode: customer_2 deliver_cap: 38.666387376162 cap_limit: 40
3334 customer_3 ('customer_3', 'customer_4')
1241 customer_3 -13.662704342031756
resNode: customer_4 deliver_cap: 48.978134552791964 cap_limit: 40
3335 customer_3 ('customer_3', 'customer_5')
1241 customer_3 -13.662704342031756
resNode: customer_5 deliver_cap: 44.48729233312221 cap_limit: 40
3336 customer_1 ('customer_1', 'customer_3')
1242 customer_1 -8.800413855032213
resNode: customer_3 deliver_cap: 47.07571194502451 cap_limit: 40
3337 customer_1 ('customer_1', 'depot_t')
1242 customer_1 -8.800413855032213
resNode: depot_t deliver_cap: 26.534231938056024 cap_limit: 40
3338 customer_1 ('customer_1', 'customer_2')
1242 customer_1 -8.800413855032213
resNode: customer_2 deliver_cap: 28.94643484151566 cap_limit: 40
3339 customer_1 ('customer_1', 'customer_4')
1242 customer_1 -8.800413855032213
resNode: customer_4 deliver_cap: 46.61336566776992 cap_limit: 40
3340 customer_1 ('customer_1', 'customer_5')
1242 customer_1 -8.800413855032213
resNode: customer_5 deliver_cap: 36.36997938047462 cap_limit: 40
3341 customer_4 ('customer_4', 'customer_3')
1244 customer_4 -13.636079302517949
resNode: customer_3 deliver_cap: 48.978134552791964 cap_limit: 40
3342 customer_4 ('customer_4', 'customer_1')
1244 customer_4 -13.636079302517949
resNode: customer_1 deliver_cap: 48.20700943299674 cap_limit: 40
3343 customer_4 ('customer_4', 'depot_t')
1244 customer_4 -13.636079302517949
resNode: depot_t deliver_cap: 34.429188653347715 cap_limit: 40
3344 customer_4 ('customer_4', 'customer_2')
1244 customer_4 -13.636079302517949
resNode: customer_2 deliver_cap: 38.48206017952795 cap_limit: 40
3345 customer_4 ('customer_4', 'customer_5')
1244 customer_4 -13.636079302517949
resNode: customer_5 deliver_cap: 44.26609969716134 cap_limit: 40
3346 customer_5 ('customer_5', 'customer_3')
1245 customer_5 -11.706057985752823
resNode: customer_3 deliver_cap: 44.48729233312221 cap_limit: 40
3347 customer_5 ('customer_5', 'customer_1')
1245 customer_5 -11.706057985752823
resNode: customer_1 deliver_cap: 37.96362314570145 cap_limit: 40
3348 customer_5 ('customer_5', 'depot_t')
1245 customer_5 -11.706057985752823
resNode: depot_t deliver_cap: 21.386623718530466 cap_limit: 40
3349 customer_5 ('customer_5', 'customer_2')
1245 customer_5 -11.706057985752823
resNode: customer_2 deliver_cap: 24.507883463652327 cap_limit: 40
3350 customer_5 ('customer_5', 'customer_4')
1245 customer_5 -11.706057985752823
resNode: customer_4 deliver_cap: 44.266099697161344 cap_limit: 40
3351 customer_2 ('customer_2', 'customer_3')
1249 customer_2 -13.507810892883862
resNode: customer_3 deliver_cap: 61.25630439217294 cap_limit: 40
3352 customer_2 ('customer_2', 'customer_1')
1249 customer_2 -13.507810892883862
resNode: customer_1 deliver_cap: 50.15722026777019 cap_limit: 40
3353 customer_2 ('customer_2', 'depot_t')
1249 customer_2 -13.507810892883862
resNode: depot_t deliver_cap: 33.244026082745805 cap_limit: 40
3354 customer_2 ('customer_2', 'customer_4')
1249 customer_2 -13.507810892883862
resNode: customer_4 deliver_cap: 61.035111756212075 cap_limit: 40
3355 customer_2 ('customer_2', 'customer_5')
1249 customer_2 -13.507810892883862
resNode: customer_5 deliver_cap: 44.26609969716133 cap_limit: 40
3356 customer_5 ('customer_5', 'customer_3')
1250 customer_5 -20.716809374415128
resNode: customer_3 deliver_cap: 67.4568433303147 cap_limit: 40
3357 customer_5 ('customer_5', 'customer_1')
1250 customer_5 -20.716809374415128
resNode: customer_1 deliver_cap: 58.88920686770355 cap_limit: 40
3358 customer_5 ('customer_5', 'depot_t')
1250 customer_5 -20.716809374415128
resNode: depot_t deliver_cap: 38.5616163570295 cap_limit: 40
3359 customer_5 ('customer_5', 'customer_2')
1250 customer_5 -20.716809374415128
resNode: customer_2 deliver_cap: 42.7423192492446 cap_limit: 40
3360 customer_5 ('customer_5', 'customer_4')
1250 customer_5 -20.716809374415128
resNode: customer_4 deliver_cap: 67.19878525502702 cap_limit: 40
3361 customer_3 ('customer_3', 'customer_1')
1251 customer_3 -16.89469559803888
resNode: customer_1 deliver_cap: 51.31171185529574 cap_limit: 40
3362 customer_3 ('customer_3', 'depot_t')
1251 customer_3 -16.89469559803888
resNode: depot_t deliver_cap: 38.531553661189236 cap_limit: 40
3363 customer_3 ('customer_3', 'customer_2')
1251 customer_3 -16.89469559803888
resNode: customer_2 deliver_cap: 43.309337188024266 cap_limit: 40
3364 customer_3 ('customer_3', 'customer_4')
1251 customer_3 -16.89469559803888
resNode: customer_4 deliver_cap: 56.28539623619496 cap_limit: 40
3365 customer_3 ('customer_3', 'customer_5')
1251 customer_3 -16.89469559803888
resNode: customer_5 deliver_cap: 52.543027719803504 cap_limit: 40
3366 customer_2 ('customer_2', 'customer_3')
1253 customer_2 -7.52215788062453
resNode: customer_3 deliver_cap: 45.662944223291085 cap_limit: 40
3367 customer_2 ('customer_2', 'customer_1')
1253 customer_2 -7.52215788062453
resNode: customer_1 deliver_cap: 33.71338813204396 cap_limit: 40
3368 customer_2 ('customer_2', 'depot_t')
1253 customer_2 -7.52215788062453
resNode: depot_t deliver_cap: 22.213524974225905 cap_limit: 40
3369 customer_2 ('customer_2', 'customer_4')
1253 customer_2 -7.52215788062453
resNode: customer_4 deliver_cap: 45.51548246598384 cap_limit: 40
3370 customer_2 ('customer_2', 'customer_5')
1253 customer_2 -7.52215788062453
resNode: customer_5 deliver_cap: 34.336141093283345 cap_limit: 40
3371 customer_4 ('customer_4', 'customer_3')
1254 customer_4 -16.752178332077534
resNode: customer_3 deliver_cap: 56.00737715557443 cap_limit: 40
3372 customer_4 ('customer_4', 'customer_1')
1254 customer_4 -16.752178332077534
resNode: customer_1 deliver_cap: 50.71941956899563 cap_limit: 40
3373 customer_4 ('customer_4', 'depot_t')
1254 customer_4 -16.752178332077534
resNode: depot_t deliver_cap: 38.19249972453587 cap_limit: 40
3374 customer_4 ('customer_4', 'customer_2')
1254 customer_4 -16.752178332077534
resNode: customer_2 deliver_cap: 42.93946016622059 cap_limit: 40
3375 customer_4 ('customer_4', 'customer_5')
1254 customer_4 -16.752178332077534
resNode: customer_5 deliver_cap: 52.08068144254891 cap_limit: 40
3376 customer_5 ('customer_5', 'customer_3')
1255 customer_5 -17.199721543967335
resNode: customer_3 deliver_cap: 55.99579906776329 cap_limit: 40
3377 customer_5 ('customer_5', 'customer_1')
1255 customer_5 -17.199721543967335
resNode: customer_1 deliver_cap: 45.50934288202365 cap_limit: 40
3378 customer_5 ('customer_5', 'depot_t')
1255 customer_5 -17.199721543967335
resNode: depot_t deliver_cap: 30.68068311385265 cap_limit: 40
3379 customer_5 ('customer_5', 'customer_2')
1255 customer_5 -17.199721543967335
resNode: customer_2 deliver_cap: 34.74475113638435 cap_limit: 40
3380 customer_5 ('customer_5', 'customer_4')
1255 customer_5 -17.199721543967335
resNode: customer_4 deliver_cap: 55.81147187112924 cap_limit: 40
3381 customer_3 ('customer_3', 'customer_1')
1256 customer_3 -15.080971404450489
resNode: customer_1 deliver_cap: 46.937859235472544 cap_limit: 40
3382 customer_3 ('customer_3', 'depot_t')
1256 customer_3 -15.080971404450489
resNode: depot_t deliver_cap: 34.52218875968464 cap_limit: 40
3383 customer_3 ('customer_3', 'customer_2')
1256 customer_3 -15.080971404450489
resNode: customer_2 deliver_cap: 38.93548456820107 cap_limit: 40
3384 customer_3 ('customer_3', 'customer_4')
1256 customer_3 -15.080971404450489
resNode: customer_4 deliver_cap: 50.81808046141597 cap_limit: 40
3385 customer_3 ('customer_3', 'customer_5')
1256 customer_3 -15.080971404450489
resNode: customer_5 deliver_cap: 47.07571194502451 cap_limit: 40
3386 customer_1 ('customer_1', 'customer_3')
1257 customer_1 -7.762423836880643
resNode: customer_3 deliver_cap: 45.662944223291085 cap_limit: 40
3387 customer_1 ('customer_1', 'depot_t')
1257 customer_1 -7.762423836880643
resNode: depot_t deliver_cap: 24.632539672524757 cap_limit: 40
3388 customer_1 ('customer_1', 'customer_2')
1257 customer_1 -7.762423836880643
resNode: customer_2 deliver_cap: 27.711607131590352 cap_limit: 40
3389 customer_1 ('customer_1', 'customer_4')
1257 customer_1 -7.762423836880643
resNode: customer_4 deliver_cap: 45.29306720148741 cap_limit: 40
3390 customer_1 ('customer_1', 'customer_5')
1257 customer_1 -7.762423836880643
resNode: customer_5 deliver_cap: 37.09835817165117 cap_limit: 40
3391 customer_4 ('customer_4', 'customer_3')
1259 customer_4 -15.063562724768383
resNode: customer_3 deliver_cap: 50.81808046141597 cap_limit: 40
3392 customer_4 ('customer_4', 'customer_1')
1259 customer_4 -15.063562724768383
resNode: customer_1 deliver_cap: 46.56798221366886 cap_limit: 40
3393 customer_4 ('customer_4', 'depot_t')
1259 customer_4 -15.063562724768383
resNode: depot_t deliver_cap: 34.387015482153 cap_limit: 40
3394 customer_4 ('customer_4', 'customer_2')
1259 customer_4 -15.063562724768383

3465 customer_4 ('customer_4', 'customer_5')
1279 customer_4 -9.642661999877461
resNode: customer_5 deliver_cap: 35.304017474801995 cap_limit: 40
3466 customer_5 ('customer_5', 'customer_3')
1280 customer_5 -10.602374526132024
resNode: customer_3 deliver_cap: 38.436111574973495 cap_limit: 40
3467 customer_5 ('customer_5', 'customer_1')
1280 customer_5 -10.602374526132024
resNode: customer_1 deliver_cap: 29.361611402089885 cap_limit: 40
3468 customer_5 ('customer_5', 'depot_t')
1280 customer_5 -10.602374526132024
resNode: depot_t deliver_cap: 18.072872296643833 cap_limit: 40
3469 customer_5 ('customer_5', 'customer_2')
1280 customer_5 -10.602374526132024
resNode: customer_2 deliver_cap: 21.288167592860407 cap_limit: 40
3470 customer_5 ('customer_5', 'customer_4')
1280 customer_5 -10.602374526132024
resNode: customer_4 deliver_cap: 38.288649817666254 cap_limit: 40
3471 customer_3 ('customer_3', 'customer_1')
1281 customer_3 -11.539667943859218
resNode: customer_1 deliver_cap: 39.9427043219003 cap_limit: 40
3472 customer_3 ('customer_3', 'depot_t')
1281 customer_3 -11.539667943859218
resNode: depot_t deliver_cap: 28.109963422243425 cap_limit: 40
3473 customer_3 ('customer_3', 'customer_2')
1281 customer_3 -11.539667943859218
resNode: customer_2 deliver_cap: 31.940329654628833 cap_limit: 40
3474 customer_3 ('customer_3', 'customer_4')
1281 customer_3 -11.539667943859218
resNode: customer_4 deliver_cap: 42.07413681945068 cap_limit: 40
3475 customer_3 ('customer_3', 'customer_5')
1281 customer_3 -11.539667943859218
resNode: customer_5 deliver_cap: 38.33176830305921 cap_limit: 40
3476 customer_1 ('customer_1', 'customer_3')
1282 customer_1 -8.063425759722836
resNode: customer_3 deliver_cap: 45.2930672014874 cap_limit: 40
3477 customer_1 ('customer_1', 'depot_t')
1282 customer_1 -8.063425759722836
resNode: depot_t deliver_cap: 24.385954991322304 cap_limit: 40
3478 customer_1 ('customer_1', 'customer_2')
1282 customer_1 -8.063425759722836
resNode: customer_2 deliver_cap: 27.434199365237593 cap_limit: 40
3479 customer_1 ('customer_1', 'customer_4')
1282 customer_1 -8.063425759722836
resNode: customer_4 deliver_cap: 44.92319017968373 cap_limit: 40
3480 customer_1 ('customer_1', 'customer_5')
1282 customer_1 -8.063425759722836
resNode: customer_5 deliver_cap: 36.72848114984748 cap_limit: 40
3481 customer_2 ('customer_2', 'customer_3')
1284 customer_2 -7.431868369697188
resNode: customer_3 deliver_cap: 41.14162984616064 cap_limit: 40
3482 customer_2 ('customer_2', 'customer_1')
1284 customer_2 -7.431868369697188
resNode: customer_1 deliver_cap: 30.322402349196125 cap_limit: 40
3483 customer_2 ('customer_2', 'depot_t')
1284 customer_2 -7.431868369697188
resNode: depot_t deliver_cap: 19.199315389472275 cap_limit: 40
3484 customer_2 ('customer_2', 'customer_4')
1284 customer_2 -7.431868369697188
resNode: customer_4 deliver_cap: 40.99416808885339 cap_limit: 40
3485 customer_2 ('customer_2', 'customer_5')
1284 customer_2 -7.431868369697188
resNode: customer_5 deliver_cap: 29.814826716152897 cap_limit: 40
3486 customer_5 ('customer_5', 'customer_3')
1285 customer_5 -14.89526047297364
resNode: customer_3 deliver_cap: 48.56357650254337 cap_limit: 40
3487 customer_5 ('customer_5', 'customer_1')
1285 customer_5 -14.89526047297364
resNode: customer_1 deliver_cap: 39.56356482984771 cap_limit: 40
3488 customer_5 ('customer_5', 'depot_t')
1285 customer_5 -14.89526047297364
resNode: depot_t deliver_cap: 25.230386566024706 cap_limit: 40
3489 customer_5 ('customer_5', 'customer_2')
1285 customer_5 -14.89526047297364
resNode: customer_2 deliver_cap: 28.798973084208413 cap_limit: 40
3490 customer_5 ('customer_5', 'customer_4')
1285 customer_5 -14.89526047297364
resNode: customer_4 deliver_cap: 48.37924930590931 cap_limit: 40
3491 customer_3 ('customer_3', 'customer_1')
1286 customer_3 -11.186222028422248
resNode: customer_1 deliver_cap: 36.948809508787136 cap_limit: 40
3492 customer_3 ('customer_3', 'depot_t')
1286 customer_3 -11.186222028422248
resNode: depot_t deliver_cap: 25.36555984355635 cap_limit: 40
3493 customer_3 ('customer_3', 'customer_2')
1286 customer_3 -11.186222028422248
resNode: customer_2 deliver_cap: 28.94643484151566 cap_limit: 40
3494 customer_3 ('customer_3', 'customer_4')
1286 customer_3 -11.186222028422248
resNode: customer_4 deliver_cap: 38.331768303059214 cap_limit: 40
3495 customer_3 ('customer_3', 'customer_5')
1286 customer_3 -11.186222028422248
resNode: customer_5 deliver_cap: 34.589399786667755 cap_limit: 40
3496 customer_1 ('customer_1', 'customer_3')
1287 customer_1 -7.3453684192029645
resNode: customer_3 deliver_cap: 37.098358171651164 cap_limit: 40
3497 customer_1 ('customer_1', 'depot_t')
1287 customer_1 -7.3453684192029645
resNode: depot_t deliver_cap: 18.922815638098143 cap_limit: 40
3498 customer_1 ('customer_1', 'customer_2')
1287 customer_1 -7.3453684192029645
resNode: customer_2 deliver_cap: 21.28816759286041 cap_limit: 40
3499 customer_1 ('customer_1', 'customer_4')
1287 customer_1 -7.3453684192029645
resNode: customer_4 deliver_cap: 36.72848114984749 cap_limit: 40
3500 customer_1 ('customer_1', 'customer_5')
1287 customer_1 -7.3453684192029645
resNode: customer_5 deliver_cap: 28.53377212001125 cap_limit: 40
3501 customer_2 ('customer_2', 'customer_3')
1289 customer_2 -5.9676529434612515
resNode: customer_3 deliver_cap: 29.96228847346015 cap_limit: 40
3502 customer_2 ('customer_2', 'customer_1')
1289 customer_2 -5.9676529434612515
resNode: customer_1 deliver_cap: 21.937896319670752 cap_limit: 40
3503 customer_2 ('customer_2', 'depot_t')
1289 customer_2 -5.9676529434612515
resNode: depot_t deliver_cap: 11.746421141005282 cap_limit: 40
3504 customer_2 ('customer_2', 'customer_4')
1289 customer_2 -5.9676529434612515
resNode: customer_4 deliver_cap: 29.814826716152908 cap_limit: 40
3505 customer_2 ('customer_2', 'customer_5')
1289 customer_2 -5.9676529434612515
resNode: customer_5 deliver_cap: 18.63548534345241 cap_limit: 40
3506 customer_4 ('customer_4', 'customer_3')
1290 customer_4 -11.16881334874014
resNode: customer_3 deliver_cap: 38.331768303059214 cap_limit: 40
3507 customer_4 ('customer_4', 'customer_1')
1290 customer_4 -11.16881334874014
resNode: customer_1 deliver_cap: 36.578932486983454 cap_limit: 40
3508 customer_4 ('customer_4', 'depot_t')
1290 customer_4 -11.16881334874014
resNode: depot_t deliver_cap: 25.230386566024706 cap_limit: 40
3509 customer_4 ('customer_4', 'customer_2')
1290 customer_4 -11.16881334874014
resNode: customer_2 deliver_cap: 28.798973084208413 cap_limit: 40
3510 customer_4 ('customer_4', 'customer_5')
1290 customer_4 -11.16881334874014
resNode: customer_5 deliver_cap: 34.40507259003369 cap_limit: 40
3511 customer_1 ('customer_1', 'customer_3')
1291 customer_1 -10.632725021329737
resNode: customer_3 deliver_cap: 56.007377155574424 cap_limit: 40
3512 customer_1 ('customer_1', 'depot_t')
1291 customer_1 -10.632725021329737
resNode: depot_t deliver_cap: 33.08411975912596 cap_limit: 40
3513 customer_1 ('customer_1', 'customer_2')
1291 customer_1 -10.632725021329737
resNode: customer_2 deliver_cap: 36.09176700995559 cap_limit: 40
3514 customer_1 ('customer_1', 'customer_4')
1291 customer_1 -10.632725021329737
resNode: customer_4 deliver_cap: 55.54503087831983 cap_limit: 40
3515 customer_1 ('customer_1', 'customer_5')
1291 customer_1 -10.632725021329737
resNode: customer_5 deliver_cap: 45.30164459102453 cap_limit: 40
3516 customer_2 ('customer_2', 'customer_3')
1293 customer_2 -9.445415398475511
resNode: customer_3 deliver_cap: 50.540061380795436 cap_limit: 40
3517 customer_2 ('customer_2', 'customer_1')
1293 customer_2 -9.445415398475511
resNode: customer_1 deliver_cap: 39.720289057403875 cap_limit: 40
3518 customer_2 ('customer_2', 'depot_t')
1293 customer_2 -9.445415398475511
resNode: depot_t deliver_cap: 25.748609647460444 cap_limit: 40
3519 customer_2 ('customer_2', 'customer_4')
1293 customer_2 -9.445415398475511
resNode: customer_4 deliver_cap: 50.35573418416138 cap_limit: 40
3520 customer_2 ('customer_2', 'customer_5')
1293 customer_2 -9.445415398475511
resNode: customer_5 deliver_cap: 36.381557468285756 cap_limit: 40
3521 customer_4 ('customer_4', 'customer_3')
1294 customer_4 -13.421498548787326
resNode: customer_3 deliver_cap: 49.42459307105436 cap_limit: 40
3522 customer_4 ('customer_4', 'customer_1')
1294 customer_4 -13.421498548787326
resNode: customer_1 deliver_cap: 48.579058198215414 cap_limit: 40
3523 customer_4 ('customer_4', 'depot_t')
1294 customer_4 -13.421498548787326
resNode: depot_t deliver_cap: 34.7764341675518 cap_limit: 40
3524 customer_4 ('customer_4', 'customer_2')
1294 customer_4 -13.421498548787326
resNode: customer_2 deliver_cap: 38.854108944746606 cap_limit: 40
3525 customer_4 ('customer_4', 'customer_5')
1294 customer_4 -13.421498548787326
resNode: customer_5 deliver_cap: 44.71255821542374 cap_limit: 40
3526 customer_5 ('customer_5', 'customer_3')
1295 customer_5 -16.607381331764277
resNode: customer_3 deliver_cap: 57.2119206907656 cap_limit: 40
3527 customer_5 ('customer_5', 'customer_1')
1295 customer_5 -16.607381331764277
resNode: customer_1 deliver_cap: 48.567480110404276 cap_limit: 40
3528 customer_5 ('customer_5', 'depot_t')
1295 customer_5 -16.607381331764277
resNode: depot_t deliver_cap: 31.28355688558643 cap_limit: 40
3529 customer_5 ('customer_5', 'customer_2')
1295 customer_5 -16.607381331764277
resNode: customer_2 deliver_cap: 35.11174042835515 cap_limit: 40
3530 customer_5 ('customer_5', 'customer_4')
1295 customer_5 -16.607381331764277
resNode: customer_4 deliver_cap: 56.990728054804734 cap_limit: 40
3531 customer_3 ('customer_3', 'customer_1')
1296 customer_3 -16.454419714672056
resNode: customer_1 deliver_cap: 50.71941956899563 cap_limit: 40
3532 customer_3 ('customer_3', 'depot_t')
1296 customer_3 -16.454419714672056
resNode: depot_t deliver_cap: 37.988619065414134 cap_limit: 40
3533 customer_3 ('customer_3', 'customer_2')
1296 customer_3 -16.454419714672056
resNode: customer_2 deliver_cap: 42.71704490172415 cap_limit: 40
3534 customer_3 ('customer_3', 'customer_4')
1296 customer_3 -16.454419714672056
resNode: customer_4 deliver_cap: 55.54503087831983 cap_limit: 40
3535 customer_3 ('customer_3', 'customer_5')
1296 customer_3 -16.454419714672056
resNode: customer_5 deliver_cap: 51.80266236192837 cap_limit: 40
3536 customer_2 ('customer_2', 'customer_3')
1298 customer_2 -7.266973336726487
resNode: customer_3 deliver_cap: 45.07065193699097 cap_limit: 40
3537 customer_2 ('customer_2', 'customer_1')
1298 customer_2 -7.266973336726487
resNode: customer_1 deliver_cap: 33.26916891731887 cap_limit: 40
3538 customer_2 ('customer_2', 'depot_t')
1298 customer_2 -7.266973336726487
resNode: depot_t deliver_cap: 21.81866345002583 cap_limit: 40
3539 customer_2 ('customer_2', 'customer_4')
1298 customer_2 -7.266973336726487
resNode: customer_4 deliver_cap: 44.92319017968373 cap_limit: 40
3540 customer_2 ('customer_2', 'customer_5')
1298 customer_2 -7.266973336726487
resNode: customer_5 deliver_cap: 33.74384880698323 cap_limit: 40
3541 customer_4 ('customer_4', 'customer_3')
1299 customer_4 -16.311902448710708
resNode: customer_3 deliver_cap: 55.26701179769929 cap_limit: 40
3542 customer_4 ('customer_4', 'customer_1')
1299 customer_4 -16.311902448710708
resNode: customer_1 deliver_cap: 50.12712728269552 cap_limit: 40
3543 customer_4 ('customer_4', 'depot_t')
1299 customer_4 -16.311902448710708
resNode: depot_t deliver_cap: 37.64956512876077 cap_limit: 40
3544 customer_4 ('customer_4', 'customer_2')
1299 customer_4 -16.311902448710708
resNode: customer_2 deliver_cap: 42.34716787992048 cap_limit: 40
3545 customer_4 ('customer_4', 'customer_5')
1299 customer_4 -16.311902448710708
resNode: customer_5 deliver_cap: 51.340316084673766 cap_limit: 40
3546 customer_5 ('customer_5', 'customer_3')
1300 customer_5 -16.75944566060051
resNode: customer_3 deliver_cap: 55.25543370988815 cap_limit: 40
3547 customer_5 ('customer_5', 'customer_1')
1300 customer_5 -16.75944566060051
resNode: customer_1 deliver_cap: 44.91705059572354 cap_limit: 40
3548 customer_5 ('customer_5', 'depot_t')
1300 customer_5 -16.75944566060051
resNode: depot_t deliver_cap: 30.137748518077547 cap_limit: 40
3549 customer_5 ('customer_5', 'customer_2')
1300 customer_5 -16.75944566060051
resNode: customer_2 deliver_cap: 34.15245885008424 cap_limit: 40
3550 customer_5 ('customer_5', 'customer_4')
1300 customer_5 -16.75944566060051
resNode: customer_4 deliver_cap: 55.0711065132541 cap_limit: 40
3551 customer_3 ('customer_3', 'customer_1')
1301 customer_3 -14.784338712737611
resNode: customer_1 deliver_cap: 46.56798221366887 cap_limit: 40
3552 customer_3 ('customer_3', 'depot_t')
1301 customer_3 -14.784338712737611
resNode: depot_t deliver_cap: 34.183134823031274 cap_limit: 40
3553 customer_3 ('customer_3', 'customer_2')
1301 customer_3 -14.784338712737611
resNode: customer_2 deliver_cap: 38.565607546397395 cap_limit: 40
3554 customer_3 ('customer_3', 'customer_4')
1301 customer_3 -14.784338712737611
resNode: customer_4 deliver_cap: 50.35573418416138 cap_limit: 40
3555 customer_3 ('customer_3', 'customer_5')
1301 customer_3 -14.784338712737611
resNode: customer_5 deliver_cap: 46.61336566776992 cap_limit: 40
3556 customer_1 ('customer_1', 'customer_3')
1302 customer_1 -7.581377714481411
resNode: customer_3 deliver_cap: 45.2930672014874 cap_limit: 40
3557 customer_1 ('customer_1', 'depot_t')
1302 customer_1 -7.581377714481411
resNode: depot_t deliver_cap: 24.385954991322304 cap_limit: 40
3558 customer_1 ('customer_1', 'customer_2')
1302 customer_1 -7.581377714481411
resNode: customer_2 deliver_cap: 27.434199365237593 cap_limit: 40
3559 customer_1 ('customer_1', 'customer_4')
1302 customer_1 -7.581377714481411
resNode: customer_4 deliver_cap: 44.92319017968373 cap_limit: 40
3560 customer_1 ('customer_1', 'customer_5')
1302 customer_1 -7.581377714481411
resNode: customer_5 deliver_cap: 36.72848114984748 cap_limit: 40
3561 customer_4 ('customer_4', 'customer_3')
1304 customer_4 -14.766930033055505
resNode: customer_3 deliver_cap: 50.35573418416138 cap_limit: 40
3562 customer_4 ('customer_4', 'customer_1')
1304 customer_4 -14.766930033055505
resNode: customer_1 deliver_cap: 46.19810519186519 cap_limit: 40
3563 customer_4 ('customer_4', 'depot_t')
1304 customer_4 -14.766930033055505
resNode: depot_t deliver_cap: 34.04796154549963 cap_limit: 40
3564 customer_4 ('customer_4', 'customer_2')
1304 customer_4 -14.766930033055505
resNode: customer_2 deliver_cap: 38.41814578909015 cap_limit: 40
3565 customer_4 ('customer_4', 'customer_5')
1304 customer_4 -14.766930033055505
resNode: customer_5 deliver_cap: 46.42903847113586 cap_limit: 40
3566 customer_5 ('customer_5', 'customer_3')
1305 customer_5 -13.535617552084158
resNode: customer_3 deliver_cap: 46.61336566776992 cap_limit: 40
3567 customer_5 ('customer_5', 'customer_1')
1305 customer_5 -13.535617552084158
resNode: customer_1 deliver_cap: 38.00339616202895 cap_limit: 40
3568 customer_5 ('customer_5', 'depot_t')
1305 customer_5 -13.535617552084158
resNode: depot_t deliver_cap: 23.80023195385751 cap_limit: 40
3569 customer_5 ('customer_5', 'customer_2')
1305 customer_5 -13.535617552084158
resNode: customer_2 deliver_cap: 27.23880441638965 cap_limit: 40
3570 customer_5 ('customer_5', 'customer_4')
1305 customer_5 -13.535617552084158
resNode: customer_4 deliver_cap: 46.42903847113586 cap_limit: 40
3571 customer_1 ('customer_1', 'customer_3')
1307 customer_1 -14.589730673232403
resNode: customer_3 deliver_cap: 55.53345279050869 cap_limit: 40
3572 customer_1 ('customer_1', 'depot_t')
1307 customer_1 -14.589730673232403
resNode: depot_t deliver_cap: 32.73657522474442 cap_limit: 40
3573 customer_1 ('customer_1', 'customer_2')
1307 customer_1 -14.589730673232403
resNode: customer_2 deliver_cap: 35.712627517903 cap_limit: 40
3574 customer_1 ('customer_1', 'customer_4')
1307 customer_1 -14.589730673232403
resNode: customer_4 deliver_cap: 55.0711065132541 cap_limit: 40
3575 customer_1 ('customer_1', 'customer_5')
1307 customer_1 -14.589730673232403
resNode: customer_5 deliver_cap: 44.8277202259588 cap_limit: 40
3576 customer_2 ('customer_2', 'customer_3')
1309 customer_2 -12.539228213388231
resNode: customer_3 deliver_cap: 46.61336566776992 cap_limit: 40
3577 customer_2 ('customer_2', 'customer_1')
1309 customer_2 -12.539228213388231
resNode: customer_1 deliver_cap: 36.578932486983454 cap_limit: 40
3578 customer_2 ('customer_2', 'depot_t')
1309 customer_2 -12.539228213388231
resNode: depot_t deliver_cap: 22.869032791241732 cap_limit: 40
3579 customer_2 ('customer_2', 'customer_4')
1309 customer_2 -12.539228213388231
resNode: customer_4 deliver_cap: 46.42903847113586 cap_limit: 40
3580 customer_2 ('customer_2', 'customer_5')
1309 customer_2 -12.539228213388231
resNode: customer_5 deliver_cap: 32.45486175526024 cap_limit: 40
3581 customer_1 ('customer_1', 'customer_3')
1311 customer_1 -12.952240373854584
resNode: customer_3 deliver_cap: 55.995799067763286 cap_limit: 40
3582 customer_1 ('customer_1', 'depot_t')
1311 customer_1 -12.952240373854584
resNode: depot_t deliver_cap: 33.07562916139779 cap_limit: 40
3583 customer_1 ('customer_1', 'customer_2')
1311 customer_1 -12.952240373854584
resNode: customer_2 deliver_cap: 36.082504539706676 cap_limit: 40
3584 customer_1 ('customer_1', 'customer_4')
1311 customer_1 -12.952240373854584
resNode: customer_4 deliver_cap: 55.53345279050869 cap_limit: 40
3585 customer_1 ('customer_1', 'customer_5')
1311 customer_1 -12.952240373854584
resNode: customer_5 deliver_cap: 45.29006650321339 cap_limit: 40
3586 customer_2 ('customer_2', 'customer_3')
1313 customer_2 -11.764930751000358
resNode: customer_3 deliver_cap: 50.52848329298429 cap_limit: 40
3587 customer_2 ('customer_2', 'customer_1')
1313 customer_2 -11.764930751000358
resNode: customer_1 deliver_cap: 39.71102658715496 cap_limit: 40
3588 customer_2 ('customer_2', 'depot_t')
1313 customer_2 -11.764930751000358
resNode: depot_t deliver_cap: 25.74011904973227 cap_limit: 40
3589 customer_2 ('customer_2', 'customer_4')
1313 customer_2 -11.764930751000358
resNode: customer_4 deliver_cap: 50.34415609635023 cap_limit: 40
3590 customer_2 ('customer_2', 'customer_5')
1313 customer_2 -11.764930751000358
resNode: customer_5 deliver_cap: 36.36997938047461 cap_limit: 40
3591 customer_4 ('customer_4', 'customer_3')
1314 customer_4 -15.738119379359388
resNode: customer_3 deliver_cap: 49.41069936568099 cap_limit: 40
3592 customer_4 ('customer_4', 'customer_1')
1314 customer_4 -15.738119379359388
resNode: customer_1 deliver_cap: 48.56748011040427 cap_limit: 40
3593 customer_4 ('customer_4', 'depot_t')
1314 customer_4 -15.738119379359388
resNode: depot_t deliver_cap: 34.765627952261404 cap_limit: 40
3594 customer_4 ('customer_4', 'customer_2')
1314 customer_4 -15.738119379359388
resNode: customer_2 deliver_cap: 38.84253085693547 cap_limit: 40
3595 customer_4 ('customer_4', 'customer_5')
1314 customer_4 -15.738119379359388
resNode: customer_5 deliver_cap: 44.698664510050364 cap_limit: 40
3596 customer_5 ('customer_5', 'customer_3')
1315 customer_5 -18.924002162336343
resNode: customer_3 deliver_cap: 57.19802698539223 cap_limit: 40
3597 customer_5 ('customer_5', 'customer_1')
1315 customer_5 -18.924002162336343
resNode: customer_1 deliver_cap: 48.55590202259313 cap_limit: 40
3598 customer_5 ('customer_5', 'depot_t')
1315 customer_5 -18.924002162336343
resNode: depot_t deliver_cap: 31.272750670296034 cap_limit: 40
3599 customer_5 ('customer_5', 'customer_2')
1315 customer_5 -18.924002162336343
resNode: customer_2 deliver_cap: 35.100162340544 cap_limit: 40
3600 customer_5 ('customer_5', 'customer_4')
1315 customer_5 -18.924002162336343
resNode: customer_4 deliver_cap: 56.97683434943136 cap_limit: 40
3601 customer_3 ('customer_3', 'customer_1')
1316 customer_3 -15.415075885563255
resNode: customer_1 deliver_cap: 45.509342882023645 cap_limit: 40
3602 customer_3 ('customer_3', 'depot_t')
1316 customer_3 -15.415075885563255
resNode: depot_t deliver_cap: 33.21271543568982 cap_limit: 40

resNode: customer_5 deliver_cap: 36.659576548906294 cap_limit: 40
3666 customer_5 ('customer_5', 'customer_3')
1335 customer_5 -13.531953112111172
resNode: customer_3 deliver_cap: 59.68223910007848 cap_limit: 40
3667 customer_5 ('customer_5', 'customer_1')
1335 customer_5 -13.531953112111172
resNode: customer_1 deliver_cap: 50.62607878483168 cap_limit: 40
3668 customer_5 ('customer_5', 'depot_t')
1335 customer_5 -13.531953112111172
resNode: depot_t deliver_cap: 33.204915648385345 cap_limit: 40
3669 customer_5 ('customer_5', 'customer_2')
1335 customer_5 -13.531953112111172
resNode: customer_2 deliver_cap: 37.17033910278255 cap_limit: 40
3670 customer_5 ('customer_5', 'customer_4')
1335 customer_5 -13.531953112111172
resNode: customer_4 deliver_cap: 59.46104646411762 cap_limit: 40
3671 customer_3 ('customer_3', 'customer_1')
1336 customer_3 -11.675123812082877
resNode: customer_1 deliver_cap: 52.411724226642804 cap_limit: 40
3672 customer_3 ('customer_3', 'depot_t')
1336 customer_3 -11.675123812082877
resNode: depot_t deliver_cap: 38.09410465217153 cap_limit: 40
3673 customer_3 ('customer_3', 'customer_2')
1336 customer_3 -11.675123812082877
resNode: customer_2 deliver_cap: 42.408755892553465 cap_limit: 40
3674 customer_3 ('customer_3', 'customer_4')
1336 customer_3 -11.675123812082877
resNode: customer_4 deliver_cap: 53.468976772461716 cap_limit: 40
3675 customer_3 ('customer_3', 'customer_5')
1336 customer_3 -11.675123812082877
resNode: customer_5 deliver_cap: 48.978134552791964 cap_limit: 40
3676 customer_1 ('customer_1', 'customer_3')
1337 customer_1 -5.87724119598547
resNode: customer_3 deliver_cap: 50.81808046141598 cap_limit: 40
3677 customer_1 ('customer_1', 'depot_t')
1337 customer_1 -5.87724119598547
resNode: depot_t deliver_cap: 29.2786355167431 cap_limit: 40
3678 customer_1 ('customer_1', 'customer_2')
1337 customer_1 -5.87724119598547
resNode: customer_2 deliver_cap: 31.940329654628837 cap_limit: 40
3679 customer_1 ('customer_1', 'customer_4')
1337 customer_1 -5.87724119598547
resNode: customer_4 deliver_cap: 50.35573418416139 cap_limit: 40
3680 customer_1 ('customer_1', 'customer_5')
1337 customer_1 -5.87724119598547
resNode: customer_5 deliver_cap: 40.11234789686609 cap_limit: 40
3681 customer_4 ('customer_4', 'customer_3')
1339 customer_4 -11.648498772569067
resNode: customer_3 deliver_cap: 53.468976772461716 cap_limit: 40
3682 customer_4 ('customer_4', 'customer_1')
1339 customer_4 -11.648498772569067
resNode: customer_1 deliver_cap: 51.94937794938821 cap_limit: 40
3683 customer_4 ('customer_4', 'depot_t')
1339 customer_4 -11.648498772569067
resNode: depot_t deliver_cap: 37.92206593531307 cap_limit: 40
3684 customer_4 ('customer_4', 'customer_2')
1339 customer_4 -11.648498772569067
resNode: customer_2 deliver_cap: 42.2244286959194 cap_limit: 40
3685 customer_4 ('customer_4', 'customer_5')
1339 customer_4 -11.648498772569067
resNode: customer_5 deliver_cap: 48.756941916831096 cap_limit: 40
3686 customer_5 ('customer_5', 'customer_3')
1340 customer_5 -9.718477455803946
resNode: customer_3 deliver_cap: 48.978134552791964 cap_limit: 40
3687 customer_5 ('customer_5', 'customer_1')
1340 customer_5 -9.718477455803946
resNode: customer_1 deliver_cap: 41.70599166209291 cap_limit: 40
3688 customer_5 ('customer_5', 'depot_t')
1340 customer_5 -9.718477455803946
resNode: depot_t deliver_cap: 24.879501000495836 cap_limit: 40
3689 customer_5 ('customer_5', 'customer_2')
1340 customer_5 -9.718477455803946
resNode: customer_2 deliver_cap: 28.250251980043792 cap_limit: 40
3690 customer_5 ('customer_5', 'customer_4')
1340 customer_5 -9.718477455803946
resNode: customer_4 deliver_cap: 48.756941916831096 cap_limit: 40
3691 customer_3 ('customer_3', 'customer_1')
1341 customer_3 -8.345921319506854
resNode: customer_1 deliver_cap: 51.6705884860712 cap_limit: 40
3692 customer_3 ('customer_3', 'depot_t')
1341 customer_3 -8.345921319506854
resNode: depot_t deliver_cap: 35.65717319095338 cap_limit: 40
3693 customer_3 ('customer_3', 'customer_2')
1341 customer_3 -8.345921319506854
resNode: customer_2 deliver_cap: 39.667026485164 cap_limit: 40
3694 customer_3 ('customer_3', 'customer_4')
1341 customer_3 -8.345921319506854
resNode: customer_4 deliver_cap: 49.28641221765516 cap_limit: 40
3695 customer_3 ('customer_3', 'customer_5')
1341 customer_3 -8.345921319506854
resNode: customer_5 deliver_cap: 44.0470962947071 cap_limit: 40
3696 customer_1 ('customer_1', 'customer_3')
1342 customer_1 -7.3262580319331585
resNode: customer_3 deliver_cap: 59.69613280545186 cap_limit: 40
3697 customer_1 ('customer_1', 'depot_t')
1342 customer_1 -7.3262580319331585
resNode: depot_t deliver_cap: 36.26383501509684 cap_limit: 40
3698 customer_1 ('customer_1', 'customer_2')
1342 customer_1 -7.3262580319331585
resNode: customer_2 deliver_cap: 38.85410894474661 cap_limit: 40
3699 customer_1 ('customer_1', 'customer_4')
1342 customer_1 -7.3262580319331585
resNode: customer_4 deliver_cap: 59.14131727274634 cap_limit: 40
3700 customer_1 ('customer_1', 'customer_5')
1342 customer_1 -7.3262580319331585
resNode: customer_5 deliver_cap: 46.84925372799198 cap_limit: 40
3701 customer_2 ('customer_2', 'customer_3')
1344 customer_2 -5.722205716560629
resNode: customer_3 deliver_cap: 53.46897677246172 cap_limit: 40
3702 customer_2 ('customer_2', 'customer_1')
1344 customer_2 -5.722205716560629
resNode: customer_1 deliver_cap: 43.6677805846775 cap_limit: 40
3703 customer_2 ('customer_2', 'depot_t')
1344 customer_2 -5.722205716560629
resNode: depot_t deliver_cap: 27.187215711859295 cap_limit: 40
3704 customer_2 ('customer_2', 'customer_4')
1344 customer_2 -5.722205716560629
resNode: customer_4 deliver_cap: 53.247784136500854 cap_limit: 40
3705 customer_2 ('customer_2', 'customer_5')
1344 customer_2 -5.722205716560629
resNode: customer_5 deliver_cap: 36.47877207745011 cap_limit: 40
3706 customer_5 ('customer_5', 'customer_3')
1345 customer_5 -11.308844277318723
resNode: customer_3 deliver_cap: 58.37162777398493 cap_limit: 40
3707 customer_5 ('customer_5', 'customer_1')
1345 customer_5 -11.308844277318723
resNode: customer_1 deliver_cap: 51.101879247992315 cap_limit: 40
3708 customer_5 ('customer_5', 'depot_t')
1345 customer_5 -11.308844277318723
resNode: depot_t deliver_cap: 31.206918049524454 cap_limit: 40
3709 customer_5 ('customer_5', 'customer_2')
1345 customer_5 -11.308844277318723
resNode: customer_2 deliver_cap: 34.95499162953338 cap_limit: 40
3710 customer_5 ('customer_5', 'customer_4')
1345 customer_5 -11.308844277318723
resNode: customer_4 deliver_cap: 58.11356969869725 cap_limit: 40
3711 customer_1 ('customer_1', 'customer_3')
1347 customer_1 -11.381886709058112
resNode: customer_3 deliver_cap: 59.68223910007848 cap_limit: 40
3712 customer_1 ('customer_1', 'depot_t')
1347 customer_1 -11.381886709058112
resNode: depot_t deliver_cap: 36.253028799806444 cap_limit: 40
3713 customer_1 ('customer_1', 'customer_2')
1347 customer_1 -11.381886709058112
resNode: customer_2 deliver_cap: 38.84253085693547 cap_limit: 40
3714 customer_1 ('customer_1', 'customer_4')
1347 customer_1 -11.381886709058112
resNode: customer_4 deliver_cap: 59.127423567372965 cap_limit: 40
3715 customer_1 ('customer_1', 'customer_5')
1347 customer_1 -11.381886709058112
resNode: customer_5 deliver_cap: 46.835360022618616 cap_limit: 40
3716 customer_2 ('customer_2', 'customer_3')
1349 customer_2 -8.658597265111485
resNode: customer_3 deliver_cap: 48.978134552791964 cap_limit: 40
3717 customer_2 ('customer_2', 'customer_1')
1349 customer_2 -8.658597265111485
resNode: customer_1 deliver_cap: 39.925412068286036 cap_limit: 40
3718 customer_2 ('customer_2', 'depot_t')
1349 customer_2 -8.658597265111485
resNode: depot_t deliver_cap: 23.694338429893932 cap_limit: 40
3719 customer_2 ('customer_2', 'customer_4')
1349 customer_2 -8.658597265111485
resNode: customer_4 deliver_cap: 48.756941916831096 cap_limit: 40
3720 customer_2 ('customer_2', 'customer_5')
1349 customer_2 -8.658597265111485
resNode: customer_5 deliver_cap: 31.987929857780355 cap_limit: 40
3721 customer_1 ('customer_1', 'customer_3')
1351 customer_1 -13.263471442566011
resNode: customer_3 deliver_cap: 64.56699360090568 cap_limit: 40
3722 customer_1 ('customer_1', 'depot_t')
1351 customer_1 -13.263471442566011
resNode: depot_t deliver_cap: 39.36117181903554 cap_limit: 40
3723 customer_1 ('customer_1', 'customer_2')
1351 customer_1 -13.263471442566011
resNode: customer_2 deliver_cap: 42.93946016622059 cap_limit: 40
3724 customer_1 ('customer_1', 'customer_4')
1351 customer_1 -13.263471442566011
resNode: customer_4 deliver_cap: 64.10464732365108 cap_limit: 40
3725 customer_1 ('customer_1', 'customer_5')
1351 customer_1 -13.263471442566011
resNode: customer_5 deliver_cap: 53.86126103635578 cap_limit: 40
3726 customer_2 ('customer_2', 'customer_3')
1353 customer_2 -12.076161819711787
resNode: customer_3 deliver_cap: 59.09967782612668 cap_limit: 40
3727 customer_2 ('customer_2', 'customer_1')
1353 customer_2 -12.076161819711787
resNode: customer_1 deliver_cap: 46.56798221366887 cap_limit: 40
3728 customer_2 ('customer_2', 'depot_t')
1353 customer_2 -12.076161819711787
resNode: depot_t deliver_cap: 32.02566170737002 cap_limit: 40
3729 customer_2 ('customer_2', 'customer_4')
1353 customer_2 -12.076161819711787
resNode: customer_4 deliver_cap: 58.91535062949262 cap_limit: 40
3730 customer_2 ('customer_2', 'customer_5')
1353 customer_2 -12.076161819711787
resNode: customer_5 deliver_cap: 44.941173913617 cap_limit: 40
3731 customer_5 ('customer_5', 'customer_3')
1355 customer_5 -21.378031864333366
resNode: customer_3 deliver_cap: 67.4834604251631 cap_limit: 40
3732 customer_5 ('customer_5', 'customer_1')
1355 customer_5 -21.378031864333366
resNode: customer_1 deliver_cap: 57.12709655573552 cap_limit: 40
3733 customer_5 ('customer_5', 'depot_t')
1355 customer_5 -21.378031864333366
resNode: depot_t deliver_cap: 39.27253223456226 cap_limit: 40
3734 customer_5 ('customer_5', 'customer_2')
1355 customer_5 -21.378031864333366
resNode: customer_2 deliver_cap: 43.67135687368639 cap_limit: 40
3735 customer_5 ('customer_5', 'customer_4')
1355 customer_5 -21.378031864333366
resNode: customer_4 deliver_cap: 67.26226778920223 cap_limit: 40
3736 customer_3 ('customer_3', 'customer_1')
1356 customer_3 -12.99261663721941
resNode: customer_1 deliver_cap: 46.56798221366887 cap_limit: 40
3737 customer_3 ('customer_3', 'depot_t')
1356 customer_3 -12.99261663721941
resNode: depot_t deliver_cap: 34.183134823031274 cap_limit: 40
3738 customer_3 ('customer_3', 'customer_2')
1356 customer_3 -12.99261663721941
resNode: customer_2 deliver_cap: 38.565607546397395 cap_limit: 40
3739 customer_3 ('customer_3', 'customer_4')
1356 customer_3 -12.99261663721941
resNode: customer_4 deliver_cap: 50.35573418416138 cap_limit: 40
3740 customer_3 ('customer_3', 'customer_5')
1356 customer_3 -12.99261663721941
resNode: customer_5 deliver_cap: 46.61336566776992 cap_limit: 40
3741 customer_1 ('customer_1', 'customer_3')
1357 customer_1 -5.789655638963209
resNode: customer_3 deliver_cap: 45.2930672014874 cap_limit: 40
3742 customer_1 ('customer_1', 'depot_t')
1357 customer_1 -5.789655638963209
resNode: depot_t deliver_cap: 24.385954991322304 cap_limit: 40
3743 customer_1 ('customer_1', 'customer_2')
1357 customer_1 -5.789655638963209
resNode: customer_2 deliver_cap: 27.434199365237593 cap_limit: 40
3744 customer_1 ('customer_1', 'customer_4')
1357 customer_1 -5.789655638963209
resNode: customer_4 deliver_cap: 44.92319017968373 cap_limit: 40
3745 customer_1 ('customer_1', 'customer_5')
1357 customer_1 -5.789655638963209
resNode: customer_5 deliver_cap: 36.72848114984748 cap_limit: 40
3746 customer_4 ('customer_4', 'customer_3')
1359 customer_4 -12.975207957537304
resNode: customer_3 deliver_cap: 50.35573418416138 cap_limit: 40
3747 customer_4 ('customer_4', 'customer_1')
1359 customer_4 -12.975207957537304
resNode: customer_1 deliver_cap: 46.19810519186519 cap_limit: 40
3748 customer_4 ('customer_4', 'depot_t')
1359 customer_4 -12.975207957537304
resNode: depot_t deliver_cap: 34.04796154549963 cap_limit: 40
3749 customer_4 ('customer_4', 'customer_2')
1359 customer_4 -12.975207957537304
resNode: customer_2 deliver_cap: 38.41814578909015 cap_limit: 40
3750 customer_4 ('customer_4', 'customer_5')
1359 customer_4 -12.975207957537304
resNode: customer_5 deliver_cap: 46.42903847113586 cap_limit: 40
3751 customer_5 ('customer_5', 'customer_3')
1360 customer_5 -11.743895476565957
resNode: customer_3 deliver_cap: 46.61336566776992 cap_limit: 40
3752 customer_5 ('customer_5', 'customer_1')
1360 customer_5 -11.743895476565957
resNode: customer_1 deliver_cap: 38.00339616202895 cap_limit: 40
3753 customer_5 ('customer_5', 'depot_t')
1360 customer_5 -11.743895476565957
resNode: depot_t deliver_cap: 23.80023195385751 cap_limit: 40
3754 customer_5 ('customer_5', 'customer_2')
1360 customer_5 -11.743895476565957
resNode: customer_2 deliver_cap: 27.23880441638965 cap_limit: 40
3755 customer_5 ('customer_5', 'customer_4')
1360 customer_5 -11.743895476565957
resNode: customer_4 deliver_cap: 46.42903847113586 cap_limit: 40
3756 customer_1 ('customer_1', 'customer_3')
1362 customer_1 -13.020626321299222
resNode: customer_3 deliver_cap: 63.826628243030534 cap_limit: 40
3757 customer_1 ('customer_1', 'depot_t')
1362 customer_1 -13.020626321299222
resNode: depot_t deliver_cap: 38.81823722326044 cap_limit: 40
3758 customer_1 ('customer_1', 'customer_2')
1362 customer_1 -13.020626321299222
resNode: customer_2 deliver_cap: 42.34716787992048 cap_limit: 40
3759 customer_1 ('customer_1', 'customer_4')
1362 customer_1 -13.020626321299222
resNode: customer_4 deliver_cap: 63.364281965775945 cap_limit: 40
3760 customer_1 ('customer_1', 'customer_5')
1362 customer_1 -13.020626321299222
resNode: customer_5 deliver_cap: 53.12089567848064 cap_limit: 40
3761 customer_2 ('customer_2', 'customer_3')
1364 customer_2 -11.902821468600134
resNode: customer_3 deliver_cap: 58.63733154887208 cap_limit: 40
3762 customer_2 ('customer_2', 'customer_1')
1364 customer_2 -11.902821468600134
resNode: customer_1 deliver_cap: 46.198105191865196 cap_limit: 40
3763 customer_2 ('customer_2', 'depot_t')
1364 customer_2 -11.902821468600134
resNode: depot_t deliver_cap: 31.686607770716655 cap_limit: 40
3764 customer_2 ('customer_2', 'customer_4')
1364 customer_2 -11.902821468600134
resNode: customer_4 deliver_cap: 58.453004352238025 cap_limit: 40
3765 customer_2 ('customer_2', 'customer_5')
1364 customer_2 -11.902821468600134
resNode: customer_5 deliver_cap: 44.47882763636241 cap_limit: 40
3766 customer_5 ('customer_5', 'customer_3')
1365 customer_5 -21.089104943908062
resNode: customer_3 deliver_cap: 66.92864489245758 cap_limit: 40
3767 customer_5 ('customer_5', 'customer_1')
1365 customer_5 -21.089104943908062
resNode: customer_1 deliver_cap: 56.66475027848092 cap_limit: 40
3768 customer_5 ('customer_5', 'depot_t')
1365 customer_5 -21.089104943908062
resNode: depot_t deliver_cap: 38.841009042457976 cap_limit: 40
3769 customer_5 ('customer_5', 'customer_2')
1365 customer_5 -21.089104943908062
resNode: customer_2 deliver_cap: 43.209010596431796 cap_limit: 40
3770 customer_5 ('customer_5', 'customer_4')
1365 customer_5 -21.089104943908062
resNode: customer_4 deliver_cap: 66.70745225649672 cap_limit: 40
3771 customer_1 ('customer_1', 'customer_3')
1367 customer_1 -13.717974721181083
resNode: customer_3 deliver_cap: 57.31403238431556 cap_limit: 40
3772 customer_1 ('customer_1', 'depot_t')
1367 customer_1 -13.717974721181083
resNode: depot_t deliver_cap: 34.04233359353612 cap_limit: 40
3773 customer_1 ('customer_1', 'customer_2')
1367 customer_1 -13.717974721181083
resNode: customer_2 deliver_cap: 37.137091192948496 cap_limit: 40
3774 customer_1 ('customer_1', 'customer_4')
1367 customer_1 -13.717974721181083
resNode: customer_4 deliver_cap: 56.85168610706096 cap_limit: 40
3775 customer_1 ('customer_1', 'customer_5')
1367 customer_1 -13.717974721181083
resNode: customer_5 deliver_cap: 46.608299819765655 cap_limit: 40
3776 customer_2 ('customer_2', 'customer_3')
1369 customer_2 -11.667472261336915
resNode: customer_3 deliver_cap: 48.39394526157678 cap_limit: 40
3777 customer_2 ('customer_2', 'customer_1')
1369 customer_2 -11.667472261336915
resNode: customer_1 deliver_cap: 38.003396162028956 cap_limit: 40
3778 customer_2 ('customer_2', 'depot_t')
1369 customer_2 -11.667472261336915
resNode: depot_t deliver_cap: 24.174791160033433 cap_limit: 40
3779 customer_2 ('customer_2', 'customer_4')
1369 customer_2 -11.667472261336915
resNode: customer_4 deliver_cap: 48.20961806494273 cap_limit: 40
3780 customer_2 ('customer_2', 'customer_5')
1369 customer_2 -11.667472261336915
resNode: customer_5 deliver_cap: 34.23544134906711 cap_limit: 40
3781 customer_1 ('customer_1', 'customer_3')
1371 customer_1 -11.247437327687672
resNode: customer_3 deliver_cap: 59.377696906747225 cap_limit: 40
3782 customer_1 ('customer_1', 'depot_t')
1371 customer_1 -11.247437327687672
resNode: depot_t deliver_cap: 35.55568757665268 cap_limit: 40
3783 customer_1 ('customer_1', 'customer_2')
1371 customer_1 -11.247437327687672
resNode: customer_2 deliver_cap: 38.788022810893835 cap_limit: 40
3784 customer_1 ('customer_1', 'customer_4')
1371 customer_1 -11.247437327687672
resNode: customer_4 deliver_cap: 58.915350629492636 cap_limit: 40
3785 customer_1 ('customer_1', 'customer_5')
1371 customer_1 -11.247437327687672
resNode: customer_5 deliver_cap: 48.671964342197334 cap_limit: 40
3786 customer_2 ('customer_2', 'customer_3')
1373 customer_2 -10.060127704833446
resNode: customer_3 deliver_cap: 53.91038113196823 cap_limit: 40
3787 customer_2 ('customer_2', 'customer_1')
1373 customer_2 -10.060127704833446
resNode: customer_1 deliver_cap: 42.41654485834211 cap_limit: 40
3788 customer_2 ('customer_2', 'depot_t')
1373 customer_2 -10.060127704833446
resNode: depot_t deliver_cap: 28.22017746498716 cap_limit: 40
3789 customer_2 ('customer_2', 'customer_4')
1373 customer_2 -10.060127704833446
resNode: customer_4 deliver_cap: 53.72605393533417 cap_limit: 40
3790 customer_2 ('customer_2', 'customer_5')
1373 customer_2 -10.060127704833446
resNode: customer_5 deliver_cap: 39.75187721945855 cap_limit: 40
3791 customer_4 ('customer_4', 'customer_3')
1374 customer_4 -14.878790792938458
resNode: customer_3 deliver_cap: 53.468976772461716 cap_limit: 40
3792 customer_4 ('customer_4', 'customer_1')
1374 customer_4 -14.878790792938458
resNode: customer_1 deliver_cap: 51.94937794938821 cap_limit: 40
3793 customer_4 ('customer_4', 'depot_t')
1374 customer_4 -14.878790792938458
resNode: depot_t deliver_cap: 37.92206593531307 cap_limit: 40
3794 customer_4 ('customer_4', 'customer_2')
1374 customer_4 -14.878790792938458
resNode: customer_2 deliver_cap: 42.2244286959194 cap_limit: 40
3795 customer_4 ('customer_4', 'customer_5')
1374 customer_4 -14.878790792938458
resNode: customer_5 deliver_cap: 48.756941916831096 cap_limit: 40
3796 customer_5 ('customer_5', 'customer_3')
1375 customer_5 -18.064673575915414
resNode: customer_3 deliver_cap: 61.256304392172964 cap_limit: 40
3797 customer_5 ('customer_5', 'customer_1')
1375 customer_5 -18.064673575915414
resNode: customer_1 deliver_cap: 51.93779986157707 cap_limit: 40
3798 customer_5 ('customer_5', 'depot_t')
1375 customer_5 -18.064673575915414
resNode: depot_t deliver_cap: 34.429188653347715 cap_limit: 40
3799 customer_5 ('customer_5', 'customer_2')
1375 customer_5 -18.064673575915414
resNode: customer_2 deliver_cap: 38.48206017952795 cap_limit: 40
3800 customer_5 ('customer_5', 'customer_4')
1375 customer_5 -18.064673575915414
resNode: customer_4 deliver_cap: 61.03511175621209 cap_limit: 40
3801 customer_3 ('customer_3', 'customer_1')
1376 customer_3 -12.790306715929457
resNode: customer_1 deliver_cap: 46.7903974781653 cap_limit: 40
3802 customer_3 ('customer_3', 'depot_t')
1376 customer_3 -12.790306715929457
resNode: depot_t deliver_cap: 34.387015482153004 cap_limit: 40
3803 customer_3 ('customer_3', 'customer_2')
1376 customer_3 -12.790306715929457

1380 customer_5 -13.095332661857906
resNode: customer_1 deliver_cap: 40.98802850489321 cap_limit: 40
3818 customer_5 ('customer_5', 'depot_t')
1380 customer_5 -13.095332661857906
resNode: depot_t deliver_cap: 26.53614493481641 cap_limit: 40
3819 customer_5 ('customer_5', 'customer_2')
1380 customer_5 -13.095332661857906
resNode: customer_2 deliver_cap: 30.223436759253907 cap_limit: 40
3820 customer_5 ('customer_5', 'customer_4')
1380 customer_5 -13.095332661857906
resNode: customer_4 deliver_cap: 50.15982889971618 cap_limit: 40
3821 customer_3 ('customer_3', 'customer_1')
1381 customer_3 -14.829636873836042
resNode: customer_1 deliver_cap: 52.227397030008746 cap_limit: 40
3822 customer_3 ('customer_3', 'depot_t')
1381 customer_3 -14.829636873836042
resNode: depot_t deliver_cap: 37.92206593531307 cap_limit: 40
3823 customer_3 ('customer_3', 'customer_2')
1381 customer_3 -14.829636873836042
resNode: customer_2 deliver_cap: 42.2244286959194 cap_limit: 40
3824 customer_3 ('customer_3', 'customer_4')
1381 customer_3 -14.829636873836042
resNode: customer_4 deliver_cap: 53.24778413650084 cap_limit: 40
3825 customer_3 ('customer_3', 'customer_5')
1381 customer_3 -14.829636873836042
resNode: customer_5 deliver_cap: 48.756941916831096 cap_limit: 40
3826 customer_1 ('customer_1', 'customer_3')
1382 customer_1 -11.148235398074826
resNode: customer_3 deliver_cap: 58.91535062949263 cap_limit: 40
3827 customer_1 ('customer_1', 'depot_t')
1382 customer_1 -11.148235398074826
resNode: depot_t deliver_cap: 35.21663363999931 cap_limit: 40
3828 customer_1 ('customer_1', 'customer_2')
1382 customer_1 -11.148235398074826
resNode: customer_2 deliver_cap: 38.418145789090154 cap_limit: 40
3829 customer_1 ('customer_1', 'customer_4')
1382 customer_1 -11.148235398074826
resNode: customer_4 deliver_cap: 58.453004352238025 cap_limit: 40
3830 customer_1 ('customer_1', 'customer_5')
1382 customer_1 -11.148235398074826
resNode: customer_5 deliver_cap: 48.209618064942724 cap_limit: 40
3831 customer_2 ('customer_2', 'customer_3')
1384 customer_2 -10.030430545375737
resNode: customer_3 deliver_cap: 53.72605393533417 cap_limit: 40
3832 customer_2 ('customer_2', 'customer_1')
1384 customer_2 -10.030430545375737
resNode: customer_1 deliver_cap: 42.269083101034866 cap_limit: 40
3833 customer_2 ('customer_2', 'depot_t')
1384 customer_2 -10.030430545375737
resNode: depot_t deliver_cap: 28.085004187455517 cap_limit: 40
3834 customer_2 ('customer_2', 'customer_4')
1384 customer_2 -10.030430545375737
resNode: customer_4 deliver_cap: 53.54172673870011 cap_limit: 40
3835 customer_2 ('customer_2', 'customer_5')
1384 customer_2 -10.030430545375737
resNode: customer_5 deliver_cap: 39.56755002282449 cap_limit: 40
3836 customer_5 ('customer_5', 'customer_3')
1385 customer_5 -17.988894617299188
resNode: customer_3 deliver_cap: 61.03511175621209 cap_limit: 40
3837 customer_5 ('customer_5', 'customer_1')
1385 customer_5 -17.988894617299188
resNode: customer_1 deliver_cap: 51.753472664943004 cap_limit: 40
3838 customer_5 ('customer_5', 'depot_t')
1385 customer_5 -17.988894617299188
resNode: depot_t deliver_cap: 34.257149936489256 cap_limit: 40
3839 customer_5 ('customer_5', 'customer_2')
1385 customer_5 -17.988894617299188
resNode: customer_2 deliver_cap: 38.29773298289388 cap_limit: 40
3840 customer_5 ('customer_5', 'customer_4')
1385 customer_5 -17.988894617299188
resNode: customer_4 deliver_cap: 60.813919120251214 cap_limit: 40
3841 customer_3 ('customer_3', 'customer_1')
1386 customer_3 -14.289072532579501
resNode: customer_1 deliver_cap: 48.48502851361729 cap_limit: 40
3842 customer_3 ('customer_3', 'depot_t')
1386 customer_3 -14.289072532579501
resNode: depot_t deliver_cap: 34.429188653347715 cap_limit: 40
3843 customer_3 ('customer_3', 'customer_2')
1386 customer_3 -14.289072532579501
resNode: customer_2 deliver_cap: 38.48206017952795 cap_limit: 40
3844 customer_3 ('customer_3', 'customer_4')
1386 customer_3 -14.289072532579501
resNode: customer_4 deliver_cap: 48.756941916831096 cap_limit: 40
3845 customer_3 ('customer_3', 'customer_5')
1386 customer_3 -14.289072532579501
resNode: customer_5 deliver_cap: 44.266099697161344 cap_limit: 40
3846 customer_1 ('customer_1', 'customer_3')
1387 customer_1 -9.918008743190187
resNode: customer_3 deliver_cap: 48.67196434219733 cap_limit: 40
3847 customer_1 ('customer_1', 'depot_t')
1387 customer_1 -9.918008743190187
resNode: depot_t deliver_cap: 27.704817029316086 cap_limit: 40
3848 customer_1 ('customer_1', 'customer_2')
1387 customer_1 -9.918008743190187
resNode: customer_2 deliver_cap: 30.22343675925391 cap_limit: 40
3849 customer_1 ('customer_1', 'customer_4')
1387 customer_1 -9.918008743190187
resNode: customer_4 deliver_cap: 48.20961806494273 cap_limit: 40
3850 customer_1 ('customer_1', 'customer_5')
1387 customer_1 -9.918008743190187
resNode: customer_5 deliver_cap: 37.96623177764743 cap_limit: 40
3851 customer_2 ('customer_2', 'customer_3')
1389 customer_2 -7.86750628334602
resNode: customer_3 deliver_cap: 39.75187721945856 cap_limit: 40
3852 customer_2 ('customer_2', 'customer_1')
1389 customer_2 -7.86750628334602
resNode: customer_1 deliver_cap: 31.089741728334367 cap_limit: 40
3853 customer_2 ('customer_2', 'depot_t')
1389 customer_2 -7.86750628334602
resNode: depot_t deliver_cap: 17.8372745958134 cap_limit: 40
3854 customer_2 ('customer_2', 'customer_4')
1389 customer_2 -7.86750628334602
resNode: customer_4 deliver_cap: 39.567550022824506 cap_limit: 40
3855 customer_2 ('customer_2', 'customer_5')
1389 customer_2 -7.86750628334602
resNode: customer_5 deliver_cap: 25.593373306948884 cap_limit: 40
3856 customer_4 ('customer_4', 'customer_3')
1390 customer_4 -14.262447493065691
resNode: customer_3 deliver_cap: 48.756941916831096 cap_limit: 40
3857 customer_4 ('customer_4', 'customer_1')
1390 customer_4 -14.262447493065691
resNode: customer_1 deliver_cap: 48.02268223636269 cap_limit: 40
3858 customer_4 ('customer_4', 'depot_t')
1390 customer_4 -14.262447493065691
resNode: depot_t deliver_cap: 34.257149936489256 cap_limit: 40
3859 customer_4 ('customer_4', 'customer_2')
1390 customer_4 -14.262447493065691
resNode: customer_2 deliver_cap: 38.29773298289388 cap_limit: 40
3860 customer_4 ('customer_4', 'customer_5')
1390 customer_4 -14.262447493065691
resNode: customer_5 deliver_cap: 44.044907061200476 cap_limit: 40
3861 customer_2 ('customer_2', 'customer_3')
1393 customer_2 -13.409503054679037
resNode: customer_3 deliver_cap: 61.25630439217295 cap_limit: 40
3862 customer_2 ('customer_2', 'customer_1')
1393 customer_2 -13.409503054679037
resNode: customer_1 deliver_cap: 50.1572202677702 cap_limit: 40
3863 customer_2 ('customer_2', 'depot_t')
1393 customer_2 -13.409503054679037
resNode: depot_t deliver_cap: 33.24402608274581 cap_limit: 40
3864 customer_2 ('customer_2', 'customer_4')
1393 customer_2 -13.409503054679037
resNode: customer_4 deliver_cap: 61.03511175621209 cap_limit: 40
3865 customer_2 ('customer_2', 'customer_5')
1393 customer_2 -13.409503054679037
resNode: customer_5 deliver_cap: 44.26609969716134 cap_limit: 40
3866 customer_5 ('customer_5', 'customer_3')
1395 customer_5 -20.618501536210303
resNode: customer_3 deliver_cap: 67.45684333031471 cap_limit: 40
3867 customer_5 ('customer_5', 'customer_1')
1395 customer_5 -20.618501536210303
resNode: customer_1 deliver_cap: 58.889206867703564 cap_limit: 40
3868 customer_5 ('customer_5', 'depot_t')
1395 customer_5 -20.618501536210303
resNode: depot_t deliver_cap: 38.56161635702951 cap_limit: 40
3869 customer_5 ('customer_5', 'customer_2')
1395 customer_5 -20.618501536210303
resNode: customer_2 deliver_cap: 42.74231924924461 cap_limit: 40
3870 customer_5 ('customer_5', 'customer_4')
1395 customer_5 -20.618501536210303
resNode: customer_4 deliver_cap: 67.19878525502703 cap_limit: 40
3871 customer_2 ('customer_2', 'customer_3')
1398 customer_2 -9.335603305995452
resNode: customer_3 deliver_cap: 50.34415609635024 cap_limit: 40
3872 customer_2 ('customer_2', 'customer_1')
1398 customer_2 -9.335603305995452
resNode: customer_1 deliver_cap: 39.563564829847714 cap_limit: 40
3873 customer_2 ('customer_2', 'depot_t')
1398 customer_2 -9.335603305995452
resNode: depot_t deliver_cap: 25.604945772200633 cap_limit: 40
3874 customer_2 ('customer_2', 'customer_4')
1398 customer_2 -9.335603305995452
resNode: customer_4 deliver_cap: 50.15982889971618 cap_limit: 40
3875 customer_2 ('customer_2', 'customer_5')
1398 customer_2 -9.335603305995452
resNode: customer_5 deliver_cap: 36.18565218384056 cap_limit: 40
3876 customer_5 ('customer_5', 'customer_3')
1400 customer_5 -17.338882715076355
resNode: customer_3 deliver_cap: 59.11352986199961 cap_limit: 40
3877 customer_5 ('customer_5', 'customer_1')
1400 customer_5 -17.338882715076355
resNode: customer_1 deliver_cap: 50.15215441976594 cap_limit: 40
3878 customer_5 ('customer_5', 'depot_t')
1400 customer_5 -17.338882715076355
resNode: depot_t deliver_cap: 32.76258624099066 cap_limit: 40
3879 customer_5 ('customer_5', 'customer_2')
1400 customer_5 -17.338882715076355
resNode: customer_2 deliver_cap: 36.69641473771682 cap_limit: 40
3880 customer_5 ('customer_5', 'customer_4')
1400 customer_5 -17.338882715076355
resNode: customer_4 deliver_cap: 58.892337226038734 cap_limit: 40
3881 customer_3 ('customer_3', 'customer_1')
1401 customer_3 -13.525482984537518
resNode: customer_1 deliver_cap: 48.48502851361729 cap_limit: 40
3882 customer_3 ('customer_3', 'depot_t')
1401 customer_3 -13.525482984537518
resNode: depot_t deliver_cap: 34.429188653347715 cap_limit: 40
3883 customer_3 ('customer_3', 'customer_2')
1401 customer_3 -13.525482984537518
resNode: customer_2 deliver_cap: 38.48206017952795 cap_limit: 40
3884 customer_3 ('customer_3', 'customer_4')
1401 customer_3 -13.525482984537518
resNode: customer_4 deliver_cap: 48.756941916831096 cap_limit: 40
3885 customer_3 ('customer_3', 'customer_5')
1401 customer_3 -13.525482984537518
resNode: customer_5 deliver_cap: 44.266099697161344 cap_limit: 40
3886 customer_1 ('customer_1', 'customer_3')
1402 customer_1 -8.709274296696487
resNode: customer_3 deliver_cap: 46.89138474839046 cap_limit: 40
3887 customer_1 ('customer_1', 'depot_t')
1402 customer_1 -8.709274296696487
resNode: depot_t deliver_cap: 26.399058660524382 cap_limit: 40
3888 customer_1 ('customer_1', 'customer_2')
1402 customer_1 -8.709274296696487
resNode: customer_2 deliver_cap: 28.79897308420842 cap_limit: 40
3889 customer_1 ('customer_1', 'customer_4')
1402 customer_1 -8.709274296696487
resNode: customer_4 deliver_cap: 46.42903847113586 cap_limit: 40
3890 customer_1 ('customer_1', 'customer_5')
1402 customer_1 -8.709274296696487
resNode: customer_5 deliver_cap: 36.18565218384056 cap_limit: 40
3891 customer_4 ('customer_4', 'customer_3')
1404 customer_4 -13.498857945023708
resNode: customer_3 deliver_cap: 48.756941916831096 cap_limit: 40
3892 customer_4 ('customer_4', 'customer_1')
1404 customer_4 -13.498857945023708
resNode: customer_1 deliver_cap: 48.02268223636269 cap_limit: 40
3893 customer_4 ('customer_4', 'depot_t')
1404 customer_4 -13.498857945023708
resNode: depot_t deliver_cap: 34.257149936489256 cap_limit: 40
3894 customer_4 ('customer_4', 'customer_2')
1404 customer_4 -13.498857945023708
resNode: customer_2 deliver_cap: 38.29773298289388 cap_limit: 40
3895 customer_4 ('customer_4', 'customer_5')
1404 customer_4 -13.498857945023708
resNode: customer_5 deliver_cap: 44.044907061200476 cap_limit: 40
3896 customer_5 ('customer_5', 'customer_3')
1405 customer_5 -11.568836628258584
resNode: customer_3 deliver_cap: 44.266099697161344 cap_limit: 40
3897 customer_5 ('customer_5', 'customer_1')
1405 customer_5 -11.568836628258584
resNode: customer_1 deliver_cap: 37.77929594906739 cap_limit: 40
3898 customer_5 ('customer_5', 'depot_t')
1405 customer_5 -11.568836628258584
resNode: depot_t deliver_cap: 21.214585001672017 cap_limit: 40
3899 customer_5 ('customer_5', 'customer_2')
1405 customer_5 -11.568836628258584
resNode: customer_2 deliver_cap: 24.323556267018272 cap_limit: 40
3900 customer_5 ('customer_5', 'customer_4')
1405 customer_5 -11.568836628258584
resNode: customer_4 deliver_cap: 44.044907061200476 cap_limit: 40
3901 customer_2 ('customer_2', 'customer_3')
1409 customer_2 -13.370589535389627
resNode: customer_3 deliver_cap: 61.03511175621209 cap_limit: 40
3902 customer_2 ('customer_2', 'customer_1')
1409 customer_2 -13.370589535389627
resNode: customer_1 deliver_cap: 49.97289307113615 cap_limit: 40
3903 customer_2 ('customer_2', 'depot_t')
1409 customer_2 -13.370589535389627
resNode: depot_t deliver_cap: 33.07198736588736 cap_limit: 40
3904 customer_2 ('customer_2', 'customer_4')
1409 customer_2 -13.370589535389627
resNode: customer_4 deliver_cap: 60.813919120251214 cap_limit: 40
3905 customer_2 ('customer_2', 'customer_5')
1409 customer_2 -13.370589535389627
resNode: customer_5 deliver_cap: 44.044907061200476 cap_limit: 40
3906 customer_5 ('customer_5', 'customer_3')
1410 customer_5 -20.53350621776238
resNode: customer_3 deliver_cap: 67.19878525502703 cap_limit: 40
3907 customer_5 ('customer_5', 'customer_1')
1410 customer_5 -20.53350621776238
resNode: customer_1 deliver_cap: 58.668014231742696 cap_limit: 40
3908 customer_5 ('customer_5', 'depot_t')
1410 customer_5 -20.53350621776238
resNode: depot_t deliver_cap: 38.352712200844245 cap_limit: 40
3909 customer_5 ('customer_5', 'customer_2')
1410 customer_5 -20.53350621776238
resNode: customer_2 deliver_cap: 42.52112661328374 cap_limit: 40
3910 customer_5 ('customer_5', 'customer_4')
1410 customer_5 -20.53350621776238
resNode: customer_4 deliver_cap: 66.94072717973935 cap_limit: 40
3911 customer_3 ('customer_3', 'customer_1')
1411 customer_3 -11.974193281023183
resNode: customer_1 deliver_cap: 54.136671485030334 cap_limit: 40
3912 customer_3 ('customer_3', 'depot_t')
1411 customer_3 -11.974193281023183
resNode: depot_t deliver_cap: 39.70405542666656 cap_limit: 40
3913 customer_3 ('customer_3', 'customer_2')
1411 customer_3 -11.974193281023183
resNode: customer_2 deliver_cap: 44.13370315094099 cap_limit: 40
3914 customer_3 ('customer_3', 'customer_4')
1411 customer_3 -11.974193281023183
resNode: customer_4 deliver_cap: 55.538913482526745 cap_limit: 40
3915 customer_3 ('customer_3', 'customer_5')
1411 customer_3 -11.974193281023183
resNode: customer_5 deliver_cap: 51.04807126285699 cap_limit: 40
3916 customer_2 ('customer_2', 'customer_3')
1413 customer_2 -4.557764227474669
resNode: customer_3 deliver_cap: 47.07571194502451 cap_limit: 40
3917 customer_2 ('customer_2', 'customer_1')
1413 customer_2 -4.557764227474669
resNode: customer_1 deliver_cap: 36.94880950878713 cap_limit: 40
3918 customer_2 ('customer_2', 'depot_t')
1413 customer_2 -4.557764227474669
resNode: depot_t deliver_cap: 23.2080867278951 cap_limit: 40
3919 customer_2 ('customer_2', 'customer_4')
1413 customer_2 -4.557764227474669
resNode: customer_4 deliver_cap: 46.89138474839045 cap_limit: 40
3920 customer_2 ('customer_2', 'customer_5')
1413 customer_2 -4.557764227474669
resNode: customer_5 deliver_cap: 32.917208032514836 cap_limit: 40
3921 customer_4 ('customer_4', 'customer_3')
1414 customer_4 -11.808558701199104
resNode: customer_3 deliver_cap: 55.20529058578211 cap_limit: 40
3922 customer_4 ('customer_4', 'customer_1')
1414 customer_4 -11.808558701199104
resNode: customer_1 deliver_cap: 53.39630612715519 cap_limit: 40
3923 customer_4 ('customer_4', 'depot_t')
1414 customer_4 -11.808558701199104
resNode: depot_t deliver_cap: 39.27253223456226 cap_limit: 40
3924 customer_4 ('customer_4', 'customer_2')
1414 customer_4 -11.808558701199104
resNode: customer_2 deliver_cap: 43.67135687368639 cap_limit: 40
3925 customer_4 ('customer_4', 'customer_5')
1414 customer_4 -11.808558701199104
resNode: customer_5 deliver_cap: 50.493255730151475 cap_limit: 40
3926 customer_5 ('customer_5', 'customer_3')
1415 customer_5 -11.74393259872414
resNode: customer_3 deliver_cap: 55.19139688040873 cap_limit: 40
3927 customer_5 ('customer_5', 'customer_1')
1415 customer_5 -11.74393259872414
resNode: customer_1 deliver_cap: 46.88371026844022 cap_limit: 40
3928 customer_5 ('customer_5', 'depot_t')
1415 customer_5 -11.74393259872414
resNode: depot_t deliver_cap: 29.712038366419986 cap_limit: 40
3929 customer_5 ('customer_5', 'customer_2')
1415 customer_5 -11.74393259872414
resNode: customer_2 deliver_cap: 33.42797058639109 cap_limit: 40
3930 customer_5 ('customer_5', 'customer_4')
1415 customer_5 -11.74393259872414
resNode: customer_4 deliver_cap: 54.97020424444786 cap_limit: 40
3931 customer_3 ('customer_3', 'customer_1')
1416 customer_3 -9.887103298695843
resNode: customer_1 deliver_cap: 48.669355710251345 cap_limit: 40
3932 customer_3 ('customer_3', 'depot_t')
1416 customer_3 -9.887103298695843
resNode: depot_t deliver_cap: 34.60122737020616 cap_limit: 40
3933 customer_3 ('customer_3', 'customer_2')
1416 customer_3 -9.887103298695843
resNode: customer_2 deliver_cap: 38.666387376162 cap_limit: 40
3934 customer_3 ('customer_3', 'customer_4')
1416 customer_3 -9.887103298695843
resNode: customer_4 deliver_cap: 48.978134552791964 cap_limit: 40
3935 customer_3 ('customer_3', 'customer_5')
1416 customer_3 -9.887103298695843
resNode: customer_5 deliver_cap: 44.48729233312221 cap_limit: 40
3936 customer_1 ('customer_1', 'customer_3')
1417 customer_1 -5.024812811696301
resNode: customer_3 deliver_cap: 47.07571194502451 cap_limit: 40
3937 customer_1 ('customer_1', 'depot_t')
1417 customer_1 -5.024812811696301
resNode: depot_t deliver_cap: 26.534231938056024 cap_limit: 40
3938 customer_1 ('customer_1', 'customer_2')
1417 customer_1 -5.024812811696301
resNode: customer_2 deliver_cap: 28.94643484151566 cap_limit: 40
3939 customer_1 ('customer_1', 'customer_4')
1417 customer_1 -5.024812811696301
resNode: customer_4 deliver_cap: 46.61336566776992 cap_limit: 40
3940 customer_1 ('customer_1', 'customer_5')
1417 customer_1 -5.024812811696301
resNode: customer_5 deliver_cap: 36.36997938047462 cap_limit: 40
3941 customer_4 ('customer_4', 'customer_3')
1419 customer_4 -9.860478259182038
resNode: customer_3 deliver_cap: 48.978134552791964 cap_limit: 40
3942 customer_4 ('customer_4', 'customer_1')
1419 customer_4 -9.860478259182038
resNode: customer_1 deliver_cap: 48.20700943299674 cap_limit: 40
3943 customer_4 ('customer_4', 'depot_t')
1419 customer_4 -9.860478259182038
resNode: depot_t deliver_cap: 34.429188653347715 cap_limit: 40
3944 customer_4 ('customer_4', 'customer_2')
1419 customer_4 -9.860478259182038
resNode: customer_2 deliver_cap: 38.48206017952795 cap_limit: 40
3945 customer_4 ('customer_4', 'customer_5')
1419 customer_4 -9.860478259182038
resNode: customer_5 deliver_cap: 44.26609969716134 cap_limit: 40
3946 customer_5 ('customer_5', 'customer_3')
1420 customer_5 -7.930456942416912
resNode: customer_3 deliver_cap: 44.48729233312221 cap_limit: 40
3947 customer_5 ('customer_5', 'customer_1')
1420 customer_5 -7.930456942416912
resNode: customer_1 deliver_cap: 37.96362314570145 cap_limit: 40
3948 customer_5 ('customer_5', 'depot_t')
1420 customer_5 -7.930456942416912
resNode: depot_t deliver_cap: 21.38662371853047 cap_limit: 40
3949 customer_5 ('customer_5', 'customer_2')
1420 customer_5 -7.930456942416912
resNode: customer_2 deliver_cap: 24.50788346365233 cap_limit: 40
3950 customer_5 ('customer_5', 'customer_4')
1420 customer_5 -7.930456942416912
resNode: customer_4 deliver_cap: 44.266099697161344 cap_limit: 40
3951 customer_3 ('customer_3', 'customer_1')
1421 customer_3 -5.6223086770219535
resNode: customer_1 deliver_cap: 47.17974626640145 cap_limit: 40
3952 customer_3 ('customer_3', 'depot_t')
1421 customer_3 -5.6223086770219535
resNode: depot_t deliver_cap: 31.41582220570972 cap_limit: 40
3953 customer_3 ('customer_3', 'customer_2')
1421 customer_3 -5.6223086770219535
resNode: customer_2 deliver_cap: 35.17618426549425 cap_limit: 40
3954 customer_3 ('customer_3', 'customer_4')
1421 customer_3 -5.6223086770219535
resNode: customer_4 deliver_cap: 44.0470962947071 cap_limit: 40
3955 customer_3 ('customer_3', 'customer_5')
1421 customer_3 -5.6223086770219535

resNode: customer_3 deliver_cap: 55.19139688040874 cap_limit: 40
4007 customer_5 ('customer_5', 'customer_1')
1435 customer_5 -14.172496541859802
resNode: customer_1 deliver_cap: 46.883710268440225 cap_limit: 40
4008 customer_5 ('customer_5', 'depot_t')
1435 customer_5 -14.172496541859802
resNode: depot_t deliver_cap: 29.712038366419986 cap_limit: 40
4009 customer_5 ('customer_5', 'customer_2')
1435 customer_5 -14.172496541859802
resNode: customer_2 deliver_cap: 33.42797058639109 cap_limit: 40
4010 customer_5 ('customer_5', 'customer_4')
1435 customer_5 -14.172496541859802
resNode: customer_4 deliver_cap: 54.97020424444787 cap_limit: 40
4011 customer_3 ('customer_3', 'customer_1')
1436 customer_3 -8.34792788656967
resNode: customer_1 deliver_cap: 38.37327318383263 cap_limit: 40
4012 customer_3 ('customer_3', 'depot_t')
1436 customer_3 -8.34792788656967
resNode: depot_t deliver_cap: 26.67131821234805 cap_limit: 40
4013 customer_3 ('customer_3', 'customer_2')
1436 customer_3 -8.34792788656967
resNode: customer_2 deliver_cap: 30.370898516561155 cap_limit: 40
4014 customer_3 ('customer_3', 'customer_4')
1436 customer_3 -8.34792788656967
resNode: customer_4 deliver_cap: 40.11234789686608 cap_limit: 40
4015 customer_3 ('customer_3', 'customer_5')
1436 customer_3 -8.34792788656967
resNode: customer_5 deliver_cap: 36.36997938047462 cap_limit: 40
4016 customer_1 ('customer_1', 'customer_3')
1437 customer_1 -3.7058134601372954
resNode: customer_3 deliver_cap: 37.098358171651164 cap_limit: 40
4017 customer_1 ('customer_1', 'depot_t')
1437 customer_1 -3.7058134601372954
resNode: depot_t deliver_cap: 18.922815638098143 cap_limit: 40
4018 customer_1 ('customer_1', 'customer_2')
1437 customer_1 -3.7058134601372954
resNode: customer_2 deliver_cap: 21.28816759286041 cap_limit: 40
4019 customer_1 ('customer_1', 'customer_4')
1437 customer_1 -3.7058134601372954
resNode: customer_4 deliver_cap: 36.72848114984749 cap_limit: 40
4020 customer_1 ('customer_1', 'customer_5')
1437 customer_1 -3.7058134601372954
resNode: customer_5 deliver_cap: 28.53377212001125 cap_limit: 40
4021 customer_4 ('customer_4', 'customer_3')
1439 customer_4 -8.330519206887566
resNode: customer_3 deliver_cap: 40.11234789686608 cap_limit: 40
4022 customer_4 ('customer_4', 'customer_1')
1439 customer_4 -8.330519206887566
resNode: customer_1 deliver_cap: 38.00339616202895 cap_limit: 40
4023 customer_4 ('customer_4', 'depot_t')
1439 customer_4 -8.330519206887566
resNode: depot_t deliver_cap: 26.536144934816413 cap_limit: 40
4024 customer_4 ('customer_4', 'customer_2')
1439 customer_4 -8.330519206887566
resNode: customer_2 deliver_cap: 30.22343675925391 cap_limit: 40
4025 customer_4 ('customer_4', 'customer_5')
1439 customer_4 -8.330519206887566
resNode: customer_5 deliver_cap: 36.18565218384056 cap_limit: 40
4026 customer_5 ('customer_5', 'customer_3')
1440 customer_5 -7.099206725916223
resNode: customer_3 deliver_cap: 36.36997938047462 cap_limit: 40
4027 customer_5 ('customer_5', 'customer_1')
1440 customer_5 -7.099206725916223
resNode: customer_1 deliver_cap: 29.808687132192713 cap_limit: 40
4028 customer_5 ('customer_5', 'depot_t')
1440 customer_5 -7.099206725916223
resNode: depot_t deliver_cap: 16.288415343174293 cap_limit: 40
4029 customer_5 ('customer_5', 'customer_2')
1440 customer_5 -7.099206725916223
resNode: customer_2 deliver_cap: 19.04409538655342 cap_limit: 40
4030 customer_5 ('customer_5', 'customer_4')
1440 customer_5 -7.099206725916223
resNode: customer_4 deliver_cap: 36.18565218384057 cap_limit: 40
4031 customer_3 ('customer_3', 'customer_1')
1441 customer_3 -10.72431187797135
resNode: customer_1 deliver_cap: 46.895288356251356 cap_limit: 40
4032 customer_3 ('customer_3', 'depot_t')
1441 customer_3 -10.72431187797135
resNode: depot_t deliver_cap: 32.94543117313951 cap_limit: 40
4033 customer_3 ('customer_3', 'customer_2')
1441 customer_3 -10.72431187797135
resNode: customer_2 deliver_cap: 36.89232002216202 cap_limit: 40
4034 customer_3 ('customer_3', 'customer_4')
1441 customer_3 -10.72431187797135
resNode: customer_4 deliver_cap: 46.849253727991986 cap_limit: 40
4035 customer_3 ('customer_3', 'customer_5')
1441 customer_3 -10.72431187797135
resNode: customer_5 deliver_cap: 42.35841150832222 cap_limit: 40
4036 customer_1 ('customer_1', 'customer_3')
1442 customer_1 -8.375937570649482
resNode: customer_3 deliver_cap: 53.58324195573523 cap_limit: 40
4037 customer_1 ('customer_1', 'depot_t')
1442 customer_1 -8.375937570649482
resNode: depot_t deliver_cap: 31.30642061257722 cap_limit: 40
4038 customer_1 ('customer_1', 'customer_2')
1442 customer_1 -8.375937570649482
resNode: customer_2 deliver_cap: 34.15245885008424 cap_limit: 40
4039 customer_1 ('customer_1', 'customer_4')
1442 customer_1 -8.375937570649482
resNode: customer_4 deliver_cap: 53.120895678480636 cap_limit: 40
4040 customer_1 ('customer_1', 'customer_5')
1442 customer_1 -8.375937570649482
resNode: customer_5 deliver_cap: 42.877509391185335 cap_limit: 40
4041 customer_2 ('customer_2', 'customer_3')
1444 customer_2 -7.258132717950392
resNode: customer_3 deliver_cap: 48.393945261576775 cap_limit: 40
4042 customer_2 ('customer_2', 'customer_1')
1444 customer_2 -7.258132717950392
resNode: customer_1 deliver_cap: 38.00339616202895 cap_limit: 40
4043 customer_2 ('customer_2', 'depot_t')
1444 customer_2 -7.258132717950392
resNode: depot_t deliver_cap: 24.17479116003343 cap_limit: 40
4044 customer_2 ('customer_2', 'customer_4')
1444 customer_2 -7.258132717950392
resNode: customer_4 deliver_cap: 48.20961806494272 cap_limit: 40
4045 customer_2 ('customer_2', 'customer_5')
1444 customer_2 -7.258132717950392
resNode: customer_5 deliver_cap: 34.2354413490671 cap_limit: 40
4046 customer_5 ('customer_5', 'customer_3')
1445 customer_5 -13.8835696214345
resNode: customer_3 deliver_cap: 54.63658134770322 cap_limit: 40
4047 customer_5 ('customer_5', 'customer_1')
1445 customer_5 -13.8835696214345
resNode: customer_1 deliver_cap: 46.421363991185615 cap_limit: 40
4048 customer_5 ('customer_5', 'depot_t')
1445 customer_5 -13.8835696214345
resNode: depot_t deliver_cap: 29.280515174315692 cap_limit: 40
4049 customer_5 ('customer_5', 'customer_2')
1445 customer_5 -13.8835696214345
resNode: customer_2 deliver_cap: 32.965624309136494 cap_limit: 40
4050 customer_5 ('customer_5', 'customer_4')
1445 customer_5 -13.8835696214345
resNode: customer_4 deliver_cap: 54.415388711742345 cap_limit: 40
4051 customer_3 ('customer_3', 'customer_1')
1446 customer_3 -13.04402019862639
resNode: customer_1 deliver_cap: 46.883710268440225 cap_limit: 40
4052 customer_3 ('customer_3', 'depot_t')
1446 customer_3 -13.04402019862639
resNode: depot_t deliver_cap: 32.93462495784912 cap_limit: 40
4053 customer_3 ('customer_3', 'customer_2')
1446 customer_3 -13.04402019862639
resNode: customer_2 deliver_cap: 36.88074193435088 cap_limit: 40
4054 customer_3 ('customer_3', 'customer_4')
1446 customer_3 -13.04402019862639
resNode: customer_4 deliver_cap: 46.83536002261862 cap_limit: 40
4055 customer_3 ('customer_3', 'customer_5')
1446 customer_3 -13.04402019862639
resNode: customer_5 deliver_cap: 42.344517802948864 cap_limit: 40
4056 customer_1 ('customer_1', 'customer_3')
1447 customer_1 -9.073285970531344
resNode: customer_3 deliver_cap: 47.07064609702026 cap_limit: 40
4057 customer_1 ('customer_1', 'depot_t')
1447 customer_1 -9.073285970531344
resNode: depot_t deliver_cap: 26.5305169828529 cap_limit: 40
4058 customer_1 ('customer_1', 'customer_2')
1447 customer_1 -9.073285970531344
resNode: customer_2 deliver_cap: 28.942382163112256 cap_limit: 40
4059 customer_1 ('customer_1', 'customer_4')
1447 customer_1 -9.073285970531344
resNode: customer_4 deliver_cap: 46.60829981976566 cap_limit: 40
4060 customer_1 ('customer_1', 'customer_5')
1447 customer_1 -9.073285970531344
resNode: customer_5 deliver_cap: 36.36491353247036 cap_limit: 40
4061 customer_2 ('customer_2', 'customer_3')
1449 customer_2 -7.022783510687176
resNode: customer_3 deliver_cap: 38.15055897428149 cap_limit: 40
4062 customer_2 ('customer_2', 'customer_1')
1449 customer_2 -7.022783510687176
resNode: customer_1 deliver_cap: 29.808687132192713 cap_limit: 40
4063 customer_2 ('customer_2', 'depot_t')
1449 customer_2 -7.022783510687176
resNode: depot_t deliver_cap: 16.662974549350217 cap_limit: 40
4064 customer_2 ('customer_2', 'customer_4')
1449 customer_2 -7.022783510687176
resNode: customer_4 deliver_cap: 37.96623177764744 cap_limit: 40
4065 customer_2 ('customer_2', 'customer_5')
1449 customer_2 -7.022783510687176
resNode: customer_5 deliver_cap: 23.992055061771815 cap_limit: 40
4066 customer_4 ('customer_4', 'customer_3')
1450 customer_4 -13.01739515911258
resNode: customer_3 deliver_cap: 46.83536002261862 cap_limit: 40
4067 customer_4 ('customer_4', 'customer_1')
1450 customer_4 -13.01739515911258
resNode: customer_1 deliver_cap: 46.42136399118562 cap_limit: 40
4068 customer_4 ('customer_4', 'depot_t')
1450 customer_4 -13.01739515911258
resNode: depot_t deliver_cap: 32.76258624099066 cap_limit: 40
4069 customer_4 ('customer_4', 'customer_2')
1450 customer_4 -13.01739515911258
resNode: customer_2 deliver_cap: 36.69641473771682 cap_limit: 40
4070 customer_4 ('customer_4', 'customer_5')
1450 customer_4 -13.01739515911258
resNode: customer_5 deliver_cap: 42.123325166987996 cap_limit: 40
4071 customer_1 ('customer_1', 'customer_3')
1451 customer_1 -4.4264541603660765
resNode: customer_3 deliver_cap: 45.4035201908716 cap_limit: 40
4072 customer_1 ('customer_1', 'depot_t')
1451 customer_1 -4.4264541603660765
resNode: depot_t deliver_cap: 25.307957985010553 cap_limit: 40
4073 customer_1 ('customer_1', 'customer_2')
1451 customer_1 -4.4264541603660765
resNode: customer_2 deliver_cap: 27.60868143819333 cap_limit: 40
4074 customer_1 ('customer_1', 'customer_4')
1451 customer_1 -4.4264541603660765
resNode: customer_4 deliver_cap: 44.941173913617 cap_limit: 40
4075 customer_1 ('customer_1', 'customer_5')
1451 customer_1 -4.4264541603660765
resNode: customer_5 deliver_cap: 34.6977876263217 cap_limit: 40
4076 customer_2 ('customer_2', 'customer_3')
1453 customer_2 -3.239144537511854
resNode: customer_3 deliver_cap: 39.93620441609261 cap_limit: 40
4077 customer_2 ('customer_2', 'customer_1')
1453 customer_2 -3.239144537511854
resNode: customer_1 deliver_cap: 31.237203485641615 cap_limit: 40
4078 customer_2 ('customer_2', 'depot_t')
1453 customer_2 -3.239144537511854
resNode: depot_t deliver_cap: 17.972447873345043 cap_limit: 40
4079 customer_2 ('customer_2', 'customer_4')
1453 customer_2 -3.239144537511854
resNode: customer_4 deliver_cap: 39.75187721945855 cap_limit: 40
4080 customer_2 ('customer_2', 'customer_5')
1453 customer_2 -3.239144537511854
resNode: customer_5 deliver_cap: 25.77770050358294 cap_limit: 40
4081 customer_4 ('customer_4', 'customer_3')
1454 customer_4 -4.564263446647961
resNode: customer_3 deliver_cap: 36.69996471341098 cap_limit: 40
4082 customer_4 ('customer_4', 'customer_1')
1454 customer_4 -4.564263446647961
resNode: customer_1 deliver_cap: 37.975201233512585 cap_limit: 40
4083 customer_4 ('customer_4', 'depot_t')
1454 customer_4 -4.564263446647961
resNode: depot_t deliver_cap: 24.879501000495832 cap_limit: 40
4084 customer_4 ('customer_4', 'customer_2')
1454 customer_4 -4.564263446647961
resNode: customer_2 deliver_cap: 28.25025198004379 cap_limit: 40
4085 customer_4 ('customer_4', 'customer_5')
1454 customer_4 -4.564263446647961
resNode: customer_5 deliver_cap: 31.987929857780355 cap_limit: 40
4086 customer_5 ('customer_5', 'customer_3')
1455 customer_5 -7.750146229624915
resNode: customer_3 deliver_cap: 44.48729233312221 cap_limit: 40
4087 customer_5 ('customer_5', 'customer_1')
1455 customer_5 -7.750146229624915
resNode: customer_1 deliver_cap: 37.96362314570145 cap_limit: 40
4088 customer_5 ('customer_5', 'depot_t')
1455 customer_5 -7.750146229624915
resNode: depot_t deliver_cap: 21.386623718530466 cap_limit: 40
4089 customer_5 ('customer_5', 'customer_2')
1455 customer_5 -7.750146229624915
resNode: customer_2 deliver_cap: 24.507883463652327 cap_limit: 40
4090 customer_5 ('customer_5', 'customer_4')
1455 customer_5 -7.750146229624915
resNode: customer_4 deliver_cap: 44.266099697161344 cap_limit: 40
4091 customer_3 ('customer_3', 'customer_1')
1456 customer_3 -5.969323548607867
resNode: customer_1 deliver_cap: 35.6110561054648 cap_limit: 40
4092 customer_3 ('customer_3', 'depot_t')
1456 customer_3 -5.969323548607867
resNode: depot_t deliver_cap: 24.139285890510884 cap_limit: 40
4093 customer_3 ('customer_3', 'customer_2')
1456 customer_3 -5.969323548607867
resNode: customer_2 deliver_cap: 27.60868143819333 cap_limit: 40
4094 customer_3 ('customer_3', 'customer_4')
1456 customer_3 -5.969323548607867
resNode: customer_4 deliver_cap: 36.6595765489063 cap_limit: 40
4095 customer_3 ('customer_3', 'customer_5')
1456 customer_3 -5.969323548607867
resNode: customer_5 deliver_cap: 32.917208032514836 cap_limit: 40
4096 customer_2 ('customer_2', 'customer_3')
1458 customer_2 -1.5032407530156802
resNode: customer_3 deliver_cap: 29.96228847346015 cap_limit: 40
4097 customer_2 ('customer_2', 'customer_1')
1458 customer_2 -1.5032407530156802
resNode: customer_1 deliver_cap: 21.937896319670752 cap_limit: 40
4098 customer_2 ('customer_2', 'depot_t')
1458 customer_2 -1.5032407530156802
resNode: depot_t deliver_cap: 11.746421141005282 cap_limit: 40
4099 customer_2 ('customer_2', 'customer_4')
1458 customer_2 -1.5032407530156802
resNode: customer_4 deliver_cap: 29.814826716152908 cap_limit: 40
4100 customer_2 ('customer_2', 'customer_5')
1458 customer_2 -1.5032407530156802
resNode: customer_5 deliver_cap: 18.63548534345241 cap_limit: 40
4101 customer_4 ('customer_4', 'customer_3')
1459 customer_4 -5.826806282646516
resNode: customer_3 deliver_cap: 36.381557468285756 cap_limit: 40
4102 customer_4 ('customer_4', 'customer_1')
1459 customer_4 -5.826806282646516
resNode: customer_1 deliver_cap: 35.01876381916469 cap_limit: 40
4103 customer_4 ('customer_4', 'depot_t')
1459 customer_4 -5.826806282646516
resNode: depot_t deliver_cap: 23.80023195385751 cap_limit: 40
4104 customer_4 ('customer_4', 'customer_2')
1459 customer_4 -5.826806282646516
resNode: customer_2 deliver_cap: 27.23880441638965 cap_limit: 40
4105 customer_4 ('customer_4', 'customer_5')
1459 customer_4 -5.826806282646516
resNode: customer_5 deliver_cap: 32.45486175526023 cap_limit: 40
4106 customer_5 ('customer_5', 'customer_3')
1460 customer_5 -6.274349494536316
resNode: customer_3 deliver_cap: 36.36997938047462 cap_limit: 40
4107 customer_5 ('customer_5', 'customer_1')
1460 customer_5 -6.274349494536316
resNode: customer_1 deliver_cap: 29.808687132192713 cap_limit: 40
4108 customer_5 ('customer_5', 'depot_t')
1460 customer_5 -6.274349494536316
resNode: depot_t deliver_cap: 16.28841534317429 cap_limit: 40
4109 customer_5 ('customer_5', 'customer_2')
1460 customer_5 -6.274349494536316
resNode: customer_2 deliver_cap: 19.044095386553415 cap_limit: 40
4110 customer_5 ('customer_5', 'customer_4')
1460 customer_5 -6.274349494536316
resNode: customer_4 deliver_cap: 36.18565218384057 cap_limit: 40
4111 customer_3 ('customer_3', 'customer_1')
1461 customer_3 -4.515109527545545
resNode: customer_1 deliver_cap: 38.25322031413313 cap_limit: 40
4112 customer_3 ('customer_3', 'depot_t')
1461 customer_3 -4.515109527545545
resNode: depot_t deliver_cap: 24.87950100049583 cap_limit: 40
4113 customer_3 ('customer_3', 'customer_2')
1461 customer_3 -4.515109527545545
resNode: customer_2 deliver_cap: 28.250251980043785 cap_limit: 40
4114 customer_3 ('customer_3', 'customer_4')
1461 customer_3 -4.515109527545545
resNode: customer_4 deliver_cap: 36.47877207745011 cap_limit: 40
4115 customer_3 ('customer_3', 'customer_5')
1461 customer_3 -4.515109527545545
resNode: customer_5 deliver_cap: 31.987929857780355 cap_limit: 40
4116 customer_1 ('customer_1', 'customer_3')
1462 customer_1 -4.327252230753232
resNode: customer_3 deliver_cap: 44.941173913617 cap_limit: 40
4117 customer_1 ('customer_1', 'depot_t')
1462 customer_1 -4.327252230753232
resNode: depot_t deliver_cap: 24.96890404835718 cap_limit: 40
4118 customer_1 ('customer_1', 'customer_2')
1462 customer_1 -4.327252230753232
resNode: customer_2 deliver_cap: 27.23880441638965 cap_limit: 40
4119 customer_1 ('customer_1', 'customer_4')
1462 customer_1 -4.327252230753232
resNode: customer_4 deliver_cap: 44.47882763636241 cap_limit: 40
4120 customer_1 ('customer_1', 'customer_5')
1462 customer_1 -4.327252230753232
resNode: customer_5 deliver_cap: 34.23544134906711 cap_limit: 40
4121 customer_2 ('customer_2', 'customer_3')
1464 customer_2 -3.2094473780541444
resNode: customer_3 deliver_cap: 39.75187721945855 cap_limit: 40
4122 customer_2 ('customer_2', 'customer_1')
1464 customer_2 -3.2094473780541444
resNode: customer_1 deliver_cap: 31.089741728334367 cap_limit: 40
4123 customer_2 ('customer_2', 'depot_t')
1464 customer_2 -3.2094473780541444
resNode: depot_t deliver_cap: 17.837274595813398 cap_limit: 40
4124 customer_2 ('customer_2', 'customer_4')
1464 customer_2 -3.2094473780541444
resNode: customer_4 deliver_cap: 39.56755002282449 cap_limit: 40
4125 customer_2 ('customer_2', 'customer_5')
1464 customer_2 -3.2094473780541444
resNode: customer_5 deliver_cap: 25.59337330694888 cap_limit: 40
4126 customer_5 ('customer_5', 'customer_3')
1465 customer_5 -7.67436727100869
resNode: customer_3 deliver_cap: 44.26609969716134 cap_limit: 40
4127 customer_5 ('customer_5', 'customer_1')
1465 customer_5 -7.67436727100869
resNode: customer_1 deliver_cap: 37.77929594906739 cap_limit: 40
4128 customer_5 ('customer_5', 'depot_t')
1465 customer_5 -7.67436727100869
resNode: depot_t deliver_cap: 21.21458500167201 cap_limit: 40
4129 customer_5 ('customer_5', 'customer_2')
1465 customer_5 -7.67436727100869
resNode: customer_2 deliver_cap: 24.32355626701827 cap_limit: 40
4130 customer_5 ('customer_5', 'customer_4')
1465 customer_5 -7.67436727100869
resNode: customer_4 deliver_cap: 44.044907061200476 cap_limit: 40
4131 customer_3 ('customer_3', 'customer_1')
1466 customer_3 -3.974545186289002
resNode: customer_1 deliver_cap: 34.510851797741665 cap_limit: 40
4132 customer_3 ('customer_3', 'depot_t')
1466 customer_3 -3.974545186289002
resNode: depot_t deliver_cap: 21.386623718530466 cap_limit: 40
4133 customer_3 ('customer_3', 'customer_2')
1466 customer_3 -3.974545186289002
resNode: customer_2 deliver_cap: 24.507883463652327 cap_limit: 40
4134 customer_3 ('customer_3', 'customer_4')
1466 customer_3 -3.974545186289002
resNode: customer_4 deliver_cap: 31.987929857780355 cap_limit: 40
4135 customer_3 ('customer_3', 'customer_5')
1466 customer_3 -3.974545186289002
resNode: customer_5 deliver_cap: 27.4970876381106 cap_limit: 40
4136 customer_1 ('customer_1', 'customer_3')
1467 customer_1 -3.097025575868593
resNode: customer_3 deliver_cap: 34.697787626321706 cap_limit: 40
4137 customer_1 ('customer_1', 'depot_t')
1467 customer_1 -3.097025575868593
resNode: depot_t deliver_cap: 17.457087437673962 cap_limit: 40
4138 customer_1 ('customer_1', 'customer_2')
1467 customer_1 -3.097025575868593
resNode: customer_2 deliver_cap: 19.044095386553415 cap_limit: 40
4139 customer_1 ('customer_1', 'customer_4')
1467 customer_1 -3.097025575868593
resNode: customer_4 deliver_cap: 34.235441349067116 cap_limit: 40
4140 customer_1 ('customer_1', 'customer_5')
1467 customer_1 -3.097025575868593
resNode: customer_5 deliver_cap: 23.99205506177181 cap_limit: 40
4141 customer_2 ('customer_2', 'customer_3')
1469 customer_2 -1.046523116024426
resNode: customer_3 deliver_cap: 25.77770050358293 cap_limit: 40
4142 customer_2 ('customer_2', 'customer_1')
1469 customer_2 -1.046523116024426
resNode: customer_1 deliver_cap: 19.91040035563387 cap_limit: 40
4143 customer_2 ('customer_2', 'depot_t')
1469 customer_2 -1.046523116024426
resNode: depot_t deliver_cap: 7.589545004171278 cap_limit: 40
4144 customer_2 ('customer_2', 'customer_4')
1469 customer_2 -1.046523116024426
resNode: customer_4 deliver_cap: 25.59337330694888 cap_limit: 40

4189 customer_5 ('customer_5', 'customer_2')
1480 customer_5 -11.498321014647342
resNode: customer_2 deliver_cap: 32.965624309136494 cap_limit: 40
4190 customer_5 ('customer_5', 'customer_4')
1480 customer_5 -11.498321014647342
resNode: customer_4 deliver_cap: 54.415388711742345 cap_limit: 40
4191 customer_3 ('customer_3', 'customer_1')
1481 customer_3 -9.799035860304015
resNode: customer_1 deliver_cap: 48.48502851361728 cap_limit: 40
4192 customer_3 ('customer_3', 'depot_t')
1481 customer_3 -9.799035860304015
resNode: depot_t deliver_cap: 34.42918865334771 cap_limit: 40
4193 customer_3 ('customer_3', 'customer_2')
1481 customer_3 -9.799035860304015
resNode: customer_2 deliver_cap: 38.48206017952794 cap_limit: 40
4194 customer_3 ('customer_3', 'customer_4')
1481 customer_3 -9.799035860304015
resNode: customer_4 deliver_cap: 48.756941916831096 cap_limit: 40
4195 customer_3 ('customer_3', 'customer_5')
1481 customer_3 -9.799035860304015
resNode: customer_5 deliver_cap: 44.26609969716134 cap_limit: 40
4196 customer_1 ('customer_1', 'customer_3')
1482 customer_1 -4.9828271724629865
resNode: customer_3 deliver_cap: 46.89138474839045 cap_limit: 40
4197 customer_1 ('customer_1', 'depot_t')
1482 customer_1 -4.9828271724629865
resNode: depot_t deliver_cap: 26.39905866052438 cap_limit: 40
4198 customer_1 ('customer_1', 'customer_2')
1482 customer_1 -4.9828271724629865
resNode: customer_2 deliver_cap: 28.798973084208413 cap_limit: 40
4199 customer_1 ('customer_1', 'customer_4')
1482 customer_1 -4.9828271724629865
resNode: customer_4 deliver_cap: 46.42903847113586 cap_limit: 40
4200 customer_1 ('customer_1', 'customer_5')
1482 customer_1 -4.9828271724629865
resNode: customer_5 deliver_cap: 36.18565218384056 cap_limit: 40
4201 customer_4 ('customer_4', 'customer_3')
1484 customer_4 -9.772410820790206
resNode: customer_3 deliver_cap: 48.756941916831096 cap_limit: 40
4202 customer_4 ('customer_4', 'customer_1')
1484 customer_4 -9.772410820790206
resNode: customer_1 deliver_cap: 48.022682236362684 cap_limit: 40
4203 customer_4 ('customer_4', 'depot_t')
1484 customer_4 -9.772410820790206
resNode: depot_t deliver_cap: 34.257149936489256 cap_limit: 40
4204 customer_4 ('customer_4', 'customer_2')
1484 customer_4 -9.772410820790206
resNode: customer_2 deliver_cap: 38.29773298289388 cap_limit: 40
4205 customer_4 ('customer_4', 'customer_5')
1484 customer_4 -9.772410820790206
resNode: customer_5 deliver_cap: 44.04490706120047 cap_limit: 40
4206 customer_5 ('customer_5', 'customer_3')
1485 customer_5 -7.842389504025082
resNode: customer_3 deliver_cap: 44.26609969716134 cap_limit: 40
4207 customer_5 ('customer_5', 'customer_1')
1485 customer_5 -7.842389504025082
resNode: customer_1 deliver_cap: 37.77929594906739 cap_limit: 40
4208 customer_5 ('customer_5', 'depot_t')
1485 customer_5 -7.842389504025082
resNode: depot_t deliver_cap: 21.214585001672013 cap_limit: 40
4209 customer_5 ('customer_5', 'customer_2')
1485 customer_5 -7.842389504025082
resNode: customer_2 deliver_cap: 24.32355626701827 cap_limit: 40
4210 customer_5 ('customer_5', 'customer_4')
1485 customer_5 -7.842389504025082
resNode: customer_4 deliver_cap: 44.044907061200476 cap_limit: 40
4211 customer_3 ('customer_3', 'customer_1')
1486 customer_3 -13.116453368640887
resNode: customer_1 deliver_cap: 54.74588125015182 cap_limit: 40
4212 customer_3 ('customer_3', 'depot_t')
1486 customer_3 -13.116453368640887
resNode: depot_t deliver_cap: 38.5616163570295 cap_limit: 40
4213 customer_3 ('customer_3', 'customer_2')
1486 customer_3 -13.116453368640887
resNode: customer_2 deliver_cap: 42.7423192492446 cap_limit: 40
4214 customer_3 ('customer_3', 'customer_4')
1486 customer_3 -13.116453368640887
resNode: customer_4 deliver_cap: 52.874253775749196 cap_limit: 40
4215 customer_3 ('customer_3', 'customer_5')
1486 customer_3 -13.116453368640887
resNode: customer_5 deliver_cap: 47.63493785280115 cap_limit: 40
4216 customer_1 ('customer_1', 'customer_3')
1487 customer_1 -9.505798757279248
resNode: customer_3 deliver_cap: 54.97020424444786 cap_limit: 40
4217 customer_1 ('customer_1', 'depot_t')
1487 customer_1 -9.505798757279248
resNode: depot_t deliver_cap: 32.588112800982614 cap_limit: 40
4218 customer_1 ('customer_1', 'customer_2')
1487 customer_1 -9.505798757279248
resNode: customer_2 deliver_cap: 34.915835143909945 cap_limit: 40
4219 customer_1 ('customer_1', 'customer_4')
1487 customer_1 -9.505798757279248
resNode: customer_4 deliver_cap: 54.415388711742345 cap_limit: 40
4220 customer_1 ('customer_1', 'customer_5')
1487 customer_1 -9.505798757279248
resNode: customer_5 deliver_cap: 42.12332516698798 cap_limit: 40
4221 customer_2 ('customer_2', 'customer_3')
1489 customer_2 -6.782509313332624
resNode: customer_3 deliver_cap: 44.26609969716134 cap_limit: 40
4222 customer_2 ('customer_2', 'customer_1')
1489 customer_2 -6.782509313332624
resNode: customer_1 deliver_cap: 35.99871635526051 cap_limit: 40
4223 customer_2 ('customer_2', 'depot_t')
1489 customer_2 -6.782509313332624
resNode: depot_t deliver_cap: 20.02942243107011 cap_limit: 40
4224 customer_2 ('customer_2', 'customer_4')
1489 customer_2 -6.782509313332624
resNode: customer_4 deliver_cap: 44.044907061200476 cap_limit: 40
4225 customer_2 ('customer_2', 'customer_5')
1489 customer_2 -6.782509313332624
resNode: customer_5 deliver_cap: 27.275895002149728 cap_limit: 40
4226 customer_4 ('customer_4', 'customer_3')
1490 customer_4 -13.080611969295376
resNode: customer_3 deliver_cap: 52.874253775749196 cap_limit: 40
4227 customer_4 ('customer_4', 'customer_1')
1490 customer_4 -13.080611969295376
resNode: customer_1 deliver_cap: 54.1910657174463 cap_limit: 40
4228 customer_4 ('customer_4', 'depot_t')
1490 customer_4 -13.080611969295376
resNode: depot_t deliver_cap: 38.35271220084424 cap_limit: 40
4229 customer_4 ('customer_4', 'customer_2')
1490 customer_4 -13.080611969295376
resNode: customer_2 deliver_cap: 42.521126613283734 cap_limit: 40
4230 customer_4 ('customer_4', 'customer_5')
1490 customer_4 -13.080611969295376
resNode: customer_5 deliver_cap: 47.376879777513466 cap_limit: 40
4231 customer_1 ('customer_1', 'customer_3')
1497 customer_1 -8.321728694197585
resNode: customer_3 deliver_cap: 59.2274050302785 cap_limit: 40
4232 customer_1 ('customer_1', 'depot_t')
1497 customer_1 -8.321728694197585
resNode: depot_t deliver_cap: 35.445473533908945 cap_limit: 40
4233 customer_1 ('customer_1', 'customer_2')
1497 customer_1 -8.321728694197585
resNode: customer_2 deliver_cap: 38.66778930971885 cap_limit: 40
4234 customer_1 ('customer_1', 'customer_4')
1497 customer_1 -8.321728694197585
resNode: customer_4 deliver_cap: 58.765058753023894 cap_limit: 40
4235 customer_1 ('customer_1', 'customer_5')
1497 customer_1 -8.321728694197585
resNode: customer_5 deliver_cap: 48.52167246572859 cap_limit: 40
4236 customer_5 ('customer_5', 'customer_3')
1500 customer_5 -14.265296096231687
resNode: customer_3 deliver_cap: 59.06932403542698 cap_limit: 40
4237 customer_5 ('customer_5', 'customer_1')
1500 customer_5 -14.265296096231687
resNode: customer_1 deliver_cap: 50.11531623095542 cap_limit: 40
4238 customer_5 ('customer_5', 'depot_t')
1500 customer_5 -14.265296096231687
resNode: depot_t deliver_cap: 32.72820393143417 cap_limit: 40
4239 customer_5 ('customer_5', 'customer_2')
1500 customer_5 -14.265296096231687
resNode: customer_2 deliver_cap: 36.659576548906294 cap_limit: 40
4240 customer_5 ('customer_5', 'customer_4')
1500 customer_5 -14.265296096231687
resNode: customer_4 deliver_cap: 58.84813139946612 cap_limit: 40
4241 customer_2 ('customer_2', 'customer_3')
1509 customer_2 -14.214411008696452
resNode: customer_3 deliver_cap: 61.20601954799521 cap_limit: 40
4242 customer_2 ('customer_2', 'customer_1')
1509 customer_2 -14.214411008696452
resNode: customer_1 deliver_cap: 50.115316230955415 cap_limit: 40
4243 customer_2 ('customer_2', 'depot_t')
1509 customer_2 -14.214411008696452
resNode: depot_t deliver_cap: 33.204915648385345 cap_limit: 40
4244 customer_2 ('customer_2', 'customer_4')
1509 customer_2 -14.214411008696452
resNode: customer_4 deliver_cap: 60.98482691203435 cap_limit: 40
4245 customer_2 ('customer_2', 'customer_5')
1509 customer_2 -14.214411008696452
resNode: customer_5 deliver_cap: 44.2158148529836 cap_limit: 40
4246 customer_2 ('customer_2', 'customer_3')
1513 customer_2 -12.70680949465288
resNode: customer_3 deliver_cap: 67.4921196957203 cap_limit: 40
4247 customer_2 ('customer_2', 'customer_1')
1513 customer_2 -12.70680949465288
resNode: customer_1 deliver_cap: 55.353733020726324 cap_limit: 40
4248 customer_2 ('customer_2', 'depot_t')
1513 customer_2 -12.70680949465288
resNode: depot_t deliver_cap: 38.094104652171524 cap_limit: 40
4249 customer_2 ('customer_2', 'customer_4')
1513 customer_2 -12.70680949465288
resNode: customer_4 deliver_cap: 67.27092705975943 cap_limit: 40
4250 customer_2 ('customer_2', 'customer_5')
1513 customer_2 -12.70680949465288
resNode: customer_5 deliver_cap: 50.501915000708685 cap_limit: 40
4251 customer_2 ('customer_2', 'customer_3')
1518 customer_2 -6.769931353024759
resNode: customer_3 deliver_cap: 53.760089255499494 cap_limit: 40
4252 customer_2 ('customer_2', 'customer_1')
1518 customer_2 -6.769931353024759
resNode: customer_1 deliver_cap: 42.29631135716712 cap_limit: 40
4253 customer_2 ('customer_2', 'depot_t')
1518 customer_2 -6.769931353024759
resNode: depot_t deliver_cap: 28.109963422243418 cap_limit: 40
4254 customer_2 ('customer_2', 'customer_4')
1518 customer_2 -6.769931353024759
resNode: customer_4 deliver_cap: 53.575762058865436 cap_limit: 40
4255 customer_2 ('customer_2', 'customer_5')
1518 customer_2 -6.769931353024759
resNode: customer_5 deliver_cap: 39.601585342989814 cap_limit: 40
4256 customer_5 ('customer_5', 'customer_3')
1520 customer_5 -15.627194051892978
resNode: customer_3 deliver_cap: 63.21264965297871 cap_limit: 40
4257 customer_5 ('customer_5', 'customer_1')
1520 customer_5 -15.627194051892978
resNode: customer_1 deliver_cap: 53.568087578915204 cap_limit: 40
4258 customer_5 ('customer_5', 'depot_t')
1520 customer_5 -15.627194051892978
resNode: depot_t deliver_cap: 35.9507905228633 cap_limit: 40
4259 customer_5 ('customer_5', 'customer_2')
1520 customer_5 -15.627194051892978
resNode: customer_2 deliver_cap: 40.112347896866076 cap_limit: 40
4260 customer_5 ('customer_5', 'customer_4')
1520 customer_5 -15.627194051892978
resNode: customer_4 deliver_cap: 62.99145701701785 cap_limit: 40
4261 customer_2 ('customer_2', 'customer_3')
1524 customer_2 -12.66789597536347
resNode: customer_3 deliver_cap: 67.27092705975943 cap_limit: 40
4262 customer_2 ('customer_2', 'customer_1')
1524 customer_2 -12.66789597536347
resNode: customer_1 deliver_cap: 55.16940582409227 cap_limit: 40
4263 customer_2 ('customer_2', 'depot_t')
1524 customer_2 -12.66789597536347
resNode: depot_t deliver_cap: 37.92206593531307 cap_limit: 40
4264 customer_2 ('customer_2', 'customer_4')
1524 customer_2 -12.66789597536347
resNode: customer_4 deliver_cap: 67.04973442379857 cap_limit: 40
4265 customer_2 ('customer_2', 'customer_5')
1524 customer_2 -12.66789597536347
resNode: customer_5 deliver_cap: 50.28072236474782 cap_limit: 40
4266 customer_1 ('customer_1', 'customer_3')
1527 customer_1 -12.529552321486598
resNode: customer_3 deliver_cap: 61.20601954799522 cap_limit: 40
4267 customer_1 ('customer_1', 'depot_t')
1527 customer_1 -12.529552321486598
resNode: depot_t deliver_cap: 37.43819137040834 cap_limit: 40
4268 customer_1 ('customer_1', 'customer_2')
1527 customer_1 -12.529552321486598
resNode: customer_2 deliver_cap: 40.11234789686608 cap_limit: 40
4269 customer_1 ('customer_1', 'customer_4')
1527 customer_1 -12.529552321486598
resNode: customer_4 deliver_cap: 60.65120401528971 cap_limit: 40
4270 customer_1 ('customer_1', 'customer_5')
1527 customer_1 -12.529552321486598
resNode: customer_5 deliver_cap: 48.359140470535344 cap_limit: 40
4271 customer_2 ('customer_2', 'customer_3')
1529 customer_2 -9.806262877539973
resNode: customer_3 deliver_cap: 50.50191500070869 cap_limit: 40
4272 customer_2 ('customer_2', 'customer_1')
1529 customer_2 -9.806262877539973
resNode: customer_1 deliver_cap: 41.19522910821665 cap_limit: 40
4273 customer_2 ('customer_2', 'depot_t')
1529 customer_2 -9.806262877539973
resNode: depot_t deliver_cap: 24.879501000495832 cap_limit: 40
4274 customer_2 ('customer_2', 'customer_4')
1529 customer_2 -9.806262877539973
resNode: customer_4 deliver_cap: 50.28072236474782 cap_limit: 40
4275 customer_2 ('customer_2', 'customer_5')
1529 customer_2 -9.806262877539973
resNode: customer_5 deliver_cap: 33.511710305697086 cap_limit: 40
4276 customer_2 ('customer_2', 'customer_3')
1533 customer_2 -8.435351549814817
resNode: customer_3 deliver_cap: 65.6467456281235 cap_limit: 40
4277 customer_2 ('customer_2', 'customer_1')
1533 customer_2 -8.435351549814817
resNode: customer_1 deliver_cap: 55.20099903897143 cap_limit: 40
4278 customer_2 ('customer_2', 'depot_t')
1533 customer_2 -8.435351549814817
resNode: depot_t deliver_cap: 35.65717319095337 cap_limit: 40
4279 customer_2 ('customer_2', 'customer_4')
1533 customer_2 -8.435351549814817
resNode: customer_4 deliver_cap: 65.38868755283582 cap_limit: 40
4280 customer_2 ('customer_2', 'customer_5')
1533 customer_2 -8.435351549814817
resNode: customer_5 deliver_cap: 45.82484015060995 cap_limit: 40
4281 customer_5 ('customer_5', 'customer_3')
1535 customer_5 -14.525570909261242
resNode: customer_3 deliver_cap: 70.44331485817497 cap_limit: 40
4282 customer_5 ('customer_5', 'customer_1')
1535 customer_5 -14.525570909261242
resNode: customer_1 deliver_cap: 62.88513184957587 cap_limit: 40
4283 customer_5 ('customer_5', 'depot_t')
1535 customer_5 -14.525570909261242
resNode: depot_t deliver_cap: 39.82475716513291 cap_limit: 40
4284 customer_5 ('customer_5', 'customer_2')
1535 customer_5 -14.525570909261242
resNode: customer_2 deliver_cap: 44.04709629470711 cap_limit: 40
4285 customer_5 ('customer_5', 'customer_4')
1535 customer_5 -14.525570909261242
resNode: customer_4 deliver_cap: 70.14839134356048 cap_limit: 40
4286 customer_2 ('customer_2', 'customer_3')
1538 customer_2 -7.74911703942978
resNode: customer_3 deliver_cap: 63.22654335835208 cap_limit: 40
4287 customer_2 ('customer_2', 'customer_1')
1538 customer_2 -7.74911703942978
resNode: customer_1 deliver_cap: 51.79908607291948 cap_limit: 40
4288 customer_2 ('customer_2', 'depot_t')
1538 customer_2 -7.74911703942978
resNode: depot_t deliver_cap: 34.7764341675518 cap_limit: 40
4289 customer_2 ('customer_2', 'customer_4')
1538 customer_2 -7.74911703942978
resNode: customer_4 deliver_cap: 63.00535072239121 cap_limit: 40
4290 customer_2 ('customer_2', 'customer_5')
1538 customer_2 -7.74911703942978
resNode: customer_5 deliver_cap: 46.23633866334047 cap_limit: 40
4291 customer_1 ('customer_1', 'customer_3')
1542 customer_1 -8.544888581177796
resNode: customer_3 deliver_cap: 63.56016625509674 cap_limit: 40
4292 customer_1 ('customer_1', 'depot_t')
1542 customer_1 -8.544888581177796
resNode: depot_t deliver_cap: 39.269194364820635 cap_limit: 40
4293 customer_1 ('customer_1', 'customer_2')
1542 customer_1 -8.544888581177796
resNode: customer_2 deliver_cap: 42.07413681945068 cap_limit: 40
4294 customer_1 ('customer_1', 'customer_4')
1542 customer_1 -8.544888581177796
resNode: customer_4 deliver_cap: 63.00535072239123 cap_limit: 40
4295 customer_1 ('customer_1', 'customer_5')
1542 customer_1 -8.544888581177796
resNode: customer_5 deliver_cap: 50.713287177636865 cap_limit: 40
4296 customer_5 ('customer_5', 'customer_3')
1545 customer_5 -12.259865836113976
resNode: customer_3 deliver_cap: 60.14937162988778 cap_limit: 40
4297 customer_5 ('customer_5', 'customer_1')
1545 customer_5 -12.259865836113976
resNode: customer_1 deliver_cap: 52.62565969590905 cap_limit: 40
4298 customer_5 ('customer_5', 'depot_t')
1545 customer_5 -12.259865836113976
resNode: depot_t deliver_cap: 32.64604402811248 cap_limit: 40
4299 customer_5 ('customer_5', 'customer_2')
1545 customer_5 -12.259865836113976
resNode: customer_2 deliver_cap: 36.47877207745011 cap_limit: 40
4300 customer_5 ('customer_5', 'customer_4')
1545 customer_5 -12.259865836113976
resNode: customer_4 deliver_cap: 59.891313554600096 cap_limit: 40
4301 customer_2 ('customer_2', 'customer_3')
1549 customer_2 -11.136494793424985
resNode: customer_3 deliver_cap: 60.14937162988778 cap_limit: 40
4302 customer_2 ('customer_2', 'customer_1')
1549 customer_2 -11.136494793424985
resNode: customer_1 deliver_cap: 50.488964183340805 cap_limit: 40
4303 customer_2 ('customer_2', 'depot_t')
1549 customer_2 -11.136494793424985
resNode: depot_t deliver_cap: 31.20691804952445 cap_limit: 40
4304 customer_2 ('customer_2', 'customer_4')
1549 customer_2 -11.136494793424985
resNode: customer_4 deliver_cap: 59.891313554600096 cap_limit: 40
4305 customer_2 ('customer_2', 'customer_5')
1549 customer_2 -11.136494793424985
resNode: customer_5 deliver_cap: 40.327466152374235 cap_limit: 40
4306 customer_2 ('customer_2', 'customer_3')
1558 customer_2 -11.803973844033992
resNode: customer_3 deliver_cap: 63.21264965297871 cap_limit: 40
4307 customer_2 ('customer_2', 'customer_1')
1558 customer_2 -11.803973844033992
resNode: customer_1 deliver_cap: 51.787507985108334 cap_limit: 40
4308 customer_2 ('customer_2', 'depot_t')
1558 customer_2 -11.803973844033992
resNode: depot_t deliver_cap: 34.765627952261404 cap_limit: 40
4309 customer_2 ('customer_2', 'customer_4')
1558 customer_2 -11.803973844033992
resNode: customer_4 deliver_cap: 62.99145701701785 cap_limit: 40
4310 customer_2 ('customer_2', 'customer_5')
1558 customer_2 -11.803973844033992
resNode: customer_5 deliver_cap: 46.2224449579671 cap_limit: 40
4311 customer_1 ('customer_1', 'customer_3')
1562 customer_1 -11.231788895302554
resNode: customer_3 deliver_cap: 59.06932403542698 cap_limit: 40
4312 customer_1 ('customer_1', 'depot_t')
1562 customer_1 -11.231788895302554
resNode: depot_t deliver_cap: 35.776317082855265 cap_limit: 40
4313 customer_1 ('customer_1', 'customer_2')
1562 customer_1 -11.231788895302554
resNode: customer_2 deliver_cap: 38.331768303059214 cap_limit: 40
4314 customer_1 ('customer_1', 'customer_4')
1562 customer_1 -11.231788895302554
resNode: customer_4 deliver_cap: 58.51450850272146 cap_limit: 40
4315 customer_1 ('customer_1', 'customer_5')
1562 customer_1 -11.231788895302554
resNode: customer_5 deliver_cap: 46.2224449579671 cap_limit: 40
4316 customer_5 ('customer_5', 'customer_3')
1565 customer_5 -14.01117402114087
resNode: customer_3 deliver_cap: 54.91005570693974 cap_limit: 40
4317 customer_5 ('customer_5', 'customer_1')
1565 customer_5 -14.01117402114087
resNode: customer_1 deliver_cap: 48.1348174762393 cap_limit: 40
4318 customer_5 ('customer_5', 'depot_t')
1565 customer_5 -14.01117402114087
resNode: depot_t deliver_cap: 28.404693042868825 cap_limit: 40
4319 customer_5 ('customer_5', 'customer_2')
1565 customer_5 -14.01117402114087
resNode: customer_2 deliver_cap: 31.987929857780358 cap_limit: 40
4320 customer_5 ('customer_5', 'customer_4')
1565 customer_5 -14.01117402114087
resNode: customer_4 deliver_cap: 54.65199763165206 cap_limit: 40
4321 customer_2 ('customer_2', 'customer_3')
1573 customer_2 -15.072755808904615
resNode: customer_3 deliver_cap: 67.5090023949892 cap_limit: 40
4322 customer_2 ('customer_2', 'customer_1')
1573 customer_2 -15.072755808904615
resNode: customer_1 deliver_cap: 53.295441868758886 cap_limit: 40
4323 customer_2 ('customer_2', 'depot_t')
1573 customer_2 -15.072755808904615
resNode: depot_t deliver_cap: 38.192499724535864 cap_limit: 40
4324 customer_2 ('customer_2', 'customer_4')
1573 customer_2 -15.072755808904615
resNode: customer_4 deliver_cap: 67.32467519835514 cap_limit: 40
4325 customer_2 ('customer_2', 'customer_5')
1573 customer_2 -15.072755808904615
resNode: customer_5 deliver_cap: 53.350498482479516 cap_limit: 40
4326 customer_2 ('customer_2', 'customer_3')
1589 customer_2 -22.493890945645568
resNode: customer_3 deliver_cap: 69.00724087307982 cap_limit: 40
4327 customer_2 ('customer_2', 'customer_1')

4340 customer_2 ('customer_2', 'customer_5')
1598 customer_2 -7.46730697333876
resNode: customer_5 deliver_cap: 36.319871106746476 cap_limit: 40
4341 customer_5 ('customer_5', 'customer_3')
1600 customer_5 -17.764786265888795
resNode: customer_3 deliver_cap: 58.47546158459221 cap_limit: 40
4342 customer_5 ('customer_5', 'customer_1')
1600 customer_5 -17.764786265888795
resNode: customer_1 deliver_cap: 47.49307289548679 cap_limit: 40
4343 customer_5 ('customer_5', 'depot_t')
1600 customer_5 -17.764786265888795
resNode: depot_t deliver_cap: 32.49910229286052 cap_limit: 40
4344 customer_5 ('customer_5', 'customer_2')
1600 customer_5 -17.764786265888795
resNode: customer_2 deliver_cap: 36.72848114984748 cap_limit: 40
4345 customer_5 ('customer_5', 'customer_4')
1600 customer_5 -17.764786265888795
resNode: customer_4 deliver_cap: 58.29113438795816 cap_limit: 40
4346 customer_2 ('customer_2', 'customer_3')
1604 customer_2 -14.699884149406623
resNode: customer_3 deliver_cap: 61.85735942357614 cap_limit: 40
4347 customer_2 ('customer_2', 'customer_1')
1604 customer_2 -14.699884149406623
resNode: customer_1 deliver_cap: 48.77412749162844 cap_limit: 40
4348 customer_2 ('customer_2', 'depot_t')
1604 customer_2 -14.699884149406623
resNode: depot_t deliver_cap: 34.04796154549963 cap_limit: 40
4349 customer_2 ('customer_2', 'customer_4')
1604 customer_2 -14.699884149406623
resNode: customer_4 deliver_cap: 61.673032226942084 cap_limit: 40
4350 customer_2 ('customer_2', 'customer_5')
1604 customer_2 -14.699884149406623
resNode: customer_5 deliver_cap: 47.69885551106646 cap_limit: 40
4351 customer_1 ('customer_1', 'customer_3')
1607 customer_1 -14.587462347221074
resNode: customer_3 deliver_cap: 56.8032698304393 cap_limit: 40
4352 customer_1 ('customer_1', 'depot_t')
1607 customer_1 -14.587462347221074
resNode: depot_t deliver_cap: 33.6677743873602 cap_limit: 40
4353 customer_1 ('customer_1', 'customer_2')
1607 customer_1 -14.587462347221074
resNode: customer_2 deliver_cap: 36.72848114984749 cap_limit: 40
4354 customer_1 ('customer_1', 'customer_4')
1607 customer_1 -14.587462347221074
resNode: customer_4 deliver_cap: 56.34092355318471 cap_limit: 40
4355 customer_1 ('customer_1', 'customer_5')
1607 customer_1 -14.587462347221074
resNode: customer_5 deliver_cap: 46.0975372658894 cap_limit: 40
4356 customer_2 ('customer_2', 'customer_3')
1609 customer_2 -12.536959887376902
resNode: customer_3 deliver_cap: 47.88318270770052 cap_limit: 40
4357 customer_2 ('customer_2', 'customer_1')
1609 customer_2 -12.536959887376902
resNode: customer_1 deliver_cap: 37.59478611892794 cap_limit: 40
4358 customer_2 ('customer_2', 'depot_t')
1609 customer_2 -12.536959887376902
resNode: depot_t deliver_cap: 23.800231953857505 cap_limit: 40
4359 customer_2 ('customer_2', 'customer_4')
1609 customer_2 -12.536959887376902
resNode: customer_4 deliver_cap: 47.69885551106646 cap_limit: 40
4360 customer_2 ('customer_2', 'customer_5')
1609 customer_2 -12.536959887376902
resNode: customer_5 deliver_cap: 33.72467879519084 cap_limit: 40
4361 customer_2 ('customer_2', 'customer_3')
1618 customer_2 -14.78055299711282
resNode: customer_3 deliver_cap: 66.76863703711406 cap_limit: 40
4362 customer_2 ('customer_2', 'customer_1')
1618 customer_2 -14.78055299711282
resNode: customer_1 deliver_cap: 52.703149582458764 cap_limit: 40
4363 customer_2 ('customer_2', 'depot_t')
1618 customer_2 -14.78055299711282
resNode: depot_t deliver_cap: 37.64956512876076 cap_limit: 40
4364 customer_2 ('customer_2', 'customer_4')
1618 customer_2 -14.78055299711282
resNode: customer_4 deliver_cap: 66.58430984048 cap_limit: 40
4365 customer_2 ('customer_2', 'customer_5')
1618 customer_2 -14.78055299711282
resNode: customer_5 deliver_cap: 52.610133124604374 cap_limit: 40
4366 customer_2 ('customer_2', 'customer_3')
1629 customer_2 -22.174140940069957
resNode: customer_3 deliver_cap: 68.4524253403743 cap_limit: 40
4367 customer_2 ('customer_2', 'customer_1')
1629 customer_2 -22.174140940069957
resNode: customer_1 deliver_cap: 56.153987724604654 cap_limit: 40
4368 customer_2 ('customer_2', 'depot_t')
1629 customer_2 -22.174140940069957
resNode: depot_t deliver_cap: 38.84100904245797 cap_limit: 40
4369 customer_2 ('customer_2', 'customer_4')
1629 customer_2 -22.174140940069957
resNode: customer_4 deliver_cap: 68.23123270441343 cap_limit: 40
4370 customer_2 ('customer_2', 'customer_5')
1629 customer_2 -22.174140940069957
resNode: customer_5 deliver_cap: 51.462220645362684 cap_limit: 40
4371 customer_2 ('customer_2', 'customer_3')
1638 customer_2 -15.04372833974701
resNode: customer_3 deliver_cap: 60.25604117839907 cap_limit: 40
4372 customer_2 ('customer_2', 'customer_1')
1638 customer_2 -15.04372833974701
resNode: customer_1 deliver_cap: 47.49307289548679 cap_limit: 40
4373 customer_2 ('customer_2', 'depot_t')
1638 customer_2 -15.04372833974701
resNode: depot_t deliver_cap: 32.873661499036444 cap_limit: 40
4374 customer_2 ('customer_2', 'customer_4')
1638 customer_2 -15.04372833974701
resNode: customer_4 deliver_cap: 60.071713981765015 cap_limit: 40
4375 customer_2 ('customer_2', 'customer_5')
1638 customer_2 -15.04372833974701
resNode: customer_5 deliver_cap: 46.0975372658894 cap_limit: 40
4376 customer_1 ('customer_1', 'customer_3')
1642 customer_1 -14.417399330448045
resNode: customer_3 deliver_cap: 56.8032698304393 cap_limit: 40
4377 customer_1 ('customer_1', 'depot_t')
1642 customer_1 -14.417399330448045
resNode: depot_t deliver_cap: 33.6677743873602 cap_limit: 40
4378 customer_1 ('customer_1', 'customer_2')
1642 customer_1 -14.417399330448045
resNode: customer_2 deliver_cap: 36.72848114984749 cap_limit: 40
4379 customer_1 ('customer_1', 'customer_4')
1642 customer_1 -14.417399330448045
resNode: customer_4 deliver_cap: 56.34092355318471 cap_limit: 40
4380 customer_1 ('customer_1', 'customer_5')
1642 customer_1 -14.417399330448045
resNode: customer_5 deliver_cap: 46.0975372658894 cap_limit: 40
4381 customer_5 ('customer_5', 'customer_3')
1645 customer_5 -19.754932932522347
resNode: customer_3 deliver_cap: 56.16036179561995 cap_limit: 40
4382 customer_5 ('customer_5', 'customer_1')
1645 customer_5 -19.754932932522347
resNode: customer_1 deliver_cap: 47.69118103111622 cap_limit: 40
4383 customer_5 ('customer_5', 'depot_t')
1645 customer_5 -19.754932932522347
resNode: depot_t deliver_cap: 30.465677744917592 cap_limit: 40
4384 customer_5 ('customer_5', 'customer_2')
1645 customer_5 -19.754932932522347
resNode: customer_2 deliver_cap: 34.2354413490671 cap_limit: 40
4385 customer_5 ('customer_5', 'customer_4')
1645 customer_5 -19.754932932522347
resNode: customer_4 deliver_cap: 55.93916915965907 cap_limit: 40
4386 customer_2 ('customer_2', 'customer_3')
1653 customer_2 -12.710768581082375
resNode: customer_3 deliver_cap: 62.31970570083075 cap_limit: 40
4387 customer_2 ('customer_2', 'customer_1')
1653 customer_2 -12.710768581082375
resNode: customer_1 deliver_cap: 49.144004513432115 cap_limit: 40
4388 customer_2 ('customer_2', 'depot_t')
1653 customer_2 -12.710768581082375
resNode: depot_t deliver_cap: 34.387015482153004 cap_limit: 40
4389 customer_2 ('customer_2', 'customer_4')
1653 customer_2 -12.710768581082375
resNode: customer_4 deliver_cap: 62.13537850419669 cap_limit: 40
4390 customer_2 ('customer_2', 'customer_5')
1653 customer_2 -12.710768581082375
resNode: customer_5 deliver_cap: 48.161201788321065 cap_limit: 40
4391 customer_1 ('customer_1', 'customer_3')
1657 customer_1 -13.177817165304006
resNode: customer_3 deliver_cap: 62.31970570083075 cap_limit: 40
4392 customer_1 ('customer_1', 'depot_t')
1657 customer_1 -13.177817165304006
resNode: depot_t deliver_cap: 37.71316069231393 cap_limit: 40
4393 customer_1 ('customer_1', 'customer_2')
1657 customer_1 -13.177817165304006
resNode: customer_2 deliver_cap: 41.14162984616065 cap_limit: 40
4394 customer_1 ('customer_1', 'customer_4')
1657 customer_1 -13.177817165304006
resNode: customer_4 deliver_cap: 61.85735942357614 cap_limit: 40
4395 customer_1 ('customer_1', 'customer_5')
1657 customer_1 -13.177817165304006
resNode: customer_5 deliver_cap: 51.61397313628084 cap_limit: 40
4396 customer_5 ('customer_5', 'customer_3')
1660 customer_5 -19.89445973497617
resNode: customer_3 deliver_cap: 62.78008484008968 cap_limit: 40
4397 customer_5 ('customer_5', 'customer_1')
1660 customer_5 -19.89445973497617
resNode: customer_1 deliver_cap: 53.20761690150767 cap_limit: 40
4398 customer_5 ('customer_5', 'depot_t')
1660 customer_5 -19.89445973497617
resNode: depot_t deliver_cap: 35.614351223949605 cap_limit: 40
4399 customer_5 ('customer_5', 'customer_2')
1660 customer_5 -19.89445973497617
resNode: customer_2 deliver_cap: 39.75187721945854 cap_limit: 40
4400 customer_5 ('customer_5', 'customer_4')
1660 customer_5 -19.89445973497617
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
4401 customer_2 ('customer_2', 'customer_3')
1664 customer_2 -15.898187995732856
resNode: customer_3 deliver_cap: 67.27092705975943 cap_limit: 40
4402 customer_2 ('customer_2', 'customer_1')
1664 customer_2 -15.898187995732856
resNode: customer_1 deliver_cap: 55.16940582409227 cap_limit: 40
4403 customer_2 ('customer_2', 'depot_t')
1664 customer_2 -15.898187995732856
resNode: depot_t deliver_cap: 37.92206593531307 cap_limit: 40
4404 customer_2 ('customer_2', 'customer_4')
1664 customer_2 -15.898187995732856
resNode: customer_4 deliver_cap: 67.04973442379857 cap_limit: 40
4405 customer_2 ('customer_2', 'customer_5')
1664 customer_2 -15.898187995732856
resNode: customer_5 deliver_cap: 50.28072236474782 cap_limit: 40
4406 customer_2 ('customer_2', 'customer_3')
1669 customer_2 -18.834579544283713
resNode: customer_3 deliver_cap: 62.78008484008968 cap_limit: 40
4407 customer_2 ('customer_2', 'customer_1')
1669 customer_2 -18.834579544283713
resNode: customer_1 deliver_cap: 51.42703730770081 cap_limit: 40
4408 customer_2 ('customer_2', 'depot_t')
1669 customer_2 -18.834579544283713
resNode: depot_t deliver_cap: 34.42918865334771 cap_limit: 40
4409 customer_2 ('customer_2', 'customer_4')
1669 customer_2 -18.834579544283713
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
4410 customer_2 ('customer_2', 'customer_5')
1669 customer_2 -18.834579544283713
resNode: customer_5 deliver_cap: 45.789880145078065 cap_limit: 40
4411 customer_2 ('customer_2', 'customer_3')
1673 customer_2 -14.545805992949084
resNode: customer_3 deliver_cap: 62.31970570083074 cap_limit: 40
4412 customer_2 ('customer_2', 'customer_1')
1673 customer_2 -14.545805992949084
resNode: customer_1 deliver_cap: 49.144004513432115 cap_limit: 40
4413 customer_2 ('customer_2', 'depot_t')
1673 customer_2 -14.545805992949084
resNode: depot_t deliver_cap: 34.387015482153 cap_limit: 40
4414 customer_2 ('customer_2', 'customer_4')
1673 customer_2 -14.545805992949084
resNode: customer_4 deliver_cap: 62.13537850419668 cap_limit: 40
4415 customer_2 ('customer_2', 'customer_5')
1673 customer_2 -14.545805992949084
resNode: customer_5 deliver_cap: 48.16120178832106 cap_limit: 40
4416 customer_3 ('customer_3', 'customer_1')
1676 customer_3 -15.462260810456705
resNode: customer_1 deliver_cap: 49.144004513432115 cap_limit: 40
4417 customer_3 ('customer_3', 'depot_t')
1676 customer_3 -15.462260810456705
resNode: depot_t deliver_cap: 36.54448859781425 cap_limit: 40
4418 customer_3 ('customer_3', 'customer_2')
1676 customer_3 -15.462260810456705
resNode: customer_2 deliver_cap: 41.14162984616064 cap_limit: 40
4419 customer_3 ('customer_3', 'customer_4')
1676 customer_3 -15.462260810456705
resNode: customer_4 deliver_cap: 53.575762058865436 cap_limit: 40
4420 customer_3 ('customer_3', 'customer_5')
1676 customer_3 -15.462260810456705
resNode: customer_5 deliver_cap: 49.83339354247398 cap_limit: 40
4421 customer_1 ('customer_1', 'customer_3')
1677 customer_1 -7.454292843524492
resNode: customer_3 deliver_cap: 47.869089501250656 cap_limit: 40
4422 customer_1 ('customer_1', 'depot_t')
1677 customer_1 -7.454292843524492
resNode: depot_t deliver_cap: 26.10330319116447 cap_limit: 40
4423 customer_1 ('customer_1', 'customer_2')
1677 customer_1 -7.454292843524492
resNode: customer_2 deliver_cap: 29.36621609006003 cap_limit: 40
4424 customer_1 ('customer_1', 'customer_4')
1677 customer_1 -7.454292843524492
resNode: customer_4 deliver_cap: 47.49921247944698 cap_limit: 40
4425 customer_1 ('customer_1', 'customer_5')
1677 customer_1 -7.454292843524492
resNode: customer_5 deliver_cap: 39.30450344961074 cap_limit: 40
4426 customer_4 ('customer_4', 'customer_3')
1679 customer_4 -15.4448521307746
resNode: customer_3 deliver_cap: 53.575762058865436 cap_limit: 40
4427 customer_4 ('customer_4', 'customer_1')
1679 customer_4 -15.4448521307746
resNode: customer_1 deliver_cap: 48.77412749162844 cap_limit: 40
4428 customer_4 ('customer_4', 'depot_t')
1679 customer_4 -15.4448521307746
resNode: depot_t deliver_cap: 36.4093153202826 cap_limit: 40
4429 customer_4 ('customer_4', 'customer_2')
1679 customer_4 -15.4448521307746
resNode: customer_2 deliver_cap: 40.99416808885339 cap_limit: 40
4430 customer_4 ('customer_4', 'customer_5')
1679 customer_4 -15.4448521307746
resNode: customer_5 deliver_cap: 49.64906634583991 cap_limit: 40
4431 customer_5 ('customer_5', 'customer_3')
1680 customer_5 -14.213539649803256
resNode: customer_3 deliver_cap: 49.83339354247398 cap_limit: 40
4432 customer_5 ('customer_5', 'customer_1')
1680 customer_5 -14.213539649803256
resNode: customer_1 deliver_cap: 40.579418461792194 cap_limit: 40
4433 customer_5 ('customer_5', 'depot_t')
1680 customer_5 -14.213539649803256
resNode: depot_t deliver_cap: 26.161585728640485 cap_limit: 40
4434 customer_5 ('customer_5', 'customer_2')
1680 customer_5 -14.213539649803256
resNode: customer_2 deliver_cap: 29.814826716152897 cap_limit: 40
4435 customer_5 ('customer_5', 'customer_4')
1680 customer_5 -14.213539649803256
resNode: customer_4 deliver_cap: 49.64906634583991 cap_limit: 40
4436 customer_2 ('customer_2', 'customer_3')
1684 customer_2 -14.37246564183743
resNode: customer_3 deliver_cap: 61.85735942357614 cap_limit: 40
4437 customer_2 ('customer_2', 'customer_1')
1684 customer_2 -14.37246564183743
resNode: customer_1 deliver_cap: 48.77412749162844 cap_limit: 40
4438 customer_2 ('customer_2', 'depot_t')
1684 customer_2 -14.37246564183743
resNode: depot_t deliver_cap: 34.04796154549963 cap_limit: 40
4439 customer_2 ('customer_2', 'customer_4')
1684 customer_2 -14.37246564183743
resNode: customer_4 deliver_cap: 61.673032226942084 cap_limit: 40
4440 customer_2 ('customer_2', 'customer_5')
1684 customer_2 -14.37246564183743
resNode: customer_5 deliver_cap: 47.69885551106646 cap_limit: 40
4441 customer_1 ('customer_1', 'customer_3')
1687 customer_1 -16.18761889441838
resNode: customer_3 deliver_cap: 60.534060259019626 cap_limit: 40
4442 customer_1 ('customer_1', 'depot_t')
1687 customer_1 -16.18761889441838
resNode: depot_t deliver_cap: 36.403687368319105 cap_limit: 40
4443 customer_1 ('customer_1', 'customer_2')
1687 customer_1 -16.18761889441838
resNode: customer_2 deliver_cap: 39.71311349271175 cap_limit: 40
4444 customer_1 ('customer_1', 'customer_4')
1687 customer_1 -16.18761889441838
resNode: customer_4 deliver_cap: 60.07171398176503 cap_limit: 40
4445 customer_1 ('customer_1', 'customer_5')
1687 customer_1 -16.18761889441838
resNode: customer_5 deliver_cap: 49.82832769446973 cap_limit: 40
4446 customer_2 ('customer_2', 'customer_3')
1689 customer_2 -14.13711643457421
resNode: customer_3 deliver_cap: 51.61397313628084 cap_limit: 40
4447 customer_2 ('customer_2', 'customer_1')
1689 customer_2 -14.13711643457421
resNode: customer_1 deliver_cap: 40.5794184617922 cap_limit: 40
4448 customer_2 ('customer_2', 'depot_t')
1689 customer_2 -14.13711643457421
resNode: depot_t deliver_cap: 26.53614493481641 cap_limit: 40
4449 customer_2 ('customer_2', 'customer_4')
1689 customer_2 -14.13711643457421
resNode: customer_4 deliver_cap: 51.42964593964679 cap_limit: 40
4450 customer_2 ('customer_2', 'customer_5')
1689 customer_2 -14.13711643457421
resNode: customer_5 deliver_cap: 37.45546922377116 cap_limit: 40
4451 customer_2 ('customer_2', 'customer_3')
1693 customer_2 -15.849034076630444
resNode: customer_3 deliver_cap: 67.27092705975943 cap_limit: 40
4452 customer_2 ('customer_2', 'customer_1')
1693 customer_2 -15.849034076630444
resNode: customer_1 deliver_cap: 55.16940582409227 cap_limit: 40
4453 customer_2 ('customer_2', 'depot_t')
1693 customer_2 -15.849034076630444
resNode: depot_t deliver_cap: 37.92206593531307 cap_limit: 40
4454 customer_2 ('customer_2', 'customer_4')
1693 customer_2 -15.849034076630444
resNode: customer_4 deliver_cap: 67.04973442379857 cap_limit: 40
4455 customer_2 ('customer_2', 'customer_5')
1693 customer_2 -15.849034076630444
resNode: customer_5 deliver_cap: 50.28072236474782 cap_limit: 40
4456 customer_2 ('customer_2', 'customer_3')
1698 customer_2 -12.580743566319226
resNode: customer_3 deliver_cap: 61.85735942357614 cap_limit: 40
4457 customer_2 ('customer_2', 'customer_1')
1698 customer_2 -12.580743566319226
resNode: customer_1 deliver_cap: 48.77412749162844 cap_limit: 40
4458 customer_2 ('customer_2', 'depot_t')
1698 customer_2 -12.580743566319226
resNode: depot_t deliver_cap: 34.04796154549963 cap_limit: 40
4459 customer_2 ('customer_2', 'customer_4')
1698 customer_2 -12.580743566319226
resNode: customer_4 deliver_cap: 61.673032226942084 cap_limit: 40
4460 customer_2 ('customer_2', 'customer_5')
1698 customer_2 -12.580743566319226
resNode: customer_5 deliver_cap: 47.69885551106646 cap_limit: 40
4461 customer_1 ('customer_1', 'customer_3')
1702 customer_1 -13.135831526070696
resNode: customer_3 deliver_cap: 62.13537850419669 cap_limit: 40
4462 customer_1 ('customer_1', 'depot_t')
1702 customer_1 -13.135831526070696
resNode: depot_t deliver_cap: 37.577987414782285 cap_limit: 40
4463 customer_1 ('customer_1', 'customer_2')
1702 customer_1 -13.135831526070696
resNode: customer_2 deliver_cap: 40.9941680888534 cap_limit: 40
4464 customer_1 ('customer_1', 'customer_4')
1702 customer_1 -13.135831526070696
resNode: customer_4 deliver_cap: 61.6730322269421 cap_limit: 40
4465 customer_1 ('customer_1', 'customer_5')
1702 customer_1 -13.135831526070696
resNode: customer_5 deliver_cap: 51.4296459396468 cap_limit: 40
4466 customer_5 ('customer_5', 'customer_3')
1705 customer_5 -19.80639229658435
resNode: customer_3 deliver_cap: 62.55889220412882 cap_limit: 40
4467 customer_5 ('customer_5', 'customer_1')
1705 customer_5 -19.80639229658435
resNode: customer_1 deliver_cap: 53.02328970487361 cap_limit: 40
4468 customer_5 ('customer_5', 'depot_t')
1705 customer_5 -19.80639229658435
resNode: depot_t deliver_cap: 35.44231250709116 cap_limit: 40
4469 customer_5 ('customer_5', 'customer_2')
1705 customer_5 -19.80639229658435
resNode: customer_2 deliver_cap: 39.56755002282449 cap_limit: 40
4470 customer_5 ('customer_5', 'customer_4')
1705 customer_5 -19.80639229658435
resNode: customer_4 deliver_cap: 62.33769956816794 cap_limit: 40
4471 customer_2 ('customer_2', 'customer_3')
1709 customer_2 -18.746512105891885
resNode: customer_3 deliver_cap: 62.55889220412881 cap_limit: 40
4472 customer_2 ('customer_2', 'customer_1')
1709 customer_2 -18.746512105891885
resNode: customer_1 deliver_cap: 51.24271011106675 cap_limit: 40
4473 customer_2 ('customer_2', 'depot_t')
1709 customer_2 -18.746512105891885
resNode: depot_t deliver_cap: 34.25714993648925 cap_limit: 40
4474 customer_2 ('customer_2', 'customer_4')
1709 customer_2 -18.746512105891885
resNode: customer_4 deliver_cap: 62.33769956816794 cap_limit: 40
4475 customer_2 ('customer_2', 'customer_5')
1709 customer_2 -18.746512105891885
resNode: customer_5 deliver_cap: 45.56868750911719 cap_limit: 40
4476 customer_2 ('customer_2', 'customer_3')
1713 customer_2 -15.058978500947804
resNode: customer_3 deliver_cap: 62.78008484008968 cap_limit: 40
4477 customer_2 ('customer_2', 'customer_1')
1713 customer_2 -15.058978500947804
resNode: customer_1 deliver_cap: 51.42703730770081 cap_limit: 40
4478 customer_2 ('customer_2', 'depot_t')

resNode: depot_t deliver_cap: 22.399747572273917 cap_limit: 40
4509 customer_5 ('customer_5', 'customer_2')
1725 customer_5 -13.218312074527354
resNode: customer_2 deliver_cap: 25.593373306948884 cap_limit: 40
4510 customer_5 ('customer_5', 'customer_4')
1725 customer_5 -13.218312074527354
resNode: customer_4 deliver_cap: 45.5686875091172 cap_limit: 40
4511 customer_2 ('customer_2', 'customer_3')
1729 customer_2 -15.020064981658392
resNode: customer_3 deliver_cap: 62.55889220412882 cap_limit: 40
4512 customer_2 ('customer_2', 'customer_1')
1729 customer_2 -15.020064981658392
resNode: customer_1 deliver_cap: 51.242710111066756 cap_limit: 40
4513 customer_2 ('customer_2', 'depot_t')
1729 customer_2 -15.020064981658392
resNode: depot_t deliver_cap: 34.257149936489256 cap_limit: 40
4514 customer_2 ('customer_2', 'customer_4')
1729 customer_2 -15.020064981658392
resNode: customer_4 deliver_cap: 62.33769956816794 cap_limit: 40
4515 customer_2 ('customer_2', 'customer_5')
1729 customer_2 -15.020064981658392
resNode: customer_5 deliver_cap: 45.5686875091172 cap_limit: 40
4516 customer_5 ('customer_5', 'customer_3')
1730 customer_5 -22.500435924013793
resNode: customer_3 deliver_cap: 68.97652911092987 cap_limit: 40
4517 customer_5 ('customer_5', 'customer_1')
1730 customer_5 -22.500435924013793
resNode: customer_1 deliver_cap: 60.191794679659424 cap_limit: 40
4518 customer_5 ('customer_5', 'depot_t')
1730 customer_5 -22.500435924013793
resNode: depot_t deliver_cap: 39.79183817943226 cap_limit: 40
4519 customer_5 ('customer_5', 'customer_2')
1730 customer_5 -22.500435924013793
resNode: customer_2 deliver_cap: 44.04490706120047 cap_limit: 40
4520 customer_5 ('customer_5', 'customer_4')
1730 customer_5 -22.500435924013793
resNode: customer_4 deliver_cap: 68.7184710356422 cap_limit: 40
4521 customer_2 ('customer_2', 'customer_3')
1749 customer_2 -20.878781364522744
resNode: customer_3 deliver_cap: 69.23458718621755 cap_limit: 40
4522 customer_2 ('customer_2', 'customer_1')
1749 customer_2 -20.878781364522744
resNode: customer_1 deliver_cap: 58.27629180305205 cap_limit: 40
4523 customer_2 ('customer_2', 'depot_t')
1749 customer_2 -20.878781364522744
resNode: depot_t deliver_cap: 38.5616163570295 cap_limit: 40
4524 customer_2 ('customer_2', 'customer_4')
1749 customer_2 -20.878781364522744
resNode: customer_4 deliver_cap: 68.97652911092986 cap_limit: 40
4525 customer_2 ('customer_2', 'customer_5')
1749 customer_2 -20.878781364522744
resNode: customer_5 deliver_cap: 49.412681708704 cap_limit: 40
4526 customer_1 ('customer_1', 'customer_3')
1757 customer_1 -12.21554443075815
resNode: customer_3 deliver_cap: 58.75348066521275 cap_limit: 40
4527 customer_1 ('customer_1', 'depot_t')
1757 customer_1 -12.21554443075815
resNode: depot_t deliver_cap: 35.0979289995274 cap_limit: 40
4528 customer_1 ('customer_1', 'customer_2')
1757 customer_1 -12.21554443075815
resNode: customer_2 deliver_cap: 38.288649817666254 cap_limit: 40
4529 customer_1 ('customer_1', 'customer_4')
1757 customer_1 -12.21554443075815
resNode: customer_4 deliver_cap: 58.29113438795816 cap_limit: 40
4530 customer_1 ('customer_1', 'customer_5')
1757 customer_1 -12.21554443075815
resNode: customer_5 deliver_cap: 48.04774810066286 cap_limit: 40
4531 customer_5 ('customer_5', 'customer_3')
1760 customer_5 -18.040630741525817
resNode: customer_3 deliver_cap: 58.500614797348085 cap_limit: 40
4532 customer_5 ('customer_5', 'customer_1')
1760 customer_5 -18.040630741525817
resNode: customer_1 deliver_cap: 49.64139186588967 cap_limit: 40
4533 customer_5 ('customer_5', 'depot_t')
1760 customer_5 -18.040630741525817
resNode: depot_t deliver_cap: 32.28587452403948 cap_limit: 40
4534 customer_5 ('customer_5', 'customer_2')
1760 customer_5 -18.040630741525817
resNode: customer_2 deliver_cap: 36.18565218384055 cap_limit: 40
4535 customer_5 ('customer_5', 'customer_4')
1760 customer_5 -18.040630741525817
resNode: customer_4 deliver_cap: 58.27942216138722 cap_limit: 40
4536 customer_2 ('customer_2', 'customer_3')
1769 customer_2 -17.989745653990582
resNode: customer_3 deliver_cap: 60.63731030991632 cap_limit: 40
4537 customer_2 ('customer_2', 'customer_1')
1769 customer_2 -17.989745653990582
resNode: customer_1 deliver_cap: 49.64139186588968 cap_limit: 40
4538 customer_2 ('customer_2', 'depot_t')
1769 customer_2 -17.989745653990582
resNode: depot_t deliver_cap: 32.76258624099066 cap_limit: 40
4539 customer_2 ('customer_2', 'customer_4')
1769 customer_2 -17.989745653990582
resNode: customer_4 deliver_cap: 60.41611767395546 cap_limit: 40
4540 customer_2 ('customer_2', 'customer_5')
1769 customer_2 -17.989745653990582
resNode: customer_5 deliver_cap: 43.64710561490471 cap_limit: 40
4541 customer_2 ('customer_2', 'customer_3')
1773 customer_2 -14.295388952905821
resNode: customer_3 deliver_cap: 62.78008484008968 cap_limit: 40
4542 customer_2 ('customer_2', 'customer_1')
1773 customer_2 -14.295388952905821
resNode: customer_1 deliver_cap: 51.42703730770081 cap_limit: 40
4543 customer_2 ('customer_2', 'depot_t')
1773 customer_2 -14.295388952905821
resNode: depot_t deliver_cap: 34.42918865334771 cap_limit: 40
4544 customer_2 ('customer_2', 'customer_4')
1773 customer_2 -14.295388952905821
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
4545 customer_2 ('customer_2', 'customer_5')
1773 customer_2 -14.295388952905821
resNode: customer_5 deliver_cap: 45.789880145078065 cap_limit: 40
4546 customer_2 ('customer_2', 'customer_3')
1778 customer_2 -9.340184739534077
resNode: customer_3 deliver_cap: 49.83339354247398 cap_limit: 40
4547 customer_2 ('customer_2', 'customer_1')
1778 customer_2 -9.340184739534077
resNode: customer_1 deliver_cap: 39.15495478674671 cap_limit: 40
4548 customer_2 ('customer_2', 'depot_t')
1778 customer_2 -9.340184739534077
resNode: depot_t deliver_cap: 25.230386566024706 cap_limit: 40
4549 customer_2 ('customer_2', 'customer_4')
1778 customer_2 -9.340184739534077
resNode: customer_4 deliver_cap: 49.64906634583991 cap_limit: 40
4550 customer_2 ('customer_2', 'customer_5')
1778 customer_2 -9.340184739534077
resNode: customer_5 deliver_cap: 35.6748896299643 cap_limit: 40
4551 customer_5 ('customer_5', 'customer_3')
1780 customer_5 -17.215773510145915
resNode: customer_3 deliver_cap: 58.50061479734809 cap_limit: 40
4552 customer_5 ('customer_5', 'customer_1')
1780 customer_5 -17.215773510145915
resNode: customer_1 deliver_cap: 49.64139186588969 cap_limit: 40
4553 customer_5 ('customer_5', 'depot_t')
1780 customer_5 -17.215773510145915
resNode: depot_t deliver_cap: 32.285874524039485 cap_limit: 40
4554 customer_5 ('customer_5', 'customer_2')
1780 customer_5 -17.215773510145915
resNode: customer_2 deliver_cap: 36.18565218384056 cap_limit: 40
4555 customer_5 ('customer_5', 'customer_4')
1780 customer_5 -17.215773510145915
resNode: customer_4 deliver_cap: 58.27942216138723 cap_limit: 40
4556 customer_2 ('customer_2', 'customer_3')
1784 customer_2 -14.256475433616409
resNode: customer_3 deliver_cap: 62.55889220412882 cap_limit: 40
4557 customer_2 ('customer_2', 'customer_1')
1784 customer_2 -14.256475433616409
resNode: customer_1 deliver_cap: 51.242710111066756 cap_limit: 40
4558 customer_2 ('customer_2', 'depot_t')
1784 customer_2 -14.256475433616409
resNode: depot_t deliver_cap: 34.257149936489256 cap_limit: 40
4559 customer_2 ('customer_2', 'customer_4')
1784 customer_2 -14.256475433616409
resNode: customer_4 deliver_cap: 62.33769956816794 cap_limit: 40
4560 customer_2 ('customer_2', 'customer_5')
1784 customer_2 -14.256475433616409
resNode: customer_5 deliver_cap: 45.5686875091172 cap_limit: 40
4561 customer_5 ('customer_5', 'customer_3')
1785 customer_5 -21.73684637597181
resNode: customer_3 deliver_cap: 68.97652911092987 cap_limit: 40
4562 customer_5 ('customer_5', 'customer_1')
1785 customer_5 -21.73684637597181
resNode: customer_1 deliver_cap: 60.191794679659424 cap_limit: 40
4563 customer_5 ('customer_5', 'depot_t')
1785 customer_5 -21.73684637597181
resNode: depot_t deliver_cap: 39.79183817943226 cap_limit: 40
4564 customer_5 ('customer_5', 'customer_2')
1785 customer_5 -21.73684637597181
resNode: customer_2 deliver_cap: 44.04490706120047 cap_limit: 40
4565 customer_5 ('customer_5', 'customer_4')
1785 customer_5 -21.73684637597181
resNode: customer_4 deliver_cap: 68.7184710356422 cap_limit: 40
4566 customer_1 ('customer_1', 'customer_3')
1787 customer_1 -14.118131779739535
resNode: customer_3 deliver_cap: 56.49398469236459 cap_limit: 40
4567 customer_1 ('customer_1', 'depot_t')
1787 customer_1 -14.118131779739535
resNode: depot_t deliver_cap: 33.773275371584525 cap_limit: 40
4568 customer_1 ('customer_1', 'customer_2')
1787 customer_1 -14.118131779739535
resNode: customer_2 deliver_cap: 36.18565218384056 cap_limit: 40
4569 customer_1 ('customer_1', 'customer_4')
1787 customer_1 -14.118131779739535
resNode: customer_4 deliver_cap: 55.93916915965907 cap_limit: 40
4570 customer_1 ('customer_1', 'customer_5')
1787 customer_1 -14.118131779739535
resNode: customer_5 deliver_cap: 43.64710561490472 cap_limit: 40
4571 customer_2 ('customer_2', 'customer_3')
1789 customer_2 -11.39484233579291
resNode: customer_3 deliver_cap: 45.78988014507807 cap_limit: 40
4572 customer_2 ('customer_2', 'customer_1')
1789 customer_2 -11.39484233579291
resNode: customer_1 deliver_cap: 37.26853339519113 cap_limit: 40
4573 customer_2 ('customer_2', 'depot_t')
1789 customer_2 -11.39484233579291
resNode: depot_t deliver_cap: 21.214585001672013 cap_limit: 40
4574 customer_2 ('customer_2', 'customer_4')
1789 customer_2 -11.39484233579291
resNode: customer_4 deliver_cap: 45.5686875091172 cap_limit: 40
4575 customer_2 ('customer_2', 'customer_5')
1789 customer_2 -11.39484233579291
resNode: customer_5 deliver_cap: 28.799675450066463 cap_limit: 40
4576 customer_4 ('customer_4', 'customer_3')
1790 customer_4 -18.010399251738317
resNode: customer_3 deliver_cap: 54.65199763165206 cap_limit: 40
4577 customer_4 ('customer_4', 'customer_1')
1790 customer_4 -18.010399251738317
resNode: customer_1 deliver_cap: 55.71484616536303 cap_limit: 40
4578 customer_4 ('customer_4', 'depot_t')
1790 customer_4 -18.010399251738317
resNode: depot_t deliver_cap: 39.79183817943227 cap_limit: 40
4579 customer_4 ('customer_4', 'customer_2')
1790 customer_4 -18.010399251738317
resNode: customer_2 deliver_cap: 44.044907061200476 cap_limit: 40
4580 customer_4 ('customer_4', 'customer_5')
1790 customer_4 -18.010399251738317
resNode: customer_5 deliver_cap: 49.15462363341632 cap_limit: 40
4581 customer_5 ('customer_5', 'customer_3')
1805 customer_5 -21.904868608988203
resNode: customer_3 deliver_cap: 68.97652911092986 cap_limit: 40
4582 customer_5 ('customer_5', 'customer_1')
1805 customer_5 -21.904868608988203
resNode: customer_1 deliver_cap: 60.1917946796594 cap_limit: 40
4583 customer_5 ('customer_5', 'depot_t')
1805 customer_5 -21.904868608988203
resNode: depot_t deliver_cap: 39.791838179432254 cap_limit: 40
4584 customer_5 ('customer_5', 'customer_2')
1805 customer_5 -21.904868608988203
resNode: customer_2 deliver_cap: 44.04490706120046 cap_limit: 40
4585 customer_5 ('customer_5', 'customer_4')
1805 customer_5 -21.904868608988203
resNode: customer_4 deliver_cap: 68.71847103564218 cap_limit: 40
4586 customer_2 ('customer_2', 'customer_3')
1809 customer_2 -20.781497566299215
resNode: customer_3 deliver_cap: 68.97652911092986 cap_limit: 40
4587 customer_2 ('customer_2', 'customer_1')
1809 customer_2 -20.781497566299215
resNode: customer_1 deliver_cap: 58.05509916709117 cap_limit: 40
4588 customer_2 ('customer_2', 'depot_t')
1809 customer_2 -20.781497566299215
resNode: depot_t deliver_cap: 38.35271220084424 cap_limit: 40
4589 customer_2 ('customer_2', 'customer_4')
1809 customer_2 -20.781497566299215
resNode: customer_4 deliver_cap: 68.71847103564218 cap_limit: 40
4590 customer_2 ('customer_2', 'customer_5')
1809 customer_2 -20.781497566299215
resNode: customer_5 deliver_cap: 49.154623633416314 cap_limit: 40
4591 customer_2 ('customer_2', 'customer_3')
1813 customer_2 -13.120875447485693
resNode: customer_3 deliver_cap: 69.56205640578534 cap_limit: 40
4592 customer_2 ('customer_2', 'customer_1')
1813 customer_2 -13.120875447485693
resNode: customer_1 deliver_cap: 57.078680279113854 cap_limit: 40
4593 customer_2 ('customer_2', 'depot_t')
1813 customer_2 -13.120875447485693
resNode: depot_t deliver_cap: 39.70405542666656 cap_limit: 40
4594 customer_2 ('customer_2', 'customer_4')
1813 customer_2 -13.120875447485693
resNode: customer_4 deliver_cap: 69.34086376982447 cap_limit: 40
4595 customer_2 ('customer_2', 'customer_5')
1813 customer_2 -13.120875447485693
resNode: customer_5 deliver_cap: 52.57185171077372 cap_limit: 40
4596 customer_1 ('customer_1', 'customer_3')
1817 customer_1 -7.219809075482319
resNode: customer_3 deliver_cap: 55.485036513887025 cap_limit: 40
4597 customer_1 ('customer_1', 'depot_t')
1817 customer_1 -7.219809075482319
resNode: depot_t deliver_cap: 32.70106995522187 cap_limit: 40
4598 customer_1 ('customer_1', 'customer_2')
1817 customer_1 -7.219809075482319
resNode: customer_2 deliver_cap: 35.67389449660567 cap_limit: 40
4599 customer_1 ('customer_1', 'customer_4')
1817 customer_1 -7.219809075482319
resNode: customer_4 deliver_cap: 55.02269023663243 cap_limit: 40
4600 customer_1 ('customer_1', 'customer_5')
1817 customer_1 -7.219809075482319
resNode: customer_5 deliver_cap: 44.77930394933713 cap_limit: 40
4601 customer_5 ('customer_5', 'customer_3')
1820 customer_5 -12.227784348418556
resNode: customer_3 deliver_cap: 54.57848181575723 cap_limit: 40
4602 customer_5 ('customer_5', 'customer_1')
1820 customer_5 -12.227784348418556
resNode: customer_1 deliver_cap: 46.372947714563956 cap_limit: 40
4603 customer_5 ('customer_5', 'depot_t')
1820 customer_5 -12.227784348418556
resNode: depot_t deliver_cap: 29.23532664946881 cap_limit: 40
4604 customer_5 ('customer_5', 'customer_2')
1820 customer_5 -12.227784348418556
resNode: customer_2 deliver_cap: 32.917208032514836 cap_limit: 40
4605 customer_5 ('customer_5', 'customer_4')
1820 customer_5 -12.227784348418556
resNode: customer_4 deliver_cap: 54.35728917979635 cap_limit: 40
4606 customer_2 ('customer_2', 'customer_3')
1824 customer_2 -12.924417782511307
resNode: customer_3 deliver_cap: 69.00724087307982 cap_limit: 40
4607 customer_2 ('customer_2', 'customer_1')
1824 customer_2 -12.924417782511307
resNode: customer_1 deliver_cap: 56.616334001859265 cap_limit: 40
4608 customer_2 ('customer_2', 'depot_t')
1824 customer_2 -12.924417782511307
resNode: depot_t deliver_cap: 39.27253223456226 cap_limit: 40
4609 customer_2 ('customer_2', 'customer_4')
1824 customer_2 -12.924417782511307
resNode: customer_4 deliver_cap: 68.78604823711896 cap_limit: 40
4610 customer_2 ('customer_2', 'customer_5')
1824 customer_2 -12.924417782511307
resNode: customer_5 deliver_cap: 52.01703617806821 cap_limit: 40
4611 customer_2 ('customer_2', 'customer_3')
1829 customer_2 -12.176899260883323
resNode: customer_3 deliver_cap: 56.71517732832547 cap_limit: 40
4612 customer_2 ('customer_2', 'customer_1')
1829 customer_2 -12.176899260883323
resNode: customer_1 deliver_cap: 46.37294771456396 cap_limit: 40
4613 customer_2 ('customer_2', 'depot_t')
1829 customer_2 -12.176899260883323
resNode: depot_t deliver_cap: 29.712038366419986 cap_limit: 40
4614 customer_2 ('customer_2', 'customer_4')
1829 customer_2 -12.176899260883323
resNode: customer_4 deliver_cap: 56.4939846923646 cap_limit: 40
4615 customer_2 ('customer_2', 'customer_5')
1829 customer_2 -12.176899260883323
resNode: customer_5 deliver_cap: 39.72497263331385 cap_limit: 40
4616 customer_2 ('customer_2', 'customer_3')
1833 customer_2 -10.669297746839751
resNode: customer_3 deliver_cap: 63.00127747605055 cap_limit: 40
4617 customer_2 ('customer_2', 'customer_1')
1833 customer_2 -10.669297746839751
resNode: customer_1 deliver_cap: 51.61136450433486 cap_limit: 40
4618 customer_2 ('customer_2', 'depot_t')
1833 customer_2 -10.669297746839751
resNode: depot_t deliver_cap: 34.60122737020616 cap_limit: 40
4619 customer_2 ('customer_2', 'customer_4')
1833 customer_2 -10.669297746839751
resNode: customer_4 deliver_cap: 62.78008484008967 cap_limit: 40
4620 customer_2 ('customer_2', 'customer_5')
1833 customer_2 -10.669297746839751
resNode: customer_5 deliver_cap: 46.011072781038926 cap_limit: 40
4621 customer_2 ('customer_2', 'customer_3')
1838 customer_2 -5.668011734309493
resNode: customer_3 deliver_cap: 50.01772073910803 cap_limit: 40
4622 customer_2 ('customer_2', 'customer_1')
1838 customer_2 -5.668011734309493
resNode: customer_1 deliver_cap: 39.30241654405395 cap_limit: 40
4623 customer_2 ('customer_2', 'depot_t')
1838 customer_2 -5.668011734309493
resNode: depot_t deliver_cap: 25.365559843556348 cap_limit: 40
4624 customer_2 ('customer_2', 'customer_4')
1838 customer_2 -5.668011734309493
resNode: customer_4 deliver_cap: 49.83339354247398 cap_limit: 40
4625 customer_2 ('customer_2', 'customer_5')
1838 customer_2 -5.668011734309493
resNode: customer_5 deliver_cap: 35.85921682659835 cap_limit: 40
4626 customer_5 ('customer_5', 'customer_3')
1840 customer_5 -13.589682304079846
resNode: customer_3 deliver_cap: 58.72180743330896 cap_limit: 40
4627 customer_5 ('customer_5', 'customer_1')
1840 customer_5 -13.589682304079846
resNode: customer_1 deliver_cap: 49.82571906252373 cap_limit: 40
4628 customer_5 ('customer_5', 'depot_t')
1840 customer_5 -13.589682304079846
resNode: depot_t deliver_cap: 32.45791324089794 cap_limit: 40
4629 customer_5 ('customer_5', 'customer_2')
1840 customer_5 -13.589682304079846
resNode: customer_2 deliver_cap: 36.36997938047461 cap_limit: 40
4630 customer_5 ('customer_5', 'customer_4')
1840 customer_5 -13.589682304079846
resNode: customer_4 deliver_cap: 58.500614797348085 cap_limit: 40
4631 customer_2 ('customer_2', 'customer_3')
1844 customer_2 -10.630384227550339
resNode: customer_3 deliver_cap: 62.78008484008968 cap_limit: 40
4632 customer_2 ('customer_2', 'customer_1')
1844 customer_2 -10.630384227550339
resNode: customer_1 deliver_cap: 51.42703730770081 cap_limit: 40
4633 customer_2 ('customer_2', 'depot_t')
1844 customer_2 -10.630384227550339
resNode: depot_t deliver_cap: 34.42918865334771 cap_limit: 40
4634 customer_2 ('customer_2', 'customer_4')
1844 customer_2 -10.630384227550339
resNode: customer_4 deliver_cap: 62.55889220412882 cap_limit: 40
4635 customer_2 ('customer_2', 'customer_5')
1844 customer_2 -10.630384227550339
resNode: customer_5 deliver_cap: 45.789880145078065 cap_limit: 40
4636 customer_1 ('customer_1', 'customer_3')
1847 customer_1 -10.492040573673464
resNode: customer_3 deliver_cap: 56.71517732832547 cap_limit: 40
4637 customer_1 ('customer_1', 'depot_t')
1847 customer_1 -10.492040573673464
resNode: depot_t deliver_cap: 33.94531408844298 cap_limit: 40
4638 customer_1 ('customer_1', 'customer_2')
1847 customer_1 -10.492040573673464
resNode: customer_2 deliver_cap: 36.36997938047462 cap_limit: 40
4639 customer_1 ('customer_1', 'customer_4')
1847 customer_1 -10.492040573673464
resNode: customer_4 deliver_cap: 56.16036179561995 cap_limit: 40
4640 customer_1 ('customer_1', 'customer_5')
1847 customer_1 -10.492040573673464
resNode: customer_5 deliver_cap: 43.868298250865585 cap_limit: 40
4641 customer_2 ('customer_2', 'customer_3')
1849 customer_2 -7.768751129726842
resNode: customer_3 deliver_cap: 46.01107278103893 cap_limit: 40
4642 customer_2 ('customer_2', 'customer_1')
1849 customer_2 -7.768751129726842
resNode: customer_1 deliver_cap: 37.45286059182518 cap_limit: 40
4643 customer_2 ('customer_2', 'depot_t')
1849 customer_2 -7.768751129726842
resNode: depot_t deliver_cap: 21.386623718530466 cap_limit: 40
4644 customer_2 ('customer_2', 'customer_4')
1849 customer_2 -7.768751129726842
resNode: customer_4 deliver_cap: 45.78988014507807 cap_limit: 40
4645 customer_2 ('customer_2', 'customer_5')
1849 customer_2 -7.768751129726842
resNode: customer_5 deliver_cap: 29.020868086027328 cap_limit: 40
4646 customer_2 ('customer_2', 'customer_3')
1853 customer_2 -5.462247672903821

4705 customer_1 ('customer_1', 'customer_5')
1882 customer_1 -9.194277147489423
resNode: customer_5 deliver_cap: 41.731602738297354 cap_limit: 40
4706 customer_5 ('customer_5', 'customer_3')
1885 customer_5 -11.038070144229874
resNode: customer_3 deliver_cap: 49.67073978399169 cap_limit: 40
4707 customer_5 ('customer_5', 'customer_1')
1885 customer_5 -11.038070144229874
resNode: customer_1 deliver_cap: 43.64397525656955 cap_limit: 40
4708 customer_5 ('customer_5', 'depot_t')
1885 customer_5 -11.038070144229874
resNode: depot_t deliver_cap: 24.163342057625165 cap_limit: 40
4709 customer_5 ('customer_5', 'customer_2')
1885 customer_5 -11.038070144229874
resNode: customer_2 deliver_cap: 27.497087638110603 cap_limit: 40
4710 customer_5 ('customer_5', 'customer_4')
1885 customer_5 -11.038070144229874
resNode: customer_4 deliver_cap: 49.412681708704014 cap_limit: 40
4711 customer_2 ('customer_2', 'customer_3')
1889 customer_2 -13.475041035158164
resNode: customer_3 deliver_cap: 69.23458718621755 cap_limit: 40
4712 customer_2 ('customer_2', 'customer_1')
1889 customer_2 -13.475041035158164
resNode: customer_1 deliver_cap: 58.27629180305205 cap_limit: 40
4713 customer_2 ('customer_2', 'depot_t')
1889 customer_2 -13.475041035158164
resNode: depot_t deliver_cap: 38.5616163570295 cap_limit: 40
4714 customer_2 ('customer_2', 'customer_4')
1889 customer_2 -13.475041035158164
resNode: customer_4 deliver_cap: 68.97652911092986 cap_limit: 40
4715 customer_2 ('customer_2', 'customer_5')
1889 customer_2 -13.475041035158164
resNode: customer_5 deliver_cap: 49.412681708704 cap_limit: 40
4716 customer_2 ('customer_2', 'customer_3')
1893 customer_2 -9.74517463910186
resNode: customer_3 deliver_cap: 57.265616107693894 cap_limit: 40
4717 customer_2 ('customer_2', 'customer_1')
1893 customer_2 -9.74517463910186
resNode: customer_1 deliver_cap: 45.100732838922646 cap_limit: 40
4718 customer_2 ('customer_2', 'depot_t')
1893 customer_2 -9.74517463910186
resNode: depot_t deliver_cap: 30.68068311385265 cap_limit: 40
4719 customer_2 ('customer_2', 'customer_4')
1893 customer_2 -9.74517463910186
resNode: customer_4 deliver_cap: 57.08128891105984 cap_limit: 40
4720 customer_2 ('customer_2', 'customer_5')
1893 customer_2 -9.74517463910186
resNode: customer_5 deliver_cap: 43.10711219518422 cap_limit: 40
4721 customer_5 ('customer_5', 'customer_3')
1895 customer_5 -19.478819051018675
resNode: customer_3 deliver_cap: 67.41928187561199 cap_limit: 40
4722 customer_5 ('customer_5', 'customer_1')
1895 customer_5 -19.478819051018675
resNode: customer_1 deliver_cap: 57.073614431109604 cap_limit: 40
4723 customer_5 ('customer_5', 'depot_t')
1895 customer_5 -19.478819051018675
resNode: depot_t deliver_cap: 39.2226155849114 cap_limit: 40
4724 customer_5 ('customer_5', 'customer_2')
1895 customer_5 -19.478819051018675
resNode: customer_2 deliver_cap: 43.61787474906047 cap_limit: 40
4725 customer_5 ('customer_5', 'customer_4')
1895 customer_5 -19.478819051018675
resNode: customer_4 deliver_cap: 67.19808923965113 cap_limit: 40
4726 customer_1 ('customer_1', 'customer_3')
1897 customer_1 -10.21222322332349
resNode: customer_3 deliver_cap: 57.265616107693894 cap_limit: 40
4727 customer_1 ('customer_1', 'depot_t')
1897 customer_1 -10.21222322332349
resNode: depot_t deliver_cap: 34.00682832401357 cap_limit: 40
4728 customer_1 ('customer_1', 'customer_2')
1897 customer_1 -10.21222322332349
resNode: customer_2 deliver_cap: 37.09835817165117 cap_limit: 40
4729 customer_1 ('customer_1', 'customer_4')
1897 customer_1 -10.21222322332349
resNode: customer_4 deliver_cap: 56.8032698304393 cap_limit: 40
4730 customer_1 ('customer_1', 'customer_5')
1897 customer_1 -10.21222322332349
resNode: customer_5 deliver_cap: 46.559883543144 cap_limit: 40
4731 customer_5 ('customer_5', 'customer_3')
1900 customer_5 -15.665343394711444
resNode: customer_3 deliver_cap: 56.71517732832547 cap_limit: 40
4732 customer_5 ('customer_5', 'customer_1')
1900 customer_5 -15.665343394711444
resNode: customer_1 deliver_cap: 48.153527308370826 cap_limit: 40
4733 customer_5 ('customer_5', 'depot_t')
1900 customer_5 -15.665343394711444
resNode: depot_t deliver_cap: 30.897200937021882 cap_limit: 40
4734 customer_5 ('customer_5', 'customer_2')
1900 customer_5 -15.665343394711444
resNode: customer_2 deliver_cap: 34.6977876263217 cap_limit: 40
4735 customer_5 ('customer_5', 'customer_4')
1900 customer_5 -15.665343394711444
resNode: customer_4 deliver_cap: 56.4939846923646 cap_limit: 40
4736 customer_2 ('customer_2', 'customer_3')
1904 customer_2 -11.66907165546813
resNode: customer_3 deliver_cap: 61.20601954799522 cap_limit: 40
4737 customer_2 ('customer_2', 'customer_1')
1904 customer_2 -11.66907165546813
resNode: customer_1 deliver_cap: 50.11531623095542 cap_limit: 40
4738 customer_2 ('customer_2', 'depot_t')
1904 customer_2 -11.66907165546813
resNode: depot_t deliver_cap: 33.20491564838535 cap_limit: 40
4739 customer_2 ('customer_2', 'customer_4')
1904 customer_2 -11.66907165546813
resNode: customer_4 deliver_cap: 60.98482691203435 cap_limit: 40
4740 customer_2 ('customer_2', 'customer_5')
1904 customer_2 -11.66907165546813
resNode: customer_5 deliver_cap: 44.215814852983605 cap_limit: 40
4741 customer_5 ('customer_5', 'customer_3')
1905 customer_5 -18.867594127795698
resNode: customer_3 deliver_cap: 67.39817767877402 cap_limit: 40
4742 customer_5 ('customer_5', 'customer_1')
1905 customer_5 -18.867594127795698
resNode: customer_1 deliver_cap: 58.838922023525825 cap_limit: 40
4743 customer_5 ('customer_5', 'depot_t')
1905 customer_5 -18.867594127795698
resNode: depot_t deliver_cap: 38.514125115306086 cap_limit: 40
4744 customer_5 ('customer_5', 'customer_2')
1905 customer_5 -18.867594127795698
resNode: customer_2 deliver_cap: 42.69203440506687 cap_limit: 40
4745 customer_5 ('customer_5', 'customer_4')
1905 customer_5 -18.867594127795698
resNode: customer_4 deliver_cap: 67.14011960348634 cap_limit: 40
4746 customer_2 ('customer_2', 'customer_3')
1909 customer_2 -14.605463204018989
resNode: customer_3 deliver_cap: 56.715177328325474 cap_limit: 40
4747 customer_2 ('customer_2', 'customer_1')
1909 customer_2 -14.605463204018989
resNode: customer_1 deliver_cap: 46.37294771456396 cap_limit: 40
4748 customer_2 ('customer_2', 'depot_t')
1909 customer_2 -14.605463204018989
resNode: depot_t deliver_cap: 29.71203836641999 cap_limit: 40
4749 customer_2 ('customer_2', 'customer_4')
1909 customer_2 -14.605463204018989
resNode: customer_4 deliver_cap: 56.4939846923646 cap_limit: 40
4750 customer_2 ('customer_2', 'customer_5')
1909 customer_2 -14.605463204018989
resNode: customer_5 deliver_cap: 39.724972633313854 cap_limit: 40
4751 customer_1 ('customer_1', 'customer_3')
1911 customer_1 -10.589309761915798
resNode: customer_3 deliver_cap: 57.265616107693894 cap_limit: 40
4752 customer_1 ('customer_1', 'depot_t')
1911 customer_1 -10.589309761915798
resNode: depot_t deliver_cap: 34.00682832401357 cap_limit: 40
4753 customer_1 ('customer_1', 'customer_2')
1911 customer_1 -10.589309761915798
resNode: customer_2 deliver_cap: 37.09835817165117 cap_limit: 40
4754 customer_1 ('customer_1', 'customer_4')
1911 customer_1 -10.589309761915798
resNode: customer_4 deliver_cap: 56.8032698304393 cap_limit: 40
4755 customer_1 ('customer_1', 'customer_5')
1911 customer_1 -10.589309761915798
resNode: customer_5 deliver_cap: 46.559883543144 cap_limit: 40
4756 customer_2 ('customer_2', 'customer_3')
1913 customer_2 -9.402000139061576
resNode: customer_3 deliver_cap: 51.7983003329149 cap_limit: 40
4757 customer_2 ('customer_2', 'customer_1')
1913 customer_2 -9.402000139061576
resNode: customer_1 deliver_cap: 40.72688021909945 cap_limit: 40
4758 customer_2 ('customer_2', 'depot_t')
1913 customer_2 -9.402000139061576
resNode: depot_t deliver_cap: 26.67131821234805 cap_limit: 40
4759 customer_2 ('customer_2', 'customer_4')
1913 customer_2 -9.402000139061576
resNode: customer_4 deliver_cap: 51.61397313628085 cap_limit: 40
4760 customer_2 ('customer_2', 'customer_5')
1913 customer_2 -9.402000139061576
resNode: customer_5 deliver_cap: 37.639796420405226 cap_limit: 40
4761 customer_4 ('customer_4', 'customer_3')
1914 customer_4 -13.692643027403259
resNode: customer_3 deliver_cap: 50.934479813597726 cap_limit: 40
4762 customer_4 ('customer_4', 'customer_1')
1914 customer_4 -13.692643027403259
resNode: customer_1 deliver_cap: 49.83729715033488 cap_limit: 40
4763 customer_4 ('customer_4', 'depot_t')
1914 customer_4 -13.692643027403259
resNode: depot_t deliver_cap: 35.95079052286331 cap_limit: 40
4764 customer_4 ('customer_4', 'customer_2')
1914 customer_4 -13.692643027403259
resNode: customer_2 deliver_cap: 40.11234789686608 cap_limit: 40
4765 customer_4 ('customer_4', 'customer_5')
1914 customer_4 -13.692643027403259
resNode: customer_5 deliver_cap: 46.2224449579671 cap_limit: 40
4766 customer_5 ('customer_5', 'customer_3')
1915 customer_5 -16.87852581038021
resNode: customer_3 deliver_cap: 58.72180743330897 cap_limit: 40
4767 customer_5 ('customer_5', 'customer_1')
1915 customer_5 -16.87852581038021
resNode: customer_1 deliver_cap: 49.825719062523746 cap_limit: 40
4768 customer_5 ('customer_5', 'depot_t')
1915 customer_5 -16.87852581038021
resNode: depot_t deliver_cap: 32.45791324089794 cap_limit: 40
4769 customer_5 ('customer_5', 'customer_2')
1915 customer_5 -16.87852581038021
resNode: customer_2 deliver_cap: 36.36997938047462 cap_limit: 40
4770 customer_5 ('customer_5', 'customer_4')
1915 customer_5 -16.87852581038021
resNode: customer_4 deliver_cap: 58.500614797348106 cap_limit: 40
4771 customer_3 ('customer_3', 'customer_1')
1916 customer_3 -12.132179150157587
resNode: customer_1 deliver_cap: 45.10073283892264 cap_limit: 40
4772 customer_3 ('customer_3', 'depot_t')
1916 customer_3 -12.132179150157587
resNode: depot_t deliver_cap: 32.8381562295139 cap_limit: 40
4773 customer_3 ('customer_3', 'customer_2')
1916 customer_3 -12.132179150157587
resNode: customer_2 deliver_cap: 37.098358171651164 cap_limit: 40
4774 customer_3 ('customer_3', 'customer_4')
1916 customer_3 -12.132179150157587
resNode: customer_4 deliver_cap: 48.521672465728585 cap_limit: 40
4775 customer_3 ('customer_3', 'customer_5')
1916 customer_3 -12.132179150157587
resNode: customer_5 deliver_cap: 44.779303949337134 cap_limit: 40
4776 customer_2 ('customer_2', 'customer_3')
1918 customer_2 -4.700572375359828
resNode: customer_3 deliver_cap: 39.45196520691798 cap_limit: 40
4777 customer_2 ('customer_2', 'customer_1')
1918 customer_2 -4.700572375359828
resNode: customer_1 deliver_cap: 29.055153869764133 cap_limit: 40
4778 customer_2 ('customer_2', 'depot_t')
1918 customer_2 -4.700572375359828
resNode: depot_t deliver_cap: 18.072872296643837 cap_limit: 40
4779 customer_2 ('customer_2', 'customer_4')
1918 customer_2 -4.700572375359828
resNode: customer_4 deliver_cap: 39.304503449610735 cap_limit: 40
4780 customer_2 ('customer_2', 'customer_5')
1918 customer_2 -4.700572375359828
resNode: customer_5 deliver_cap: 28.12516207691024 cap_limit: 40
4781 customer_4 ('customer_4', 'customer_3')
1919 customer_4 -11.989661884196238
resNode: customer_3 deliver_cap: 48.243653385108054 cap_limit: 40
4782 customer_4 ('customer_4', 'customer_1')
1919 customer_4 -11.989661884196238
resNode: customer_1 deliver_cap: 44.50844055262253 cap_limit: 40
4783 customer_4 ('customer_4', 'depot_t')
1919 customer_4 -11.989661884196238
resNode: depot_t deliver_cap: 32.49910229286053 cap_limit: 40
4784 customer_4 ('customer_4', 'customer_2')
1919 customer_4 -11.989661884196238
resNode: customer_2 deliver_cap: 36.72848114984749 cap_limit: 40
4785 customer_4 ('customer_4', 'customer_5')
1919 customer_4 -11.989661884196238
resNode: customer_5 deliver_cap: 44.31695767208253 cap_limit: 40
4786 customer_5 ('customer_5', 'customer_3')
1920 customer_5 -12.43720509608604
resNode: customer_3 deliver_cap: 48.232075297296916 cap_limit: 40
4787 customer_5 ('customer_5', 'customer_1')
1920 customer_5 -12.43720509608604
resNode: customer_1 deliver_cap: 39.29836386565055 cap_limit: 40
4788 customer_5 ('customer_5', 'depot_t')
1920 customer_5 -12.43720509608604
resNode: depot_t deliver_cap: 24.987285682177305 cap_limit: 40
4789 customer_5 ('customer_5', 'customer_2')
1920 customer_5 -12.43720509608604
resNode: customer_2 deliver_cap: 28.53377212001125 cap_limit: 40
4790 customer_5 ('customer_5', 'customer_4')
1920 customer_5 -12.43720509608604
resNode: customer_4 deliver_cap: 48.04774810066286 cap_limit: 40
4791 customer_3 ('customer_3', 'customer_1')
1921 customer_3 -13.643489108300841
resNode: customer_1 deliver_cap: 50.115316230955415 cap_limit: 40
4792 customer_3 ('customer_3', 'depot_t')
1921 customer_3 -13.643489108300841
resNode: depot_t deliver_cap: 35.95079052286331 cap_limit: 40
4793 customer_3 ('customer_3', 'customer_2')
1921 customer_3 -13.643489108300841
resNode: customer_2 deliver_cap: 40.11234789686608 cap_limit: 40
4794 customer_3 ('customer_3', 'customer_4')
1921 customer_3 -13.643489108300841
resNode: customer_4 deliver_cap: 50.71328717763686 cap_limit: 40
4795 customer_3 ('customer_3', 'customer_5')
1921 customer_3 -13.643489108300841
resNode: customer_5 deliver_cap: 46.2224449579671 cap_limit: 40
4796 customer_1 ('customer_1', 'customer_3')
1922 customer_1 -10.490107832302954
resNode: customer_3 deliver_cap: 56.8032698304393 cap_limit: 40
4797 customer_1 ('customer_1', 'depot_t')
1922 customer_1 -10.490107832302954
resNode: depot_t deliver_cap: 33.6677743873602 cap_limit: 40
4798 customer_1 ('customer_1', 'customer_2')
1922 customer_1 -10.490107832302954
resNode: customer_2 deliver_cap: 36.72848114984749 cap_limit: 40
4799 customer_1 ('customer_1', 'customer_4')
1922 customer_1 -10.490107832302954
resNode: customer_4 deliver_cap: 56.34092355318471 cap_limit: 40
4800 customer_1 ('customer_1', 'customer_5')
1922 customer_1 -10.490107832302954
resNode: customer_5 deliver_cap: 46.0975372658894 cap_limit: 40
4801 customer_2 ('customer_2', 'customer_3')
1924 customer_2 -9.372302979603866
resNode: customer_3 deliver_cap: 51.61397313628085 cap_limit: 40
4802 customer_2 ('customer_2', 'customer_1')
1924 customer_2 -9.372302979603866
resNode: customer_1 deliver_cap: 40.5794184617922 cap_limit: 40
4803 customer_2 ('customer_2', 'depot_t')
1924 customer_2 -9.372302979603866
resNode: depot_t deliver_cap: 26.536144934816413 cap_limit: 40
4804 customer_2 ('customer_2', 'customer_4')
1924 customer_2 -9.372302979603866
resNode: customer_4 deliver_cap: 51.42964593964679 cap_limit: 40
4805 customer_2 ('customer_2', 'customer_5')
1924 customer_2 -9.372302979603866
resNode: customer_5 deliver_cap: 37.45546922377117 cap_limit: 40
4806 customer_5 ('customer_5', 'customer_3')
1925 customer_5 -16.802746851763985
resNode: customer_3 deliver_cap: 58.50061479734809 cap_limit: 40
4807 customer_5 ('customer_5', 'customer_1')
1925 customer_5 -16.802746851763985
resNode: customer_1 deliver_cap: 49.64139186588969 cap_limit: 40
4808 customer_5 ('customer_5', 'depot_t')
1925 customer_5 -16.802746851763985
resNode: depot_t deliver_cap: 32.285874524039485 cap_limit: 40
4809 customer_5 ('customer_5', 'customer_2')
1925 customer_5 -16.802746851763985
resNode: customer_2 deliver_cap: 36.18565218384056 cap_limit: 40
4810 customer_5 ('customer_5', 'customer_4')
1925 customer_5 -16.802746851763985
resNode: customer_4 deliver_cap: 58.27942216138723 cap_limit: 40
4811 customer_3 ('customer_3', 'customer_1')
1926 customer_3 -13.102924767044296
resNode: customer_1 deliver_cap: 46.37294771456396 cap_limit: 40
4812 customer_3 ('customer_3', 'depot_t')
1926 customer_3 -13.102924767044296
resNode: depot_t deliver_cap: 32.45791324089794 cap_limit: 40
4813 customer_3 ('customer_3', 'customer_2')
1926 customer_3 -13.102924767044296
resNode: customer_2 deliver_cap: 36.36997938047462 cap_limit: 40
4814 customer_3 ('customer_3', 'customer_4')
1926 customer_3 -13.102924767044296
resNode: customer_4 deliver_cap: 46.222444957967106 cap_limit: 40
4815 customer_3 ('customer_3', 'customer_5')
1926 customer_3 -13.102924767044296
resNode: customer_5 deliver_cap: 41.731602738297354 cap_limit: 40
4816 customer_1 ('customer_1', 'customer_3')
1927 customer_1 -9.259881177418317
resNode: customer_3 deliver_cap: 46.559883543144 cap_limit: 40
4817 customer_1 ('customer_1', 'depot_t')
1927 customer_1 -9.259881177418317
resNode: depot_t deliver_cap: 26.15595777667698 cap_limit: 40
4818 customer_1 ('customer_1', 'customer_2')
1927 customer_1 -9.259881177418317
resNode: customer_2 deliver_cap: 28.53377212001125 cap_limit: 40
4819 customer_1 ('customer_1', 'customer_4')
1927 customer_1 -9.259881177418317
resNode: customer_4 deliver_cap: 46.0975372658894 cap_limit: 40
4820 customer_1 ('customer_1', 'customer_5')
1927 customer_1 -9.259881177418317
resNode: customer_5 deliver_cap: 35.8541509785941 cap_limit: 40
4821 customer_2 ('customer_2', 'customer_3')
1929 customer_2 -7.209378717574148
resNode: customer_3 deliver_cap: 37.63979642040523 cap_limit: 40
4822 customer_2 ('customer_2', 'customer_1')
1929 customer_2 -7.209378717574148
resNode: customer_1 deliver_cap: 29.400077089091702 cap_limit: 40
4823 customer_2 ('customer_2', 'depot_t')
1929 customer_2 -7.209378717574148
resNode: depot_t deliver_cap: 16.288415343174293 cap_limit: 40
4824 customer_2 ('customer_2', 'customer_4')
1929 customer_2 -7.209378717574148
resNode: customer_4 deliver_cap: 37.45546922377117 cap_limit: 40
4825 customer_2 ('customer_2', 'customer_5')
1929 customer_2 -7.209378717574148
resNode: customer_5 deliver_cap: 23.481292507895553 cap_limit: 40
4826 customer_4 ('customer_4', 'customer_3')
1930 customer_4 -13.07629972753049
resNode: customer_3 deliver_cap: 46.222444957967106 cap_limit: 40
4827 customer_4 ('customer_4', 'customer_1')
1930 customer_4 -13.07629972753049
resNode: customer_1 deliver_cap: 45.91060143730936 cap_limit: 40
4828 customer_4 ('customer_4', 'depot_t')
1930 customer_4 -13.07629972753049
resNode: depot_t deliver_cap: 32.28587452403949 cap_limit: 40
4829 customer_4 ('customer_4', 'customer_2')
1930 customer_4 -13.07629972753049
resNode: customer_2 deliver_cap: 36.18565218384057 cap_limit: 40
4830 customer_4 ('customer_4', 'customer_5')
1930 customer_4 -13.07629972753049
resNode: customer_5 deliver_cap: 41.51041010233648 cap_limit: 40
4831 customer_2 ('customer_2', 'customer_3')
1933 customer_2 -11.388235169181932
resNode: customer_3 deliver_cap: 60.872396651250575 cap_limit: 40
4832 customer_2 ('customer_2', 'customer_1')
1933 customer_2 -11.388235169181932
resNode: customer_1 deliver_cap: 49.837297150334884 cap_limit: 40
4833 customer_2 ('customer_2', 'depot_t')
1933 customer_2 -11.388235169181932
resNode: depot_t deliver_cap: 32.94543117313951 cap_limit: 40
4834 customer_2 ('customer_2', 'customer_4')
1933 customer_2 -11.388235169181932
resNode: customer_4 deliver_cap: 60.65120401528971 cap_limit: 40
4835 customer_2 ('customer_2', 'customer_5')
1933 customer_2 -11.388235169181932
resNode: customer_5 deliver_cap: 43.882191956238955 cap_limit: 40
4836 customer_5 ('customer_5', 'customer_3')
1935 customer_5 -18.517252871354366
resNode: customer_3 deliver_cap: 67.00895096590526 cap_limit: 40
4837 customer_5 ('customer_5', 'customer_1')
1935 customer_5 -18.517252871354366
resNode: customer_1 deliver_cap: 58.50529912678117 cap_limit: 40
4838 customer_5 ('customer_5', 'depot_t')
1935 customer_5 -18.517252871354366
resNode: depot_t deliver_cap: 38.19903682393614 cap_limit: 40
4839 customer_5 ('customer_5', 'customer_2')
1935 customer_5 -18.517252871354366
resNode: customer_2 deliver_cap: 42.35841150832222 cap_limit: 40
4840 customer_5 ('customer_5', 'customer_4')
1935 customer_5 -18.517252871354366
resNode: customer_4 deliver_cap: 66.75089289061758 cap_limit: 40
4841 customer_2 ('customer_2', 'customer_3')
1938 customer_2 -9.452971827310062
resNode: customer_3 deliver_cap: 56.52525074981876 cap_limit: 40
4842 customer_2 ('customer_2', 'customer_1')
1938 customer_2 -9.452971827310062
resNode: customer_1 deliver_cap: 44.50844055262253 cap_limit: 40
4843 customer_2 ('customer_2', 'depot_t')

resNode: customer_3 deliver_cap: 58.71572841570386 cap_limit: 40
4882 customer_5 ('customer_5', 'customer_1')
1960 customer_5 -17.636551277713547
resNode: customer_1 deliver_cap: 49.82065321451949 cap_limit: 40
4883 customer_5 ('customer_5', 'depot_t')
1960 customer_5 -17.636551277713547
resNode: depot_t deliver_cap: 32.45318511609397 cap_limit: 40
4884 customer_5 ('customer_5', 'customer_2')
1960 customer_5 -17.636551277713547
resNode: customer_2 deliver_cap: 36.36491353247036 cap_limit: 40
4885 customer_5 ('customer_5', 'customer_4')
1960 customer_5 -17.636551277713547
resNode: customer_4 deliver_cap: 58.494535779742996 cap_limit: 40
4886 customer_3 ('customer_3', 'customer_1')
1961 customer_3 -13.823151547174703
resNode: customer_1 deliver_cap: 48.153527308370826 cap_limit: 40
4887 customer_3 ('customer_3', 'depot_t')
1961 customer_3 -13.823151547174703
resNode: depot_t deliver_cap: 34.11978752845101 cap_limit: 40
4888 customer_3 ('customer_3', 'customer_2')
1961 customer_3 -13.823151547174703
resNode: customer_2 deliver_cap: 38.15055897428148 cap_limit: 40
4889 customer_3 ('customer_3', 'customer_4')
1961 customer_3 -13.823151547174703
resNode: customer_4 deliver_cap: 48.35914047053534 cap_limit: 40
4890 customer_3 ('customer_3', 'customer_5')
1961 customer_3 -13.823151547174703
resNode: customer_5 deliver_cap: 43.86829825086559 cap_limit: 40
4891 customer_1 ('customer_1', 'customer_3')
1962 customer_1 -9.08981816064529
resNode: customer_3 deliver_cap: 46.559883543144 cap_limit: 40
4892 customer_1 ('customer_1', 'depot_t')
1962 customer_1 -9.08981816064529
resNode: depot_t deliver_cap: 26.15595777667698 cap_limit: 40
4893 customer_1 ('customer_1', 'customer_2')
1962 customer_1 -9.08981816064529
resNode: customer_2 deliver_cap: 28.53377212001125 cap_limit: 40
4894 customer_1 ('customer_1', 'customer_4')
1962 customer_1 -9.08981816064529
resNode: customer_4 deliver_cap: 46.0975372658894 cap_limit: 40
4895 customer_1 ('customer_1', 'customer_5')
1962 customer_1 -9.08981816064529
resNode: customer_5 deliver_cap: 35.8541509785941 cap_limit: 40
4896 customer_4 ('customer_4', 'customer_3')
1964 customer_4 -13.796526507660896
resNode: customer_3 deliver_cap: 48.359140470535344 cap_limit: 40
4897 customer_4 ('customer_4', 'customer_1')
1964 customer_4 -13.796526507660896
resNode: customer_1 deliver_cap: 47.69118103111623 cap_limit: 40
4898 customer_4 ('customer_4', 'depot_t')
1964 customer_4 -13.796526507660896
resNode: depot_t deliver_cap: 33.94774881159257 cap_limit: 40
4899 customer_4 ('customer_4', 'customer_2')
1964 customer_4 -13.796526507660896
resNode: customer_2 deliver_cap: 37.96623177764743 cap_limit: 40
4900 customer_4 ('customer_4', 'customer_5')
1964 customer_4 -13.796526507660896
resNode: customer_5 deliver_cap: 43.64710561490472 cap_limit: 40
4901 customer_5 ('customer_5', 'customer_3')
1965 customer_5 -11.866505190895772
resNode: customer_3 deliver_cap: 43.86829825086559 cap_limit: 40
4902 customer_5 ('customer_5', 'customer_1')
1965 customer_5 -11.866505190895772
resNode: customer_1 deliver_cap: 37.447794743820936 cap_limit: 40
4903 customer_5 ('customer_5', 'depot_t')
1965 customer_5 -11.866505190895772
resNode: depot_t deliver_cap: 20.90518387677532 cap_limit: 40
4904 customer_5 ('customer_5', 'customer_2')
1965 customer_5 -11.866505190895772
resNode: customer_2 deliver_cap: 23.992055061771815 cap_limit: 40
4905 customer_5 ('customer_5', 'customer_4')
1965 customer_5 -11.866505190895772
resNode: customer_4 deliver_cap: 43.64710561490472 cap_limit: 40
4906 customer_2 ('customer_2', 'customer_3')
1969 customer_2 -13.668258098026811
resNode: customer_3 deliver_cap: 60.63731030991633 cap_limit: 40
4907 customer_2 ('customer_2', 'customer_1')
1969 customer_2 -13.668258098026811
resNode: customer_1 deliver_cap: 49.64139186588969 cap_limit: 40
4908 customer_2 ('customer_2', 'depot_t')
1969 customer_2 -13.668258098026811
resNode: depot_t deliver_cap: 32.76258624099066 cap_limit: 40
4909 customer_2 ('customer_2', 'customer_4')
1969 customer_2 -13.668258098026811
resNode: customer_4 deliver_cap: 60.41611767395546 cap_limit: 40
4910 customer_2 ('customer_2', 'customer_5')
1969 customer_2 -13.668258098026811
resNode: customer_5 deliver_cap: 43.64710561490472 cap_limit: 40
4911 customer_5 ('customer_5', 'customer_3')
1970 customer_5 -20.748299479087947
resNode: customer_3 deliver_cap: 66.73468356768198 cap_limit: 40
4912 customer_5 ('customer_5', 'customer_1')
1970 customer_5 -20.748299479087947
resNode: customer_1 deliver_cap: 58.27021278544694 cap_limit: 40
4913 customer_5 ('customer_5', 'depot_t')
1970 customer_5 -20.748299479087947
resNode: depot_t deliver_cap: 37.97701083489825 cap_limit: 40
4914 customer_5 ('customer_5', 'customer_2')
1970 customer_5 -20.748299479087947
resNode: customer_2 deliver_cap: 42.12332516698798 cap_limit: 40
4915 customer_5 ('customer_5', 'customer_4')
1970 customer_5 -20.748299479087947
resNode: customer_4 deliver_cap: 66.4766254923943 cap_limit: 40
4916 customer_2 ('customer_2', 'customer_3')
1973 customer_2 -4.958173632702412
resNode: customer_3 deliver_cap: 48.34552898495512 cap_limit: 40
4917 customer_2 ('customer_2', 'customer_1')
1973 customer_2 -4.958173632702412
resNode: customer_1 deliver_cap: 37.96466314073162 cap_limit: 40
4918 customer_2 ('customer_2', 'depot_t')
1973 customer_2 -4.958173632702412
resNode: depot_t deliver_cap: 24.139285890510884 cap_limit: 40
4919 customer_2 ('customer_2', 'customer_4')
1973 customer_2 -4.958173632702412
resNode: customer_4 deliver_cap: 48.16120178832107 cap_limit: 40
4920 customer_2 ('customer_2', 'customer_5')
1973 customer_2 -4.958173632702412
resNode: customer_5 deliver_cap: 34.187025072445444 cap_limit: 40
4921 customer_5 ('customer_5', 'customer_3')
1975 customer_5 -12.461796263934534
resNode: customer_3 deliver_cap: 56.71517732832547 cap_limit: 40
4922 customer_5 ('customer_5', 'customer_1')
1975 customer_5 -12.461796263934534
resNode: customer_1 deliver_cap: 48.153527308370826 cap_limit: 40
4923 customer_5 ('customer_5', 'depot_t')
1975 customer_5 -12.461796263934534
resNode: depot_t deliver_cap: 30.897200937021882 cap_limit: 40
4924 customer_5 ('customer_5', 'customer_2')
1975 customer_5 -12.461796263934534
resNode: customer_2 deliver_cap: 34.6977876263217 cap_limit: 40
4925 customer_5 ('customer_5', 'customer_4')
1975 customer_5 -12.461796263934534
resNode: customer_4 deliver_cap: 56.4939846923646 cap_limit: 40
4926 customer_3 ('customer_3', 'customer_1')
1976 customer_3 -10.604966963906236
resNode: customer_1 deliver_cap: 49.939172750181946 cap_limit: 40
4927 customer_3 ('customer_3', 'depot_t')
1976 customer_3 -10.604966963906236
resNode: depot_t deliver_cap: 35.786389940808064 cap_limit: 40
4928 customer_3 ('customer_3', 'customer_2')
1976 customer_3 -10.604966963906236
resNode: customer_2 deliver_cap: 39.93620441609261 cap_limit: 40
4929 customer_3 ('customer_3', 'customer_4')
1976 customer_3 -10.604966963906236
resNode: customer_4 deliver_cap: 50.50191500070869 cap_limit: 40
4930 customer_3 ('customer_3', 'customer_5')
1976 customer_3 -10.604966963906236
resNode: customer_5 deliver_cap: 46.01107278103893 cap_limit: 40
4931 customer_1 ('customer_1', 'customer_3')
1977 customer_1 -5.425222216924041
resNode: customer_3 deliver_cap: 48.345528984955116 cap_limit: 40
4932 customer_1 ('customer_1', 'depot_t')
1977 customer_1 -5.425222216924041
resNode: depot_t deliver_cap: 27.4654311006718 cap_limit: 40
4933 customer_1 ('customer_1', 'customer_2')
1977 customer_1 -5.425222216924041
resNode: customer_2 deliver_cap: 29.962288473460145 cap_limit: 40
4934 customer_1 ('customer_1', 'customer_4')
1977 customer_1 -5.425222216924041
resNode: customer_4 deliver_cap: 47.88318270770053 cap_limit: 40
4935 customer_1 ('customer_1', 'customer_5')
1977 customer_1 -5.425222216924041
resNode: customer_5 deliver_cap: 37.639796420405226 cap_limit: 40
4936 customer_4 ('customer_4', 'customer_3')
1979 customer_4 -10.57834192439243
resNode: customer_3 deliver_cap: 50.50191500070869 cap_limit: 40
4937 customer_4 ('customer_4', 'customer_1')
1979 customer_4 -10.57834192439243
resNode: customer_1 deliver_cap: 49.47682647292735 cap_limit: 40
4938 customer_4 ('customer_4', 'depot_t')
1979 customer_4 -10.57834192439243
resNode: depot_t deliver_cap: 35.61435122394961 cap_limit: 40
4939 customer_4 ('customer_4', 'customer_2')
1979 customer_4 -10.57834192439243
resNode: customer_2 deliver_cap: 39.75187721945855 cap_limit: 40
4940 customer_4 ('customer_4', 'customer_5')
1979 customer_4 -10.57834192439243
resNode: customer_5 deliver_cap: 45.789880145078065 cap_limit: 40
4941 customer_5 ('customer_5', 'customer_3')
1980 customer_5 -8.648320607627303
resNode: customer_3 deliver_cap: 46.01107278103893 cap_limit: 40
4942 customer_5 ('customer_5', 'customer_1')
1980 customer_5 -8.648320607627303
resNode: customer_1 deliver_cap: 39.233440185632055 cap_limit: 40
4943 customer_5 ('customer_5', 'depot_t')
1980 customer_5 -8.648320607627303
resNode: depot_t deliver_cap: 22.57178628913237 cap_limit: 40
4944 customer_5 ('customer_5', 'customer_2')
1980 customer_5 -8.648320607627303
resNode: customer_2 deliver_cap: 25.777700503582935 cap_limit: 40
4945 customer_5 ('customer_5', 'customer_4')
1980 customer_5 -8.648320607627303
resNode: customer_4 deliver_cap: 45.78988014507807 cap_limit: 40
4946 customer_3 ('customer_3', 'customer_1')
1981 customer_3 -6.657626602214998
resNode: customer_1 deliver_cap: 48.70352671431819 cap_limit: 40
4947 customer_3 ('customer_3', 'depot_t')
1981 customer_3 -6.657626602214998
resNode: depot_t deliver_cap: 32.85494818429774 cap_limit: 40
4948 customer_3 ('customer_3', 'customer_2')
1981 customer_3 -6.657626602214998
resNode: customer_2 deliver_cap: 36.69996471341097 cap_limit: 40
4949 customer_3 ('customer_3', 'customer_4')
1981 customer_3 -6.657626602214998
resNode: customer_4 deliver_cap: 45.82484015060996 cap_limit: 40
4950 customer_3 ('customer_3', 'customer_5')
1981 customer_3 -6.657626602214998
resNode: customer_5 deliver_cap: 40.585524227661914 cap_limit: 40
4951 customer_1 ('customer_1', 'customer_3')
1982 customer_1 -6.256101183756517
resNode: customer_3 deliver_cap: 56.72907103369883 cap_limit: 40
4952 customer_1 ('customer_1', 'depot_t')
1982 customer_1 -6.256101183756517
resNode: depot_t deliver_cap: 33.95612030373337 cap_limit: 40
4953 customer_1 ('customer_1', 'customer_2')
1982 customer_1 -6.256101183756517
resNode: customer_2 deliver_cap: 36.381557468285756 cap_limit: 40
4954 customer_1 ('customer_1', 'customer_4')
1982 customer_1 -6.256101183756517
resNode: customer_4 deliver_cap: 56.17425550099332 cap_limit: 40
4955 customer_1 ('customer_1', 'customer_5')
1982 customer_1 -6.256101183756517
resNode: customer_5 deliver_cap: 43.882191956238955 cap_limit: 40
4956 customer_2 ('customer_2', 'customer_3')
1984 customer_2 -4.652048868383989
resNode: customer_3 deliver_cap: 50.50191500070869 cap_limit: 40
4957 customer_2 ('customer_2', 'customer_1')
1984 customer_2 -4.652048868383989
resNode: customer_1 deliver_cap: 41.19522910821665 cap_limit: 40
4958 customer_2 ('customer_2', 'depot_t')
1984 customer_2 -4.652048868383989
resNode: depot_t deliver_cap: 24.879501000495832 cap_limit: 40
4959 customer_2 ('customer_2', 'customer_4')
1984 customer_2 -4.652048868383989
resNode: customer_4 deliver_cap: 50.28072236474782 cap_limit: 40
4960 customer_2 ('customer_2', 'customer_5')
1984 customer_2 -4.652048868383989
resNode: customer_5 deliver_cap: 33.511710305697086 cap_limit: 40
4961 customer_5 ('customer_5', 'customer_3')
1985 customer_5 -9.620549560026868
resNode: customer_3 deliver_cap: 54.91005570693973 cap_limit: 40
4962 customer_5 ('customer_5', 'customer_1')
1985 customer_5 -9.620549560026868
resNode: customer_1 deliver_cap: 48.1348174762393 cap_limit: 40
4963 customer_5 ('customer_5', 'depot_t')
1985 customer_5 -9.620549560026868
resNode: depot_t deliver_cap: 28.404693042868814 cap_limit: 40
4964 customer_5 ('customer_5', 'customer_2')
1985 customer_5 -9.620549560026868
resNode: customer_2 deliver_cap: 31.98792985778035 cap_limit: 40
4965 customer_5 ('customer_5', 'customer_4')
1985 customer_5 -9.620549560026868
resNode: customer_4 deliver_cap: 54.65199763165206 cap_limit: 40
4966 customer_1 ('customer_1', 'customer_3')
1987 customer_1 -10.311729860881474
resNode: customer_3 deliver_cap: 56.71517732832547 cap_limit: 40
4967 customer_1 ('customer_1', 'depot_t')
1987 customer_1 -10.311729860881474
resNode: depot_t deliver_cap: 33.945314088442984 cap_limit: 40
4968 customer_1 ('customer_1', 'customer_2')
1987 customer_1 -10.311729860881474
resNode: customer_2 deliver_cap: 36.36997938047462 cap_limit: 40
4969 customer_1 ('customer_1', 'customer_4')
1987 customer_1 -10.311729860881474
resNode: customer_4 deliver_cap: 56.16036179561995 cap_limit: 40
4970 customer_1 ('customer_1', 'customer_5')
1987 customer_1 -10.311729860881474
resNode: customer_5 deliver_cap: 43.86829825086559 cap_limit: 40
4971 customer_2 ('customer_2', 'customer_3')
1989 customer_2 -7.588440416934848
resNode: customer_3 deliver_cap: 46.01107278103895 cap_limit: 40
4972 customer_2 ('customer_2', 'customer_1')
1989 customer_2 -7.588440416934848
resNode: customer_1 deliver_cap: 37.452860591825186 cap_limit: 40
4973 customer_2 ('customer_2', 'depot_t')
1989 customer_2 -7.588440416934848
resNode: depot_t deliver_cap: 21.38662371853047 cap_limit: 40
4974 customer_2 ('customer_2', 'customer_4')
1989 customer_2 -7.588440416934848
resNode: customer_4 deliver_cap: 45.78988014507807 cap_limit: 40
4975 customer_2 ('customer_2', 'customer_5')
1989 customer_2 -7.588440416934848
resNode: customer_5 deliver_cap: 29.020868086027335 cap_limit: 40
4976 customer_1 ('customer_1', 'customer_3')
1991 customer_1 -7.980520667423341
resNode: customer_3 deliver_cap: 53.81284475973411 cap_limit: 40
4977 customer_1 ('customer_1', 'depot_t')
1991 customer_1 -7.980520667423341
resNode: depot_t deliver_cap: 31.474796002176397 cap_limit: 40
4978 customer_1 ('customer_1', 'customer_2')
1991 customer_1 -7.980520667423341
resNode: customer_2 deliver_cap: 34.336141093283345 cap_limit: 40
4979 customer_1 ('customer_1', 'customer_4')
1991 customer_1 -7.980520667423341
resNode: customer_4 deliver_cap: 53.35049848247952 cap_limit: 40
4980 customer_1 ('customer_1', 'customer_5')
1991 customer_1 -7.980520667423341
resNode: customer_5 deliver_cap: 43.10711219518422 cap_limit: 40
4981 customer_2 ('customer_2', 'customer_3')
1993 customer_2 -6.793211044569115
resNode: customer_3 deliver_cap: 48.345528984955116 cap_limit: 40
4982 customer_2 ('customer_2', 'customer_1')
1993 customer_2 -6.793211044569115
resNode: customer_1 deliver_cap: 37.964663140731616 cap_limit: 40
4983 customer_2 ('customer_2', 'depot_t')
1993 customer_2 -6.793211044569115
resNode: depot_t deliver_cap: 24.139285890510877 cap_limit: 40
4984 customer_2 ('customer_2', 'customer_4')
1993 customer_2 -6.793211044569115
resNode: customer_4 deliver_cap: 48.16120178832106 cap_limit: 40
4985 customer_2 ('customer_2', 'customer_5')
1993 customer_2 -6.793211044569115
resNode: customer_5 deliver_cap: 34.18702507244544 cap_limit: 40
4986 customer_4 ('customer_4', 'customer_3')
1994 customer_4 -10.22066109592085
resNode: customer_3 deliver_cap: 46.79115419604599 cap_limit: 40
4987 customer_4 ('customer_4', 'customer_1')
1994 customer_4 -10.22066109592085
resNode: customer_1 deliver_cap: 46.384525802375094 cap_limit: 40
4988 customer_4 ('customer_4', 'depot_t')
1994 customer_4 -10.22066109592085
resNode: depot_t deliver_cap: 32.72820393143417 cap_limit: 40
4989 customer_4 ('customer_4', 'customer_2')
1994 customer_4 -10.22066109592085
resNode: customer_2 deliver_cap: 36.659576548906294 cap_limit: 40
4990 customer_4 ('customer_4', 'customer_5')
1994 customer_4 -10.22066109592085
resNode: customer_5 deliver_cap: 42.07911934041536 cap_limit: 40
4991 customer_5 ('customer_5', 'customer_3')
1995 customer_5 -13.406543878897807
resNode: customer_3 deliver_cap: 54.57848181575723 cap_limit: 40
4992 customer_5 ('customer_5', 'customer_1')
1995 customer_5 -13.406543878897807
resNode: customer_1 deliver_cap: 46.372947714563956 cap_limit: 40
4993 customer_5 ('customer_5', 'depot_t')
1995 customer_5 -13.406543878897807
resNode: depot_t deliver_cap: 29.23532664946881 cap_limit: 40
4994 customer_5 ('customer_5', 'customer_2')
1995 customer_5 -13.406543878897807
resNode: customer_2 deliver_cap: 32.917208032514836 cap_limit: 40
4995 customer_5 ('customer_5', 'customer_4')
1995 customer_5 -13.406543878897807
resNode: customer_4 deliver_cap: 54.35728917979635 cap_limit: 40
4996 customer_3 ('customer_3', 'customer_1')
1996 customer_3 -7.709665862076736
resNode: customer_1 deliver_cap: 37.964663140731616 cap_limit: 40
4997 customer_3 ('customer_3', 'depot_t')
1996 customer_3 -7.709665862076736
resNode: depot_t deliver_cap: 26.296759006172127 cap_limit: 40
4998 customer_3 ('customer_3', 'customer_2')
1996 customer_3 -7.709665862076736
resNode: customer_2 deliver_cap: 29.962288473460145 cap_limit: 40
4999 customer_3 ('customer_3', 'customer_4')
1996 customer_3 -7.709665862076736
resNode: customer_4 deliver_cap: 39.601585342989814 cap_limit: 40
5000 customer_3 ('customer_3', 'customer_5')
1996 customer_3 -7.709665862076736
resNode: customer_5 deliver_cap: 35.859216826598356 cap_limit: 40
5001 customer_1 ('customer_1', 'customer_3')
1997 customer_1 -3.1952420741134295
resNode: customer_3 deliver_cap: 36.68974812855016 cap_limit: 40
5002 customer_1 ('customer_1', 'depot_t')
1997 customer_1 -3.1952420741134295
resNode: depot_t deliver_cap: 18.650408942697474 cap_limit: 40
5003 customer_1 ('customer_1', 'customer_2')
1997 customer_1 -3.1952420741134295
resNode: customer_2 deliver_cap: 20.981710060534656 cap_limit: 40
5004 customer_1 ('customer_1', 'customer_4')
1997 customer_1 -3.1952420741134295
resNode: customer_4 deliver_cap: 36.319871106746476 cap_limit: 40
5005 customer_1 ('customer_1', 'customer_5')
1997 customer_1 -3.1952420741134295
resNode: customer_5 deliver_cap: 28.12516207691024 cap_limit: 40
5006 customer_4 ('customer_4', 'customer_3')
1999 customer_4 -7.692257182394634
resNode: customer_3 deliver_cap: 39.60158534298982 cap_limit: 40
5007 customer_4 ('customer_4', 'customer_1')
1999 customer_4 -7.692257182394634
resNode: customer_1 deliver_cap: 37.59478611892794 cap_limit: 40
5008 customer_4 ('customer_4', 'depot_t')
1999 customer_4 -7.692257182394634
resNode: depot_t deliver_cap: 26.16158572864049 cap_limit: 40
5009 customer_4 ('customer_4', 'customer_2')
1999 customer_4 -7.692257182394634
resNode: customer_2 deliver_cap: 29.8148267161529 cap_limit: 40
5010 customer_4 ('customer_4', 'customer_5')
1999 customer_4 -7.692257182394634
resNode: customer_5 deliver_cap: 35.6748896299643 cap_limit: 40
5011 customer_5 ('customer_5', 'customer_3')
2000 customer_5 -6.460944701423291
resNode: customer_3 deliver_cap: 35.859216826598356 cap_limit: 40
5012 customer_5 ('customer_5', 'customer_1')
2000 customer_5 -6.460944701423291
resNode: customer_1 deliver_cap: 29.400077089091702 cap_limit: 40
5013 customer_5 ('customer_5', 'depot_t')
2000 customer_5 -6.460944701423291
resNode: depot_t deliver_cap: 15.913856136998369 cap_limit: 40
5014 customer_5 ('customer_5', 'customer_2')
2000 customer_5 -6.460944701423291
resNode: customer_2 deliver_cap: 18.63548534345241 cap_limit: 40
5015 customer_5 ('customer_5', 'customer_4')
2000 customer_5 -6.460944701423291
resNode: customer_4 deliver_cap: 35.6748896299643 cap_limit: 40
5016 customer_3 ('customer_3', 'customer_1')
2001 customer_3 -9.958359215009356
resNode: customer_1 deliver_cap: 46.384525802375094 cap_limit: 40
5017 customer_3 ('customer_3', 'depot_t')
2001 customer_3 -9.958359215009356
resNode: depot_t deliver_cap: 32.46871945618834 cap_limit: 40
5018 customer_3 ('customer_3', 'customer_2')
2001 customer_3 -9.958359215009356
resNode: customer_2 deliver_cap: 36.381557468285756 cap_limit: 40
5019 customer_3 ('customer_3', 'customer_4')
2001 customer_3 -9.958359215009356
resNode: customer_4 deliver_cap: 46.23633866334047 cap_limit: 40

resNode: customer_4 deliver_cap: 50.28072236474782 cap_limit: 40
5090 customer_3 ('customer_3', 'customer_5')
2021 customer_3 -10.516899525514411
resNode: customer_5 deliver_cap: 45.78988014507807 cap_limit: 40
5091 customer_1 ('customer_1', 'customer_3')
2022 customer_1 -5.383236577690731
resNode: customer_3 deliver_cap: 48.161201788321065 cap_limit: 40
5092 customer_1 ('customer_1', 'depot_t')
2022 customer_1 -5.383236577690731
resNode: depot_t deliver_cap: 27.330257823140165 cap_limit: 40
5093 customer_1 ('customer_1', 'customer_2')
2022 customer_1 -5.383236577690731
resNode: customer_2 deliver_cap: 29.8148267161529 cap_limit: 40
5094 customer_1 ('customer_1', 'customer_4')
2022 customer_1 -5.383236577690731
resNode: customer_4 deliver_cap: 47.69885551106646 cap_limit: 40
5095 customer_1 ('customer_1', 'customer_5')
2022 customer_1 -5.383236577690731
resNode: customer_5 deliver_cap: 37.45546922377117 cap_limit: 40
5096 customer_4 ('customer_4', 'customer_3')
2024 customer_4 -10.490274486000605
resNode: customer_3 deliver_cap: 50.28072236474783 cap_limit: 40
5097 customer_4 ('customer_4', 'customer_1')
2024 customer_4 -10.490274486000605
resNode: customer_1 deliver_cap: 49.2924992762933 cap_limit: 40
5098 customer_4 ('customer_4', 'depot_t')
2024 customer_4 -10.490274486000605
resNode: depot_t deliver_cap: 35.44231250709116 cap_limit: 40
5099 customer_4 ('customer_4', 'customer_2')
2024 customer_4 -10.490274486000605
resNode: customer_2 deliver_cap: 39.5675500228245 cap_limit: 40
5100 customer_4 ('customer_4', 'customer_5')
2024 customer_4 -10.490274486000605
resNode: customer_5 deliver_cap: 45.5686875091172 cap_limit: 40
5101 customer_5 ('customer_5', 'customer_3')
2025 customer_5 -8.56025316923548
resNode: customer_3 deliver_cap: 45.78988014507807 cap_limit: 40
5102 customer_5 ('customer_5', 'customer_1')
2025 customer_5 -8.56025316923548
resNode: customer_1 deliver_cap: 39.049112988998 cap_limit: 40
5103 customer_5 ('customer_5', 'depot_t')
2025 customer_5 -8.56025316923548
resNode: depot_t deliver_cap: 22.399747572273917 cap_limit: 40
5104 customer_5 ('customer_5', 'customer_2')
2025 customer_5 -8.56025316923548
resNode: customer_2 deliver_cap: 25.593373306948884 cap_limit: 40
5105 customer_5 ('customer_5', 'customer_4')
2025 customer_5 -8.56025316923548
resNode: customer_4 deliver_cap: 45.5686875091172 cap_limit: 40
5106 customer_1 ('customer_1', 'customer_3')
2027 customer_1 -10.223662422489646
resNode: customer_3 deliver_cap: 56.49398469236459 cap_limit: 40
5107 customer_1 ('customer_1', 'depot_t')
2027 customer_1 -10.223662422489646
resNode: depot_t deliver_cap: 33.773275371584525 cap_limit: 40
5108 customer_1 ('customer_1', 'customer_2')
2027 customer_1 -10.223662422489646
resNode: customer_2 deliver_cap: 36.18565218384056 cap_limit: 40
5109 customer_1 ('customer_1', 'customer_4')
2027 customer_1 -10.223662422489646
resNode: customer_4 deliver_cap: 55.93916915965907 cap_limit: 40
5110 customer_1 ('customer_1', 'customer_5')
2027 customer_1 -10.223662422489646
resNode: customer_5 deliver_cap: 43.64710561490472 cap_limit: 40
5111 customer_2 ('customer_2', 'customer_3')
2029 customer_2 -7.5003729785430195
resNode: customer_3 deliver_cap: 45.78988014507807 cap_limit: 40
5112 customer_2 ('customer_2', 'customer_1')
2029 customer_2 -7.5003729785430195
resNode: customer_1 deliver_cap: 37.26853339519113 cap_limit: 40
5113 customer_2 ('customer_2', 'depot_t')
2029 customer_2 -7.5003729785430195
resNode: depot_t deliver_cap: 21.214585001672013 cap_limit: 40
5114 customer_2 ('customer_2', 'customer_4')
2029 customer_2 -7.5003729785430195
resNode: customer_4 deliver_cap: 45.5686875091172 cap_limit: 40
5115 customer_2 ('customer_2', 'customer_5')
2029 customer_2 -7.5003729785430195
resNode: customer_5 deliver_cap: 28.799675450066463 cap_limit: 40
5116 customer_4 ('customer_4', 'customer_3')
2030 customer_4 -14.115929894488424
resNode: customer_3 deliver_cap: 54.65199763165206 cap_limit: 40
5117 customer_4 ('customer_4', 'customer_1')
2030 customer_4 -14.115929894488424
resNode: customer_1 deliver_cap: 55.71484616536303 cap_limit: 40
5118 customer_4 ('customer_4', 'depot_t')
2030 customer_4 -14.115929894488424
resNode: depot_t deliver_cap: 39.79183817943227 cap_limit: 40
5119 customer_4 ('customer_4', 'customer_2')
2030 customer_4 -14.115929894488424
resNode: customer_2 deliver_cap: 44.044907061200476 cap_limit: 40
5120 customer_4 ('customer_4', 'customer_5')
2030 customer_4 -14.115929894488424
resNode: customer_5 deliver_cap: 49.15462363341632 cap_limit: 40
5121 customer_1 ('customer_1', 'customer_3')
2031 customer_1 -5.500297413157623
resNode: customer_3 deliver_cap: 52.57185171077373 cap_limit: 40
5122 customer_1 ('customer_1', 'depot_t')
2031 customer_1 -5.500297413157623
resNode: depot_t deliver_cap: 30.72272749701385 cap_limit: 40
5123 customer_1 ('customer_1', 'customer_2')
2031 customer_1 -5.500297413157623
resNode: customer_2 deliver_cap: 32.91720803251484 cap_limit: 40
5124 customer_1 ('customer_1', 'customer_4')
2031 customer_1 -5.500297413157623
resNode: customer_4 deliver_cap: 52.01703617806821 cap_limit: 40
5125 customer_1 ('customer_1', 'customer_5')
2031 customer_1 -5.500297413157623
resNode: customer_5 deliver_cap: 39.72497263331385 cap_limit: 40
5126 customer_2 ('customer_2', 'customer_3')
2033 customer_2 -3.8128393735989334
resNode: customer_3 deliver_cap: 46.01107278103893 cap_limit: 40
5127 customer_2 ('customer_2', 'customer_1')
2033 customer_2 -3.8128393735989334
resNode: customer_1 deliver_cap: 37.45286059182518 cap_limit: 40
5128 customer_2 ('customer_2', 'depot_t')
2033 customer_2 -3.8128393735989334
resNode: depot_t deliver_cap: 21.386623718530466 cap_limit: 40
5129 customer_2 ('customer_2', 'customer_4')
2033 customer_2 -3.8128393735989334
resNode: customer_4 deliver_cap: 45.78988014507807 cap_limit: 40
5130 customer_2 ('customer_2', 'customer_5')
2033 customer_2 -3.8128393735989334
resNode: customer_5 deliver_cap: 29.020868086027328 cap_limit: 40
5131 customer_4 ('customer_4', 'customer_3')
2034 customer_4 -4.846983578986567
resNode: customer_3 deliver_cap: 40.585524227661914 cap_limit: 40
5132 customer_4 ('customer_4', 'customer_1')
2034 customer_4 -4.846983578986567
resNode: customer_1 deliver_cap: 43.65786896194291 cap_limit: 40
5133 customer_4 ('customer_4', 'depot_t')
2034 customer_4 -4.846983578986567
resNode: depot_t deliver_cap: 28.40469304286882 cap_limit: 40
5134 customer_4 ('customer_4', 'customer_2')
2034 customer_4 -4.846983578986567
resNode: customer_2 deliver_cap: 31.987929857780355 cap_limit: 40
5135 customer_4 ('customer_4', 'customer_5')
2034 customer_4 -4.846983578986567
resNode: customer_5 deliver_cap: 35.088150229426184 cap_limit: 40
5136 customer_5 ('customer_5', 'customer_3')
2035 customer_5 -7.8457479361439475
resNode: customer_3 deliver_cap: 49.67073978399169 cap_limit: 40
5137 customer_5 ('customer_5', 'customer_1')
2035 customer_5 -7.8457479361439475
resNode: customer_1 deliver_cap: 43.64397525656955 cap_limit: 40
5138 customer_5 ('customer_5', 'depot_t')
2035 customer_5 -7.8457479361439475
resNode: depot_t deliver_cap: 24.163342057625165 cap_limit: 40
5139 customer_5 ('customer_5', 'customer_2')
2035 customer_5 -7.8457479361439475
resNode: customer_2 deliver_cap: 27.497087638110603 cap_limit: 40
5140 customer_5 ('customer_5', 'customer_4')
2035 customer_5 -7.8457479361439475
resNode: customer_4 deliver_cap: 49.412681708704014 cap_limit: 40
5141 customer_3 ('customer_3', 'customer_1')
2036 customer_3 -7.972479716295293
resNode: customer_1 deliver_cap: 44.700755960411044 cap_limit: 40
5142 customer_3 ('customer_3', 'depot_t')
2036 customer_3 -7.972479716295293
resNode: depot_t deliver_cap: 30.897200937021882 cap_limit: 40
5143 customer_3 ('customer_3', 'customer_2')
2036 customer_3 -7.972479716295293
resNode: customer_2 deliver_cap: 34.6977876263217 cap_limit: 40
5144 customer_3 ('customer_3', 'customer_4')
2036 customer_3 -7.972479716295293
resNode: customer_4 deliver_cap: 44.215814852983605 cap_limit: 40
5145 customer_3 ('customer_3', 'customer_5')
2036 customer_3 -7.972479716295293
resNode: customer_5 deliver_cap: 39.72497263331385 cap_limit: 40
5146 customer_2 ('customer_2', 'customer_3')
2038 customer_2 -2.9150295439016016
resNode: customer_3 deliver_cap: 37.639796420405226 cap_limit: 40
5147 customer_2 ('customer_2', 'customer_1')
2038 customer_2 -2.9150295439016016
resNode: customer_1 deliver_cap: 29.4000770890917 cap_limit: 40
5148 customer_2 ('customer_2', 'depot_t')
2038 customer_2 -2.9150295439016016
resNode: depot_t deliver_cap: 16.28841534317429 cap_limit: 40
5149 customer_2 ('customer_2', 'customer_4')
2038 customer_2 -2.9150295439016016
resNode: customer_4 deliver_cap: 37.45546922377117 cap_limit: 40
5150 customer_2 ('customer_2', 'customer_5')
2038 customer_2 -2.9150295439016016
resNode: customer_5 deliver_cap: 23.48129250789555 cap_limit: 40
5151 customer_4 ('customer_4', 'customer_3')
2039 customer_4 -7.806845136471214
resNode: customer_3 deliver_cap: 43.882191956238955 cap_limit: 40
5152 customer_4 ('customer_4', 'customer_1')
2039 customer_4 -7.806845136471214
resNode: customer_1 deliver_cap: 43.9603906025359 cap_limit: 40
5153 customer_4 ('customer_4', 'depot_t')
2039 customer_4 -7.806845136471214
resNode: depot_t deliver_cap: 30.465677744917592 cap_limit: 40
5154 customer_4 ('customer_4', 'customer_2')
2039 customer_4 -7.806845136471214
resNode: customer_2 deliver_cap: 34.2354413490671 cap_limit: 40
5155 customer_4 ('customer_4', 'customer_5')
2039 customer_4 -7.806845136471214
resNode: customer_5 deliver_cap: 39.17015710060833 cap_limit: 40
5156 customer_5 ('customer_5', 'customer_3')
2040 customer_5 -7.7422190339962516
resNode: customer_3 deliver_cap: 43.86829825086559 cap_limit: 40
5157 customer_5 ('customer_5', 'customer_1')
2040 customer_5 -7.7422190339962516
resNode: customer_1 deliver_cap: 37.44779474382093 cap_limit: 40
5158 customer_5 ('customer_5', 'depot_t')
2040 customer_5 -7.7422190339962516
resNode: depot_t deliver_cap: 20.905183876775318 cap_limit: 40
5159 customer_5 ('customer_5', 'customer_2')
2040 customer_5 -7.7422190339962516
resNode: customer_2 deliver_cap: 23.99205506177181 cap_limit: 40
5160 customer_5 ('customer_5', 'customer_4')
2040 customer_5 -7.7422190339962516
resNode: customer_4 deliver_cap: 43.64710561490472 cap_limit: 40
5161 customer_3 ('customer_3', 'customer_1')
2041 customer_3 -3.9288193034574133
resNode: customer_1 deliver_cap: 35.78066883767227 cap_limit: 40
5162 customer_3 ('customer_3', 'depot_t')
2041 customer_3 -3.9288193034574133
resNode: depot_t deliver_cap: 22.57178628913237 cap_limit: 40
5163 customer_3 ('customer_3', 'customer_2')
2041 customer_3 -3.9288193034574133
resNode: customer_2 deliver_cap: 25.777700503582935 cap_limit: 40
5164 customer_3 ('customer_3', 'customer_4')
2041 customer_3 -3.9288193034574133
resNode: customer_4 deliver_cap: 33.51171030569708 cap_limit: 40
5165 customer_3 ('customer_3', 'customer_5')
2041 customer_3 -3.9288193034574133
resNode: customer_5 deliver_cap: 29.020868086027328 cap_limit: 40
5166 customer_1 ('customer_1', 'customer_3')
2042 customer_1 -2.288700534602636
resNode: customer_3 deliver_cap: 34.187025072445444 cap_limit: 40
5167 customer_1 ('customer_1', 'depot_t')
2042 customer_1 -2.288700534602636
resNode: depot_t deliver_cap: 17.08252823149804 cap_limit: 40
5168 customer_1 ('customer_1', 'customer_2')
2042 customer_1 -2.288700534602636
resNode: customer_2 deliver_cap: 18.63548534345241 cap_limit: 40
5169 customer_1 ('customer_1', 'customer_4')
2042 customer_1 -2.288700534602636
resNode: customer_4 deliver_cap: 33.72467879519085 cap_limit: 40
5170 customer_1 ('customer_1', 'customer_5')
2042 customer_1 -2.288700534602636
resNode: customer_5 deliver_cap: 23.48129250789555 cap_limit: 40
5171 customer_4 ('customer_4', 'customer_3')
2044 customer_4 -3.902194263943603
resNode: customer_3 deliver_cap: 33.511710305697086 cap_limit: 40
5172 customer_4 ('customer_4', 'customer_1')
2044 customer_4 -3.902194263943603
resNode: customer_1 deliver_cap: 35.31832256041768 cap_limit: 40
5173 customer_4 ('customer_4', 'depot_t')
2044 customer_4 -3.902194263943603
resNode: depot_t deliver_cap: 22.399747572273913 cap_limit: 40
5174 customer_4 ('customer_4', 'customer_2')
2044 customer_4 -3.902194263943603
resNode: customer_2 deliver_cap: 25.59337330694888 cap_limit: 40
5175 customer_4 ('customer_4', 'customer_5')
2044 customer_4 -3.902194263943603
resNode: customer_5 deliver_cap: 28.799675450066463 cap_limit: 40
5176 customer_5 ('customer_5', 'customer_3')
2045 customer_5 -1.9721729471784797
resNode: customer_3 deliver_cap: 29.020868086027328 cap_limit: 40
5177 customer_5 ('customer_5', 'customer_1')
2045 customer_5 -1.9721729471784797
resNode: customer_1 deliver_cap: 25.07493627312238 cap_limit: 40
5178 customer_5 ('customer_5', 'depot_t')
2045 customer_5 -1.9721729471784797
resNode: depot_t deliver_cap: 9.35718263745667 cap_limit: 40
5179 customer_5 ('customer_5', 'customer_2')
2045 customer_5 -1.9721729471784797
resNode: customer_2 deliver_cap: 11.61919659107326 cap_limit: 40
5180 customer_5 ('customer_5', 'customer_4')
2045 customer_5 -1.9721729471784797
resNode: customer_4 deliver_cap: 28.79967545006646 cap_limit: 40
5181 customer_3 ('customer_3', 'customer_1')
2046 customer_3 -4.797829659884149
resNode: customer_1 deliver_cap: 43.99149185868755 cap_limit: 40
5182 customer_3 ('customer_3', 'depot_t')
2046 customer_3 -4.797829659884149
resNode: depot_t deliver_cap: 28.40469304286882 cap_limit: 40
5183 customer_3 ('customer_3', 'customer_2')
2046 customer_3 -4.797829659884149
resNode: customer_2 deliver_cap: 31.987929857780355 cap_limit: 40
5184 customer_3 ('customer_3', 'customer_4')
2046 customer_3 -4.797829659884149
resNode: customer_4 deliver_cap: 40.327466152374235 cap_limit: 40
5185 customer_3 ('customer_3', 'customer_5')
2046 customer_3 -4.797829659884149
resNode: customer_5 deliver_cap: 35.088150229426184 cap_limit: 40
5186 customer_1 ('customer_1', 'customer_3')
2047 customer_1 -5.377978169682049
resNode: customer_3 deliver_cap: 52.01703617806821 cap_limit: 40
5187 customer_1 ('customer_1', 'depot_t')
2047 customer_1 -5.377978169682049
resNode: depot_t deliver_cap: 30.291204304909556 cap_limit: 40
5188 customer_1 ('customer_1', 'customer_2')
2047 customer_1 -5.377978169682049
resNode: customer_2 deliver_cap: 32.45486175526024 cap_limit: 40
5189 customer_1 ('customer_1', 'customer_4')
2047 customer_1 -5.377978169682049
resNode: customer_4 deliver_cap: 51.4622206453627 cap_limit: 40
5190 customer_1 ('customer_1', 'customer_5')
2047 customer_1 -5.377978169682049
resNode: customer_5 deliver_cap: 39.170157100608336 cap_limit: 40
5191 customer_2 ('customer_2', 'customer_3')
2049 customer_2 -3.77392585430952
resNode: customer_3 deliver_cap: 45.78988014507807 cap_limit: 40
5192 customer_2 ('customer_2', 'customer_1')
2049 customer_2 -3.77392585430952
resNode: customer_1 deliver_cap: 37.26853339519113 cap_limit: 40
5193 customer_2 ('customer_2', 'depot_t')
2049 customer_2 -3.77392585430952
resNode: depot_t deliver_cap: 21.214585001672013 cap_limit: 40
5194 customer_2 ('customer_2', 'customer_4')
2049 customer_2 -3.77392585430952
resNode: customer_4 deliver_cap: 45.5686875091172 cap_limit: 40
5195 customer_2 ('customer_2', 'customer_5')
2049 customer_2 -3.77392585430952
resNode: customer_5 deliver_cap: 28.799675450066463 cap_limit: 40
5196 customer_5 ('customer_5', 'customer_3')
2050 customer_5 -7.760752617696019
resNode: customer_3 deliver_cap: 49.41268170870401 cap_limit: 40
5197 customer_5 ('customer_5', 'customer_1')
2050 customer_5 -7.760752617696019
resNode: customer_1 deliver_cap: 43.42278262060868 cap_limit: 40
5198 customer_5 ('customer_5', 'depot_t')
2050 customer_5 -7.760752617696019
resNode: depot_t deliver_cap: 23.954437901439896 cap_limit: 40
5199 customer_5 ('customer_5', 'customer_2')
2050 customer_5 -7.760752617696019
resNode: customer_2 deliver_cap: 27.27589500214973 cap_limit: 40
5200 customer_5 ('customer_5', 'customer_4')
2050 customer_5 -7.760752617696019
resNode: customer_4 deliver_cap: 49.154623633416335 cap_limit: 40
5201 customer_2 ('customer_2', 'customer_3')
2053 customer_2 -5.764391702075098
resNode: customer_3 deliver_cap: 59.06932403542697 cap_limit: 40
5202 customer_2 ('customer_2', 'customer_1')
2053 customer_2 -5.764391702075098
resNode: customer_1 deliver_cap: 48.33473663714855 cap_limit: 40
5203 customer_2 ('customer_2', 'depot_t')
2053 customer_2 -5.764391702075098
resNode: depot_t deliver_cap: 31.54304136083227 cap_limit: 40
5204 customer_2 ('customer_2', 'customer_4')
2053 customer_2 -5.764391702075098
resNode: customer_4 deliver_cap: 58.8481313994661 cap_limit: 40
5205 customer_2 ('customer_2', 'customer_5')
2053 customer_2 -5.764391702075098
resNode: customer_5 deliver_cap: 42.07911934041536 cap_limit: 40
5206 customer_5 ('customer_5', 'customer_3')
2055 customer_5 -13.497088052544727
resNode: customer_3 deliver_cap: 67.39817767877402 cap_limit: 40
5207 customer_5 ('customer_5', 'customer_1')
2055 customer_5 -13.497088052544727
resNode: customer_1 deliver_cap: 58.838922023525825 cap_limit: 40
5208 customer_5 ('customer_5', 'depot_t')
2055 customer_5 -13.497088052544727
resNode: depot_t deliver_cap: 38.514125115306086 cap_limit: 40
5209 customer_5 ('customer_5', 'customer_2')
2055 customer_5 -13.497088052544727
resNode: customer_2 deliver_cap: 42.69203440506687 cap_limit: 40
5210 customer_5 ('customer_5', 'customer_4')
2055 customer_5 -13.497088052544727
resNode: customer_4 deliver_cap: 67.14011960348634 cap_limit: 40
5211 customer_1 ('customer_1', 'customer_3')
2057 customer_1 -6.458222914262246
resNode: customer_3 deliver_cap: 59.06932403542697 cap_limit: 40
5212 customer_1 ('customer_1', 'depot_t')
2057 customer_1 -6.458222914262246
resNode: depot_t deliver_cap: 35.77631708285526 cap_limit: 40
5213 customer_1 ('customer_1', 'customer_2')
2057 customer_1 -6.458222914262246
resNode: customer_2 deliver_cap: 38.33176830305921 cap_limit: 40
5214 customer_1 ('customer_1', 'customer_4')
2057 customer_1 -6.458222914262246
resNode: customer_4 deliver_cap: 58.51450850272146 cap_limit: 40
5215 customer_1 ('customer_1', 'customer_5')
2057 customer_1 -6.458222914262246
resNode: customer_5 deliver_cap: 46.2224449579671 cap_limit: 40
5216 customer_5 ('customer_5', 'customer_3')
2060 customer_5 -9.237608040100563
resNode: customer_3 deliver_cap: 54.91005570693973 cap_limit: 40
5217 customer_5 ('customer_5', 'customer_1')
2060 customer_5 -9.237608040100563
resNode: customer_1 deliver_cap: 48.1348174762393 cap_limit: 40
5218 customer_5 ('customer_5', 'depot_t')
2060 customer_5 -9.237608040100563
resNode: depot_t deliver_cap: 28.40469304286882 cap_limit: 40
5219 customer_5 ('customer_5', 'customer_2')
2060 customer_5 -9.237608040100563
resNode: customer_2 deliver_cap: 31.987929857780355 cap_limit: 40
5220 customer_5 ('customer_5', 'customer_4')
2060 customer_5 -9.237608040100563
resNode: customer_4 deliver_cap: 54.65199763165206 cap_limit: 40
5221 customer_3 ('customer_3', 'customer_1')
2061 customer_3 -7.706921133709741
resNode: customer_1 deliver_cap: 58.051251962432175 cap_limit: 40
5222 customer_3 ('customer_3', 'depot_t')
2061 customer_3 -7.706921133709741
resNode: depot_t deliver_cap: 39.82475716513291 cap_limit: 40
5223 customer_3 ('customer_3', 'customer_2')
2061 customer_3 -7.706921133709741
resNode: customer_2 deliver_cap: 44.0470962947071 cap_limit: 40
5224 customer_3 ('customer_3', 'customer_4')
2061 customer_3 -7.706921133709741
resNode: customer_4 deliver_cap: 53.777498224385816 cap_limit: 40
5225 customer_3 ('customer_3', 'customer_5')
2061 customer_3 -7.706921133709741
resNode: customer_5 deliver_cap: 47.78970859815948 cap_limit: 40
5226 customer_2 ('customer_2', 'customer_3')
2064 customer_2 -5.36496387468029
resNode: customer_3 deliver_cap: 60.14937162988778 cap_limit: 40
5227 customer_2 ('customer_2', 'customer_1')
2064 customer_2 -5.36496387468029
resNode: customer_1 deliver_cap: 50.488964183340805 cap_limit: 40

5296 customer_2 ('customer_2', 'customer_3')
2109 customer_2 -7.668395211559411
resNode: customer_3 deliver_cap: 45.78988014507807 cap_limit: 40
5297 customer_2 ('customer_2', 'customer_1')
2109 customer_2 -7.668395211559411
resNode: customer_1 deliver_cap: 37.26853339519113 cap_limit: 40
5298 customer_2 ('customer_2', 'depot_t')
2109 customer_2 -7.668395211559411
resNode: depot_t deliver_cap: 21.214585001672013 cap_limit: 40
5299 customer_2 ('customer_2', 'customer_4')
2109 customer_2 -7.668395211559411
resNode: customer_4 deliver_cap: 45.5686875091172 cap_limit: 40
5300 customer_2 ('customer_2', 'customer_5')
2109 customer_2 -7.668395211559411
resNode: customer_5 deliver_cap: 28.799675450066463 cap_limit: 40
5301 customer_4 ('customer_4', 'customer_3')
2110 customer_4 -14.283952127504817
resNode: customer_3 deliver_cap: 54.65199763165206 cap_limit: 40
5302 customer_4 ('customer_4', 'customer_1')
2110 customer_4 -14.283952127504817
resNode: customer_1 deliver_cap: 55.71484616536303 cap_limit: 40
5303 customer_4 ('customer_4', 'depot_t')
2110 customer_4 -14.283952127504817
resNode: depot_t deliver_cap: 39.79183817943227 cap_limit: 40
5304 customer_4 ('customer_4', 'customer_2')
2110 customer_4 -14.283952127504817
resNode: customer_2 deliver_cap: 44.044907061200476 cap_limit: 40
5305 customer_4 ('customer_4', 'customer_5')
2110 customer_4 -14.283952127504817
resNode: customer_5 deliver_cap: 49.15462363341632 cap_limit: 40
5306 customer_2 ('customer_2', 'customer_3')
2113 customer_2 -13.37673319695333
resNode: customer_3 deliver_cap: 69.23458718621755 cap_limit: 40
5307 customer_2 ('customer_2', 'customer_1')
2113 customer_2 -13.37673319695333
resNode: customer_1 deliver_cap: 58.27629180305205 cap_limit: 40
5308 customer_2 ('customer_2', 'depot_t')
2113 customer_2 -13.37673319695333
resNode: depot_t deliver_cap: 38.5616163570295 cap_limit: 40
5309 customer_2 ('customer_2', 'customer_4')
2113 customer_2 -13.37673319695333
resNode: customer_4 deliver_cap: 68.97652911092986 cap_limit: 40
5310 customer_2 ('customer_2', 'customer_5')
2113 customer_2 -13.37673319695333
resNode: customer_5 deliver_cap: 49.412681708704 cap_limit: 40
5311 customer_2 ('customer_2', 'customer_3')
2118 customer_2 -9.666106178053427
resNode: customer_3 deliver_cap: 58.500614797348085 cap_limit: 40
5312 customer_2 ('customer_2', 'customer_1')
2118 customer_2 -9.666106178053427
resNode: customer_1 deliver_cap: 47.86081227208281 cap_limit: 40
5313 customer_2 ('customer_2', 'depot_t')
2118 customer_2 -9.666106178053427
resNode: depot_t deliver_cap: 31.10071195343758 cap_limit: 40
5314 customer_2 ('customer_2', 'customer_4')
2118 customer_2 -9.666106178053427
resNode: customer_4 deliver_cap: 58.27942216138722 cap_limit: 40
5315 customer_2 ('customer_2', 'customer_5')
2118 customer_2 -9.666106178053427
resNode: customer_5 deliver_cap: 41.51041010233647 cap_limit: 40
5316 customer_5 ('customer_5', 'customer_3')
2120 customer_5 -17.280321437256625
resNode: customer_3 deliver_cap: 66.73468356768198 cap_limit: 40
5317 customer_5 ('customer_5', 'customer_1')
2120 customer_5 -17.280321437256625
resNode: customer_1 deliver_cap: 58.27021278544694 cap_limit: 40
5318 customer_5 ('customer_5', 'depot_t')
2120 customer_5 -17.280321437256625
resNode: depot_t deliver_cap: 37.97701083489825 cap_limit: 40
5319 customer_5 ('customer_5', 'customer_2')
2120 customer_5 -17.280321437256625
resNode: customer_2 deliver_cap: 42.12332516698798 cap_limit: 40
5320 customer_5 ('customer_5', 'customer_4')
2120 customer_5 -17.280321437256625
resNode: customer_4 deliver_cap: 66.4766254923943 cap_limit: 40
5321 customer_1 ('customer_1', 'customer_3')
2122 customer_1 -9.093921229321989
resNode: customer_3 deliver_cap: 54.35728917979635 cap_limit: 40
5322 customer_1 ('customer_1', 'depot_t')
2122 customer_1 -9.093921229321989
resNode: depot_t deliver_cap: 32.11140108403144 cap_limit: 40
5323 customer_1 ('customer_1', 'customer_2')
2122 customer_1 -9.093921229321989
resNode: customer_2 deliver_cap: 34.40507259003369 cap_limit: 40
5324 customer_1 ('customer_1', 'customer_4')
2122 customer_1 -9.093921229321989
resNode: customer_4 deliver_cap: 53.80247364709084 cap_limit: 40
5325 customer_1 ('customer_1', 'customer_5')
2122 customer_1 -9.093921229321989
resNode: customer_5 deliver_cap: 41.51041010233648 cap_limit: 40
5326 customer_4 ('customer_4', 'customer_3')
2124 customer_4 -13.520362579462832
resNode: customer_3 deliver_cap: 54.65199763165206 cap_limit: 40
5327 customer_4 ('customer_4', 'customer_1')
2124 customer_4 -13.520362579462832
resNode: customer_1 deliver_cap: 55.71484616536303 cap_limit: 40
5328 customer_4 ('customer_4', 'depot_t')
2124 customer_4 -13.520362579462832
resNode: depot_t deliver_cap: 39.79183817943227 cap_limit: 40
5329 customer_4 ('customer_4', 'customer_2')
2124 customer_4 -13.520362579462832
resNode: customer_2 deliver_cap: 44.044907061200476 cap_limit: 40
5330 customer_4 ('customer_4', 'customer_5')
2124 customer_4 -13.520362579462832
resNode: customer_5 deliver_cap: 49.15462363341632 cap_limit: 40
5331 customer_5 ('customer_5', 'customer_3')
2125 customer_5 -10.891632426903925
resNode: customer_3 deliver_cap: 49.41268170870401 cap_limit: 40
5332 customer_5 ('customer_5', 'customer_1')
2125 customer_5 -10.891632426903925
resNode: customer_1 deliver_cap: 43.42278262060868 cap_limit: 40
5333 customer_5 ('customer_5', 'depot_t')
2125 customer_5 -10.891632426903925
resNode: depot_t deliver_cap: 23.954437901439896 cap_limit: 40
5334 customer_5 ('customer_5', 'customer_2')
2125 customer_5 -10.891632426903925
resNode: customer_2 deliver_cap: 27.27589500214973 cap_limit: 40
5335 customer_5 ('customer_5', 'customer_4')
2125 customer_5 -10.891632426903925
resNode: customer_4 deliver_cap: 49.154623633416335 cap_limit: 40
5336 customer_2 ('customer_2', 'customer_3')
2129 customer_2 -13.328603317832215
resNode: customer_3 deliver_cap: 68.97652911092986 cap_limit: 40
5337 customer_2 ('customer_2', 'customer_1')
2129 customer_2 -13.328603317832215
resNode: customer_1 deliver_cap: 58.05509916709117 cap_limit: 40
5338 customer_2 ('customer_2', 'depot_t')
2129 customer_2 -13.328603317832215
resNode: depot_t deliver_cap: 38.35271220084424 cap_limit: 40
5339 customer_2 ('customer_2', 'customer_4')
2129 customer_2 -13.328603317832215
resNode: customer_4 deliver_cap: 68.71847103564218 cap_limit: 40
5340 customer_2 ('customer_2', 'customer_5')
2129 customer_2 -13.328603317832215
resNode: customer_5 deliver_cap: 49.154623633416314 cap_limit: 40
5341 customer_1 ('customer_1', 'customer_3')
2147 customer_1 -12.041361281463665
resNode: customer_3 deliver_cap: 60.687169752981816 cap_limit: 40
5342 customer_1 ('customer_1', 'depot_t')
2147 customer_1 -12.041361281463665
resNode: depot_t deliver_cap: 35.47859340849407 cap_limit: 40
5343 customer_1 ('customer_1', 'customer_2')
2147 customer_1 -12.041361281463665
resNode: customer_2 deliver_cap: 39.42065934277119 cap_limit: 40
5344 customer_1 ('customer_1', 'customer_4')
2147 customer_1 -12.041361281463665
resNode: customer_4 deliver_cap: 60.28646964602783 cap_limit: 40
5345 customer_1 ('customer_1', 'customer_5')
2147 customer_1 -12.041361281463665
resNode: customer_5 deliver_cap: 51.40886819703857 cap_limit: 40
5346 customer_5 ('customer_5', 'customer_3')
2150 customer_5 -21.126285239532123
resNode: customer_3 deliver_cap: 64.02206834474387 cap_limit: 40
5347 customer_5 ('customer_5', 'customer_1')
2150 customer_5 -21.126285239532123
resNode: customer_1 deliver_cap: 52.79002612690183 cap_limit: 40
5348 customer_5 ('customer_5', 'depot_t')
2150 customer_5 -21.126285239532123
resNode: depot_t deliver_cap: 36.68974812855016 cap_limit: 40
5349 customer_5 ('customer_5', 'customer_2')
2150 customer_5 -21.126285239532123
resNode: customer_2 deliver_cap: 41.12838506912592 cap_limit: 40
5350 customer_5 ('customer_5', 'customer_4')
2150 customer_5 -21.126285239532123
resNode: customer_4 deliver_cap: 63.82545266833421 cap_limit: 40
5351 customer_2 ('customer_2', 'customer_3')
2154 customer_2 -21.05837473353435
resNode: customer_3 deliver_cap: 65.92135324480452 cap_limit: 40
5352 customer_2 ('customer_2', 'customer_1')
2154 customer_2 -21.05837473353435
resNode: customer_1 deliver_cap: 52.79002612690183 cap_limit: 40
5353 customer_2 ('customer_2', 'depot_t')
2154 customer_2 -21.05837473353435
resNode: depot_t deliver_cap: 37.09835817165116 cap_limit: 40
5354 customer_2 ('customer_2', 'customer_4')
2154 customer_2 -21.05837473353435
resNode: customer_4 deliver_cap: 65.72473756839486 cap_limit: 40
5355 customer_2 ('customer_2', 'customer_5')
2154 customer_2 -21.05837473353435
resNode: customer_5 deliver_cap: 50.81894907146086 cap_limit: 40
5356 customer_2 ('customer_2', 'customer_3')
2163 customer_2 -17.58888279124171
resNode: customer_3 deliver_cap: 65.92135324480452 cap_limit: 40
5357 customer_2 ('customer_2', 'customer_1')
2163 customer_2 -17.58888279124171
resNode: customer_1 deliver_cap: 52.79002612690183 cap_limit: 40
5358 customer_2 ('customer_2', 'depot_t')
2163 customer_2 -17.58888279124171
resNode: depot_t deliver_cap: 37.098358171651164 cap_limit: 40
5359 customer_2 ('customer_2', 'customer_4')
2163 customer_2 -17.58888279124171
resNode: customer_4 deliver_cap: 65.72473756839486 cap_limit: 40
5360 customer_2 ('customer_2', 'customer_5')
2163 customer_2 -17.58888279124171
resNode: customer_5 deliver_cap: 50.818949071460864 cap_limit: 40
5361 customer_1 ('customer_1', 'customer_3')
2167 customer_1 -16.98060180213192
resNode: customer_3 deliver_cap: 62.23839714031409 cap_limit: 40
5362 customer_1 ('customer_1', 'depot_t')
2167 customer_1 -16.98060180213192
resNode: depot_t deliver_cap: 37.964663140731616 cap_limit: 40
5363 customer_1 ('customer_1', 'customer_2')
2167 customer_1 -16.98060180213192
resNode: customer_2 deliver_cap: 41.12838506912592 cap_limit: 40
5364 customer_1 ('customer_1', 'customer_4')
2167 customer_1 -16.98060180213192
resNode: customer_4 deliver_cap: 61.74522777790919 cap_limit: 40
5365 customer_1 ('customer_1', 'customer_5')
2167 customer_1 -16.98060180213192
resNode: customer_5 deliver_cap: 50.81894907146087 cap_limit: 40
5366 customer_5 ('customer_5', 'customer_3')
2170 customer_5 -22.483295545466362
resNode: customer_3 deliver_cap: 61.23767004760982 cap_limit: 40
5367 customer_5 ('customer_5', 'customer_1')
2170 customer_5 -22.483295545466362
resNode: customer_1 deliver_cap: 52.518835754369476 cap_limit: 40
5368 customer_5 ('customer_5', 'depot_t')
2170 customer_5 -22.483295545466362
resNode: depot_t deliver_cap: 34.18702507244544 cap_limit: 40
5369 customer_5 ('customer_5', 'customer_2')
2170 customer_5 -22.483295545466362
resNode: customer_2 deliver_cap: 38.16604676018375 cap_limit: 40
5370 customer_5 ('customer_5', 'customer_4')
2170 customer_5 -22.483295545466362
resNode: customer_4 deliver_cap: 61.00418893187334 cap_limit: 40
5371 customer_2 ('customer_2', 'customer_3')
2188 customer_2 -17.418819774468687
resNode: customer_3 deliver_cap: 65.92135324480454 cap_limit: 40
5372 customer_2 ('customer_2', 'customer_1')
2188 customer_2 -17.418819774468687
resNode: customer_1 deliver_cap: 52.79002612690183 cap_limit: 40
5373 customer_2 ('customer_2', 'depot_t')
2188 customer_2 -17.418819774468687
resNode: depot_t deliver_cap: 37.09835817165117 cap_limit: 40
5374 customer_2 ('customer_2', 'customer_4')
2188 customer_2 -17.418819774468687
resNode: customer_4 deliver_cap: 65.72473756839487 cap_limit: 40
5375 customer_2 ('customer_2', 'customer_5')
2188 customer_2 -17.418819774468687
resNode: customer_5 deliver_cap: 50.81894907146087 cap_limit: 40
5376 customer_2 ('customer_2', 'customer_3')
2194 customer_2 -22.270860150389375
resNode: customer_3 deliver_cap: 63.49307086643184 cap_limit: 40
5377 customer_2 ('customer_2', 'customer_1')
2194 customer_2 -22.270860150389375
resNode: customer_1 deliver_cap: 52.51883575436948 cap_limit: 40
5378 customer_2 ('customer_2', 'depot_t')
2194 customer_2 -22.270860150389375
resNode: depot_t deliver_cap: 34.6977876263217 cap_limit: 40
5379 customer_2 ('customer_2', 'customer_4')
2194 customer_2 -22.270860150389375
resNode: customer_4 deliver_cap: 63.259589750695376 cap_limit: 40
5380 customer_2 ('customer_2', 'customer_5')
2194 customer_2 -22.270860150389375
resNode: customer_5 deliver_cap: 45.55896591058625 cap_limit: 40
5381 customer_2 ('customer_2', 'customer_3')
2209 customer_2 -22.596704512765623
resNode: customer_3 deliver_cap: 70.12839880014165 cap_limit: 40
5382 customer_2 ('customer_2', 'customer_1')
2209 customer_2 -22.596704512765623
resNode: customer_1 deliver_cap: 58.106480330125116 cap_limit: 40
5383 customer_2 ('customer_2', 'depot_t')
2209 customer_2 -22.596704512765623
resNode: depot_t deliver_cap: 39.93620441609261 cap_limit: 40
5384 customer_2 ('customer_2', 'customer_4')
2209 customer_2 -22.596704512765623
resNode: customer_4 deliver_cap: 69.89491768440519 cap_limit: 40
5385 customer_2 ('customer_2', 'customer_5')
2209 customer_2 -22.596704512765623
resNode: customer_5 deliver_cap: 52.19429384429606 cap_limit: 40
5386 customer_2 ('customer_2', 'customer_3')
2233 customer_2 -10.45850849977522
resNode: customer_3 deliver_cap: 55.948829414840034 cap_limit: 40
5387 customer_2 ('customer_2', 'customer_1')
2233 customer_2 -10.45850849977522
resNode: customer_1 deliver_cap: 42.44442771564476 cap_limit: 40
5388 customer_2 ('customer_2', 'depot_t')
2233 customer_2 -10.45850849977522
resNode: depot_t deliver_cap: 29.476812408040466 cap_limit: 40
5389 customer_2 ('customer_2', 'customer_4')
2233 customer_2 -10.45850849977522
resNode: customer_4 deliver_cap: 55.78907917775718 cap_limit: 40
5390 customer_2 ('customer_2', 'customer_5')
2233 customer_2 -10.45850849977522
resNode: customer_5 deliver_cap: 43.67812602399831 cap_limit: 40
5391 customer_5 ('customer_5', 'customer_3')
2235 customer_5 -22.0086030986095
resNode: customer_3 deliver_cap: 67.70502444923432 cap_limit: 40
5392 customer_5 ('customer_5', 'customer_1')
2235 customer_5 -22.0086030986095
resNode: customer_1 deliver_cap: 55.78242796180031 cap_limit: 40
5393 customer_5 ('customer_5', 'depot_t')
2235 customer_5 -22.0086030986095
resNode: depot_t deliver_cap: 39.45196520691799 cap_limit: 40
5394 customer_5 ('customer_5', 'customer_2')
2235 customer_5 -22.0086030986095
resNode: customer_2 deliver_cap: 44.1207869040244 cap_limit: 40
5395 customer_5 ('customer_5', 'customer_4')
2235 customer_5 -22.0086030986095
resNode: customer_4 deliver_cap: 67.50840877282465 cap_limit: 40
5396 customer_2 ('customer_2', 'customer_3')
2244 customer_2 -16.583075121483894
resNode: customer_3 deliver_cap: 56.406593647216496 cap_limit: 40
5397 customer_2 ('customer_2', 'customer_1')
2244 customer_2 -16.583075121483894
resNode: customer_1 deliver_cap: 45.05928395386156 cap_limit: 40
5398 customer_2 ('customer_2', 'depot_t')
2244 customer_2 -16.583075121483894
resNode: depot_t deliver_cap: 29.962288473460145 cap_limit: 40
5399 customer_2 ('customer_2', 'customer_4')
2244 customer_2 -16.583075121483894
resNode: customer_4 deliver_cap: 56.20997797080683 cap_limit: 40
5400 customer_2 ('customer_2', 'customer_5')
2244 customer_2 -16.583075121483894
resNode: customer_5 deliver_cap: 41.30418947387284 cap_limit: 40
5401 customer_2 ('customer_2', 'customer_3')
2253 customer_2 -19.29605788169898
resNode: customer_3 deliver_cap: 69.60430934929497 cap_limit: 40
5402 customer_2 ('customer_2', 'customer_1')
2253 customer_2 -19.29605788169898
resNode: customer_1 deliver_cap: 55.78242796180031 cap_limit: 40
5403 customer_2 ('customer_2', 'depot_t')
2253 customer_2 -19.29605788169898
resNode: depot_t deliver_cap: 39.860575250019 cap_limit: 40
5404 customer_2 ('customer_2', 'customer_4')
2253 customer_2 -19.29605788169898
resNode: customer_4 deliver_cap: 69.4076936728853 cap_limit: 40
5405 customer_2 ('customer_2', 'customer_5')
2253 customer_2 -19.29605788169898
resNode: customer_5 deliver_cap: 54.50190517595131 cap_limit: 40
5406 customer_5 ('customer_5', 'customer_3')
2260 customer_5 -25.05366347291358
resNode: customer_3 deliver_cap: 65.61118042169221 cap_limit: 40
5407 customer_5 ('customer_5', 'customer_1')
2260 customer_5 -25.05366347291358
resNode: customer_1 deliver_cap: 56.20179185885992 cap_limit: 40
5408 customer_5 ('customer_5', 'depot_t')
2260 customer_5 -25.05366347291358
resNode: depot_t deliver_cap: 37.639796420405226 cap_limit: 40
5409 customer_5 ('customer_5', 'customer_2')
2260 customer_5 -25.05366347291358
resNode: customer_2 deliver_cap: 41.84900286467418 cap_limit: 40
5410 customer_5 ('customer_5', 'customer_4')
2260 customer_5 -25.05366347291358
resNode: customer_4 deliver_cap: 65.37769930595574 cap_limit: 40
5411 customer_2 ('customer_2', 'customer_3')
2279 customer_2 -22.493276474654294
resNode: customer_3 deliver_cap: 69.89491768440519 cap_limit: 40
5412 customer_2 ('customer_2', 'customer_1')
2279 customer_2 -22.493276474654294
resNode: customer_1 deliver_cap: 57.90986465371546 cap_limit: 40
5413 customer_2 ('customer_2', 'depot_t')
2279 customer_2 -22.493276474654294
resNode: depot_t deliver_cap: 39.75187721945855 cap_limit: 40
5414 customer_2 ('customer_2', 'customer_4')
2279 customer_2 -22.493276474654294
resNode: customer_4 deliver_cap: 69.66143656866872 cap_limit: 40
5415 customer_2 ('customer_2', 'customer_5')
2279 customer_2 -22.493276474654294
resNode: customer_5 deliver_cap: 51.960812728559596 cap_limit: 40
5416 customer_5 ('customer_5', 'customer_3')
2295 customer_5 -21.584171530620942
resNode: customer_3 deliver_cap: 65.61118042169221 cap_limit: 40
5417 customer_5 ('customer_5', 'customer_1')
2295 customer_5 -21.584171530620942
resNode: customer_1 deliver_cap: 56.20179185885992 cap_limit: 40
5418 customer_5 ('customer_5', 'depot_t')
2295 customer_5 -21.584171530620942
resNode: depot_t deliver_cap: 37.639796420405226 cap_limit: 40
5419 customer_5 ('customer_5', 'customer_2')
2295 customer_5 -21.584171530620942
resNode: customer_2 deliver_cap: 41.84900286467418 cap_limit: 40
5420 customer_5 ('customer_5', 'customer_4')
2295 customer_5 -21.584171530620942
resNode: customer_4 deliver_cap: 65.37769930595574 cap_limit: 40
5421 customer_2 ('customer_2', 'customer_3')
2299 customer_2 -21.54179915231698
resNode: customer_3 deliver_cap: 67.86658124051424 cap_limit: 40
5422 customer_2 ('customer_2', 'customer_1')
2299 customer_2 -21.54179915231698
resNode: customer_1 deliver_cap: 56.20179185885992 cap_limit: 40
5423 customer_2 ('customer_2', 'depot_t')
2299 customer_2 -21.54179915231698
resNode: depot_t deliver_cap: 38.15055897428148 cap_limit: 40
5424 customer_2 ('customer_2', 'customer_4')
2299 customer_2 -21.54179915231698
resNode: customer_4 deliver_cap: 67.63310012477777 cap_limit: 40
5425 customer_2 ('customer_2', 'customer_5')
2299 customer_2 -21.54179915231698
resNode: customer_5 deliver_cap: 49.932476284668645 cap_limit: 40
5426 customer_2 ('customer_2', 'customer_3')
2303 customer_2 -17.877203208595734
resNode: customer_3 deliver_cap: 70.12839880014167 cap_limit: 40
5427 customer_2 ('customer_2', 'customer_1')
2303 customer_2 -17.877203208595734
resNode: customer_1 deliver_cap: 58.10648033012512 cap_limit: 40
5428 customer_2 ('customer_2', 'depot_t')
2303 customer_2 -17.877203208595734
resNode: depot_t deliver_cap: 39.93620441609261 cap_limit: 40
5429 customer_2 ('customer_2', 'customer_4')
2303 customer_2 -17.877203208595734
resNode: customer_4 deliver_cap: 69.89491768440519 cap_limit: 40
5430 customer_2 ('customer_2', 'customer_5')
2303 customer_2 -17.877203208595734
resNode: customer_5 deliver_cap: 52.19429384429608 cap_limit: 40
5431 customer_2 ('customer_2', 'customer_3')
2308 customer_2 -12.118662931038326
resNode: customer_3 deliver_cap: 56.4065936472165 cap_limit: 40
5432 customer_2 ('customer_2', 'customer_1')
2308 customer_2 -12.118662931038326
resNode: customer_1 deliver_cap: 45.05928395386156 cap_limit: 40
5433 customer_2 ('customer_2', 'depot_t')
2308 customer_2 -12.118662931038326
resNode: depot_t deliver_cap: 29.96228847346015 cap_limit: 40
5434 customer_2 ('customer_2', 'customer_4')

resNode: customer_4 deliver_cap: 67.52075873315653 cap_limit: 40
5465 customer_2 ('customer_2', 'customer_5')
2358 customer_2 -11.121902789398417
resNode: customer_5 deliver_cap: 52.614970236222526 cap_limit: 40
5466 customer_2 ('customer_2', 'customer_3')
2364 customer_2 -16.39488562581012
resNode: customer_3 deliver_cap: 65.6258459995863 cap_limit: 40
5467 customer_2 ('customer_2', 'customer_1')
2364 customer_2 -16.39488562581012
resNode: customer_1 deliver_cap: 54.31485691913114 cap_limit: 40
5468 customer_2 ('customer_2', 'depot_t')
2364 customer_2 -16.39488562581012
resNode: depot_t deliver_cap: 36.38155746828575 cap_limit: 40
5469 customer_2 ('customer_2', 'customer_4')
2364 customer_2 -16.39488562581012
resNode: customer_4 deliver_cap: 65.39236488384984 cap_limit: 40
5470 customer_2 ('customer_2', 'customer_5')
2364 customer_2 -16.39488562581012
resNode: customer_5 deliver_cap: 47.69174104374072 cap_limit: 40
5471 customer_5 ('customer_5', 'customer_3')
2380 customer_5 -18.286133913216744
resNode: customer_3 deliver_cap: 68.09611305696602 cap_limit: 40
5472 customer_5 ('customer_5', 'customer_1')
2380 customer_5 -18.286133913216744
resNode: customer_1 deliver_cap: 58.29436670961681 cap_limit: 40
5473 customer_5 ('customer_5', 'depot_t')
2380 customer_5 -18.286133913216744
resNode: depot_t deliver_cap: 39.601585342989814 cap_limit: 40
5474 customer_5 ('customer_5', 'customer_2')
2380 customer_5 -18.286133913216744
resNode: customer_2 deliver_cap: 43.94157771543108 cap_limit: 40
5475 customer_5 ('customer_5', 'customer_4')
2380 customer_5 -18.286133913216744
resNode: customer_4 deliver_cap: 67.86263194122955 cap_limit: 40
5476 customer_5 ('customer_5', 'customer_3')
2400 customer_5 -17.49423626031441
resNode: customer_3 deliver_cap: 61.72456277864396 cap_limit: 40
5477 customer_5 ('customer_5', 'customer_1')
2400 customer_5 -17.49423626031441
resNode: customer_1 deliver_cap: 54.43602435589646 cap_limit: 40
5478 customer_5 ('customer_5', 'depot_t')
2400 customer_5 -17.49423626031441
resNode: depot_t deliver_cap: 33.511710305697086 cap_limit: 40
5479 customer_5 ('customer_5', 'customer_2')
2400 customer_5 -17.49423626031441
resNode: customer_2 deliver_cap: 37.39208742530091 cap_limit: 40
5480 customer_5 ('customer_5', 'customer_4')
2400 customer_5 -17.49423626031441
resNode: customer_4 deliver_cap: 61.45421622358067 cap_limit: 40
5481 customer_2 ('customer_2', 'customer_3')
2408 customer_2 -13.32812453361886
resNode: customer_3 deliver_cap: 68.09611305696602 cap_limit: 40
5482 customer_2 ('customer_2', 'customer_1')
2408 customer_2 -13.32812453361886
resNode: customer_1 deliver_cap: 56.39508180955616 cap_limit: 40
5483 customer_2 ('customer_2', 'depot_t')
2408 customer_2 -13.32812453361886
resNode: depot_t deliver_cap: 38.33176830305921 cap_limit: 40
5484 customer_2 ('customer_2', 'customer_4')
2408 customer_2 -13.32812453361886
resNode: customer_4 deliver_cap: 67.86263194122955 cap_limit: 40
5485 customer_2 ('customer_2', 'customer_5')
2408 customer_2 -13.32812453361886
resNode: customer_5 deliver_cap: 50.16200810112043 cap_limit: 40
5486 customer_2 ('customer_2', 'customer_3')
2414 customer_2 -15.586112052251256
resNode: customer_3 deliver_cap: 61.72456277864396 cap_limit: 40
5487 customer_2 ('customer_2', 'customer_1')
2414 customer_2 -15.586112052251256
resNode: customer_1 deliver_cap: 52.180623537074425 cap_limit: 40
5488 customer_2 ('customer_2', 'depot_t')
2414 customer_2 -15.586112052251256
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
5489 customer_2 ('customer_2', 'customer_4')
2414 customer_2 -15.586112052251256
resNode: customer_4 deliver_cap: 61.45421622358067 cap_limit: 40
5490 customer_2 ('customer_2', 'customer_5')
2414 customer_2 -15.586112052251256
resNode: customer_5 deliver_cap: 40.95875704029644 cap_limit: 40
5491 customer_2 ('customer_2', 'customer_3')
2423 customer_2 -15.175601785221513
resNode: customer_3 deliver_cap: 67.7050244492343 cap_limit: 40
5492 customer_2 ('customer_2', 'customer_1')
2423 customer_2 -15.175601785221513
resNode: customer_1 deliver_cap: 54.23925898050102 cap_limit: 40
5493 customer_2 ('customer_2', 'depot_t')
2423 customer_2 -15.175601785221513
resNode: depot_t deliver_cap: 38.436111574973495 cap_limit: 40
5494 customer_2 ('customer_2', 'customer_4')
2423 customer_2 -15.175601785221513
resNode: customer_4 deliver_cap: 67.50840877282464 cap_limit: 40
5495 customer_2 ('customer_2', 'customer_5')
2423 customer_2 -15.175601785221513
resNode: customer_5 deliver_cap: 52.602620275890644 cap_limit: 40
5496 customer_2 ('customer_2', 'customer_3')
2429 customer_2 -20.445690099680434
resNode: customer_3 deliver_cap: 65.6111804216922 cap_limit: 40
5497 customer_2 ('customer_2', 'customer_1')
2429 customer_2 -20.445690099680434
resNode: customer_1 deliver_cap: 54.302506958799256 cap_limit: 40
5498 customer_2 ('customer_2', 'depot_t')
2429 customer_2 -20.445690099680434
resNode: depot_t deliver_cap: 36.36997938047461 cap_limit: 40
5499 customer_2 ('customer_2', 'customer_4')
2429 customer_2 -20.445690099680434
resNode: customer_4 deliver_cap: 65.37769930595573 cap_limit: 40
5500 customer_2 ('customer_2', 'customer_5')
2429 customer_2 -20.445690099680434
resNode: customer_5 deliver_cap: 47.677075465846606 cap_limit: 40
5501 customer_1 ('customer_1', 'customer_3')
2442 customer_1 -13.742463564731821
resNode: customer_3 deliver_cap: 64.02206834474387 cap_limit: 40
5502 customer_1 ('customer_1', 'depot_t')
2442 customer_1 -13.742463564731821
resNode: depot_t deliver_cap: 39.302416544053955 cap_limit: 40
5503 customer_1 ('customer_1', 'customer_2')
2442 customer_1 -13.742463564731821
resNode: customer_2 deliver_cap: 42.57761792272512 cap_limit: 40
5504 customer_1 ('customer_1', 'customer_4')
2442 customer_1 -13.742463564731821
resNode: customer_4 deliver_cap: 63.52889898233897 cap_limit: 40
5505 customer_1 ('customer_1', 'customer_5')
2442 customer_1 -13.742463564731821
resNode: customer_5 deliver_cap: 52.60262027589065 cap_limit: 40
5506 customer_5 ('customer_5', 'customer_3')
2445 customer_5 -19.66320524660449
resNode: customer_3 deliver_cap: 63.35577960287018 cap_limit: 40
5507 customer_5 ('customer_5', 'customer_1')
2445 customer_5 -19.66320524660449
resNode: customer_1 deliver_cap: 54.302506958799256 cap_limit: 40
5508 customer_5 ('customer_5', 'depot_t')
2445 customer_5 -19.66320524660449
resNode: depot_t deliver_cap: 35.859216826598356 cap_limit: 40
5509 customer_5 ('customer_5', 'customer_2')
2445 customer_5 -19.66320524660449
resNode: customer_2 deliver_cap: 39.94971796461353 cap_limit: 40
5510 customer_5 ('customer_5', 'customer_4')
2445 customer_5 -19.66320524660449
resNode: customer_4 deliver_cap: 63.122298487133705 cap_limit: 40
5511 customer_2 ('customer_2', 'customer_3')
2449 customer_2 -19.620832868300532
resNode: customer_3 deliver_cap: 65.61118042169221 cap_limit: 40
5512 customer_2 ('customer_2', 'customer_1')
2449 customer_2 -19.620832868300532
resNode: customer_1 deliver_cap: 54.30250695879926 cap_limit: 40
5513 customer_2 ('customer_2', 'depot_t')
2449 customer_2 -19.620832868300532
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
5514 customer_2 ('customer_2', 'customer_4')
2449 customer_2 -19.620832868300532
resNode: customer_4 deliver_cap: 65.37769930595574 cap_limit: 40
5515 customer_2 ('customer_2', 'customer_5')
2449 customer_2 -19.620832868300532
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
5516 customer_2 ('customer_2', 'customer_3')
2458 customer_2 -16.15134092600789
resNode: customer_3 deliver_cap: 65.61118042169221 cap_limit: 40
5517 customer_2 ('customer_2', 'customer_1')
2458 customer_2 -16.15134092600789
resNode: customer_1 deliver_cap: 54.30250695879926 cap_limit: 40
5518 customer_2 ('customer_2', 'depot_t')
2458 customer_2 -16.15134092600789
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
5519 customer_2 ('customer_2', 'customer_4')
2458 customer_2 -16.15134092600789
resNode: customer_4 deliver_cap: 65.37769930595574 cap_limit: 40
5520 customer_2 ('customer_2', 'customer_5')
2458 customer_2 -16.15134092600789
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
5521 customer_1 ('customer_1', 'customer_3')
2462 customer_1 -15.59720399746563
resNode: customer_3 deliver_cap: 61.237670047609825 cap_limit: 40
5522 customer_1 ('customer_1', 'depot_t')
2462 customer_1 -15.59720399746563
resNode: depot_t deliver_cap: 37.452860591825186 cap_limit: 40
5523 customer_1 ('customer_1', 'customer_2')
2462 customer_1 -15.59720399746563
resNode: customer_2 deliver_cap: 39.949717964613534 cap_limit: 40
5524 customer_1 ('customer_1', 'customer_4')
2462 customer_1 -15.59720399746563
resNode: customer_4 deliver_cap: 60.652031429754 cap_limit: 40
5525 customer_1 ('customer_1', 'customer_5')
2462 customer_1 -15.59720399746563
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
5526 customer_5 ('customer_5', 'customer_3')
2465 customer_5 -17.935715464604286
resNode: customer_3 deliver_cap: 56.23575562126982 cap_limit: 40
5527 customer_5 ('customer_5', 'customer_1')
2465 customer_5 -17.935715464604286
resNode: customer_1 deliver_cap: 49.6956909018006 cap_limit: 40
5528 customer_5 ('customer_5', 'depot_t')
2465 customer_5 -17.935715464604286
resNode: depot_t deliver_cap: 29.020868086027335 cap_limit: 40
5529 customer_5 ('customer_5', 'customer_2')
2465 customer_5 -17.935715464604286
resNode: customer_2 deliver_cap: 32.65175397120505 cap_limit: 40
5530 customer_5 ('customer_5', 'customer_4')
2465 customer_5 -17.935715464604286
resNode: customer_4 deliver_cap: 55.96540906620653 cap_limit: 40
5531 customer_2 ('customer_2', 'customer_3')
2478 customer_2 -15.12025906999114
resNode: customer_3 deliver_cap: 62.06832768284507 cap_limit: 40
5532 customer_2 ('customer_2', 'customer_1')
2478 customer_2 -15.12025906999114
resNode: customer_1 deliver_cap: 47.15173407564863 cap_limit: 40
5533 customer_2 ('customer_2', 'depot_t')
2478 customer_2 -15.12025906999114
resNode: depot_t deliver_cap: 33.71338813204396 cap_limit: 40
5534 customer_2 ('customer_2', 'customer_4')
2478 customer_2 -15.12025906999114
resNode: customer_4 deliver_cap: 61.90857744576222 cap_limit: 40
5535 customer_2 ('customer_2', 'customer_5')
2478 customer_2 -15.12025906999114
resNode: customer_5 deliver_cap: 49.797624292003356 cap_limit: 40
5536 customer_2 ('customer_2', 'customer_3')
2484 customer_2 -23.01006557670127
resNode: customer_3 deliver_cap: 63.938283823222704 cap_limit: 40
5537 customer_2 ('customer_2', 'customer_1')
2484 customer_2 -23.01006557670127
resNode: customer_1 deliver_cap: 51.1787822218666 cap_limit: 40
5538 customer_2 ('customer_2', 'depot_t')
2484 customer_2 -23.01006557670127
resNode: depot_t deliver_cap: 35.6110561054648 cap_limit: 40
5539 customer_2 ('customer_2', 'customer_4')
2484 customer_2 -23.01006557670127
resNode: customer_4 deliver_cap: 63.74166814681304 cap_limit: 40
5540 customer_2 ('customer_2', 'customer_5')
2484 customer_2 -23.01006557670127
resNode: customer_5 deliver_cap: 48.83587964987905 cap_limit: 40
5541 customer_1 ('customer_1', 'customer_3')
2502 customer_1 -15.071631517250493
resNode: customer_3 deliver_cap: 62.06832768284507 cap_limit: 40
5542 customer_1 ('customer_1', 'depot_t')
2502 customer_1 -15.071631517250493
resNode: depot_t deliver_cap: 36.43477966763017 cap_limit: 40
5543 customer_1 ('customer_1', 'customer_2')
2502 customer_1 -15.071631517250493
resNode: customer_2 deliver_cap: 40.483088519589074 cap_limit: 40
5544 customer_1 ('customer_1', 'customer_4')
2502 customer_1 -15.071631517250493
resNode: customer_4 deliver_cap: 61.66762757589108 cap_limit: 40
5545 customer_1 ('customer_1', 'customer_5')
2502 customer_1 -15.071631517250493
resNode: customer_5 deliver_cap: 52.790026126901836 cap_limit: 40
5546 customer_5 ('customer_5', 'customer_3')
2505 customer_5 -24.55496641662566
resNode: customer_3 deliver_cap: 65.72195502765248 cap_limit: 40
5547 customer_5 ('customer_5', 'customer_1')
2505 customer_5 -24.55496641662566
resNode: customer_1 deliver_cap: 54.17118405676507 cap_limit: 40
5548 customer_5 ('customer_5', 'depot_t')
2505 customer_5 -24.55496641662566
resNode: depot_t deliver_cap: 37.964663140731616 cap_limit: 40
5549 customer_5 ('customer_5', 'customer_2')
2505 customer_5 -24.55496641662566
resNode: customer_2 deliver_cap: 42.50954299898917 cap_limit: 40
5550 customer_5 ('customer_5', 'customer_4')
2505 customer_5 -24.55496641662566
resNode: customer_4 deliver_cap: 65.52533935124282 cap_limit: 40
5551 customer_2 ('customer_2', 'customer_3')
2509 customer_2 -24.487055910627888
resNode: customer_3 deliver_cap: 67.62123992771315 cap_limit: 40
5552 customer_2 ('customer_2', 'customer_1')
2509 customer_2 -24.487055910627888
resNode: customer_1 deliver_cap: 54.17118405676507 cap_limit: 40
5553 customer_2 ('customer_2', 'depot_t')
2509 customer_2 -24.487055910627888
resNode: depot_t deliver_cap: 38.37327318383263 cap_limit: 40
5554 customer_2 ('customer_2', 'customer_4')
2509 customer_2 -24.487055910627888
resNode: customer_4 deliver_cap: 67.42462425130348 cap_limit: 40
5555 customer_2 ('customer_2', 'customer_5')
2509 customer_2 -24.487055910627888
resNode: customer_5 deliver_cap: 52.51883575436948 cap_limit: 40
5556 customer_2 ('customer_2', 'customer_3')
2518 customer_2 -21.017563968335242
resNode: customer_3 deliver_cap: 67.62123992771313 cap_limit: 40
5557 customer_2 ('customer_2', 'customer_1')
2518 customer_2 -21.017563968335242
resNode: customer_1 deliver_cap: 54.17118405676507 cap_limit: 40
5558 customer_2 ('customer_2', 'depot_t')
2518 customer_2 -21.017563968335242
resNode: depot_t deliver_cap: 38.37327318383262 cap_limit: 40
5559 customer_2 ('customer_2', 'customer_4')
2518 customer_2 -21.017563968335242
resNode: customer_4 deliver_cap: 67.42462425130347 cap_limit: 40
5560 customer_2 ('customer_2', 'customer_5')
2518 customer_2 -21.017563968335242
resNode: customer_5 deliver_cap: 52.518835754369476 cap_limit: 40
5561 customer_1 ('customer_1', 'customer_3')
2522 customer_1 -20.409282979225456
resNode: customer_3 deliver_cap: 63.938283823222704 cap_limit: 40
5562 customer_1 ('customer_1', 'depot_t')
2522 customer_1 -20.409282979225456
resNode: depot_t deliver_cap: 39.23957815291308 cap_limit: 40
5563 customer_1 ('customer_1', 'customer_2')
2522 customer_1 -20.409282979225456
resNode: customer_2 deliver_cap: 42.50954299898917 cap_limit: 40
5564 customer_1 ('customer_1', 'customer_4')
2522 customer_1 -20.409282979225456
resNode: customer_4 deliver_cap: 63.445114460817805 cap_limit: 40
5565 customer_1 ('customer_1', 'customer_5')
2522 customer_1 -20.409282979225456
resNode: customer_5 deliver_cap: 52.51883575436948 cap_limit: 40
5566 customer_5 ('customer_5', 'customer_3')
2525 customer_5 -26.310387663866603
resNode: customer_3 deliver_cap: 63.25628548356379 cap_limit: 40
5567 customer_5 ('customer_5', 'customer_1')
2525 customer_5 -26.310387663866603
resNode: customer_1 deliver_cap: 54.21872243727809 cap_limit: 40
5568 customer_5 ('customer_5', 'depot_t')
2525 customer_5 -26.310387663866603
resNode: depot_t deliver_cap: 35.780668837672266 cap_limit: 40
5569 customer_5 ('customer_5', 'customer_2')
2525 customer_5 -26.310387663866603
resNode: customer_2 deliver_cap: 39.86593344309236 cap_limit: 40
5570 customer_5 ('customer_5', 'customer_4')
2525 customer_5 -26.310387663866603
resNode: customer_4 deliver_cap: 63.02280436782732 cap_limit: 40
5571 customer_2 ('customer_2', 'customer_3')
2538 customer_2 -17.0982931921126
resNode: customer_3 deliver_cap: 69.71381477847005 cap_limit: 40
5572 customer_2 ('customer_2', 'customer_1')
2538 customer_2 -17.0982931921126
resNode: customer_1 deliver_cap: 55.87140112300506 cap_limit: 40
5573 customer_2 ('customer_2', 'depot_t')
2538 customer_2 -17.0982931921126
resNode: depot_t deliver_cap: 39.94270432190031 cap_limit: 40
5574 customer_2 ('customer_2', 'customer_4')
2538 customer_2 -17.0982931921126
resNode: customer_4 deliver_cap: 69.51719910206039 cap_limit: 40
5575 customer_2 ('customer_2', 'customer_5')
2538 customer_2 -17.0982931921126
resNode: customer_5 deliver_cap: 54.61141060512639 cap_limit: 40
5576 customer_2 ('customer_2', 'customer_3')
2544 customer_2 -22.839191739986145
resNode: customer_3 deliver_cap: 67.99661893765965 cap_limit: 40
5577 customer_2 ('customer_2', 'customer_1')
2544 customer_2 -22.839191739986145
resNode: customer_1 deliver_cap: 56.311297288035 cap_limit: 40
5578 customer_2 ('customer_2', 'depot_t')
2544 customer_2 -22.839191739986145
resNode: depot_t deliver_cap: 38.253220314133124 cap_limit: 40
5579 customer_2 ('customer_2', 'customer_4')
2544 customer_2 -22.839191739986145
resNode: customer_4 deliver_cap: 67.76313782192318 cap_limit: 40
5580 customer_2 ('customer_2', 'customer_5')
2544 customer_2 -22.839191739986145
resNode: customer_5 deliver_cap: 50.06251398181405 cap_limit: 40
5581 customer_2 ('customer_2', 'customer_3')
2558 customer_2 -19.660447889024308
resNode: customer_3 deliver_cap: 65.72195502765248 cap_limit: 40
5582 customer_2 ('customer_2', 'customer_1')
2558 customer_2 -19.660447889024308
resNode: customer_1 deliver_cap: 52.6280150754658 cap_limit: 40
5583 customer_2 ('customer_2', 'depot_t')
2558 customer_2 -19.660447889024308
resNode: depot_t deliver_cap: 36.948809508787136 cap_limit: 40
5584 customer_2 ('customer_2', 'customer_4')
2558 customer_2 -19.660447889024308
resNode: customer_4 deliver_cap: 65.52533935124282 cap_limit: 40
5585 customer_2 ('customer_2', 'customer_5')
2558 customer_2 -19.660447889024308
resNode: customer_5 deliver_cap: 50.61955085430883 cap_limit: 40
5586 customer_2 ('customer_2', 'customer_3')
2564 customer_2 -24.46575430779999
resNode: customer_3 deliver_cap: 63.2562854835638 cap_limit: 40
5587 customer_2 ('customer_2', 'customer_1')
2564 customer_2 -24.46575430779999
resNode: customer_1 deliver_cap: 52.319437537217446 cap_limit: 40
5588 customer_2 ('customer_2', 'depot_t')
2564 customer_2 -24.46575430779999
resNode: depot_t deliver_cap: 34.510851797741665 cap_limit: 40
5589 customer_2 ('customer_2', 'customer_4')
2564 customer_2 -24.46575430779999
resNode: customer_4 deliver_cap: 63.022804367827334 cap_limit: 40
5590 customer_2 ('customer_2', 'customer_5')
2564 customer_2 -24.46575430779999
resNode: customer_5 deliver_cap: 45.32218052771821 cap_limit: 40
5591 customer_1 ('customer_1', 'customer_3')
2567 customer_1 -15.448718055842802
resNode: customer_3 deliver_cap: 62.06832768284507 cap_limit: 40
5592 customer_1 ('customer_1', 'depot_t')
2567 customer_1 -15.448718055842802
resNode: depot_t deliver_cap: 36.43477966763017 cap_limit: 40
5593 customer_1 ('customer_1', 'customer_2')
2567 customer_1 -15.448718055842802
resNode: customer_2 deliver_cap: 40.483088519589074 cap_limit: 40
5594 customer_1 ('customer_1', 'customer_4')
2567 customer_1 -15.448718055842802
resNode: customer_4 deliver_cap: 61.66762757589108 cap_limit: 40
5595 customer_1 ('customer_1', 'customer_5')
2567 customer_1 -15.448718055842802
resNode: customer_5 deliver_cap: 52.790026126901836 cap_limit: 40
5596 customer_5 ('customer_5', 'customer_3')
2570 customer_5 -24.93205295521797
resNode: customer_3 deliver_cap: 65.72195502765248 cap_limit: 40
5597 customer_5 ('customer_5', 'customer_1')
2570 customer_5 -24.93205295521797
resNode: customer_1 deliver_cap: 54.17118405676507 cap_limit: 40
5598 customer_5 ('customer_5', 'depot_t')
2570 customer_5 -24.93205295521797
resNode: depot_t deliver_cap: 37.964663140731616 cap_limit: 40
5599 customer_5 ('customer_5', 'customer_2')
2570 customer_5 -24.93205295521797
resNode: customer_2 deliver_cap: 42.50954299898917 cap_limit: 40
5600 customer_5 ('customer_5', 'customer_4')
2570 customer_5 -24.93205295521797
resNode: customer_4 deliver_cap: 65.52533935124282 cap_limit: 40
5601 customer_2 ('customer_2', 'customer_3')
2574 customer_2 -24.864142449220196
resNode: customer_3 deliver_cap: 67.62123992771315 cap_limit: 40
5602 customer_2 ('customer_2', 'customer_1')
2574 customer_2 -24.864142449220196

5673 customer_5 ('customer_5', 'depot_t')
2650 customer_5 -27.924533057615008
resNode: depot_t deliver_cap: 39.30241654405395 cap_limit: 40
5674 customer_5 ('customer_5', 'customer_2')
2650 customer_5 -27.924533057615008
resNode: customer_2 deliver_cap: 43.95877585258836 cap_limit: 40
5675 customer_5 ('customer_5', 'customer_4')
2650 customer_5 -27.924533057615008
resNode: customer_4 deliver_cap: 67.3090105556726 cap_limit: 40
5676 customer_3 ('customer_3', 'customer_1')
2651 customer_3 -19.256832853384502
resNode: customer_1 deliver_cap: 47.151734075648626 cap_limit: 40
5677 customer_3 ('customer_3', 'depot_t')
2651 customer_3 -19.256832853384502
resNode: depot_t deliver_cap: 35.47859340849407 cap_limit: 40
5678 customer_3 ('customer_3', 'customer_2')
2651 customer_3 -19.256832853384502
resNode: customer_2 deliver_cap: 40.483088519589074 cap_limit: 40
5679 customer_3 ('customer_3', 'customer_4')
2651 customer_3 -19.256832853384502
resNode: customer_4 deliver_cap: 54.49024319314181 cap_limit: 40
5680 customer_3 ('customer_3', 'customer_5')
2651 customer_3 -19.256832853384502
resNode: customer_5 deliver_cap: 51.24685714560254 cap_limit: 40
5681 customer_2 ('customer_2', 'customer_3')
2653 customer_2 -8.600393758819493
resNode: customer_3 deliver_cap: 42.44442771564476 cap_limit: 40
5682 customer_2 ('customer_2', 'customer_1')
2653 customer_2 -8.600393758819493
resNode: customer_1 deliver_cap: 29.29590604006572 cap_limit: 40
5683 customer_2 ('customer_2', 'depot_t')
2653 customer_2 -8.600393758819493
resNode: depot_t deliver_cap: 19.295328248410737 cap_limit: 40
5684 customer_2 ('customer_2', 'customer_4')
2653 customer_2 -8.600393758819493
resNode: customer_4 deliver_cap: 42.32154291788872 cap_limit: 40
5685 customer_2 ('customer_2', 'customer_5')
2653 customer_2 -8.600393758819493
resNode: customer_5 deliver_cap: 33.005425107304966 cap_limit: 40
5686 customer_4 ('customer_4', 'customer_3')
2654 customer_4 -19.1297271299983
resNode: customer_3 deliver_cap: 54.24929332327067 cap_limit: 40
5687 customer_4 ('customer_4', 'customer_1')
2654 customer_4 -19.1297271299983
resNode: customer_1 deliver_cap: 46.65815717039854 cap_limit: 40
5688 customer_4 ('customer_4', 'depot_t')
2654 customer_4 -19.1297271299983
resNode: depot_t deliver_cap: 35.20118564214131 cap_limit: 40
5689 customer_4 ('customer_4', 'customer_2')
2654 customer_4 -19.1297271299983
resNode: customer_2 deliver_cap: 40.174857668086005 cap_limit: 40
5690 customer_4 ('customer_4', 'customer_5')
2654 customer_4 -19.1297271299983
resNode: customer_5 deliver_cap: 50.846157038648556 cap_limit: 40
5691 customer_5 ('customer_5', 'customer_3')
2655 customer_5 -19.918716551464613
resNode: customer_3 deliver_cap: 54.23925898050102 cap_limit: 40
5692 customer_5 ('customer_5', 'customer_1')
2655 customer_5 -19.918716551464613
resNode: customer_1 deliver_cap: 42.31642659792189 cap_limit: 40
5693 customer_5 ('customer_5', 'depot_t')
2655 customer_5 -19.918716551464613
resNode: depot_t deliver_cap: 29.055153869764126 cap_limit: 40
5694 customer_5 ('customer_5', 'customer_2')
2655 customer_5 -19.918716551464613
resNode: customer_2 deliver_cap: 33.3459334765558 cap_limit: 40
5695 customer_5 ('customer_5', 'customer_4')
2655 customer_5 -19.918716551464613
resNode: customer_4 deliver_cap: 54.079508743418174 cap_limit: 40
5696 customer_1 ('customer_1', 'customer_3')
2657 customer_1 -17.577051619264125
resNode: customer_3 deliver_cap: 61.66762757589108 cap_limit: 40
5697 customer_1 ('customer_1', 'depot_t')
2657 customer_1 -17.577051619264125
resNode: depot_t deliver_cap: 36.157371901277415 cap_limit: 40
5698 customer_1 ('customer_1', 'customer_2')
2657 customer_1 -17.577051619264125
resNode: customer_2 deliver_cap: 40.17485766808601 cap_limit: 40
5699 customer_1 ('customer_1', 'customer_4')
2657 customer_1 -17.577051619264125
resNode: customer_4 deliver_cap: 61.266927468937105 cap_limit: 40
5700 customer_1 ('customer_1', 'customer_5')
2657 customer_1 -17.577051619264125
resNode: customer_5 deliver_cap: 52.389326019947845 cap_limit: 40
5701 customer_2 ('customer_2', 'customer_3')
2659 customer_2 -16.783411741680663
resNode: customer_3 deliver_cap: 57.17023710762042 cap_limit: 40
5702 customer_2 ('customer_2', 'customer_1')
2659 customer_2 -16.783411741680663
resNode: customer_1 deliver_cap: 43.3839720947066 cap_limit: 40
5703 customer_2 ('customer_2', 'depot_t')
2659 customer_2 -16.783411741680663
resNode: depot_t deliver_cap: 30.322402349196125 cap_limit: 40
5704 customer_2 ('customer_2', 'customer_4')
2659 customer_2 -16.783411741680663
resNode: customer_4 deliver_cap: 57.01048687053758 cap_limit: 40
5705 customer_2 ('customer_2', 'customer_5')
2659 customer_2 -16.783411741680663
resNode: customer_5 deliver_cap: 44.899533716778706 cap_limit: 40
5706 customer_5 ('customer_5', 'customer_3')
2660 customer_5 -27.854898338886592
resNode: customer_3 deliver_cap: 67.3090105556726 cap_limit: 40
5707 customer_5 ('customer_5', 'customer_1')
2660 customer_5 -27.854898338886592
resNode: customer_1 deliver_cap: 55.460666673281416 cap_limit: 40
5708 customer_5 ('customer_5', 'depot_t')
2660 customer_5 -27.854898338886592
resNode: depot_t deliver_cap: 39.15495478674671 cap_limit: 40
5709 customer_5 ('customer_5', 'customer_2')
2660 customer_5 -27.854898338886592
resNode: customer_2 deliver_cap: 43.79902561550551 cap_limit: 40
5710 customer_5 ('customer_5', 'customer_4')
2660 customer_5 -27.854898338886592
resNode: customer_4 deliver_cap: 67.11239487926294 cap_limit: 40
5711 customer_3 ('customer_3', 'customer_1')
2661 customer_3 -24.148932014279097
resNode: customer_1 deliver_cap: 52.6280150754658 cap_limit: 40
5712 customer_3 ('customer_3', 'depot_t')
2661 customer_3 -24.148932014279097
resNode: depot_t deliver_cap: 39.30241654405395 cap_limit: 40
5713 customer_3 ('customer_3', 'customer_2')
2661 customer_3 -24.148932014279097
resNode: customer_2 deliver_cap: 43.95877585258836 cap_limit: 40
5714 customer_3 ('customer_3', 'customer_4')
2661 customer_3 -24.148932014279097
resNode: customer_4 deliver_cap: 56.39508180955616 cap_limit: 40
5715 customer_3 ('customer_3', 'customer_5')
2661 customer_3 -24.148932014279097
resNode: customer_5 deliver_cap: 52.4032220587386 cap_limit: 40
5716 customer_1 ('customer_1', 'customer_3')
2662 customer_1 -16.688271173955997
resNode: customer_3 deliver_cap: 52.79002612690183 cap_limit: 40
5717 customer_1 ('customer_1', 'depot_t')
2662 customer_1 -16.688271173955997
resNode: depot_t deliver_cap: 30.011340128900226 cap_limit: 40
5718 customer_1 ('customer_1', 'customer_2')
2662 customer_1 -16.688271173955997
resNode: customer_2 deliver_cap: 33.34593347655581 cap_limit: 40
5719 customer_1 ('customer_1', 'customer_4')
2662 customer_1 -16.688271173955997
resNode: customer_4 deliver_cap: 52.389326019947845 cap_limit: 40
5720 customer_1 ('customer_1', 'customer_5')
2662 customer_1 -16.688271173955997
resNode: customer_5 deliver_cap: 43.511724570958584 cap_limit: 40
5721 customer_2 ('customer_2', 'customer_3')
2664 customer_2 -15.08629337018013
resNode: customer_3 deliver_cap: 45.05928395386155 cap_limit: 40
5722 customer_2 ('customer_2', 'customer_1')
2664 customer_2 -15.08629337018013
resNode: customer_1 deliver_cap: 34.06785428412285 cap_limit: 40
5723 customer_2 ('customer_2', 'depot_t')
2664 customer_2 -15.08629337018013
resNode: depot_t deliver_cap: 21.93789631967075 cap_limit: 40
5724 customer_2 ('customer_2', 'customer_4')
2664 customer_2 -15.08629337018013
resNode: customer_4 deliver_cap: 44.899533716778706 cap_limit: 40
5725 customer_2 ('customer_2', 'customer_5')
2664 customer_2 -15.08629337018013
resNode: customer_5 deliver_cap: 32.78858056301983 cap_limit: 40
5726 customer_4 ('customer_4', 'customer_3')
2665 customer_4 -24.12845121465309
resNode: customer_3 deliver_cap: 56.39508180955616 cap_limit: 40
5727 customer_4 ('customer_4', 'customer_1')
2665 customer_4 -24.12845121465309
resNode: customer_1 deliver_cap: 52.227314968511806 cap_limit: 40
5728 customer_4 ('customer_4', 'depot_t')
2665 customer_4 -24.12845121465309
resNode: depot_t deliver_cap: 39.15495478674671 cap_limit: 40
5729 customer_4 ('customer_4', 'customer_2')
2665 customer_4 -24.12845121465309
resNode: customer_2 deliver_cap: 43.79902561550551 cap_limit: 40
5730 customer_4 ('customer_4', 'customer_5')
2665 customer_4 -24.12845121465309
resNode: customer_5 deliver_cap: 52.206606382328935 cap_limit: 40
5731 customer_2 ('customer_2', 'customer_3')
2668 customer_2 -22.416831061693813
resNode: customer_3 deliver_cap: 69.41726109247479 cap_limit: 40
5732 customer_2 ('customer_2', 'customer_1')
2668 customer_2 -22.416831061693813
resNode: customer_1 deliver_cap: 55.63045125313392 cap_limit: 40
5733 customer_2 ('customer_2', 'depot_t')
2668 customer_2 -22.416831061693813
resNode: depot_t deliver_cap: 39.72028905740386 cap_limit: 40
5734 customer_2 ('customer_2', 'customer_4')
2668 customer_2 -22.416831061693813
resNode: customer_4 deliver_cap: 69.22064541606512 cap_limit: 40
5735 customer_2 ('customer_2', 'customer_5')
2668 customer_2 -22.416831061693813
resNode: customer_5 deliver_cap: 54.31485691913113 cap_limit: 40
5736 customer_2 ('customer_2', 'customer_3')
2673 customer_2 -16.700371335602256
resNode: customer_3 deliver_cap: 61.42667770601995 cap_limit: 40
5737 customer_2 ('customer_2', 'customer_1')
2673 customer_2 -16.700371335602256
resNode: customer_1 deliver_cap: 46.65815717039854 cap_limit: 40
5738 customer_2 ('customer_2', 'depot_t')
2673 customer_2 -16.700371335602256
resNode: depot_t deliver_cap: 33.26916891731887 cap_limit: 40
5739 customer_2 ('customer_2', 'customer_4')
2673 customer_2 -16.700371335602256
resNode: customer_4 deliver_cap: 61.266927468937105 cap_limit: 40
5740 customer_2 ('customer_2', 'customer_5')
2673 customer_2 -16.700371335602256
resNode: customer_5 deliver_cap: 49.15597431517823 cap_limit: 40
5741 customer_1 ('customer_1', 'customer_3')
2677 customer_1 -17.095003574022698
resNode: customer_3 deliver_cap: 61.66762757589108 cap_limit: 40
5742 customer_1 ('customer_1', 'depot_t')
2677 customer_1 -17.095003574022698
resNode: depot_t deliver_cap: 36.1573719012774 cap_limit: 40
5743 customer_1 ('customer_1', 'customer_2')
2677 customer_1 -17.095003574022698
resNode: customer_2 deliver_cap: 40.174857668086005 cap_limit: 40
5744 customer_1 ('customer_1', 'customer_4')
2677 customer_1 -17.095003574022698
resNode: customer_4 deliver_cap: 61.26692746893709 cap_limit: 40
5745 customer_1 ('customer_1', 'customer_5')
2677 customer_1 -17.095003574022698
resNode: customer_5 deliver_cap: 52.389326019947845 cap_limit: 40
5746 customer_5 ('customer_5', 'customer_3')
2680 customer_5 -26.462751904084215
resNode: customer_3 deliver_cap: 65.22878566524757 cap_limit: 40
5747 customer_5 ('customer_5', 'customer_1')
2680 customer_5 -26.462751904084215
resNode: customer_1 deliver_cap: 53.77048394981108 cap_limit: 40
5748 customer_5 ('customer_5', 'depot_t')
2680 customer_5 -26.462751904084215
resNode: depot_t deliver_cap: 37.594786118927935 cap_limit: 40
5749 customer_5 ('customer_5', 'customer_2')
2680 customer_5 -26.462751904084215
resNode: customer_2 deliver_cap: 42.10884289203518 cap_limit: 40
5750 customer_5 ('customer_5', 'customer_4')
2680 customer_5 -26.462751904084215
resNode: customer_4 deliver_cap: 65.03216998883791 cap_limit: 40
5751 customer_2 ('customer_2', 'customer_3')
2684 customer_2 -25.445198948056113
resNode: customer_3 deliver_cap: 65.22878566524757 cap_limit: 40
5752 customer_2 ('customer_2', 'customer_1')
2684 customer_2 -25.445198948056113
resNode: customer_1 deliver_cap: 52.227314968511806 cap_limit: 40
5753 customer_2 ('customer_2', 'depot_t')
2684 customer_2 -25.445198948056113
resNode: depot_t deliver_cap: 36.57893248698345 cap_limit: 40
5754 customer_2 ('customer_2', 'customer_4')
2684 customer_2 -25.445198948056113
resNode: customer_4 deliver_cap: 65.03216998883791 cap_limit: 40
5755 customer_2 ('customer_2', 'customer_5')
2684 customer_2 -25.445198948056113
resNode: customer_5 deliver_cap: 50.12638149190391 cap_limit: 40
5756 customer_2 ('customer_2', 'customer_3')
2688 customer_2 -24.73615344608848
resNode: customer_3 deliver_cap: 69.40491113214291 cap_limit: 40
5757 customer_2 ('customer_2', 'customer_1')
2688 customer_2 -24.73615344608848
resNode: customer_1 deliver_cap: 55.620416910364256 cap_limit: 40
5758 customer_2 ('customer_2', 'depot_t')
2688 customer_2 -24.73615344608848
resNode: depot_t deliver_cap: 39.711026587154954 cap_limit: 40
5759 customer_2 ('customer_2', 'customer_4')
2688 customer_2 -24.73615344608848
resNode: customer_4 deliver_cap: 69.20829545573325 cap_limit: 40
5760 customer_2 ('customer_2', 'customer_5')
2688 customer_2 -24.73615344608848
resNode: customer_5 deliver_cap: 54.30250695879925 cap_limit: 40
5761 customer_2 ('customer_2', 'customer_3')
2693 customer_2 -17.180633206860286
resNode: customer_3 deliver_cap: 55.7824279618003 cap_limit: 40
5762 customer_2 ('customer_2', 'customer_1')
2693 customer_2 -17.180633206860286
resNode: customer_1 deliver_cap: 42.31642659792189 cap_limit: 40
5763 customer_2 ('customer_2', 'depot_t')
2693 customer_2 -17.180633206860286
resNode: depot_t deliver_cap: 29.361611402089885 cap_limit: 40
5764 customer_2 ('customer_2', 'customer_4')
2693 customer_2 -17.180633206860286
resNode: customer_4 deliver_cap: 55.62267772471745 cap_limit: 40
5765 customer_2 ('customer_2', 'customer_5')
2693 customer_2 -17.180633206860286
resNode: customer_5 deliver_cap: 43.51172457095858 cap_limit: 40
5766 customer_5 ('customer_5', 'customer_3')
2695 customer_5 -28.682727386548486
resNode: customer_3 deliver_cap: 67.50022266087772 cap_limit: 40
5767 customer_5 ('customer_5', 'customer_1')
2695 customer_5 -28.682727386548486
resNode: customer_1 deliver_cap: 55.616026508760584 cap_limit: 40
5768 customer_5 ('customer_5', 'depot_t')
2695 customer_5 -28.682727386548486
resNode: depot_t deliver_cap: 39.29836386565054 cap_limit: 40
5769 customer_5 ('customer_5', 'customer_2')
2695 customer_5 -28.682727386548486
resNode: customer_2 deliver_cap: 43.954385450984674 cap_limit: 40
5770 customer_5 ('customer_5', 'customer_4')
2695 customer_5 -28.682727386548486
resNode: customer_4 deliver_cap: 67.30360698446806 cap_limit: 40
5771 customer_1 ('customer_1', 'customer_3')
2697 customer_1 -16.518208157182965
resNode: customer_3 deliver_cap: 52.79002612690183 cap_limit: 40
5772 customer_1 ('customer_1', 'depot_t')
2697 customer_1 -16.518208157182965
resNode: depot_t deliver_cap: 30.011340128900223 cap_limit: 40
5773 customer_1 ('customer_1', 'customer_2')
2697 customer_1 -16.518208157182965
resNode: customer_2 deliver_cap: 33.3459334765558 cap_limit: 40
5774 customer_1 ('customer_1', 'customer_4')
2697 customer_1 -16.518208157182965
resNode: customer_4 deliver_cap: 52.38932601994784 cap_limit: 40
5775 customer_1 ('customer_1', 'customer_5')
2697 customer_1 -16.518208157182965
resNode: customer_5 deliver_cap: 43.51172457095857 cap_limit: 40
5776 customer_5 ('customer_5', 'customer_3')
2700 customer_5 -23.325109915420654
resNode: customer_3 deliver_cap: 54.30250695879925 cap_limit: 40
5777 customer_5 ('customer_5', 'customer_1')
2700 customer_5 -23.325109915420654
resNode: customer_1 deliver_cap: 44.89288250082183 cap_limit: 40
5778 customer_5 ('customer_5', 'depot_t')
2700 customer_5 -23.325109915420654
resNode: depot_t deliver_cap: 29.400077089091695 cap_limit: 40
5779 customer_5 ('customer_5', 'customer_2')
2700 customer_5 -23.325109915420654
resNode: customer_2 deliver_cap: 33.23124144304592 cap_limit: 40
5780 customer_5 ('customer_5', 'customer_4')
2700 customer_5 -23.325109915420654
resNode: customer_4 deliver_cap: 54.10589128238959 cap_limit: 40
5781 customer_2 ('customer_2', 'customer_3')
2704 customer_2 -24.703384166686867
resNode: customer_3 deliver_cap: 69.20829545573325 cap_limit: 40
5782 customer_2 ('customer_2', 'customer_1')
2704 customer_2 -24.703384166686867
resNode: customer_1 deliver_cap: 55.460666673281416 cap_limit: 40
5783 customer_2 ('customer_2', 'depot_t')
2704 customer_2 -24.703384166686867
resNode: depot_t deliver_cap: 39.56356482984771 cap_limit: 40
5784 customer_2 ('customer_2', 'customer_4')
2704 customer_2 -24.703384166686867
resNode: customer_4 deliver_cap: 69.01167977932359 cap_limit: 40
5785 customer_2 ('customer_2', 'customer_5')
2704 customer_2 -24.703384166686867
resNode: customer_5 deliver_cap: 54.10589128238959 cap_limit: 40
5786 customer_2 ('customer_2', 'customer_3')
2708 customer_2 -18.386241926325816
resNode: customer_3 deliver_cap: 69.71381477847004 cap_limit: 40
5787 customer_2 ('customer_2', 'customer_1')
2708 customer_2 -18.386241926325816
resNode: customer_1 deliver_cap: 55.87140112300506 cap_limit: 40
5788 customer_2 ('customer_2', 'depot_t')
2708 customer_2 -18.386241926325816
resNode: depot_t deliver_cap: 39.9427043219003 cap_limit: 40
5789 customer_2 ('customer_2', 'customer_4')
2708 customer_2 -18.386241926325816
resNode: customer_4 deliver_cap: 69.51719910206037 cap_limit: 40
5790 customer_2 ('customer_2', 'customer_5')
2708 customer_2 -18.386241926325816
resNode: customer_5 deliver_cap: 54.61141060512638 cap_limit: 40
5791 customer_2 ('customer_2', 'customer_3')
2724 customer_2 -25.102585664121897
resNode: customer_3 deliver_cap: 70.11472849292 cap_limit: 40
5792 customer_2 ('customer_2', 'customer_1')
2724 customer_2 -25.102585664121897
resNode: customer_1 deliver_cap: 58.09496849246477 cap_limit: 40
5793 customer_2 ('customer_2', 'depot_t')
2724 customer_2 -25.102585664121897
resNode: depot_t deliver_cap: 39.925412068286036 cap_limit: 40
5794 customer_2 ('customer_2', 'customer_4')
2724 customer_2 -25.102585664121897
resNode: customer_4 deliver_cap: 69.88124737718353 cap_limit: 40
5795 customer_2 ('customer_2', 'customer_5')
2724 customer_2 -25.102585664121897
resNode: customer_5 deliver_cap: 52.18062353707441 cap_limit: 40
5796 customer_1 ('customer_1', 'customer_3')
2727 customer_1 -15.3032814985045
resNode: customer_3 deliver_cap: 61.66762757589108 cap_limit: 40
5797 customer_1 ('customer_1', 'depot_t')
2727 customer_1 -15.3032814985045
resNode: depot_t deliver_cap: 36.157371901277415 cap_limit: 40
5798 customer_1 ('customer_1', 'customer_2')
2727 customer_1 -15.3032814985045
resNode: customer_2 deliver_cap: 40.17485766808601 cap_limit: 40
5799 customer_1 ('customer_1', 'customer_4')
2727 customer_1 -15.3032814985045
resNode: customer_4 deliver_cap: 61.266927468937105 cap_limit: 40
5800 customer_1 ('customer_1', 'customer_5')
2727 customer_1 -15.3032814985045
resNode: customer_5 deliver_cap: 52.389326019947845 cap_limit: 40
5801 customer_5 ('customer_5', 'customer_3')
2730 customer_5 -24.671029828566013
resNode: customer_3 deliver_cap: 65.22878566524759 cap_limit: 40
5802 customer_5 ('customer_5', 'customer_1')
2730 customer_5 -24.671029828566013
resNode: customer_1 deliver_cap: 53.770483949811094 cap_limit: 40
5803 customer_5 ('customer_5', 'depot_t')
2730 customer_5 -24.671029828566013
resNode: depot_t deliver_cap: 37.59478611892794 cap_limit: 40
5804 customer_5 ('customer_5', 'customer_2')
2730 customer_5 -24.671029828566013
resNode: customer_2 deliver_cap: 42.108842892035184 cap_limit: 40
5805 customer_5 ('customer_5', 'customer_4')
2730 customer_5 -24.671029828566013
resNode: customer_4 deliver_cap: 65.03216998883792 cap_limit: 40
5806 customer_2 ('customer_2', 'customer_3')
2734 customer_2 -24.60311932256824
resNode: customer_3 deliver_cap: 67.12807056530824 cap_limit: 40
5807 customer_2 ('customer_2', 'customer_1')
2734 customer_2 -24.60311932256824
resNode: customer_1 deliver_cap: 53.770483949811094 cap_limit: 40
5808 customer_2 ('customer_2', 'depot_t')
2734 customer_2 -24.60311932256824
resNode: depot_t deliver_cap: 38.00339616202894 cap_limit: 40
5809 customer_2 ('customer_2', 'customer_4')
2734 customer_2 -24.60311932256824
resNode: customer_4 deliver_cap: 66.93145488889857 cap_limit: 40
5810 customer_2 ('customer_2', 'customer_5')
2734 customer_2 -24.60311932256824
resNode: customer_5 deliver_cap: 52.02566639196457 cap_limit: 40

2808 customer_2 -16.033829251318444
resNode: customer_3 deliver_cap: 58.106480330125116 cap_limit: 40
5882 customer_2 ('customer_2', 'customer_1')
2808 customer_2 -16.033829251318444
resNode: customer_1 deliver_cap: 46.44044188372481 cap_limit: 40
5883 customer_2 ('customer_2', 'depot_t')
2808 customer_2 -16.033829251318444
resNode: depot_t deliver_cap: 31.237203485641608 cap_limit: 40
5884 customer_2 ('customer_2', 'customer_4')
2808 customer_2 -16.033829251318444
resNode: customer_4 deliver_cap: 57.90986465371546 cap_limit: 40
5885 customer_2 ('customer_2', 'customer_5')
2808 customer_2 -16.033829251318444
resNode: customer_5 deliver_cap: 43.00407615678146 cap_limit: 40
5886 customer_5 ('customer_5', 'customer_3')
2810 customer_5 -24.152925437360985
resNode: customer_3 deliver_cap: 65.37439503882416 cap_limit: 40
5887 customer_5 ('customer_5', 'customer_1')
2810 customer_5 -24.152925437360985
resNode: customer_1 deliver_cap: 56.00239364170788 cap_limit: 40
5888 customer_5 ('customer_5', 'depot_t')
2810 customer_5 -24.152925437360985
resNode: depot_t deliver_cap: 37.452860591825186 cap_limit: 40
5889 customer_5 ('customer_5', 'customer_2')
2810 customer_5 -24.152925437360985
resNode: customer_2 deliver_cap: 41.649604647522146 cap_limit: 40
5890 customer_5 ('customer_5', 'customer_4')
2810 customer_5 -24.152925437360985
resNode: customer_4 deliver_cap: 65.1409139230877 cap_limit: 40
5891 customer_3 ('customer_3', 'customer_1')
2811 customer_3 -18.904163671895496
resNode: customer_1 deliver_cap: 51.1787822218666 cap_limit: 40
5892 customer_3 ('customer_3', 'depot_t')
2811 customer_3 -18.904163671895496
resNode: depot_t deliver_cap: 37.964663140731616 cap_limit: 40
5893 customer_3 ('customer_3', 'customer_2')
2811 customer_3 -18.904163671895496
resNode: customer_2 deliver_cap: 42.50954299898917 cap_limit: 40
5894 customer_3 ('customer_3', 'customer_4')
2811 customer_3 -18.904163671895496
resNode: customer_4 deliver_cap: 54.61141060512638 cap_limit: 40
5895 customer_3 ('customer_3', 'customer_5')
2811 customer_3 -18.904163671895496
resNode: customer_5 deliver_cap: 50.61955085430883 cap_limit: 40
5896 customer_2 ('customer_2', 'customer_3')
2813 customer_2 -10.62188117973456
resNode: customer_3 deliver_cap: 45.05928395386156 cap_limit: 40
5897 customer_2 ('customer_2', 'customer_1')
2813 customer_2 -10.62188117973456
resNode: customer_1 deliver_cap: 34.06785428412285 cap_limit: 40
5898 customer_2 ('customer_2', 'depot_t')
2813 customer_2 -10.62188117973456
resNode: depot_t deliver_cap: 21.937896319670752 cap_limit: 40
5899 customer_2 ('customer_2', 'customer_4')
2813 customer_2 -10.62188117973456
resNode: customer_4 deliver_cap: 44.899533716778706 cap_limit: 40
5900 customer_2 ('customer_2', 'customer_5')
2813 customer_2 -10.62188117973456
resNode: customer_5 deliver_cap: 32.788580563019835 cap_limit: 40
5901 customer_4 ('customer_4', 'customer_3')
2814 customer_4 -18.753940634646575
resNode: customer_3 deliver_cap: 54.314856919131145 cap_limit: 40
5902 customer_4 ('customer_4', 'customer_1')
2814 customer_4 -18.753940634646575
resNode: customer_1 deliver_cap: 50.53713224504148 cap_limit: 40
5903 customer_4 ('customer_4', 'depot_t')
2814 customer_4 -18.753940634646575
resNode: depot_t deliver_cap: 37.59478611892794 cap_limit: 40
5904 customer_4 ('customer_4', 'customer_2')
2814 customer_4 -18.753940634646575
resNode: customer_2 deliver_cap: 42.10884289203519 cap_limit: 40
5905 customer_4 ('customer_4', 'customer_5')
2814 customer_4 -18.753940634646575
resNode: customer_5 deliver_cap: 50.12638149190392 cap_limit: 40
5906 customer_5 ('customer_5', 'customer_3')
2815 customer_5 -19.030760741748118
resNode: customer_3 deliver_cap: 54.30250695879926 cap_limit: 40
5907 customer_5 ('customer_5', 'customer_1')
2815 customer_5 -19.030760741748118
resNode: customer_1 deliver_cap: 44.89288250082184 cap_limit: 40
5908 customer_5 ('customer_5', 'depot_t')
2815 customer_5 -19.030760741748118
resNode: depot_t deliver_cap: 29.400077089091702 cap_limit: 40
5909 customer_5 ('customer_5', 'customer_2')
2815 customer_5 -19.030760741748118
resNode: customer_2 deliver_cap: 33.231241443045924 cap_limit: 40
5910 customer_5 ('customer_5', 'customer_4')
2815 customer_5 -19.030760741748118
resNode: customer_4 deliver_cap: 54.10589128238961 cap_limit: 40
5911 customer_1 ('customer_1', 'customer_3')
2817 customer_1 -17.280947312173737
resNode: customer_3 deliver_cap: 63.445114460817805 cap_limit: 40
5912 customer_1 ('customer_1', 'depot_t')
2817 customer_1 -17.280947312173737
resNode: depot_t deliver_cap: 38.86970113110941 cap_limit: 40
5913 customer_1 ('customer_1', 'customer_2')
2817 customer_1 -17.280947312173737
resNode: customer_2 deliver_cap: 42.10884289203519 cap_limit: 40
5914 customer_1 ('customer_1', 'customer_4')
2817 customer_1 -17.280947312173737
resNode: customer_4 deliver_cap: 62.95194509841291 cap_limit: 40
5915 customer_1 ('customer_1', 'customer_5')
2817 customer_1 -17.280947312173737
resNode: customer_5 deliver_cap: 52.025666391964585 cap_limit: 40
5916 customer_2 ('customer_2', 'customer_3')
2819 customer_2 -16.00105997191684
resNode: customer_3 deliver_cap: 57.90986465371546 cap_limit: 40
5917 customer_2 ('customer_2', 'customer_1')
2819 customer_2 -16.00105997191684
resNode: customer_1 deliver_cap: 46.28069164664196 cap_limit: 40
5918 customer_2 ('customer_2', 'depot_t')
2819 customer_2 -16.00105997191684
resNode: depot_t deliver_cap: 31.089741728334367 cap_limit: 40
5919 customer_2 ('customer_2', 'customer_4')
2819 customer_2 -16.00105997191684
resNode: customer_4 deliver_cap: 57.713248977305796 cap_limit: 40
5920 customer_2 ('customer_2', 'customer_5')
2819 customer_2 -16.00105997191684
resNode: customer_5 deliver_cap: 42.8074604803718 cap_limit: 40
5921 customer_5 ('customer_5', 'customer_3')
2820 customer_5 -24.074074358800857
resNode: customer_3 deliver_cap: 65.1409139230877 cap_limit: 40
5922 customer_5 ('customer_5', 'customer_1')
2820 customer_5 -24.074074358800857
resNode: customer_1 deliver_cap: 55.80577796529822 cap_limit: 40
5923 customer_5 ('customer_5', 'depot_t')
2820 customer_5 -24.074074358800857
resNode: depot_t deliver_cap: 37.26853339519113 cap_limit: 40
5924 customer_5 ('customer_5', 'customer_2')
2820 customer_5 -24.074074358800857
resNode: customer_2 deliver_cap: 41.45298897111248 cap_limit: 40
5925 customer_5 ('customer_5', 'customer_4')
2820 customer_5 -24.074074358800857
resNode: customer_4 deliver_cap: 64.90743280735123 cap_limit: 40
5926 customer_3 ('customer_3', 'customer_1')
2821 customer_3 -20.377324394025067
resNode: customer_1 deliver_cap: 52.319437537217446 cap_limit: 40
5927 customer_3 ('customer_3', 'depot_t')
2821 customer_3 -20.377324394025067
resNode: depot_t deliver_cap: 37.452860591825186 cap_limit: 40
5928 customer_3 ('customer_3', 'customer_2')
2821 customer_3 -20.377324394025067
resNode: customer_2 deliver_cap: 41.649604647522146 cap_limit: 40
5929 customer_3 ('customer_3', 'customer_4')
2821 customer_3 -20.377324394025067
resNode: customer_4 deliver_cap: 52.180623537074425 cap_limit: 40
5930 customer_3 ('customer_3', 'customer_5')
2821 customer_3 -20.377324394025067
resNode: customer_5 deliver_cap: 47.44029008297857 cap_limit: 40
5931 customer_1 ('customer_1', 'customer_3')
2822 customer_1 -15.879997552500845
resNode: customer_3 deliver_cap: 52.51883575436948 cap_limit: 40
5932 customer_1 ('customer_1', 'depot_t')
2822 customer_1 -15.879997552500845
resNode: depot_t deliver_cap: 30.67499210127317 cap_limit: 40
5933 customer_1 ('customer_1', 'customer_2')
2822 customer_1 -15.879997552500845
resNode: customer_2 deliver_cap: 33.231241443045924 cap_limit: 40
5934 customer_1 ('customer_1', 'customer_4')
2822 customer_1 -15.879997552500845
resNode: customer_4 deliver_cap: 52.02566639196458 cap_limit: 40
5935 customer_1 ('customer_1', 'customer_5')
2822 customer_1 -15.879997552500845
resNode: customer_5 deliver_cap: 41.09938768551626 cap_limit: 40
5936 customer_2 ('customer_2', 'customer_3')
2824 customer_2 -13.605232764622524
resNode: customer_3 deliver_cap: 43.004076156781466 cap_limit: 40
5937 customer_2 ('customer_2', 'customer_1')
2824 customer_2 -13.605232764622524
resNode: customer_1 deliver_cap: 34.16973849288309 cap_limit: 40
5938 customer_2 ('customer_2', 'depot_t')
2824 customer_2 -13.605232764622524
resNode: depot_t deliver_cap: 19.910400355633872 cap_limit: 40
5939 customer_2 ('customer_2', 'customer_4')
2824 customer_2 -13.605232764622524
resNode: customer_4 deliver_cap: 42.8074604803718 cap_limit: 40
5940 customer_2 ('customer_2', 'customer_5')
2824 customer_2 -13.605232764622524
resNode: customer_5 deliver_cap: 27.90167198343781 cap_limit: 40
5941 customer_4 ('customer_4', 'customer_3')
2825 customer_4 -20.347627234567362
resNode: customer_3 deliver_cap: 52.180623537074425 cap_limit: 40
5942 customer_4 ('customer_4', 'customer_1')
2825 customer_4 -20.347627234567362
resNode: customer_1 deliver_cap: 51.82626817481254 cap_limit: 40
5943 customer_4 ('customer_4', 'depot_t')
2825 customer_4 -20.347627234567362
resNode: depot_t deliver_cap: 37.268533395191135 cap_limit: 40
5944 customer_4 ('customer_4', 'customer_2')
2825 customer_4 -20.347627234567362
resNode: customer_2 deliver_cap: 41.45298897111249 cap_limit: 40
5945 customer_4 ('customer_4', 'customer_5')
2825 customer_4 -20.347627234567362
resNode: customer_5 deliver_cap: 47.2068089672421 cap_limit: 40
5946 customer_2 ('customer_2', 'customer_3')
2828 customer_2 -20.329019683081597
resNode: customer_3 deliver_cap: 70.11472849292001 cap_limit: 40
5947 customer_2 ('customer_2', 'customer_1')
2828 customer_2 -20.329019683081597
resNode: customer_1 deliver_cap: 58.09496849246478 cap_limit: 40
5948 customer_2 ('customer_2', 'depot_t')
2828 customer_2 -20.329019683081597
resNode: depot_t deliver_cap: 39.925412068286036 cap_limit: 40
5949 customer_2 ('customer_2', 'customer_4')
2828 customer_2 -20.329019683081597
resNode: customer_4 deliver_cap: 69.88124737718354 cap_limit: 40
5950 customer_2 ('customer_2', 'customer_5')
2828 customer_2 -20.329019683081597
resNode: customer_5 deliver_cap: 52.18062353707442 cap_limit: 40
5951 customer_2 ('customer_2', 'customer_3')
2833 customer_2 -17.333709947379397
resNode: customer_3 deliver_cap: 65.22878566524759 cap_limit: 40
5952 customer_2 ('customer_2', 'customer_1')
2833 customer_2 -17.333709947379397
resNode: customer_1 deliver_cap: 52.22731496851182 cap_limit: 40
5953 customer_2 ('customer_2', 'depot_t')
2833 customer_2 -17.333709947379397
resNode: depot_t deliver_cap: 36.578932486983454 cap_limit: 40
5954 customer_2 ('customer_2', 'customer_4')
2833 customer_2 -17.333709947379397
resNode: customer_4 deliver_cap: 65.03216998883792 cap_limit: 40
5955 customer_2 ('customer_2', 'customer_5')
2833 customer_2 -17.333709947379397
resNode: customer_5 deliver_cap: 50.12638149190392 cap_limit: 40
5956 customer_5 ('customer_5', 'customer_3')
2840 customer_5 -24.242096591817244
resNode: customer_3 deliver_cap: 65.14091392308768 cap_limit: 40
5957 customer_5 ('customer_5', 'customer_1')
2840 customer_5 -24.242096591817244
resNode: customer_1 deliver_cap: 55.805777965298205 cap_limit: 40
5958 customer_5 ('customer_5', 'depot_t')
2840 customer_5 -24.242096591817244
resNode: depot_t deliver_cap: 37.26853339519112 cap_limit: 40
5959 customer_5 ('customer_5', 'customer_2')
2840 customer_5 -24.242096591817244
resNode: customer_2 deliver_cap: 41.452988971112475 cap_limit: 40
5960 customer_5 ('customer_5', 'customer_4')
2840 customer_5 -24.242096591817244
resNode: customer_4 deliver_cap: 64.9074328073512 cap_limit: 40
5961 customer_2 ('customer_2', 'customer_3')
2844 customer_2 -23.16105278379261
resNode: customer_3 deliver_cap: 65.14091392308768 cap_limit: 40
5962 customer_2 ('customer_2', 'customer_1')
2844 customer_2 -23.16105278379261
resNode: customer_1 deliver_cap: 53.906493065237555 cap_limit: 40
5963 customer_2 ('customer_2', 'depot_t')
2844 customer_2 -23.16105278379261
resNode: depot_t deliver_cap: 35.99871635526051 cap_limit: 40
5964 customer_2 ('customer_2', 'customer_4')
2844 customer_2 -23.16105278379261
resNode: customer_4 deliver_cap: 64.9074328073512 cap_limit: 40
5965 customer_2 ('customer_2', 'customer_5')
2844 customer_2 -23.16105278379261
resNode: customer_5 deliver_cap: 47.20680896724209 cap_limit: 40
5966 customer_2 ('customer_2', 'customer_3')
2853 customer_2 -16.789654797764346
resNode: customer_3 deliver_cap: 69.4172610924748 cap_limit: 40
5967 customer_2 ('customer_2', 'customer_1')
2853 customer_2 -16.789654797764346
resNode: customer_1 deliver_cap: 55.63045125313393 cap_limit: 40
5968 customer_2 ('customer_2', 'depot_t')
2853 customer_2 -16.789654797764346
resNode: depot_t deliver_cap: 39.720289057403875 cap_limit: 40
5969 customer_2 ('customer_2', 'customer_4')
2853 customer_2 -16.789654797764346
resNode: customer_4 deliver_cap: 69.22064541606514 cap_limit: 40
5970 customer_2 ('customer_2', 'customer_5')
2853 customer_2 -16.789654797764346
resNode: customer_5 deliver_cap: 54.314856919131145 cap_limit: 40
5971 customer_2 ('customer_2', 'customer_3')
2859 customer_2 -22.461048575482753
resNode: customer_3 deliver_cap: 67.6444614355403 cap_limit: 40
5972 customer_2 ('customer_2', 'customer_1')
2859 customer_2 -22.461048575482753
resNode: customer_1 deliver_cap: 56.01474360203976 cap_limit: 40
5973 customer_2 ('customer_2', 'depot_t')
2859 customer_2 -22.461048575482753
resNode: depot_t deliver_cap: 37.97520123351258 cap_limit: 40
5974 customer_2 ('customer_2', 'customer_4')
2859 customer_2 -22.461048575482753
resNode: customer_4 deliver_cap: 67.41098031980383 cap_limit: 40
5975 customer_2 ('customer_2', 'customer_5')
2859 customer_2 -22.461048575482753
resNode: customer_5 deliver_cap: 49.7103564796947 cap_limit: 40
5976 customer_2 ('customer_2', 'customer_3')
2878 customer_2 -14.754019722411826
resNode: customer_3 deliver_cap: 61.42667770601995 cap_limit: 40
5977 customer_2 ('customer_2', 'customer_1')
2878 customer_2 -14.754019722411826
resNode: customer_1 deliver_cap: 46.658157170398546 cap_limit: 40
5978 customer_2 ('customer_2', 'depot_t')
2878 customer_2 -14.754019722411826
resNode: depot_t deliver_cap: 33.26916891731887 cap_limit: 40
5979 customer_2 ('customer_2', 'customer_4')
2878 customer_2 -14.754019722411826
resNode: customer_4 deliver_cap: 61.266927468937105 cap_limit: 40
5980 customer_2 ('customer_2', 'customer_5')
2878 customer_2 -14.754019722411826
resNode: customer_5 deliver_cap: 49.155974315178234 cap_limit: 40
5981 customer_2 ('customer_2', 'customer_3')
2884 customer_2 -22.458734889653172
resNode: customer_3 deliver_cap: 63.148560774822556 cap_limit: 40
5982 customer_2 ('customer_2', 'customer_1')
2884 customer_2 -22.458734889653172
resNode: customer_1 deliver_cap: 50.53713224504148 cap_limit: 40
5983 customer_2 ('customer_2', 'depot_t')
2884 customer_2 -22.458734889653172
resNode: depot_t deliver_cap: 35.01876381916469 cap_limit: 40
5984 customer_2 ('customer_2', 'customer_4')
2884 customer_2 -22.458734889653172
resNode: customer_4 deliver_cap: 62.95194509841289 cap_limit: 40
5985 customer_2 ('customer_2', 'customer_5')
2884 customer_2 -22.458734889653172
resNode: customer_5 deliver_cap: 48.0461566014789 cap_limit: 40
5986 customer_1 ('customer_1', 'customer_3')
2902 customer_1 -14.821233453263073
resNode: customer_3 deliver_cap: 61.66762757589108 cap_limit: 40
5987 customer_1 ('customer_1', 'depot_t')
2902 customer_1 -14.821233453263073
resNode: depot_t deliver_cap: 36.157371901277415 cap_limit: 40
5988 customer_1 ('customer_1', 'customer_2')
2902 customer_1 -14.821233453263073
resNode: customer_2 deliver_cap: 40.17485766808601 cap_limit: 40
5989 customer_1 ('customer_1', 'customer_4')
2902 customer_1 -14.821233453263073
resNode: customer_4 deliver_cap: 61.266927468937105 cap_limit: 40
5990 customer_1 ('customer_1', 'customer_5')
2902 customer_1 -14.821233453263073
resNode: customer_5 deliver_cap: 52.389326019947845 cap_limit: 40
5991 customer_5 ('customer_5', 'customer_3')
2905 customer_5 -24.188981783324586
resNode: customer_3 deliver_cap: 65.22878566524759 cap_limit: 40
5992 customer_5 ('customer_5', 'customer_1')
2905 customer_5 -24.188981783324586
resNode: customer_1 deliver_cap: 53.770483949811094 cap_limit: 40
5993 customer_5 ('customer_5', 'depot_t')
2905 customer_5 -24.188981783324586
resNode: depot_t deliver_cap: 37.59478611892794 cap_limit: 40
5994 customer_5 ('customer_5', 'customer_2')
2905 customer_5 -24.188981783324586
resNode: customer_2 deliver_cap: 42.108842892035184 cap_limit: 40
5995 customer_5 ('customer_5', 'customer_4')
2905 customer_5 -24.188981783324586
resNode: customer_4 deliver_cap: 65.03216998883792 cap_limit: 40
5996 customer_2 ('customer_2', 'customer_3')
2909 customer_2 -24.121071277326813
resNode: customer_3 deliver_cap: 67.12807056530824 cap_limit: 40
5997 customer_2 ('customer_2', 'customer_1')
2909 customer_2 -24.121071277326813
resNode: customer_1 deliver_cap: 53.770483949811094 cap_limit: 40
5998 customer_2 ('customer_2', 'depot_t')
2909 customer_2 -24.121071277326813
resNode: depot_t deliver_cap: 38.00339616202894 cap_limit: 40
5999 customer_2 ('customer_2', 'customer_4')
2909 customer_2 -24.121071277326813
resNode: customer_4 deliver_cap: 66.93145488889857 cap_limit: 40
6000 customer_2 ('customer_2', 'customer_5')
2909 customer_2 -24.121071277326813
resNode: customer_5 deliver_cap: 52.02566639196457 cap_limit: 40
6001 customer_2 ('customer_2', 'customer_3')
2918 customer_2 -20.651579335034175
resNode: customer_3 deliver_cap: 67.12807056530824 cap_limit: 40
6002 customer_2 ('customer_2', 'customer_1')
2918 customer_2 -20.651579335034175
resNode: customer_1 deliver_cap: 53.770483949811094 cap_limit: 40
6003 customer_2 ('customer_2', 'depot_t')
2918 customer_2 -20.651579335034175
resNode: depot_t deliver_cap: 38.00339616202895 cap_limit: 40
6004 customer_2 ('customer_2', 'customer_4')
2918 customer_2 -20.651579335034175
resNode: customer_4 deliver_cap: 66.93145488889857 cap_limit: 40
6005 customer_2 ('customer_2', 'customer_5')
2918 customer_2 -20.651579335034175
resNode: customer_5 deliver_cap: 52.02566639196458 cap_limit: 40
6006 customer_1 ('customer_1', 'customer_3')
2922 customer_1 -20.043298345924384
resNode: customer_3 deliver_cap: 63.445114460817805 cap_limit: 40
6007 customer_1 ('customer_1', 'depot_t')
2922 customer_1 -20.043298345924384
resNode: depot_t deliver_cap: 38.86970113110941 cap_limit: 40
6008 customer_1 ('customer_1', 'customer_2')
2922 customer_1 -20.043298345924384
resNode: customer_2 deliver_cap: 42.10884289203519 cap_limit: 40
6009 customer_1 ('customer_1', 'customer_4')
2922 customer_1 -20.043298345924384
resNode: customer_4 deliver_cap: 62.95194509841291 cap_limit: 40
6010 customer_1 ('customer_1', 'customer_5')
2922 customer_1 -20.043298345924384
resNode: customer_5 deliver_cap: 52.025666391964585 cap_limit: 40
6011 customer_5 ('customer_5', 'customer_3')
2925 customer_5 -25.828816461251883
resNode: customer_3 deliver_cap: 62.67064686570797 cap_limit: 40
6012 customer_5 ('customer_5', 'customer_1')
2925 customer_5 -25.828816461251883
resNode: customer_1 deliver_cap: 53.72555307487319 cap_limit: 40
6013 customer_5 ('customer_5', 'depot_t')
2925 customer_5 -25.828816461251883
resNode: depot_t deliver_cap: 35.31832256041767 cap_limit: 40
6014 customer_5 ('customer_5', 'customer_2')
2925 customer_5 -25.828816461251883
resNode: customer_2 deliver_cap: 39.37276408068746 cap_limit: 40
6015 customer_5 ('customer_5', 'customer_4')
2925 customer_5 -25.828816461251883
resNode: customer_4 deliver_cap: 62.4371657499715 cap_limit: 40
6016 customer_2 ('customer_2', 'customer_3')
2933 customer_2 -19.294463255723233
resNode: customer_3 deliver_cap: 65.22878566524759 cap_limit: 40
6017 customer_2 ('customer_2', 'customer_1')
2933 customer_2 -19.294463255723233
resNode: customer_1 deliver_cap: 52.22731496851182 cap_limit: 40
6018 customer_2 ('customer_2', 'depot_t')
2933 customer_2 -19.294463255723233
resNode: depot_t deliver_cap: 36.578932486983454 cap_limit: 40
6019 customer_2 ('customer_2', 'customer_4')

resNode: customer_2 deliver_cap: 33.231241443045924 cap_limit: 40
6090 customer_5 ('customer_5', 'customer_4')
3035 customer_5 -19.685554956354995
resNode: customer_4 deliver_cap: 54.10589128238959 cap_limit: 40
6091 customer_2 ('customer_2', 'customer_3')
3039 customer_2 -20.023716762408696
resNode: customer_3 deliver_cap: 67.12807056530824 cap_limit: 40
6092 customer_2 ('customer_2', 'customer_1')
3039 customer_2 -20.023716762408696
resNode: customer_1 deliver_cap: 53.770483949811094 cap_limit: 40
6093 customer_2 ('customer_2', 'depot_t')
3039 customer_2 -20.023716762408696
resNode: depot_t deliver_cap: 38.00339616202895 cap_limit: 40
6094 customer_2 ('customer_2', 'customer_4')
3039 customer_2 -20.023716762408696
resNode: customer_4 deliver_cap: 66.93145488889857 cap_limit: 40
6095 customer_2 ('customer_2', 'customer_5')
3039 customer_2 -20.023716762408696
resNode: customer_5 deliver_cap: 52.02566639196458 cap_limit: 40
6096 customer_2 ('customer_2', 'customer_3')
3044 customer_2 -19.617644450357222
resNode: customer_3 deliver_cap: 56.20179185885991 cap_limit: 40
6097 customer_2 ('customer_2', 'customer_1')
3044 customer_2 -19.617644450357222
resNode: customer_1 deliver_cap: 44.892882500821834 cap_limit: 40
6098 customer_2 ('customer_2', 'depot_t')
3044 customer_2 -19.617644450357222
resNode: depot_t deliver_cap: 29.80868713219271 cap_limit: 40
6099 customer_2 ('customer_2', 'customer_4')
3044 customer_2 -19.617644450357222
resNode: customer_4 deliver_cap: 56.005176182450256 cap_limit: 40
6100 customer_2 ('customer_2', 'customer_5')
3044 customer_2 -19.617644450357222
resNode: customer_5 deliver_cap: 41.099387685516255 cap_limit: 40
6101 customer_2 ('customer_2', 'customer_3')
3053 customer_2 -18.231994686890495
resNode: customer_3 deliver_cap: 67.12807056530824 cap_limit: 40
6102 customer_2 ('customer_2', 'customer_1')
3053 customer_2 -18.231994686890495
resNode: customer_1 deliver_cap: 53.770483949811094 cap_limit: 40
6103 customer_2 ('customer_2', 'depot_t')
3053 customer_2 -18.231994686890495
resNode: depot_t deliver_cap: 38.00339616202895 cap_limit: 40
6104 customer_2 ('customer_2', 'customer_4')
3053 customer_2 -18.231994686890495
resNode: customer_4 deliver_cap: 66.93145488889857 cap_limit: 40
6105 customer_2 ('customer_2', 'customer_5')
3053 customer_2 -18.231994686890495
resNode: customer_5 deliver_cap: 52.02566639196458 cap_limit: 40
6106 customer_5 ('customer_5', 'customer_3')
3060 customer_5 -25.585526229780058
resNode: customer_3 deliver_cap: 67.39631474190972 cap_limit: 40
6107 customer_5 ('customer_5', 'customer_1')
3060 customer_5 -25.585526229780058
resNode: customer_1 deliver_cap: 57.70506286535887 cap_limit: 40
6108 customer_5 ('customer_5', 'depot_t')
3060 customer_5 -25.585526229780058
resNode: depot_t deliver_cap: 39.04911298899799 cap_limit: 40
6109 customer_5 ('customer_5', 'customer_2')
3060 customer_5 -25.585526229780058
resNode: customer_2 deliver_cap: 43.35227387117314 cap_limit: 40
6110 customer_5 ('customer_5', 'customer_4')
3060 customer_5 -25.585526229780058
resNode: customer_4 deliver_cap: 67.16283362617324 cap_limit: 40
6111 customer_2 ('customer_2', 'customer_3')
3064 customer_2 -24.504482421755426
resNode: customer_3 deliver_cap: 67.3963147419097 cap_limit: 40
6112 customer_2 ('customer_2', 'customer_1')
3064 customer_2 -24.504482421755426
resNode: customer_1 deliver_cap: 55.80577796529821 cap_limit: 40
6113 customer_2 ('customer_2', 'depot_t')
3064 customer_2 -24.504482421755426
resNode: depot_t deliver_cap: 37.77929594906738 cap_limit: 40
6114 customer_2 ('customer_2', 'customer_4')
3064 customer_2 -24.504482421755426
resNode: customer_4 deliver_cap: 67.16283362617324 cap_limit: 40
6115 customer_2 ('customer_2', 'customer_5')
3064 customer_2 -24.504482421755426
resNode: customer_5 deliver_cap: 49.462209786064115 cap_limit: 40
6116 customer_2 ('customer_2', 'customer_3')
3068 customer_2 -20.820020936755242
resNode: customer_3 deliver_cap: 67.62979585764619 cap_limit: 40
6117 customer_2 ('customer_2', 'customer_1')
3068 customer_2 -20.820020936755242
resNode: customer_1 deliver_cap: 56.002393641707876 cap_limit: 40
6118 customer_2 ('customer_2', 'depot_t')
3068 customer_2 -20.820020936755242
resNode: depot_t deliver_cap: 37.96362314570144 cap_limit: 40
6119 customer_2 ('customer_2', 'customer_4')
3068 customer_2 -20.820020936755242
resNode: customer_4 deliver_cap: 67.39631474190972 cap_limit: 40
6120 customer_2 ('customer_2', 'customer_5')
3068 customer_2 -20.820020936755242
resNode: customer_5 deliver_cap: 49.695690901800596 cap_limit: 40
6121 customer_2 ('customer_2', 'customer_3')
3073 customer_2 -16.148152508064584
resNode: customer_3 deliver_cap: 56.20179185885992 cap_limit: 40
6122 customer_2 ('customer_2', 'customer_1')
3073 customer_2 -16.148152508064584
resNode: customer_1 deliver_cap: 44.89288250082184 cap_limit: 40
6123 customer_2 ('customer_2', 'depot_t')
3073 customer_2 -16.148152508064584
resNode: depot_t deliver_cap: 29.808687132192713 cap_limit: 40
6124 customer_2 ('customer_2', 'customer_4')
3073 customer_2 -16.148152508064584
resNode: customer_4 deliver_cap: 56.005176182450256 cap_limit: 40
6125 customer_2 ('customer_2', 'customer_5')
3073 customer_2 -16.148152508064584
resNode: customer_5 deliver_cap: 41.09938768551626 cap_limit: 40
6126 customer_5 ('customer_5', 'customer_3')
3075 customer_5 -24.740803457121224
resNode: customer_3 deliver_cap: 65.36797829801877 cap_limit: 40
6127 customer_5 ('customer_5', 'customer_1')
3075 customer_5 -24.740803457121224
resNode: customer_1 deliver_cap: 55.996990070503344 cap_limit: 40
6128 customer_5 ('customer_5', 'depot_t')
3075 customer_5 -24.740803457121224
resNode: depot_t deliver_cap: 37.447794743820936 cap_limit: 40
6129 customer_5 ('customer_5', 'customer_2')
3075 customer_5 -24.740803457121224
resNode: customer_2 deliver_cap: 41.64420107631761 cap_limit: 40
6130 customer_5 ('customer_5', 'customer_4')
3075 customer_5 -24.740803457121224
resNode: customer_4 deliver_cap: 65.1344971822823 cap_limit: 40
6131 customer_3 ('customer_3', 'customer_1')
3076 customer_3 -20.9571644839459
resNode: customer_1 deliver_cap: 54.2187224372781 cap_limit: 40
6132 customer_3 ('customer_3', 'depot_t')
3076 customer_3 -20.9571644839459
resNode: depot_t deliver_cap: 39.233440185632055 cap_limit: 40
6133 customer_3 ('customer_3', 'customer_2')
3076 customer_3 -20.9571644839459
resNode: customer_2 deliver_cap: 43.5488895475828 cap_limit: 40
6134 customer_3 ('customer_3', 'customer_4')
3076 customer_3 -20.9571644839459
resNode: customer_4 deliver_cap: 54.43602435589645 cap_limit: 40
6135 customer_3 ('customer_3', 'customer_5')
3076 customer_3 -20.9571644839459
resNode: customer_5 deliver_cap: 49.6956909018006 cap_limit: 40
6136 customer_1 ('customer_1', 'customer_3')
3077 customer_1 -15.539871518954794
resNode: customer_3 deliver_cap: 52.51883575436948 cap_limit: 40
6137 customer_1 ('customer_1', 'depot_t')
3077 customer_1 -15.539871518954794
resNode: depot_t deliver_cap: 30.67499210127317 cap_limit: 40
6138 customer_1 ('customer_1', 'customer_2')
3077 customer_1 -15.539871518954794
resNode: customer_2 deliver_cap: 33.231241443045924 cap_limit: 40
6139 customer_1 ('customer_1', 'customer_4')
3077 customer_1 -15.539871518954794
resNode: customer_4 deliver_cap: 52.02566639196458 cap_limit: 40
6140 customer_1 ('customer_1', 'customer_5')
3077 customer_1 -15.539871518954794
resNode: customer_5 deliver_cap: 41.09938768551626 cap_limit: 40
6141 customer_4 ('customer_4', 'customer_3')
3079 customer_4 -20.92746732448819
resNode: customer_3 deliver_cap: 54.43602435589646 cap_limit: 40
6142 customer_4 ('customer_4', 'customer_1')
3079 customer_4 -20.92746732448819
resNode: customer_1 deliver_cap: 53.7255530748732 cap_limit: 40
6143 customer_4 ('customer_4', 'depot_t')
3079 customer_4 -20.92746732448819
resNode: depot_t deliver_cap: 39.049112988998 cap_limit: 40
6144 customer_4 ('customer_4', 'customer_2')
3079 customer_4 -20.92746732448819
resNode: customer_2 deliver_cap: 43.352273871173146 cap_limit: 40
6145 customer_4 ('customer_4', 'customer_5')
3079 customer_4 -20.92746732448819
resNode: customer_5 deliver_cap: 49.46220978606412 cap_limit: 40
6146 customer_5 ('customer_5', 'customer_3')
3080 customer_5 -18.764543062458472
resNode: customer_3 deliver_cap: 49.6956909018006 cap_limit: 40
6147 customer_5 ('customer_5', 'customer_1')
3080 customer_5 -18.764543062458472
resNode: customer_1 deliver_cap: 42.79927436842488 cap_limit: 40
6148 customer_5 ('customer_5', 'depot_t')
3080 customer_5 -18.764543062458472
resNode: depot_t deliver_cap: 25.074936273122383 cap_limit: 40
6149 customer_5 ('customer_5', 'customer_2')
3080 customer_5 -18.764543062458472
resNode: customer_2 deliver_cap: 28.446485374239156 cap_limit: 40
6150 customer_5 ('customer_5', 'customer_4')
3080 customer_5 -18.764543062458472
resNode: customer_4 deliver_cap: 49.46220978606412 cap_limit: 40
6151 customer_2 ('customer_2', 'customer_3')
3084 customer_2 -20.778035297521924
resNode: customer_3 deliver_cap: 67.39631474190972 cap_limit: 40
6152 customer_2 ('customer_2', 'customer_1')
3084 customer_2 -20.778035297521924
resNode: customer_1 deliver_cap: 55.80577796529822 cap_limit: 40
6153 customer_2 ('customer_2', 'depot_t')
3084 customer_2 -20.778035297521924
resNode: depot_t deliver_cap: 37.77929594906739 cap_limit: 40
6154 customer_2 ('customer_2', 'customer_4')
3084 customer_2 -20.778035297521924
resNode: customer_4 deliver_cap: 67.16283362617324 cap_limit: 40
6155 customer_2 ('customer_2', 'customer_5')
3084 customer_2 -20.778035297521924
resNode: customer_5 deliver_cap: 49.46220978606412 cap_limit: 40
6156 customer_2 ('customer_2', 'customer_3')
3098 customer_2 -19.050087198164704
resNode: customer_3 deliver_cap: 69.20829545573325 cap_limit: 40
6157 customer_2 ('customer_2', 'customer_1')
3098 customer_2 -19.050087198164704
resNode: customer_1 deliver_cap: 55.460666673281416 cap_limit: 40
6158 customer_2 ('customer_2', 'depot_t')
3098 customer_2 -19.050087198164704
resNode: depot_t deliver_cap: 39.56356482984771 cap_limit: 40
6159 customer_2 ('customer_2', 'customer_4')
3098 customer_2 -19.050087198164704
resNode: customer_4 deliver_cap: 69.01167977932359 cap_limit: 40
6160 customer_2 ('customer_2', 'customer_5')
3098 customer_2 -19.050087198164704
resNode: customer_5 deliver_cap: 54.10589128238959 cap_limit: 40
6161 customer_2 ('customer_2', 'customer_3')
3104 customer_2 -24.67250465477181
resNode: customer_3 deliver_cap: 67.3963147419097 cap_limit: 40
6162 customer_2 ('customer_2', 'customer_1')
3104 customer_2 -24.67250465477181
resNode: customer_1 deliver_cap: 55.805777965298205 cap_limit: 40
6163 customer_2 ('customer_2', 'depot_t')
3104 customer_2 -24.67250465477181
resNode: depot_t deliver_cap: 37.779295949067375 cap_limit: 40
6164 customer_2 ('customer_2', 'customer_4')
3104 customer_2 -24.67250465477181
resNode: customer_4 deliver_cap: 67.16283362617322 cap_limit: 40
6165 customer_2 ('customer_2', 'customer_5')
3104 customer_2 -24.67250465477181
resNode: customer_5 deliver_cap: 49.46220978606411 cap_limit: 40
6166 customer_2 ('customer_2', 'customer_3')
3128 customer_2 -16.446749352688606
resNode: customer_3 deliver_cap: 68.37085510687106 cap_limit: 40
6167 customer_2 ('customer_2', 'customer_1')
3128 customer_2 -16.446749352688606
resNode: customer_1 deliver_cap: 54.78024638983089 cap_limit: 40
6168 customer_2 ('customer_2', 'depot_t')
3128 customer_2 -16.446749352688606
resNode: depot_t deliver_cap: 38.93548456820107 cap_limit: 40
6169 customer_2 ('customer_2', 'customer_4')
3128 customer_2 -16.446749352688606
resNode: customer_4 deliver_cap: 68.1742394304614 cap_limit: 40
6170 customer_2 ('customer_2', 'customer_5')
3128 customer_2 -16.446749352688606
resNode: customer_5 deliver_cap: 53.268450933527404 cap_limit: 40
6171 customer_2 ('customer_2', 'customer_3')
3133 customer_2 -8.629088442804886
resNode: customer_3 deliver_cap: 53.39908845996764 cap_limit: 40
6172 customer_2 ('customer_2', 'customer_1')
3133 customer_2 -8.629088442804886
resNode: customer_1 deliver_cap: 40.483088519589074 cap_limit: 40
6173 customer_2 ('customer_2', 'depot_t')
3133 customer_2 -8.629088442804886
resNode: depot_t deliver_cap: 27.71160713159035 cap_limit: 40
6174 customer_2 ('customer_2', 'customer_4')
3133 customer_2 -8.629088442804886
resNode: customer_4 deliver_cap: 53.23933822288479 cap_limit: 40
6175 customer_2 ('customer_2', 'customer_5')
3133 customer_2 -8.629088442804886
resNode: customer_5 deliver_cap: 41.12838506912592 cap_limit: 40
6176 customer_5 ('customer_5', 'customer_3')
3135 customer_5 -19.443680843118273
resNode: customer_3 deliver_cap: 64.56688173554521 cap_limit: 40
6177 customer_5 ('customer_5', 'customer_1')
3135 customer_5 -19.443680843118273
resNode: customer_1 deliver_cap: 53.23268700692791 cap_limit: 40
6178 customer_5 ('customer_5', 'depot_t')
3135 customer_5 -19.443680843118273
resNode: depot_t deliver_cap: 37.09835817165116 cap_limit: 40
6179 customer_5 ('customer_5', 'customer_2')
3135 customer_5 -19.443680843118273
resNode: customer_2 deliver_cap: 41.571045949152 cap_limit: 40
6180 customer_5 ('customer_5', 'customer_4')
3135 customer_5 -19.443680843118273
resNode: customer_4 deliver_cap: 64.37026605913555 cap_limit: 40
6181 customer_2 ('customer_2', 'customer_3')
3139 customer_2 -16.413980073286993
resNode: customer_3 deliver_cap: 68.1742394304614 cap_limit: 40
6182 customer_2 ('customer_2', 'customer_1')
3139 customer_2 -16.413980073286993
resNode: customer_1 deliver_cap: 54.62049615274804 cap_limit: 40
6183 customer_2 ('customer_2', 'depot_t')
3139 customer_2 -16.413980073286993
resNode: depot_t deliver_cap: 38.78802281089382 cap_limit: 40
6184 customer_2 ('customer_2', 'customer_4')
3139 customer_2 -16.413980073286993
resNode: customer_4 deliver_cap: 67.97762375405173 cap_limit: 40
6185 customer_2 ('customer_2', 'customer_5')
3139 customer_2 -16.413980073286993
resNode: customer_5 deliver_cap: 53.07183525711774 cap_limit: 40
6186 customer_1 ('customer_1', 'customer_3')
3142 customer_1 -16.292917653871
resNode: customer_3 deliver_cap: 62.78321053111543 cap_limit: 40
6187 customer_1 ('customer_1', 'depot_t')
3142 customer_1 -16.292917653871
resNode: depot_t deliver_cap: 38.37327318383262 cap_limit: 40
6188 customer_1 ('customer_1', 'customer_2')
3142 customer_1 -16.292917653871
resNode: customer_2 deliver_cap: 41.57104594915201 cap_limit: 40
6189 customer_1 ('customer_1', 'customer_4')
3142 customer_1 -16.292917653871
resNode: customer_4 deliver_cap: 62.29004116871053 cap_limit: 40
6190 customer_1 ('customer_1', 'customer_5')
3142 customer_1 -16.292917653871
resNode: customer_5 deliver_cap: 51.36376246226221 cap_limit: 40
6191 customer_2 ('customer_2', 'customer_3')
3144 customer_2 -14.01815286599268
resNode: customer_3 deliver_cap: 53.268450933527404 cap_limit: 40
6192 customer_2 ('customer_2', 'customer_1')
3144 customer_2 -14.01815286599268
resNode: customer_1 deliver_cap: 42.50954299898917 cap_limit: 40
6193 customer_2 ('customer_2', 'depot_t')
3144 customer_2 -14.01815286599268
resNode: depot_t deliver_cap: 27.608681438193326 cap_limit: 40
6194 customer_2 ('customer_2', 'customer_4')
3144 customer_2 -14.01815286599268
resNode: customer_4 deliver_cap: 53.07183525711774 cap_limit: 40
6195 customer_2 ('customer_2', 'customer_5')
3144 customer_2 -14.01815286599268
resNode: customer_5 deliver_cap: 38.16604676018375 cap_limit: 40
6196 customer_2 ('customer_2', 'customer_3')
3163 customer_2 -16.731135626207767
resNode: customer_3 deliver_cap: 66.46616663560587 cap_limit: 40
6197 customer_2 ('customer_2', 'customer_1')
3163 customer_2 -16.731135626207767
resNode: customer_1 deliver_cap: 53.232687006927925 cap_limit: 40
6198 customer_2 ('customer_2', 'depot_t')
3163 customer_2 -16.731135626207767
resNode: depot_t deliver_cap: 37.50696821475217 cap_limit: 40
6199 customer_2 ('customer_2', 'customer_4')
3163 customer_2 -16.731135626207767
resNode: customer_4 deliver_cap: 66.26955095919621 cap_limit: 40
6200 customer_2 ('customer_2', 'customer_5')
3163 customer_2 -16.731135626207767
resNode: customer_5 deliver_cap: 51.36376246226221 cap_limit: 40
6201 customer_1 ('customer_1', 'customer_3')
3167 customer_1 -16.122854637097976
resNode: customer_3 deliver_cap: 62.78321053111544 cap_limit: 40
6202 customer_1 ('customer_1', 'depot_t')
3167 customer_1 -16.122854637097976
resNode: depot_t deliver_cap: 38.37327318383263 cap_limit: 40
6203 customer_1 ('customer_1', 'customer_2')
3167 customer_1 -16.122854637097976
resNode: customer_2 deliver_cap: 41.571045949152015 cap_limit: 40
6204 customer_1 ('customer_1', 'customer_4')
3167 customer_1 -16.122854637097976
resNode: customer_4 deliver_cap: 62.29004116871053 cap_limit: 40
6205 customer_1 ('customer_1', 'customer_5')
3167 customer_1 -16.122854637097976
resNode: customer_5 deliver_cap: 51.36376246226221 cap_limit: 40
6206 customer_5 ('customer_5', 'customer_3')
3170 customer_5 -21.753239018901482
resNode: customer_3 deliver_cap: 61.88463594918641 cap_limit: 40
6207 customer_5 ('customer_5', 'customer_1')
3170 customer_5 -21.753239018901482
resNode: customer_1 deliver_cap: 53.06364914517083 cap_limit: 40
6208 customer_5 ('customer_5', 'depot_t')
3170 customer_5 -21.753239018901482
resNode: depot_t deliver_cap: 34.6977876263217 cap_limit: 40
6209 customer_5 ('customer_5', 'customer_2')
3170 customer_5 -21.753239018901482
resNode: customer_2 deliver_cap: 38.71086015098509 cap_limit: 40
6210 customer_5 ('customer_5', 'customer_4')
3170 customer_5 -21.753239018901482
resNode: customer_4 deliver_cap: 61.651154833449944 cap_limit: 40
6211 customer_2 ('customer_2', 'customer_3')
3173 customer_2 -14.247224222503302
resNode: customer_3 deliver_cap: 68.37085510687108 cap_limit: 40
6212 customer_2 ('customer_2', 'customer_1')
3173 customer_2 -14.247224222503302
resNode: customer_1 deliver_cap: 54.78024638983089 cap_limit: 40
6213 customer_2 ('customer_2', 'depot_t')
3173 customer_2 -14.247224222503302
resNode: depot_t deliver_cap: 38.935484568201076 cap_limit: 40
6214 customer_2 ('customer_2', 'customer_4')
3173 customer_2 -14.247224222503302
resNode: customer_4 deliver_cap: 68.17423943046141 cap_limit: 40
6215 customer_2 ('customer_2', 'customer_5')
3173 customer_2 -14.247224222503302
resNode: customer_5 deliver_cap: 53.26845093352741 cap_limit: 40
6216 customer_5 ('customer_5', 'customer_3')
3180 customer_5 -21.72985559529301
resNode: customer_3 deliver_cap: 68.51996388289622 cap_limit: 40
6217 customer_5 ('customer_5', 'customer_1')
3180 customer_5 -21.72985559529301
resNode: customer_1 deliver_cap: 58.65129372092646 cap_limit: 40
6218 customer_5 ('customer_5', 'depot_t')
3180 customer_5 -21.72985559529301
resNode: depot_t deliver_cap: 39.93620441609261 cap_limit: 40
6219 customer_5 ('customer_5', 'customer_2')
3180 customer_5 -21.72985559529301
resNode: customer_2 deliver_cap: 44.298504726740724 cap_limit: 40
6220 customer_5 ('customer_5', 'customer_4')
3180 customer_5 -21.72985559529301
resNode: customer_4 deliver_cap: 68.28648276715975 cap_limit: 40
6221 customer_2 ('customer_2', 'customer_3')
3189 customer_2 -20.64881178726837
resNode: customer_3 deliver_cap: 68.51996388289622 cap_limit: 40
6222 customer_2 ('customer_2', 'customer_1')
3189 customer_2 -20.64881178726837
resNode: customer_1 deliver_cap: 56.752008820865804 cap_limit: 40
6223 customer_2 ('customer_2', 'depot_t')
3189 customer_2 -20.64881178726837
resNode: depot_t deliver_cap: 38.666387376162 cap_limit: 40
6224 customer_2 ('customer_2', 'customer_4')
3189 customer_2 -20.64881178726837
resNode: customer_4 deliver_cap: 68.28648276715975 cap_limit: 40
6225 customer_2 ('customer_2', 'customer_5')
3189 customer_2 -20.64881178726837
resNode: customer_5 deliver_cap: 50.58585892705063 cap_limit: 40
6226 customer_2 ('customer_2', 'customer_3')
3193 customer_2 -16.082261634370006
resNode: customer_3 deliver_cap: 68.37085510687106 cap_limit: 40
6227 customer_2 ('customer_2', 'customer_1')
3193 customer_2 -16.082261634370006

6281 customer_3 ('customer_3', 'customer_1')
3241 customer_3 -17.010354291123114
resNode: customer_1 deliver_cap: 54.96833761643603 cap_limit: 40
6282 customer_3 ('customer_3', 'depot_t')
3241 customer_3 -17.010354291123114
resNode: depot_t deliver_cap: 39.93620441609261 cap_limit: 40
6283 customer_3 ('customer_3', 'customer_2')
3241 customer_3 -17.010354291123114
resNode: customer_2 deliver_cap: 44.29850472674073 cap_limit: 40
6284 customer_3 ('customer_3', 'customer_4')
3241 customer_3 -17.010354291123114
resNode: customer_4 deliver_cap: 55.326192381146484 cap_limit: 40
6285 customer_3 ('customer_3', 'customer_5')
3241 customer_3 -17.010354291123114
resNode: customer_5 deliver_cap: 50.58585892705064 cap_limit: 40
6286 customer_1 ('customer_1', 'customer_3')
3242 customer_1 -11.417370268516873
resNode: customer_3 deliver_cap: 53.26845093352741 cap_limit: 40
6287 customer_1 ('customer_1', 'depot_t')
3242 customer_1 -11.417370268516873
resNode: depot_t deliver_cap: 31.237203485641615 cap_limit: 40
6288 customer_1 ('customer_1', 'customer_2')
3242 customer_1 -11.417370268516873
resNode: customer_2 deliver_cap: 33.840303776111746 cap_limit: 40
6289 customer_1 ('customer_1', 'customer_4')
3242 customer_1 -11.417370268516873
resNode: customer_4 deliver_cap: 52.775281571122505 cap_limit: 40
6290 customer_1 ('customer_1', 'customer_5')
3242 customer_1 -11.417370268516873
resNode: customer_5 deliver_cap: 41.84900286467419 cap_limit: 40
6291 customer_4 ('customer_4', 'customer_3')
3244 customer_4 -16.980657131665406
resNode: customer_3 deliver_cap: 55.326192381146484 cap_limit: 40
6292 customer_4 ('customer_4', 'customer_1')
3244 customer_4 -16.980657131665406
resNode: customer_1 deliver_cap: 54.475168254031125 cap_limit: 40
6293 customer_4 ('customer_4', 'depot_t')
3244 customer_4 -16.980657131665406
resNode: depot_t deliver_cap: 39.75187721945855 cap_limit: 40
6294 customer_4 ('customer_4', 'customer_2')
3244 customer_4 -16.980657131665406
resNode: customer_2 deliver_cap: 44.10188905033107 cap_limit: 40
6295 customer_4 ('customer_4', 'customer_5')
3244 customer_4 -16.980657131665406
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
6296 customer_5 ('customer_5', 'customer_3')
3245 customer_5 -14.817732869635693
resNode: customer_3 deliver_cap: 50.58585892705064 cap_limit: 40
6297 customer_5 ('customer_5', 'customer_1')
3245 customer_5 -14.817732869635693
resNode: customer_1 deliver_cap: 43.54888954758281 cap_limit: 40
6298 customer_5 ('customer_5', 'depot_t')
3245 customer_5 -14.817732869635693
resNode: depot_t deliver_cap: 25.77770050358294 cap_limit: 40
6299 customer_5 ('customer_5', 'customer_2')
3245 customer_5 -14.817732869635693
resNode: customer_2 deliver_cap: 29.196100553397084 cap_limit: 40
6300 customer_5 ('customer_5', 'customer_4')
3245 customer_5 -14.817732869635693
resNode: customer_4 deliver_cap: 50.35237781131416 cap_limit: 40
6301 customer_2 ('customer_2', 'customer_3')
3249 customer_2 -16.831225104699147
resNode: customer_3 deliver_cap: 68.28648276715975 cap_limit: 40
6302 customer_2 ('customer_2', 'customer_1')
3249 customer_2 -16.831225104699147
resNode: customer_1 deliver_cap: 56.55539314445615 cap_limit: 40
6303 customer_2 ('customer_2', 'depot_t')
3249 customer_2 -16.831225104699147
resNode: depot_t deliver_cap: 38.48206017952795 cap_limit: 40
6304 customer_2 ('customer_2', 'customer_4')
3249 customer_2 -16.831225104699147
resNode: customer_4 deliver_cap: 68.05300165142329 cap_limit: 40
6305 customer_2 ('customer_2', 'customer_5')
3249 customer_2 -16.831225104699147
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
6306 customer_2 ('customer_2', 'customer_3')
3253 customer_2 -9.626970156970204
resNode: customer_3 deliver_cap: 69.34338315429255 cap_limit: 40
6307 customer_2 ('customer_2', 'customer_1')
3253 customer_2 -9.626970156970204
resNode: customer_1 deliver_cap: 57.44541452309429 cap_limit: 40
6308 customer_2 ('customer_2', 'depot_t')
3253 customer_2 -9.626970156970204
resNode: depot_t deliver_cap: 39.31645522200121 cap_limit: 40
6309 customer_2 ('customer_2', 'customer_4')
3253 customer_2 -9.626970156970204
resNode: customer_4 deliver_cap: 69.10990203855609 cap_limit: 40
6310 customer_2 ('customer_2', 'customer_5')
3253 customer_2 -9.626970156970204
resNode: customer_5 deliver_cap: 51.40927819844696 cap_limit: 40
6311 customer_5 ('customer_5', 'customer_3')
3260 customer_5 -14.334718842989442
resNode: customer_3 deliver_cap: 65.62131816584983 cap_limit: 40
6312 customer_5 ('customer_5', 'customer_1')
3260 customer_5 -14.334718842989442
resNode: customer_1 deliver_cap: 57.801404008483345 cap_limit: 40
6313 customer_5 ('customer_5', 'depot_t')
3260 customer_5 -14.334718842989442
resNode: depot_t deliver_cap: 36.69996471341098 cap_limit: 40
6314 customer_5 ('customer_5', 'customer_2')
3260 customer_5 -14.334718842989442
resNode: customer_2 deliver_cap: 40.75746707788779 cap_limit: 40
6315 customer_5 ('customer_5', 'customer_4')
3260 customer_5 -14.334718842989442
resNode: customer_4 deliver_cap: 65.35097161078654 cap_limit: 40
6316 customer_2 ('customer_2', 'customer_3')
3264 customer_2 -10.503283868843516
resNode: customer_3 deliver_cap: 71.11012532322397 cap_limit: 40
6317 customer_2 ('customer_2', 'customer_1')
3264 customer_2 -10.503283868843516
resNode: customer_1 deliver_cap: 60.28633664375716 cap_limit: 40
6318 customer_2 ('customer_2', 'depot_t')
3264 customer_2 -10.503283868843516
resNode: depot_t deliver_cap: 39.667026485163994 cap_limit: 40
6319 customer_2 ('customer_2', 'customer_4')
3264 customer_2 -10.503283868843516
resNode: customer_4 deliver_cap: 70.83977876816067 cap_limit: 40
6320 customer_2 ('customer_2', 'customer_5')
3264 customer_2 -10.503283868843516
resNode: customer_5 deliver_cap: 50.34431958487643 cap_limit: 40
6321 customer_2 ('customer_2', 'customer_3')
3269 customer_2 -13.190184182968276
resNode: customer_3 deliver_cap: 65.62131816584983 cap_limit: 40
6322 customer_2 ('customer_2', 'customer_1')
3269 customer_2 -13.190184182968276
resNode: customer_1 deliver_cap: 55.546003189661306 cap_limit: 40
6323 customer_2 ('customer_2', 'depot_t')
3269 customer_2 -13.190184182968276
resNode: depot_t deliver_cap: 35.17618426549424 cap_limit: 40
6324 customer_2 ('customer_2', 'customer_4')
3269 customer_2 -13.190184182968276
resNode: customer_4 deliver_cap: 65.35097161078654 cap_limit: 40
6325 customer_2 ('customer_2', 'customer_5')
3269 customer_2 -13.190184182968276
resNode: customer_5 deliver_cap: 44.8555124275023 cap_limit: 40
6326 customer_1 ('customer_1', 'customer_3')
3272 customer_1 -9.713686329230107
resNode: customer_3 deliver_cap: 64.5792316958771 cap_limit: 40
6327 customer_1 ('customer_1', 'depot_t')
3272 customer_1 -9.713686329230107
resNode: depot_t deliver_cap: 39.720289057403875 cap_limit: 40
6328 customer_1 ('customer_1', 'customer_2')
3272 customer_1 -9.713686329230107
resNode: customer_2 deliver_cap: 43.030313145520864 cap_limit: 40
6329 customer_1 ('customer_1', 'customer_4')
3272 customer_1 -9.713686329230107
resNode: customer_4 deliver_cap: 64.0860623334722 cap_limit: 40
6330 customer_1 ('customer_1', 'customer_5')
3272 customer_1 -9.713686329230107
resNode: customer_5 deliver_cap: 53.15978362702388 cap_limit: 40
6331 customer_5 ('customer_5', 'customer_3')
3275 customer_5 -15.765013171524629
resNode: customer_3 deliver_cap: 64.01741108234089 cap_limit: 40
6332 customer_5 ('customer_5', 'customer_1')
3275 customer_5 -15.765013171524629
resNode: customer_1 deliver_cap: 54.85967030993248 cap_limit: 40
6333 customer_5 ('customer_5', 'depot_t')
3275 customer_5 -15.765013171524629
resNode: depot_t deliver_cap: 36.381557468285756 cap_limit: 40
6334 customer_5 ('customer_5', 'customer_2')
3275 customer_5 -15.765013171524629
resNode: customer_2 deliver_cap: 40.50688131574675 cap_limit: 40
6335 customer_5 ('customer_5', 'customer_4')
3275 customer_5 -15.765013171524629
resNode: customer_4 deliver_cap: 63.78392996660441 cap_limit: 40
6336 customer_2 ('customer_2', 'customer_3')
3279 customer_2 -15.722640793220672
resNode: customer_3 deliver_cap: 66.27281190116291 cap_limit: 40
6337 customer_2 ('customer_2', 'customer_1')
3279 customer_2 -15.722640793220672
resNode: customer_1 deliver_cap: 54.85967030993249 cap_limit: 40
6338 customer_2 ('customer_2', 'depot_t')
3279 customer_2 -15.722640793220672
resNode: depot_t deliver_cap: 36.89232002216202 cap_limit: 40
6339 customer_2 ('customer_2', 'customer_4')
3279 customer_2 -15.722640793220672
resNode: customer_4 deliver_cap: 66.03933078542644 cap_limit: 40
6340 customer_2 ('customer_2', 'customer_5')
3279 customer_2 -15.722640793220672
resNode: customer_5 deliver_cap: 48.33870694531732 cap_limit: 40
6341 customer_2 ('customer_2', 'customer_3')
3288 customer_2 -8.106380481404013
resNode: customer_3 deliver_cap: 59.043981888774745 cap_limit: 40
6342 customer_2 ('customer_2', 'customer_1')
3288 customer_2 -8.106380481404013
resNode: customer_1 deliver_cap: 47.202161900127635 cap_limit: 40
6343 customer_2 ('customer_2', 'depot_t')
3288 customer_2 -8.106380481404013
resNode: depot_t deliver_cap: 31.940329654628833 cap_limit: 40
6344 customer_2 ('customer_2', 'customer_4')
3288 customer_2 -8.106380481404013
resNode: customer_4 deliver_cap: 58.84736621236509 cap_limit: 40
6345 customer_2 ('customer_2', 'customer_5')
3288 customer_2 -8.106380481404013
resNode: customer_5 deliver_cap: 43.94157771543109 cap_limit: 40
6346 customer_2 ('customer_2', 'customer_3')
3299 customer_2 -11.346536945755227
resNode: customer_3 deliver_cap: 55.32619238114649 cap_limit: 40
6347 customer_2 ('customer_2', 'customer_1')
3299 customer_2 -11.346536945755227
resNode: customer_1 deliver_cap: 45.64146439833971 cap_limit: 40
6348 customer_2 ('customer_2', 'depot_t')
3299 customer_2 -11.346536945755227
resNode: depot_t deliver_cap: 28.25025198004379 cap_limit: 40
6349 customer_2 ('customer_2', 'customer_4')
3299 customer_2 -11.346536945755227
resNode: customer_4 deliver_cap: 55.092711265410024 cap_limit: 40
6350 customer_2 ('customer_2', 'customer_5')
3299 customer_2 -11.346536945755227
resNode: customer_5 deliver_cap: 37.39208742530091 cap_limit: 40
6351 customer_2 ('customer_2', 'customer_3')
3303 customer_2 -13.520785893530771
resNode: customer_3 deliver_cap: 68.74307895854263 cap_limit: 40
6352 customer_2 ('customer_2', 'customer_1')
3303 customer_2 -13.520785893530771
resNode: customer_1 deliver_cap: 56.939895200357505 cap_limit: 40
6353 customer_2 ('customer_2', 'depot_t')
3303 customer_2 -13.520785893530771
resNode: depot_t deliver_cap: 38.84253085693547 cap_limit: 40
6354 customer_2 ('customer_2', 'customer_4')
3303 customer_2 -13.520785893530771
resNode: customer_4 deliver_cap: 68.50959784280616 cap_limit: 40
6355 customer_2 ('customer_2', 'customer_5')
3303 customer_2 -13.520785893530771
resNode: customer_5 deliver_cap: 50.80897400269703 cap_limit: 40
6356 customer_1 ('customer_1', 'customer_3')
3307 customer_1 -12.966648964988511
resNode: customer_3 deliver_cap: 64.36956858446024 cap_limit: 40
6357 customer_1 ('customer_1', 'depot_t')
3307 customer_1 -12.966648964988511
resNode: depot_t deliver_cap: 39.925412068286036 cap_limit: 40
6358 customer_1 ('customer_1', 'customer_2')
3307 customer_1 -12.966648964988511
resNode: customer_2 deliver_cap: 42.587106206171775 cap_limit: 40
6359 customer_1 ('customer_1', 'customer_4')
3307 customer_1 -12.966648964988511
resNode: customer_4 deliver_cap: 63.78392996660441 cap_limit: 40
6360 customer_1 ('customer_1', 'customer_5')
3307 customer_1 -12.966648964988511
resNode: customer_5 deliver_cap: 50.80897400269703 cap_limit: 40
6361 customer_5 ('customer_5', 'customer_3')
3310 customer_5 -15.923298301242381
resNode: customer_3 deliver_cap: 59.862164453412404 cap_limit: 40
6362 customer_5 ('customer_5', 'customer_1')
3310 customer_5 -15.923298301242381
resNode: customer_1 deliver_cap: 52.82758943865101 cap_limit: 40
6363 customer_5 ('customer_5', 'depot_t')
3310 customer_5 -15.923298301242381
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
6364 customer_5 ('customer_5', 'customer_2')
3310 customer_5 -15.923298301242381
resNode: customer_2 deliver_cap: 35.78365250805547 cap_limit: 40
6365 customer_5 ('customer_5', 'customer_4')
3310 customer_5 -15.923298301242381
resNode: customer_4 deliver_cap: 59.59181789834911 cap_limit: 40
6366 customer_1 ('customer_1', 'customer_3')
3322 customer_1 -13.768157197573945
resNode: customer_3 deliver_cap: 64.56688173554521 cap_limit: 40
6367 customer_1 ('customer_1', 'depot_t')
3322 customer_1 -13.768157197573945
resNode: depot_t deliver_cap: 39.71102658715496 cap_limit: 40
6368 customer_1 ('customer_1', 'customer_2')
3322 customer_1 -13.768157197573945
resNode: customer_2 deliver_cap: 43.02027880275121 cap_limit: 40
6369 customer_1 ('customer_1', 'customer_4')
3322 customer_1 -13.768157197573945
resNode: customer_4 deliver_cap: 64.07371237314031 cap_limit: 40
6370 customer_1 ('customer_1', 'customer_5')
3322 customer_1 -13.768157197573945
resNode: customer_5 deliver_cap: 53.14743366669199 cap_limit: 40
6371 customer_5 ('customer_5', 'customer_3')
3325 customer_5 -19.816589517915677
resNode: customer_3 deliver_cap: 64.00274550444676 cap_limit: 40
6372 customer_5 ('customer_5', 'customer_1')
3325 customer_5 -19.816589517915677
resNode: customer_1 deliver_cap: 54.847320349600594 cap_limit: 40
6373 customer_5 ('customer_5', 'depot_t')
3325 customer_5 -19.816589517915677
resNode: depot_t deliver_cap: 36.36997938047461 cap_limit: 40
6374 customer_5 ('customer_5', 'customer_2')
3325 customer_5 -19.816589517915677
resNode: customer_2 deliver_cap: 40.494531355414864 cap_limit: 40
6375 customer_5 ('customer_5', 'customer_4')
3325 customer_5 -19.816589517915677
resNode: customer_4 deliver_cap: 63.76926438871029 cap_limit: 40
6376 customer_2 ('customer_2', 'customer_3')
3329 customer_2 -19.77421713961172
resNode: customer_3 deliver_cap: 66.2581463232688 cap_limit: 40
6377 customer_2 ('customer_2', 'customer_1')
3329 customer_2 -19.77421713961172
resNode: customer_1 deliver_cap: 54.8473203496006 cap_limit: 40
6378 customer_2 ('customer_2', 'depot_t')
3329 customer_2 -19.77421713961172
resNode: depot_t deliver_cap: 36.88074193435087 cap_limit: 40
6379 customer_2 ('customer_2', 'customer_4')
3329 customer_2 -19.77421713961172
resNode: customer_4 deliver_cap: 66.02466520753234 cap_limit: 40
6380 customer_2 ('customer_2', 'customer_5')
3329 customer_2 -19.77421713961172
resNode: customer_5 deliver_cap: 48.324041367423206 cap_limit: 40
6381 customer_2 ('customer_2', 'customer_3')
3333 customer_2 -16.109621195890476
resNode: customer_3 deliver_cap: 68.51996388289622 cap_limit: 40
6382 customer_2 ('customer_2', 'customer_1')
3333 customer_2 -16.109621195890476
resNode: customer_1 deliver_cap: 56.752008820865804 cap_limit: 40
6383 customer_2 ('customer_2', 'depot_t')
3333 customer_2 -16.109621195890476
resNode: depot_t deliver_cap: 38.666387376162 cap_limit: 40
6384 customer_2 ('customer_2', 'customer_4')
3333 customer_2 -16.109621195890476
resNode: customer_4 deliver_cap: 68.28648276715975 cap_limit: 40
6385 customer_2 ('customer_2', 'customer_5')
3333 customer_2 -16.109621195890476
resNode: customer_5 deliver_cap: 50.58585892705063 cap_limit: 40
6386 customer_2 ('customer_2', 'customer_3')
3338 customer_2 -10.66853517831572
resNode: customer_3 deliver_cap: 55.052122137957184 cap_limit: 40
6387 customer_2 ('customer_2', 'customer_1')
3338 customer_2 -10.66853517831572
resNode: customer_1 deliver_cap: 43.95877585258837 cap_limit: 40
6388 customer_2 ('customer_2', 'depot_t')
3338 customer_2 -10.66853517831572
resNode: depot_t deliver_cap: 28.94643484151566 cap_limit: 40
6389 customer_2 ('customer_2', 'customer_4')
3338 customer_2 -10.66853517831572
resNode: customer_4 deliver_cap: 54.85550646154752 cap_limit: 40
6390 customer_2 ('customer_2', 'customer_5')
3338 customer_2 -10.66853517831572
resNode: customer_5 deliver_cap: 39.94971796461353 cap_limit: 40
6391 customer_5 ('customer_5', 'customer_3')
3340 customer_5 -18.99173228653578
resNode: customer_3 deliver_cap: 64.00274550444678 cap_limit: 40
6392 customer_5 ('customer_5', 'customer_1')
3340 customer_5 -18.99173228653578
resNode: customer_1 deliver_cap: 54.84732034960061 cap_limit: 40
6393 customer_5 ('customer_5', 'depot_t')
3340 customer_5 -18.99173228653578
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
6394 customer_5 ('customer_5', 'customer_2')
3340 customer_5 -18.99173228653578
resNode: customer_2 deliver_cap: 40.49453135541487 cap_limit: 40
6395 customer_5 ('customer_5', 'customer_4')
3340 customer_5 -18.99173228653578
resNode: customer_4 deliver_cap: 63.76926438871031 cap_limit: 40
6396 customer_2 ('customer_2', 'customer_3')
3344 customer_2 -16.067635556657162
resNode: customer_3 deliver_cap: 68.28648276715975 cap_limit: 40
6397 customer_2 ('customer_2', 'customer_1')
3344 customer_2 -16.067635556657162
resNode: customer_1 deliver_cap: 56.55539314445615 cap_limit: 40
6398 customer_2 ('customer_2', 'depot_t')
3344 customer_2 -16.067635556657162
resNode: depot_t deliver_cap: 38.48206017952795 cap_limit: 40
6399 customer_2 ('customer_2', 'customer_4')
3344 customer_2 -16.067635556657162
resNode: customer_4 deliver_cap: 68.05300165142329 cap_limit: 40
6400 customer_2 ('customer_2', 'customer_5')
3344 customer_2 -16.067635556657162
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
6401 customer_1 ('customer_1', 'customer_3')
3347 customer_1 -15.920651285549845
resNode: customer_3 deliver_cap: 61.88463594918641 cap_limit: 40
6402 customer_1 ('customer_1', 'depot_t')
3347 customer_1 -15.920651285549845
resNode: depot_t deliver_cap: 37.96362314570145 cap_limit: 40
6403 customer_1 ('customer_1', 'customer_2')
3347 customer_1 -15.920651285549845
resNode: customer_2 deliver_cap: 40.49453135541487 cap_limit: 40
6404 customer_1 ('customer_1', 'customer_4')
3347 customer_1 -15.920651285549845
resNode: customer_4 deliver_cap: 61.29899733133058 cap_limit: 40
6405 customer_1 ('customer_1', 'customer_5')
3347 customer_1 -15.920651285549845
resNode: customer_5 deliver_cap: 48.32404136742321 cap_limit: 40
6406 customer_2 ('customer_2', 'customer_3')
3349 customer_2 -12.973099513569068
resNode: customer_3 deliver_cap: 50.58585892705064 cap_limit: 40
6407 customer_2 ('customer_2', 'customer_1')
3349 customer_2 -12.973099513569068
resNode: customer_1 deliver_cap: 41.649604647522146 cap_limit: 40
6408 customer_2 ('customer_2', 'depot_t')
3349 customer_2 -12.973099513569068
resNode: depot_t deliver_cap: 24.507883463652327 cap_limit: 40
6409 customer_2 ('customer_2', 'customer_4')
3349 customer_2 -12.973099513569068
resNode: customer_4 deliver_cap: 50.35237781131416 cap_limit: 40
6410 customer_2 ('customer_2', 'customer_5')
3349 customer_2 -12.973099513569068
resNode: customer_5 deliver_cap: 32.65175397120505 cap_limit: 40
6411 customer_1 ('customer_1', 'customer_3')
3367 customer_1 -11.682490918041442
resNode: customer_3 deliver_cap: 58.13742879810944 cap_limit: 40
6412 customer_1 ('customer_1', 'depot_t')
3367 customer_1 -11.682490918041442
resNode: depot_t deliver_cap: 33.71338813204396 cap_limit: 40
6413 customer_1 ('customer_1', 'customer_2')
3367 customer_1 -11.682490918041442
resNode: customer_2 deliver_cap: 37.45932014671551 cap_limit: 40
6414 customer_1 ('customer_1', 'customer_4')
3367 customer_1 -11.682490918041442
resNode: customer_4 deliver_cap: 57.73672869115546 cap_limit: 40
6415 customer_1 ('customer_1', 'customer_5')
3367 customer_1 -11.682490918041442
resNode: customer_5 deliver_cap: 48.859127242166196 cap_limit: 40
6416 customer_5 ('customer_5', 'customer_3')
3370 customer_5 -20.031912677589023
resNode: customer_3 deliver_cap: 60.88392563105478 cap_limit: 40
6417 customer_5 ('customer_5', 'customer_1')
3370 customer_5 -20.031912677589023
resNode: customer_1 deliver_cap: 50.24028517202944 cap_limit: 40
6418 customer_5 ('customer_5', 'depot_t')
3370 customer_5 -20.031912677589023
resNode: depot_t deliver_cap: 34.336141093283345 cap_limit: 40

resNode: customer_4 deliver_cap: 64.38261601946743 cap_limit: 40
6465 customer_2 ('customer_2', 'customer_5')
3408 customer_2 -13.442582540925772
resNode: customer_5 deliver_cap: 49.47682752253343 cap_limit: 40
6466 customer_1 ('customer_1', 'customer_3')
3412 customer_1 -14.077898361342754
resNode: customer_3 deliver_cap: 64.87578538187235 cap_limit: 40
6467 customer_1 ('customer_1', 'depot_t')
3412 customer_1 -14.077898361342754
resNode: depot_t deliver_cap: 39.94270432190031 cap_limit: 40
6468 customer_1 ('customer_1', 'customer_2')
3412 customer_1 -14.077898361342754
resNode: customer_2 deliver_cap: 43.271263015392 cap_limit: 40
6469 customer_1 ('customer_1', 'customer_4')
3412 customer_1 -14.077898361342754
resNode: customer_4 deliver_cap: 64.38261601946743 cap_limit: 40
6470 customer_1 ('customer_1', 'customer_5')
3412 customer_1 -14.077898361342754
resNode: customer_5 deliver_cap: 53.45633731301911 cap_limit: 40
6471 customer_5 ('customer_5', 'customer_3')
3415 customer_5 -20.19872997379241
resNode: customer_3 deliver_cap: 64.36956858446024 cap_limit: 40
6472 customer_5 ('customer_5', 'customer_1')
3415 customer_5 -20.19872997379241
resNode: customer_1 deliver_cap: 55.15622399592773 cap_limit: 40
6473 customer_5 ('customer_5', 'depot_t')
3415 customer_5 -20.19872997379241
resNode: depot_t deliver_cap: 36.659576548906294 cap_limit: 40
6474 customer_5 ('customer_5', 'customer_2')
3415 customer_5 -20.19872997379241
resNode: customer_2 deliver_cap: 40.803435001741995 cap_limit: 40
6475 customer_5 ('customer_5', 'customer_4')
3415 customer_5 -20.19872997379241
resNode: customer_4 deliver_cap: 64.13608746872377 cap_limit: 40
6476 customer_2 ('customer_2', 'customer_3')
3419 customer_2 -19.117686165767775
resNode: customer_3 deliver_cap: 64.36956858446023 cap_limit: 40
6477 customer_2 ('customer_2', 'customer_1')
3419 customer_2 -19.117686165767775
resNode: customer_1 deliver_cap: 53.25693909586707 cap_limit: 40
6478 customer_2 ('customer_2', 'depot_t')
3419 customer_2 -19.117686165767775
resNode: depot_t deliver_cap: 35.389759508975686 cap_limit: 40
6479 customer_2 ('customer_2', 'customer_4')
3419 customer_2 -19.117686165767775
resNode: customer_4 deliver_cap: 64.13608746872376 cap_limit: 40
6480 customer_2 ('customer_2', 'customer_5')
3419 customer_2 -19.117686165767775
resNode: customer_5 deliver_cap: 46.435463628614635 cap_limit: 40
6481 customer_2 ('customer_2', 'customer_3')
3423 customer_2 -17.49782528179035
resNode: customer_3 deliver_cap: 64.56688173554521 cap_limit: 40
6482 customer_2 ('customer_2', 'customer_1')
3423 customer_2 -17.49782528179035
resNode: customer_1 deliver_cap: 51.68951802562864 cap_limit: 40
6483 customer_2 ('customer_2', 'depot_t')
3423 customer_2 -17.49782528179035
resNode: depot_t deliver_cap: 36.082504539706676 cap_limit: 40
6484 customer_2 ('customer_2', 'customer_4')
3423 customer_2 -17.49782528179035
resNode: customer_4 deliver_cap: 64.37026605913555 cap_limit: 40
6485 customer_2 ('customer_2', 'customer_5')
3423 customer_2 -17.49782528179035
resNode: customer_5 deliver_cap: 49.46447756220155 cap_limit: 40
6486 customer_1 ('customer_1', 'customer_3')
3427 customer_1 -16.88954429268056
resNode: customer_3 deliver_cap: 60.88392563105478 cap_limit: 40
6487 customer_1 ('customer_1', 'depot_t')
3427 customer_1 -16.88954429268056
resNode: depot_t deliver_cap: 36.948809508787136 cap_limit: 40
6488 customer_1 ('customer_1', 'customer_2')
3427 customer_1 -16.88954429268056
resNode: customer_2 deliver_cap: 40.027876967852734 cap_limit: 40
6489 customer_1 ('customer_1', 'customer_4')
3427 customer_1 -16.88954429268056
resNode: customer_4 deliver_cap: 60.39075626864988 cap_limit: 40
6490 customer_1 ('customer_1', 'customer_5')
3427 customer_1 -16.88954429268056
resNode: customer_5 deliver_cap: 49.46447756220156 cap_limit: 40
6491 customer_5 ('customer_5', 'customer_3')
3430 customer_5 -22.074783776032355
resNode: customer_3 deliver_cap: 59.62923513036439 cap_limit: 40
6492 customer_5 ('customer_5', 'customer_1')
3430 customer_5 -22.074783776032355
resNode: customer_1 deliver_cap: 51.16436424511018 cap_limit: 40
6493 customer_5 ('customer_5', 'depot_t')
3430 customer_5 -22.074783776032355
resNode: depot_t deliver_cap: 32.91720803251484 cap_limit: 40
6494 customer_5 ('customer_5', 'customer_2')
3430 customer_5 -22.074783776032355
resNode: customer_2 deliver_cap: 36.81157525092444 cap_limit: 40
6495 customer_5 ('customer_5', 'customer_4')
3430 customer_5 -22.074783776032355
resNode: customer_4 deliver_cap: 59.395754014627926 cap_limit: 40
6496 customer_2 ('customer_2', 'customer_3')
3433 customer_2 -10.841212393263906
resNode: customer_3 deliver_cap: 53.39908845996764 cap_limit: 40
6497 customer_2 ('customer_2', 'customer_1')
3433 customer_2 -10.841212393263906
resNode: customer_1 deliver_cap: 40.483088519589074 cap_limit: 40
6498 customer_2 ('customer_2', 'depot_t')
3433 customer_2 -10.841212393263906
resNode: depot_t deliver_cap: 27.711607131590352 cap_limit: 40
6499 customer_2 ('customer_2', 'customer_4')
3433 customer_2 -10.841212393263906
resNode: customer_4 deliver_cap: 53.23933822288479 cap_limit: 40
6500 customer_2 ('customer_2', 'customer_5')
3433 customer_2 -10.841212393263906
resNode: customer_5 deliver_cap: 41.12838506912592 cap_limit: 40
6501 customer_5 ('customer_5', 'customer_3')
3435 customer_5 -21.655804793577296
resNode: customer_3 deliver_cap: 64.56688173554522 cap_limit: 40
6502 customer_5 ('customer_5', 'customer_1')
3435 customer_5 -21.655804793577296
resNode: customer_1 deliver_cap: 53.232687006927925 cap_limit: 40
6503 customer_5 ('customer_5', 'depot_t')
3435 customer_5 -21.655804793577296
resNode: depot_t deliver_cap: 37.09835817165117 cap_limit: 40
6504 customer_5 ('customer_5', 'customer_2')
3435 customer_5 -21.655804793577296
resNode: customer_2 deliver_cap: 41.571045949152015 cap_limit: 40
6505 customer_5 ('customer_5', 'customer_4')
3435 customer_5 -21.655804793577296
resNode: customer_4 deliver_cap: 64.37026605913556 cap_limit: 40
6506 customer_1 ('customer_1', 'customer_3')
3437 customer_1 -11.157072558841858
resNode: customer_3 deliver_cap: 53.39908845996764 cap_limit: 40
6507 customer_1 ('customer_1', 'depot_t')
3437 customer_1 -11.157072558841858
resNode: depot_t deliver_cap: 30.432998667176562 cap_limit: 40
6508 customer_1 ('customer_1', 'customer_2')
3437 customer_1 -11.157072558841858
resNode: customer_2 deliver_cap: 33.814442963529515 cap_limit: 40
6509 customer_1 ('customer_1', 'customer_4')
3437 customer_1 -11.157072558841858
resNode: customer_4 deliver_cap: 52.99838835301367 cap_limit: 40
6510 customer_1 ('customer_1', 'customer_5')
3437 customer_1 -11.157072558841858
resNode: customer_5 deliver_cap: 44.1207869040244 cap_limit: 40
6511 customer_5 ('customer_5', 'customer_3')
3440 customer_5 -18.13966537469469
resNode: customer_3 deliver_cap: 55.052122137957184 cap_limit: 40
6512 customer_5 ('customer_5', 'customer_1')
3440 customer_5 -18.13966537469469
resNode: customer_1 deliver_cap: 45.50194483388764 cap_limit: 40
6513 customer_5 ('customer_5', 'depot_t')
3440 customer_5 -18.13966537469469
resNode: depot_t deliver_cap: 29.962288473460145 cap_limit: 40
6514 customer_5 ('customer_5', 'customer_2')
3440 customer_5 -18.13966537469469
resNode: customer_2 deliver_cap: 33.84030377611174 cap_limit: 40
6515 customer_5 ('customer_5', 'customer_4')
3440 customer_5 -18.13966537469469
resNode: customer_4 deliver_cap: 54.85550646154752 cap_limit: 40
6516 customer_1 ('customer_1', 'customer_3')
3442 customer_1 -15.340862593159581
resNode: customer_3 deliver_cap: 64.5792316958771 cap_limit: 40
6517 customer_1 ('customer_1', 'depot_t')
3442 customer_1 -15.340862593159581
resNode: depot_t deliver_cap: 39.72028905740387 cap_limit: 40
6518 customer_1 ('customer_1', 'customer_2')
3442 customer_1 -15.340862593159581
resNode: customer_2 deliver_cap: 43.03031314552086 cap_limit: 40
6519 customer_1 ('customer_1', 'customer_4')
3442 customer_1 -15.340862593159581
resNode: customer_4 deliver_cap: 64.08606233347219 cap_limit: 40
6520 customer_1 ('customer_1', 'customer_5')
3442 customer_1 -15.340862593159581
resNode: customer_5 deliver_cap: 53.15978362702386 cap_limit: 40
6521 customer_2 ('customer_2', 'customer_3')
3444 customer_2 -14.060975252902681
resNode: customer_3 deliver_cap: 59.043981888774745 cap_limit: 40
6522 customer_2 ('customer_2', 'customer_1')
3444 customer_2 -14.060975252902681
resNode: customer_1 deliver_cap: 47.202161900127635 cap_limit: 40
6523 customer_2 ('customer_2', 'depot_t')
3444 customer_2 -14.060975252902681
resNode: depot_t deliver_cap: 31.940329654628833 cap_limit: 40
6524 customer_2 ('customer_2', 'customer_4')
3444 customer_2 -14.060975252902681
resNode: customer_4 deliver_cap: 58.84736621236509 cap_limit: 40
6525 customer_2 ('customer_2', 'customer_5')
3444 customer_2 -14.060975252902681
resNode: customer_5 deliver_cap: 43.94157771543109 cap_limit: 40
6526 customer_5 ('customer_5', 'customer_3')
3445 customer_5 -22.39979836675372
resNode: customer_3 deliver_cap: 66.48767813972059 cap_limit: 40
6527 customer_5 ('customer_5', 'customer_1')
3445 customer_5 -22.39979836675372
resNode: customer_1 deliver_cap: 56.9398952003575 cap_limit: 40
6528 customer_5 ('customer_5', 'depot_t')
3445 customer_5 -22.39979836675372
resNode: depot_t deliver_cap: 38.33176830305921 cap_limit: 40
6529 customer_5 ('customer_5', 'customer_2')
3445 customer_5 -22.39979836675372
resNode: customer_2 deliver_cap: 42.58710620617177 cap_limit: 40
6530 customer_5 ('customer_5', 'customer_4')
3445 customer_5 -22.39979836675372
resNode: customer_4 deliver_cap: 66.25419702398412 cap_limit: 40
6531 customer_1 ('customer_1', 'customer_3')
3447 customer_1 -19.396877206544907
resNode: customer_3 deliver_cap: 64.56688173554521 cap_limit: 40
6532 customer_1 ('customer_1', 'depot_t')
3447 customer_1 -19.396877206544907
resNode: depot_t deliver_cap: 39.71102658715496 cap_limit: 40
6533 customer_1 ('customer_1', 'customer_2')
3447 customer_1 -19.396877206544907
resNode: customer_2 deliver_cap: 43.02027880275121 cap_limit: 40
6534 customer_1 ('customer_1', 'customer_4')
3447 customer_1 -19.396877206544907
resNode: customer_4 deliver_cap: 64.07371237314031 cap_limit: 40
6535 customer_1 ('customer_1', 'customer_5')
3447 customer_1 -19.396877206544907
resNode: customer_5 deliver_cap: 53.14743366669199 cap_limit: 40
6536 customer_2 ('customer_2', 'customer_3')
3449 customer_2 -17.122112418666585
resNode: customer_3 deliver_cap: 55.052122137957184 cap_limit: 40
6537 customer_2 ('customer_2', 'customer_1')
3449 customer_2 -17.122112418666585
resNode: customer_1 deliver_cap: 43.95877585258837 cap_limit: 40
6538 customer_2 ('customer_2', 'depot_t')
3449 customer_2 -17.122112418666585
resNode: depot_t deliver_cap: 28.94643484151566 cap_limit: 40
6539 customer_2 ('customer_2', 'customer_4')
3449 customer_2 -17.122112418666585
resNode: customer_4 deliver_cap: 54.85550646154752 cap_limit: 40
6540 customer_2 ('customer_2', 'customer_5')
3449 customer_2 -17.122112418666585
resNode: customer_5 deliver_cap: 39.94971796461353 cap_limit: 40
6541 customer_1 ('customer_1', 'customer_3')
3451 customer_1 -13.530127150181855
resNode: customer_3 deliver_cap: 58.13742879810944 cap_limit: 40
6542 customer_1 ('customer_1', 'depot_t')
3451 customer_1 -13.530127150181855
resNode: depot_t deliver_cap: 33.71338813204395 cap_limit: 40
6543 customer_1 ('customer_1', 'customer_2')
3451 customer_1 -13.530127150181855
resNode: customer_2 deliver_cap: 37.459320146715505 cap_limit: 40
6544 customer_1 ('customer_1', 'customer_4')
3451 customer_1 -13.530127150181855
resNode: customer_4 deliver_cap: 57.73672869115545 cap_limit: 40
6545 customer_1 ('customer_1', 'customer_5')
3451 customer_1 -13.530127150181855
resNode: customer_5 deliver_cap: 48.85912724216619 cap_limit: 40
6546 customer_2 ('customer_2', 'customer_3')
3453 customer_2 -12.676249805130606
resNode: customer_3 deliver_cap: 53.39908845996764 cap_limit: 40
6547 customer_2 ('customer_2', 'customer_1')
3453 customer_2 -12.676249805130606
resNode: customer_1 deliver_cap: 40.483088519589074 cap_limit: 40
6548 customer_2 ('customer_2', 'depot_t')
3453 customer_2 -12.676249805130606
resNode: depot_t deliver_cap: 27.71160713159035 cap_limit: 40
6549 customer_2 ('customer_2', 'customer_4')
3453 customer_2 -12.676249805130606
resNode: customer_4 deliver_cap: 53.23933822288479 cap_limit: 40
6550 customer_2 ('customer_2', 'customer_5')
3453 customer_2 -12.676249805130606
resNode: customer_5 deliver_cap: 41.12838506912592 cap_limit: 40
6551 customer_4 ('customer_4', 'customer_3')
3454 customer_4 -19.349276661477457
resNode: customer_3 deliver_cap: 55.74552784018567 cap_limit: 40
6552 customer_4 ('customer_4', 'customer_1')
3454 customer_4 -19.349276661477457
resNode: customer_1 deliver_cap: 51.69955236839829 cap_limit: 40
6553 customer_4 ('customer_4', 'depot_t')
3454 customer_4 -19.349276661477457
resNode: depot_t deliver_cap: 38.66778930971884 cap_limit: 40
6554 customer_4 ('customer_4', 'customer_2')
3454 customer_4 -19.349276661477457
resNode: customer_2 deliver_cap: 43.271263015391995 cap_limit: 40
6555 customer_4 ('customer_4', 'customer_5')
3454 customer_4 -19.349276661477457
resNode: customer_5 deliver_cap: 51.557052412958456 cap_limit: 40
6556 customer_5 ('customer_5', 'customer_3')
3455 customer_5 -22.659905061667462
resNode: customer_3 deliver_cap: 62.66759683548455 cap_limit: 40
6557 customer_5 ('customer_5', 'customer_1')
3455 customer_5 -22.659905061667462
resNode: customer_1 deliver_cap: 51.68951802562864 cap_limit: 40
6558 customer_5 ('customer_5', 'depot_t')
3455 customer_5 -22.659905061667462
resNode: depot_t deliver_cap: 35.67389449660567 cap_limit: 40
6559 customer_5 ('customer_5', 'customer_2')
3455 customer_5 -22.659905061667462
resNode: customer_2 deliver_cap: 40.02787696785273 cap_limit: 40
6560 customer_5 ('customer_5', 'customer_4')
3455 customer_5 -22.659905061667462
resNode: customer_4 deliver_cap: 62.470981159074896 cap_limit: 40
6561 customer_3 ('customer_3', 'customer_1')
3456 customer_3 -13.494637662835446
resNode: customer_1 deliver_cap: 40.483088519589074 cap_limit: 40
6562 customer_3 ('customer_3', 'depot_t')
3456 customer_3 -13.494637662835446
resNode: depot_t deliver_cap: 29.476812408040463 cap_limit: 40
6563 customer_3 ('customer_3', 'customer_2')
3456 customer_3 -13.494637662835446
resNode: customer_2 deliver_cap: 33.81444296352951 cap_limit: 40
6564 customer_3 ('customer_3', 'customer_4')
3456 customer_3 -13.494637662835446
resNode: customer_4 deliver_cap: 45.82100397026438 cap_limit: 40
6565 customer_3 ('customer_3', 'customer_5')
3456 customer_3 -13.494637662835446
resNode: customer_5 deliver_cap: 42.57761792272511 cap_limit: 40
6566 customer_1 ('customer_1', 'customer_3')
3457 customer_1 -5.692669580139555
resNode: customer_3 deliver_cap: 39.42065934277119 cap_limit: 40
6567 customer_1 ('customer_1', 'depot_t')
3457 customer_1 -5.692669580139555
resNode: depot_t deliver_cap: 19.295328248410737 cap_limit: 40
6568 customer_1 ('customer_1', 'customer_2')
3457 customer_1 -5.692669580139555
resNode: customer_2 deliver_cap: 22.511216289812527 cap_limit: 40
6569 customer_1 ('customer_1', 'customer_4')
3457 customer_1 -5.692669580139555
resNode: customer_4 deliver_cap: 39.11242849126812 cap_limit: 40
6570 customer_1 ('customer_1', 'customer_5')
3457 customer_1 -5.692669580139555
resNode: customer_5 deliver_cap: 32.28350429973792 cap_limit: 40
6571 customer_4 ('customer_4', 'customer_3')
3459 customer_4 -13.483373223041145
resNode: customer_3 deliver_cap: 45.82100397026438 cap_limit: 40
6572 customer_4 ('customer_4', 'customer_1')
3459 customer_4 -13.483373223041145
resNode: customer_1 deliver_cap: 40.17485766808601 cap_limit: 40
6573 customer_4 ('customer_4', 'depot_t')
3459 customer_4 -13.483373223041145
resNode: depot_t deliver_cap: 29.36621609006003 cap_limit: 40
6574 customer_4 ('customer_4', 'customer_2')
3459 customer_4 -13.483373223041145
resNode: customer_2 deliver_cap: 33.69155816577347 cap_limit: 40
6575 customer_4 ('customer_4', 'customer_5')
3459 customer_4 -13.483373223041145
resNode: customer_5 deliver_cap: 42.417867685642264 cap_limit: 40
6576 customer_5 ('customer_5', 'customer_3')
3460 customer_5 -12.717866632598987
resNode: customer_3 deliver_cap: 42.57761792272511 cap_limit: 40
6577 customer_5 ('customer_5', 'customer_1')
3460 customer_5 -12.717866632598987
resNode: customer_1 deliver_cap: 33.34593347655581 cap_limit: 40
6578 customer_5 ('customer_5', 'depot_t')
3460 customer_5 -12.717866632598987
resNode: depot_t deliver_cap: 20.981710060534656 cap_limit: 40
6579 customer_5 ('customer_5', 'customer_2')
3460 customer_5 -12.717866632598987
resNode: customer_2 deliver_cap: 24.37544035518972 cap_limit: 40
6580 customer_5 ('customer_5', 'customer_4')
3460 customer_5 -12.717866632598987
resNode: customer_4 deliver_cap: 42.417867685642264 cap_limit: 40
6581 customer_3 ('customer_3', 'customer_1')
3461 customer_3 -19.096242083253316
resNode: customer_1 deliver_cap: 51.69955236839829 cap_limit: 40
6582 customer_3 ('customer_3', 'depot_t')
3461 customer_3 -19.096242083253316
resNode: depot_t deliver_cap: 38.44537404522241 cap_limit: 40
6583 customer_3 ('customer_3', 'customer_2')
3461 customer_3 -19.096242083253316
resNode: customer_2 deliver_cap: 43.03031314552085 cap_limit: 40
6584 customer_3 ('customer_3', 'customer_4')
3461 customer_3 -19.096242083253316
resNode: customer_4 deliver_cap: 55.25235847778076 cap_limit: 40
6585 customer_3 ('customer_3', 'customer_5')
3461 customer_3 -19.096242083253316
resNode: customer_5 deliver_cap: 51.260498726963206 cap_limit: 40
6586 customer_1 ('customer_1', 'customer_3')
3462 customer_1 -13.311960874177567
resNode: customer_3 deliver_cap: 57.49577882128432 cap_limit: 40
6587 customer_1 ('customer_1', 'depot_t')
3462 customer_1 -13.311960874177567
resNode: depot_t deliver_cap: 33.26916891731887 cap_limit: 40
6588 customer_1 ('customer_1', 'customer_2')
3462 customer_1 -13.311960874177567
resNode: customer_2 deliver_cap: 36.96574324146541 cap_limit: 40
6589 customer_1 ('customer_1', 'customer_4')
3462 customer_1 -13.311960874177567
resNode: customer_4 deliver_cap: 57.09507871433033 cap_limit: 40
6590 customer_1 ('customer_1', 'customer_5')
3462 customer_1 -13.311960874177567
resNode: customer_5 deliver_cap: 48.21747726534107 cap_limit: 40
6591 customer_2 ('customer_2', 'customer_3')
3464 customer_2 -12.518320996594106
resNode: customer_3 deliver_cap: 52.99838835301365 cap_limit: 40
6592 customer_2 ('customer_2', 'customer_1')
3464 customer_2 -12.518320996594106
resNode: customer_1 deliver_cap: 40.174857668086005 cap_limit: 40
6593 customer_2 ('customer_2', 'depot_t')
3464 customer_2 -12.518320996594106
resNode: depot_t deliver_cap: 27.43419936523759 cap_limit: 40
6594 customer_2 ('customer_2', 'customer_4')
3464 customer_2 -12.518320996594106
resNode: customer_4 deliver_cap: 52.8386381159308 cap_limit: 40
6595 customer_2 ('customer_2', 'customer_5')
3464 customer_2 -12.518320996594106
resNode: customer_5 deliver_cap: 40.72768496217193 cap_limit: 40
6596 customer_5 ('customer_5', 'customer_3')
3465 customer_5 -22.386389683817313
resNode: customer_3 deliver_cap: 62.174427473079646 cap_limit: 40
6597 customer_5 ('customer_5', 'customer_1')
3465 customer_5 -22.386389683817313
resNode: customer_1 deliver_cap: 51.288817918674646 cap_limit: 40
6598 customer_5 ('customer_5', 'depot_t')
3465 customer_5 -22.386389683817313
resNode: depot_t deliver_cap: 35.304017474801995 cap_limit: 40
6599 customer_5 ('customer_5', 'customer_2')
3465 customer_5 -22.386389683817313
resNode: customer_2 deliver_cap: 39.627176860898736 cap_limit: 40
6600 customer_5 ('customer_5', 'customer_4')
3465 customer_5 -22.386389683817313
resNode: customer_4 deliver_cap: 61.97781179666998 cap_limit: 40
6601 customer_3 ('customer_3', 'customer_1')
3466 customer_3 -21.416336340168716
resNode: customer_1 deliver_cap: 51.68951802562863 cap_limit: 40
6602 customer_3 ('customer_3', 'depot_t')
3466 customer_3 -21.416336340168716

resNode: customer_1 deliver_cap: 43.95877585258837 cap_limit: 40
6673 customer_2 ('customer_2', 'depot_t')
3493 customer_2 -13.346511375330675
resNode: depot_t deliver_cap: 28.94643484151566 cap_limit: 40
6674 customer_2 ('customer_2', 'customer_4')
3493 customer_2 -13.346511375330675
resNode: customer_4 deliver_cap: 54.85550646154752 cap_limit: 40
6675 customer_2 ('customer_2', 'customer_5')
3493 customer_2 -13.346511375330675
resNode: customer_5 deliver_cap: 39.94971796461353 cap_limit: 40
6676 customer_4 ('customer_4', 'customer_3')
3494 customer_4 -17.626232385713422
resNode: customer_3 deliver_cap: 53.52738775370732 cap_limit: 40
6677 customer_4 ('customer_4', 'customer_1')
3494 customer_4 -17.626232385713422
resNode: customer_1 deliver_cap: 52.960385409871826 cap_limit: 40
6678 customer_4 ('customer_4', 'depot_t')
3494 customer_4 -17.626232385713422
resNode: depot_t deliver_cap: 38.331768303059214 cap_limit: 40
6679 customer_4 ('customer_4', 'customer_2')
3494 customer_4 -17.626232385713422
resNode: customer_2 deliver_cap: 42.587106206171775 cap_limit: 40
6680 customer_4 ('customer_4', 'customer_5')
3494 customer_4 -17.626232385713422
resNode: customer_5 deliver_cap: 48.553573183874995 cap_limit: 40
6681 customer_5 ('customer_5', 'customer_3')
3495 customer_5 -20.74974236008385
resNode: customer_3 deliver_cap: 61.747344685624746 cap_limit: 40
6682 customer_5 ('customer_5', 'customer_1')
3495 customer_5 -20.74974236008385
resNode: customer_1 deliver_cap: 52.948035449539944 cap_limit: 40
6683 customer_5 ('customer_5', 'depot_t')
3495 customer_5 -20.74974236008385
resNode: depot_t deliver_cap: 34.589399786667755 cap_limit: 40
6684 customer_5 ('customer_5', 'customer_2')
3495 customer_5 -20.74974236008385
resNode: customer_2 deliver_cap: 38.595246455354214 cap_limit: 40
6685 customer_5 ('customer_5', 'customer_4')
3495 customer_5 -20.74974236008385
resNode: customer_4 deliver_cap: 61.51386356988827 cap_limit: 40
6686 customer_3 ('customer_3', 'customer_1')
3496 customer_3 -17.166488245938055
resNode: customer_1 deliver_cap: 50.24028517202944 cap_limit: 40
6687 customer_3 ('customer_3', 'depot_t')
3496 customer_3 -17.166488245938055
resNode: depot_t deliver_cap: 37.098358171651164 cap_limit: 40
6688 customer_3 ('customer_3', 'customer_2')
3496 customer_3 -17.166488245938055
resNode: customer_2 deliver_cap: 41.57104594915201 cap_limit: 40
6689 customer_3 ('customer_3', 'customer_4')
3496 customer_3 -17.166488245938055
resNode: customer_4 deliver_cap: 53.456337313019105 cap_limit: 40
6690 customer_3 ('customer_3', 'customer_5')
3496 customer_3 -17.166488245938055
resNode: customer_5 deliver_cap: 49.46447756220155 cap_limit: 40
6691 customer_2 ('customer_2', 'customer_3')
3498 customer_2 -9.154926056614759
resNode: customer_3 deliver_cap: 44.1207869040244 cap_limit: 40
6692 customer_2 ('customer_2', 'customer_1')
3498 customer_2 -9.154926056614759
resNode: customer_1 deliver_cap: 33.34593347655581 cap_limit: 40
6693 customer_2 ('customer_2', 'depot_t')
3498 customer_2 -9.154926056614759
resNode: depot_t deliver_cap: 21.28816759286041 cap_limit: 40
6694 customer_2 ('customer_2', 'customer_4')
3498 customer_2 -9.154926056614759
resNode: customer_4 deliver_cap: 43.961036666941546 cap_limit: 40
6695 customer_2 ('customer_2', 'customer_5')
3498 customer_2 -9.154926056614759
resNode: customer_5 deliver_cap: 31.850083513182675 cap_limit: 40
6696 customer_4 ('customer_4', 'customer_3')
3499 customer_4 -17.01626520868913
resNode: customer_3 deliver_cap: 53.15978362702387 cap_limit: 40
6697 customer_4 ('customer_4', 'customer_1')
3499 customer_4 -17.01626520868913
resNode: customer_1 deliver_cap: 49.59863519520432 cap_limit: 40
6698 customer_4 ('customer_4', 'depot_t')
3499 customer_4 -17.01626520868913
resNode: depot_t deliver_cap: 36.72848114984749 cap_limit: 40
6699 customer_4 ('customer_4', 'customer_2')
3499 customer_4 -17.01626520868913
resNode: customer_2 deliver_cap: 41.17034584219803 cap_limit: 40
6700 customer_4 ('customer_4', 'customer_5')
3499 customer_4 -17.01626520868913
resNode: customer_5 deliver_cap: 48.971308199796646 cap_limit: 40
6701 customer_5 ('customer_5', 'customer_3')
3500 customer_5 -17.293085315790677
resNode: customer_3 deliver_cap: 53.14743366669199 cap_limit: 40
6702 customer_5 ('customer_5', 'customer_1')
3500 customer_5 -17.293085315790677
resNode: customer_1 deliver_cap: 43.954385450984674 cap_limit: 40
6703 customer_5 ('customer_5', 'depot_t')
3500 customer_5 -17.293085315790677
resNode: depot_t deliver_cap: 28.53377212001125 cap_limit: 40
6704 customer_5 ('customer_5', 'customer_2')
3500 customer_5 -17.293085315790677
resNode: customer_2 deliver_cap: 32.292744393208764 cap_limit: 40
6705 customer_5 ('customer_5', 'customer_4')
3500 customer_5 -17.293085315790677
resNode: customer_4 deliver_cap: 52.95081799028233 cap_limit: 40
6706 customer_3 ('customer_3', 'customer_1')
3501 customer_3 -13.420164070524798
resNode: customer_1 deliver_cap: 42.509542998989176 cap_limit: 40
6707 customer_3 ('customer_3', 'depot_t')
3501 customer_3 -13.420164070524798
resNode: depot_t deliver_cap: 29.96228847346015 cap_limit: 40
6708 customer_3 ('customer_3', 'customer_2')
3501 customer_3 -13.420164070524798
resNode: customer_2 deliver_cap: 33.840303776111746 cap_limit: 40
6709 customer_3 ('customer_3', 'customer_4')
3501 customer_3 -13.420164070524798
resNode: customer_4 deliver_cap: 43.941577715431094 cap_limit: 40
6710 customer_3 ('customer_3', 'customer_5')
3501 customer_3 -13.420164070524798
resNode: customer_5 deliver_cap: 39.949717964613534 cap_limit: 40
6711 customer_1 ('customer_1', 'customer_3')
3502 customer_1 -8.492501006937438
resNode: customer_3 deliver_cap: 41.12838506912592 cap_limit: 40
6712 customer_1 ('customer_1', 'depot_t')
3502 customer_1 -8.492501006937438
resNode: depot_t deliver_cap: 21.937896319670752 cap_limit: 40
6713 customer_1 ('customer_1', 'customer_2')
3502 customer_1 -8.492501006937438
resNode: customer_2 deliver_cap: 24.375440355189724 cap_limit: 40
6714 customer_1 ('customer_1', 'customer_4')
3502 customer_1 -8.492501006937438
resNode: customer_4 deliver_cap: 40.72768496217194 cap_limit: 40
6715 customer_1 ('customer_1', 'customer_5')
3502 customer_1 -8.492501006937438
resNode: customer_5 deliver_cap: 31.85008351318268 cap_limit: 40
6716 customer_4 ('customer_4', 'customer_3')
3504 customer_4 -13.399683270898795
resNode: customer_3 deliver_cap: 43.941577715431094 cap_limit: 40
6717 customer_4 ('customer_4', 'customer_1')
3504 customer_4 -13.399683270898795
resNode: customer_1 deliver_cap: 42.10884289203519 cap_limit: 40
6718 customer_4 ('customer_4', 'depot_t')
3504 customer_4 -13.399683270898795
resNode: depot_t deliver_cap: 29.814826716152908 cap_limit: 40
6719 customer_4 ('customer_4', 'customer_2')
3504 customer_4 -13.399683270898795
resNode: customer_2 deliver_cap: 33.6805535390289 cap_limit: 40
6720 customer_4 ('customer_4', 'customer_5')
3504 customer_4 -13.399683270898795
resNode: customer_5 deliver_cap: 39.75310228820387 cap_limit: 40
6721 customer_5 ('customer_5', 'customer_3')
3505 customer_5 -11.935467844662856
resNode: customer_3 deliver_cap: 39.949717964613534 cap_limit: 40
6722 customer_5 ('customer_5', 'customer_1')
3505 customer_5 -11.935467844662856
resNode: customer_1 deliver_cap: 33.23124144304593 cap_limit: 40
6723 customer_5 ('customer_5', 'depot_t')
3505 customer_5 -11.935467844662856
resNode: depot_t deliver_cap: 18.63548534345241 cap_limit: 40
6724 customer_5 ('customer_5', 'customer_2')
3505 customer_5 -11.935467844662856
resNode: customer_2 deliver_cap: 21.56960038527003 cap_limit: 40
6725 customer_5 ('customer_5', 'customer_4')
3505 customer_5 -11.935467844662856
resNode: customer_4 deliver_cap: 39.75310228820388 cap_limit: 40
6726 customer_3 ('customer_3', 'customer_1')
3506 customer_3 -17.577078466611006
resNode: customer_1 deliver_cap: 53.25693909586707 cap_limit: 40
6727 customer_3 ('customer_3', 'depot_t')
3506 customer_3 -17.577078466611006
resNode: depot_t deliver_cap: 38.331768303059214 cap_limit: 40
6728 customer_3 ('customer_3', 'customer_2')
3506 customer_3 -17.577078466611006
resNode: customer_2 deliver_cap: 42.587106206171775 cap_limit: 40
6729 customer_3 ('customer_3', 'customer_4')
3506 customer_3 -17.577078466611006
resNode: customer_4 deliver_cap: 53.293906637970856 cap_limit: 40
6730 customer_3 ('customer_3', 'customer_5')
3506 customer_3 -17.577078466611006
resNode: customer_5 deliver_cap: 48.553573183874995 cap_limit: 40
6731 customer_1 ('customer_1', 'customer_3')
3507 customer_1 -14.593629436185964
resNode: customer_3 deliver_cap: 60.390756268649874 cap_limit: 40
6732 customer_1 ('customer_1', 'depot_t')
3507 customer_1 -14.593629436185964
resNode: depot_t deliver_cap: 36.578932486983454 cap_limit: 40
6733 customer_1 ('customer_1', 'customer_2')
3507 customer_1 -14.593629436185964
resNode: customer_2 deliver_cap: 39.62717686089874 cap_limit: 40
6734 customer_1 ('customer_1', 'customer_4')
3507 customer_1 -14.593629436185964
resNode: customer_4 deliver_cap: 59.89758690624497 cap_limit: 40
6735 customer_1 ('customer_1', 'customer_5')
3507 customer_1 -14.593629436185964
resNode: customer_5 deliver_cap: 48.971308199796646 cap_limit: 40
6736 customer_2 ('customer_2', 'customer_3')
3509 customer_2 -13.313742095929062
resNode: customer_3 deliver_cap: 54.85550646154752 cap_limit: 40
6737 customer_2 ('customer_2', 'customer_1')
3509 customer_2 -13.313742095929062
resNode: customer_1 deliver_cap: 43.79902561550551 cap_limit: 40
6738 customer_2 ('customer_2', 'depot_t')
3509 customer_2 -13.313742095929062
resNode: depot_t deliver_cap: 28.798973084208413 cap_limit: 40
6739 customer_2 ('customer_2', 'customer_4')
3509 customer_2 -13.313742095929062
resNode: customer_4 deliver_cap: 54.65889078513786 cap_limit: 40
6740 customer_2 ('customer_2', 'customer_5')
3509 customer_2 -13.313742095929062
resNode: customer_5 deliver_cap: 39.75310228820386 cap_limit: 40
6741 customer_5 ('customer_5', 'customer_3')
3510 customer_5 -20.670891281523723
resNode: customer_3 deliver_cap: 61.51386356988827 cap_limit: 40
6742 customer_5 ('customer_5', 'customer_1')
3510 customer_5 -20.670891281523723
resNode: customer_1 deliver_cap: 52.75141977313028 cap_limit: 40
6743 customer_5 ('customer_5', 'depot_t')
3510 customer_5 -20.670891281523723
resNode: depot_t deliver_cap: 34.40507259003369 cap_limit: 40
6744 customer_5 ('customer_5', 'customer_2')
3510 customer_5 -20.670891281523723
resNode: customer_2 deliver_cap: 38.39863077894455 cap_limit: 40
6745 customer_5 ('customer_5', 'customer_4')
3510 customer_5 -20.670891281523723
resNode: customer_4 deliver_cap: 61.28038245415179 cap_limit: 40
6746 customer_2 ('customer_2', 'customer_3')
3513 customer_2 -13.245151778825734
resNode: customer_3 deliver_cap: 64.5792316958771 cap_limit: 40
6747 customer_2 ('customer_2', 'customer_1')
3513 customer_2 -13.245151778825734
resNode: customer_1 deliver_cap: 51.69955236839829 cap_limit: 40
6748 customer_2 ('customer_2', 'depot_t')
3513 customer_2 -13.245151778825734
resNode: depot_t deliver_cap: 36.09176700995559 cap_limit: 40
6749 customer_2 ('customer_2', 'customer_4')
3513 customer_2 -13.245151778825734
resNode: customer_4 deliver_cap: 64.38261601946743 cap_limit: 40
6750 customer_2 ('customer_2', 'customer_5')
3513 customer_2 -13.245151778825734
resNode: customer_5 deliver_cap: 49.47682752253343 cap_limit: 40
6751 customer_1 ('customer_1', 'customer_3')
3517 customer_1 -13.787794572369204
resNode: customer_3 deliver_cap: 64.5792316958771 cap_limit: 40
6752 customer_1 ('customer_1', 'depot_t')
3517 customer_1 -13.787794572369204
resNode: depot_t deliver_cap: 39.720289057403875 cap_limit: 40
6753 customer_1 ('customer_1', 'customer_2')
3517 customer_1 -13.787794572369204
resNode: customer_2 deliver_cap: 43.030313145520864 cap_limit: 40
6754 customer_1 ('customer_1', 'customer_4')
3517 customer_1 -13.787794572369204
resNode: customer_4 deliver_cap: 64.0860623334722 cap_limit: 40
6755 customer_1 ('customer_1', 'customer_5')
3517 customer_1 -13.787794572369204
resNode: customer_5 deliver_cap: 53.15978362702388 cap_limit: 40
6756 customer_5 ('customer_5', 'customer_3')
3520 customer_5 -19.839121414663726
resNode: customer_3 deliver_cap: 64.01741108234089 cap_limit: 40
6757 customer_5 ('customer_5', 'customer_1')
3520 customer_5 -19.839121414663726
resNode: customer_1 deliver_cap: 54.85967030993248 cap_limit: 40
6758 customer_5 ('customer_5', 'depot_t')
3520 customer_5 -19.839121414663726
resNode: depot_t deliver_cap: 36.381557468285756 cap_limit: 40
6759 customer_5 ('customer_5', 'customer_2')
3520 customer_5 -19.839121414663726
resNode: customer_2 deliver_cap: 40.50688131574675 cap_limit: 40
6760 customer_5 ('customer_5', 'customer_4')
3520 customer_5 -19.839121414663726
resNode: customer_4 deliver_cap: 63.78392996660441 cap_limit: 40
6761 customer_2 ('customer_2', 'customer_3')
3524 customer_2 -15.884058866694762
resNode: customer_3 deliver_cap: 68.75774453643673 cap_limit: 40
6762 customer_2 ('customer_2', 'customer_1')
3524 customer_2 -15.884058866694762
resNode: customer_1 deliver_cap: 56.95224516068939 cap_limit: 40
6763 customer_2 ('customer_2', 'depot_t')
3524 customer_2 -15.884058866694762
resNode: depot_t deliver_cap: 38.854108944746606 cap_limit: 40
6764 customer_2 ('customer_2', 'customer_4')
3524 customer_2 -15.884058866694762
resNode: customer_4 deliver_cap: 68.52426342070025 cap_limit: 40
6765 customer_2 ('customer_2', 'customer_5')
3524 customer_2 -15.884058866694762
resNode: customer_5 deliver_cap: 50.823639580591134 cap_limit: 40
6766 customer_2 ('customer_2', 'customer_3')
3529 customer_2 -18.75807760663909
resNode: customer_3 deliver_cap: 64.01741108234087 cap_limit: 40
6767 customer_2 ('customer_2', 'customer_1')
3529 customer_2 -18.75807760663909
resNode: customer_1 deliver_cap: 52.960385409871826 cap_limit: 40
6768 customer_2 ('customer_2', 'depot_t')
3529 customer_2 -18.75807760663909
resNode: depot_t deliver_cap: 35.11174042835515 cap_limit: 40
6769 customer_2 ('customer_2', 'customer_4')
3529 customer_2 -18.75807760663909
resNode: customer_4 deliver_cap: 63.78392996660441 cap_limit: 40
6770 customer_2 ('customer_2', 'customer_5')
3529 customer_2 -18.75807760663909
resNode: customer_5 deliver_cap: 46.08330612649528 cap_limit: 40
6771 customer_1 ('customer_1', 'customer_3')
3537 customer_1 -11.365609260987137
resNode: customer_3 deliver_cap: 57.49577882128432 cap_limit: 40
6772 customer_1 ('customer_1', 'depot_t')
3537 customer_1 -11.365609260987137
resNode: depot_t deliver_cap: 33.26916891731887 cap_limit: 40
6773 customer_1 ('customer_1', 'customer_2')
3537 customer_1 -11.365609260987137
resNode: customer_2 deliver_cap: 36.96574324146542 cap_limit: 40
6774 customer_1 ('customer_1', 'customer_4')
3537 customer_1 -11.365609260987137
resNode: customer_4 deliver_cap: 57.09507871433034 cap_limit: 40
6775 customer_1 ('customer_1', 'customer_5')
3537 customer_1 -11.365609260987137
resNode: customer_5 deliver_cap: 48.217477265341074 cap_limit: 40
6776 customer_5 ('customer_5', 'customer_3')
3540 customer_5 -19.529939681065933
resNode: customer_3 deliver_cap: 60.09420258265463 cap_limit: 40
6777 customer_5 ('customer_5', 'customer_1')
3540 customer_5 -19.529939681065933
resNode: customer_1 deliver_cap: 49.59863519520432 cap_limit: 40
6778 customer_5 ('customer_5', 'depot_t')
3540 customer_5 -19.529939681065933
resNode: depot_t deliver_cap: 33.74384880698323 cap_limit: 40
6779 customer_5 ('customer_5', 'customer_2')
3540 customer_5 -19.529939681065933
resNode: customer_2 deliver_cap: 37.936994137428414 cap_limit: 40
6780 customer_5 ('customer_5', 'customer_4')
3540 customer_5 -19.529939681065933
resNode: customer_4 deliver_cap: 59.89758690624497 cap_limit: 40
6781 customer_2 ('customer_2', 'customer_3')
3549 customer_2 -19.46202917506816
resNode: customer_3 deliver_cap: 61.99348748271529 cap_limit: 40
6782 customer_2 ('customer_2', 'customer_1')
3549 customer_2 -19.46202917506816
resNode: customer_1 deliver_cap: 49.598635195204324 cap_limit: 40
6783 customer_2 ('customer_2', 'depot_t')
3549 customer_2 -19.46202917506816
resNode: depot_t deliver_cap: 34.15245885008424 cap_limit: 40
6784 customer_2 ('customer_2', 'customer_4')
3549 customer_2 -19.46202917506816
resNode: customer_4 deliver_cap: 61.79687180630563 cap_limit: 40
6785 customer_2 ('customer_2', 'customer_5')
3549 customer_2 -19.46202917506816
resNode: customer_5 deliver_cap: 46.89108330937163 cap_limit: 40
6786 customer_2 ('customer_2', 'customer_3')
3553 customer_2 -17.94662521640455
resNode: customer_3 deliver_cap: 67.87768574446616 cap_limit: 40
6787 customer_2 ('customer_2', 'customer_1')
3553 customer_2 -17.94662521640455
resNode: customer_1 deliver_cap: 54.37954628287691 cap_limit: 40
6788 customer_2 ('customer_2', 'depot_t')
3553 customer_2 -17.94662521640455
resNode: depot_t deliver_cap: 38.565607546397395 cap_limit: 40
6789 customer_2 ('customer_2', 'customer_4')
3553 customer_2 -17.94662521640455
resNode: customer_4 deliver_cap: 67.6810700680565 cap_limit: 40
6790 customer_2 ('customer_2', 'customer_5')
3553 customer_2 -17.94662521640455
resNode: customer_5 deliver_cap: 52.775281571122505 cap_limit: 40
6791 customer_2 ('customer_2', 'customer_3')
3558 customer_2 -10.24455087583448
resNode: customer_3 deliver_cap: 52.99838835301367 cap_limit: 40
6792 customer_2 ('customer_2', 'customer_1')
3558 customer_2 -10.24455087583448
resNode: customer_1 deliver_cap: 40.17485766808601 cap_limit: 40
6793 customer_2 ('customer_2', 'depot_t')
3558 customer_2 -10.24455087583448
resNode: depot_t deliver_cap: 27.434199365237593 cap_limit: 40
6794 customer_2 ('customer_2', 'customer_4')
3558 customer_2 -10.24455087583448
resNode: customer_4 deliver_cap: 52.83863811593081 cap_limit: 40
6795 customer_2 ('customer_2', 'customer_5')
3558 customer_2 -10.24455087583448
resNode: customer_5 deliver_cap: 40.727684962171935 cap_limit: 40
6796 customer_5 ('customer_5', 'customer_3')
3560 customer_5 -20.943556706834222
resNode: customer_3 deliver_cap: 64.07371237314031 cap_limit: 40
6797 customer_5 ('customer_5', 'customer_1')
3560 customer_5 -20.943556706834222
resNode: customer_1 deliver_cap: 52.831986899973934 cap_limit: 40
6798 customer_5 ('customer_5', 'depot_t')
3560 customer_5 -20.943556706834222
resNode: depot_t deliver_cap: 36.72848114984748 cap_limit: 40
6799 customer_5 ('customer_5', 'customer_2')
3560 customer_5 -20.943556706834222
resNode: customer_2 deliver_cap: 41.170345842198024 cap_limit: 40
6800 customer_5 ('customer_5', 'customer_4')
3560 customer_5 -20.943556706834222
resNode: customer_4 deliver_cap: 63.877096696730646 cap_limit: 40
6801 customer_2 ('customer_2', 'customer_3')
3564 customer_2 -17.91385593700294
resNode: customer_3 deliver_cap: 67.6810700680565 cap_limit: 40
6802 customer_2 ('customer_2', 'customer_1')
3564 customer_2 -17.91385593700294
resNode: customer_1 deliver_cap: 54.219796045794055 cap_limit: 40
6803 customer_2 ('customer_2', 'depot_t')
3564 customer_2 -17.91385593700294
resNode: depot_t deliver_cap: 38.41814578909015 cap_limit: 40
6804 customer_2 ('customer_2', 'customer_4')
3564 customer_2 -17.91385593700294
resNode: customer_4 deliver_cap: 67.48445439164684 cap_limit: 40
6805 customer_2 ('customer_2', 'customer_5')
3564 customer_2 -17.91385593700294
resNode: customer_5 deliver_cap: 52.57866589471284 cap_limit: 40
6806 customer_1 ('customer_1', 'customer_3')
3567 customer_1 -17.792793517586944
resNode: customer_3 deliver_cap: 62.29004116871053 cap_limit: 40
6807 customer_1 ('customer_1', 'depot_t')
3567 customer_1 -17.792793517586944
resNode: depot_t deliver_cap: 38.00339616202895 cap_limit: 40
6808 customer_1 ('customer_1', 'customer_2')
3567 customer_1 -17.792793517586944
resNode: customer_2 deliver_cap: 41.17034584219803 cap_limit: 40
6809 customer_1 ('customer_1', 'customer_4')
3567 customer_1 -17.792793517586944
resNode: customer_4 deliver_cap: 61.79687180630563 cap_limit: 40
6810 customer_1 ('customer_1', 'customer_5')
3567 customer_1 -17.792793517586944

resNode: customer_2 deliver_cap: 32.292744393208764 cap_limit: 40
6880 customer_5 ('customer_5', 'customer_4')
3610 customer_5 -17.947879530397554
resNode: customer_4 deliver_cap: 52.95081799028233 cap_limit: 40
6881 customer_2 ('customer_2', 'customer_3')
3614 customer_2 -18.286041336451248
resNode: customer_3 deliver_cap: 65.97299727320096 cap_limit: 40
6882 customer_2 ('customer_2', 'customer_1')
3614 customer_2 -18.286041336451248
resNode: customer_1 deliver_cap: 52.831986899973934 cap_limit: 40
6883 customer_2 ('customer_2', 'depot_t')
3614 customer_2 -18.286041336451248
resNode: depot_t deliver_cap: 37.13709119294849 cap_limit: 40
6884 customer_2 ('customer_2', 'customer_4')
3614 customer_2 -18.286041336451248
resNode: customer_4 deliver_cap: 65.7763815967913 cap_limit: 40
6885 customer_2 ('customer_2', 'customer_5')
3614 customer_2 -18.286041336451248
resNode: customer_5 deliver_cap: 50.8705930998573 cap_limit: 40
6886 customer_1 ('customer_1', 'customer_3')
3617 customer_1 -20.154733812278096
resNode: customer_3 deliver_cap: 64.56147816434067 cap_limit: 40
6887 customer_1 ('customer_1', 'depot_t')
3617 customer_1 -20.154733812278096
resNode: depot_t deliver_cap: 39.70697390875155 cap_limit: 40
6888 customer_1 ('customer_1', 'customer_2')
3617 customer_1 -20.154733812278096
resNode: customer_2 deliver_cap: 43.015888401147514 cap_limit: 40
6889 customer_1 ('customer_1', 'customer_4')
3617 customer_1 -20.154733812278096
resNode: customer_4 deliver_cap: 64.06830880193577 cap_limit: 40
6890 customer_1 ('customer_1', 'customer_5')
3617 customer_1 -20.154733812278096
resNode: customer_5 deliver_cap: 53.14203009548745 cap_limit: 40
6891 customer_2 ('customer_2', 'customer_3')
3619 customer_2 -17.87996902439977
resNode: customer_3 deliver_cap: 55.04671856675264 cap_limit: 40
6892 customer_2 ('customer_2', 'customer_1')
3619 customer_2 -17.87996902439977
resNode: customer_1 deliver_cap: 43.954385450984674 cap_limit: 40
6893 customer_2 ('customer_2', 'depot_t')
3619 customer_2 -17.87996902439977
resNode: depot_t deliver_cap: 28.94238216311225 cap_limit: 40
6894 customer_2 ('customer_2', 'customer_4')
3619 customer_2 -17.87996902439977
resNode: customer_4 deliver_cap: 54.85010289034298 cap_limit: 40
6895 customer_2 ('customer_2', 'customer_5')
3619 customer_2 -17.87996902439977
resNode: customer_5 deliver_cap: 39.94431439340898 cap_limit: 40
6896 customer_1 ('customer_1', 'customer_3')
3621 customer_1 -15.480116570343688
resNode: customer_3 deliver_cap: 62.78321053111544 cap_limit: 40
6897 customer_1 ('customer_1', 'depot_t')
3621 customer_1 -15.480116570343688
resNode: depot_t deliver_cap: 38.37327318383263 cap_limit: 40
6898 customer_1 ('customer_1', 'customer_2')
3621 customer_1 -15.480116570343688
resNode: customer_2 deliver_cap: 41.571045949152015 cap_limit: 40
6899 customer_1 ('customer_1', 'customer_4')
3621 customer_1 -15.480116570343688
resNode: customer_4 deliver_cap: 62.29004116871053 cap_limit: 40
6900 customer_1 ('customer_1', 'customer_5')
3621 customer_1 -15.480116570343688
resNode: customer_5 deliver_cap: 51.36376246226221 cap_limit: 40
6901 customer_2 ('customer_2', 'customer_3')
3623 customer_2 -14.126090808587975
resNode: customer_3 deliver_cap: 56.95140703801784 cap_limit: 40
6902 customer_2 ('customer_2', 'customer_1')
3623 customer_2 -14.126090808587975
resNode: customer_1 deliver_cap: 45.50194483388765 cap_limit: 40
6903 customer_2 ('customer_2', 'depot_t')
3623 customer_2 -14.126090808587975
resNode: depot_t deliver_cap: 30.370898516561155 cap_limit: 40
6904 customer_2 ('customer_2', 'customer_4')
3623 customer_2 -14.126090808587975
resNode: customer_4 deliver_cap: 56.754791361608184 cap_limit: 40
6905 customer_2 ('customer_2', 'customer_5')
3623 customer_2 -14.126090808587975
resNode: customer_5 deliver_cap: 41.84900286467418 cap_limit: 40
6906 customer_5 ('customer_5', 'customer_3')
3625 customer_5 -21.97446669179287
resNode: customer_3 deliver_cap: 64.00274550444678 cap_limit: 40
6907 customer_5 ('customer_5', 'customer_1')
3625 customer_5 -21.97446669179287
resNode: customer_1 deliver_cap: 54.84732034960061 cap_limit: 40
6908 customer_5 ('customer_5', 'depot_t')
3625 customer_5 -21.97446669179287
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
6909 customer_5 ('customer_5', 'customer_2')
3625 customer_5 -21.97446669179287
resNode: customer_2 deliver_cap: 40.49453135541487 cap_limit: 40
6910 customer_5 ('customer_5', 'customer_4')
3625 customer_5 -21.97446669179287
resNode: customer_4 deliver_cap: 63.76926438871031 cap_limit: 40
6911 customer_3 ('customer_3', 'customer_1')
3626 customer_3 -16.996425229165027
resNode: customer_1 deliver_cap: 50.24028517202944 cap_limit: 40
6912 customer_3 ('customer_3', 'depot_t')
3626 customer_3 -16.996425229165027
resNode: depot_t deliver_cap: 37.098358171651164 cap_limit: 40
6913 customer_3 ('customer_3', 'customer_2')
3626 customer_3 -16.996425229165027
resNode: customer_2 deliver_cap: 41.57104594915201 cap_limit: 40
6914 customer_3 ('customer_3', 'customer_4')
3626 customer_3 -16.996425229165027
resNode: customer_4 deliver_cap: 53.456337313019105 cap_limit: 40
6915 customer_3 ('customer_3', 'customer_5')
3626 customer_3 -16.996425229165027
resNode: customer_5 deliver_cap: 49.46447756220155 cap_limit: 40
6916 customer_2 ('customer_2', 'customer_3')
3628 customer_2 -8.98486303984173
resNode: customer_3 deliver_cap: 44.1207869040244 cap_limit: 40
6917 customer_2 ('customer_2', 'customer_1')
3628 customer_2 -8.98486303984173
resNode: customer_1 deliver_cap: 33.34593347655581 cap_limit: 40
6918 customer_2 ('customer_2', 'depot_t')
3628 customer_2 -8.98486303984173
resNode: depot_t deliver_cap: 21.28816759286041 cap_limit: 40
6919 customer_2 ('customer_2', 'customer_4')
3628 customer_2 -8.98486303984173
resNode: customer_4 deliver_cap: 43.961036666941546 cap_limit: 40
6920 customer_2 ('customer_2', 'customer_5')
3628 customer_2 -8.98486303984173
resNode: customer_5 deliver_cap: 31.850083513182675 cap_limit: 40
6921 customer_4 ('customer_4', 'customer_3')
3629 customer_4 -16.846202191916102
resNode: customer_3 deliver_cap: 53.15978362702387 cap_limit: 40
6922 customer_4 ('customer_4', 'customer_1')
3629 customer_4 -16.846202191916102
resNode: customer_1 deliver_cap: 49.59863519520432 cap_limit: 40
6923 customer_4 ('customer_4', 'depot_t')
3629 customer_4 -16.846202191916102
resNode: depot_t deliver_cap: 36.72848114984749 cap_limit: 40
6924 customer_4 ('customer_4', 'customer_2')
3629 customer_4 -16.846202191916102
resNode: customer_2 deliver_cap: 41.17034584219803 cap_limit: 40
6925 customer_4 ('customer_4', 'customer_5')
3629 customer_4 -16.846202191916102
resNode: customer_5 deliver_cap: 48.971308199796646 cap_limit: 40
6926 customer_5 ('customer_5', 'customer_3')
3630 customer_5 -17.12302229901765
resNode: customer_3 deliver_cap: 53.14743366669199 cap_limit: 40
6927 customer_5 ('customer_5', 'customer_1')
3630 customer_5 -17.12302229901765
resNode: customer_1 deliver_cap: 43.954385450984674 cap_limit: 40
6928 customer_5 ('customer_5', 'depot_t')
3630 customer_5 -17.12302229901765
resNode: depot_t deliver_cap: 28.53377212001125 cap_limit: 40
6929 customer_5 ('customer_5', 'customer_2')
3630 customer_5 -17.12302229901765
resNode: customer_2 deliver_cap: 32.292744393208764 cap_limit: 40
6930 customer_5 ('customer_5', 'customer_4')
3630 customer_5 -17.12302229901765
resNode: customer_4 deliver_cap: 52.95081799028233 cap_limit: 40
6931 customer_1 ('customer_1', 'customer_3')
3632 customer_1 -15.373208869443268
resNode: customer_3 deliver_cap: 62.29004116871053 cap_limit: 40
6932 customer_1 ('customer_1', 'depot_t')
3632 customer_1 -15.373208869443268
resNode: depot_t deliver_cap: 38.00339616202895 cap_limit: 40
6933 customer_1 ('customer_1', 'customer_2')
3632 customer_1 -15.373208869443268
resNode: customer_2 deliver_cap: 41.17034584219803 cap_limit: 40
6934 customer_1 ('customer_1', 'customer_4')
3632 customer_1 -15.373208869443268
resNode: customer_4 deliver_cap: 61.79687180630563 cap_limit: 40
6935 customer_1 ('customer_1', 'customer_5')
3632 customer_1 -15.373208869443268
resNode: customer_5 deliver_cap: 50.87059309985731 cap_limit: 40
6936 customer_2 ('customer_2', 'customer_3')
3634 customer_2 -14.093321529186367
resNode: customer_3 deliver_cap: 56.754791361608184 cap_limit: 40
6937 customer_2 ('customer_2', 'customer_1')
3634 customer_2 -14.093321529186367
resNode: customer_1 deliver_cap: 45.3421945968048 cap_limit: 40
6938 customer_2 ('customer_2', 'depot_t')
3634 customer_2 -14.093321529186367
resNode: depot_t deliver_cap: 30.22343675925391 cap_limit: 40
6939 customer_2 ('customer_2', 'customer_4')
3634 customer_2 -14.093321529186367
resNode: customer_4 deliver_cap: 56.55817568519852 cap_limit: 40
6940 customer_2 ('customer_2', 'customer_5')
3634 customer_2 -14.093321529186367
resNode: customer_5 deliver_cap: 41.65238718826453 cap_limit: 40
6941 customer_5 ('customer_5', 'customer_3')
3635 customer_5 -21.89561561323275
resNode: customer_3 deliver_cap: 63.7692643887103 cap_limit: 40
6942 customer_5 ('customer_5', 'customer_1')
3635 customer_5 -21.89561561323275
resNode: customer_1 deliver_cap: 54.650704673190944 cap_limit: 40
6943 customer_5 ('customer_5', 'depot_t')
3635 customer_5 -21.89561561323275
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
6944 customer_5 ('customer_5', 'customer_2')
3635 customer_5 -21.89561561323275
resNode: customer_2 deliver_cap: 40.29791567900521 cap_limit: 40
6945 customer_5 ('customer_5', 'customer_4')
3635 customer_5 -21.89561561323275
resNode: customer_4 deliver_cap: 63.53578327297383 cap_limit: 40
6946 customer_3 ('customer_3', 'customer_1')
3636 customer_3 -18.19886564845696
resNode: customer_1 deliver_cap: 51.16436424511017 cap_limit: 40
6947 customer_3 ('customer_3', 'depot_t')
3636 customer_3 -18.19886564845696
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
6948 customer_3 ('customer_3', 'customer_2')
3636 customer_3 -18.19886564845696
resNode: customer_2 deliver_cap: 40.49453135541487 cap_limit: 40
6949 customer_3 ('customer_3', 'customer_4')
3636 customer_3 -18.19886564845696
resNode: customer_4 deliver_cap: 50.808974002697035 cap_limit: 40
6950 customer_3 ('customer_3', 'customer_5')
3636 customer_3 -18.19886564845696
resNode: customer_5 deliver_cap: 46.06864054860118 cap_limit: 40
6951 customer_1 ('customer_1', 'customer_3')
3637 customer_1 -13.972259109770377
resNode: customer_3 deliver_cap: 51.363762462262216 cap_limit: 40
6952 customer_1 ('customer_1', 'depot_t')
3637 customer_1 -13.972259109770377
resNode: depot_t deliver_cap: 29.808687132192713 cap_limit: 40
6953 customer_1 ('customer_1', 'customer_2')
3637 customer_1 -13.972259109770377
resNode: customer_2 deliver_cap: 32.29274439320877 cap_limit: 40
6954 customer_1 ('customer_1', 'customer_4')
3637 customer_1 -13.972259109770377
resNode: customer_4 deliver_cap: 50.87059309985732 cap_limit: 40
6955 customer_1 ('customer_1', 'customer_5')
3637 customer_1 -13.972259109770377
resNode: customer_5 deliver_cap: 39.944314393408995 cap_limit: 40
6956 customer_2 ('customer_2', 'customer_3')
3639 customer_2 -11.697494321892055
resNode: customer_3 deliver_cap: 41.84900286467419 cap_limit: 40
6957 customer_2 ('customer_2', 'customer_1')
3639 customer_2 -11.697494321892055
resNode: customer_1 deliver_cap: 33.23124144304593 cap_limit: 40
6958 customer_2 ('customer_2', 'depot_t')
3639 customer_2 -11.697494321892055
resNode: depot_t deliver_cap: 19.04409538655342 cap_limit: 40
6959 customer_2 ('customer_2', 'customer_4')
3639 customer_2 -11.697494321892055
resNode: customer_4 deliver_cap: 41.652387188264534 cap_limit: 40
6960 customer_2 ('customer_2', 'customer_5')
3639 customer_2 -11.697494321892055
resNode: customer_5 deliver_cap: 26.74659869133054 cap_limit: 40
6961 customer_4 ('customer_4', 'customer_3')
3640 customer_4 -18.169168488999247
resNode: customer_3 deliver_cap: 50.808974002697035 cap_limit: 40
6962 customer_4 ('customer_4', 'customer_1')
3640 customer_4 -18.169168488999247
resNode: customer_1 deliver_cap: 50.671194882705265 cap_limit: 40
6963 customer_4 ('customer_4', 'depot_t')
3640 customer_4 -18.169168488999247
resNode: depot_t deliver_cap: 36.18565218384057 cap_limit: 40
6964 customer_4 ('customer_4', 'customer_2')
3640 customer_4 -18.169168488999247
resNode: customer_2 deliver_cap: 40.297915679005214 cap_limit: 40
6965 customer_4 ('customer_4', 'customer_5')
3640 customer_4 -18.169168488999247
resNode: customer_5 deliver_cap: 45.83515943286471 cap_limit: 40
6966 customer_2 ('customer_2', 'customer_3')
3643 customer_2 -18.150560937513482
resNode: customer_3 deliver_cap: 68.74307895854263 cap_limit: 40
6967 customer_2 ('customer_2', 'customer_1')
3643 customer_2 -18.150560937513482
resNode: customer_1 deliver_cap: 56.939895200357505 cap_limit: 40
6968 customer_2 ('customer_2', 'depot_t')
3643 customer_2 -18.150560937513482
resNode: depot_t deliver_cap: 38.84253085693547 cap_limit: 40
6969 customer_2 ('customer_2', 'customer_4')
3643 customer_2 -18.150560937513482
resNode: customer_4 deliver_cap: 68.50959784280616 cap_limit: 40
6970 customer_2 ('customer_2', 'customer_5')
3643 customer_2 -18.150560937513482
resNode: customer_5 deliver_cap: 50.80897400269703 cap_limit: 40
6971 customer_2 ('customer_2', 'customer_3')
3648 customer_2 -15.425971504648928
resNode: customer_3 deliver_cap: 64.07371237314031 cap_limit: 40
6972 customer_2 ('customer_2', 'customer_1')
3648 customer_2 -15.425971504648928
resNode: customer_1 deliver_cap: 51.28881791867465 cap_limit: 40
6973 customer_2 ('customer_2', 'depot_t')
3648 customer_2 -15.425971504648928
resNode: depot_t deliver_cap: 35.712627517903 cap_limit: 40
6974 customer_2 ('customer_2', 'customer_4')
3648 customer_2 -15.425971504648928
resNode: customer_4 deliver_cap: 63.877096696730646 cap_limit: 40
6975 customer_2 ('customer_2', 'customer_5')
3648 customer_2 -15.425971504648928
resNode: customer_5 deliver_cap: 48.971308199796646 cap_limit: 40
6976 customer_1 ('customer_1', 'customer_3')
3652 customer_1 -16.061287325065912
resNode: customer_3 deliver_cap: 64.37026605913555 cap_limit: 40
6977 customer_1 ('customer_1', 'depot_t')
3652 customer_1 -16.061287325065912
resNode: depot_t deliver_cap: 39.56356482984771 cap_limit: 40
6978 customer_1 ('customer_1', 'customer_2')
3652 customer_1 -16.061287325065912
resNode: customer_2 deliver_cap: 42.86052856566835 cap_limit: 40
6979 customer_1 ('customer_1', 'customer_4')
3652 customer_1 -16.061287325065912
resNode: customer_4 deliver_cap: 63.877096696730646 cap_limit: 40
6980 customer_1 ('customer_1', 'customer_5')
3652 customer_1 -16.061287325065912
resNode: customer_5 deliver_cap: 52.950817990282324 cap_limit: 40
6981 customer_5 ('customer_5', 'customer_3')
3655 customer_5 -22.06363784624913
resNode: customer_3 deliver_cap: 63.76926438871029 cap_limit: 40
6982 customer_5 ('customer_5', 'customer_1')
3655 customer_5 -22.06363784624913
resNode: customer_1 deliver_cap: 54.65070467319093 cap_limit: 40
6983 customer_5 ('customer_5', 'depot_t')
3655 customer_5 -22.06363784624913
resNode: depot_t deliver_cap: 36.18565218384055 cap_limit: 40
6984 customer_5 ('customer_5', 'customer_2')
3655 customer_5 -22.06363784624913
resNode: customer_2 deliver_cap: 40.2979156790052 cap_limit: 40
6985 customer_5 ('customer_5', 'customer_4')
3655 customer_5 -22.06363784624913
resNode: customer_4 deliver_cap: 63.535783272973816 cap_limit: 40
6986 customer_2 ('customer_2', 'customer_3')
3659 customer_2 -20.982594038224498
resNode: customer_3 deliver_cap: 63.76926438871029 cap_limit: 40
6987 customer_2 ('customer_2', 'customer_1')
3659 customer_2 -20.982594038224498
resNode: customer_1 deliver_cap: 52.75141977313028 cap_limit: 40
6988 customer_2 ('customer_2', 'depot_t')
3659 customer_2 -20.982594038224498
resNode: depot_t deliver_cap: 34.915835143909945 cap_limit: 40
6989 customer_2 ('customer_2', 'customer_4')
3659 customer_2 -20.982594038224498
resNode: customer_4 deliver_cap: 63.535783272973816 cap_limit: 40
6990 customer_2 ('customer_2', 'customer_5')
3659 customer_2 -20.982594038224498
resNode: customer_5 deliver_cap: 45.8351594328647 cap_limit: 40
6991 customer_1 ('customer_1', 'customer_3')
3662 customer_1 -9.775740042375908
resNode: customer_3 deliver_cap: 64.87578538187235 cap_limit: 40
6992 customer_1 ('customer_1', 'depot_t')
3662 customer_1 -9.775740042375908
resNode: depot_t deliver_cap: 39.94270432190031 cap_limit: 40
6993 customer_1 ('customer_1', 'customer_2')
3662 customer_1 -9.775740042375908
resNode: customer_2 deliver_cap: 43.271263015392 cap_limit: 40
6994 customer_1 ('customer_1', 'customer_4')
3662 customer_1 -9.775740042375908
resNode: customer_4 deliver_cap: 64.38261601946743 cap_limit: 40
6995 customer_1 ('customer_1', 'customer_5')
3662 customer_1 -9.775740042375908
resNode: customer_5 deliver_cap: 53.45633731301911 cap_limit: 40
6996 customer_5 ('customer_5', 'customer_3')
3665 customer_5 -15.896571654825564
resNode: customer_3 deliver_cap: 64.36956858446024 cap_limit: 40
6997 customer_5 ('customer_5', 'customer_1')
3665 customer_5 -15.896571654825564
resNode: customer_1 deliver_cap: 55.15622399592773 cap_limit: 40
6998 customer_5 ('customer_5', 'depot_t')
3665 customer_5 -15.896571654825564
resNode: depot_t deliver_cap: 36.659576548906294 cap_limit: 40
6999 customer_5 ('customer_5', 'customer_2')
3665 customer_5 -15.896571654825564
resNode: customer_2 deliver_cap: 40.803435001741995 cap_limit: 40
7000 customer_5 ('customer_5', 'customer_4')
3665 customer_5 -15.896571654825564
resNode: customer_4 deliver_cap: 64.13608746872377 cap_limit: 40
7001 customer_2 ('customer_2', 'customer_3')
3669 customer_2 -15.854199276521602
resNode: customer_3 deliver_cap: 66.62496940328225 cap_limit: 40
7002 customer_2 ('customer_2', 'customer_1')
3669 customer_2 -15.854199276521602
resNode: customer_1 deliver_cap: 55.156223995927725 cap_limit: 40
7003 customer_2 ('customer_2', 'depot_t')
3669 customer_2 -15.854199276521602
resNode: depot_t deliver_cap: 37.17033910278255 cap_limit: 40
7004 customer_2 ('customer_2', 'customer_4')
3669 customer_2 -15.854199276521602
resNode: customer_4 deliver_cap: 66.39148828754578 cap_limit: 40
7005 customer_2 ('customer_2', 'customer_5')
3669 customer_2 -15.854199276521602
resNode: customer_5 deliver_cap: 48.69086444743667 cap_limit: 40
7006 customer_2 ('customer_2', 'customer_3')
3678 customer_2 -8.0572265623016
resNode: customer_3 deliver_cap: 59.04398188877475 cap_limit: 40
7007 customer_2 ('customer_2', 'customer_1')
3678 customer_2 -8.0572265623016
resNode: customer_1 deliver_cap: 47.20216190012764 cap_limit: 40
7008 customer_2 ('customer_2', 'depot_t')
3678 customer_2 -8.0572265623016
resNode: depot_t deliver_cap: 31.940329654628837 cap_limit: 40
7009 customer_2 ('customer_2', 'customer_4')
3678 customer_2 -8.0572265623016
resNode: customer_4 deliver_cap: 58.84736621236509 cap_limit: 40
7010 customer_2 ('customer_2', 'customer_5')
3678 customer_2 -8.0572265623016
resNode: customer_5 deliver_cap: 43.941577715431094 cap_limit: 40
7011 customer_2 ('customer_2', 'customer_3')
3689 customer_2 -11.297383026652815
resNode: customer_3 deliver_cap: 55.32619238114649 cap_limit: 40
7012 customer_2 ('customer_2', 'customer_1')
3689 customer_2 -11.297383026652815
resNode: customer_1 deliver_cap: 45.641464398339714 cap_limit: 40
7013 customer_2 ('customer_2', 'depot_t')
3689 customer_2 -11.297383026652815
resNode: depot_t deliver_cap: 28.250251980043792 cap_limit: 40
7014 customer_2 ('customer_2', 'customer_4')
3689 customer_2 -11.297383026652815
resNode: customer_4 deliver_cap: 55.092711265410024 cap_limit: 40
7015 customer_2 ('customer_2', 'customer_5')
3689 customer_2 -11.297383026652815
resNode: customer_5 deliver_cap: 37.39208742530091 cap_limit: 40
7016 customer_2 ('customer_2', 'customer_3')
3693 customer_2 -10.404976030638691
resNode: customer_3 deliver_cap: 71.11012532322397 cap_limit: 40
7017 customer_2 ('customer_2', 'customer_1')
3693 customer_2 -10.404976030638691

resNode: customer_1 deliver_cap: 52.82758943865101 cap_limit: 40
7048 customer_5 ('customer_5', 'depot_t')
3720 customer_5 -15.874144382139965
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
7049 customer_5 ('customer_5', 'customer_2')
3720 customer_5 -15.874144382139965
resNode: customer_2 deliver_cap: 35.78365250805547 cap_limit: 40
7050 customer_5 ('customer_5', 'customer_4')
3720 customer_5 -15.874144382139965
resNode: customer_4 deliver_cap: 59.59181789834911 cap_limit: 40
7051 customer_2 ('customer_2', 'customer_3')
3738 customer_2 -16.154903140886347
resNode: customer_3 deliver_cap: 67.87768574446616 cap_limit: 40
7052 customer_2 ('customer_2', 'customer_1')
3738 customer_2 -16.154903140886347
resNode: customer_1 deliver_cap: 54.37954628287691 cap_limit: 40
7053 customer_2 ('customer_2', 'depot_t')
3738 customer_2 -16.154903140886347
resNode: depot_t deliver_cap: 38.565607546397395 cap_limit: 40
7054 customer_2 ('customer_2', 'customer_4')
3738 customer_2 -16.154903140886347
resNode: customer_4 deliver_cap: 67.6810700680565 cap_limit: 40
7055 customer_2 ('customer_2', 'customer_5')
3738 customer_2 -16.154903140886347
resNode: customer_5 deliver_cap: 52.775281571122505 cap_limit: 40
7056 customer_2 ('customer_2', 'customer_3')
3743 customer_2 -8.45282880031628
resNode: customer_3 deliver_cap: 52.99838835301367 cap_limit: 40
7057 customer_2 ('customer_2', 'customer_1')
3743 customer_2 -8.45282880031628
resNode: customer_1 deliver_cap: 40.17485766808601 cap_limit: 40
7058 customer_2 ('customer_2', 'depot_t')
3743 customer_2 -8.45282880031628
resNode: depot_t deliver_cap: 27.434199365237593 cap_limit: 40
7059 customer_2 ('customer_2', 'customer_4')
3743 customer_2 -8.45282880031628
resNode: customer_4 deliver_cap: 52.83863811593081 cap_limit: 40
7060 customer_2 ('customer_2', 'customer_5')
3743 customer_2 -8.45282880031628
resNode: customer_5 deliver_cap: 40.727684962171935 cap_limit: 40
7061 customer_5 ('customer_5', 'customer_3')
3745 customer_5 -19.15183463131602
resNode: customer_3 deliver_cap: 64.07371237314031 cap_limit: 40
7062 customer_5 ('customer_5', 'customer_1')
3745 customer_5 -19.15183463131602
resNode: customer_1 deliver_cap: 52.831986899973934 cap_limit: 40
7063 customer_5 ('customer_5', 'depot_t')
3745 customer_5 -19.15183463131602
resNode: depot_t deliver_cap: 36.72848114984748 cap_limit: 40
7064 customer_5 ('customer_5', 'customer_2')
3745 customer_5 -19.15183463131602
resNode: customer_2 deliver_cap: 41.170345842198024 cap_limit: 40
7065 customer_5 ('customer_5', 'customer_4')
3745 customer_5 -19.15183463131602
resNode: customer_4 deliver_cap: 63.877096696730646 cap_limit: 40
7066 customer_2 ('customer_2', 'customer_3')
3749 customer_2 -16.122133861484738
resNode: customer_3 deliver_cap: 67.6810700680565 cap_limit: 40
7067 customer_2 ('customer_2', 'customer_1')
3749 customer_2 -16.122133861484738
resNode: customer_1 deliver_cap: 54.219796045794055 cap_limit: 40
7068 customer_2 ('customer_2', 'depot_t')
3749 customer_2 -16.122133861484738
resNode: depot_t deliver_cap: 38.41814578909015 cap_limit: 40
7069 customer_2 ('customer_2', 'customer_4')
3749 customer_2 -16.122133861484738
resNode: customer_4 deliver_cap: 67.48445439164684 cap_limit: 40
7070 customer_2 ('customer_2', 'customer_5')
3749 customer_2 -16.122133861484738
resNode: customer_5 deliver_cap: 52.57866589471284 cap_limit: 40
7071 customer_1 ('customer_1', 'customer_3')
3752 customer_1 -16.001071442068742
resNode: customer_3 deliver_cap: 62.29004116871053 cap_limit: 40
7072 customer_1 ('customer_1', 'depot_t')
3752 customer_1 -16.001071442068742
resNode: depot_t deliver_cap: 38.00339616202895 cap_limit: 40
7073 customer_1 ('customer_1', 'customer_2')
3752 customer_1 -16.001071442068742
resNode: customer_2 deliver_cap: 41.17034584219803 cap_limit: 40
7074 customer_1 ('customer_1', 'customer_4')
3752 customer_1 -16.001071442068742
resNode: customer_4 deliver_cap: 61.79687180630563 cap_limit: 40
7075 customer_1 ('customer_1', 'customer_5')
3752 customer_1 -16.001071442068742
resNode: customer_5 deliver_cap: 50.87059309985731 cap_limit: 40
7076 customer_2 ('customer_2', 'customer_3')
3754 customer_2 -13.726306654190424
resNode: customer_3 deliver_cap: 52.775281571122505 cap_limit: 40
7077 customer_2 ('customer_2', 'customer_1')
3754 customer_2 -13.726306654190424
resNode: customer_1 deliver_cap: 42.10884289203519 cap_limit: 40
7078 customer_2 ('customer_2', 'depot_t')
3754 customer_2 -13.726306654190424
resNode: depot_t deliver_cap: 27.23880441638965 cap_limit: 40
7079 customer_2 ('customer_2', 'customer_4')
3754 customer_2 -13.726306654190424
resNode: customer_4 deliver_cap: 52.57866589471284 cap_limit: 40
7080 customer_2 ('customer_2', 'customer_5')
3754 customer_2 -13.726306654190424
resNode: customer_5 deliver_cap: 37.67287739777885 cap_limit: 40
7081 customer_2 ('customer_2', 'customer_3')
3773 customer_2 -16.439289414405508
resNode: customer_3 deliver_cap: 65.97299727320097 cap_limit: 40
7082 customer_2 ('customer_2', 'customer_1')
3773 customer_2 -16.439289414405508
resNode: customer_1 deliver_cap: 52.83198689997394 cap_limit: 40
7083 customer_2 ('customer_2', 'depot_t')
3773 customer_2 -16.439289414405508
resNode: depot_t deliver_cap: 37.137091192948496 cap_limit: 40
7084 customer_2 ('customer_2', 'customer_4')
3773 customer_2 -16.439289414405508
resNode: customer_4 deliver_cap: 65.77638159679131 cap_limit: 40
7085 customer_2 ('customer_2', 'customer_5')
3773 customer_2 -16.439289414405508
resNode: customer_5 deliver_cap: 50.87059309985731 cap_limit: 40
7086 customer_1 ('customer_1', 'customer_3')
3777 customer_1 -15.831008425295721
resNode: customer_3 deliver_cap: 62.29004116871054 cap_limit: 40
7087 customer_1 ('customer_1', 'depot_t')
3777 customer_1 -15.831008425295721
resNode: depot_t deliver_cap: 38.003396162028956 cap_limit: 40
7088 customer_1 ('customer_1', 'customer_2')
3777 customer_1 -15.831008425295721
resNode: customer_2 deliver_cap: 41.17034584219803 cap_limit: 40
7089 customer_1 ('customer_1', 'customer_4')
3777 customer_1 -15.831008425295721
resNode: customer_4 deliver_cap: 61.79687180630563 cap_limit: 40
7090 customer_1 ('customer_1', 'customer_5')
3777 customer_1 -15.831008425295721
resNode: customer_5 deliver_cap: 50.87059309985731 cap_limit: 40
7091 customer_5 ('customer_5', 'customer_3')
3780 customer_5 -21.34580623778558
resNode: customer_3 deliver_cap: 61.2989973313306 cap_limit: 40
7092 customer_5 ('customer_5', 'customer_1')
3780 customer_5 -21.34580623778558
resNode: customer_1 deliver_cap: 52.57047978276593 cap_limit: 40
7093 customer_5 ('customer_5', 'depot_t')
3780 customer_5 -21.34580623778558
resNode: depot_t deliver_cap: 34.23544134906711 cap_limit: 40
7094 customer_5 ('customer_5', 'customer_2')
3780 customer_5 -21.34580623778558
resNode: customer_2 deliver_cap: 38.21769078858019 cap_limit: 40
7095 customer_5 ('customer_5', 'customer_4')
3780 customer_5 -21.34580623778558
resNode: customer_4 deliver_cap: 61.06551621559413 cap_limit: 40
7096 customer_2 ('customer_2', 'customer_3')
3783 customer_2 -14.140724064448072
resNode: customer_3 deliver_cap: 68.17423943046141 cap_limit: 40
7097 customer_2 ('customer_2', 'customer_1')
3783 customer_2 -14.140724064448072
resNode: customer_1 deliver_cap: 54.62049615274805 cap_limit: 40
7098 customer_2 ('customer_2', 'depot_t')
3783 customer_2 -14.140724064448072
resNode: depot_t deliver_cap: 38.788022810893835 cap_limit: 40
7099 customer_2 ('customer_2', 'customer_4')
3783 customer_2 -14.140724064448072
resNode: customer_4 deliver_cap: 67.97762375405175 cap_limit: 40
7100 customer_2 ('customer_2', 'customer_5')
3783 customer_2 -14.140724064448072
resNode: customer_5 deliver_cap: 53.071835257117755 cap_limit: 40
7101 customer_5 ('customer_5', 'customer_3')
3790 customer_5 -21.577273638079262
resNode: customer_3 deliver_cap: 68.28648276715975 cap_limit: 40
7102 customer_5 ('customer_5', 'customer_1')
3790 customer_5 -21.577273638079262
resNode: customer_1 deliver_cap: 58.4546780445168 cap_limit: 40
7103 customer_5 ('customer_5', 'depot_t')
3790 customer_5 -21.577273638079262
resNode: depot_t deliver_cap: 39.75187721945855 cap_limit: 40
7104 customer_5 ('customer_5', 'customer_2')
3790 customer_5 -21.577273638079262
resNode: customer_2 deliver_cap: 44.10188905033107 cap_limit: 40
7105 customer_5 ('customer_5', 'customer_4')
3790 customer_5 -21.577273638079262
resNode: customer_4 deliver_cap: 68.05300165142329 cap_limit: 40
7106 customer_2 ('customer_2', 'customer_3')
3799 customer_2 -20.496229830054627
resNode: customer_3 deliver_cap: 68.28648276715975 cap_limit: 40
7107 customer_2 ('customer_2', 'customer_1')
3799 customer_2 -20.496229830054627
resNode: customer_1 deliver_cap: 56.55539314445615 cap_limit: 40
7108 customer_2 ('customer_2', 'depot_t')
3799 customer_2 -20.496229830054627
resNode: depot_t deliver_cap: 38.48206017952795 cap_limit: 40
7109 customer_2 ('customer_2', 'customer_4')
3799 customer_2 -20.496229830054627
resNode: customer_4 deliver_cap: 68.05300165142329 cap_limit: 40
7110 customer_2 ('customer_2', 'customer_5')
3799 customer_2 -20.496229830054627
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
7111 customer_2 ('customer_2', 'customer_3')
3803 customer_2 -15.975761476314775
resNode: customer_3 deliver_cap: 68.17423943046141 cap_limit: 40
7112 customer_2 ('customer_2', 'customer_1')
3803 customer_2 -15.975761476314775
resNode: customer_1 deliver_cap: 54.62049615274804 cap_limit: 40
7113 customer_2 ('customer_2', 'depot_t')
3803 customer_2 -15.975761476314775
resNode: depot_t deliver_cap: 38.78802281089383 cap_limit: 40
7114 customer_2 ('customer_2', 'customer_4')
3803 customer_2 -15.975761476314775
resNode: customer_4 deliver_cap: 67.97762375405175 cap_limit: 40
7115 customer_2 ('customer_2', 'customer_5')
3803 customer_2 -15.975761476314775
resNode: customer_5 deliver_cap: 53.07183525711775 cap_limit: 40
7116 customer_1 ('customer_1', 'customer_3')
3807 customer_1 -8.520042531167526
resNode: customer_3 deliver_cap: 53.239338222884804 cap_limit: 40
7117 customer_1 ('customer_1', 'depot_t')
3807 customer_1 -8.520042531167526
resNode: depot_t deliver_cap: 30.32240234919613 cap_limit: 40
7118 customer_1 ('customer_1', 'customer_2')
3807 customer_1 -8.520042531167526
resNode: customer_2 deliver_cap: 33.69155816577348 cap_limit: 40
7119 customer_1 ('customer_1', 'customer_4')
3807 customer_1 -8.520042531167526
resNode: customer_4 deliver_cap: 52.83863811593081 cap_limit: 40
7120 customer_1 ('customer_1', 'customer_5')
3807 customer_1 -8.520042531167526
resNode: customer_5 deliver_cap: 43.96103666694155 cap_limit: 40
7121 customer_5 ('customer_5', 'customer_3')
3810 customer_5 -15.456553547861844
resNode: customer_3 deliver_cap: 54.85550646154753 cap_limit: 40
7122 customer_5 ('customer_5', 'customer_1')
3810 customer_5 -15.456553547861844
resNode: customer_1 deliver_cap: 45.3421945968048 cap_limit: 40
7123 customer_5 ('customer_5', 'depot_t')
3810 customer_5 -15.456553547861844
resNode: depot_t deliver_cap: 29.8148267161529 cap_limit: 40
7124 customer_5 ('customer_5', 'customer_2')
3810 customer_5 -15.456553547861844
resNode: customer_2 deliver_cap: 33.68055353902889 cap_limit: 40
7125 customer_5 ('customer_5', 'customer_4')
3810 customer_5 -15.456553547861844
resNode: customer_4 deliver_cap: 54.65889078513787 cap_limit: 40
7126 customer_2 ('customer_2', 'customer_3')
3814 customer_2 -15.794715353915542
resNode: customer_3 deliver_cap: 67.6810700680565 cap_limit: 40
7127 customer_2 ('customer_2', 'customer_1')
3814 customer_2 -15.794715353915542
resNode: customer_1 deliver_cap: 54.219796045794055 cap_limit: 40
7128 customer_2 ('customer_2', 'depot_t')
3814 customer_2 -15.794715353915542
resNode: depot_t deliver_cap: 38.41814578909015 cap_limit: 40
7129 customer_2 ('customer_2', 'customer_4')
3814 customer_2 -15.794715353915542
resNode: customer_4 deliver_cap: 67.48445439164684 cap_limit: 40
7130 customer_2 ('customer_2', 'customer_5')
3814 customer_2 -15.794715353915542
resNode: customer_5 deliver_cap: 52.57866589471284 cap_limit: 40
7131 customer_2 ('customer_2', 'customer_3')
3819 customer_2 -15.388643041864066
resNode: customer_3 deliver_cap: 56.75479136160818 cap_limit: 40
7132 customer_2 ('customer_2', 'customer_1')
3819 customer_2 -15.388643041864066
resNode: customer_1 deliver_cap: 45.342194596804795 cap_limit: 40
7133 customer_2 ('customer_2', 'depot_t')
3819 customer_2 -15.388643041864066
resNode: depot_t deliver_cap: 30.223436759253907 cap_limit: 40
7134 customer_2 ('customer_2', 'customer_4')
3819 customer_2 -15.388643041864066
resNode: customer_4 deliver_cap: 56.55817568519852 cap_limit: 40
7135 customer_2 ('customer_2', 'customer_5')
3819 customer_2 -15.388643041864066
resNode: customer_5 deliver_cap: 41.65238718826452 cap_limit: 40
7136 customer_2 ('customer_2', 'customer_3')
3828 customer_2 -14.002993278397343
resNode: customer_3 deliver_cap: 67.68107006805651 cap_limit: 40
7137 customer_2 ('customer_2', 'customer_1')
3828 customer_2 -14.002993278397343
resNode: customer_1 deliver_cap: 54.219796045794055 cap_limit: 40
7138 customer_2 ('customer_2', 'depot_t')
3828 customer_2 -14.002993278397343
resNode: depot_t deliver_cap: 38.418145789090154 cap_limit: 40
7139 customer_2 ('customer_2', 'customer_4')
3828 customer_2 -14.002993278397343
resNode: customer_4 deliver_cap: 67.48445439164685 cap_limit: 40
7140 customer_2 ('customer_2', 'customer_5')
3828 customer_2 -14.002993278397343
resNode: customer_5 deliver_cap: 52.57866589471285 cap_limit: 40
7141 customer_5 ('customer_5', 'customer_3')
3835 customer_5 -21.48613407974353
resNode: customer_3 deliver_cap: 68.05300165142329 cap_limit: 40
7142 customer_5 ('customer_5', 'customer_1')
3835 customer_5 -21.48613407974353
resNode: customer_1 deliver_cap: 58.25806236810713 cap_limit: 40
7143 customer_5 ('customer_5', 'depot_t')
3835 customer_5 -21.48613407974353
resNode: depot_t deliver_cap: 39.56755002282449 cap_limit: 40
7144 customer_5 ('customer_5', 'customer_2')
3835 customer_5 -21.48613407974353
resNode: customer_2 deliver_cap: 43.9052733739214 cap_limit: 40
7145 customer_5 ('customer_5', 'customer_4')
3835 customer_5 -21.48613407974353
resNode: customer_4 deliver_cap: 67.8195205356868 cap_limit: 40
7146 customer_2 ('customer_2', 'customer_3')
3839 customer_2 -20.405090271718898
resNode: customer_3 deliver_cap: 68.05300165142329 cap_limit: 40
7147 customer_2 ('customer_2', 'customer_1')
3839 customer_2 -20.405090271718898
resNode: customer_1 deliver_cap: 56.35877746804648 cap_limit: 40
7148 customer_2 ('customer_2', 'depot_t')
3839 customer_2 -20.405090271718898
resNode: depot_t deliver_cap: 38.29773298289388 cap_limit: 40
7149 customer_2 ('customer_2', 'customer_4')
3839 customer_2 -20.405090271718898
resNode: customer_4 deliver_cap: 67.8195205356868 cap_limit: 40
7150 customer_2 ('customer_2', 'customer_5')
3839 customer_2 -20.405090271718898
resNode: customer_5 deliver_cap: 50.11889669557769 cap_limit: 40
7151 customer_2 ('customer_2', 'customer_3')
3843 customer_2 -16.720628786718713
resNode: customer_3 deliver_cap: 68.28648276715975 cap_limit: 40
7152 customer_2 ('customer_2', 'customer_1')
3843 customer_2 -16.720628786718713
resNode: customer_1 deliver_cap: 56.55539314445615 cap_limit: 40
7153 customer_2 ('customer_2', 'depot_t')
3843 customer_2 -16.720628786718713
resNode: depot_t deliver_cap: 38.48206017952795 cap_limit: 40
7154 customer_2 ('customer_2', 'customer_4')
3843 customer_2 -16.720628786718713
resNode: customer_4 deliver_cap: 68.05300165142329 cap_limit: 40
7155 customer_2 ('customer_2', 'customer_5')
3843 customer_2 -16.720628786718713
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
7156 customer_2 ('customer_2', 'customer_3')
3848 customer_2 -11.91915109957143
resNode: customer_3 deliver_cap: 56.754791361608184 cap_limit: 40
7157 customer_2 ('customer_2', 'customer_1')
3848 customer_2 -11.91915109957143
resNode: customer_1 deliver_cap: 45.3421945968048 cap_limit: 40
7158 customer_2 ('customer_2', 'depot_t')
3848 customer_2 -11.91915109957143
resNode: depot_t deliver_cap: 30.22343675925391 cap_limit: 40
7159 customer_2 ('customer_2', 'customer_4')
3848 customer_2 -11.91915109957143
resNode: customer_4 deliver_cap: 56.55817568519852 cap_limit: 40
7160 customer_2 ('customer_2', 'customer_5')
3848 customer_2 -11.91915109957143
resNode: customer_5 deliver_cap: 41.65238718826453 cap_limit: 40
7161 customer_5 ('customer_5', 'customer_3')
3850 customer_5 -20.64141130708469
resNode: customer_3 deliver_cap: 66.02466520753234 cap_limit: 40
7162 customer_5 ('customer_5', 'customer_1')
3850 customer_5 -20.64141130708469
resNode: customer_1 deliver_cap: 56.54998957325161 cap_limit: 40
7163 customer_5 ('customer_5', 'depot_t')
3850 customer_5 -20.64141130708469
resNode: depot_t deliver_cap: 37.96623177764743 cap_limit: 40
7164 customer_5 ('customer_5', 'customer_2')
3850 customer_5 -20.64141130708469
resNode: customer_2 deliver_cap: 42.19720057906587 cap_limit: 40
7165 customer_5 ('customer_5', 'customer_4')
3850 customer_5 -20.64141130708469
resNode: customer_4 deliver_cap: 65.79118409179587 cap_limit: 40
7166 customer_3 ('customer_3', 'customer_1')
3851 customer_3 -16.857772333909374
resNode: customer_1 deliver_cap: 54.771721940026374 cap_limit: 40
7167 customer_3 ('customer_3', 'depot_t')
3851 customer_3 -16.857772333909374
resNode: depot_t deliver_cap: 39.75187721945856 cap_limit: 40
7168 customer_3 ('customer_3', 'customer_2')
3851 customer_3 -16.857772333909374
resNode: customer_2 deliver_cap: 44.101889050331074 cap_limit: 40
7169 customer_3 ('customer_3', 'customer_4')
3851 customer_3 -16.857772333909374
resNode: customer_4 deliver_cap: 55.092711265410024 cap_limit: 40
7170 customer_3 ('customer_3', 'customer_5')
3851 customer_3 -16.857772333909374
resNode: customer_5 deliver_cap: 50.35237781131417 cap_limit: 40
7171 customer_1 ('customer_1', 'customer_3')
3852 customer_1 -11.31087011046164
resNode: customer_3 deliver_cap: 53.071835257117755 cap_limit: 40
7172 customer_1 ('customer_1', 'depot_t')
3852 customer_1 -11.31087011046164
resNode: depot_t deliver_cap: 31.089741728334367 cap_limit: 40
7173 customer_1 ('customer_1', 'customer_2')
3852 customer_1 -11.31087011046164
resNode: customer_2 deliver_cap: 33.6805535390289 cap_limit: 40
7174 customer_1 ('customer_1', 'customer_4')
3852 customer_1 -11.31087011046164
resNode: customer_4 deliver_cap: 52.578665894712856 cap_limit: 40
7175 customer_1 ('customer_1', 'customer_5')
3852 customer_1 -11.31087011046164
resNode: customer_5 deliver_cap: 41.652387188264534 cap_limit: 40
7176 customer_4 ('customer_4', 'customer_3')
3854 customer_4 -16.828075174451666
resNode: customer_3 deliver_cap: 55.092711265410024 cap_limit: 40
7177 customer_4 ('customer_4', 'customer_1')
3854 customer_4 -16.828075174451666
resNode: customer_1 deliver_cap: 54.27855257762147 cap_limit: 40
7178 customer_4 ('customer_4', 'depot_t')
3854 customer_4 -16.828075174451666
resNode: depot_t deliver_cap: 39.567550022824506 cap_limit: 40
7179 customer_4 ('customer_4', 'customer_2')
3854 customer_4 -16.828075174451666
resNode: customer_2 deliver_cap: 43.90527337392142 cap_limit: 40
7180 customer_4 ('customer_4', 'customer_5')
3854 customer_4 -16.828075174451666
resNode: customer_5 deliver_cap: 50.118896695577696 cap_limit: 40
7181 customer_5 ('customer_5', 'customer_3')
3855 customer_5 -14.665150912421945
resNode: customer_3 deliver_cap: 50.35237781131417 cap_limit: 40
7182 customer_5 ('customer_5', 'customer_1')
3855 customer_5 -14.665150912421945
resNode: customer_1 deliver_cap: 43.35227387117315 cap_limit: 40
7183 customer_5 ('customer_5', 'depot_t')
3855 customer_5 -14.665150912421945
resNode: depot_t deliver_cap: 25.593373306948884 cap_limit: 40
7184 customer_5 ('customer_5', 'customer_2')
3855 customer_5 -14.665150912421945
resNode: customer_2 deliver_cap: 28.999484876987424 cap_limit: 40
7185 customer_5 ('customer_5', 'customer_4')
3855 customer_5 -14.665150912421945

7223 customer_2 ('customer_2', 'depot_t')
3894 customer_2 -15.915053599443416
resNode: depot_t deliver_cap: 38.29773298289388 cap_limit: 40
7224 customer_2 ('customer_2', 'customer_4')
3894 customer_2 -15.915053599443416
resNode: customer_4 deliver_cap: 67.8195205356868 cap_limit: 40
7225 customer_2 ('customer_2', 'customer_5')
3894 customer_2 -15.915053599443416
resNode: customer_5 deliver_cap: 50.11889669557769 cap_limit: 40
7226 customer_1 ('customer_1', 'customer_3')
3897 customer_1 -15.768069328336102
resNode: customer_3 deliver_cap: 61.651154833449944 cap_limit: 40
7227 customer_1 ('customer_1', 'depot_t')
3897 customer_1 -15.768069328336102
resNode: depot_t deliver_cap: 37.77929594906739 cap_limit: 40
7228 customer_1 ('customer_1', 'customer_2')
3897 customer_1 -15.768069328336102
resNode: customer_2 deliver_cap: 40.297915679005214 cap_limit: 40
7229 customer_1 ('customer_1', 'customer_4')
3897 customer_1 -15.768069328336102
resNode: customer_4 deliver_cap: 61.06551621559413 cap_limit: 40
7230 customer_1 ('customer_1', 'customer_5')
3897 customer_1 -15.768069328336102
resNode: customer_5 deliver_cap: 48.090560251686746 cap_limit: 40
7231 customer_2 ('customer_2', 'customer_3')
3899 customer_2 -12.820517556355325
resNode: customer_3 deliver_cap: 50.35237781131417 cap_limit: 40
7232 customer_2 ('customer_2', 'customer_1')
3899 customer_2 -12.820517556355325
resNode: customer_1 deliver_cap: 41.45298897111249 cap_limit: 40
7233 customer_2 ('customer_2', 'depot_t')
3899 customer_2 -12.820517556355325
resNode: depot_t deliver_cap: 24.323556267018272 cap_limit: 40
7234 customer_2 ('customer_2', 'customer_4')
3899 customer_2 -12.820517556355325
resNode: customer_4 deliver_cap: 50.1188966955777 cap_limit: 40
7235 customer_2 ('customer_2', 'customer_5')
3899 customer_2 -12.820517556355325
resNode: customer_5 deliver_cap: 32.41827285546859 cap_limit: 40
7236 customer_1 ('customer_1', 'customer_3')
3917 customer_1 -8.611447615054118
resNode: customer_3 deliver_cap: 60.88392563105477 cap_limit: 40
7237 customer_1 ('customer_1', 'depot_t')
3917 customer_1 -8.611447615054118
resNode: depot_t deliver_cap: 36.94880950878713 cap_limit: 40
7238 customer_1 ('customer_1', 'customer_2')
3917 customer_1 -8.611447615054118
resNode: customer_2 deliver_cap: 40.02787696785273 cap_limit: 40
7239 customer_1 ('customer_1', 'customer_4')
3917 customer_1 -8.611447615054118
resNode: customer_4 deliver_cap: 60.39075626864987 cap_limit: 40
7240 customer_1 ('customer_1', 'customer_5')
3917 customer_1 -8.611447615054118
resNode: customer_5 deliver_cap: 49.464477562201544 cap_limit: 40
7241 customer_5 ('customer_5', 'customer_3')
3920 customer_5 -13.796687098405911
resNode: customer_3 deliver_cap: 59.62923513036438 cap_limit: 40
7242 customer_5 ('customer_5', 'customer_1')
3920 customer_5 -13.796687098405911
resNode: customer_1 deliver_cap: 51.164364245110164 cap_limit: 40
7243 customer_5 ('customer_5', 'depot_t')
3920 customer_5 -13.796687098405911
resNode: depot_t deliver_cap: 32.917208032514836 cap_limit: 40
7244 customer_5 ('customer_5', 'customer_2')
3920 customer_5 -13.796687098405911
resNode: customer_2 deliver_cap: 36.811575250924434 cap_limit: 40
7245 customer_5 ('customer_5', 'customer_4')
3920 customer_5 -13.796687098405911
resNode: customer_4 deliver_cap: 59.395754014627904 cap_limit: 40
7246 customer_2 ('customer_2', 'customer_3')
3929 customer_2 -13.754314720101949
resNode: customer_3 deliver_cap: 61.88463594918641 cap_limit: 40
7247 customer_2 ('customer_2', 'customer_1')
3929 customer_2 -13.754314720101949
resNode: customer_1 deliver_cap: 51.16436424511017 cap_limit: 40
7248 customer_2 ('customer_2', 'depot_t')
3929 customer_2 -13.754314720101949
resNode: depot_t deliver_cap: 33.42797058639109 cap_limit: 40
7249 customer_2 ('customer_2', 'customer_4')
3929 customer_2 -13.754314720101949
resNode: customer_4 deliver_cap: 61.651154833449944 cap_limit: 40
7250 customer_2 ('customer_2', 'customer_5')
3929 customer_2 -13.754314720101949
resNode: customer_5 deliver_cap: 43.95053099334082 cap_limit: 40
7251 customer_2 ('customer_2', 'customer_3')
3933 customer_2 -12.334020152554562
resNode: customer_3 deliver_cap: 68.51996388289622 cap_limit: 40
7252 customer_2 ('customer_2', 'customer_1')
3933 customer_2 -12.334020152554562
resNode: customer_1 deliver_cap: 56.752008820865804 cap_limit: 40
7253 customer_2 ('customer_2', 'depot_t')
3933 customer_2 -12.334020152554562
resNode: depot_t deliver_cap: 38.666387376162 cap_limit: 40
7254 customer_2 ('customer_2', 'customer_4')
3933 customer_2 -12.334020152554562
resNode: customer_4 deliver_cap: 68.28648276715975 cap_limit: 40
7255 customer_2 ('customer_2', 'customer_5')
3933 customer_2 -12.334020152554562
resNode: customer_5 deliver_cap: 50.58585892705063 cap_limit: 40
7256 customer_2 ('customer_2', 'customer_3')
3938 customer_2 -6.892934134979808
resNode: customer_3 deliver_cap: 55.052122137957184 cap_limit: 40
7257 customer_2 ('customer_2', 'customer_1')
3938 customer_2 -6.892934134979808
resNode: customer_1 deliver_cap: 43.95877585258837 cap_limit: 40
7258 customer_2 ('customer_2', 'depot_t')
3938 customer_2 -6.892934134979808
resNode: depot_t deliver_cap: 28.94643484151566 cap_limit: 40
7259 customer_2 ('customer_2', 'customer_4')
3938 customer_2 -6.892934134979808
resNode: customer_4 deliver_cap: 54.85550646154752 cap_limit: 40
7260 customer_2 ('customer_2', 'customer_5')
3938 customer_2 -6.892934134979808
resNode: customer_5 deliver_cap: 39.94971796461353 cap_limit: 40
7261 customer_5 ('customer_5', 'customer_3')
3940 customer_5 -15.216131243199868
resNode: customer_3 deliver_cap: 64.00274550444678 cap_limit: 40
7262 customer_5 ('customer_5', 'customer_1')
3940 customer_5 -15.216131243199868
resNode: customer_1 deliver_cap: 54.84732034960061 cap_limit: 40
7263 customer_5 ('customer_5', 'depot_t')
3940 customer_5 -15.216131243199868
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
7264 customer_5 ('customer_5', 'customer_2')
3940 customer_5 -15.216131243199868
resNode: customer_2 deliver_cap: 40.49453135541487 cap_limit: 40
7265 customer_5 ('customer_5', 'customer_4')
3940 customer_5 -15.216131243199868
resNode: customer_4 deliver_cap: 63.76926438871031 cap_limit: 40
7266 customer_2 ('customer_2', 'customer_3')
3944 customer_2 -12.292034513321251
resNode: customer_3 deliver_cap: 68.28648276715975 cap_limit: 40
7267 customer_2 ('customer_2', 'customer_1')
3944 customer_2 -12.292034513321251
resNode: customer_1 deliver_cap: 56.55539314445615 cap_limit: 40
7268 customer_2 ('customer_2', 'depot_t')
3944 customer_2 -12.292034513321251
resNode: depot_t deliver_cap: 38.48206017952795 cap_limit: 40
7269 customer_2 ('customer_2', 'customer_4')
3944 customer_2 -12.292034513321251
resNode: customer_4 deliver_cap: 68.05300165142329 cap_limit: 40
7270 customer_2 ('customer_2', 'customer_5')
3944 customer_2 -12.292034513321251
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
7271 customer_1 ('customer_1', 'customer_3')
3947 customer_1 -12.145050242213934
resNode: customer_3 deliver_cap: 61.88463594918642 cap_limit: 40
7272 customer_1 ('customer_1', 'depot_t')
3947 customer_1 -12.145050242213934
resNode: depot_t deliver_cap: 37.96362314570145 cap_limit: 40
7273 customer_1 ('customer_1', 'customer_2')
3947 customer_1 -12.145050242213934
resNode: customer_2 deliver_cap: 40.49453135541488 cap_limit: 40
7274 customer_1 ('customer_1', 'customer_4')
3947 customer_1 -12.145050242213934
resNode: customer_4 deliver_cap: 61.298997331330604 cap_limit: 40
7275 customer_1 ('customer_1', 'customer_5')
3947 customer_1 -12.145050242213934
resNode: customer_5 deliver_cap: 48.32404136742322 cap_limit: 40
7276 customer_2 ('customer_2', 'customer_3')
3949 customer_2 -9.197498470233157
resNode: customer_3 deliver_cap: 50.58585892705064 cap_limit: 40
7277 customer_2 ('customer_2', 'customer_1')
3949 customer_2 -9.197498470233157
resNode: customer_1 deliver_cap: 41.64960464752215 cap_limit: 40
7278 customer_2 ('customer_2', 'depot_t')
3949 customer_2 -9.197498470233157
resNode: depot_t deliver_cap: 24.50788346365233 cap_limit: 40
7279 customer_2 ('customer_2', 'customer_4')
3949 customer_2 -9.197498470233157
resNode: customer_4 deliver_cap: 50.35237781131416 cap_limit: 40
7280 customer_2 ('customer_2', 'customer_5')
3949 customer_2 -9.197498470233157
resNode: customer_5 deliver_cap: 32.65175397120505 cap_limit: 40
7281 customer_2 ('customer_2', 'customer_3')
3953 customer_2 -7.369499345121168
resNode: customer_3 deliver_cap: 65.62131816584983 cap_limit: 40
7282 customer_2 ('customer_2', 'customer_1')
3953 customer_2 -7.369499345121168
resNode: customer_1 deliver_cap: 55.54600318966131 cap_limit: 40
7283 customer_2 ('customer_2', 'depot_t')
3953 customer_2 -7.369499345121168
resNode: depot_t deliver_cap: 35.17618426549425 cap_limit: 40
7284 customer_2 ('customer_2', 'customer_4')
3953 customer_2 -7.369499345121168
resNode: customer_4 deliver_cap: 65.35097161078654 cap_limit: 40
7285 customer_2 ('customer_2', 'customer_5')
3953 customer_2 -7.369499345121168
resNode: customer_5 deliver_cap: 44.855512427502305 cap_limit: 40
7286 customer_5 ('customer_5', 'customer_3')
3955 customer_5 -12.895976787355986
resNode: customer_3 deliver_cap: 69.79724505865786 cap_limit: 40
7287 customer_5 ('customer_5', 'customer_1')
3955 customer_5 -12.895976787355986
resNode: customer_1 deliver_cap: 62.72819896927612 cap_limit: 40
7288 customer_5 ('customer_5', 'depot_t')
3955 customer_5 -12.895976787355986
resNode: depot_t deliver_cap: 38.80778037175906 cap_limit: 40
7289 customer_5 ('customer_5', 'customer_2')
3955 customer_5 -12.895976787355986
resNode: customer_2 deliver_cap: 42.993114102270745 cap_limit: 40
7290 customer_5 ('customer_5', 'customer_4')
3955 customer_5 -12.895976787355986
resNode: customer_4 deliver_cap: 69.49003306426778 cap_limit: 40
7291 customer_2 ('customer_2', 'customer_3')
3958 customer_2 -7.317083581534678
resNode: customer_3 deliver_cap: 64.01741108234089 cap_limit: 40
7292 customer_2 ('customer_2', 'customer_1')
3958 customer_2 -7.317083581534678
resNode: customer_1 deliver_cap: 52.96038540987183 cap_limit: 40
7293 customer_2 ('customer_2', 'depot_t')
3958 customer_2 -7.317083581534678
resNode: depot_t deliver_cap: 35.11174042835515 cap_limit: 40
7294 customer_2 ('customer_2', 'customer_4')
3958 customer_2 -7.317083581534678
resNode: customer_4 deliver_cap: 63.78392996660441 cap_limit: 40
7295 customer_2 ('customer_2', 'customer_5')
3958 customer_2 -7.317083581534678
resNode: customer_5 deliver_cap: 46.083306126495295 cap_limit: 40
7296 customer_1 ('customer_1', 'customer_3')
3962 customer_1 -8.193082983948207
resNode: customer_3 deliver_cap: 64.36956858446024 cap_limit: 40
7297 customer_1 ('customer_1', 'depot_t')
3962 customer_1 -8.193082983948207
resNode: depot_t deliver_cap: 39.925412068286036 cap_limit: 40
7298 customer_1 ('customer_1', 'customer_2')
3962 customer_1 -8.193082983948207
resNode: customer_2 deliver_cap: 42.587106206171775 cap_limit: 40
7299 customer_1 ('customer_1', 'customer_4')
3962 customer_1 -8.193082983948207
resNode: customer_4 deliver_cap: 63.78392996660441 cap_limit: 40
7300 customer_1 ('customer_1', 'customer_5')
3962 customer_1 -8.193082983948207
resNode: customer_5 deliver_cap: 50.80897400269703 cap_limit: 40
7301 customer_5 ('customer_5', 'customer_3')
3965 customer_5 -11.149732320202077
resNode: customer_3 deliver_cap: 59.862164453412404 cap_limit: 40
7302 customer_5 ('customer_5', 'customer_1')
3965 customer_5 -11.149732320202077
resNode: customer_1 deliver_cap: 52.82758943865101 cap_limit: 40
7303 customer_5 ('customer_5', 'depot_t')
3965 customer_5 -11.149732320202077
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
7304 customer_5 ('customer_5', 'customer_2')
3965 customer_5 -11.149732320202077
resNode: customer_2 deliver_cap: 35.78365250805547 cap_limit: 40
7305 customer_5 ('customer_5', 'customer_4')
3965 customer_5 -11.149732320202077
resNode: customer_4 deliver_cap: 59.59181789834911 cap_limit: 40
7306 customer_2 ('customer_2', 'customer_3')
3969 customer_2 -10.005197660180912
resNode: customer_3 deliver_cap: 59.862164453412404 cap_limit: 40
7307 customer_2 ('customer_2', 'customer_1')
3969 customer_2 -10.005197660180912
resNode: customer_1 deliver_cap: 50.572188619828985 cap_limit: 40
7308 customer_2 ('customer_2', 'depot_t')
3969 customer_2 -10.005197660180912
resNode: depot_t deliver_cap: 30.464149409863623 cap_limit: 40
7309 customer_2 ('customer_2', 'customer_4')
3969 customer_2 -10.005197660180912
resNode: customer_4 deliver_cap: 59.59181789834911 cap_limit: 40
7310 customer_2 ('customer_2', 'customer_5')
3969 customer_2 -10.005197660180912
resNode: customer_5 deliver_cap: 39.09635871506488 cap_limit: 40
7311 customer_2 ('customer_2', 'customer_3')
3978 customer_2 -11.3717474180087
resNode: customer_3 deliver_cap: 64.00274550444676 cap_limit: 40
7312 customer_2 ('customer_2', 'customer_1')
3978 customer_2 -11.3717474180087
resNode: customer_1 deliver_cap: 52.948035449539944 cap_limit: 40
7313 customer_2 ('customer_2', 'depot_t')
3978 customer_2 -11.3717474180087
resNode: depot_t deliver_cap: 35.100162340544 cap_limit: 40
7314 customer_2 ('customer_2', 'customer_4')
3978 customer_2 -11.3717474180087
resNode: customer_4 deliver_cap: 63.76926438871029 cap_limit: 40
7315 customer_2 ('customer_2', 'customer_5')
3978 customer_2 -11.3717474180087
resNode: customer_5 deliver_cap: 46.068640548601174 cap_limit: 40
7316 customer_1 ('customer_1', 'customer_3')
3982 customer_1 -10.817610489466439
resNode: customer_3 deliver_cap: 59.62923513036438 cap_limit: 40
7317 customer_1 ('customer_1', 'depot_t')
3982 customer_1 -10.817610489466439
resNode: depot_t deliver_cap: 36.18304355189458 cap_limit: 40
7318 customer_1 ('customer_1', 'customer_2')
3982 customer_1 -10.817610489466439
resNode: customer_2 deliver_cap: 38.595246455354214 cap_limit: 40
7319 customer_1 ('customer_1', 'customer_4')
3982 customer_1 -10.817610489466439
resNode: customer_4 deliver_cap: 59.043596512508564 cap_limit: 40
7320 customer_1 ('customer_1', 'customer_5')
3982 customer_1 -10.817610489466439
resNode: customer_5 deliver_cap: 46.06864054860118 cap_limit: 40
7321 customer_5 ('customer_5', 'customer_3')
3985 customer_5 -12.838667696622444
resNode: customer_3 deliver_cap: 54.37335729603826 cap_limit: 40
7322 customer_5 ('customer_5', 'customer_1')
3985 customer_5 -12.838667696622444
resNode: customer_1 deliver_cap: 48.08725598455517 cap_limit: 40
7323 customer_5 ('customer_5', 'depot_t')
3985 customer_5 -12.838667696622444
resNode: depot_t deliver_cap: 27.4970876381106 cap_limit: 40
7324 customer_5 ('customer_5', 'customer_2')
3985 customer_5 -12.838667696622444
resNode: customer_2 deliver_cap: 31.043319053959614 cap_limit: 40
7325 customer_5 ('customer_5', 'customer_4')
3985 customer_5 -12.838667696622444
resNode: customer_4 deliver_cap: 54.10301074097498 cap_limit: 40
7326 customer_2 ('customer_2', 'customer_3')
3993 customer_2 -11.090895295915267
resNode: customer_3 deliver_cap: 62.78321053111544 cap_limit: 40
7327 customer_2 ('customer_2', 'customer_1')
3993 customer_2 -11.090895295915267
resNode: customer_1 deliver_cap: 50.240285172029445 cap_limit: 40
7328 customer_2 ('customer_2', 'depot_t')
3993 customer_2 -11.090895295915267
resNode: depot_t deliver_cap: 34.74475113638435 cap_limit: 40
7329 customer_2 ('customer_2', 'customer_4')
3993 customer_2 -11.090895295915267
resNode: customer_4 deliver_cap: 62.58659485470578 cap_limit: 40
7330 customer_2 ('customer_2', 'customer_5')
3993 customer_2 -11.090895295915267
resNode: customer_5 deliver_cap: 47.68080635777178 cap_limit: 40
7331 customer_1 ('customer_1', 'customer_3')
3997 customer_1 -11.633538089458737
resNode: customer_3 deliver_cap: 62.78321053111544 cap_limit: 40
7332 customer_1 ('customer_1', 'depot_t')
3997 customer_1 -11.633538089458737
resNode: depot_t deliver_cap: 38.37327318383263 cap_limit: 40
7333 customer_1 ('customer_1', 'customer_2')
3997 customer_1 -11.633538089458737
resNode: customer_2 deliver_cap: 41.571045949152015 cap_limit: 40
7334 customer_1 ('customer_1', 'customer_4')
3997 customer_1 -11.633538089458737
resNode: customer_4 deliver_cap: 62.29004116871053 cap_limit: 40
7335 customer_1 ('customer_1', 'customer_5')
3997 customer_1 -11.633538089458737
resNode: customer_5 deliver_cap: 51.36376246226221 cap_limit: 40
7336 customer_5 ('customer_5', 'customer_3')
4000 customer_5 -17.26392247126224
resNode: customer_3 deliver_cap: 61.88463594918641 cap_limit: 40
7337 customer_5 ('customer_5', 'customer_1')
4000 customer_5 -17.26392247126224
resNode: customer_1 deliver_cap: 53.06364914517083 cap_limit: 40
7338 customer_5 ('customer_5', 'depot_t')
4000 customer_5 -17.26392247126224
resNode: depot_t deliver_cap: 34.6977876263217 cap_limit: 40
7339 customer_5 ('customer_5', 'customer_2')
4000 customer_5 -17.26392247126224
resNode: customer_2 deliver_cap: 38.71086015098509 cap_limit: 40
7340 customer_5 ('customer_5', 'customer_4')
4000 customer_5 -17.26392247126224
resNode: customer_4 deliver_cap: 61.651154833449944 cap_limit: 40
7341 customer_2 ('customer_2', 'customer_3')
4004 customer_2 -13.308859923293278
resNode: customer_3 deliver_cap: 66.62496940328226 cap_limit: 40
7342 customer_2 ('customer_2', 'customer_1')
4004 customer_2 -13.308859923293278
resNode: customer_1 deliver_cap: 55.15622399592773 cap_limit: 40
7343 customer_2 ('customer_2', 'depot_t')
4004 customer_2 -13.308859923293278
resNode: depot_t deliver_cap: 37.170339102782556 cap_limit: 40
7344 customer_2 ('customer_2', 'customer_4')
4004 customer_2 -13.308859923293278
resNode: customer_4 deliver_cap: 66.39148828754578 cap_limit: 40
7345 customer_2 ('customer_2', 'customer_5')
4004 customer_2 -13.308859923293278
resNode: customer_5 deliver_cap: 48.690864447436674 cap_limit: 40
7346 customer_2 ('customer_2', 'customer_3')
4009 customer_2 -16.18287866323761
resNode: customer_3 deliver_cap: 61.88463594918641 cap_limit: 40
7347 customer_2 ('customer_2', 'customer_1')
4009 customer_2 -16.18287866323761
resNode: customer_1 deliver_cap: 51.16436424511017 cap_limit: 40
7348 customer_2 ('customer_2', 'depot_t')
4009 customer_2 -16.18287866323761
resNode: depot_t deliver_cap: 33.42797058639109 cap_limit: 40
7349 customer_2 ('customer_2', 'customer_4')
4009 customer_2 -16.18287866323761
resNode: customer_4 deliver_cap: 61.651154833449944 cap_limit: 40
7350 customer_2 ('customer_2', 'customer_5')
4009 customer_2 -16.18287866323761
resNode: customer_5 deliver_cap: 43.95053099334082 cap_limit: 40
7351 customer_1 ('customer_1', 'customer_3')
4011 customer_1 -12.010624628051046
resNode: customer_3 deliver_cap: 62.78321053111544 cap_limit: 40
7352 customer_1 ('customer_1', 'depot_t')
4011 customer_1 -12.010624628051046
resNode: depot_t deliver_cap: 38.37327318383263 cap_limit: 40
7353 customer_1 ('customer_1', 'customer_2')
4011 customer_1 -12.010624628051046
resNode: customer_2 deliver_cap: 41.571045949152015 cap_limit: 40
7354 customer_1 ('customer_1', 'customer_4')
4011 customer_1 -12.010624628051046
resNode: customer_4 deliver_cap: 62.29004116871053 cap_limit: 40
7355 customer_1 ('customer_1', 'customer_5')
4011 customer_1 -12.010624628051046
resNode: customer_5 deliver_cap: 51.36376246226221 cap_limit: 40
7356 customer_2 ('customer_2', 'customer_3')
4013 customer_2 -10.656598866295333
resNode: customer_3 deliver_cap: 56.95140703801784 cap_limit: 40
7357 customer_2 ('customer_2', 'customer_1')
4013 customer_2 -10.656598866295333
resNode: customer_1 deliver_cap: 45.50194483388765 cap_limit: 40
7358 customer_2 ('customer_2', 'depot_t')
4013 customer_2 -10.656598866295333
resNode: depot_t deliver_cap: 30.370898516561155 cap_limit: 40
7359 customer_2 ('customer_2', 'customer_4')
4013 customer_2 -10.656598866295333
resNode: customer_4 deliver_cap: 56.754791361608184 cap_limit: 40
7360 customer_2 ('customer_2', 'customer_5')
4013 customer_2 -10.656598866295333
resNode: customer_5 deliver_cap: 41.84900286467418 cap_limit: 40

resNode: customer_1 deliver_cap: 54.85967030993249 cap_limit: 40
7423 customer_2 ('customer_2', 'depot_t')
4033 customer_2 -13.023389785663404
resNode: depot_t deliver_cap: 36.89232002216202 cap_limit: 40
7424 customer_2 ('customer_2', 'customer_4')
4033 customer_2 -13.023389785663404
resNode: customer_4 deliver_cap: 66.03933078542644 cap_limit: 40
7425 customer_2 ('customer_2', 'customer_5')
4033 customer_2 -13.023389785663404
resNode: customer_5 deliver_cap: 48.33870694531732 cap_limit: 40
7426 customer_2 ('customer_2', 'customer_3')
4038 customer_2 -10.786353061492214
resNode: customer_3 deliver_cap: 61.99348748271529 cap_limit: 40
7427 customer_2 ('customer_2', 'customer_1')
4038 customer_2 -10.786353061492214
resNode: customer_1 deliver_cap: 49.598635195204324 cap_limit: 40
7428 customer_2 ('customer_2', 'depot_t')
4038 customer_2 -10.786353061492214
resNode: depot_t deliver_cap: 34.15245885008424 cap_limit: 40
7429 customer_2 ('customer_2', 'customer_4')
4038 customer_2 -10.786353061492214
resNode: customer_4 deliver_cap: 61.79687180630563 cap_limit: 40
7430 customer_2 ('customer_2', 'customer_5')
4038 customer_2 -10.786353061492214
resNode: customer_5 deliver_cap: 46.89108330937163 cap_limit: 40
7431 customer_1 ('customer_1', 'customer_3')
4042 customer_1 -11.421668881909198
resNode: customer_3 deliver_cap: 62.29004116871053 cap_limit: 40
7432 customer_1 ('customer_1', 'depot_t')
4042 customer_1 -11.421668881909198
resNode: depot_t deliver_cap: 38.00339616202895 cap_limit: 40
7433 customer_1 ('customer_1', 'customer_2')
4042 customer_1 -11.421668881909198
resNode: customer_2 deliver_cap: 41.17034584219803 cap_limit: 40
7434 customer_1 ('customer_1', 'customer_4')
4042 customer_1 -11.421668881909198
resNode: customer_4 deliver_cap: 61.79687180630563 cap_limit: 40
7435 customer_1 ('customer_1', 'customer_5')
4042 customer_1 -11.421668881909198
resNode: customer_5 deliver_cap: 50.87059309985731 cap_limit: 40
7436 customer_5 ('customer_5', 'customer_3')
4045 customer_5 -16.93646669439906
resNode: customer_3 deliver_cap: 61.29899733133058 cap_limit: 40
7437 customer_5 ('customer_5', 'customer_1')
4045 customer_5 -16.93646669439906
resNode: customer_1 deliver_cap: 52.570479782765915 cap_limit: 40
7438 customer_5 ('customer_5', 'depot_t')
4045 customer_5 -16.93646669439906
resNode: depot_t deliver_cap: 34.2354413490671 cap_limit: 40
7439 customer_5 ('customer_5', 'customer_2')
4045 customer_5 -16.93646669439906
resNode: customer_2 deliver_cap: 38.217690788580185 cap_limit: 40
7440 customer_5 ('customer_5', 'customer_4')
4045 customer_5 -16.93646669439906
resNode: customer_4 deliver_cap: 61.06551621559411 cap_limit: 40
7441 customer_2 ('customer_2', 'customer_3')
4049 customer_2 -15.855422886374425
resNode: customer_3 deliver_cap: 61.29899733133058 cap_limit: 40
7442 customer_2 ('customer_2', 'customer_1')
4049 customer_2 -15.855422886374425
resNode: customer_1 deliver_cap: 50.671194882705265 cap_limit: 40
7443 customer_2 ('customer_2', 'depot_t')
4049 customer_2 -15.855422886374425
resNode: depot_t deliver_cap: 32.965624309136494 cap_limit: 40
7444 customer_2 ('customer_2', 'customer_4')
4049 customer_2 -15.855422886374425
resNode: customer_4 deliver_cap: 61.06551621559411 cap_limit: 40
7445 customer_2 ('customer_2', 'customer_5')
4049 customer_2 -15.855422886374425
resNode: customer_5 deliver_cap: 43.36489237548499 cap_limit: 40
7446 customer_2 ('customer_2', 'customer_3')
4053 customer_2 -15.342133265667515
resNode: customer_3 deliver_cap: 66.2581463232688 cap_limit: 40
7447 customer_2 ('customer_2', 'customer_1')
4053 customer_2 -15.342133265667515
resNode: customer_1 deliver_cap: 54.84732034960061 cap_limit: 40
7448 customer_2 ('customer_2', 'depot_t')
4053 customer_2 -15.342133265667515
resNode: depot_t deliver_cap: 36.88074193435088 cap_limit: 40
7449 customer_2 ('customer_2', 'customer_4')
4053 customer_2 -15.342133265667515
resNode: customer_4 deliver_cap: 66.02466520753234 cap_limit: 40
7450 customer_2 ('customer_2', 'customer_5')
4053 customer_2 -15.342133265667515
resNode: customer_5 deliver_cap: 48.32404136742321 cap_limit: 40
7451 customer_2 ('customer_2', 'customer_3')
4058 customer_2 -10.940985139814497
resNode: customer_3 deliver_cap: 55.046718566752645 cap_limit: 40
7452 customer_2 ('customer_2', 'customer_1')
4058 customer_2 -10.940985139814497
resNode: customer_1 deliver_cap: 43.954385450984674 cap_limit: 40
7453 customer_2 ('customer_2', 'depot_t')
4058 customer_2 -10.940985139814497
resNode: depot_t deliver_cap: 28.942382163112256 cap_limit: 40
7454 customer_2 ('customer_2', 'customer_4')
4058 customer_2 -10.940985139814497
resNode: customer_4 deliver_cap: 54.85010289034298 cap_limit: 40
7455 customer_2 ('customer_2', 'customer_5')
4058 customer_2 -10.940985139814497
resNode: customer_5 deliver_cap: 39.94431439340899 cap_limit: 40
7456 customer_5 ('customer_5', 'customer_3')
4060 customer_5 -19.262915786033492
resNode: customer_3 deliver_cap: 63.99632876364139 cap_limit: 40
7457 customer_5 ('customer_5', 'customer_1')
4060 customer_5 -19.262915786033492
resNode: customer_1 deliver_cap: 54.84191677839607 cap_limit: 40
7458 customer_5 ('customer_5', 'depot_t')
4060 customer_5 -19.262915786033492
resNode: depot_t deliver_cap: 36.36491353247036 cap_limit: 40
7459 customer_5 ('customer_5', 'customer_2')
4060 customer_5 -19.262915786033492
resNode: customer_2 deliver_cap: 40.48912778421033 cap_limit: 40
7460 customer_5 ('customer_5', 'customer_4')
4060 customer_5 -19.262915786033492
resNode: customer_4 deliver_cap: 63.76284764790492 cap_limit: 40
7461 customer_3 ('customer_3', 'customer_1')
4061 customer_3 -15.47927681285817
resNode: customer_1 deliver_cap: 53.063649145170835 cap_limit: 40
7462 customer_3 ('customer_3', 'depot_t')
4061 customer_3 -15.47927681285817
resNode: depot_t deliver_cap: 38.15055897428149 cap_limit: 40
7463 customer_3 ('customer_3', 'customer_2')
4061 customer_3 -15.47927681285817
resNode: customer_2 deliver_cap: 42.393816255475535 cap_limit: 40
7464 customer_3 ('customer_3', 'customer_4')
4061 customer_3 -15.47927681285817
resNode: customer_4 deliver_cap: 53.064374821519074 cap_limit: 40
7465 customer_3 ('customer_3', 'customer_5')
4061 customer_3 -15.47927681285817
resNode: customer_5 deliver_cap: 48.32404136742322 cap_limit: 40
7466 customer_1 ('customer_1', 'customer_3')
4062 customer_1 -10.332704150704707
resNode: customer_3 deliver_cap: 51.363762462262216 cap_limit: 40
7467 customer_1 ('customer_1', 'depot_t')
4062 customer_1 -10.332704150704707
resNode: depot_t deliver_cap: 29.808687132192713 cap_limit: 40
7468 customer_1 ('customer_1', 'customer_2')
4062 customer_1 -10.332704150704707
resNode: customer_2 deliver_cap: 32.29274439320877 cap_limit: 40
7469 customer_1 ('customer_1', 'customer_4')
4062 customer_1 -10.332704150704707
resNode: customer_4 deliver_cap: 50.87059309985732 cap_limit: 40
7470 customer_1 ('customer_1', 'customer_5')
4062 customer_1 -10.332704150704707
resNode: customer_5 deliver_cap: 39.944314393408995 cap_limit: 40
7471 customer_4 ('customer_4', 'customer_3')
4064 customer_4 -15.449579653400463
resNode: customer_3 deliver_cap: 53.064374821519074 cap_limit: 40
7472 customer_4 ('customer_4', 'customer_1')
4064 customer_4 -15.449579653400463
resNode: customer_1 deliver_cap: 52.57047978276593 cap_limit: 40
7473 customer_4 ('customer_4', 'depot_t')
4064 customer_4 -15.449579653400463
resNode: depot_t deliver_cap: 37.96623177764744 cap_limit: 40
7474 customer_4 ('customer_4', 'customer_2')
4064 customer_4 -15.449579653400463
resNode: customer_2 deliver_cap: 42.19720057906588 cap_limit: 40
7475 customer_4 ('customer_4', 'customer_5')
4064 customer_4 -15.449579653400463
resNode: customer_5 deliver_cap: 48.090560251686746 cap_limit: 40
7476 customer_5 ('customer_5', 'customer_3')
4065 customer_5 -13.286655391370743
resNode: customer_3 deliver_cap: 48.32404136742322 cap_limit: 40
7477 customer_5 ('customer_5', 'customer_1')
4065 customer_5 -13.286655391370743
resNode: customer_1 deliver_cap: 41.644201076317614 cap_limit: 40
7478 customer_5 ('customer_5', 'depot_t')
4065 customer_5 -13.286655391370743
resNode: depot_t deliver_cap: 23.992055061771815 cap_limit: 40
7479 customer_5 ('customer_5', 'customer_2')
4065 customer_5 -13.286655391370743
resNode: customer_2 deliver_cap: 27.291412082131885 cap_limit: 40
7480 customer_5 ('customer_5', 'customer_4')
4065 customer_5 -13.286655391370743
resNode: customer_4 deliver_cap: 48.09056025168675 cap_limit: 40
7481 customer_2 ('customer_2', 'customer_3')
4069 customer_2 -15.300147626434201
resNode: customer_3 deliver_cap: 66.02466520753234 cap_limit: 40
7482 customer_2 ('customer_2', 'customer_1')
4069 customer_2 -15.300147626434201
resNode: customer_1 deliver_cap: 54.650704673190944 cap_limit: 40
7483 customer_2 ('customer_2', 'depot_t')
4069 customer_2 -15.300147626434201
resNode: depot_t deliver_cap: 36.69641473771682 cap_limit: 40
7484 customer_2 ('customer_2', 'customer_4')
4069 customer_2 -15.300147626434201
resNode: customer_4 deliver_cap: 65.79118409179586 cap_limit: 40
7485 customer_2 ('customer_2', 'customer_5')
4069 customer_2 -15.300147626434201
resNode: customer_5 deliver_cap: 48.09056025168674 cap_limit: 40
7486 customer_2 ('customer_2', 'customer_3')
4073 customer_2 -6.155226170803506
resNode: customer_3 deliver_cap: 53.26845093352741 cap_limit: 40
7487 customer_2 ('customer_2', 'customer_1')
4073 customer_2 -6.155226170803506
resNode: customer_1 deliver_cap: 42.509542998989176 cap_limit: 40
7488 customer_2 ('customer_2', 'depot_t')
4073 customer_2 -6.155226170803506
resNode: depot_t deliver_cap: 27.60868143819333 cap_limit: 40
7489 customer_2 ('customer_2', 'customer_4')
4073 customer_2 -6.155226170803506
resNode: customer_4 deliver_cap: 53.071835257117755 cap_limit: 40
7490 customer_2 ('customer_2', 'customer_5')
4073 customer_2 -6.155226170803506
resNode: customer_5 deliver_cap: 38.166046760183754 cap_limit: 40
7491 customer_5 ('customer_5', 'customer_3')
4075 customer_5 -14.060375340485333
resNode: customer_3 deliver_cap: 61.88463594918641 cap_limit: 40
7492 customer_5 ('customer_5', 'customer_1')
4075 customer_5 -14.060375340485333
resNode: customer_1 deliver_cap: 53.06364914517083 cap_limit: 40
7493 customer_5 ('customer_5', 'depot_t')
4075 customer_5 -14.060375340485333
resNode: depot_t deliver_cap: 34.6977876263217 cap_limit: 40
7494 customer_5 ('customer_5', 'customer_2')
4075 customer_5 -14.060375340485333
resNode: customer_2 deliver_cap: 38.71086015098509 cap_limit: 40
7495 customer_5 ('customer_5', 'customer_4')
4075 customer_5 -14.060375340485333
resNode: customer_4 deliver_cap: 61.651154833449944 cap_limit: 40
7496 customer_3 ('customer_3', 'customer_1')
4076 customer_3 -12.290852986953222
resNode: customer_1 deliver_cap: 54.96833761643603 cap_limit: 40
7497 customer_3 ('customer_3', 'depot_t')
4076 customer_3 -12.290852986953222
resNode: depot_t deliver_cap: 39.93620441609261 cap_limit: 40
7498 customer_3 ('customer_3', 'customer_2')
4076 customer_3 -12.290852986953222
resNode: customer_2 deliver_cap: 44.29850472674073 cap_limit: 40
7499 customer_3 ('customer_3', 'customer_4')
4076 customer_3 -12.290852986953222
resNode: customer_4 deliver_cap: 55.326192381146484 cap_limit: 40
7500 customer_3 ('customer_3', 'customer_5')
4076 customer_3 -12.290852986953222
resNode: customer_5 deliver_cap: 50.58585892705064 cap_limit: 40
7501 customer_1 ('customer_1', 'customer_3')
4077 customer_1 -6.69786896434698
resNode: customer_3 deliver_cap: 53.26845093352741 cap_limit: 40
7502 customer_1 ('customer_1', 'depot_t')
4077 customer_1 -6.69786896434698
resNode: depot_t deliver_cap: 31.237203485641615 cap_limit: 40
7503 customer_1 ('customer_1', 'customer_2')
4077 customer_1 -6.69786896434698
resNode: customer_2 deliver_cap: 33.840303776111746 cap_limit: 40
7504 customer_1 ('customer_1', 'customer_4')
4077 customer_1 -6.69786896434698
resNode: customer_4 deliver_cap: 52.775281571122505 cap_limit: 40
7505 customer_1 ('customer_1', 'customer_5')
4077 customer_1 -6.69786896434698
resNode: customer_5 deliver_cap: 41.84900286467419 cap_limit: 40
7506 customer_4 ('customer_4', 'customer_3')
4079 customer_4 -12.261155827495514
resNode: customer_3 deliver_cap: 55.326192381146484 cap_limit: 40
7507 customer_4 ('customer_4', 'customer_1')
4079 customer_4 -12.261155827495514
resNode: customer_1 deliver_cap: 54.475168254031125 cap_limit: 40
7508 customer_4 ('customer_4', 'depot_t')
4079 customer_4 -12.261155827495514
resNode: depot_t deliver_cap: 39.75187721945855 cap_limit: 40
7509 customer_4 ('customer_4', 'customer_2')
4079 customer_4 -12.261155827495514
resNode: customer_2 deliver_cap: 44.10188905033107 cap_limit: 40
7510 customer_4 ('customer_4', 'customer_5')
4079 customer_4 -12.261155827495514
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
7511 customer_5 ('customer_5', 'customer_3')
4080 customer_5 -10.098231565465799
resNode: customer_3 deliver_cap: 50.58585892705064 cap_limit: 40
7512 customer_5 ('customer_5', 'customer_1')
4080 customer_5 -10.098231565465799
resNode: customer_1 deliver_cap: 43.54888954758281 cap_limit: 40
7513 customer_5 ('customer_5', 'depot_t')
4080 customer_5 -10.098231565465799
resNode: depot_t deliver_cap: 25.77770050358294 cap_limit: 40
7514 customer_5 ('customer_5', 'customer_2')
4080 customer_5 -10.098231565465799
resNode: customer_2 deliver_cap: 29.196100553397084 cap_limit: 40
7515 customer_5 ('customer_5', 'customer_4')
4080 customer_5 -10.098231565465799
resNode: customer_4 deliver_cap: 50.35237781131416 cap_limit: 40
7516 customer_3 ('customer_3', 'customer_1')
4081 customer_3 -8.586041891764523
resNode: customer_1 deliver_cap: 53.427893634400945 cap_limit: 40
7517 customer_3 ('customer_3', 'depot_t')
4081 customer_3 -8.586041891764523
resNode: depot_t deliver_cap: 36.69996471341098 cap_limit: 40
7518 customer_3 ('customer_3', 'customer_2')
4081 customer_3 -8.586041891764523
resNode: customer_2 deliver_cap: 40.75746707788779 cap_limit: 40
7519 customer_3 ('customer_3', 'customer_4')
4081 customer_3 -8.586041891764523
resNode: customer_4 deliver_cap: 50.34431958487645 cap_limit: 40
7520 customer_3 ('customer_3', 'customer_5')
4081 customer_3 -8.586041891764523
resNode: customer_5 deliver_cap: 44.8555124275023 cap_limit: 40
7521 customer_1 ('customer_1', 'customer_3')
4082 customer_1 -7.90930382042717
resNode: customer_3 deliver_cap: 61.89930152708053 cap_limit: 40
7522 customer_1 ('customer_1', 'depot_t')
4082 customer_1 -7.90930382042717
resNode: depot_t deliver_cap: 37.975201233512585 cap_limit: 40
7523 customer_1 ('customer_1', 'customer_2')
4082 customer_1 -7.90930382042717
resNode: customer_2 deliver_cap: 40.50688131574676 cap_limit: 40
7524 customer_1 ('customer_1', 'customer_4')
4082 customer_1 -7.90930382042717
resNode: customer_4 deliver_cap: 61.3136629092247 cap_limit: 40
7525 customer_1 ('customer_1', 'customer_5')
4082 customer_1 -7.90930382042717
resNode: customer_5 deliver_cap: 48.33870694531732 cap_limit: 40
7526 customer_2 ('customer_2', 'customer_3')
4084 customer_2 -6.14316901749683
resNode: customer_3 deliver_cap: 55.32619238114649 cap_limit: 40
7527 customer_2 ('customer_2', 'customer_1')
4084 customer_2 -6.14316901749683
resNode: customer_1 deliver_cap: 45.64146439833971 cap_limit: 40
7528 customer_2 ('customer_2', 'depot_t')
4084 customer_2 -6.14316901749683
resNode: depot_t deliver_cap: 28.25025198004379 cap_limit: 40
7529 customer_2 ('customer_2', 'customer_4')
4084 customer_2 -6.14316901749683
resNode: customer_4 deliver_cap: 55.092711265410024 cap_limit: 40
7530 customer_2 ('customer_2', 'customer_5')
4084 customer_2 -6.14316901749683
resNode: customer_5 deliver_cap: 37.39208742530091 cap_limit: 40
7531 customer_5 ('customer_5', 'customer_3')
4085 customer_5 -11.483519921025966
resNode: customer_3 deliver_cap: 59.862164453412404 cap_limit: 40
7532 customer_5 ('customer_5', 'customer_1')
4085 customer_5 -11.483519921025966
resNode: customer_1 deliver_cap: 52.82758943865101 cap_limit: 40
7533 customer_5 ('customer_5', 'depot_t')
4085 customer_5 -11.483519921025966
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
7534 customer_5 ('customer_5', 'customer_2')
4085 customer_5 -11.483519921025966
resNode: customer_2 deliver_cap: 35.78365250805547 cap_limit: 40
7535 customer_5 ('customer_5', 'customer_4')
4085 customer_5 -11.483519921025966
resNode: customer_4 deliver_cap: 59.59181789834911 cap_limit: 40
7536 customer_1 ('customer_1', 'customer_3')
4087 customer_1 -11.964739529421937
resNode: customer_3 deliver_cap: 61.88463594918641 cap_limit: 40
7537 customer_1 ('customer_1', 'depot_t')
4087 customer_1 -11.964739529421937
resNode: depot_t deliver_cap: 37.96362314570145 cap_limit: 40
7538 customer_1 ('customer_1', 'customer_2')
4087 customer_1 -11.964739529421937
resNode: customer_2 deliver_cap: 40.49453135541487 cap_limit: 40
7539 customer_1 ('customer_1', 'customer_4')
4087 customer_1 -11.964739529421937
resNode: customer_4 deliver_cap: 61.29899733133058 cap_limit: 40
7540 customer_1 ('customer_1', 'customer_5')
4087 customer_1 -11.964739529421937
resNode: customer_5 deliver_cap: 48.32404136742321 cap_limit: 40
7541 customer_2 ('customer_2', 'customer_3')
4089 customer_2 -9.01718775744116
resNode: customer_3 deliver_cap: 50.58585892705064 cap_limit: 40
7542 customer_2 ('customer_2', 'customer_1')
4089 customer_2 -9.01718775744116
resNode: customer_1 deliver_cap: 41.649604647522146 cap_limit: 40
7543 customer_2 ('customer_2', 'depot_t')
4089 customer_2 -9.01718775744116
resNode: depot_t deliver_cap: 24.507883463652327 cap_limit: 40
7544 customer_2 ('customer_2', 'customer_4')
4089 customer_2 -9.01718775744116
resNode: customer_4 deliver_cap: 50.35237781131416 cap_limit: 40
7545 customer_2 ('customer_2', 'customer_5')
4089 customer_2 -9.01718775744116
resNode: customer_5 deliver_cap: 32.65175397120505 cap_limit: 40
7546 customer_1 ('customer_1', 'customer_3')
4091 customer_1 -9.344289344425928
resNode: customer_3 deliver_cap: 59.100254426625 cap_limit: 40
7547 customer_1 ('customer_1', 'depot_t')
4091 customer_1 -9.344289344425928
resNode: depot_t deliver_cap: 35.6110561054648 cap_limit: 40
7548 customer_1 ('customer_1', 'customer_2')
4091 customer_1 -9.344289344425928
resNode: customer_2 deliver_cap: 38.578644114253535 cap_limit: 40
7549 customer_1 ('customer_1', 'customer_4')
4091 customer_1 -9.344289344425928
resNode: customer_4 deliver_cap: 58.6070850642201 cap_limit: 40
7550 customer_1 ('customer_1', 'customer_5')
4091 customer_1 -9.344289344425928
resNode: customer_5 deliver_cap: 47.68080635777178 cap_limit: 40
7551 customer_2 ('customer_2', 'customer_3')
4093 customer_2 -7.990263582670214
resNode: customer_3 deliver_cap: 53.26845093352741 cap_limit: 40
7552 customer_2 ('customer_2', 'customer_1')
4093 customer_2 -7.990263582670214
resNode: customer_1 deliver_cap: 42.509542998989176 cap_limit: 40
7553 customer_2 ('customer_2', 'depot_t')
4093 customer_2 -7.990263582670214
resNode: depot_t deliver_cap: 27.60868143819333 cap_limit: 40
7554 customer_2 ('customer_2', 'customer_4')
4093 customer_2 -7.990263582670214
resNode: customer_4 deliver_cap: 53.071835257117755 cap_limit: 40
7555 customer_2 ('customer_2', 'customer_5')
4093 customer_2 -7.990263582670214
resNode: customer_5 deliver_cap: 38.166046760183754 cap_limit: 40
7556 customer_4 ('customer_4', 'customer_3')
4094 customer_4 -11.851936654514734
resNode: customer_3 deliver_cap: 51.40927819844697 cap_limit: 40
7557 customer_4 ('customer_4', 'customer_1')
4094 customer_4 -11.851936654514734
resNode: customer_1 deliver_cap: 51.17671420544205 cap_limit: 40
7558 customer_4 ('customer_4', 'depot_t')
4094 customer_4 -11.851936654514734
resNode: depot_t deliver_cap: 36.6595765489063 cap_limit: 40
7559 customer_4 ('customer_4', 'customer_2')
4094 customer_4 -11.851936654514734
resNode: customer_2 deliver_cap: 40.803435001742 cap_limit: 40
7560 customer_4 ('customer_4', 'customer_5')
4094 customer_4 -11.851936654514734

resNode: customer_3 deliver_cap: 50.808974002697035 cap_limit: 40
7622 customer_4 ('customer_4', 'customer_1')
4110 customer_4 -13.874819315326702
resNode: customer_1 deliver_cap: 50.671194882705265 cap_limit: 40
7623 customer_4 ('customer_4', 'depot_t')
4110 customer_4 -13.874819315326702
resNode: depot_t deliver_cap: 36.18565218384057 cap_limit: 40
7624 customer_4 ('customer_4', 'customer_2')
4110 customer_4 -13.874819315326702
resNode: customer_2 deliver_cap: 40.297915679005214 cap_limit: 40
7625 customer_4 ('customer_4', 'customer_5')
4110 customer_4 -13.874819315326702
resNode: customer_5 deliver_cap: 45.83515943286471 cap_limit: 40
7626 customer_1 ('customer_1', 'customer_3')
4111 customer_1 -7.948189276854593
resNode: customer_3 deliver_cap: 62.25145902919988 cap_limit: 40
7627 customer_1 ('customer_1', 'depot_t')
4111 customer_1 -7.948189276854593
resNode: depot_t deliver_cap: 38.25322031413313 cap_limit: 40
7628 customer_1 ('customer_1', 'customer_2')
4111 customer_1 -7.948189276854593
resNode: customer_2 deliver_cap: 40.803435001742 cap_limit: 40
7629 customer_1 ('customer_1', 'customer_4')
4111 customer_1 -7.948189276854593
resNode: customer_4 deliver_cap: 61.665820411344065 cap_limit: 40
7630 customer_1 ('customer_1', 'customer_5')
4111 customer_1 -7.948189276854593
resNode: customer_5 deliver_cap: 48.69086444743668 cap_limit: 40
7631 customer_2 ('customer_2', 'customer_3')
4113 customer_2 -6.094015098394412
resNode: customer_3 deliver_cap: 55.326192381146484 cap_limit: 40
7632 customer_2 ('customer_2', 'customer_1')
4113 customer_2 -6.094015098394412
resNode: customer_1 deliver_cap: 45.64146439833971 cap_limit: 40
7633 customer_2 ('customer_2', 'depot_t')
4113 customer_2 -6.094015098394412
resNode: depot_t deliver_cap: 28.250251980043785 cap_limit: 40
7634 customer_2 ('customer_2', 'customer_4')
4113 customer_2 -6.094015098394412
resNode: customer_4 deliver_cap: 55.09271126541001 cap_limit: 40
7635 customer_2 ('customer_2', 'customer_5')
4113 customer_2 -6.094015098394412
resNode: customer_5 deliver_cap: 37.3920874253009 cap_limit: 40
7636 customer_4 ('customer_4', 'customer_3')
4114 customer_4 -8.497974453372695
resNode: customer_3 deliver_cap: 50.344319584876445 cap_limit: 40
7637 customer_4 ('customer_4', 'customer_1')
4114 customer_4 -8.497974453372695
resNode: customer_1 deliver_cap: 52.842255016545124 cap_limit: 40
7638 customer_4 ('customer_4', 'depot_t')
4114 customer_4 -8.497974453372695
resNode: depot_t deliver_cap: 36.47877207745011 cap_limit: 40
7639 customer_4 ('customer_4', 'customer_2')
4114 customer_4 -8.497974453372695
resNode: customer_2 deliver_cap: 40.523985962151315 cap_limit: 40
7640 customer_4 ('customer_4', 'customer_5')
4114 customer_4 -8.497974453372695
resNode: customer_5 deliver_cap: 44.585165872439006 cap_limit: 40
7641 customer_5 ('customer_5', 'customer_3')
4115 customer_5 -11.43436600192355
resNode: customer_3 deliver_cap: 59.862164453412404 cap_limit: 40
7642 customer_5 ('customer_5', 'customer_1')
4115 customer_5 -11.43436600192355
resNode: customer_1 deliver_cap: 52.82758943865101 cap_limit: 40
7643 customer_5 ('customer_5', 'depot_t')
4115 customer_5 -11.43436600192355
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
7644 customer_5 ('customer_5', 'customer_2')
4115 customer_5 -11.43436600192355
resNode: customer_2 deliver_cap: 35.78365250805547 cap_limit: 40
7645 customer_5 ('customer_5', 'customer_4')
4115 customer_5 -11.43436600192355
resNode: customer_4 deliver_cap: 59.59181789834911 cap_limit: 40
7646 customer_2 ('customer_2', 'customer_3')
4118 customer_2 -6.01749538475278
resNode: customer_3 deliver_cap: 52.775281571122505 cap_limit: 40
7647 customer_2 ('customer_2', 'customer_1')
4118 customer_2 -6.01749538475278
resNode: customer_1 deliver_cap: 42.10884289203519 cap_limit: 40
7648 customer_2 ('customer_2', 'depot_t')
4118 customer_2 -6.01749538475278
resNode: depot_t deliver_cap: 27.23880441638965 cap_limit: 40
7649 customer_2 ('customer_2', 'customer_4')
4118 customer_2 -6.01749538475278
resNode: customer_4 deliver_cap: 52.57866589471284 cap_limit: 40
7650 customer_2 ('customer_2', 'customer_5')
4118 customer_2 -6.01749538475278
resNode: customer_5 deliver_cap: 37.67287739777885 cap_limit: 40
7651 customer_5 ('customer_5', 'customer_3')
4120 customer_5 -13.807057985120963
resNode: customer_3 deliver_cap: 61.2989973313306 cap_limit: 40
7652 customer_5 ('customer_5', 'customer_1')
4120 customer_5 -13.807057985120963
resNode: customer_1 deliver_cap: 52.57047978276593 cap_limit: 40
7653 customer_5 ('customer_5', 'depot_t')
4120 customer_5 -13.807057985120963
resNode: depot_t deliver_cap: 34.23544134906711 cap_limit: 40
7654 customer_5 ('customer_5', 'customer_2')
4120 customer_5 -13.807057985120963
resNode: customer_2 deliver_cap: 38.21769078858019 cap_limit: 40
7655 customer_5 ('customer_5', 'customer_4')
4120 customer_5 -13.807057985120963
resNode: customer_4 deliver_cap: 61.06551621559413 cap_limit: 40
7656 customer_3 ('customer_3', 'customer_1')
4121 customer_3 -12.199713428617493
resNode: customer_1 deliver_cap: 54.77172194002637 cap_limit: 40
7657 customer_3 ('customer_3', 'depot_t')
4121 customer_3 -12.199713428617493
resNode: depot_t deliver_cap: 39.75187721945855 cap_limit: 40
7658 customer_3 ('customer_3', 'customer_2')
4121 customer_3 -12.199713428617493
resNode: customer_2 deliver_cap: 44.10188905033107 cap_limit: 40
7659 customer_3 ('customer_3', 'customer_4')
4121 customer_3 -12.199713428617493
resNode: customer_4 deliver_cap: 55.09271126541001 cap_limit: 40
7660 customer_3 ('customer_3', 'customer_5')
4121 customer_3 -12.199713428617493
resNode: customer_5 deliver_cap: 50.35237781131416 cap_limit: 40
7661 customer_1 ('customer_1', 'customer_3')
4122 customer_1 -6.6528112051697645
resNode: customer_3 deliver_cap: 53.07183525711775 cap_limit: 40
7662 customer_1 ('customer_1', 'depot_t')
4122 customer_1 -6.6528112051697645
resNode: depot_t deliver_cap: 31.089741728334367 cap_limit: 40
7663 customer_1 ('customer_1', 'customer_2')
4122 customer_1 -6.6528112051697645
resNode: customer_2 deliver_cap: 33.68055353902889 cap_limit: 40
7664 customer_1 ('customer_1', 'customer_4')
4122 customer_1 -6.6528112051697645
resNode: customer_4 deliver_cap: 52.57866589471284 cap_limit: 40
7665 customer_1 ('customer_1', 'customer_5')
4122 customer_1 -6.6528112051697645
resNode: customer_5 deliver_cap: 41.65238718826453 cap_limit: 40
7666 customer_4 ('customer_4', 'customer_3')
4124 customer_4 -12.170016269159785
resNode: customer_3 deliver_cap: 55.09271126541001 cap_limit: 40
7667 customer_4 ('customer_4', 'customer_1')
4124 customer_4 -12.170016269159785
resNode: customer_1 deliver_cap: 54.27855257762146 cap_limit: 40
7668 customer_4 ('customer_4', 'depot_t')
4124 customer_4 -12.170016269159785
resNode: depot_t deliver_cap: 39.56755002282449 cap_limit: 40
7669 customer_4 ('customer_4', 'customer_2')
4124 customer_4 -12.170016269159785
resNode: customer_2 deliver_cap: 43.9052733739214 cap_limit: 40
7670 customer_4 ('customer_4', 'customer_5')
4124 customer_4 -12.170016269159785
resNode: customer_5 deliver_cap: 50.11889669557769 cap_limit: 40
7671 customer_5 ('customer_5', 'customer_3')
4125 customer_5 -10.007092007130066
resNode: customer_3 deliver_cap: 50.35237781131416 cap_limit: 40
7672 customer_5 ('customer_5', 'customer_1')
4125 customer_5 -10.007092007130066
resNode: customer_1 deliver_cap: 43.352273871173146 cap_limit: 40
7673 customer_5 ('customer_5', 'depot_t')
4125 customer_5 -10.007092007130066
resNode: depot_t deliver_cap: 25.59337330694888 cap_limit: 40
7674 customer_5 ('customer_5', 'customer_2')
4125 customer_5 -10.007092007130066
resNode: customer_2 deliver_cap: 28.99948487698742 cap_limit: 40
7675 customer_5 ('customer_5', 'customer_4')
4125 customer_5 -10.007092007130066
resNode: customer_4 deliver_cap: 50.11889669557769 cap_limit: 40
7676 customer_1 ('customer_1', 'customer_3')
4127 customer_1 -11.873599971086207
resNode: customer_3 deliver_cap: 61.65115483344994 cap_limit: 40
7677 customer_1 ('customer_1', 'depot_t')
4127 customer_1 -11.873599971086207
resNode: depot_t deliver_cap: 37.77929594906739 cap_limit: 40
7678 customer_1 ('customer_1', 'customer_2')
4127 customer_1 -11.873599971086207
resNode: customer_2 deliver_cap: 40.29791567900521 cap_limit: 40
7679 customer_1 ('customer_1', 'customer_4')
4127 customer_1 -11.873599971086207
resNode: customer_4 deliver_cap: 61.06551621559411 cap_limit: 40
7680 customer_1 ('customer_1', 'customer_5')
4127 customer_1 -11.873599971086207
resNode: customer_5 deliver_cap: 48.09056025168674 cap_limit: 40
7681 customer_2 ('customer_2', 'customer_3')
4129 customer_2 -8.92604819910543
resNode: customer_3 deliver_cap: 50.35237781131416 cap_limit: 40
7682 customer_2 ('customer_2', 'customer_1')
4129 customer_2 -8.92604819910543
resNode: customer_1 deliver_cap: 41.45298897111248 cap_limit: 40
7683 customer_2 ('customer_2', 'depot_t')
4129 customer_2 -8.92604819910543
resNode: depot_t deliver_cap: 24.32355626701827 cap_limit: 40
7684 customer_2 ('customer_2', 'customer_4')
4129 customer_2 -8.92604819910543
resNode: customer_4 deliver_cap: 50.11889669557769 cap_limit: 40
7685 customer_2 ('customer_2', 'customer_5')
4129 customer_2 -8.92604819910543
resNode: customer_5 deliver_cap: 32.41827285546857 cap_limit: 40
7686 customer_1 ('customer_1', 'customer_3')
4131 customer_1 -7.095760892565426
resNode: customer_3 deliver_cap: 57.511125575104025 cap_limit: 40
7687 customer_1 ('customer_1', 'depot_t')
4131 customer_1 -7.095760892565426
resNode: depot_t deliver_cap: 34.510851797741665 cap_limit: 40
7688 customer_1 ('customer_1', 'customer_2')
4131 customer_1 -7.095760892565426
resNode: customer_2 deliver_cap: 36.81157525092444 cap_limit: 40
7689 customer_1 ('customer_1', 'customer_4')
4131 customer_1 -7.095760892565426
resNode: customer_4 deliver_cap: 56.925486957248204 cap_limit: 40
7690 customer_1 ('customer_1', 'customer_5')
4131 customer_1 -7.095760892565426
resNode: customer_5 deliver_cap: 43.95053099334082 cap_limit: 40
7691 customer_2 ('customer_2', 'customer_3')
4133 customer_2 -5.241586714105248
resNode: customer_3 deliver_cap: 50.58585892705064 cap_limit: 40
7692 customer_2 ('customer_2', 'customer_1')
4133 customer_2 -5.241586714105248
resNode: customer_1 deliver_cap: 41.649604647522146 cap_limit: 40
7693 customer_2 ('customer_2', 'depot_t')
4133 customer_2 -5.241586714105248
resNode: depot_t deliver_cap: 24.507883463652327 cap_limit: 40
7694 customer_2 ('customer_2', 'customer_4')
4133 customer_2 -5.241586714105248
resNode: customer_4 deliver_cap: 50.35237781131416 cap_limit: 40
7695 customer_2 ('customer_2', 'customer_5')
4133 customer_2 -5.241586714105248
resNode: customer_5 deliver_cap: 32.65175397120505 cap_limit: 40
7696 customer_4 ('customer_4', 'customer_3')
4134 customer_4 -6.709953939985663
resNode: customer_3 deliver_cap: 44.855512427502305 cap_limit: 40
7697 customer_4 ('customer_4', 'customer_1')
4134 customer_4 -6.709953939985663
resNode: customer_1 deliver_cap: 48.10192156244928 cap_limit: 40
7698 customer_4 ('customer_4', 'depot_t')
4134 customer_4 -6.709953939985663
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
7699 customer_4 ('customer_4', 'customer_2')
4134 customer_4 -6.709953939985663
resNode: customer_2 deliver_cap: 35.78365250805547 cap_limit: 40
7700 customer_4 ('customer_4', 'customer_5')
4134 customer_4 -6.709953939985663
resNode: customer_5 deliver_cap: 39.09635871506488 cap_limit: 40
7701 customer_5 ('customer_5', 'customer_3')
4135 customer_5 -9.64634548853652
resNode: customer_3 deliver_cap: 54.37335729603826 cap_limit: 40
7702 customer_5 ('customer_5', 'customer_1')
4135 customer_5 -9.64634548853652
resNode: customer_1 deliver_cap: 48.08725598455517 cap_limit: 40
7703 customer_5 ('customer_5', 'depot_t')
4135 customer_5 -9.64634548853652
resNode: depot_t deliver_cap: 27.4970876381106 cap_limit: 40
7704 customer_5 ('customer_5', 'customer_2')
4135 customer_5 -9.64634548853652
resNode: customer_2 deliver_cap: 31.043319053959614 cap_limit: 40
7705 customer_5 ('customer_5', 'customer_4')
4135 customer_5 -9.64634548853652
resNode: customer_4 deliver_cap: 54.10301074097498 cap_limit: 40
7706 customer_3 ('customer_3', 'customer_1')
4136 customer_3 -9.571058792846099
resNode: customer_1 deliver_cap: 49.3806930406804 cap_limit: 40
7707 customer_3 ('customer_3', 'depot_t')
4136 customer_3 -9.571058792846099
resNode: depot_t deliver_cap: 34.697787626321706 cap_limit: 40
7708 customer_3 ('customer_3', 'customer_2')
4136 customer_3 -9.571058792846099
resNode: customer_2 deliver_cap: 38.7108601509851 cap_limit: 40
7709 customer_3 ('customer_3', 'customer_4')
4136 customer_3 -9.571058792846099
resNode: customer_4 deliver_cap: 48.69086444743668 cap_limit: 40
7710 customer_3 ('customer_3', 'customer_5')
4136 customer_3 -9.571058792846099
resNode: customer_5 deliver_cap: 43.95053099334083 cap_limit: 40
7711 customer_2 ('customer_2', 'customer_3')
4138 customer_2 -3.9336532059268663
resNode: customer_3 deliver_cap: 41.84900286467419 cap_limit: 40
7712 customer_2 ('customer_2', 'customer_1')
4138 customer_2 -3.9336532059268663
resNode: customer_1 deliver_cap: 33.231241443045924 cap_limit: 40
7713 customer_2 ('customer_2', 'depot_t')
4138 customer_2 -3.9336532059268663
resNode: depot_t deliver_cap: 19.044095386553415 cap_limit: 40
7714 customer_2 ('customer_2', 'customer_4')
4138 customer_2 -3.9336532059268663
resNode: customer_4 deliver_cap: 41.65238718826453 cap_limit: 40
7715 customer_2 ('customer_2', 'customer_5')
4138 customer_2 -3.9336532059268663
resNode: customer_5 deliver_cap: 26.746598691330536 cap_limit: 40
7716 customer_4 ('customer_4', 'customer_3')
4139 customer_4 -9.397718441734444
resNode: customer_3 deliver_cap: 48.33870694531733 cap_limit: 40
7717 customer_4 ('customer_4', 'customer_1')
4139 customer_4 -9.397718441734444
resNode: customer_1 deliver_cap: 48.59096999228025 cap_limit: 40
7718 customer_4 ('customer_4', 'depot_t')
4139 customer_4 -9.397718441734444
resNode: depot_t deliver_cap: 34.235441349067116 cap_limit: 40
7719 customer_4 ('customer_4', 'customer_2')
4139 customer_4 -9.397718441734444
resNode: customer_2 deliver_cap: 38.2176907885802 cap_limit: 40
7720 customer_4 ('customer_4', 'customer_5')
4139 customer_4 -9.397718441734444
resNode: customer_5 deliver_cap: 43.364892375485 cap_limit: 40
7721 customer_5 ('customer_5', 'customer_3')
4140 customer_5 -9.162369234471225
resNode: customer_3 deliver_cap: 48.32404136742321 cap_limit: 40
7722 customer_5 ('customer_5', 'customer_1')
4140 customer_5 -9.162369234471225
resNode: customer_1 deliver_cap: 41.64420107631761 cap_limit: 40
7723 customer_5 ('customer_5', 'depot_t')
4140 customer_5 -9.162369234471225
resNode: depot_t deliver_cap: 23.99205506177181 cap_limit: 40
7724 customer_5 ('customer_5', 'customer_2')
4140 customer_5 -9.162369234471225
resNode: customer_2 deliver_cap: 27.29141208213188 cap_limit: 40
7725 customer_5 ('customer_5', 'customer_4')
4140 customer_5 -9.162369234471225
resNode: customer_4 deliver_cap: 48.09056025168674 cap_limit: 40
7726 customer_3 ('customer_3', 'customer_1')
4141 customer_3 -5.378730261295903
resNode: customer_1 deliver_cap: 39.86593344309237 cap_limit: 40
7727 customer_3 ('customer_3', 'depot_t')
4141 customer_3 -5.378730261295903
resNode: depot_t deliver_cap: 25.77770050358293 cap_limit: 40
7728 customer_3 ('customer_3', 'customer_2')
4141 customer_3 -5.378730261295903
resNode: customer_2 deliver_cap: 29.196100553397077 cap_limit: 40
7729 customer_3 ('customer_3', 'customer_4')
4141 customer_3 -5.378730261295903
resNode: customer_4 deliver_cap: 37.3920874253009 cap_limit: 40
7730 customer_3 ('customer_3', 'customer_5')
4141 customer_3 -5.378730261295903
resNode: customer_5 deliver_cap: 32.65175397120505 cap_limit: 40
7731 customer_1 ('customer_1', 'customer_3')
4142 customer_1 -3.325372216817078
resNode: customer_3 deliver_cap: 38.166046760183754 cap_limit: 40
7732 customer_1 ('customer_1', 'depot_t')
4142 customer_1 -3.325372216817078
resNode: depot_t deliver_cap: 19.91040035563387 cap_limit: 40
7733 customer_1 ('customer_1', 'customer_2')
4142 customer_1 -3.325372216817078
resNode: customer_2 deliver_cap: 21.569600385270025 cap_limit: 40
7734 customer_1 ('customer_1', 'customer_4')
4142 customer_1 -3.325372216817078
resNode: customer_4 deliver_cap: 37.67287739777885 cap_limit: 40
7735 customer_1 ('customer_1', 'customer_5')
4142 customer_1 -3.325372216817078
resNode: customer_5 deliver_cap: 26.746598691330536 cap_limit: 40
7736 customer_4 ('customer_4', 'customer_3')
4144 customer_4 -5.349033101838194
resNode: customer_3 deliver_cap: 37.3920874253009 cap_limit: 40
7737 customer_4 ('customer_4', 'customer_1')
4144 customer_4 -5.349033101838194
resNode: customer_1 deliver_cap: 39.37276408068747 cap_limit: 40
7738 customer_4 ('customer_4', 'depot_t')
4144 customer_4 -5.349033101838194
resNode: depot_t deliver_cap: 25.59337330694888 cap_limit: 40
7739 customer_4 ('customer_4', 'customer_2')
4144 customer_4 -5.349033101838194
resNode: customer_2 deliver_cap: 28.99948487698742 cap_limit: 40
7740 customer_4 ('customer_4', 'customer_5')
4144 customer_4 -5.349033101838194
resNode: customer_5 deliver_cap: 32.41827285546857 cap_limit: 40
7741 customer_5 ('customer_5', 'customer_3')
4145 customer_5 -3.186108839808476
resNode: customer_3 deliver_cap: 32.651753971205046 cap_limit: 40
7742 customer_5 ('customer_5', 'customer_1')
4145 customer_5 -3.186108839808476
resNode: customer_1 deliver_cap: 28.446485374239153 cap_limit: 40
7743 customer_5 ('customer_5', 'depot_t')
4145 customer_5 -3.186108839808476
resNode: depot_t deliver_cap: 11.61919659107326 cap_limit: 40
7744 customer_5 ('customer_5', 'customer_2')
4145 customer_5 -3.186108839808476
resNode: customer_2 deliver_cap: 14.093696380053427 cap_limit: 40
7745 customer_5 ('customer_5', 'customer_4')
4145 customer_5 -3.186108839808476
resNode: customer_4 deliver_cap: 32.41827285546857 cap_limit: 40
7746 customer_3 ('customer_3', 'customer_1')
4146 customer_3 -6.660800020883246
resNode: customer_1 deliver_cap: 48.45407906456863 cap_limit: 40
7747 customer_3 ('customer_3', 'depot_t')
4146 customer_3 -6.660800020883246
resNode: depot_t deliver_cap: 31.98792985778035 cap_limit: 40
7748 customer_3 ('customer_3', 'customer_2')
4146 customer_3 -6.660800020883246
resNode: customer_2 deliver_cap: 35.78365250805546 cap_limit: 40
7749 customer_3 ('customer_3', 'customer_4')
4146 customer_3 -6.660800020883246
resNode: customer_4 deliver_cap: 44.58516587243902 cap_limit: 40
7750 customer_3 ('customer_3', 'customer_5')
4146 customer_3 -6.660800020883246
resNode: customer_5 deliver_cap: 39.09635871506488 cap_limit: 40
7751 customer_1 ('customer_1', 'customer_3')
4147 customer_1 -6.965735877802273
resNode: customer_3 deliver_cap: 56.925486957248204 cap_limit: 40
7752 customer_1 ('customer_1', 'depot_t')
4147 customer_1 -6.965735877802273
resNode: depot_t deliver_cap: 34.04850552048706 cap_limit: 40
7753 customer_1 ('customer_1', 'customer_2')
4147 customer_1 -6.965735877802273
resNode: customer_2 deliver_cap: 36.318405888519536 cap_limit: 40
7754 customer_1 ('customer_1', 'customer_4')
4147 customer_1 -6.965735877802273
resNode: customer_4 deliver_cap: 56.33984833939238 cap_limit: 40
7755 customer_1 ('customer_1', 'customer_5')
4147 customer_1 -6.965735877802273
resNode: customer_5 deliver_cap: 43.364892375485 cap_limit: 40
7756 customer_2 ('customer_2', 'customer_3')
4149 customer_2 -5.199601074871933
resNode: customer_3 deliver_cap: 50.35237781131416 cap_limit: 40
7757 customer_2 ('customer_2', 'customer_1')
4149 customer_2 -5.199601074871933
resNode: customer_1 deliver_cap: 41.45298897111249 cap_limit: 40
7758 customer_2 ('customer_2', 'depot_t')
4149 customer_2 -5.199601074871933
resNode: depot_t deliver_cap: 24.32355626701827 cap_limit: 40
7759 customer_2 ('customer_2', 'customer_4')
4149 customer_2 -5.199601074871933
resNode: customer_4 deliver_cap: 50.11889669557769 cap_limit: 40
7760 customer_2 ('customer_2', 'customer_5')

resNode: depot_t deliver_cap: 36.57893248698345 cap_limit: 40
7798 customer_1 ('customer_1', 'customer_2')
4177 customer_1 -8.442893743853084
resNode: customer_2 deliver_cap: 39.627176860898736 cap_limit: 40
7799 customer_1 ('customer_1', 'customer_4')
4177 customer_1 -8.442893743853084
resNode: customer_4 deliver_cap: 59.89758690624497 cap_limit: 40
7800 customer_1 ('customer_1', 'customer_5')
4177 customer_1 -8.442893743853084
resNode: customer_5 deliver_cap: 48.971308199796646 cap_limit: 40
7801 customer_5 ('customer_5', 'customer_3')
4180 customer_5 -13.512546657891225
resNode: customer_3 deliver_cap: 59.04359651250856 cap_limit: 40
7802 customer_5 ('customer_5', 'customer_1')
4180 customer_5 -13.512546657891225
resNode: customer_1 deliver_cap: 50.671194882705265 cap_limit: 40
7803 customer_5 ('customer_5', 'depot_t')
4180 customer_5 -13.512546657891225
resNode: depot_t deliver_cap: 32.45486175526023 cap_limit: 40
7804 customer_5 ('customer_5', 'customer_2')
4180 customer_5 -13.512546657891225
resNode: customer_2 deliver_cap: 36.31840588851953 cap_limit: 40
7805 customer_5 ('customer_5', 'customer_4')
4180 customer_5 -13.512546657891225
resNode: customer_4 deliver_cap: 58.81011539677209 cap_limit: 40
7806 customer_2 ('customer_2', 'customer_3')
4189 customer_2 -13.470174279587267
resNode: customer_3 deliver_cap: 61.29899733133058 cap_limit: 40
7807 customer_2 ('customer_2', 'customer_1')
4189 customer_2 -13.470174279587267
resNode: customer_1 deliver_cap: 50.671194882705265 cap_limit: 40
7808 customer_2 ('customer_2', 'depot_t')
4189 customer_2 -13.470174279587267
resNode: depot_t deliver_cap: 32.965624309136494 cap_limit: 40
7809 customer_2 ('customer_2', 'customer_4')
4189 customer_2 -13.470174279587267
resNode: customer_4 deliver_cap: 61.06551621559411 cap_limit: 40
7810 customer_2 ('customer_2', 'customer_5')
4189 customer_2 -13.470174279587267
resNode: customer_5 deliver_cap: 43.36489237548499 cap_limit: 40
7811 customer_2 ('customer_2', 'customer_3')
4193 customer_2 -12.230592114443228
resNode: customer_3 deliver_cap: 68.28648276715975 cap_limit: 40
7812 customer_2 ('customer_2', 'customer_1')
4193 customer_2 -12.230592114443228
resNode: customer_1 deliver_cap: 56.55539314445614 cap_limit: 40
7813 customer_2 ('customer_2', 'depot_t')
4193 customer_2 -12.230592114443228
resNode: depot_t deliver_cap: 38.48206017952794 cap_limit: 40
7814 customer_2 ('customer_2', 'customer_4')
4193 customer_2 -12.230592114443228
resNode: customer_4 deliver_cap: 68.05300165142329 cap_limit: 40
7815 customer_2 ('customer_2', 'customer_5')
4193 customer_2 -12.230592114443228
resNode: customer_5 deliver_cap: 50.352377811314156 cap_limit: 40
7816 customer_2 ('customer_2', 'customer_3')
4198 customer_2 -6.835587896026989
resNode: customer_3 deliver_cap: 54.85550646154752 cap_limit: 40
7817 customer_2 ('customer_2', 'customer_1')
4198 customer_2 -6.835587896026989
resNode: customer_1 deliver_cap: 43.79902561550551 cap_limit: 40
7818 customer_2 ('customer_2', 'depot_t')
4198 customer_2 -6.835587896026989
resNode: depot_t deliver_cap: 28.798973084208413 cap_limit: 40
7819 customer_2 ('customer_2', 'customer_4')
4198 customer_2 -6.835587896026989
resNode: customer_4 deliver_cap: 54.65889078513786 cap_limit: 40
7820 customer_2 ('customer_2', 'customer_5')
4198 customer_2 -6.835587896026989
resNode: customer_5 deliver_cap: 39.75310228820386 cap_limit: 40
7821 customer_5 ('customer_5', 'customer_3')
4200 customer_5 -15.112703205088536
resNode: customer_3 deliver_cap: 63.7692643887103 cap_limit: 40
7822 customer_5 ('customer_5', 'customer_1')
4200 customer_5 -15.112703205088536
resNode: customer_1 deliver_cap: 54.650704673190944 cap_limit: 40
7823 customer_5 ('customer_5', 'depot_t')
4200 customer_5 -15.112703205088536
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
7824 customer_5 ('customer_5', 'customer_2')
4200 customer_5 -15.112703205088536
resNode: customer_2 deliver_cap: 40.29791567900521 cap_limit: 40
7825 customer_5 ('customer_5', 'customer_4')
4200 customer_5 -15.112703205088536
resNode: customer_4 deliver_cap: 63.53578327297383 cap_limit: 40
7826 customer_2 ('customer_2', 'customer_3')
4204 customer_2 -12.188606475209914
resNode: customer_3 deliver_cap: 68.05300165142329 cap_limit: 40
7827 customer_2 ('customer_2', 'customer_1')
4204 customer_2 -12.188606475209914
resNode: customer_1 deliver_cap: 56.35877746804648 cap_limit: 40
7828 customer_2 ('customer_2', 'depot_t')
4204 customer_2 -12.188606475209914
resNode: depot_t deliver_cap: 38.29773298289388 cap_limit: 40
7829 customer_2 ('customer_2', 'customer_4')
4204 customer_2 -12.188606475209914
resNode: customer_4 deliver_cap: 67.8195205356868 cap_limit: 40
7830 customer_2 ('customer_2', 'customer_5')
4204 customer_2 -12.188606475209914
resNode: customer_5 deliver_cap: 50.11889669557769 cap_limit: 40
7831 customer_1 ('customer_1', 'customer_3')
4207 customer_1 -12.0416222041026
resNode: customer_3 deliver_cap: 61.651154833449944 cap_limit: 40
7832 customer_1 ('customer_1', 'depot_t')
4207 customer_1 -12.0416222041026
resNode: depot_t deliver_cap: 37.77929594906739 cap_limit: 40
7833 customer_1 ('customer_1', 'customer_2')
4207 customer_1 -12.0416222041026
resNode: customer_2 deliver_cap: 40.297915679005214 cap_limit: 40
7834 customer_1 ('customer_1', 'customer_4')
4207 customer_1 -12.0416222041026
resNode: customer_4 deliver_cap: 61.06551621559413 cap_limit: 40
7835 customer_1 ('customer_1', 'customer_5')
4207 customer_1 -12.0416222041026
resNode: customer_5 deliver_cap: 48.090560251686746 cap_limit: 40
7836 customer_2 ('customer_2', 'customer_3')
4209 customer_2 -9.094070432121823
resNode: customer_3 deliver_cap: 50.35237781131416 cap_limit: 40
7837 customer_2 ('customer_2', 'customer_1')
4209 customer_2 -9.094070432121823
resNode: customer_1 deliver_cap: 41.45298897111249 cap_limit: 40
7838 customer_2 ('customer_2', 'depot_t')
4209 customer_2 -9.094070432121823
resNode: depot_t deliver_cap: 24.32355626701827 cap_limit: 40
7839 customer_2 ('customer_2', 'customer_4')
4209 customer_2 -9.094070432121823
resNode: customer_4 deliver_cap: 50.11889669557769 cap_limit: 40
7840 customer_2 ('customer_2', 'customer_5')
4209 customer_2 -9.094070432121823
resNode: customer_5 deliver_cap: 32.41827285546858 cap_limit: 40
7841 customer_2 ('customer_2', 'customer_3')
4218 customer_2 -11.268319379897369
resNode: customer_3 deliver_cap: 63.76926438871029 cap_limit: 40
7842 customer_2 ('customer_2', 'customer_1')
4218 customer_2 -11.268319379897369
resNode: customer_1 deliver_cap: 52.75141977313028 cap_limit: 40
7843 customer_2 ('customer_2', 'depot_t')
4218 customer_2 -11.268319379897369
resNode: depot_t deliver_cap: 34.915835143909945 cap_limit: 40
7844 customer_2 ('customer_2', 'customer_4')
4218 customer_2 -11.268319379897369
resNode: customer_4 deliver_cap: 63.535783272973816 cap_limit: 40
7845 customer_2 ('customer_2', 'customer_5')
4218 customer_2 -11.268319379897369
resNode: customer_5 deliver_cap: 45.8351594328647 cap_limit: 40
7846 customer_1 ('customer_1', 'customer_3')
4222 customer_1 -10.714182451355107
resNode: customer_3 deliver_cap: 59.395754014627904 cap_limit: 40
7847 customer_1 ('customer_1', 'depot_t')
4222 customer_1 -10.714182451355107
resNode: depot_t deliver_cap: 35.99871635526051 cap_limit: 40
7848 customer_1 ('customer_1', 'customer_2')
4222 customer_1 -10.714182451355107
resNode: customer_2 deliver_cap: 38.39863077894455 cap_limit: 40
7849 customer_1 ('customer_1', 'customer_4')
4222 customer_1 -10.714182451355107
resNode: customer_4 deliver_cap: 58.81011539677209 cap_limit: 40
7850 customer_1 ('customer_1', 'customer_5')
4222 customer_1 -10.714182451355107
resNode: customer_5 deliver_cap: 45.83515943286471 cap_limit: 40
7851 customer_5 ('customer_5', 'customer_3')
4225 customer_5 -12.689157859352598
resNode: customer_3 deliver_cap: 54.103010740974966 cap_limit: 40
7852 customer_5 ('customer_5', 'customer_1')
4225 customer_5 -12.689157859352598
resNode: customer_1 deliver_cap: 47.85377486881869 cap_limit: 40
7853 customer_5 ('customer_5', 'depot_t')
4225 customer_5 -12.689157859352598
resNode: depot_t deliver_cap: 27.275895002149728 cap_limit: 40
7854 customer_5 ('customer_5', 'customer_2')
4225 customer_5 -12.689157859352598
resNode: customer_2 deliver_cap: 30.80983793822314 cap_limit: 40
7855 customer_5 ('customer_5', 'customer_4')
4225 customer_5 -12.689157859352598
resNode: customer_4 deliver_cap: 53.83266418591169 cap_limit: 40
7856 customer_2 ('customer_2', 'customer_3')
4233 customer_2 -11.202491107918924
resNode: customer_3 deliver_cap: 68.01392809556144 cap_limit: 40
7857 customer_2 ('customer_2', 'customer_1')
4233 customer_2 -11.202491107918924
resNode: customer_1 deliver_cap: 54.49024319314181 cap_limit: 40
7858 customer_2 ('customer_2', 'depot_t')
4233 customer_2 -11.202491107918924
resNode: depot_t deliver_cap: 38.66778930971885 cap_limit: 40
7859 customer_2 ('customer_2', 'customer_4')
4233 customer_2 -11.202491107918924
resNode: customer_4 deliver_cap: 67.81731241915178 cap_limit: 40
7860 customer_2 ('customer_2', 'customer_5')
4233 customer_2 -11.202491107918924
resNode: customer_5 deliver_cap: 52.911523922217775 cap_limit: 40
7861 customer_2 ('customer_2', 'customer_3')
4239 customer_2 -16.544978714485765
resNode: customer_3 deliver_cap: 65.97800350170567 cap_limit: 40
7862 customer_2 ('customer_2', 'customer_1')
4239 customer_2 -16.544978714485765
resNode: customer_1 deliver_cap: 54.61141060512639 cap_limit: 40
7863 customer_2 ('customer_2', 'depot_t')
4239 customer_2 -16.544978714485765
resNode: depot_t deliver_cap: 36.659576548906294 cap_limit: 40
7864 customer_2 ('customer_2', 'customer_4')
4239 customer_2 -16.544978714485765
resNode: customer_4 deliver_cap: 65.7445223859692 cap_limit: 40
7865 customer_2 ('customer_2', 'customer_5')
4239 customer_2 -16.544978714485765
resNode: customer_5 deliver_cap: 48.043898545860074 cap_limit: 40
7866 customer_5 ('customer_5', 'customer_3')
4255 customer_5 -18.23697999411433
resNode: customer_3 deliver_cap: 68.09611305696602 cap_limit: 40
7867 customer_5 ('customer_5', 'customer_1')
4255 customer_5 -18.23697999411433
resNode: customer_1 deliver_cap: 58.29436670961681 cap_limit: 40
7868 customer_5 ('customer_5', 'depot_t')
4255 customer_5 -18.23697999411433
resNode: depot_t deliver_cap: 39.601585342989814 cap_limit: 40
7869 customer_5 ('customer_5', 'customer_2')
4255 customer_5 -18.23697999411433
resNode: customer_2 deliver_cap: 43.94157771543108 cap_limit: 40
7870 customer_5 ('customer_5', 'customer_4')
4255 customer_5 -18.23697999411433
resNode: customer_4 deliver_cap: 67.86263194122955 cap_limit: 40
7871 customer_5 ('customer_5', 'customer_3')
4275 customer_5 -17.445082341211993
resNode: customer_3 deliver_cap: 61.72456277864396 cap_limit: 40
7872 customer_5 ('customer_5', 'customer_1')
4275 customer_5 -17.445082341211993
resNode: customer_1 deliver_cap: 54.43602435589646 cap_limit: 40
7873 customer_5 ('customer_5', 'depot_t')
4275 customer_5 -17.445082341211993
resNode: depot_t deliver_cap: 33.511710305697086 cap_limit: 40
7874 customer_5 ('customer_5', 'customer_2')
4275 customer_5 -17.445082341211993
resNode: customer_2 deliver_cap: 37.39208742530091 cap_limit: 40
7875 customer_5 ('customer_5', 'customer_4')
4275 customer_5 -17.445082341211993
resNode: customer_4 deliver_cap: 61.45421622358067 cap_limit: 40
7876 customer_2 ('customer_2', 'customer_3')
4299 customer_2 -14.097513991154571
resNode: customer_3 deliver_cap: 67.2133699360181 cap_limit: 40
7877 customer_2 ('customer_2', 'customer_1')
4299 customer_2 -14.097513991154571
resNode: customer_1 deliver_cap: 56.92095699117028 cap_limit: 40
7878 customer_2 ('customer_2', 'depot_t')
4299 customer_2 -14.097513991154571
resNode: depot_t deliver_cap: 36.47877207745011 cap_limit: 40
7879 customer_2 ('customer_2', 'customer_4')
4299 customer_2 -14.097513991154571
resNode: customer_4 deliver_cap: 66.94302338095483 cap_limit: 40
7880 customer_2 ('customer_2', 'customer_5')
4299 customer_2 -14.097513991154571
resNode: customer_5 deliver_cap: 46.44756419767059 cap_limit: 40
7881 customer_2 ('customer_2', 'customer_3')
4313 customer_2 -13.278970614516448
resNode: customer_3 deliver_cap: 68.09611305696603 cap_limit: 40
7882 customer_2 ('customer_2', 'customer_1')
4313 customer_2 -13.278970614516448
resNode: customer_1 deliver_cap: 56.39508180955617 cap_limit: 40
7883 customer_2 ('customer_2', 'depot_t')
4313 customer_2 -13.278970614516448
resNode: depot_t deliver_cap: 38.331768303059214 cap_limit: 40
7884 customer_2 ('customer_2', 'customer_4')
4313 customer_2 -13.278970614516448
resNode: customer_4 deliver_cap: 67.86263194122957 cap_limit: 40
7885 customer_2 ('customer_2', 'customer_5')
4313 customer_2 -13.278970614516448
resNode: customer_5 deliver_cap: 50.16200810112044 cap_limit: 40
7886 customer_2 ('customer_2', 'customer_3')
4319 customer_2 -15.536958133148845
resNode: customer_3 deliver_cap: 61.724562778643964 cap_limit: 40
7887 customer_2 ('customer_2', 'customer_1')
4319 customer_2 -15.536958133148845
resNode: customer_1 deliver_cap: 52.180623537074425 cap_limit: 40
7888 customer_2 ('customer_2', 'depot_t')
4319 customer_2 -15.536958133148845
resNode: depot_t deliver_cap: 31.987929857780358 cap_limit: 40
7889 customer_2 ('customer_2', 'customer_4')
4319 customer_2 -15.536958133148845
resNode: customer_4 deliver_cap: 61.45421622358069 cap_limit: 40
7890 customer_2 ('customer_2', 'customer_5')
4319 customer_2 -15.536958133148845
resNode: customer_5 deliver_cap: 40.95875704029644 cap_limit: 40
7891 customer_1 ('customer_1', 'customer_3')
4337 customer_1 -11.834278553824749
resNode: customer_3 deliver_cap: 60.28646964602783 cap_limit: 40
7892 customer_1 ('customer_1', 'depot_t')
4337 customer_1 -11.834278553824749
resNode: depot_t deliver_cap: 35.20118564214131 cap_limit: 40
7893 customer_1 ('customer_1', 'customer_2')
4337 customer_1 -11.834278553824749
resNode: customer_2 deliver_cap: 39.11242849126812 cap_limit: 40
7894 customer_1 ('customer_1', 'customer_4')
4337 customer_1 -11.834278553824749
resNode: customer_4 deliver_cap: 59.885769539073856 cap_limit: 40
7895 customer_1 ('customer_1', 'customer_5')
4337 customer_1 -11.834278553824749
resNode: customer_5 deliver_cap: 51.008168090084595 cap_limit: 40
7896 customer_5 ('customer_5', 'customer_3')
4340 customer_5 -20.803615942579558
resNode: customer_3 deliver_cap: 63.52889898233896 cap_limit: 40
7897 customer_5 ('customer_5', 'customer_1')
4340 customer_5 -20.803615942579558
resNode: customer_1 deliver_cap: 52.38932601994784 cap_limit: 40
7898 customer_5 ('customer_5', 'depot_t')
4340 customer_5 -20.803615942579558
resNode: depot_t deliver_cap: 36.319871106746476 cap_limit: 40
7899 customer_5 ('customer_5', 'customer_2')
4340 customer_5 -20.803615942579558
resNode: customer_2 deliver_cap: 40.72768496217193 cap_limit: 40
7900 customer_5 ('customer_5', 'customer_4')
4340 customer_5 -20.803615942579558
resNode: customer_4 deliver_cap: 63.332283305929295 cap_limit: 40
7901 customer_2 ('customer_2', 'customer_3')
4344 customer_2 -20.73570543658178
resNode: customer_3 deliver_cap: 65.42818388239962 cap_limit: 40
7902 customer_2 ('customer_2', 'customer_1')
4344 customer_2 -20.73570543658178
resNode: customer_1 deliver_cap: 52.389326019947845 cap_limit: 40
7903 customer_2 ('customer_2', 'depot_t')
4344 customer_2 -20.73570543658178
resNode: depot_t deliver_cap: 36.72848114984748 cap_limit: 40
7904 customer_2 ('customer_2', 'customer_4')
4344 customer_2 -20.73570543658178
resNode: customer_4 deliver_cap: 65.23156820598996 cap_limit: 40
7905 customer_2 ('customer_2', 'customer_5')
4344 customer_2 -20.73570543658178
resNode: customer_5 deliver_cap: 50.32577970905596 cap_limit: 40
7906 customer_2 ('customer_2', 'customer_3')
4353 customer_2 -17.266213494289147
resNode: customer_3 deliver_cap: 65.42818388239962 cap_limit: 40
7907 customer_2 ('customer_2', 'customer_1')
4353 customer_2 -17.266213494289147
resNode: customer_1 deliver_cap: 52.389326019947845 cap_limit: 40
7908 customer_2 ('customer_2', 'depot_t')
4353 customer_2 -17.266213494289147
resNode: depot_t deliver_cap: 36.72848114984749 cap_limit: 40
7909 customer_2 ('customer_2', 'customer_4')
4353 customer_2 -17.266213494289147
resNode: customer_4 deliver_cap: 65.23156820598996 cap_limit: 40
7910 customer_2 ('customer_2', 'customer_5')
4353 customer_2 -17.266213494289147
resNode: customer_5 deliver_cap: 50.325779709055965 cap_limit: 40
7911 customer_1 ('customer_1', 'customer_3')
4357 customer_1 -16.657932505179353
resNode: customer_3 deliver_cap: 61.745227777909186 cap_limit: 40
7912 customer_1 ('customer_1', 'depot_t')
4357 customer_1 -16.657932505179353
resNode: depot_t deliver_cap: 37.59478611892794 cap_limit: 40
7913 customer_1 ('customer_1', 'customer_2')
4357 customer_1 -16.657932505179353
resNode: customer_2 deliver_cap: 40.727684962171935 cap_limit: 40
7914 customer_1 ('customer_1', 'customer_4')
4357 customer_1 -16.657932505179353
resNode: customer_4 deliver_cap: 61.25205841550428 cap_limit: 40
7915 customer_1 ('customer_1', 'customer_5')
4357 customer_1 -16.657932505179353
resNode: customer_5 deliver_cap: 50.32577970905596 cap_limit: 40
7916 customer_5 ('customer_5', 'customer_3')
4360 customer_5 -22.045039679200148
resNode: customer_3 deliver_cap: 60.65203142975399 cap_limit: 40
7917 customer_5 ('customer_5', 'customer_1')
4360 customer_5 -22.045039679200148
resNode: customer_1 deliver_cap: 52.02566639196458 cap_limit: 40
7918 customer_5 ('customer_5', 'depot_t')
4360 customer_5 -22.045039679200148
resNode: depot_t deliver_cap: 33.72467879519084 cap_limit: 40
7919 customer_5 ('customer_5', 'customer_2')
4360 customer_5 -22.045039679200148
resNode: customer_2 deliver_cap: 37.67287739777884 cap_limit: 40
7920 customer_5 ('customer_5', 'customer_4')
4360 customer_5 -22.045039679200148
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
7921 customer_2 ('customer_2', 'customer_3')
4378 customer_2 -17.09615047751612
resNode: customer_3 deliver_cap: 65.42818388239962 cap_limit: 40
7922 customer_2 ('customer_2', 'customer_1')
4378 customer_2 -17.09615047751612
resNode: customer_1 deliver_cap: 52.389326019947845 cap_limit: 40
7923 customer_2 ('customer_2', 'depot_t')
4378 customer_2 -17.09615047751612
resNode: depot_t deliver_cap: 36.72848114984749 cap_limit: 40
7924 customer_2 ('customer_2', 'customer_4')
4378 customer_2 -17.09615047751612
resNode: customer_4 deliver_cap: 65.23156820598996 cap_limit: 40
7925 customer_2 ('customer_2', 'customer_5')
4378 customer_2 -17.09615047751612
resNode: customer_5 deliver_cap: 50.325779709055965 cap_limit: 40
7926 customer_2 ('customer_2', 'customer_3')
4384 customer_2 -21.832604284123157
resNode: customer_3 deliver_cap: 62.90743224857602 cap_limit: 40
7927 customer_2 ('customer_2', 'customer_1')
4384 customer_2 -21.832604284123157
resNode: customer_1 deliver_cap: 52.02566639196458 cap_limit: 40
7928 customer_2 ('customer_2', 'depot_t')
4384 customer_2 -21.832604284123157
resNode: depot_t deliver_cap: 34.2354413490671 cap_limit: 40
7929 customer_2 ('customer_2', 'customer_4')
4384 customer_2 -21.832604284123157
resNode: customer_4 deliver_cap: 62.67395113283954 cap_limit: 40
7930 customer_2 ('customer_2', 'customer_5')
4384 customer_2 -21.832604284123157
resNode: customer_5 deliver_cap: 44.973327292730424 cap_limit: 40
7931 customer_2 ('customer_2', 'customer_3')
4399 customer_2 -22.431834075776266
resNode: customer_3 deliver_cap: 69.89491768440519 cap_limit: 40
7932 customer_2 ('customer_2', 'customer_1')
4399 customer_2 -22.431834075776266
resNode: customer_1 deliver_cap: 57.90986465371545 cap_limit: 40
7933 customer_2 ('customer_2', 'depot_t')
4399 customer_2 -22.431834075776266
resNode: depot_t deliver_cap: 39.75187721945854 cap_limit: 40
7934 customer_2 ('customer_2', 'customer_4')
4399 customer_2 -22.431834075776266
resNode: customer_4 deliver_cap: 69.66143656866872 cap_limit: 40
7935 customer_2 ('customer_2', 'customer_5')
4399 customer_2 -22.431834075776266

8001 customer_2 ('customer_2', 'customer_3')
4509 customer_2 -14.575811089284981
resNode: customer_3 deliver_cap: 51.96081272855961 cap_limit: 40
8002 customer_2 ('customer_2', 'customer_1')
4509 customer_2 -14.575811089284981
resNode: customer_1 deliver_cap: 42.80746048037181 cap_limit: 40
8003 customer_2 ('customer_2', 'depot_t')
4509 customer_2 -14.575811089284981
resNode: depot_t deliver_cap: 25.593373306948884 cap_limit: 40
8004 customer_2 ('customer_2', 'customer_4')
4509 customer_2 -14.575811089284981
resNode: customer_4 deliver_cap: 51.727331612823136 cap_limit: 40
8005 customer_2 ('customer_2', 'customer_5')
4509 customer_2 -14.575811089284981
resNode: customer_5 deliver_cap: 34.02670777271402 cap_limit: 40
8006 customer_2 ('customer_2', 'customer_3')
4528 customer_2 -15.056813147390677
resNode: customer_3 deliver_cap: 67.50840877282464 cap_limit: 40
8007 customer_2 ('customer_2', 'customer_1')
4528 customer_2 -15.056813147390677
resNode: customer_1 deliver_cap: 54.079508743418174 cap_limit: 40
8008 customer_2 ('customer_2', 'depot_t')
4528 customer_2 -15.056813147390677
resNode: depot_t deliver_cap: 38.288649817666254 cap_limit: 40
8009 customer_2 ('customer_2', 'customer_4')
4528 customer_2 -15.056813147390677
resNode: customer_4 deliver_cap: 67.31179309641497 cap_limit: 40
8010 customer_2 ('customer_2', 'customer_5')
4528 customer_2 -15.056813147390677
resNode: customer_5 deliver_cap: 52.40600459948098 cap_limit: 40
8011 customer_2 ('customer_2', 'customer_3')
4534 customer_2 -20.28081966269108
resNode: customer_3 deliver_cap: 65.37769930595573 cap_limit: 40
8012 customer_2 ('customer_2', 'customer_1')
4534 customer_2 -20.28081966269108
resNode: customer_1 deliver_cap: 54.10589128238959 cap_limit: 40
8013 customer_2 ('customer_2', 'depot_t')
4534 customer_2 -20.28081966269108
resNode: depot_t deliver_cap: 36.18565218384055 cap_limit: 40
8014 customer_2 ('customer_2', 'customer_4')
4534 customer_2 -20.28081966269108
resNode: customer_4 deliver_cap: 65.14421819021925 cap_limit: 40
8015 customer_2 ('customer_2', 'customer_5')
4534 customer_2 -20.28081966269108
resNode: customer_5 deliver_cap: 47.44359435011013 cap_limit: 40
8016 customer_1 ('customer_1', 'customer_3')
4547 customer_1 -13.623674926900984
resNode: customer_3 deliver_cap: 63.82545266833421 cap_limit: 40
8017 customer_1 ('customer_1', 'depot_t')
4547 customer_1 -13.623674926900984
resNode: depot_t deliver_cap: 39.15495478674671 cap_limit: 40
8018 customer_1 ('customer_1', 'customer_2')
4547 customer_1 -13.623674926900984
resNode: customer_2 deliver_cap: 42.417867685642264 cap_limit: 40
8019 customer_1 ('customer_1', 'customer_4')
4547 customer_1 -13.623674926900984
resNode: customer_4 deliver_cap: 63.33228330592931 cap_limit: 40
8020 customer_1 ('customer_1', 'customer_5')
4547 customer_1 -13.623674926900984
resNode: customer_5 deliver_cap: 52.40600459948099 cap_limit: 40
8021 customer_5 ('customer_5', 'customer_3')
4550 customer_5 -19.49833480961514
resNode: customer_3 deliver_cap: 63.122298487133705 cap_limit: 40
8022 customer_5 ('customer_5', 'customer_1')
4550 customer_5 -19.49833480961514
resNode: customer_1 deliver_cap: 54.10589128238959 cap_limit: 40
8023 customer_5 ('customer_5', 'depot_t')
4550 customer_5 -19.49833480961514
resNode: depot_t deliver_cap: 35.6748896299643 cap_limit: 40
8024 customer_5 ('customer_5', 'customer_2')
4550 customer_5 -19.49833480961514
resNode: customer_2 deliver_cap: 39.75310228820386 cap_limit: 40
8025 customer_5 ('customer_5', 'customer_4')
4550 customer_5 -19.49833480961514
resNode: customer_4 deliver_cap: 62.888817371397224 cap_limit: 40
8026 customer_2 ('customer_2', 'customer_3')
4554 customer_2 -19.45596243131118
resNode: customer_3 deliver_cap: 65.37769930595573 cap_limit: 40
8027 customer_2 ('customer_2', 'customer_1')
4554 customer_2 -19.45596243131118
resNode: customer_1 deliver_cap: 54.1058912823896 cap_limit: 40
8028 customer_2 ('customer_2', 'depot_t')
4554 customer_2 -19.45596243131118
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
8029 customer_2 ('customer_2', 'customer_4')
4554 customer_2 -19.45596243131118
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8030 customer_2 ('customer_2', 'customer_5')
4554 customer_2 -19.45596243131118
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8031 customer_2 ('customer_2', 'customer_3')
4568 customer_2 -15.98647048901854
resNode: customer_3 deliver_cap: 65.37769930595573 cap_limit: 40
8032 customer_2 ('customer_2', 'customer_1')
4568 customer_2 -15.98647048901854
resNode: customer_1 deliver_cap: 54.1058912823896 cap_limit: 40
8033 customer_2 ('customer_2', 'depot_t')
4568 customer_2 -15.98647048901854
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
8034 customer_2 ('customer_2', 'customer_4')
4568 customer_2 -15.98647048901854
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8035 customer_2 ('customer_2', 'customer_5')
4568 customer_2 -15.98647048901854
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8036 customer_1 ('customer_1', 'customer_3')
4572 customer_1 -15.432333560476279
resNode: customer_3 deliver_cap: 61.00418893187335 cap_limit: 40
8037 customer_1 ('customer_1', 'depot_t')
4572 customer_1 -15.432333560476279
resNode: depot_t deliver_cap: 37.26853339519113 cap_limit: 40
8038 customer_1 ('customer_1', 'customer_2')
4572 customer_1 -15.432333560476279
resNode: customer_2 deliver_cap: 39.75310228820387 cap_limit: 40
8039 customer_1 ('customer_1', 'customer_4')
4572 customer_1 -15.432333560476279
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8040 customer_1 ('customer_1', 'customer_5')
4572 customer_1 -15.432333560476279
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8041 customer_5 ('customer_5', 'customer_3')
4575 customer_5 -17.72476322845642
resNode: customer_3 deliver_cap: 55.96540906620653 cap_limit: 40
8042 customer_5 ('customer_5', 'customer_1')
4575 customer_5 -17.72476322845642
resNode: customer_1 deliver_cap: 49.46220978606412 cap_limit: 40
8043 customer_5 ('customer_5', 'depot_t')
4575 customer_5 -17.72476322845642
resNode: depot_t deliver_cap: 28.799675450066463 cap_limit: 40
8044 customer_5 ('customer_5', 'customer_2')
4575 customer_5 -17.72476322845642
resNode: customer_2 deliver_cap: 32.41827285546858 cap_limit: 40
8045 customer_5 ('customer_5', 'customer_4')
4575 customer_5 -17.72476322845642
resNode: customer_4 deliver_cap: 55.69506251114325 cap_limit: 40
8046 customer_2 ('customer_2', 'customer_3')
4598 customer_2 -9.788707446171033
resNode: customer_3 deliver_cap: 64.02206834474387 cap_limit: 40
8047 customer_2 ('customer_2', 'customer_1')
4598 customer_2 -9.788707446171033
resNode: customer_1 deliver_cap: 51.24685714560254 cap_limit: 40
8048 customer_2 ('customer_2', 'depot_t')
4598 customer_2 -9.788707446171033
resNode: depot_t deliver_cap: 35.67389449660567 cap_limit: 40
8049 customer_2 ('customer_2', 'customer_4')
4598 customer_2 -9.788707446171033
resNode: customer_4 deliver_cap: 63.82545266833421 cap_limit: 40
8050 customer_2 ('customer_2', 'customer_5')
4598 customer_2 -9.788707446171033
resNode: customer_5 deliver_cap: 48.91966417140021 cap_limit: 40
8051 customer_2 ('customer_2', 'customer_3')
4604 customer_2 -14.19560292364001
resNode: customer_3 deliver_cap: 61.23767004760982 cap_limit: 40
8052 customer_2 ('customer_2', 'customer_1')
4604 customer_2 -14.19560292364001
resNode: customer_1 deliver_cap: 50.61955085430883 cap_limit: 40
8053 customer_2 ('customer_2', 'depot_t')
4604 customer_2 -14.19560292364001
resNode: depot_t deliver_cap: 32.917208032514836 cap_limit: 40
8054 customer_2 ('customer_2', 'customer_4')
4604 customer_2 -14.19560292364001
resNode: customer_4 deliver_cap: 61.00418893187334 cap_limit: 40
8055 customer_2 ('customer_2', 'customer_5')
4604 customer_2 -14.19560292364001
resNode: customer_5 deliver_cap: 43.30356509176422 cap_limit: 40
8056 customer_5 ('customer_5', 'customer_3')
4615 customer_5 -21.54162492667111
resNode: customer_3 deliver_cap: 69.31855006795334 cap_limit: 40
8057 customer_5 ('customer_5', 'customer_1')
4615 customer_5 -21.54162492667111
resNode: customer_1 deliver_cap: 60.994467923936384 cap_limit: 40
8058 customer_5 ('customer_5', 'depot_t')
4615 customer_5 -21.54162492667111
resNode: depot_t deliver_cap: 39.72497263331385 cap_limit: 40
8059 customer_5 ('customer_5', 'customer_2')
4615 customer_5 -21.54162492667111
resNode: customer_2 deliver_cap: 43.95053099334082 cap_limit: 40
8060 customer_5 ('customer_5', 'customer_4')
4615 customer_5 -21.54162492667111
resNode: customer_4 deliver_cap: 69.04820351289007 cap_limit: 40
8061 customer_1 ('customer_1', 'customer_3')
4622 customer_1 -9.966862521395903
resNode: customer_3 deliver_cap: 64.02206834474387 cap_limit: 40
8062 customer_1 ('customer_1', 'depot_t')
4622 customer_1 -9.966862521395903
resNode: depot_t deliver_cap: 39.30241654405395 cap_limit: 40
8063 customer_1 ('customer_1', 'customer_2')
4622 customer_1 -9.966862521395903
resNode: customer_2 deliver_cap: 42.57761792272511 cap_limit: 40
8064 customer_1 ('customer_1', 'customer_4')
4622 customer_1 -9.966862521395903
resNode: customer_4 deliver_cap: 63.52889898233896 cap_limit: 40
8065 customer_1 ('customer_1', 'customer_5')
4622 customer_1 -9.966862521395903
resNode: customer_5 deliver_cap: 52.60262027589064 cap_limit: 40
8066 customer_5 ('customer_5', 'customer_3')
4625 customer_5 -15.887604203268573
resNode: customer_3 deliver_cap: 63.35577960287017 cap_limit: 40
8067 customer_5 ('customer_5', 'customer_1')
4625 customer_5 -15.887604203268573
resNode: customer_1 deliver_cap: 54.302506958799256 cap_limit: 40
8068 customer_5 ('customer_5', 'depot_t')
4625 customer_5 -15.887604203268573
resNode: depot_t deliver_cap: 35.85921682659835 cap_limit: 40
8069 customer_5 ('customer_5', 'customer_2')
4625 customer_5 -15.887604203268573
resNode: customer_2 deliver_cap: 39.94971796461352 cap_limit: 40
8070 customer_5 ('customer_5', 'customer_4')
4625 customer_5 -15.887604203268573
resNode: customer_4 deliver_cap: 63.122298487133705 cap_limit: 40
8071 customer_2 ('customer_2', 'customer_3')
4629 customer_2 -15.845231824964614
resNode: customer_3 deliver_cap: 65.6111804216922 cap_limit: 40
8072 customer_2 ('customer_2', 'customer_1')
4629 customer_2 -15.845231824964614
resNode: customer_1 deliver_cap: 54.302506958799256 cap_limit: 40
8073 customer_2 ('customer_2', 'depot_t')
4629 customer_2 -15.845231824964614
resNode: depot_t deliver_cap: 36.36997938047461 cap_limit: 40
8074 customer_2 ('customer_2', 'customer_4')
4629 customer_2 -15.845231824964614
resNode: customer_4 deliver_cap: 65.37769930595573 cap_limit: 40
8075 customer_2 ('customer_2', 'customer_5')
4629 customer_2 -15.845231824964614
resNode: customer_5 deliver_cap: 47.677075465846606 cap_limit: 40
8076 customer_2 ('customer_2', 'customer_3')
4638 customer_2 -12.375739882671974
resNode: customer_3 deliver_cap: 65.61118042169221 cap_limit: 40
8077 customer_2 ('customer_2', 'customer_1')
4638 customer_2 -12.375739882671974
resNode: customer_1 deliver_cap: 54.30250695879926 cap_limit: 40
8078 customer_2 ('customer_2', 'depot_t')
4638 customer_2 -12.375739882671974
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
8079 customer_2 ('customer_2', 'customer_4')
4638 customer_2 -12.375739882671974
resNode: customer_4 deliver_cap: 65.37769930595574 cap_limit: 40
8080 customer_2 ('customer_2', 'customer_5')
4638 customer_2 -12.375739882671974
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
8081 customer_1 ('customer_1', 'customer_3')
4642 customer_1 -11.821602954129713
resNode: customer_3 deliver_cap: 61.23767004760982 cap_limit: 40
8082 customer_1 ('customer_1', 'depot_t')
4642 customer_1 -11.821602954129713
resNode: depot_t deliver_cap: 37.45286059182518 cap_limit: 40
8083 customer_1 ('customer_1', 'customer_2')
4642 customer_1 -11.821602954129713
resNode: customer_2 deliver_cap: 39.94971796461353 cap_limit: 40
8084 customer_1 ('customer_1', 'customer_4')
4642 customer_1 -11.821602954129713
resNode: customer_4 deliver_cap: 60.652031429754 cap_limit: 40
8085 customer_1 ('customer_1', 'customer_5')
4642 customer_1 -11.821602954129713
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
8086 customer_5 ('customer_5', 'customer_3')
4645 customer_5 -14.16011442126837
resNode: customer_3 deliver_cap: 56.23575562126981 cap_limit: 40
8087 customer_5 ('customer_5', 'customer_1')
4645 customer_5 -14.16011442126837
resNode: customer_1 deliver_cap: 49.6956909018006 cap_limit: 40
8088 customer_5 ('customer_5', 'depot_t')
4645 customer_5 -14.16011442126837
resNode: depot_t deliver_cap: 29.020868086027328 cap_limit: 40
8089 customer_5 ('customer_5', 'customer_2')
4645 customer_5 -14.16011442126837
resNode: customer_2 deliver_cap: 32.65175397120505 cap_limit: 40
8090 customer_5 ('customer_5', 'customer_4')
4645 customer_5 -14.16011442126837
resNode: customer_4 deliver_cap: 55.96540906620653 cap_limit: 40
8091 customer_2 ('customer_2', 'customer_3')
4659 customer_2 -12.310944112510702
resNode: customer_3 deliver_cap: 71.91360679187555 cap_limit: 40
8092 customer_2 ('customer_2', 'customer_1')
4659 customer_2 -12.310944112510702
resNode: customer_1 deliver_cap: 61.97908055692427 cap_limit: 40
8093 customer_2 ('customer_2', 'depot_t')
4659 customer_2 -12.310944112510702
resNode: depot_t deliver_cap: 38.807780371759065 cap_limit: 40
8094 customer_2 ('customer_2', 'customer_4')
4659 customer_2 -12.310944112510702
resNode: customer_4 deliver_cap: 71.60639479748545 cap_limit: 40
8095 customer_2 ('customer_2', 'customer_5')
4659 customer_2 -12.310944112510702
resNode: customer_5 deliver_cap: 48.316100271026095 cap_limit: 40
8096 customer_2 ('customer_2', 'customer_3')
4673 customer_2 -8.554558552578555
resNode: customer_3 deliver_cap: 68.09611305696602 cap_limit: 40
8097 customer_2 ('customer_2', 'customer_1')
4673 customer_2 -8.554558552578555
resNode: customer_1 deliver_cap: 56.39508180955616 cap_limit: 40
8098 customer_2 ('customer_2', 'depot_t')
4673 customer_2 -8.554558552578555
resNode: depot_t deliver_cap: 38.33176830305921 cap_limit: 40
8099 customer_2 ('customer_2', 'customer_4')
4673 customer_2 -8.554558552578555
resNode: customer_4 deliver_cap: 67.86263194122955 cap_limit: 40
8100 customer_2 ('customer_2', 'customer_5')
4673 customer_2 -8.554558552578555
resNode: customer_5 deliver_cap: 50.16200810112043 cap_limit: 40
8101 customer_2 ('customer_2', 'customer_3')
4679 customer_2 -10.812546071210951
resNode: customer_3 deliver_cap: 61.72456277864396 cap_limit: 40
8102 customer_2 ('customer_2', 'customer_1')
4679 customer_2 -10.812546071210951
resNode: customer_1 deliver_cap: 52.180623537074425 cap_limit: 40
8103 customer_2 ('customer_2', 'depot_t')
4679 customer_2 -10.812546071210951
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
8104 customer_2 ('customer_2', 'customer_4')
4679 customer_2 -10.812546071210951
resNode: customer_4 deliver_cap: 61.45421622358067 cap_limit: 40
8105 customer_2 ('customer_2', 'customer_5')
4679 customer_2 -10.812546071210951
resNode: customer_5 deliver_cap: 40.95875704029644 cap_limit: 40
8106 customer_5 ('customer_5', 'customer_3')
4685 customer_5 -14.911214297130057
resNode: customer_3 deliver_cap: 65.36911393683302 cap_limit: 40
8107 customer_5 ('customer_5', 'customer_1')
4685 customer_5 -14.911214297130057
resNode: customer_1 deliver_cap: 58.83144358207025 cap_limit: 40
8108 customer_5 ('customer_5', 'depot_t')
4685 customer_5 -14.911214297130057
resNode: depot_t deliver_cap: 35.088150229426184 cap_limit: 40
8109 customer_5 ('customer_5', 'customer_2')
4685 customer_5 -14.911214297130057
resNode: customer_2 deliver_cap: 39.09635871506487 cap_limit: 40
8110 customer_5 ('customer_5', 'customer_4')
4685 customer_5 -14.911214297130057
resNode: customer_4 deliver_cap: 65.06190194244293 cap_limit: 40
8111 customer_2 ('customer_2', 'customer_3')
4703 customer_2 -10.929594823670696
resNode: customer_3 deliver_cap: 63.35577960287018 cap_limit: 40
8112 customer_2 ('customer_2', 'customer_1')
4703 customer_2 -10.929594823670696
resNode: customer_1 deliver_cap: 52.403222058738606 cap_limit: 40
8113 customer_2 ('customer_2', 'depot_t')
4703 customer_2 -10.929594823670696
resNode: depot_t deliver_cap: 34.589399786667755 cap_limit: 40
8114 customer_2 ('customer_2', 'customer_4')
4703 customer_2 -10.929594823670696
resNode: customer_4 deliver_cap: 63.122298487133705 cap_limit: 40
8115 customer_2 ('customer_2', 'customer_5')
4703 customer_2 -10.929594823670696
resNode: customer_5 deliver_cap: 45.42167464702459 cap_limit: 40
8116 customer_2 ('customer_2', 'customer_3')
4709 customer_2 -12.251990213205225
resNode: customer_3 deliver_cap: 56.23575562126982 cap_limit: 40
8117 customer_2 ('customer_2', 'customer_1')
4709 customer_2 -12.251990213205225
resNode: customer_1 deliver_cap: 47.44029008297857 cap_limit: 40
8118 customer_2 ('customer_2', 'depot_t')
4709 customer_2 -12.251990213205225
resNode: depot_t deliver_cap: 27.497087638110603 cap_limit: 40
8119 customer_2 ('customer_2', 'customer_4')
4709 customer_2 -12.251990213205225
resNode: customer_4 deliver_cap: 55.96540906620653 cap_limit: 40
8120 customer_2 ('customer_2', 'customer_5')
4709 customer_2 -12.251990213205225
resNode: customer_5 deliver_cap: 35.46994988292229 cap_limit: 40
8121 customer_2 ('customer_2', 'customer_3')
4728 customer_2 -12.929503226829446
resNode: customer_3 deliver_cap: 65.92135324480454 cap_limit: 40
8122 customer_2 ('customer_2', 'customer_1')
4728 customer_2 -12.929503226829446
resNode: customer_1 deliver_cap: 52.79002612690183 cap_limit: 40
8123 customer_2 ('customer_2', 'depot_t')
4728 customer_2 -12.929503226829446
resNode: depot_t deliver_cap: 37.09835817165117 cap_limit: 40
8124 customer_2 ('customer_2', 'customer_4')
4728 customer_2 -12.929503226829446
resNode: customer_4 deliver_cap: 65.72473756839487 cap_limit: 40
8125 customer_2 ('customer_2', 'customer_5')
4728 customer_2 -12.929503226829446
resNode: customer_5 deliver_cap: 50.81894907146087 cap_limit: 40
8126 customer_2 ('customer_2', 'customer_3')
4734 customer_2 -17.781543602750137
resNode: customer_3 deliver_cap: 63.49307086643184 cap_limit: 40
8127 customer_2 ('customer_2', 'customer_1')
4734 customer_2 -17.781543602750137
resNode: customer_1 deliver_cap: 52.51883575436948 cap_limit: 40
8128 customer_2 ('customer_2', 'depot_t')
4734 customer_2 -17.781543602750137
resNode: depot_t deliver_cap: 34.6977876263217 cap_limit: 40
8129 customer_2 ('customer_2', 'customer_4')
4734 customer_2 -17.781543602750137
resNode: customer_4 deliver_cap: 63.259589750695376 cap_limit: 40
8130 customer_2 ('customer_2', 'customer_5')
4734 customer_2 -17.781543602750137
resNode: customer_5 deliver_cap: 45.55896591058625 cap_limit: 40
8131 customer_5 ('customer_5', 'customer_3')
4750 customer_5 -23.970188869806776
resNode: customer_3 deliver_cap: 69.31855006795335 cap_limit: 40
8132 customer_5 ('customer_5', 'customer_1')
4750 customer_5 -23.970188869806776
resNode: customer_1 deliver_cap: 60.994467923936384 cap_limit: 40
8133 customer_5 ('customer_5', 'depot_t')
4750 customer_5 -23.970188869806776
resNode: depot_t deliver_cap: 39.724972633313854 cap_limit: 40
8134 customer_5 ('customer_5', 'customer_2')
4750 customer_5 -23.970188869806776
resNode: customer_2 deliver_cap: 43.95053099334083 cap_limit: 40
8135 customer_5 ('customer_5', 'customer_4')
4750 customer_5 -23.970188869806776
resNode: customer_4 deliver_cap: 69.04820351289007 cap_limit: 40
8136 customer_2 ('customer_2', 'customer_3')
4753 customer_2 -13.306589765421755
resNode: customer_3 deliver_cap: 65.92135324480454 cap_limit: 40
8137 customer_2 ('customer_2', 'customer_1')
4753 customer_2 -13.306589765421755
resNode: customer_1 deliver_cap: 52.79002612690183 cap_limit: 40
8138 customer_2 ('customer_2', 'depot_t')
4753 customer_2 -13.306589765421755
resNode: depot_t deliver_cap: 37.09835817165117 cap_limit: 40
8139 customer_2 ('customer_2', 'customer_4')

4780 customer_5 -14.622419248835529
resNode: customer_1 deliver_cap: 43.51172457095858 cap_limit: 40
8173 customer_5 ('customer_5', 'depot_t')
4780 customer_5 -14.622419248835529
resNode: depot_t deliver_cap: 28.12516207691024 cap_limit: 40
8174 customer_5 ('customer_5', 'customer_2')
4780 customer_5 -14.622419248835529
resNode: customer_2 deliver_cap: 31.850083513182675 cap_limit: 40
8175 customer_5 ('customer_5', 'customer_4')
4780 customer_5 -14.622419248835529
resNode: customer_4 deliver_cap: 52.40600459948098 cap_limit: 40
8176 customer_2 ('customer_2', 'customer_3')
4784 customer_2 -14.960581054889229
resNode: customer_3 deliver_cap: 65.42818388239962 cap_limit: 40
8177 customer_2 ('customer_2', 'customer_1')
4784 customer_2 -14.960581054889229
resNode: customer_1 deliver_cap: 52.389326019947845 cap_limit: 40
8178 customer_2 ('customer_2', 'depot_t')
4784 customer_2 -14.960581054889229
resNode: depot_t deliver_cap: 36.72848114984749 cap_limit: 40
8179 customer_2 ('customer_2', 'customer_4')
4784 customer_2 -14.960581054889229
resNode: customer_4 deliver_cap: 65.23156820598996 cap_limit: 40
8180 customer_2 ('customer_2', 'customer_5')
4784 customer_2 -14.960581054889229
resNode: customer_5 deliver_cap: 50.325779709055965 cap_limit: 40
8181 customer_1 ('customer_1', 'customer_3')
4787 customer_1 -16.829273530716076
resNode: customer_3 deliver_cap: 64.01666477353933 cap_limit: 40
8182 customer_1 ('customer_1', 'depot_t')
4787 customer_1 -16.829273530716076
resNode: depot_t deliver_cap: 39.29836386565055 cap_limit: 40
8183 customer_1 ('customer_1', 'customer_2')
4787 customer_1 -16.829273530716076
resNode: customer_2 deliver_cap: 42.57322752112143 cap_limit: 40
8184 customer_1 ('customer_1', 'customer_4')
4787 customer_1 -16.829273530716076
resNode: customer_4 deliver_cap: 63.523495411134434 cap_limit: 40
8185 customer_1 ('customer_1', 'customer_5')
4787 customer_1 -16.829273530716076
resNode: customer_5 deliver_cap: 52.59721670468611 cap_limit: 40
8186 customer_2 ('customer_2', 'customer_3')
4789 customer_2 -14.554508742837754
resNode: customer_3 deliver_cap: 54.5019051759513 cap_limit: 40
8187 customer_2 ('customer_2', 'customer_1')
4789 customer_2 -14.554508742837754
resNode: customer_1 deliver_cap: 43.511724570958584 cap_limit: 40
8188 customer_2 ('customer_2', 'depot_t')
4789 customer_2 -14.554508742837754
resNode: depot_t deliver_cap: 28.53377212001125 cap_limit: 40
8189 customer_2 ('customer_2', 'customer_4')
4789 customer_2 -14.554508742837754
resNode: customer_4 deliver_cap: 54.305289499541644 cap_limit: 40
8190 customer_2 ('customer_2', 'customer_5')
4789 customer_2 -14.554508742837754
resNode: customer_5 deliver_cap: 39.39950100260764 cap_limit: 40
8191 customer_2 ('customer_2', 'customer_3')
4798 customer_2 -13.168858979371027
resNode: customer_3 deliver_cap: 65.42818388239962 cap_limit: 40
8192 customer_2 ('customer_2', 'customer_1')
4798 customer_2 -13.168858979371027
resNode: customer_1 deliver_cap: 52.389326019947845 cap_limit: 40
8193 customer_2 ('customer_2', 'depot_t')
4798 customer_2 -13.168858979371027
resNode: depot_t deliver_cap: 36.72848114984749 cap_limit: 40
8194 customer_2 ('customer_2', 'customer_4')
4798 customer_2 -13.168858979371027
resNode: customer_4 deliver_cap: 65.23156820598996 cap_limit: 40
8195 customer_2 ('customer_2', 'customer_5')
4798 customer_2 -13.168858979371027
resNode: customer_5 deliver_cap: 50.325779709055965 cap_limit: 40
8196 customer_5 ('customer_5', 'customer_3')
4805 customer_5 -20.123979580953886
resNode: customer_3 deliver_cap: 65.37769930595574 cap_limit: 40
8197 customer_5 ('customer_5', 'customer_1')
4805 customer_5 -20.123979580953886
resNode: customer_1 deliver_cap: 56.005176182450256 cap_limit: 40
8198 customer_5 ('customer_5', 'depot_t')
4805 customer_5 -20.123979580953886
resNode: depot_t deliver_cap: 37.45546922377117 cap_limit: 40
8199 customer_5 ('customer_5', 'customer_2')
4805 customer_5 -20.123979580953886
resNode: customer_2 deliver_cap: 41.65238718826453 cap_limit: 40
8200 customer_5 ('customer_5', 'customer_4')
4805 customer_5 -20.123979580953886
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8201 customer_2 ('customer_2', 'customer_3')
4809 customer_2 -19.042935772929248
resNode: customer_3 deliver_cap: 65.37769930595573 cap_limit: 40
8202 customer_2 ('customer_2', 'customer_1')
4809 customer_2 -19.042935772929248
resNode: customer_1 deliver_cap: 54.1058912823896 cap_limit: 40
8203 customer_2 ('customer_2', 'depot_t')
4809 customer_2 -19.042935772929248
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
8204 customer_2 ('customer_2', 'customer_4')
4809 customer_2 -19.042935772929248
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8205 customer_2 ('customer_2', 'customer_5')
4809 customer_2 -19.042935772929248
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8206 customer_2 ('customer_2', 'customer_3')
4813 customer_2 -15.358474287929067
resNode: customer_3 deliver_cap: 65.61118042169221 cap_limit: 40
8207 customer_2 ('customer_2', 'customer_1')
4813 customer_2 -15.358474287929067
resNode: customer_1 deliver_cap: 54.30250695879926 cap_limit: 40
8208 customer_2 ('customer_2', 'depot_t')
4813 customer_2 -15.358474287929067
resNode: depot_t deliver_cap: 36.36997938047462 cap_limit: 40
8209 customer_2 ('customer_2', 'customer_4')
4813 customer_2 -15.358474287929067
resNode: customer_4 deliver_cap: 65.37769930595574 cap_limit: 40
8210 customer_2 ('customer_2', 'customer_5')
4813 customer_2 -15.358474287929067
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
8211 customer_2 ('customer_2', 'customer_3')
4818 customer_2 -11.085016800545112
resNode: customer_3 deliver_cap: 54.5019051759513 cap_limit: 40
8212 customer_2 ('customer_2', 'customer_1')
4818 customer_2 -11.085016800545112
resNode: customer_1 deliver_cap: 43.511724570958584 cap_limit: 40
8213 customer_2 ('customer_2', 'depot_t')
4818 customer_2 -11.085016800545112
resNode: depot_t deliver_cap: 28.53377212001125 cap_limit: 40
8214 customer_2 ('customer_2', 'customer_4')
4818 customer_2 -11.085016800545112
resNode: customer_4 deliver_cap: 54.305289499541644 cap_limit: 40
8215 customer_2 ('customer_2', 'customer_5')
4818 customer_2 -11.085016800545112
resNode: customer_5 deliver_cap: 39.39950100260764 cap_limit: 40
8216 customer_5 ('customer_5', 'customer_3')
4820 customer_5 -19.279256808295038
resNode: customer_3 deliver_cap: 63.34936286206479 cap_limit: 40
8217 customer_5 ('customer_5', 'customer_1')
4820 customer_5 -19.279256808295038
resNode: customer_1 deliver_cap: 54.29710338759472 cap_limit: 40
8218 customer_5 ('customer_5', 'depot_t')
4820 customer_5 -19.279256808295038
resNode: depot_t deliver_cap: 35.8541509785941 cap_limit: 40
8219 customer_5 ('customer_5', 'customer_2')
4820 customer_5 -19.279256808295038
resNode: customer_2 deliver_cap: 39.94431439340899 cap_limit: 40
8220 customer_5 ('customer_5', 'customer_4')
4820 customer_5 -19.279256808295038
resNode: customer_4 deliver_cap: 63.11588174632831 cap_limit: 40
8221 customer_3 ('customer_3', 'customer_1')
4821 customer_3 -15.495617835119724
resNode: customer_1 deliver_cap: 52.51883575436949 cap_limit: 40
8222 customer_3 ('customer_3', 'depot_t')
4821 customer_3 -15.495617835119724
resNode: depot_t deliver_cap: 37.63979642040523 cap_limit: 40
8223 customer_3 ('customer_3', 'customer_2')
4821 customer_3 -15.495617835119724
resNode: customer_2 deliver_cap: 41.84900286467419 cap_limit: 40
8224 customer_3 ('customer_3', 'customer_4')
4821 customer_3 -15.495617835119724
resNode: customer_4 deliver_cap: 52.41740891994247 cap_limit: 40
8225 customer_3 ('customer_3', 'customer_5')
4821 customer_3 -15.495617835119724
resNode: customer_5 deliver_cap: 47.67707546584663 cap_limit: 40
8226 customer_1 ('customer_1', 'customer_3')
4822 customer_1 -10.476735811435322
resNode: customer_3 deliver_cap: 50.81894907146087 cap_limit: 40
8227 customer_1 ('customer_1', 'depot_t')
4822 customer_1 -10.476735811435322
resNode: depot_t deliver_cap: 29.400077089091702 cap_limit: 40
8228 customer_1 ('customer_1', 'customer_2')
4822 customer_1 -10.476735811435322
resNode: customer_2 deliver_cap: 31.85008351318268 cap_limit: 40
8229 customer_1 ('customer_1', 'customer_4')
4822 customer_1 -10.476735811435322
resNode: customer_4 deliver_cap: 50.325779709055965 cap_limit: 40
8230 customer_1 ('customer_1', 'customer_5')
4822 customer_1 -10.476735811435322
resNode: customer_5 deliver_cap: 39.39950100260764 cap_limit: 40
8231 customer_4 ('customer_4', 'customer_3')
4824 customer_4 -15.465920675662012
resNode: customer_3 deliver_cap: 52.41740891994247 cap_limit: 40
8232 customer_4 ('customer_4', 'customer_1')
4824 customer_4 -15.465920675662012
resNode: customer_1 deliver_cap: 52.025666391964585 cap_limit: 40
8233 customer_4 ('customer_4', 'depot_t')
4824 customer_4 -15.465920675662012
resNode: depot_t deliver_cap: 37.45546922377117 cap_limit: 40
8234 customer_4 ('customer_4', 'customer_2')
4824 customer_4 -15.465920675662012
resNode: customer_2 deliver_cap: 41.65238718826453 cap_limit: 40
8235 customer_4 ('customer_4', 'customer_5')
4824 customer_4 -15.465920675662012
resNode: customer_5 deliver_cap: 47.443594350110146 cap_limit: 40
8236 customer_5 ('customer_5', 'customer_3')
4825 customer_5 -13.302996413632293
resNode: customer_3 deliver_cap: 47.67707546584663 cap_limit: 40
8237 customer_5 ('customer_5', 'customer_1')
4825 customer_5 -13.302996413632293
resNode: customer_1 deliver_cap: 41.09938768551626 cap_limit: 40
8238 customer_5 ('customer_5', 'depot_t')
4825 customer_5 -13.302996413632293
resNode: depot_t deliver_cap: 23.481292507895553 cap_limit: 40
8239 customer_5 ('customer_5', 'customer_2')
4825 customer_5 -13.302996413632293
resNode: customer_2 deliver_cap: 26.74659869133054 cap_limit: 40
8240 customer_5 ('customer_5', 'customer_4')
4825 customer_5 -13.302996413632293
resNode: customer_4 deliver_cap: 47.443594350110146 cap_limit: 40
8241 customer_2 ('customer_2', 'customer_3')
4829 customer_2 -15.316488648695755
resNode: customer_3 deliver_cap: 65.37769930595574 cap_limit: 40
8242 customer_2 ('customer_2', 'customer_1')
4829 customer_2 -15.316488648695755
resNode: customer_1 deliver_cap: 54.10589128238961 cap_limit: 40
8243 customer_2 ('customer_2', 'depot_t')
4829 customer_2 -15.316488648695755
resNode: depot_t deliver_cap: 36.18565218384057 cap_limit: 40
8244 customer_2 ('customer_2', 'customer_4')
4829 customer_2 -15.316488648695755
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8245 customer_2 ('customer_2', 'customer_5')
4829 customer_2 -15.316488648695755
resNode: customer_5 deliver_cap: 47.443594350110146 cap_limit: 40
8246 customer_2 ('customer_2', 'customer_3')
4853 customer_2 -12.686810934129602
resNode: customer_3 deliver_cap: 65.42818388239962 cap_limit: 40
8247 customer_2 ('customer_2', 'customer_1')
4853 customer_2 -12.686810934129602
resNode: customer_1 deliver_cap: 52.389326019947845 cap_limit: 40
8248 customer_2 ('customer_2', 'depot_t')
4853 customer_2 -12.686810934129602
resNode: depot_t deliver_cap: 36.72848114984749 cap_limit: 40
8249 customer_2 ('customer_2', 'customer_4')
4853 customer_2 -12.686810934129602
resNode: customer_4 deliver_cap: 65.23156820598996 cap_limit: 40
8250 customer_2 ('customer_2', 'customer_5')
4853 customer_2 -12.686810934129602
resNode: customer_5 deliver_cap: 50.325779709055965 cap_limit: 40
8251 customer_2 ('customer_2', 'customer_3')
4859 customer_2 -17.423264740736645
resNode: customer_3 deliver_cap: 62.90743224857603 cap_limit: 40
8252 customer_2 ('customer_2', 'customer_1')
4859 customer_2 -17.423264740736645
resNode: customer_1 deliver_cap: 52.025666391964585 cap_limit: 40
8253 customer_2 ('customer_2', 'depot_t')
4859 customer_2 -17.423264740736645
resNode: depot_t deliver_cap: 34.23544134906711 cap_limit: 40
8254 customer_2 ('customer_2', 'customer_4')
4859 customer_2 -17.423264740736645
resNode: customer_4 deliver_cap: 62.67395113283956 cap_limit: 40
8255 customer_2 ('customer_2', 'customer_5')
4859 customer_2 -17.423264740736645
resNode: customer_5 deliver_cap: 44.97332729273043 cap_limit: 40
8256 customer_5 ('customer_5', 'customer_3')
4865 customer_5 -23.496323438479628
resNode: customer_3 deliver_cap: 68.64044219464661 cap_limit: 40
8257 customer_5 ('customer_5', 'customer_1')
4865 customer_5 -23.496323438479628
resNode: customer_1 deliver_cap: 60.40882930608056 cap_limit: 40
8258 customer_5 ('customer_5', 'depot_t')
4865 customer_5 -23.496323438479628
resNode: depot_t deliver_cap: 39.170157100608336 cap_limit: 40
8259 customer_5 ('customer_5', 'customer_2')
4865 customer_5 -23.496323438479628
resNode: customer_2 deliver_cap: 43.364892375485 cap_limit: 40
8260 customer_5 ('customer_5', 'customer_4')
4865 customer_5 -23.496323438479628
resNode: customer_4 deliver_cap: 68.37009563958333 cap_limit: 40
8261 customer_1 ('customer_1', 'customer_3')
4877 customer_1 -14.014575803030313
resNode: customer_3 deliver_cap: 64.01666477353933 cap_limit: 40
8262 customer_1 ('customer_1', 'depot_t')
4877 customer_1 -14.014575803030313
resNode: depot_t deliver_cap: 39.29836386565055 cap_limit: 40
8263 customer_1 ('customer_1', 'customer_2')
4877 customer_1 -14.014575803030313
resNode: customer_2 deliver_cap: 42.57322752112143 cap_limit: 40
8264 customer_1 ('customer_1', 'customer_4')
4877 customer_1 -14.014575803030313
resNode: customer_4 deliver_cap: 63.523495411134434 cap_limit: 40
8265 customer_1 ('customer_1', 'customer_5')
4877 customer_1 -14.014575803030313
resNode: customer_5 deliver_cap: 52.59721670468611 cap_limit: 40
8266 customer_5 ('customer_5', 'customer_3')
4880 customer_5 -19.93405102290192
resNode: customer_3 deliver_cap: 63.34936286206479 cap_limit: 40
8267 customer_5 ('customer_5', 'customer_1')
4880 customer_5 -19.93405102290192
resNode: customer_1 deliver_cap: 54.29710338759472 cap_limit: 40
8268 customer_5 ('customer_5', 'depot_t')
4880 customer_5 -19.93405102290192
resNode: depot_t deliver_cap: 35.8541509785941 cap_limit: 40
8269 customer_5 ('customer_5', 'customer_2')
4880 customer_5 -19.93405102290192
resNode: customer_2 deliver_cap: 39.94431439340899 cap_limit: 40
8270 customer_5 ('customer_5', 'customer_4')
4880 customer_5 -19.93405102290192
resNode: customer_4 deliver_cap: 63.11588174632831 cap_limit: 40
8271 customer_2 ('customer_2', 'customer_3')
4884 customer_2 -19.89167864459796
resNode: customer_3 deliver_cap: 65.60476368088682 cap_limit: 40
8272 customer_2 ('customer_2', 'customer_1')
4884 customer_2 -19.89167864459796
resNode: customer_1 deliver_cap: 54.297103387594724 cap_limit: 40
8273 customer_2 ('customer_2', 'depot_t')
4884 customer_2 -19.89167864459796
resNode: depot_t deliver_cap: 36.36491353247036 cap_limit: 40
8274 customer_2 ('customer_2', 'customer_4')
4884 customer_2 -19.89167864459796
resNode: customer_4 deliver_cap: 65.37128256515035 cap_limit: 40
8275 customer_2 ('customer_2', 'customer_5')
4884 customer_2 -19.89167864459796
resNode: customer_5 deliver_cap: 47.67065872504123 cap_limit: 40
8276 customer_2 ('customer_2', 'customer_3')
4888 customer_2 -16.22708270087671
resNode: customer_3 deliver_cap: 67.86658124051424 cap_limit: 40
8277 customer_2 ('customer_2', 'customer_1')
4888 customer_2 -16.22708270087671
resNode: customer_1 deliver_cap: 56.20179185885992 cap_limit: 40
8278 customer_2 ('customer_2', 'depot_t')
4888 customer_2 -16.22708270087671
resNode: depot_t deliver_cap: 38.15055897428148 cap_limit: 40
8279 customer_2 ('customer_2', 'customer_4')
4888 customer_2 -16.22708270087671
resNode: customer_4 deliver_cap: 67.63310012477777 cap_limit: 40
8280 customer_2 ('customer_2', 'customer_5')
4888 customer_2 -16.22708270087671
resNode: customer_5 deliver_cap: 49.932476284668645 cap_limit: 40
8281 customer_2 ('customer_2', 'customer_3')
4893 customer_2 -10.914953783772088
resNode: customer_3 deliver_cap: 54.5019051759513 cap_limit: 40
8282 customer_2 ('customer_2', 'customer_1')
4893 customer_2 -10.914953783772088
resNode: customer_1 deliver_cap: 43.511724570958584 cap_limit: 40
8283 customer_2 ('customer_2', 'depot_t')
4893 customer_2 -10.914953783772088
resNode: depot_t deliver_cap: 28.53377212001125 cap_limit: 40
8284 customer_2 ('customer_2', 'customer_4')
4893 customer_2 -10.914953783772088
resNode: customer_4 deliver_cap: 54.305289499541644 cap_limit: 40
8285 customer_2 ('customer_2', 'customer_5')
4893 customer_2 -10.914953783772088
resNode: customer_5 deliver_cap: 39.39950100260764 cap_limit: 40
8286 customer_5 ('customer_5', 'customer_3')
4895 customer_5 -19.109193791522014
resNode: customer_3 deliver_cap: 63.34936286206479 cap_limit: 40
8287 customer_5 ('customer_5', 'customer_1')
4895 customer_5 -19.109193791522014
resNode: customer_1 deliver_cap: 54.29710338759472 cap_limit: 40
8288 customer_5 ('customer_5', 'depot_t')
4895 customer_5 -19.109193791522014
resNode: depot_t deliver_cap: 35.8541509785941 cap_limit: 40
8289 customer_5 ('customer_5', 'customer_2')
4895 customer_5 -19.109193791522014
resNode: customer_2 deliver_cap: 39.94431439340899 cap_limit: 40
8290 customer_5 ('customer_5', 'customer_4')
4895 customer_5 -19.109193791522014
resNode: customer_4 deliver_cap: 63.11588174632831 cap_limit: 40
8291 customer_2 ('customer_2', 'customer_3')
4899 customer_2 -16.185097061643397
resNode: customer_3 deliver_cap: 67.63310012477777 cap_limit: 40
8292 customer_2 ('customer_2', 'customer_1')
4899 customer_2 -16.185097061643397
resNode: customer_1 deliver_cap: 56.00517618245026 cap_limit: 40
8293 customer_2 ('customer_2', 'depot_t')
4899 customer_2 -16.185097061643397
resNode: depot_t deliver_cap: 37.96623177764743 cap_limit: 40
8294 customer_2 ('customer_2', 'customer_4')
4899 customer_2 -16.185097061643397
resNode: customer_4 deliver_cap: 67.3996190090413 cap_limit: 40
8295 customer_2 ('customer_2', 'customer_5')
4899 customer_2 -16.185097061643397
resNode: customer_5 deliver_cap: 49.69899516893218 cap_limit: 40
8296 customer_1 ('customer_1', 'customer_3')
4902 customer_1 -16.038112790536086
resNode: customer_3 deliver_cap: 61.23125330680443 cap_limit: 40
8297 customer_1 ('customer_1', 'depot_t')
4902 customer_1 -16.038112790536086
resNode: depot_t deliver_cap: 37.447794743820936 cap_limit: 40
8298 customer_1 ('customer_1', 'customer_2')
4902 customer_1 -16.038112790536086
resNode: customer_2 deliver_cap: 39.944314393408995 cap_limit: 40
8299 customer_1 ('customer_1', 'customer_4')
4902 customer_1 -16.038112790536086
resNode: customer_4 deliver_cap: 60.645614688948605 cap_limit: 40
8300 customer_1 ('customer_1', 'customer_5')
4902 customer_1 -16.038112790536086
resNode: customer_5 deliver_cap: 47.67065872504123 cap_limit: 40
8301 customer_2 ('customer_2', 'customer_3')
4904 customer_2 -13.09056101855531
resNode: customer_3 deliver_cap: 49.93247628466865 cap_limit: 40
8302 customer_2 ('customer_2', 'customer_1')
4904 customer_2 -13.09056101855531
resNode: customer_1 deliver_cap: 41.09938768551626 cap_limit: 40
8303 customer_2 ('customer_2', 'depot_t')
4904 customer_2 -13.09056101855531
resNode: depot_t deliver_cap: 23.992055061771815 cap_limit: 40
8304 customer_2 ('customer_2', 'customer_4')
4904 customer_2 -13.09056101855531
resNode: customer_4 deliver_cap: 49.698995168932186 cap_limit: 40
8305 customer_2 ('customer_2', 'customer_5')
4904 customer_2 -13.09056101855531
resNode: customer_5 deliver_cap: 31.99837132882307 cap_limit: 40
8306 customer_1 ('customer_1', 'customer_3')
4917 customer_1 -9.117675106942746
resNode: customer_3 deliver_cap: 62.2383971403141 cap_limit: 40
8307 customer_1 ('customer_1', 'depot_t')
4917 customer_1 -9.117675106942746
resNode: depot_t deliver_cap: 37.96466314073162 cap_limit: 40
8308 customer_1 ('customer_1', 'customer_2')
4917 customer_1 -9.117675106942746
resNode: customer_2 deliver_cap: 41.128385069125926 cap_limit: 40
8309 customer_1 ('customer_1', 'customer_4')
4917 customer_1 -9.117675106942746
resNode: customer_4 deliver_cap: 61.74522777790919 cap_limit: 40
8310 customer_1 ('customer_1', 'customer_5')

resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
8381 customer_5 ('customer_5', 'customer_3')
4975 customer_5 -13.979803708476378
resNode: customer_3 deliver_cap: 56.23575562126982 cap_limit: 40
8382 customer_5 ('customer_5', 'customer_1')
4975 customer_5 -13.979803708476378
resNode: customer_1 deliver_cap: 49.6956909018006 cap_limit: 40
8383 customer_5 ('customer_5', 'depot_t')
4975 customer_5 -13.979803708476378
resNode: depot_t deliver_cap: 29.020868086027335 cap_limit: 40
8384 customer_5 ('customer_5', 'customer_2')
4975 customer_5 -13.979803708476378
resNode: customer_2 deliver_cap: 32.65175397120505 cap_limit: 40
8385 customer_5 ('customer_5', 'customer_4')
4975 customer_5 -13.979803708476378
resNode: customer_4 deliver_cap: 55.96540906620653 cap_limit: 40
8386 customer_2 ('customer_2', 'customer_3')
4978 customer_2 -10.41006972526598
resNode: customer_3 deliver_cap: 62.23839714031409 cap_limit: 40
8387 customer_2 ('customer_2', 'customer_1')
4978 customer_2 -10.41006972526598
resNode: customer_1 deliver_cap: 49.797624292003356 cap_limit: 40
8388 customer_2 ('customer_2', 'depot_t')
4978 customer_2 -10.41006972526598
resNode: depot_t deliver_cap: 34.336141093283345 cap_limit: 40
8389 customer_2 ('customer_2', 'customer_4')
4978 customer_2 -10.41006972526598
resNode: customer_4 deliver_cap: 62.04178146390443 cap_limit: 40
8390 customer_2 ('customer_2', 'customer_5')
4978 customer_2 -10.41006972526598
resNode: customer_5 deliver_cap: 47.135992966970434 cap_limit: 40
8391 customer_1 ('customer_1', 'customer_3')
4982 customer_1 -10.952712518809449
resNode: customer_3 deliver_cap: 62.23839714031409 cap_limit: 40
8392 customer_1 ('customer_1', 'depot_t')
4982 customer_1 -10.952712518809449
resNode: depot_t deliver_cap: 37.964663140731616 cap_limit: 40
8393 customer_1 ('customer_1', 'customer_2')
4982 customer_1 -10.952712518809449
resNode: customer_2 deliver_cap: 41.12838506912592 cap_limit: 40
8394 customer_1 ('customer_1', 'customer_4')
4982 customer_1 -10.952712518809449
resNode: customer_4 deliver_cap: 61.74522777790919 cap_limit: 40
8395 customer_1 ('customer_1', 'customer_5')
4982 customer_1 -10.952712518809449
resNode: customer_5 deliver_cap: 50.81894907146087 cap_limit: 40
8396 customer_5 ('customer_5', 'customer_3')
4985 customer_5 -16.455406262143892
resNode: customer_3 deliver_cap: 61.23767004760982 cap_limit: 40
8397 customer_5 ('customer_5', 'customer_1')
4985 customer_5 -16.455406262143892
resNode: customer_1 deliver_cap: 52.518835754369476 cap_limit: 40
8398 customer_5 ('customer_5', 'depot_t')
4985 customer_5 -16.455406262143892
resNode: depot_t deliver_cap: 34.18702507244544 cap_limit: 40
8399 customer_5 ('customer_5', 'customer_2')
4985 customer_5 -16.455406262143892
resNode: customer_2 deliver_cap: 38.16604676018375 cap_limit: 40
8400 customer_5 ('customer_5', 'customer_4')
4985 customer_5 -16.455406262143892
resNode: customer_4 deliver_cap: 61.00418893187334 cap_limit: 40
8401 customer_2 ('customer_2', 'customer_3')
4989 customer_2 -12.500343714174926
resNode: customer_3 deliver_cap: 65.97800350170567 cap_limit: 40
8402 customer_2 ('customer_2', 'customer_1')
4989 customer_2 -12.500343714174926
resNode: customer_1 deliver_cap: 54.61141060512639 cap_limit: 40
8403 customer_2 ('customer_2', 'depot_t')
4989 customer_2 -12.500343714174926
resNode: depot_t deliver_cap: 36.659576548906294 cap_limit: 40
8404 customer_2 ('customer_2', 'customer_4')
4989 customer_2 -12.500343714174926
resNode: customer_4 deliver_cap: 65.7445223859692 cap_limit: 40
8405 customer_2 ('customer_2', 'customer_5')
4989 customer_2 -12.500343714174926
resNode: customer_5 deliver_cap: 48.043898545860074 cap_limit: 40
8406 customer_2 ('customer_2', 'customer_3')
4994 customer_2 -15.374362454119261
resNode: customer_3 deliver_cap: 61.23767004760982 cap_limit: 40
8407 customer_2 ('customer_2', 'customer_1')
4994 customer_2 -15.374362454119261
resNode: customer_1 deliver_cap: 50.61955085430883 cap_limit: 40
8408 customer_2 ('customer_2', 'depot_t')
4994 customer_2 -15.374362454119261
resNode: depot_t deliver_cap: 32.917208032514836 cap_limit: 40
8409 customer_2 ('customer_2', 'customer_4')
4994 customer_2 -15.374362454119261
resNode: customer_4 deliver_cap: 61.00418893187334 cap_limit: 40
8410 customer_2 ('customer_2', 'customer_5')
4994 customer_2 -15.374362454119261
resNode: customer_5 deliver_cap: 43.30356509176422 cap_limit: 40
8411 customer_1 ('customer_1', 'customer_3')
4996 customer_1 -11.329799057401758
resNode: customer_3 deliver_cap: 62.23839714031409 cap_limit: 40
8412 customer_1 ('customer_1', 'depot_t')
4996 customer_1 -11.329799057401758
resNode: depot_t deliver_cap: 37.964663140731616 cap_limit: 40
8413 customer_1 ('customer_1', 'customer_2')
4996 customer_1 -11.329799057401758
resNode: customer_2 deliver_cap: 41.12838506912592 cap_limit: 40
8414 customer_1 ('customer_1', 'customer_4')
4996 customer_1 -11.329799057401758
resNode: customer_4 deliver_cap: 61.74522777790919 cap_limit: 40
8415 customer_1 ('customer_1', 'customer_5')
4996 customer_1 -11.329799057401758
resNode: customer_5 deliver_cap: 50.81894907146087 cap_limit: 40
8416 customer_2 ('customer_2', 'customer_3')
4998 customer_2 -9.975773295646047
resNode: customer_3 deliver_cap: 56.406593647216496 cap_limit: 40
8417 customer_2 ('customer_2', 'customer_1')
4998 customer_2 -9.975773295646047
resNode: customer_1 deliver_cap: 45.05928395386156 cap_limit: 40
8418 customer_2 ('customer_2', 'depot_t')
4998 customer_2 -9.975773295646047
resNode: depot_t deliver_cap: 29.962288473460145 cap_limit: 40
8419 customer_2 ('customer_2', 'customer_4')
4998 customer_2 -9.975773295646047
resNode: customer_4 deliver_cap: 56.20997797080683 cap_limit: 40
8420 customer_2 ('customer_2', 'customer_5')
4998 customer_2 -9.975773295646047
resNode: customer_5 deliver_cap: 41.30418947387284 cap_limit: 40
8421 customer_4 ('customer_4', 'customer_3')
4999 customer_4 -14.572948566011444
resNode: customer_3 deliver_cap: 55.13582267095275 cap_limit: 40
8422 customer_4 ('customer_4', 'customer_1')
4999 customer_4 -14.572948566011444
resNode: customer_1 deliver_cap: 54.31485691913114 cap_limit: 40
8423 customer_4 ('customer_4', 'depot_t')
4999 customer_4 -14.572948566011444
resNode: depot_t deliver_cap: 39.601585342989814 cap_limit: 40
8424 customer_4 ('customer_4', 'customer_2')
4999 customer_4 -14.572948566011444
resNode: customer_2 deliver_cap: 43.94157771543108 cap_limit: 40
8425 customer_4 ('customer_4', 'customer_5')
4999 customer_4 -14.572948566011444
resNode: customer_5 deliver_cap: 50.16200810112043 cap_limit: 40
8426 customer_5 ('customer_5', 'customer_3')
5000 customer_5 -17.696458540381876
resNode: customer_3 deliver_cap: 63.35577960287018 cap_limit: 40
8427 customer_5 ('customer_5', 'customer_1')
5000 customer_5 -17.696458540381876
resNode: customer_1 deliver_cap: 54.302506958799256 cap_limit: 40
8428 customer_5 ('customer_5', 'depot_t')
5000 customer_5 -17.696458540381876
resNode: depot_t deliver_cap: 35.859216826598356 cap_limit: 40
8429 customer_5 ('customer_5', 'customer_2')
5000 customer_5 -17.696458540381876
resNode: customer_2 deliver_cap: 39.94971796461353 cap_limit: 40
8430 customer_5 ('customer_5', 'customer_4')
5000 customer_5 -17.696458540381876
resNode: customer_4 deliver_cap: 63.122298487133705 cap_limit: 40
8431 customer_3 ('customer_3', 'customer_1')
5001 customer_3 -12.846107716223099
resNode: customer_1 deliver_cap: 49.79762429200335 cap_limit: 40
8432 customer_3 ('customer_3', 'depot_t')
5001 customer_3 -12.846107716223099
resNode: depot_t deliver_cap: 36.68974812855016 cap_limit: 40
8433 customer_3 ('customer_3', 'customer_2')
5001 customer_3 -12.846107716223099
resNode: customer_2 deliver_cap: 41.12838506912592 cap_limit: 40
8434 customer_3 ('customer_3', 'customer_4')
5001 customer_3 -12.846107716223099
resNode: customer_4 deliver_cap: 52.91152392221777 cap_limit: 40
8435 customer_3 ('customer_3', 'customer_5')
5001 customer_3 -12.846107716223099
resNode: customer_5 deliver_cap: 48.91966417140021 cap_limit: 40
8436 customer_2 ('customer_2', 'customer_3')
5003 customer_2 -4.962236165368868
resNode: customer_3 deliver_cap: 43.6781260239983 cap_limit: 40
8437 customer_2 ('customer_2', 'customer_1')
5003 customer_2 -4.962236165368868
resNode: customer_1 deliver_cap: 33.005425107304966 cap_limit: 40
8438 customer_2 ('customer_2', 'depot_t')
5003 customer_2 -4.962236165368868
resNode: depot_t deliver_cap: 20.981710060534656 cap_limit: 40
8439 customer_2 ('customer_2', 'customer_4')
5003 customer_2 -4.962236165368868
resNode: customer_4 deliver_cap: 43.518375786915456 cap_limit: 40
8440 customer_2 ('customer_2', 'customer_5')
5003 customer_2 -4.962236165368868
resNode: customer_5 deliver_cap: 31.407422633156582 cap_limit: 40
8441 customer_4 ('customer_4', 'customer_3')
5004 customer_4 -12.695884678974174
resNode: customer_3 deliver_cap: 52.61497023622252 cap_limit: 40
8442 customer_4 ('customer_4', 'customer_1')
5004 customer_4 -12.695884678974174
resNode: customer_1 deliver_cap: 49.15597431517823 cap_limit: 40
8443 customer_4 ('customer_4', 'depot_t')
5004 customer_4 -12.695884678974174
resNode: depot_t deliver_cap: 36.319871106746476 cap_limit: 40
8444 customer_4 ('customer_4', 'customer_2')
5004 customer_4 -12.695884678974174
resNode: customer_2 deliver_cap: 40.72768496217193 cap_limit: 40
8445 customer_4 ('customer_4', 'customer_5')
5004 customer_4 -12.695884678974174
resNode: customer_5 deliver_cap: 48.4264948089953 cap_limit: 40
8446 customer_5 ('customer_5', 'customer_3')
5005 customer_5 -12.97270478607572
resNode: customer_3 deliver_cap: 52.602620275890644 cap_limit: 40
8447 customer_5 ('customer_5', 'customer_1')
5005 customer_5 -12.97270478607572
resNode: customer_1 deliver_cap: 43.51172457095858 cap_limit: 40
8448 customer_5 ('customer_5', 'depot_t')
5005 customer_5 -12.97270478607572
resNode: depot_t deliver_cap: 28.12516207691024 cap_limit: 40
8449 customer_5 ('customer_5', 'customer_2')
5005 customer_5 -12.97270478607572
resNode: customer_2 deliver_cap: 31.850083513182675 cap_limit: 40
8450 customer_5 ('customer_5', 'customer_4')
5005 customer_5 -12.97270478607572
resNode: customer_4 deliver_cap: 52.40600459948098 cap_limit: 40
8451 customer_3 ('customer_3', 'customer_1')
5006 customer_3 -14.523794646909034
resNode: customer_1 deliver_cap: 54.61141060512639 cap_limit: 40
8452 customer_3 ('customer_3', 'depot_t')
5006 customer_3 -14.523794646909034
resNode: depot_t deliver_cap: 39.60158534298982 cap_limit: 40
8453 customer_3 ('customer_3', 'customer_2')
5006 customer_3 -14.523794646909034
resNode: customer_2 deliver_cap: 43.94157771543109 cap_limit: 40
8454 customer_3 ('customer_3', 'customer_4')
5006 customer_3 -14.523794646909034
resNode: customer_4 deliver_cap: 54.902341555216296 cap_limit: 40
8455 customer_3 ('customer_3', 'customer_5')
5006 customer_3 -14.523794646909034
resNode: customer_5 deliver_cap: 50.16200810112044 cap_limit: 40
8456 customer_1 ('customer_1', 'customer_3')
5007 customer_1 -11.22289135650134
resNode: customer_3 deliver_cap: 61.745227777909186 cap_limit: 40
8457 customer_1 ('customer_1', 'depot_t')
5007 customer_1 -11.22289135650134
resNode: depot_t deliver_cap: 37.59478611892794 cap_limit: 40
8458 customer_1 ('customer_1', 'customer_2')
5007 customer_1 -11.22289135650134
resNode: customer_2 deliver_cap: 40.727684962171935 cap_limit: 40
8459 customer_1 ('customer_1', 'customer_4')
5007 customer_1 -11.22289135650134
resNode: customer_4 deliver_cap: 61.25205841550428 cap_limit: 40
8460 customer_1 ('customer_1', 'customer_5')
5007 customer_1 -11.22289135650134
resNode: customer_5 deliver_cap: 50.32577970905596 cap_limit: 40
8461 customer_2 ('customer_2', 'customer_3')
5009 customer_2 -9.943004016244437
resNode: customer_3 deliver_cap: 56.20997797080684 cap_limit: 40
8462 customer_2 ('customer_2', 'customer_1')
5009 customer_2 -9.943004016244437
resNode: customer_1 deliver_cap: 44.89953371677871 cap_limit: 40
8463 customer_2 ('customer_2', 'depot_t')
5009 customer_2 -9.943004016244437
resNode: depot_t deliver_cap: 29.8148267161529 cap_limit: 40
8464 customer_2 ('customer_2', 'customer_4')
5009 customer_2 -9.943004016244437
resNode: customer_4 deliver_cap: 56.01336229439718 cap_limit: 40
8465 customer_2 ('customer_2', 'customer_5')
5009 customer_2 -9.943004016244437
resNode: customer_5 deliver_cap: 41.10757379746318 cap_limit: 40
8466 customer_5 ('customer_5', 'customer_3')
5010 customer_5 -17.617607461821752
resNode: customer_3 deliver_cap: 63.122298487133705 cap_limit: 40
8467 customer_5 ('customer_5', 'customer_1')
5010 customer_5 -17.617607461821752
resNode: customer_1 deliver_cap: 54.10589128238959 cap_limit: 40
8468 customer_5 ('customer_5', 'depot_t')
5010 customer_5 -17.617607461821752
resNode: depot_t deliver_cap: 35.6748896299643 cap_limit: 40
8469 customer_5 ('customer_5', 'customer_2')
5010 customer_5 -17.617607461821752
resNode: customer_2 deliver_cap: 39.75310228820386 cap_limit: 40
8470 customer_5 ('customer_5', 'customer_4')
5010 customer_5 -17.617607461821752
resNode: customer_4 deliver_cap: 62.888817371397224 cap_limit: 40
8471 customer_3 ('customer_3', 'customer_1')
5011 customer_3 -13.920857497045963
resNode: customer_1 deliver_cap: 50.61955085430883 cap_limit: 40
8472 customer_3 ('customer_3', 'depot_t')
5011 customer_3 -13.920857497045963
resNode: depot_t deliver_cap: 35.859216826598356 cap_limit: 40
8473 customer_3 ('customer_3', 'customer_2')
5011 customer_3 -13.920857497045963
resNode: customer_2 deliver_cap: 39.94971796461353 cap_limit: 40
8474 customer_3 ('customer_3', 'customer_4')
5011 customer_3 -13.920857497045963
resNode: customer_4 deliver_cap: 50.16200810112043 cap_limit: 40
8475 customer_3 ('customer_3', 'customer_5')
5011 customer_3 -13.920857497045963
resNode: customer_5 deliver_cap: 45.42167464702459 cap_limit: 40
8476 customer_1 ('customer_1', 'customer_3')
5012 customer_1 -9.821941596828447
resNode: customer_3 deliver_cap: 50.81894907146087 cap_limit: 40
8477 customer_1 ('customer_1', 'depot_t')
5012 customer_1 -9.821941596828447
resNode: depot_t deliver_cap: 29.400077089091702 cap_limit: 40
8478 customer_1 ('customer_1', 'customer_2')
5012 customer_1 -9.821941596828447
resNode: customer_2 deliver_cap: 31.85008351318268 cap_limit: 40
8479 customer_1 ('customer_1', 'customer_4')
5012 customer_1 -9.821941596828447
resNode: customer_4 deliver_cap: 50.325779709055965 cap_limit: 40
8480 customer_1 ('customer_1', 'customer_5')
5012 customer_1 -9.821941596828447
resNode: customer_5 deliver_cap: 39.39950100260764 cap_limit: 40
8481 customer_2 ('customer_2', 'customer_3')
5014 customer_2 -7.547176808950128
resNode: customer_3 deliver_cap: 41.304189473872846 cap_limit: 40
8482 customer_2 ('customer_2', 'customer_1')
5014 customer_2 -7.547176808950128
resNode: customer_1 deliver_cap: 32.788580563019835 cap_limit: 40
8483 customer_2 ('customer_2', 'depot_t')
5014 customer_2 -7.547176808950128
resNode: depot_t deliver_cap: 18.63548534345241 cap_limit: 40
8484 customer_2 ('customer_2', 'customer_4')
5014 customer_2 -7.547176808950128
resNode: customer_4 deliver_cap: 41.10757379746319 cap_limit: 40
8485 customer_2 ('customer_2', 'customer_5')
5014 customer_2 -7.547176808950128
resNode: customer_5 deliver_cap: 26.201785300529195 cap_limit: 40
8486 customer_4 ('customer_4', 'customer_3')
5015 customer_4 -13.891160337588254
resNode: customer_3 deliver_cap: 50.16200810112043 cap_limit: 40
8487 customer_4 ('customer_4', 'customer_1')
5015 customer_4 -13.891160337588254
resNode: customer_1 deliver_cap: 50.12638149190392 cap_limit: 40
8488 customer_4 ('customer_4', 'depot_t')
5015 customer_4 -13.891160337588254
resNode: depot_t deliver_cap: 35.6748896299643 cap_limit: 40
8489 customer_4 ('customer_4', 'customer_2')
5015 customer_4 -13.891160337588254
resNode: customer_2 deliver_cap: 39.75310228820386 cap_limit: 40
8490 customer_4 ('customer_4', 'customer_5')
5015 customer_4 -13.891160337588254
resNode: customer_5 deliver_cap: 45.18819353128811 cap_limit: 40
8491 customer_2 ('customer_2', 'customer_3')
5018 customer_2 -12.214873576545052
resNode: customer_3 deliver_cap: 65.62584599958632 cap_limit: 40
8492 customer_2 ('customer_2', 'customer_1')
5018 customer_2 -12.214873576545052
resNode: customer_1 deliver_cap: 54.314856919131145 cap_limit: 40
8493 customer_2 ('customer_2', 'depot_t')
5018 customer_2 -12.214873576545052
resNode: depot_t deliver_cap: 36.381557468285756 cap_limit: 40
8494 customer_2 ('customer_2', 'customer_4')
5018 customer_2 -12.214873576545052
resNode: customer_4 deliver_cap: 65.39236488384984 cap_limit: 40
8495 customer_2 ('customer_2', 'customer_5')
5018 customer_2 -12.214873576545052
resNode: customer_5 deliver_cap: 47.69174104374073 cap_limit: 40
8496 customer_2 ('customer_2', 'customer_3')
5023 customer_2 -10.105527490842928
resNode: customer_3 deliver_cap: 61.448674091913944 cap_limit: 40
8497 customer_2 ('customer_2', 'customer_1')
5023 customer_2 -10.105527490842928
resNode: customer_1 deliver_cap: 49.155974315178234 cap_limit: 40
8498 customer_2 ('customer_2', 'depot_t')
5023 customer_2 -10.105527490842928
resNode: depot_t deliver_cap: 33.74384880698323 cap_limit: 40
8499 customer_2 ('customer_2', 'customer_4')
5023 customer_2 -10.105527490842928
resNode: customer_4 deliver_cap: 61.25205841550428 cap_limit: 40
8500 customer_2 ('customer_2', 'customer_5')
5023 customer_2 -10.105527490842928
resNode: customer_5 deliver_cap: 46.346269918570286 cap_limit: 40
8501 customer_1 ('customer_1', 'customer_3')
5027 customer_1 -10.740843311259914
resNode: customer_3 deliver_cap: 61.74522777790919 cap_limit: 40
8502 customer_1 ('customer_1', 'depot_t')
5027 customer_1 -10.740843311259914
resNode: depot_t deliver_cap: 37.59478611892794 cap_limit: 40
8503 customer_1 ('customer_1', 'customer_2')
5027 customer_1 -10.740843311259914
resNode: customer_2 deliver_cap: 40.72768496217194 cap_limit: 40
8504 customer_1 ('customer_1', 'customer_4')
5027 customer_1 -10.740843311259914
resNode: customer_4 deliver_cap: 61.252058415504294 cap_limit: 40
8505 customer_1 ('customer_1', 'customer_5')
5027 customer_1 -10.740843311259914
resNode: customer_5 deliver_cap: 50.32577970905597 cap_limit: 40
8506 customer_5 ('customer_5', 'customer_3')
5030 customer_5 -16.127950485280707
resNode: customer_3 deliver_cap: 60.652031429754 cap_limit: 40
8507 customer_5 ('customer_5', 'customer_1')
5030 customer_5 -16.127950485280707
resNode: customer_1 deliver_cap: 52.02566639196458 cap_limit: 40
8508 customer_5 ('customer_5', 'depot_t')
5030 customer_5 -16.127950485280707
resNode: depot_t deliver_cap: 33.72467879519085 cap_limit: 40
8509 customer_5 ('customer_5', 'customer_2')
5030 customer_5 -16.127950485280707
resNode: customer_2 deliver_cap: 37.67287739777885 cap_limit: 40
8510 customer_5 ('customer_5', 'customer_4')
5030 customer_5 -16.127950485280707
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8511 customer_2 ('customer_2', 'customer_3')
5034 customer_2 -15.04690667725607
resNode: customer_3 deliver_cap: 60.65203142975399 cap_limit: 40
8512 customer_2 ('customer_2', 'customer_1')
5034 customer_2 -15.04690667725607
resNode: customer_1 deliver_cap: 50.12638149190392 cap_limit: 40
8513 customer_2 ('customer_2', 'depot_t')
5034 customer_2 -15.04690667725607
resNode: depot_t deliver_cap: 32.45486175526023 cap_limit: 40
8514 customer_2 ('customer_2', 'customer_4')
5034 customer_2 -15.04690667725607
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8515 customer_2 ('customer_2', 'customer_5')
5034 customer_2 -15.04690667725607
resNode: customer_5 deliver_cap: 42.7179264739084 cap_limit: 40
8516 customer_2 ('customer_2', 'customer_3')
5038 customer_2 -14.533617056549161
resNode: customer_3 deliver_cap: 65.61118042169221 cap_limit: 40
8517 customer_2 ('customer_2', 'customer_1')
5038 customer_2 -14.533617056549161
resNode: customer_1 deliver_cap: 54.30250695879926 cap_limit: 40
8518 customer_2 ('customer_2', 'depot_t')
5038 customer_2 -14.533617056549161

resNode: customer_5 deliver_cap: 40.95875704029644 cap_limit: 40
8576 customer_1 ('customer_1', 'customer_3')
5077 customer_1 -8.949121235741714
resNode: customer_3 deliver_cap: 61.74522777790919 cap_limit: 40
8577 customer_1 ('customer_1', 'depot_t')
5077 customer_1 -8.949121235741714
resNode: depot_t deliver_cap: 37.59478611892794 cap_limit: 40
8578 customer_1 ('customer_1', 'customer_2')
5077 customer_1 -8.949121235741714
resNode: customer_2 deliver_cap: 40.72768496217194 cap_limit: 40
8579 customer_1 ('customer_1', 'customer_4')
5077 customer_1 -8.949121235741714
resNode: customer_4 deliver_cap: 61.252058415504294 cap_limit: 40
8580 customer_1 ('customer_1', 'customer_5')
5077 customer_1 -8.949121235741714
resNode: customer_5 deliver_cap: 50.32577970905597 cap_limit: 40
8581 customer_5 ('customer_5', 'customer_3')
5080 customer_5 -14.336228409762507
resNode: customer_3 deliver_cap: 60.652031429754 cap_limit: 40
8582 customer_5 ('customer_5', 'customer_1')
5080 customer_5 -14.336228409762507
resNode: customer_1 deliver_cap: 52.02566639196458 cap_limit: 40
8583 customer_5 ('customer_5', 'depot_t')
5080 customer_5 -14.336228409762507
resNode: depot_t deliver_cap: 33.72467879519085 cap_limit: 40
8584 customer_5 ('customer_5', 'customer_2')
5080 customer_5 -14.336228409762507
resNode: customer_2 deliver_cap: 37.67287739777885 cap_limit: 40
8585 customer_5 ('customer_5', 'customer_4')
5080 customer_5 -14.336228409762507
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8586 customer_2 ('customer_2', 'customer_3')
5084 customer_2 -14.293856031458546
resNode: customer_3 deliver_cap: 62.90743224857603 cap_limit: 40
8587 customer_2 ('customer_2', 'customer_1')
5084 customer_2 -14.293856031458546
resNode: customer_1 deliver_cap: 52.025666391964585 cap_limit: 40
8588 customer_2 ('customer_2', 'depot_t')
5084 customer_2 -14.293856031458546
resNode: depot_t deliver_cap: 34.23544134906711 cap_limit: 40
8589 customer_2 ('customer_2', 'customer_4')
5084 customer_2 -14.293856031458546
resNode: customer_4 deliver_cap: 62.67395113283956 cap_limit: 40
8590 customer_2 ('customer_2', 'customer_5')
5084 customer_2 -14.293856031458546
resNode: customer_5 deliver_cap: 44.97332729273043 cap_limit: 40
8591 customer_2 ('customer_2', 'customer_3')
5088 customer_2 -13.054273866314508
resNode: customer_3 deliver_cap: 69.89491768440519 cap_limit: 40
8592 customer_2 ('customer_2', 'customer_1')
5088 customer_2 -13.054273866314508
resNode: customer_1 deliver_cap: 57.90986465371546 cap_limit: 40
8593 customer_2 ('customer_2', 'depot_t')
5088 customer_2 -13.054273866314508
resNode: depot_t deliver_cap: 39.75187721945855 cap_limit: 40
8594 customer_2 ('customer_2', 'customer_4')
5088 customer_2 -13.054273866314508
resNode: customer_4 deliver_cap: 69.66143656866872 cap_limit: 40
8595 customer_2 ('customer_2', 'customer_5')
5088 customer_2 -13.054273866314508
resNode: customer_5 deliver_cap: 51.960812728559596 cap_limit: 40
8596 customer_2 ('customer_2', 'customer_3')
5093 customer_2 -7.341815387915615
resNode: customer_3 deliver_cap: 56.20997797080684 cap_limit: 40
8597 customer_2 ('customer_2', 'customer_1')
5093 customer_2 -7.341815387915615
resNode: customer_1 deliver_cap: 44.89953371677871 cap_limit: 40
8598 customer_2 ('customer_2', 'depot_t')
5093 customer_2 -7.341815387915615
resNode: depot_t deliver_cap: 29.8148267161529 cap_limit: 40
8599 customer_2 ('customer_2', 'customer_4')
5093 customer_2 -7.341815387915615
resNode: customer_4 deliver_cap: 56.01336229439718 cap_limit: 40
8600 customer_2 ('customer_2', 'customer_5')
5093 customer_2 -7.341815387915615
resNode: customer_5 deliver_cap: 41.10757379746318 cap_limit: 40
8601 customer_5 ('customer_5', 'customer_3')
5095 customer_5 -15.936384956959811
resNode: customer_3 deliver_cap: 65.37769930595574 cap_limit: 40
8602 customer_5 ('customer_5', 'customer_1')
5095 customer_5 -15.936384956959811
resNode: customer_1 deliver_cap: 56.005176182450256 cap_limit: 40
8603 customer_5 ('customer_5', 'depot_t')
5095 customer_5 -15.936384956959811
resNode: depot_t deliver_cap: 37.45546922377117 cap_limit: 40
8604 customer_5 ('customer_5', 'customer_2')
5095 customer_5 -15.936384956959811
resNode: customer_2 deliver_cap: 41.65238718826453 cap_limit: 40
8605 customer_5 ('customer_5', 'customer_4')
5095 customer_5 -15.936384956959811
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8606 customer_2 ('customer_2', 'customer_3')
5099 customer_2 -13.012288227081198
resNode: customer_3 deliver_cap: 69.66143656866872 cap_limit: 40
8607 customer_2 ('customer_2', 'customer_1')
5099 customer_2 -13.012288227081198
resNode: customer_1 deliver_cap: 57.7132489773058 cap_limit: 40
8608 customer_2 ('customer_2', 'depot_t')
5099 customer_2 -13.012288227081198
resNode: depot_t deliver_cap: 39.5675500228245 cap_limit: 40
8609 customer_2 ('customer_2', 'customer_4')
5099 customer_2 -13.012288227081198
resNode: customer_4 deliver_cap: 69.42795545293225 cap_limit: 40
8610 customer_2 ('customer_2', 'customer_5')
5099 customer_2 -13.012288227081198
resNode: customer_5 deliver_cap: 51.72733161282313 cap_limit: 40
8611 customer_1 ('customer_1', 'customer_3')
5102 customer_1 -12.86530395597388
resNode: customer_3 deliver_cap: 63.25958975069538 cap_limit: 40
8612 customer_1 ('customer_1', 'depot_t')
5102 customer_1 -12.86530395597388
resNode: depot_t deliver_cap: 39.049112988998 cap_limit: 40
8613 customer_1 ('customer_1', 'customer_2')
5102 customer_1 -12.86530395597388
resNode: customer_2 deliver_cap: 41.652387188264534 cap_limit: 40
8614 customer_1 ('customer_1', 'customer_4')
5102 customer_1 -12.86530395597388
resNode: customer_4 deliver_cap: 62.67395113283956 cap_limit: 40
8615 customer_1 ('customer_1', 'customer_5')
5102 customer_1 -12.86530395597388
resNode: customer_5 deliver_cap: 49.69899516893218 cap_limit: 40
8616 customer_2 ('customer_2', 'customer_3')
5104 customer_2 -9.917752183993107
resNode: customer_3 deliver_cap: 51.96081272855961 cap_limit: 40
8617 customer_2 ('customer_2', 'customer_1')
5104 customer_2 -9.917752183993107
resNode: customer_1 deliver_cap: 42.80746048037181 cap_limit: 40
8618 customer_2 ('customer_2', 'depot_t')
5104 customer_2 -9.917752183993107
resNode: depot_t deliver_cap: 25.593373306948884 cap_limit: 40
8619 customer_2 ('customer_2', 'customer_4')
5104 customer_2 -9.917752183993107
resNode: customer_4 deliver_cap: 51.727331612823136 cap_limit: 40
8620 customer_2 ('customer_2', 'customer_5')
5104 customer_2 -9.917752183993107
resNode: customer_5 deliver_cap: 34.02670777271402 cap_limit: 40
8621 customer_2 ('customer_2', 'customer_3')
5108 customer_2 -12.09200113176865
resNode: customer_3 deliver_cap: 65.37769930595573 cap_limit: 40
8622 customer_2 ('customer_2', 'customer_1')
5108 customer_2 -12.09200113176865
resNode: customer_1 deliver_cap: 54.1058912823896 cap_limit: 40
8623 customer_2 ('customer_2', 'depot_t')
5108 customer_2 -12.09200113176865
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
8624 customer_2 ('customer_2', 'customer_4')
5108 customer_2 -12.09200113176865
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8625 customer_2 ('customer_2', 'customer_5')
5108 customer_2 -12.09200113176865
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8626 customer_1 ('customer_1', 'customer_3')
5112 customer_1 -11.537864203226388
resNode: customer_3 deliver_cap: 61.00418893187335 cap_limit: 40
8627 customer_1 ('customer_1', 'depot_t')
5112 customer_1 -11.537864203226388
resNode: depot_t deliver_cap: 37.26853339519113 cap_limit: 40
8628 customer_1 ('customer_1', 'customer_2')
5112 customer_1 -11.537864203226388
resNode: customer_2 deliver_cap: 39.75310228820387 cap_limit: 40
8629 customer_1 ('customer_1', 'customer_4')
5112 customer_1 -11.537864203226388
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8630 customer_1 ('customer_1', 'customer_5')
5112 customer_1 -11.537864203226388
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8631 customer_5 ('customer_5', 'customer_3')
5115 customer_5 -13.83029387120653
resNode: customer_3 deliver_cap: 55.96540906620653 cap_limit: 40
8632 customer_5 ('customer_5', 'customer_1')
5115 customer_5 -13.83029387120653
resNode: customer_1 deliver_cap: 49.46220978606412 cap_limit: 40
8633 customer_5 ('customer_5', 'depot_t')
5115 customer_5 -13.83029387120653
resNode: depot_t deliver_cap: 28.799675450066463 cap_limit: 40
8634 customer_5 ('customer_5', 'customer_2')
5115 customer_5 -13.83029387120653
resNode: customer_2 deliver_cap: 32.41827285546858 cap_limit: 40
8635 customer_5 ('customer_5', 'customer_4')
5115 customer_5 -13.83029387120653
resNode: customer_4 deliver_cap: 55.69506251114325 cap_limit: 40
8636 customer_2 ('customer_2', 'customer_3')
5123 customer_2 -7.096265776492819
resNode: customer_3 deliver_cap: 61.237670047609825 cap_limit: 40
8637 customer_2 ('customer_2', 'customer_1')
5123 customer_2 -7.096265776492819
resNode: customer_1 deliver_cap: 50.619550854308834 cap_limit: 40
8638 customer_2 ('customer_2', 'depot_t')
5123 customer_2 -7.096265776492819
resNode: depot_t deliver_cap: 32.91720803251484 cap_limit: 40
8639 customer_2 ('customer_2', 'customer_4')
5123 customer_2 -7.096265776492819
resNode: customer_4 deliver_cap: 61.00418893187336 cap_limit: 40
8640 customer_2 ('customer_2', 'customer_5')
5123 customer_2 -7.096265776492819
resNode: customer_5 deliver_cap: 43.30356509176423 cap_limit: 40
8641 customer_5 ('customer_5', 'customer_3')
5125 customer_5 -14.612350796296942
resNode: customer_3 deliver_cap: 69.31855006795334 cap_limit: 40
8642 customer_5 ('customer_5', 'customer_1')
5125 customer_5 -14.612350796296942
resNode: customer_1 deliver_cap: 60.994467923936384 cap_limit: 40
8643 customer_5 ('customer_5', 'depot_t')
5125 customer_5 -14.612350796296942
resNode: depot_t deliver_cap: 39.72497263331385 cap_limit: 40
8644 customer_5 ('customer_5', 'customer_2')
5125 customer_5 -14.612350796296942
resNode: customer_2 deliver_cap: 43.95053099334082 cap_limit: 40
8645 customer_5 ('customer_5', 'customer_4')
5125 customer_5 -14.612350796296942
resNode: customer_4 deliver_cap: 69.04820351289007 cap_limit: 40
8646 customer_1 ('customer_1', 'customer_3')
5127 customer_1 -7.865691198001804
resNode: customer_3 deliver_cap: 61.23767004760982 cap_limit: 40
8647 customer_1 ('customer_1', 'depot_t')
5127 customer_1 -7.865691198001804
resNode: depot_t deliver_cap: 37.45286059182518 cap_limit: 40
8648 customer_1 ('customer_1', 'customer_2')
5127 customer_1 -7.865691198001804
resNode: customer_2 deliver_cap: 39.94971796461353 cap_limit: 40
8649 customer_1 ('customer_1', 'customer_4')
5127 customer_1 -7.865691198001804
resNode: customer_4 deliver_cap: 60.652031429754 cap_limit: 40
8650 customer_1 ('customer_1', 'customer_5')
5127 customer_1 -7.865691198001804
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
8651 customer_5 ('customer_5', 'customer_3')
5130 customer_5 -10.20420266514046
resNode: customer_3 deliver_cap: 56.23575562126981 cap_limit: 40
8652 customer_5 ('customer_5', 'customer_1')
5130 customer_5 -10.20420266514046
resNode: customer_1 deliver_cap: 49.6956909018006 cap_limit: 40
8653 customer_5 ('customer_5', 'depot_t')
5130 customer_5 -10.20420266514046
resNode: depot_t deliver_cap: 29.020868086027328 cap_limit: 40
8654 customer_5 ('customer_5', 'customer_2')
5130 customer_5 -10.20420266514046
resNode: customer_2 deliver_cap: 32.65175397120505 cap_limit: 40
8655 customer_5 ('customer_5', 'customer_4')
5130 customer_5 -10.20420266514046
resNode: customer_4 deliver_cap: 55.96540906620653 cap_limit: 40
8656 customer_2 ('customer_2', 'customer_3')
5134 customer_2 -6.372767690994539
resNode: customer_3 deliver_cap: 61.72456277864396 cap_limit: 40
8657 customer_2 ('customer_2', 'customer_1')
5134 customer_2 -6.372767690994539
resNode: customer_1 deliver_cap: 52.180623537074425 cap_limit: 40
8658 customer_2 ('customer_2', 'depot_t')
5134 customer_2 -6.372767690994539
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
8659 customer_2 ('customer_2', 'customer_4')
5134 customer_2 -6.372767690994539
resNode: customer_4 deliver_cap: 61.45421622358067 cap_limit: 40
8660 customer_2 ('customer_2', 'customer_5')
5134 customer_2 -6.372767690994539
resNode: customer_5 deliver_cap: 40.95875704029644 cap_limit: 40
8661 customer_5 ('customer_5', 'customer_3')
5135 customer_5 -11.23502546495563
resNode: customer_3 deliver_cap: 65.36911393683302 cap_limit: 40
8662 customer_5 ('customer_5', 'customer_1')
5135 customer_5 -11.23502546495563
resNode: customer_1 deliver_cap: 58.83144358207025 cap_limit: 40
8663 customer_5 ('customer_5', 'depot_t')
5135 customer_5 -11.23502546495563
resNode: depot_t deliver_cap: 35.088150229426184 cap_limit: 40
8664 customer_5 ('customer_5', 'customer_2')
5135 customer_5 -11.23502546495563
resNode: customer_2 deliver_cap: 39.09635871506487 cap_limit: 40
8665 customer_5 ('customer_5', 'customer_4')
5135 customer_5 -11.23502546495563
resNode: customer_4 deliver_cap: 65.06190194244293 cap_limit: 40
8666 customer_2 ('customer_2', 'customer_3')
5139 customer_2 -9.059668005119299
resNode: customer_3 deliver_cap: 56.23575562126982 cap_limit: 40
8667 customer_2 ('customer_2', 'customer_1')
5139 customer_2 -9.059668005119299
resNode: customer_1 deliver_cap: 47.44029008297857 cap_limit: 40
8668 customer_2 ('customer_2', 'depot_t')
5139 customer_2 -9.059668005119299
resNode: depot_t deliver_cap: 27.497087638110603 cap_limit: 40
8669 customer_2 ('customer_2', 'customer_4')
5139 customer_2 -9.059668005119299
resNode: customer_4 deliver_cap: 55.96540906620653 cap_limit: 40
8670 customer_2 ('customer_2', 'customer_5')
5139 customer_2 -9.059668005119299
resNode: customer_5 deliver_cap: 35.46994988292229 cap_limit: 40
8671 customer_2 ('customer_2', 'customer_3')
5143 customer_2 -10.088679924333986
resNode: customer_3 deliver_cap: 63.49307086643184 cap_limit: 40
8672 customer_2 ('customer_2', 'customer_1')
5143 customer_2 -10.088679924333986
resNode: customer_1 deliver_cap: 52.51883575436948 cap_limit: 40
8673 customer_2 ('customer_2', 'depot_t')
5143 customer_2 -10.088679924333986
resNode: depot_t deliver_cap: 34.6977876263217 cap_limit: 40
8674 customer_2 ('customer_2', 'customer_4')
5143 customer_2 -10.088679924333986
resNode: customer_4 deliver_cap: 63.259589750695376 cap_limit: 40
8675 customer_2 ('customer_2', 'customer_5')
5143 customer_2 -10.088679924333986
resNode: customer_5 deliver_cap: 45.55896591058625 cap_limit: 40
8676 customer_5 ('customer_5', 'customer_3')
5145 customer_5 -17.0409147394326
resNode: customer_3 deliver_cap: 69.31855006795334 cap_limit: 40
8677 customer_5 ('customer_5', 'customer_1')
5145 customer_5 -17.0409147394326
resNode: customer_1 deliver_cap: 60.994467923936384 cap_limit: 40
8678 customer_5 ('customer_5', 'depot_t')
5145 customer_5 -17.0409147394326
resNode: depot_t deliver_cap: 39.72497263331385 cap_limit: 40
8679 customer_5 ('customer_5', 'customer_2')
5145 customer_5 -17.0409147394326
resNode: customer_2 deliver_cap: 43.95053099334082 cap_limit: 40
8680 customer_5 ('customer_5', 'customer_4')
5145 customer_5 -17.0409147394326
resNode: customer_4 deliver_cap: 69.04820351289007 cap_limit: 40
8681 customer_3 ('customer_3', 'customer_1')
5146 customer_3 -11.201268661447175
resNode: customer_1 deliver_cap: 52.51883575436948 cap_limit: 40
8682 customer_3 ('customer_3', 'depot_t')
5146 customer_3 -11.201268661447175
resNode: depot_t deliver_cap: 37.639796420405226 cap_limit: 40
8683 customer_3 ('customer_3', 'customer_2')
5146 customer_3 -11.201268661447175
resNode: customer_2 deliver_cap: 41.84900286467418 cap_limit: 40
8684 customer_3 ('customer_3', 'customer_4')
5146 customer_3 -11.201268661447175
resNode: customer_4 deliver_cap: 52.41740891994247 cap_limit: 40
8685 customer_3 ('customer_3', 'customer_5')
5146 customer_3 -11.201268661447175
resNode: customer_5 deliver_cap: 47.67707546584661 cap_limit: 40
8686 customer_1 ('customer_1', 'customer_3')
5147 customer_1 -6.182386637762776
resNode: customer_3 deliver_cap: 50.818949071460864 cap_limit: 40
8687 customer_1 ('customer_1', 'depot_t')
5147 customer_1 -6.182386637762776
resNode: depot_t deliver_cap: 29.4000770890917 cap_limit: 40
8688 customer_1 ('customer_1', 'customer_2')
5147 customer_1 -6.182386637762776
resNode: customer_2 deliver_cap: 31.850083513182675 cap_limit: 40
8689 customer_1 ('customer_1', 'customer_4')
5147 customer_1 -6.182386637762776
resNode: customer_4 deliver_cap: 50.325779709055965 cap_limit: 40
8690 customer_1 ('customer_1', 'customer_5')
5147 customer_1 -6.182386637762776
resNode: customer_5 deliver_cap: 39.39950100260764 cap_limit: 40
8691 customer_4 ('customer_4', 'customer_3')
5149 customer_4 -11.171571501989467
resNode: customer_3 deliver_cap: 52.41740891994247 cap_limit: 40
8692 customer_4 ('customer_4', 'customer_1')
5149 customer_4 -11.171571501989467
resNode: customer_1 deliver_cap: 52.02566639196458 cap_limit: 40
8693 customer_4 ('customer_4', 'depot_t')
5149 customer_4 -11.171571501989467
resNode: depot_t deliver_cap: 37.45546922377117 cap_limit: 40
8694 customer_4 ('customer_4', 'customer_2')
5149 customer_4 -11.171571501989467
resNode: customer_2 deliver_cap: 41.65238718826453 cap_limit: 40
8695 customer_4 ('customer_4', 'customer_5')
5149 customer_4 -11.171571501989467
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8696 customer_5 ('customer_5', 'customer_3')
5150 customer_5 -9.00864723995975
resNode: customer_3 deliver_cap: 47.67707546584661 cap_limit: 40
8697 customer_5 ('customer_5', 'customer_1')
5150 customer_5 -9.00864723995975
resNode: customer_1 deliver_cap: 41.09938768551626 cap_limit: 40
8698 customer_5 ('customer_5', 'depot_t')
5150 customer_5 -9.00864723995975
resNode: depot_t deliver_cap: 23.48129250789555 cap_limit: 40
8699 customer_5 ('customer_5', 'customer_2')
5150 customer_5 -9.00864723995975
resNode: customer_2 deliver_cap: 26.746598691330536 cap_limit: 40
8700 customer_5 ('customer_5', 'customer_4')
5150 customer_5 -9.00864723995975
resNode: customer_4 deliver_cap: 47.443594350110146 cap_limit: 40
8701 customer_2 ('customer_2', 'customer_3')
5154 customer_2 -9.884516488072023
resNode: customer_3 deliver_cap: 62.90743224857602 cap_limit: 40
8702 customer_2 ('customer_2', 'customer_1')
5154 customer_2 -9.884516488072023
resNode: customer_1 deliver_cap: 52.02566639196458 cap_limit: 40
8703 customer_2 ('customer_2', 'depot_t')
5154 customer_2 -9.884516488072023
resNode: depot_t deliver_cap: 34.2354413490671 cap_limit: 40
8704 customer_2 ('customer_2', 'customer_4')
5154 customer_2 -9.884516488072023
resNode: customer_4 deliver_cap: 62.67395113283954 cap_limit: 40
8705 customer_2 ('customer_2', 'customer_5')
5154 customer_2 -9.884516488072023
resNode: customer_5 deliver_cap: 44.973327292730424 cap_limit: 40
8706 customer_5 ('customer_5', 'customer_3')
5155 customer_5 -16.721164733856995
resNode: customer_3 deliver_cap: 68.6404421946466 cap_limit: 40
8707 customer_5 ('customer_5', 'customer_1')
5155 customer_5 -16.721164733856995
resNode: customer_1 deliver_cap: 60.40882930608055 cap_limit: 40
8708 customer_5 ('customer_5', 'depot_t')
5155 customer_5 -16.721164733856995
resNode: depot_t deliver_cap: 39.17015710060833 cap_limit: 40
8709 customer_5 ('customer_5', 'customer_2')
5155 customer_5 -16.721164733856995
resNode: customer_2 deliver_cap: 43.36489237548499 cap_limit: 40
8710 customer_5 ('customer_5', 'customer_4')
5155 customer_5 -16.721164733856995
resNode: customer_4 deliver_cap: 68.37009563958331 cap_limit: 40
8711 customer_1 ('customer_1', 'customer_3')
5157 customer_1 -11.913826633636564
resNode: customer_3 deliver_cap: 61.231253306804426 cap_limit: 40
8712 customer_1 ('customer_1', 'depot_t')
5157 customer_1 -11.913826633636564
resNode: depot_t deliver_cap: 37.44779474382093 cap_limit: 40
8713 customer_1 ('customer_1', 'customer_2')
5157 customer_1 -11.913826633636564
resNode: customer_2 deliver_cap: 39.94431439340899 cap_limit: 40

resNode: customer_5 deliver_cap: 42.717926473908406 cap_limit: 40
8756 customer_5 ('customer_5', 'customer_3')
5170 customer_5 -8.183790008579846
resNode: customer_3 deliver_cap: 47.67707546584661 cap_limit: 40
8757 customer_5 ('customer_5', 'customer_1')
5170 customer_5 -8.183790008579846
resNode: customer_1 deliver_cap: 41.09938768551626 cap_limit: 40
8758 customer_5 ('customer_5', 'depot_t')
5170 customer_5 -8.183790008579846
resNode: depot_t deliver_cap: 23.48129250789555 cap_limit: 40
8759 customer_5 ('customer_5', 'customer_2')
5170 customer_5 -8.183790008579846
resNode: customer_2 deliver_cap: 26.746598691330536 cap_limit: 40
8760 customer_5 ('customer_5', 'customer_4')
5170 customer_5 -8.183790008579846
resNode: customer_4 deliver_cap: 47.443594350110146 cap_limit: 40
8761 customer_3 ('customer_3', 'customer_1')
5171 customer_3 -7.038346484695197
resNode: customer_1 deliver_cap: 50.062513981814064 cap_limit: 40
8762 customer_3 ('customer_3', 'depot_t')
5171 customer_3 -7.038346484695197
resNode: depot_t deliver_cap: 33.511710305697086 cap_limit: 40
8763 customer_3 ('customer_3', 'customer_2')
5171 customer_3 -7.038346484695197
resNode: customer_2 deliver_cap: 37.39208742530091 cap_limit: 40
8764 customer_3 ('customer_3', 'customer_4')
5171 customer_3 -7.038346484695197
resNode: customer_4 deliver_cap: 46.44756419767059 cap_limit: 40
8765 customer_3 ('customer_3', 'customer_5')
5171 customer_3 -7.038346484695197
resNode: customer_5 deliver_cap: 40.95875704029643 cap_limit: 40
8766 customer_1 ('customer_1', 'customer_3')
5172 customer_1 -7.02582808163157
resNode: customer_3 deliver_cap: 58.53392187449364 cap_limit: 40
8767 customer_1 ('customer_1', 'depot_t')
5172 customer_1 -7.02582808163157
resNode: depot_t deliver_cap: 35.31832256041768 cap_limit: 40
8768 customer_1 ('customer_1', 'customer_2')
5172 customer_1 -7.02582808163157
resNode: customer_2 deliver_cap: 37.672877397778855 cap_limit: 40
8769 customer_1 ('customer_1', 'customer_4')
5172 customer_1 -7.02582808163157
resNode: customer_4 deliver_cap: 57.948283256637815 cap_limit: 40
8770 customer_1 ('customer_1', 'customer_5')
5172 customer_1 -7.02582808163157
resNode: customer_5 deliver_cap: 44.97332729273043 cap_limit: 40
8771 customer_2 ('customer_2', 'customer_3')
5174 customer_2 -5.259693278701228
resNode: customer_3 deliver_cap: 51.96081272855961 cap_limit: 40
8772 customer_2 ('customer_2', 'customer_1')
5174 customer_2 -5.259693278701228
resNode: customer_1 deliver_cap: 42.8074604803718 cap_limit: 40
8773 customer_2 ('customer_2', 'depot_t')
5174 customer_2 -5.259693278701228
resNode: depot_t deliver_cap: 25.59337330694888 cap_limit: 40
8774 customer_2 ('customer_2', 'customer_4')
5174 customer_2 -5.259693278701228
resNode: customer_4 deliver_cap: 51.727331612823136 cap_limit: 40
8775 customer_2 ('customer_2', 'customer_5')
5174 customer_2 -5.259693278701228
resNode: customer_5 deliver_cap: 34.02670777271402 cap_limit: 40
8776 customer_5 ('customer_5', 'customer_3')
5175 customer_5 -9.93582451395664
resNode: customer_3 deliver_cap: 55.96540906620653 cap_limit: 40
8777 customer_5 ('customer_5', 'customer_1')
5175 customer_5 -9.93582451395664
resNode: customer_1 deliver_cap: 49.46220978606412 cap_limit: 40
8778 customer_5 ('customer_5', 'depot_t')
5175 customer_5 -9.93582451395664
resNode: depot_t deliver_cap: 28.799675450066463 cap_limit: 40
8779 customer_5 ('customer_5', 'customer_2')
5175 customer_5 -9.93582451395664
resNode: customer_2 deliver_cap: 32.41827285546858 cap_limit: 40
8780 customer_5 ('customer_5', 'customer_4')
5175 customer_5 -9.93582451395664
resNode: customer_4 deliver_cap: 55.69506251114325 cap_limit: 40
8781 customer_3 ('customer_3', 'customer_1')
5176 customer_3 -6.248290909012553
resNode: customer_1 deliver_cap: 45.32218052771822 cap_limit: 40
8782 customer_3 ('customer_3', 'depot_t')
5176 customer_3 -6.248290909012553
resNode: depot_t deliver_cap: 29.020868086027328 cap_limit: 40
8783 customer_3 ('customer_3', 'customer_2')
5176 customer_3 -6.248290909012553
resNode: customer_2 deliver_cap: 32.65175397120505 cap_limit: 40
8784 customer_3 ('customer_3', 'customer_4')
5176 customer_3 -6.248290909012553
resNode: customer_4 deliver_cap: 40.95875704029643 cap_limit: 40
8785 customer_3 ('customer_3', 'customer_5')
5176 customer_3 -6.248290909012553
resNode: customer_5 deliver_cap: 35.46994988292229 cap_limit: 40
8786 customer_1 ('customer_1', 'customer_3')
5177 customer_1 -5.112709007593912
resNode: customer_3 deliver_cap: 45.55896591058626 cap_limit: 40
8787 customer_1 ('customer_1', 'depot_t')
5177 customer_1 -5.112709007593912
resNode: depot_t deliver_cap: 25.07493627312238 cap_limit: 40
8788 customer_1 ('customer_1', 'customer_2')
5177 customer_1 -5.112709007593912
resNode: customer_2 deliver_cap: 26.746598691330536 cap_limit: 40
8789 customer_1 ('customer_1', 'customer_4')
5177 customer_1 -5.112709007593912
resNode: customer_4 deliver_cap: 44.973327292730445 cap_limit: 40
8790 customer_1 ('customer_1', 'customer_5')
5177 customer_1 -5.112709007593912
resNode: customer_5 deliver_cap: 31.998371328823065 cap_limit: 40
8791 customer_2 ('customer_2', 'customer_3')
5179 customer_2 -2.1651572356131363
resNode: customer_3 deliver_cap: 34.260188888450486 cap_limit: 40
8792 customer_2 ('customer_2', 'customer_1')
5179 customer_2 -2.1651572356131363
resNode: customer_1 deliver_cap: 27.901671983437808 cap_limit: 40
8793 customer_2 ('customer_2', 'depot_t')
5179 customer_2 -2.1651572356131363
resNode: depot_t deliver_cap: 11.61919659107326 cap_limit: 40
8794 customer_2 ('customer_2', 'customer_4')
5179 customer_2 -2.1651572356131363
resNode: customer_4 deliver_cap: 34.02670777271402 cap_limit: 40
8795 customer_2 ('customer_2', 'customer_5')
5179 customer_2 -2.1651572356131363
resNode: customer_5 deliver_cap: 16.3260839326049 cap_limit: 40
8796 customer_4 ('customer_4', 'customer_3')
5180 customer_4 -6.209377389723141
resNode: customer_3 deliver_cap: 40.958757040296426 cap_limit: 40
8797 customer_4 ('customer_4', 'customer_1')
5180 customer_4 -6.209377389723141
resNode: customer_1 deliver_cap: 44.73654190986238 cap_limit: 40
8798 customer_4 ('customer_4', 'depot_t')
5180 customer_4 -6.209377389723141
resNode: depot_t deliver_cap: 28.79967545006646 cap_limit: 40
8799 customer_4 ('customer_4', 'customer_2')
5180 customer_4 -6.209377389723141
resNode: customer_2 deliver_cap: 32.41827285546857 cap_limit: 40
8800 customer_4 ('customer_4', 'customer_5')
5180 customer_4 -6.209377389723141
resNode: customer_5 deliver_cap: 35.199603327859 cap_limit: 40
8801 customer_2 ('customer_2', 'customer_3')
5183 customer_2 -6.323613771892122
resNode: customer_3 deliver_cap: 61.72456277864396 cap_limit: 40
8802 customer_2 ('customer_2', 'customer_1')
5183 customer_2 -6.323613771892122
resNode: customer_1 deliver_cap: 52.180623537074425 cap_limit: 40
8803 customer_2 ('customer_2', 'depot_t')
5183 customer_2 -6.323613771892122
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
8804 customer_2 ('customer_2', 'customer_4')
5183 customer_2 -6.323613771892122
resNode: customer_4 deliver_cap: 61.45421622358067 cap_limit: 40
8805 customer_2 ('customer_2', 'customer_5')
5183 customer_2 -6.323613771892122
resNode: customer_5 deliver_cap: 40.95875704029644 cap_limit: 40
8806 customer_5 ('customer_5', 'customer_3')
5185 customer_5 -11.185871545853212
resNode: customer_3 deliver_cap: 65.36911393683302 cap_limit: 40
8807 customer_5 ('customer_5', 'customer_1')
5185 customer_5 -11.185871545853212
resNode: customer_1 deliver_cap: 58.83144358207025 cap_limit: 40
8808 customer_5 ('customer_5', 'depot_t')
5185 customer_5 -11.185871545853212
resNode: depot_t deliver_cap: 35.088150229426184 cap_limit: 40
8809 customer_5 ('customer_5', 'customer_2')
5185 customer_5 -11.185871545853212
resNode: customer_2 deliver_cap: 39.09635871506487 cap_limit: 40
8810 customer_5 ('customer_5', 'customer_4')
5185 customer_5 -11.185871545853212
resNode: customer_4 deliver_cap: 65.06190194244293 cap_limit: 40
8811 customer_2 ('customer_2', 'customer_3')
5188 customer_2 -6.935417676579361
resNode: customer_3 deliver_cap: 60.652031429754 cap_limit: 40
8812 customer_2 ('customer_2', 'customer_1')
5188 customer_2 -6.935417676579361
resNode: customer_1 deliver_cap: 50.12638149190393 cap_limit: 40
8813 customer_2 ('customer_2', 'depot_t')
5188 customer_2 -6.935417676579361
resNode: depot_t deliver_cap: 32.45486175526024 cap_limit: 40
8814 customer_2 ('customer_2', 'customer_4')
5188 customer_2 -6.935417676579361
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8815 customer_2 ('customer_2', 'customer_5')
5188 customer_2 -6.935417676579361
resNode: customer_5 deliver_cap: 42.717926473908406 cap_limit: 40
8816 customer_5 ('customer_5', 'customer_3')
5190 customer_5 -14.335916127069837
resNode: customer_3 deliver_cap: 68.64044219464661 cap_limit: 40
8817 customer_5 ('customer_5', 'customer_1')
5190 customer_5 -14.335916127069837
resNode: customer_1 deliver_cap: 60.40882930608056 cap_limit: 40
8818 customer_5 ('customer_5', 'depot_t')
5190 customer_5 -14.335916127069837
resNode: depot_t deliver_cap: 39.170157100608336 cap_limit: 40
8819 customer_5 ('customer_5', 'customer_2')
5190 customer_5 -14.335916127069837
resNode: customer_2 deliver_cap: 43.364892375485 cap_limit: 40
8820 customer_5 ('customer_5', 'customer_4')
5190 customer_5 -14.335916127069837
resNode: customer_4 deliver_cap: 68.37009563958333 cap_limit: 40
8821 customer_1 ('customer_1', 'customer_3')
5192 customer_1 -7.811417078992888
resNode: customer_3 deliver_cap: 61.00418893187335 cap_limit: 40
8822 customer_1 ('customer_1', 'depot_t')
5192 customer_1 -7.811417078992888
resNode: depot_t deliver_cap: 37.26853339519113 cap_limit: 40
8823 customer_1 ('customer_1', 'customer_2')
5192 customer_1 -7.811417078992888
resNode: customer_2 deliver_cap: 39.75310228820387 cap_limit: 40
8824 customer_1 ('customer_1', 'customer_4')
5192 customer_1 -7.811417078992888
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8825 customer_1 ('customer_1', 'customer_5')
5192 customer_1 -7.811417078992888
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8826 customer_5 ('customer_5', 'customer_3')
5195 customer_5 -10.10384674697303
resNode: customer_3 deliver_cap: 55.96540906620653 cap_limit: 40
8827 customer_5 ('customer_5', 'customer_1')
5195 customer_5 -10.10384674697303
resNode: customer_1 deliver_cap: 49.46220978606412 cap_limit: 40
8828 customer_5 ('customer_5', 'depot_t')
5195 customer_5 -10.10384674697303
resNode: depot_t deliver_cap: 28.799675450066463 cap_limit: 40
8829 customer_5 ('customer_5', 'customer_2')
5195 customer_5 -10.10384674697303
resNode: customer_2 deliver_cap: 32.41827285546858 cap_limit: 40
8830 customer_5 ('customer_5', 'customer_4')
5195 customer_5 -10.10384674697303
resNode: customer_4 deliver_cap: 55.69506251114325 cap_limit: 40
8831 customer_2 ('customer_2', 'customer_3')
5199 customer_2 -8.959312086951867
resNode: customer_3 deliver_cap: 55.96540906620653 cap_limit: 40
8832 customer_2 ('customer_2', 'customer_1')
5199 customer_2 -8.959312086951867
resNode: customer_1 deliver_cap: 47.2068089672421 cap_limit: 40
8833 customer_2 ('customer_2', 'depot_t')
5199 customer_2 -8.959312086951867
resNode: depot_t deliver_cap: 27.27589500214973 cap_limit: 40
8834 customer_2 ('customer_2', 'customer_4')
5199 customer_2 -8.959312086951867
resNode: customer_4 deliver_cap: 55.69506251114325 cap_limit: 40
8835 customer_2 ('customer_2', 'customer_5')
5199 customer_2 -8.959312086951867
resNode: customer_5 deliver_cap: 35.19960332785901 cap_limit: 40
8836 customer_2 ('customer_2', 'customer_3')
5213 customer_2 -8.50540463347614
resNode: customer_3 deliver_cap: 68.09611305696602 cap_limit: 40
8837 customer_2 ('customer_2', 'customer_1')
5213 customer_2 -8.50540463347614
resNode: customer_1 deliver_cap: 56.39508180955616 cap_limit: 40
8838 customer_2 ('customer_2', 'depot_t')
5213 customer_2 -8.50540463347614
resNode: depot_t deliver_cap: 38.33176830305921 cap_limit: 40
8839 customer_2 ('customer_2', 'customer_4')
5213 customer_2 -8.50540463347614
resNode: customer_4 deliver_cap: 67.86263194122955 cap_limit: 40
8840 customer_2 ('customer_2', 'customer_5')
5213 customer_2 -8.50540463347614
resNode: customer_5 deliver_cap: 50.16200810112043 cap_limit: 40
8841 customer_2 ('customer_2', 'customer_3')
5219 customer_2 -10.763392152108535
resNode: customer_3 deliver_cap: 61.72456277864396 cap_limit: 40
8842 customer_2 ('customer_2', 'customer_1')
5219 customer_2 -10.763392152108535
resNode: customer_1 deliver_cap: 52.180623537074425 cap_limit: 40
8843 customer_2 ('customer_2', 'depot_t')
5219 customer_2 -10.763392152108535
resNode: depot_t deliver_cap: 31.987929857780355 cap_limit: 40
8844 customer_2 ('customer_2', 'customer_4')
5219 customer_2 -10.763392152108535
resNode: customer_4 deliver_cap: 61.45421622358067 cap_limit: 40
8845 customer_2 ('customer_2', 'customer_5')
5219 customer_2 -10.763392152108535
resNode: customer_5 deliver_cap: 40.95875704029644 cap_limit: 40
8846 customer_2 ('customer_2', 'customer_3')
5234 customer_2 -12.15221791540915
resNode: customer_3 deliver_cap: 71.60639479748545 cap_limit: 40
8847 customer_2 ('customer_2', 'customer_1')
5234 customer_2 -12.15221791540915
resNode: customer_1 deliver_cap: 61.70873400186098 cap_limit: 40
8848 customer_2 ('customer_2', 'depot_t')
5234 customer_2 -12.15221791540915
resNode: depot_t deliver_cap: 38.54972229647138 cap_limit: 40
8849 customer_2 ('customer_2', 'customer_4')
5234 customer_2 -12.15221791540915
resNode: customer_4 deliver_cap: 71.29918280309535 cap_limit: 40
8850 customer_2 ('customer_2', 'customer_5')
5234 customer_2 -12.15221791540915
resNode: customer_5 deliver_cap: 48.00888827663599 cap_limit: 40
8851 customer_5 ('customer_5', 'customer_3')
5240 customer_5 -14.86206037802764
resNode: customer_3 deliver_cap: 65.36911393683302 cap_limit: 40
8852 customer_5 ('customer_5', 'customer_1')
5240 customer_5 -14.86206037802764
resNode: customer_1 deliver_cap: 58.83144358207025 cap_limit: 40
8853 customer_5 ('customer_5', 'depot_t')
5240 customer_5 -14.86206037802764
resNode: depot_t deliver_cap: 35.088150229426184 cap_limit: 40
8854 customer_5 ('customer_5', 'customer_2')
5240 customer_5 -14.86206037802764
resNode: customer_2 deliver_cap: 39.09635871506487 cap_limit: 40
8855 customer_5 ('customer_5', 'customer_4')
5240 customer_5 -14.86206037802764
resNode: customer_4 deliver_cap: 65.06190194244293 cap_limit: 40
8856 customer_2 ('customer_2', 'customer_3')
5248 customer_2 -9.589330489819694
resNode: customer_3 deliver_cap: 63.52889898233896 cap_limit: 40
8857 customer_2 ('customer_2', 'customer_1')
5248 customer_2 -9.589330489819694
resNode: customer_1 deliver_cap: 50.846157038648556 cap_limit: 40
8858 customer_2 ('customer_2', 'depot_t')
5248 customer_2 -9.589330489819694
resNode: depot_t deliver_cap: 35.304017474801995 cap_limit: 40
8859 customer_2 ('customer_2', 'customer_4')
5248 customer_2 -9.589330489819694
resNode: customer_4 deliver_cap: 63.332283305929295 cap_limit: 40
8860 customer_2 ('customer_2', 'customer_5')
5248 customer_2 -9.589330489819694
resNode: customer_5 deliver_cap: 48.4264948089953 cap_limit: 40
8861 customer_2 ('customer_2', 'customer_3')
5254 customer_2 -13.880639397975019
resNode: customer_3 deliver_cap: 60.65203142975399 cap_limit: 40
8862 customer_2 ('customer_2', 'customer_1')
5254 customer_2 -13.880639397975019
resNode: customer_1 deliver_cap: 50.12638149190392 cap_limit: 40
8863 customer_2 ('customer_2', 'depot_t')
5254 customer_2 -13.880639397975019
resNode: depot_t deliver_cap: 32.45486175526023 cap_limit: 40
8864 customer_2 ('customer_2', 'customer_4')
5254 customer_2 -13.880639397975019
resNode: customer_4 deliver_cap: 60.41855031401752 cap_limit: 40
8865 customer_2 ('customer_2', 'customer_5')
5254 customer_2 -13.880639397975019
resNode: customer_5 deliver_cap: 42.7179264739084 cap_limit: 40
8866 customer_5 ('customer_5', 'customer_3')
5265 customer_5 -21.11107483169247
resNode: customer_3 deliver_cap: 68.6404421946466 cap_limit: 40
8867 customer_5 ('customer_5', 'customer_1')
5265 customer_5 -21.11107483169247
resNode: customer_1 deliver_cap: 60.40882930608055 cap_limit: 40
8868 customer_5 ('customer_5', 'depot_t')
5265 customer_5 -21.11107483169247
resNode: depot_t deliver_cap: 39.17015710060833 cap_limit: 40
8869 customer_5 ('customer_5', 'customer_2')
5265 customer_5 -21.11107483169247
resNode: customer_2 deliver_cap: 43.36489237548499 cap_limit: 40
8870 customer_5 ('customer_5', 'customer_4')
5265 customer_5 -21.11107483169247
resNode: customer_4 deliver_cap: 68.37009563958331 cap_limit: 40
8871 customer_1 ('customer_1', 'customer_3')
5272 customer_1 -9.897227802667485
resNode: customer_3 deliver_cap: 63.82545266833421 cap_limit: 40
8872 customer_1 ('customer_1', 'depot_t')
5272 customer_1 -9.897227802667485
resNode: depot_t deliver_cap: 39.15495478674671 cap_limit: 40
8873 customer_1 ('customer_1', 'customer_2')
5272 customer_1 -9.897227802667485
resNode: customer_2 deliver_cap: 42.417867685642264 cap_limit: 40
8874 customer_1 ('customer_1', 'customer_4')
5272 customer_1 -9.897227802667485
resNode: customer_4 deliver_cap: 63.33228330592931 cap_limit: 40
8875 customer_1 ('customer_1', 'customer_5')
5272 customer_1 -9.897227802667485
resNode: customer_5 deliver_cap: 52.40600459948099 cap_limit: 40
8876 customer_5 ('customer_5', 'customer_3')
5275 customer_5 -15.771887685381643
resNode: customer_3 deliver_cap: 63.122298487133705 cap_limit: 40
8877 customer_5 ('customer_5', 'customer_1')
5275 customer_5 -15.771887685381643
resNode: customer_1 deliver_cap: 54.10589128238959 cap_limit: 40
8878 customer_5 ('customer_5', 'depot_t')
5275 customer_5 -15.771887685381643
resNode: depot_t deliver_cap: 35.6748896299643 cap_limit: 40
8879 customer_5 ('customer_5', 'customer_2')
5275 customer_5 -15.771887685381643
resNode: customer_2 deliver_cap: 39.75310228820386 cap_limit: 40
8880 customer_5 ('customer_5', 'customer_4')
5275 customer_5 -15.771887685381643
resNode: customer_4 deliver_cap: 62.888817371397224 cap_limit: 40
8881 customer_2 ('customer_2', 'customer_3')
5279 customer_2 -15.729515307077678
resNode: customer_3 deliver_cap: 65.37769930595573 cap_limit: 40
8882 customer_2 ('customer_2', 'customer_1')
5279 customer_2 -15.729515307077678
resNode: customer_1 deliver_cap: 54.1058912823896 cap_limit: 40
8883 customer_2 ('customer_2', 'depot_t')
5279 customer_2 -15.729515307077678
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
8884 customer_2 ('customer_2', 'customer_4')
5279 customer_2 -15.729515307077678
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8885 customer_2 ('customer_2', 'customer_5')
5279 customer_2 -15.729515307077678
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8886 customer_2 ('customer_2', 'customer_3')
5293 customer_2 -12.260023364785042
resNode: customer_3 deliver_cap: 65.37769930595573 cap_limit: 40
8887 customer_2 ('customer_2', 'customer_1')
5293 customer_2 -12.260023364785042
resNode: customer_1 deliver_cap: 54.1058912823896 cap_limit: 40
8888 customer_2 ('customer_2', 'depot_t')
5293 customer_2 -12.260023364785042
resNode: depot_t deliver_cap: 36.18565218384056 cap_limit: 40
8889 customer_2 ('customer_2', 'customer_4')
5293 customer_2 -12.260023364785042
resNode: customer_4 deliver_cap: 65.14421819021926 cap_limit: 40
8890 customer_2 ('customer_2', 'customer_5')
5293 customer_2 -12.260023364785042
resNode: customer_5 deliver_cap: 47.44359435011014 cap_limit: 40
8891 customer_1 ('customer_1', 'customer_3')
5297 customer_1 -11.705886436242778
resNode: customer_3 deliver_cap: 61.00418893187335 cap_limit: 40
8892 customer_1 ('customer_1', 'depot_t')
5297 customer_1 -11.705886436242778
resNode: depot_t deliver_cap: 37.26853339519113 cap_limit: 40
8893 customer_1 ('customer_1', 'customer_2')
5297 customer_1 -11.705886436242778
resNode: customer_2 deliver_cap: 39.75310228820387 cap_limit: 40
8894 customer_1 ('customer_1', 'customer_4')

8955 customer_1 ('customer_1', 'customer_5')
5682 customer_1 -12.825102874319189
resNode: customer_5 deliver_cap: 46.17351005153816 cap_limit: 40
8956 customer_5 ('customer_5', 'customer_3')
5685 customer_5 -23.26380841923739
resNode: customer_3 deliver_cap: 59.42219880190266 cap_limit: 40
8957 customer_5 ('customer_5', 'customer_1')
5685 customer_5 -23.26380841923739
resNode: customer_1 deliver_cap: 47.34218214603783 cap_limit: 40
8958 customer_5 ('customer_5', 'depot_t')
5685 customer_5 -23.26380841923739
resNode: depot_t deliver_cap: 33.005425107304966 cap_limit: 40
8959 customer_5 ('customer_5', 'customer_2')
5685 customer_5 -23.26380841923739
resNode: customer_2 deliver_cap: 37.47463971253514 cap_limit: 40
8960 customer_5 ('customer_5', 'customer_4')
5685 customer_5 -23.26380841923739
resNode: customer_4 deliver_cap: 59.2501600850442 cap_limit: 40
8961 customer_2 ('customer_2', 'customer_3')
5694 customer_2 -23.17887249477707
resNode: customer_3 deliver_cap: 61.08407308945573 cap_limit: 40
8962 customer_2 ('customer_2', 'customer_1')
5694 customer_2 -23.17887249477707
resNode: customer_1 deliver_cap: 47.34218214603783 cap_limit: 40
8963 customer_2 ('customer_2', 'depot_t')
5694 customer_2 -23.17887249477707
resNode: depot_t deliver_cap: 33.3459334765558 cap_limit: 40
8964 customer_2 ('customer_2', 'customer_4')
5694 customer_2 -23.17887249477707
resNode: customer_4 deliver_cap: 60.912034372597276 cap_limit: 40
8965 customer_2 ('customer_2', 'customer_5')
5694 customer_2 -23.17887249477707
resNode: customer_5 deliver_cap: 47.86946943778002 cap_limit: 40
8966 customer_2 ('customer_2', 'customer_3')
5718 customer_2 -19.709380552484433
resNode: customer_3 deliver_cap: 61.08407308945573 cap_limit: 40
8967 customer_2 ('customer_2', 'customer_1')
5718 customer_2 -19.709380552484433
resNode: customer_1 deliver_cap: 47.34218214603783 cap_limit: 40
8968 customer_2 ('customer_2', 'depot_t')
5718 customer_2 -19.709380552484433
resNode: depot_t deliver_cap: 33.34593347655581 cap_limit: 40
8969 customer_2 ('customer_2', 'customer_4')
5718 customer_2 -19.709380552484433
resNode: customer_4 deliver_cap: 60.912034372597276 cap_limit: 40
8970 customer_2 ('customer_2', 'customer_5')
5718 customer_2 -19.709380552484433
resNode: customer_5 deliver_cap: 47.869469437780026 cap_limit: 40
8971 customer_1 ('customer_1', 'customer_3')
5722 customer_1 -19.065003522996285
resNode: customer_3 deliver_cap: 57.8614864980266 cap_limit: 40
8972 customer_1 ('customer_1', 'depot_t')
5722 customer_1 -19.065003522996285
resNode: depot_t deliver_cap: 34.06785428412285 cap_limit: 40
8973 customer_1 ('customer_1', 'customer_2')
5722 customer_1 -19.065003522996285
resNode: customer_2 deliver_cap: 37.47463971253514 cap_limit: 40
8974 customer_1 ('customer_1', 'customer_4')
5722 customer_1 -19.065003522996285
resNode: customer_4 deliver_cap: 57.4299633059223 cap_limit: 40
8975 customer_1 ('customer_1', 'customer_5')
5722 customer_1 -19.065003522996285
resNode: customer_5 deliver_cap: 47.86946943778002 cap_limit: 40
8976 customer_5 ('customer_5', 'customer_3')
5725 customer_5 -25.921478853180467
resNode: customer_3 deliver_cap: 58.92367901658818 cap_limit: 40
8977 customer_5 ('customer_5', 'customer_1')
5725 customer_5 -25.921478853180467
resNode: customer_1 deliver_cap: 49.356870285325066 cap_limit: 40
8978 customer_5 ('customer_5', 'depot_t')
5725 customer_5 -25.921478853180467
resNode: depot_t deliver_cap: 32.78858056301983 cap_limit: 40
8979 customer_5 ('customer_5', 'customer_2')
5725 customer_5 -25.921478853180467
resNode: customer_2 deliver_cap: 36.79817991541255 cap_limit: 40
8980 customer_5 ('customer_5', 'customer_4')
5725 customer_5 -25.921478853180467
resNode: customer_4 deliver_cap: 58.71477486040292 cap_limit: 40
8981 customer_2 ('customer_2', 'customer_3')
5773 customer_2 -19.539317535711398
resNode: customer_3 deliver_cap: 61.08407308945573 cap_limit: 40
8982 customer_2 ('customer_2', 'customer_1')
5773 customer_2 -19.539317535711398
resNode: customer_1 deliver_cap: 47.34218214603783 cap_limit: 40
8983 customer_2 ('customer_2', 'depot_t')
5773 customer_2 -19.539317535711398
resNode: depot_t deliver_cap: 33.3459334765558 cap_limit: 40
8984 customer_2 ('customer_2', 'customer_4')
5773 customer_2 -19.539317535711398
resNode: customer_4 deliver_cap: 60.912034372597276 cap_limit: 40
8985 customer_2 ('customer_2', 'customer_5')
5773 customer_2 -19.539317535711398
resNode: customer_5 deliver_cap: 47.86946943778002 cap_limit: 40
8986 customer_2 ('customer_2', 'customer_3')
5779 customer_2 -25.69201803964093
resNode: customer_3 deliver_cap: 60.941669222902625 cap_limit: 40
8987 customer_2 ('customer_2', 'customer_1')
5779 customer_2 -25.69201803964093
resNode: customer_1 deliver_cap: 49.35687028532506 cap_limit: 40
8988 customer_2 ('customer_2', 'depot_t')
5779 customer_2 -25.69201803964093
resNode: depot_t deliver_cap: 33.23124144304592 cap_limit: 40
8989 customer_2 ('customer_2', 'customer_4')
5779 customer_2 -25.69201803964093
resNode: customer_4 deliver_cap: 60.73276506671736 cap_limit: 40
8990 customer_2 ('customer_2', 'customer_5')
5779 customer_2 -25.69201803964093
resNode: customer_5 deliver_cap: 44.89536478872498 cap_limit: 40
8991 customer_2 ('customer_2', 'customer_3')
5858 customer_2 -16.069825593418763
resNode: customer_3 deliver_cap: 61.08407308945573 cap_limit: 40
8992 customer_2 ('customer_2', 'customer_1')
5858 customer_2 -16.069825593418763
resNode: customer_1 deliver_cap: 47.34218214603783 cap_limit: 40
8993 customer_2 ('customer_2', 'depot_t')
5858 customer_2 -16.069825593418763
resNode: depot_t deliver_cap: 33.34593347655581 cap_limit: 40
8994 customer_2 ('customer_2', 'customer_4')
5858 customer_2 -16.069825593418763
resNode: customer_4 deliver_cap: 60.912034372597276 cap_limit: 40
8995 customer_2 ('customer_2', 'customer_5')
5858 customer_2 -16.069825593418763
resNode: customer_5 deliver_cap: 47.869469437780026 cap_limit: 40
8996 customer_2 ('customer_2', 'customer_3')
5864 customer_2 -22.2225260973483
resNode: customer_3 deliver_cap: 60.94166922290263 cap_limit: 40
8997 customer_2 ('customer_2', 'customer_1')
5864 customer_2 -22.2225260973483
resNode: customer_1 deliver_cap: 49.356870285325066 cap_limit: 40
8998 customer_2 ('customer_2', 'depot_t')
5864 customer_2 -22.2225260973483
resNode: depot_t deliver_cap: 33.231241443045924 cap_limit: 40
8999 customer_2 ('customer_2', 'customer_4')
5864 customer_2 -22.2225260973483
resNode: customer_4 deliver_cap: 60.73276506671736 cap_limit: 40
9000 customer_2 ('customer_2', 'customer_5')
5864 customer_2 -22.2225260973483
resNode: customer_5 deliver_cap: 44.89536478872499 cap_limit: 40
9001 customer_1 ('customer_1', 'customer_3')
5897 customer_1 -14.600591332550717
resNode: customer_3 deliver_cap: 57.8614864980266 cap_limit: 40
9002 customer_1 ('customer_1', 'depot_t')
5897 customer_1 -14.600591332550717
resNode: depot_t deliver_cap: 34.06785428412285 cap_limit: 40
9003 customer_1 ('customer_1', 'customer_2')
5897 customer_1 -14.600591332550717
resNode: customer_2 deliver_cap: 37.47463971253514 cap_limit: 40
9004 customer_1 ('customer_1', 'customer_4')
5897 customer_1 -14.600591332550717
resNode: customer_4 deliver_cap: 57.429963305922314 cap_limit: 40
9005 customer_1 ('customer_1', 'customer_5')
5897 customer_1 -14.600591332550717
resNode: customer_5 deliver_cap: 47.86946943778003 cap_limit: 40
9006 customer_5 ('customer_5', 'customer_3')
5900 customer_5 -21.457066662734903
resNode: customer_3 deliver_cap: 58.92367901658819 cap_limit: 40
9007 customer_5 ('customer_5', 'customer_1')
5900 customer_5 -21.457066662734903
resNode: customer_1 deliver_cap: 49.356870285325066 cap_limit: 40
9008 customer_5 ('customer_5', 'depot_t')
5900 customer_5 -21.457066662734903
resNode: depot_t deliver_cap: 32.788580563019835 cap_limit: 40
9009 customer_5 ('customer_5', 'customer_2')
5900 customer_5 -21.457066662734903
resNode: customer_2 deliver_cap: 36.79817991541255 cap_limit: 40
9010 customer_5 ('customer_5', 'customer_4')
5900 customer_5 -21.457066662734903
resNode: customer_4 deliver_cap: 58.71477486040292 cap_limit: 40
9011 customer_2 ('customer_2', 'customer_3')
5909 customer_2 -21.3976688659684
resNode: customer_3 deliver_cap: 60.94166922290264 cap_limit: 40
9012 customer_2 ('customer_2', 'customer_1')
5909 customer_2 -21.3976688659684
resNode: customer_1 deliver_cap: 49.35687028532507 cap_limit: 40
9013 customer_2 ('customer_2', 'depot_t')
5909 customer_2 -21.3976688659684
resNode: depot_t deliver_cap: 33.231241443045924 cap_limit: 40
9014 customer_2 ('customer_2', 'customer_4')
5909 customer_2 -21.3976688659684
resNode: customer_4 deliver_cap: 60.73276506671738 cap_limit: 40
9015 customer_2 ('customer_2', 'customer_5')
5909 customer_2 -21.3976688659684
resNode: customer_5 deliver_cap: 44.895364788725004 cap_limit: 40
9016 customer_2 ('customer_2', 'customer_3')
5933 customer_2 -17.928176923675757
resNode: customer_3 deliver_cap: 60.94166922290264 cap_limit: 40
9017 customer_2 ('customer_2', 'customer_1')
5933 customer_2 -17.928176923675757
resNode: customer_1 deliver_cap: 49.35687028532507 cap_limit: 40
9018 customer_2 ('customer_2', 'depot_t')
5933 customer_2 -17.928176923675757
resNode: depot_t deliver_cap: 33.231241443045924 cap_limit: 40
9019 customer_2 ('customer_2', 'customer_4')
5933 customer_2 -17.928176923675757
resNode: customer_4 deliver_cap: 60.73276506671738 cap_limit: 40
9020 customer_2 ('customer_2', 'customer_5')
5933 customer_2 -17.928176923675757
resNode: customer_5 deliver_cap: 44.895364788725004 cap_limit: 40
9021 customer_1 ('customer_1', 'customer_3')
5937 customer_1 -17.337943954755147
resNode: customer_3 deliver_cap: 57.028528361881555 cap_limit: 40
9022 customer_1 ('customer_1', 'depot_t')
5937 customer_1 -17.337943954755147
resNode: depot_t deliver_cap: 34.16973849288309 cap_limit: 40
9023 customer_1 ('customer_1', 'customer_2')
5937 customer_1 -17.337943954755147
resNode: customer_2 deliver_cap: 36.798179915412554 cap_limit: 40
9024 customer_1 ('customer_1', 'customer_4')
5937 customer_1 -17.337943954755147
resNode: customer_4 deliver_cap: 56.50453591432634 cap_limit: 40
9025 customer_1 ('customer_1', 'customer_5')
5937 customer_1 -17.337943954755147
resNode: customer_5 deliver_cap: 44.895364788725004 cap_limit: 40
9026 customer_5 ('customer_5', 'customer_3')
5940 customer_5 -20.612189070205314
resNode: customer_3 deliver_cap: 53.755095195976835 cap_limit: 40
9027 customer_5 ('customer_5', 'customer_1')
5940 customer_5 -20.612189070205314
resNode: customer_1 deliver_cap: 46.70149438931541 cap_limit: 40
9028 customer_5 ('customer_5', 'depot_t')
5940 customer_5 -20.612189070205314
resNode: depot_t deliver_cap: 27.90167198343781 cap_limit: 40
9029 customer_5 ('customer_5', 'customer_2')
5940 customer_5 -20.612189070205314
resNode: customer_2 deliver_cap: 31.45165608299308 cap_limit: 40
9030 customer_5 ('customer_5', 'customer_4')
5940 customer_5 -20.612189070205314
resNode: customer_4 deliver_cap: 53.50932560046475 cap_limit: 40
9031 customer_2 ('customer_2', 'customer_3')
6014 customer_2 -28.156092290321254
resNode: customer_3 deliver_cap: 69.78704970411303 cap_limit: 40
9032 customer_2 ('customer_2', 'customer_1')
6014 customer_2 -28.156092290321254
resNode: customer_1 deliver_cap: 58.31066551491674 cap_limit: 40
9033 customer_2 ('customer_2', 'depot_t')
6014 customer_2 -28.156092290321254
resNode: depot_t deliver_cap: 39.37276408068746 cap_limit: 40
9034 customer_2 ('customer_2', 'customer_4')
6014 customer_2 -28.156092290321254
resNode: customer_4 deliver_cap: 69.54128010860096 cap_limit: 40
9035 customer_2 ('customer_2', 'customer_5')
6014 customer_2 -28.156092290321254
resNode: customer_5 deliver_cap: 50.90904448743346 cap_limit: 40
9036 customer_2 ('customer_2', 'customer_3')
6083 customer_2 -15.899762576645738
resNode: customer_3 deliver_cap: 61.08407308945573 cap_limit: 40
9037 customer_2 ('customer_2', 'customer_1')
6083 customer_2 -15.899762576645738
resNode: customer_1 deliver_cap: 47.34218214603783 cap_limit: 40
9038 customer_2 ('customer_2', 'depot_t')
6083 customer_2 -15.899762576645738
resNode: depot_t deliver_cap: 33.34593347655581 cap_limit: 40
9039 customer_2 ('customer_2', 'customer_4')
6083 customer_2 -15.899762576645738
resNode: customer_4 deliver_cap: 60.912034372597276 cap_limit: 40
9040 customer_2 ('customer_2', 'customer_5')
6083 customer_2 -15.899762576645738
resNode: customer_5 deliver_cap: 47.869469437780026 cap_limit: 40
9041 customer_2 ('customer_2', 'customer_3')
6089 customer_2 -22.052463080575272
resNode: customer_3 deliver_cap: 60.94166922290263 cap_limit: 40
9042 customer_2 ('customer_2', 'customer_1')
6089 customer_2 -22.052463080575272
resNode: customer_1 deliver_cap: 49.356870285325066 cap_limit: 40
9043 customer_2 ('customer_2', 'depot_t')
6089 customer_2 -22.052463080575272
resNode: depot_t deliver_cap: 33.231241443045924 cap_limit: 40
9044 customer_2 ('customer_2', 'customer_4')
6089 customer_2 -22.052463080575272
resNode: customer_4 deliver_cap: 60.73276506671736 cap_limit: 40
9045 customer_2 ('customer_2', 'customer_5')
6089 customer_2 -22.052463080575272
resNode: customer_5 deliver_cap: 44.89536478872499 cap_limit: 40
9046 customer_2 ('customer_2', 'customer_3')
6138 customer_2 -17.588050890129708
resNode: customer_3 deliver_cap: 60.94166922290264 cap_limit: 40
9047 customer_2 ('customer_2', 'customer_1')
6138 customer_2 -17.588050890129708
resNode: customer_1 deliver_cap: 49.35687028532507 cap_limit: 40
9048 customer_2 ('customer_2', 'depot_t')
6138 customer_2 -17.588050890129708
resNode: depot_t deliver_cap: 33.231241443045924 cap_limit: 40
9049 customer_2 ('customer_2', 'customer_4')
6138 customer_2 -17.588050890129708
resNode: customer_4 deliver_cap: 60.73276506671738 cap_limit: 40
9050 customer_2 ('customer_2', 'customer_5')
6138 customer_2 -17.588050890129708
resNode: customer_5 deliver_cap: 44.895364788725004 cap_limit: 40
9051 customer_2 ('customer_2', 'customer_3')
6149 customer_2 -20.23820336758657
resNode: customer_3 deliver_cap: 56.129201321052655 cap_limit: 40
9052 customer_2 ('customer_2', 'customer_1')
6149 customer_2 -20.23820336758657
resNode: customer_1 deliver_cap: 46.701494389315414 cap_limit: 40
9053 customer_2 ('customer_2', 'depot_t')
6149 customer_2 -20.23820336758657
resNode: depot_t deliver_cap: 28.446485374239156 cap_limit: 40
9054 customer_2 ('customer_2', 'customer_4')
6149 customer_2 -20.23820336758657
resNode: customer_4 deliver_cap: 55.88343172554058 cap_limit: 40
9055 customer_2 ('customer_2', 'customer_5')
6149 customer_2 -20.23820336758657
resNode: customer_5 deliver_cap: 37.25119610437309 cap_limit: 40
9056 customer_5 ('customer_5', 'customer_3')
6195 customer_5 -24.232726289308573
resNode: customer_3 deliver_cap: 66.58556366690925 cap_limit: 40
9057 customer_5 ('customer_5', 'customer_1')
6195 customer_5 -24.232726289308573
resNode: customer_1 deliver_cap: 57.60739258960797 cap_limit: 40
9058 customer_5 ('customer_5', 'depot_t')
6195 customer_5 -24.232726289308573
resNode: depot_t deliver_cap: 38.16604676018375 cap_limit: 40
9059 customer_5 ('customer_5', 'customer_2')
6195 customer_5 -24.232726289308573
resNode: customer_2 deliver_cap: 42.35755428328563 cap_limit: 40
9060 customer_5 ('customer_5', 'customer_4')
6195 customer_5 -24.232726289308573
resNode: customer_4 deliver_cap: 66.33979407139718 cap_limit: 40
9061 customer_2 ('customer_2', 'customer_3')
6209 customer_2 -24.02880360346286
resNode: customer_3 deliver_cap: 68.95966979198508 cap_limit: 40
9062 customer_2 ('customer_2', 'customer_1')
6209 customer_2 -24.02880360346286
resNode: customer_1 deliver_cap: 57.607392589607976 cap_limit: 40
9063 customer_2 ('customer_2', 'depot_t')
6209 customer_2 -24.02880360346286
resNode: depot_t deliver_cap: 38.71086015098509 cap_limit: 40
9064 customer_2 ('customer_2', 'customer_4')
6209 customer_2 -24.02880360346286
resNode: customer_4 deliver_cap: 68.713900196473 cap_limit: 40
9065 customer_2 ('customer_2', 'customer_5')
6209 customer_2 -24.02880360346286
resNode: customer_5 deliver_cap: 50.0816645753055 cap_limit: 40
9066 customer_2 ('customer_2', 'customer_3')
6233 customer_2 -11.660133954464392
resNode: customer_3 deliver_cap: 61.73998637121892 cap_limit: 40
9067 customer_2 ('customer_2', 'customer_1')
6233 customer_2 -11.660133954464392
resNode: customer_1 deliver_cap: 47.857542581708906 cap_limit: 40
9068 customer_2 ('customer_2', 'depot_t')
6233 customer_2 -11.660133954464392
resNode: depot_t deliver_cap: 33.814442963529515 cap_limit: 40
9069 customer_2 ('customer_2', 'customer_4')
6233 customer_2 -11.660133954464392
resNode: customer_4 deliver_cap: 61.56794765436046 cap_limit: 40
9070 customer_2 ('customer_2', 'customer_5')
6233 customer_2 -11.660133954464392
resNode: customer_5 deliver_cap: 48.52538271954322 cap_limit: 40
9071 customer_2 ('customer_2', 'customer_3')
6239 customer_2 -17.988525516009066
resNode: customer_3 deliver_cap: 61.73813535075793 cap_limit: 40
9072 customer_2 ('customer_2', 'customer_1')
6239 customer_2 -17.988525516009066
resNode: customer_1 deliver_cap: 50.01278356708825 cap_limit: 40
9073 customer_2 ('customer_2', 'depot_t')
6239 customer_2 -17.988525516009066
resNode: depot_t deliver_cap: 33.84030377611174 cap_limit: 40
9074 customer_2 ('customer_2', 'customer_4')
6239 customer_2 -17.988525516009066
resNode: customer_4 deliver_cap: 61.52923119457266 cap_limit: 40
9075 customer_2 ('customer_2', 'customer_5')
6239 customer_2 -17.988525516009066
resNode: customer_5 deliver_cap: 45.691830916580294 cap_limit: 40
9076 customer_2 ('customer_2', 'customer_3')
6288 customer_2 -13.524113325563498
resNode: customer_3 deliver_cap: 61.738135350757936 cap_limit: 40
9077 customer_2 ('customer_2', 'customer_1')
6288 customer_2 -13.524113325563498
resNode: customer_1 deliver_cap: 50.012783567088256 cap_limit: 40
9078 customer_2 ('customer_2', 'depot_t')
6288 customer_2 -13.524113325563498
resNode: depot_t deliver_cap: 33.840303776111746 cap_limit: 40
9079 customer_2 ('customer_2', 'customer_4')
6288 customer_2 -13.524113325563498
resNode: customer_4 deliver_cap: 61.529231194572674 cap_limit: 40
9080 customer_2 ('customer_2', 'customer_5')
6288 customer_2 -13.524113325563498
resNode: customer_5 deliver_cap: 45.6918309165803 cap_limit: 40
9081 customer_2 ('customer_2', 'customer_3')
6299 customer_2 -16.349956860635505
resNode: customer_3 deliver_cap: 57.066220295000065 cap_limit: 40
9082 customer_2 ('customer_2', 'customer_1')
6299 customer_2 -16.349956860635505
resNode: customer_1 deliver_cap: 47.49796051717072 cap_limit: 40
9083 customer_2 ('customer_2', 'depot_t')
6299 customer_2 -16.349956860635505
resNode: depot_t deliver_cap: 29.196100553397084 cap_limit: 40
9084 customer_2 ('customer_2', 'customer_4')
6299 customer_2 -16.349956860635505
resNode: customer_4 deliver_cap: 56.82045069948799 cap_limit: 40
9085 customer_2 ('customer_2', 'customer_5')
6299 customer_2 -16.349956860635505
resNode: customer_5 deliver_cap: 38.188215078320496 cap_limit: 40
9086 customer_5 ('customer_5', 'customer_3')
6350 customer_5 -19.537734615168365
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9087 customer_5 ('customer_5', 'customer_1')
6350 customer_5 -19.537734615168365
resNode: customer_1 deliver_cap: 59.42593662300047 cap_limit: 40
9088 customer_5 ('customer_5', 'depot_t')
6350 customer_5 -19.537734615168365
resNode: depot_t deliver_cap: 37.39208742530091 cap_limit: 40
9089 customer_5 ('customer_5', 'customer_2')
6350 customer_5 -19.537734615168365
resNode: customer_2 deliver_cap: 41.4849503802683 cap_limit: 40
9090 customer_5 ('customer_5', 'customer_4')
6350 customer_5 -19.537734615168365
resNode: customer_4 deliver_cap: 66.69117679497003 cap_limit: 40
9091 customer_2 ('customer_2', 'customer_3')
6364 customer_2 -17.60844678977304
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9092 customer_2 ('customer_2', 'customer_1')
6364 customer_2 -17.60844678977304
resNode: customer_1 deliver_cap: 57.051830497924634 cap_limit: 40

9121 customer_2 ('customer_2', 'customer_3')
6494 customer_2 -24.201966727776494
resNode: customer_3 deliver_cap: 66.58556366690927 cap_limit: 40
9122 customer_2 ('customer_2', 'customer_1')
6494 customer_2 -24.201966727776494
resNode: customer_1 deliver_cap: 55.58940238329354 cap_limit: 40
9123 customer_2 ('customer_2', 'depot_t')
6494 customer_2 -24.201966727776494
resNode: depot_t deliver_cap: 36.81157525092444 cap_limit: 40
9124 customer_2 ('customer_2', 'customer_4')
6494 customer_2 -24.201966727776494
resNode: customer_4 deliver_cap: 66.3397940713972 cap_limit: 40
9125 customer_2 ('customer_2', 'customer_5')
6494 customer_2 -24.201966727776494
resNode: customer_5 deliver_cap: 47.70755845022969 cap_limit: 40
9126 customer_2 ('customer_2', 'customer_3')
6508 customer_2 -14.236745623242006
resNode: customer_3 deliver_cap: 61.73998637121892 cap_limit: 40
9127 customer_2 ('customer_2', 'customer_1')
6508 customer_2 -14.236745623242006
resNode: customer_1 deliver_cap: 47.857542581708906 cap_limit: 40
9128 customer_2 ('customer_2', 'depot_t')
6508 customer_2 -14.236745623242006
resNode: depot_t deliver_cap: 33.814442963529515 cap_limit: 40
9129 customer_2 ('customer_2', 'customer_4')
6508 customer_2 -14.236745623242006
resNode: customer_4 deliver_cap: 61.56794765436046 cap_limit: 40
9130 customer_2 ('customer_2', 'customer_5')
6508 customer_2 -14.236745623242006
resNode: customer_5 deliver_cap: 48.52538271954322 cap_limit: 40
9131 customer_2 ('customer_2', 'customer_3')
6514 customer_2 -20.56513718478668
resNode: customer_3 deliver_cap: 61.73813535075793 cap_limit: 40
9132 customer_2 ('customer_2', 'customer_1')
6514 customer_2 -20.56513718478668
resNode: customer_1 deliver_cap: 50.01278356708825 cap_limit: 40
9133 customer_2 ('customer_2', 'depot_t')
6514 customer_2 -20.56513718478668
resNode: depot_t deliver_cap: 33.84030377611174 cap_limit: 40
9134 customer_2 ('customer_2', 'customer_4')
6514 customer_2 -20.56513718478668
resNode: customer_4 deliver_cap: 61.52923119457266 cap_limit: 40
9135 customer_2 ('customer_2', 'customer_5')
6514 customer_2 -20.56513718478668
resNode: customer_5 deliver_cap: 45.691830916580294 cap_limit: 40
9136 customer_5 ('customer_5', 'customer_3')
6540 customer_5 -27.89408309336679
resNode: customer_3 deliver_cap: 68.81515267244649 cap_limit: 40
9137 customer_5 ('customer_5', 'customer_1')
6540 customer_5 -27.89408309336679
resNode: customer_1 deliver_cap: 59.50254324431461 cap_limit: 40
9138 customer_5 ('customer_5', 'depot_t')
6540 customer_5 -27.89408309336679
resNode: depot_t deliver_cap: 39.94971796461353 cap_limit: 40
9139 customer_5 ('customer_5', 'customer_2')
6540 customer_5 -27.89408309336679
resNode: customer_2 deliver_cap: 44.25270493799227 cap_limit: 40
9140 customer_5 ('customer_5', 'customer_4')
6540 customer_5 -27.89408309336679
resNode: customer_4 deliver_cap: 68.5693830769344 cap_limit: 40
9141 customer_2 ('customer_2', 'customer_3')
6543 customer_2 -17.06540986248025
resNode: customer_3 deliver_cap: 66.84281442767931 cap_limit: 40
9142 customer_2 ('customer_2', 'customer_1')
6543 customer_2 -17.06540986248025
resNode: customer_1 deliver_cap: 51.86690748321349 cap_limit: 40
9143 customer_2 ('customer_2', 'depot_t')
6543 customer_2 -17.06540986248025
resNode: depot_t deliver_cap: 37.459320146715505 cap_limit: 40
9144 customer_2 ('customer_2', 'customer_4')
6543 customer_2 -17.06540986248025
resNode: customer_4 deliver_cap: 66.67077571082086 cap_limit: 40
9145 customer_2 ('customer_2', 'customer_5')
6543 customer_2 -17.06540986248025
resNode: customer_5 deliver_cap: 53.628210776003606 cap_limit: 40
9146 customer_2 ('customer_2', 'customer_3')
6563 customer_2 -16.813357292019617
resNode: customer_3 deliver_cap: 61.73998637121892 cap_limit: 40
9147 customer_2 ('customer_2', 'customer_1')
6563 customer_2 -16.813357292019617
resNode: customer_1 deliver_cap: 47.857542581708906 cap_limit: 40
9148 customer_2 ('customer_2', 'depot_t')
6563 customer_2 -16.813357292019617
resNode: depot_t deliver_cap: 33.81444296352951 cap_limit: 40
9149 customer_2 ('customer_2', 'customer_4')
6563 customer_2 -16.813357292019617
resNode: customer_4 deliver_cap: 61.56794765436046 cap_limit: 40
9150 customer_2 ('customer_2', 'customer_5')
6563 customer_2 -16.813357292019617
resNode: customer_5 deliver_cap: 48.52538271954321 cap_limit: 40
9151 customer_3 ('customer_3', 'customer_1')
6566 customer_3 -19.40338089363459
resNode: customer_1 deliver_cap: 51.86690748321349 cap_limit: 40
9152 customer_3 ('customer_3', 'depot_t')
6566 customer_3 -19.40338089363459
resNode: depot_t deliver_cap: 39.42065934277119 cap_limit: 40
9153 customer_3 ('customer_3', 'customer_2')
6566 customer_3 -19.40338089363459
resNode: customer_2 deliver_cap: 44.53139737154798 cap_limit: 40
9154 customer_3 ('customer_3', 'customer_4')
6566 customer_3 -19.40338089363459
resNode: customer_4 deliver_cap: 58.68180036184503 cap_limit: 40
9155 customer_3 ('customer_3', 'customer_5')
6566 customer_3 -19.40338089363459
resNode: customer_5 deliver_cap: 55.188923079879665 cap_limit: 40
9156 customer_2 ('customer_2', 'customer_3')
6568 customer_2 -8.56539732585075
resNode: customer_3 deliver_cap: 46.68887048720923 cap_limit: 40
9157 customer_2 ('customer_2', 'customer_1')
6568 customer_2 -8.56539732585075
resNode: customer_1 deliver_cap: 33.48103547436082 cap_limit: 40
9158 customer_2 ('customer_2', 'depot_t')
6568 customer_2 -8.56539732585075
resNode: depot_t deliver_cap: 22.511216289812527 cap_limit: 40
9159 customer_2 ('customer_2', 'customer_4')
6568 customer_2 -8.56539732585075
resNode: customer_4 deliver_cap: 46.55369720967759 cap_limit: 40
9160 customer_2 ('customer_2', 'customer_5')
6568 customer_2 -8.56539732585075
resNode: customer_5 deliver_cap: 36.30596761803546 cap_limit: 40
9161 customer_4 ('customer_4', 'customer_3')
6569 customer_4 -19.268569398960814
resNode: customer_3 deliver_cap: 58.422315886599186 cap_limit: 40
9162 customer_4 ('customer_4', 'customer_1')
6569 customer_4 -19.268569398960814
resNode: customer_1 deliver_cap: 51.32397288743839 cap_limit: 40
9163 customer_4 ('customer_4', 'depot_t')
6569 customer_4 -19.268569398960814
resNode: depot_t deliver_cap: 39.11242849126812 cap_limit: 40
9164 customer_4 ('customer_4', 'customer_2')
6569 customer_4 -19.268569398960814
resNode: customer_2 deliver_cap: 44.1923434348946 cap_limit: 40
9165 customer_4 ('customer_4', 'customer_5')
6569 customer_4 -19.268569398960814
resNode: customer_5 deliver_cap: 54.75739988777537 cap_limit: 40
9166 customer_5 ('customer_5', 'customer_3')
6570 customer_5 -19.88683571563887
resNode: customer_3 deliver_cap: 58.41150967130879 cap_limit: 40
9167 customer_5 ('customer_5', 'customer_1')
6570 customer_5 -19.88683571563887
resNode: customer_1 deliver_cap: 46.548069257714076 cap_limit: 40
9168 customer_5 ('customer_5', 'depot_t')
6570 customer_5 -19.88683571563887
resNode: depot_t deliver_cap: 32.28350429973792 cap_limit: 40
9169 customer_5 ('customer_5', 'customer_2')
6570 customer_5 -19.88683571563887
resNode: customer_2 deliver_cap: 36.680526824211384 cap_limit: 40
9170 customer_5 ('customer_5', 'customer_4')
6570 customer_5 -19.88683571563887
resNode: customer_4 deliver_cap: 58.23947095445034 cap_limit: 40
9171 customer_2 ('customer_2', 'customer_3')
6574 customer_2 -16.786732252505814
resNode: customer_3 deliver_cap: 61.56794765436046 cap_limit: 40
9172 customer_2 ('customer_2', 'customer_1')
6574 customer_2 -16.786732252505814
resNode: customer_1 deliver_cap: 47.72236930417726 cap_limit: 40
9173 customer_2 ('customer_2', 'depot_t')
6574 customer_2 -16.786732252505814
resNode: depot_t deliver_cap: 33.69155816577347 cap_limit: 40
9174 customer_2 ('customer_2', 'customer_4')
6574 customer_2 -16.786732252505814
resNode: customer_4 deliver_cap: 61.395908937502 cap_limit: 40
9175 customer_2 ('customer_2', 'customer_5')
6574 customer_2 -16.786732252505814
resNode: customer_5 deliver_cap: 48.35334400268476 cap_limit: 40
9176 customer_1 ('customer_1', 'customer_3')
6577 customer_1 -16.682951067550704
resNode: customer_3 deliver_cap: 56.85079736743273 cap_limit: 40
9177 customer_1 ('customer_1', 'depot_t')
6577 customer_1 -16.682951067550704
resNode: depot_t deliver_cap: 33.34593347655581 cap_limit: 40
9178 customer_1 ('customer_1', 'customer_2')
6577 customer_1 -16.682951067550704
resNode: customer_2 deliver_cap: 36.680526824211384 cap_limit: 40
9179 customer_1 ('customer_1', 'customer_4')
6577 customer_1 -16.682951067550704
resNode: customer_4 deliver_cap: 56.419274175328454 cap_limit: 40
9180 customer_1 ('customer_1', 'customer_5')
6577 customer_1 -16.682951067550704
resNode: customer_5 deliver_cap: 46.858780307186166 cap_limit: 40
9181 customer_2 ('customer_2', 'customer_3')
6579 customer_2 -14.856710935740686
resNode: customer_3 deliver_cap: 48.52538271954321 cap_limit: 40
9182 customer_2 ('customer_2', 'customer_1')
6579 customer_2 -14.856710935740686
resNode: customer_1 deliver_cap: 37.47463971253514 cap_limit: 40
9183 customer_2 ('customer_2', 'depot_t')
6579 customer_2 -14.856710935740686
resNode: depot_t deliver_cap: 24.37544035518972 cap_limit: 40
9184 customer_2 ('customer_2', 'customer_4')
6579 customer_2 -14.856710935740686
resNode: customer_4 deliver_cap: 48.35334400268476 cap_limit: 40
9185 customer_2 ('customer_2', 'customer_5')
6579 customer_2 -14.856710935740686
resNode: customer_5 deliver_cap: 35.31077906786751 cap_limit: 40
9186 customer_2 ('customer_2', 'customer_3')
6588 customer_2 -16.7855464733197
resNode: customer_3 deliver_cap: 66.15180676032918 cap_limit: 40
9187 customer_2 ('customer_2', 'customer_1')
6588 customer_2 -16.7855464733197
resNode: customer_1 deliver_cap: 51.32397288743839 cap_limit: 40
9188 customer_2 ('customer_2', 'depot_t')
6588 customer_2 -16.7855464733197
resNode: depot_t deliver_cap: 36.96574324146541 cap_limit: 40
9189 customer_2 ('customer_2', 'customer_4')
6588 customer_2 -16.7855464733197
resNode: customer_4 deliver_cap: 65.97976804347073 cap_limit: 40
9190 customer_2 ('customer_2', 'customer_5')
6588 customer_2 -16.7855464733197
resNode: customer_5 deliver_cap: 52.93720310865348 cap_limit: 40
9191 customer_2 ('customer_2', 'customer_3')
6599 customer_2 -25.368291598215745
resNode: customer_3 deliver_cap: 69.30558476932555 cap_limit: 40
9192 customer_2 ('customer_2', 'customer_1')
6599 customer_2 -25.368291598215745
resNode: customer_1 deliver_cap: 56.2448007353204 cap_limit: 40
9193 customer_2 ('customer_2', 'depot_t')
6599 customer_2 -25.368291598215745
resNode: depot_t deliver_cap: 39.627176860898736 cap_limit: 40
9194 customer_2 ('customer_2', 'customer_4')
6599 customer_2 -25.368291598215745
resNode: customer_4 deliver_cap: 69.09668061314028 cap_limit: 40
9195 customer_2 ('customer_2', 'customer_5')
6599 customer_2 -25.368291598215745
resNode: customer_5 deliver_cap: 53.259280335147906 cap_limit: 40
9196 customer_2 ('customer_2', 'customer_3')
6608 customer_2 -17.157265080265816
resNode: customer_3 deliver_cap: 60.07338395886186 cap_limit: 40
9197 customer_2 ('customer_2', 'customer_1')
6608 customer_2 -17.157265080265816
resNode: customer_1 deliver_cap: 46.548069257714076 cap_limit: 40
9198 customer_2 ('customer_2', 'depot_t')
6608 customer_2 -17.157265080265816
resNode: depot_t deliver_cap: 32.62401266898876 cap_limit: 40
9199 customer_2 ('customer_2', 'customer_4')
6608 customer_2 -17.157265080265816
resNode: customer_4 deliver_cap: 59.90134524200341 cap_limit: 40
9200 customer_2 ('customer_2', 'customer_5')
6608 customer_2 -17.157265080265816
resNode: customer_5 deliver_cap: 46.858780307186166 cap_limit: 40
9201 customer_1 ('customer_1', 'customer_3')
6612 customer_1 -16.51288805077767
resNode: customer_3 deliver_cap: 56.85079736743273 cap_limit: 40
9202 customer_1 ('customer_1', 'depot_t')
6612 customer_1 -16.51288805077767
resNode: depot_t deliver_cap: 33.3459334765558 cap_limit: 40
9203 customer_1 ('customer_1', 'customer_2')
6612 customer_1 -16.51288805077767
resNode: customer_2 deliver_cap: 36.680526824211384 cap_limit: 40
9204 customer_1 ('customer_1', 'customer_4')
6612 customer_1 -16.51288805077767
resNode: customer_4 deliver_cap: 56.41927417532844 cap_limit: 40
9205 customer_1 ('customer_1', 'customer_5')
6612 customer_1 -16.51288805077767
resNode: customer_5 deliver_cap: 46.85878030718616 cap_limit: 40
9206 customer_5 ('customer_5', 'customer_3')
6615 customer_5 -23.098643078124212
resNode: customer_3 deliver_cap: 57.6964136437242 cap_limit: 40
9207 customer_5 ('customer_5', 'customer_1')
6615 customer_5 -23.098643078124212
resNode: customer_1 deliver_cap: 48.3461811547312 cap_limit: 40
9208 customer_5 ('customer_5', 'depot_t')
6615 customer_5 -23.098643078124212
resNode: depot_t deliver_cap: 31.850083513182668 cap_limit: 40
9209 customer_5 ('customer_5', 'customer_2')
6615 customer_5 -23.098643078124212
resNode: customer_2 deliver_cap: 35.78749078481868 cap_limit: 40
9210 customer_5 ('customer_5', 'customer_4')
6615 customer_5 -23.098643078124212
resNode: customer_4 deliver_cap: 57.487509487538944 cap_limit: 40
9211 customer_2 ('customer_2', 'customer_3')
6648 customer_2 -14.185543624176988
resNode: customer_3 deliver_cap: 61.56794765436046 cap_limit: 40
9212 customer_2 ('customer_2', 'customer_1')
6648 customer_2 -14.185543624176988
resNode: customer_1 deliver_cap: 47.72236930417726 cap_limit: 40
9213 customer_2 ('customer_2', 'depot_t')
6648 customer_2 -14.185543624176988
resNode: depot_t deliver_cap: 33.69155816577347 cap_limit: 40
9214 customer_2 ('customer_2', 'customer_4')
6648 customer_2 -14.185543624176988
resNode: customer_4 deliver_cap: 61.395908937502 cap_limit: 40
9215 customer_2 ('customer_2', 'customer_5')
6648 customer_2 -14.185543624176988
resNode: customer_5 deliver_cap: 48.35334400268476 cap_limit: 40
9216 customer_2 ('customer_2', 'customer_3')
6654 customer_2 -20.46785338656315
resNode: customer_3 deliver_cap: 61.52923119457266 cap_limit: 40
9217 customer_2 ('customer_2', 'customer_1')
6654 customer_2 -20.46785338656315
resNode: customer_1 deliver_cap: 49.8407448502298 cap_limit: 40
9218 customer_2 ('customer_2', 'depot_t')
6654 customer_2 -20.46785338656315
resNode: depot_t deliver_cap: 33.680553539028885 cap_limit: 40
9219 customer_2 ('customer_2', 'customer_4')
6654 customer_2 -20.46785338656315
resNode: customer_4 deliver_cap: 61.32032703838739 cap_limit: 40
9220 customer_2 ('customer_2', 'customer_5')
6654 customer_2 -20.46785338656315
resNode: customer_5 deliver_cap: 45.482926760395024 cap_limit: 40
9221 customer_5 ('customer_5', 'customer_3')
6665 customer_5 -27.75071749598474
resNode: customer_3 deliver_cap: 68.5693830769344 cap_limit: 40
9222 customer_5 ('customer_5', 'customer_1')
6665 customer_5 -27.75071749598474
resNode: customer_1 deliver_cap: 59.29363908812934 cap_limit: 40
9223 customer_5 ('customer_5', 'depot_t')
6665 customer_5 -27.75071749598474
resNode: depot_t deliver_cap: 39.75310228820386 cap_limit: 40
9224 customer_5 ('customer_5', 'customer_2')
6665 customer_5 -27.75071749598474
resNode: customer_2 deliver_cap: 44.04380078180701 cap_limit: 40
9225 customer_5 ('customer_5', 'customer_4')
6665 customer_5 -27.75071749598474
resNode: customer_4 deliver_cap: 68.32361348142231 cap_limit: 40
9226 customer_5 ('customer_5', 'customer_3')
6675 customer_5 -24.118482050030877
resNode: customer_3 deliver_cap: 68.81515267244649 cap_limit: 40
9227 customer_5 ('customer_5', 'customer_1')
6675 customer_5 -24.118482050030877
resNode: customer_1 deliver_cap: 59.50254324431461 cap_limit: 40
9228 customer_5 ('customer_5', 'depot_t')
6675 customer_5 -24.118482050030877
resNode: depot_t deliver_cap: 39.94971796461353 cap_limit: 40
9229 customer_5 ('customer_5', 'customer_2')
6675 customer_5 -24.118482050030877
resNode: customer_2 deliver_cap: 44.25270493799227 cap_limit: 40
9230 customer_5 ('customer_5', 'customer_4')
6675 customer_5 -24.118482050030877
resNode: customer_4 deliver_cap: 68.5693830769344 cap_limit: 40
9231 customer_2 ('customer_2', 'customer_3')
6684 customer_2 -23.01627462467406
resNode: customer_3 deliver_cap: 68.81515267244649 cap_limit: 40
9232 customer_2 ('customer_2', 'customer_1')
6684 customer_2 -23.01627462467406
resNode: customer_1 deliver_cap: 57.48455303800017 cap_limit: 40
9233 customer_2 ('customer_2', 'depot_t')
6684 customer_2 -23.01627462467406
resNode: depot_t deliver_cap: 38.595246455354214 cap_limit: 40
9234 customer_2 ('customer_2', 'customer_4')
6684 customer_2 -23.01627462467406
resNode: customer_4 deliver_cap: 68.5693830769344 cap_limit: 40
9235 customer_2 ('customer_2', 'customer_5')
6684 customer_2 -23.01627462467406
resNode: customer_5 deliver_cap: 49.937147455766905 cap_limit: 40
9236 customer_1 ('customer_1', 'customer_3')
6692 customer_1 -13.043396108485036
resNode: customer_3 deliver_cap: 56.85079736743273 cap_limit: 40
9237 customer_1 ('customer_1', 'depot_t')
6692 customer_1 -13.043396108485036
resNode: depot_t deliver_cap: 33.34593347655581 cap_limit: 40
9238 customer_1 ('customer_1', 'customer_2')
6692 customer_1 -13.043396108485036
resNode: customer_2 deliver_cap: 36.680526824211384 cap_limit: 40
9239 customer_1 ('customer_1', 'customer_4')
6692 customer_1 -13.043396108485036
resNode: customer_4 deliver_cap: 56.419274175328454 cap_limit: 40
9240 customer_1 ('customer_1', 'customer_5')
6692 customer_1 -13.043396108485036
resNode: customer_5 deliver_cap: 46.858780307186166 cap_limit: 40
9241 customer_5 ('customer_5', 'customer_3')
6695 customer_5 -19.629151135831577
resNode: customer_3 deliver_cap: 57.69641364372421 cap_limit: 40
9242 customer_5 ('customer_5', 'customer_1')
6695 customer_5 -19.629151135831577
resNode: customer_1 deliver_cap: 48.3461811547312 cap_limit: 40
9243 customer_5 ('customer_5', 'depot_t')
6695 customer_5 -19.629151135831577
resNode: depot_t deliver_cap: 31.850083513182675 cap_limit: 40
9244 customer_5 ('customer_5', 'customer_2')
6695 customer_5 -19.629151135831577
resNode: customer_2 deliver_cap: 35.78749078481869 cap_limit: 40
9245 customer_5 ('customer_5', 'customer_4')
6695 customer_5 -19.629151135831577
resNode: customer_4 deliver_cap: 57.487509487538944 cap_limit: 40
9246 customer_2 ('customer_2', 'customer_3')
6704 customer_2 -19.569753339065073
resNode: customer_3 deliver_cap: 59.71440385003866 cap_limit: 40
9247 customer_2 ('customer_2', 'customer_1')
6704 customer_2 -19.569753339065073
resNode: customer_1 deliver_cap: 48.346181154731205 cap_limit: 40
9248 customer_2 ('customer_2', 'depot_t')
6704 customer_2 -19.569753339065073
resNode: depot_t deliver_cap: 32.292744393208764 cap_limit: 40
9249 customer_2 ('customer_2', 'customer_4')
6704 customer_2 -19.569753339065073
resNode: customer_4 deliver_cap: 59.505499693853395 cap_limit: 40
9250 customer_2 ('customer_2', 'customer_5')
6704 customer_2 -19.569753339065073
resNode: customer_5 deliver_cap: 43.66809941586102 cap_limit: 40
9251 customer_2 ('customer_2', 'customer_3')
6708 customer_2 -15.84563588061679
resNode: customer_3 deliver_cap: 61.738135350757936 cap_limit: 40
9252 customer_2 ('customer_2', 'customer_1')
6708 customer_2 -15.84563588061679
resNode: customer_1 deliver_cap: 50.012783567088256 cap_limit: 40
9253 customer_2 ('customer_2', 'depot_t')
6708 customer_2 -15.84563588061679
resNode: depot_t deliver_cap: 33.840303776111746 cap_limit: 40
9254 customer_2 ('customer_2', 'customer_4')
6708 customer_2 -15.84563588061679
resNode: customer_4 deliver_cap: 61.529231194572674 cap_limit: 40
9255 customer_2 ('customer_2', 'customer_5')
6708 customer_2 -15.84563588061679
resNode: customer_5 deliver_cap: 45.6918309165803 cap_limit: 40
9256 customer_5 ('customer_5', 'customer_3')
6710 customer_5 -23.93817133723888
resNode: customer_3 deliver_cap: 68.81515267244649 cap_limit: 40
9257 customer_5 ('customer_5', 'customer_1')
6710 customer_5 -23.93817133723888
resNode: customer_1 deliver_cap: 59.50254324431462 cap_limit: 40
9258 customer_5 ('customer_5', 'depot_t')
6710 customer_5 -23.93817133723888
resNode: depot_t deliver_cap: 39.949717964613534 cap_limit: 40
9259 customer_5 ('customer_5', 'customer_2')

9297 customer_4 ('customer_4', 'customer_1')
6725 customer_4 -20.129801014501357
resNode: customer_1 deliver_cap: 55.06540993573832 cap_limit: 40
9298 customer_4 ('customer_4', 'depot_t')
6725 customer_4 -20.129801014501357
resNode: depot_t deliver_cap: 39.75310228820388 cap_limit: 40
9299 customer_4 ('customer_4', 'customer_2')
6725 customer_4 -20.129801014501357
resNode: customer_2 deliver_cap: 44.04380078180702 cap_limit: 40
9300 customer_4 ('customer_4', 'customer_5')
6725 customer_4 -20.129801014501357
resNode: customer_5 deliver_cap: 49.69137786025484 cap_limit: 40
9301 customer_2 ('customer_2', 'customer_3')
6733 customer_2 -17.256802597539036
resNode: customer_3 deliver_cap: 69.30558476932556 cap_limit: 40
9302 customer_2 ('customer_2', 'customer_1')
6733 customer_2 -17.256802597539036
resNode: customer_1 deliver_cap: 56.24480073532042 cap_limit: 40
9303 customer_2 ('customer_2', 'depot_t')
6733 customer_2 -17.256802597539036
resNode: depot_t deliver_cap: 39.62717686089874 cap_limit: 40
9304 customer_2 ('customer_2', 'customer_4')
6733 customer_2 -17.256802597539036
resNode: customer_4 deliver_cap: 69.0966806131403 cap_limit: 40
9305 customer_2 ('customer_2', 'customer_5')
6733 customer_2 -17.256802597539036
resNode: customer_5 deliver_cap: 53.25928033514791 cap_limit: 40
9306 customer_5 ('customer_5', 'customer_3')
6740 customer_5 -24.024270371751243
resNode: customer_3 deliver_cap: 68.5693830769344 cap_limit: 40
9307 customer_5 ('customer_5', 'customer_1')
6740 customer_5 -24.024270371751243
resNode: customer_1 deliver_cap: 59.29363908812934 cap_limit: 40
9308 customer_5 ('customer_5', 'depot_t')
6740 customer_5 -24.024270371751243
resNode: depot_t deliver_cap: 39.75310228820386 cap_limit: 40
9309 customer_5 ('customer_5', 'customer_2')
6740 customer_5 -24.024270371751243
resNode: customer_2 deliver_cap: 44.04380078180701 cap_limit: 40
9310 customer_5 ('customer_5', 'customer_4')
6740 customer_5 -24.024270371751243
resNode: customer_4 deliver_cap: 68.32361348142231 cap_limit: 40
9311 customer_2 ('customer_2', 'customer_3')
6744 customer_2 -22.922062946394433
resNode: customer_3 deliver_cap: 68.5693830769344 cap_limit: 40
9312 customer_2 ('customer_2', 'customer_1')
6744 customer_2 -22.922062946394433
resNode: customer_1 deliver_cap: 57.2756488818149 cap_limit: 40
9313 customer_2 ('customer_2', 'depot_t')
6744 customer_2 -22.922062946394433
resNode: depot_t deliver_cap: 38.39863077894455 cap_limit: 40
9314 customer_2 ('customer_2', 'customer_4')
6744 customer_2 -22.922062946394433
resNode: customer_4 deliver_cap: 68.32361348142231 cap_limit: 40
9315 customer_2 ('customer_2', 'customer_5')
6744 customer_2 -22.922062946394433
resNode: customer_5 deliver_cap: 49.69137786025483 cap_limit: 40
9316 customer_2 ('customer_2', 'customer_3')
6773 customer_2 -14.839194860129274
resNode: customer_3 deliver_cap: 66.15180676032918 cap_limit: 40
9317 customer_2 ('customer_2', 'customer_1')
6773 customer_2 -14.839194860129274
resNode: customer_1 deliver_cap: 51.3239728874384 cap_limit: 40
9318 customer_2 ('customer_2', 'depot_t')
6773 customer_2 -14.839194860129274
resNode: depot_t deliver_cap: 36.96574324146542 cap_limit: 40
9319 customer_2 ('customer_2', 'customer_4')
6773 customer_2 -14.839194860129274
resNode: customer_4 deliver_cap: 65.97976804347073 cap_limit: 40
9320 customer_2 ('customer_2', 'customer_5')
6773 customer_2 -14.839194860129274
resNode: customer_5 deliver_cap: 52.93720310865348 cap_limit: 40
9321 customer_2 ('customer_2', 'customer_3')
6779 customer_2 -22.34932402589991
resNode: customer_3 deliver_cap: 67.09534582324896 cap_limit: 40
9322 customer_2 ('customer_2', 'customer_1')
6779 customer_2 -22.34932402589991
resNode: customer_1 deliver_cap: 54.42460395619852 cap_limit: 40
9323 customer_2 ('customer_2', 'depot_t')
6779 customer_2 -22.34932402589991
resNode: depot_t deliver_cap: 37.936994137428414 cap_limit: 40
9324 customer_2 ('customer_2', 'customer_4')
6779 customer_2 -22.34932402589991
resNode: customer_4 deliver_cap: 66.88644166706369 cap_limit: 40
9325 customer_2 ('customer_2', 'customer_5')
6779 customer_2 -22.34932402589991
resNode: customer_5 deliver_cap: 51.04904138907133 cap_limit: 40
9326 customer_5 ('customer_5', 'customer_3')
6815 customer_5 -25.57848672727299
resNode: customer_3 deliver_cap: 65.96910196390313 cap_limit: 40
9327 customer_5 ('customer_5', 'customer_1')
6815 customer_5 -25.57848672727299
resNode: customer_1 deliver_cap: 57.08340014205277 cap_limit: 40
9328 customer_5 ('customer_5', 'depot_t')
6815 customer_5 -25.57848672727299
resNode: depot_t deliver_cap: 37.67287739777885 cap_limit: 40
9329 customer_5 ('customer_5', 'customer_2')
6815 customer_5 -25.57848672727299
resNode: customer_2 deliver_cap: 41.83356183573043 cap_limit: 40
9330 customer_5 ('customer_5', 'customer_4')
6815 customer_5 -25.57848672727299
resNode: customer_4 deliver_cap: 65.72333236839106 cap_limit: 40
9331 customer_2 ('customer_2', 'customer_3')
6823 customer_2 -19.217555905882868
resNode: customer_3 deliver_cap: 69.30558476932556 cap_limit: 40
9332 customer_2 ('customer_2', 'customer_1')
6823 customer_2 -19.217555905882868
resNode: customer_1 deliver_cap: 56.24480073532042 cap_limit: 40
9333 customer_2 ('customer_2', 'depot_t')
6823 customer_2 -19.217555905882868
resNode: depot_t deliver_cap: 39.62717686089874 cap_limit: 40
9334 customer_2 ('customer_2', 'customer_4')
6823 customer_2 -19.217555905882868
resNode: customer_4 deliver_cap: 69.0966806131403 cap_limit: 40
9335 customer_2 ('customer_2', 'customer_5')
6823 customer_2 -19.217555905882868
resNode: customer_5 deliver_cap: 53.25928033514791 cap_limit: 40
9336 customer_2 ('customer_2', 'customer_3')
6829 customer_2 -23.712689753874194
resNode: customer_3 deliver_cap: 65.96910196390313 cap_limit: 40
9337 customer_2 ('customer_2', 'customer_1')
6829 customer_2 -23.712689753874194
resNode: customer_1 deliver_cap: 55.06540993573832 cap_limit: 40
9338 customer_2 ('customer_2', 'depot_t')
6829 customer_2 -23.712689753874194
resNode: depot_t deliver_cap: 36.318405888519536 cap_limit: 40
9339 customer_2 ('customer_2', 'customer_4')
6829 customer_2 -23.712689753874194
resNode: customer_4 deliver_cap: 65.72333236839106 cap_limit: 40
9340 customer_2 ('customer_2', 'customer_5')
6829 customer_2 -23.712689753874194
resNode: customer_5 deliver_cap: 47.09109674722356 cap_limit: 40
9341 customer_2 ('customer_2', 'customer_3')
6868 customer_2 -14.342567352580053
resNode: customer_3 deliver_cap: 60.073383958861875 cap_limit: 40
9342 customer_2 ('customer_2', 'customer_1')
6868 customer_2 -14.342567352580053
resNode: customer_1 deliver_cap: 46.54806925771409 cap_limit: 40
9343 customer_2 ('customer_2', 'depot_t')
6868 customer_2 -14.342567352580053
resNode: depot_t deliver_cap: 32.62401266898876 cap_limit: 40
9344 customer_2 ('customer_2', 'customer_4')
6868 customer_2 -14.342567352580053
resNode: customer_4 deliver_cap: 59.901345242003416 cap_limit: 40
9345 customer_2 ('customer_2', 'customer_5')
6868 customer_2 -14.342567352580053
resNode: customer_5 deliver_cap: 46.858780307186166 cap_limit: 40
9346 customer_2 ('customer_2', 'customer_3')
6879 customer_2 -20.22454755367195
resNode: customer_3 deliver_cap: 59.71440385003866 cap_limit: 40
9347 customer_2 ('customer_2', 'customer_1')
6879 customer_2 -20.22454755367195
resNode: customer_1 deliver_cap: 48.346181154731205 cap_limit: 40
9348 customer_2 ('customer_2', 'depot_t')
6879 customer_2 -20.22454755367195
resNode: depot_t deliver_cap: 32.292744393208764 cap_limit: 40
9349 customer_2 ('customer_2', 'customer_4')
6879 customer_2 -20.22454755367195
resNode: customer_4 deliver_cap: 59.505499693853395 cap_limit: 40
9350 customer_2 ('customer_2', 'customer_5')
6879 customer_2 -20.22454755367195
resNode: customer_5 deliver_cap: 43.66809941586102 cap_limit: 40
9351 customer_5 ('customer_5', 'customer_3')
6895 customer_5 -28.650251083098553
resNode: customer_3 deliver_cap: 68.80839820844079 cap_limit: 40
9352 customer_5 ('customer_5', 'customer_1')
6895 customer_5 -28.650251083098553
resNode: customer_1 deliver_cap: 59.49680194990979 cap_limit: 40
9353 customer_5 ('customer_5', 'depot_t')
6895 customer_5 -28.650251083098553
resNode: depot_t deliver_cap: 39.94431439340898 cap_limit: 40
9354 customer_5 ('customer_5', 'customer_2')
6895 customer_5 -28.650251083098553
resNode: customer_2 deliver_cap: 44.24696364358744 cap_limit: 40
9355 customer_5 ('customer_5', 'customer_4')
6895 customer_5 -28.650251083098553
resNode: customer_4 deliver_cap: 68.56262861292873 cap_limit: 40
9356 customer_1 ('customer_1', 'customer_3')
6917 customer_1 -12.873333091712007
resNode: customer_3 deliver_cap: 56.85079736743273 cap_limit: 40
9357 customer_1 ('customer_1', 'depot_t')
6917 customer_1 -12.873333091712007
resNode: depot_t deliver_cap: 33.34593347655581 cap_limit: 40
9358 customer_1 ('customer_1', 'customer_2')
6917 customer_1 -12.873333091712007
resNode: customer_2 deliver_cap: 36.680526824211384 cap_limit: 40
9359 customer_1 ('customer_1', 'customer_4')
6917 customer_1 -12.873333091712007
resNode: customer_4 deliver_cap: 56.419274175328454 cap_limit: 40
9360 customer_1 ('customer_1', 'customer_5')
6917 customer_1 -12.873333091712007
resNode: customer_5 deliver_cap: 46.858780307186166 cap_limit: 40
9361 customer_5 ('customer_5', 'customer_3')
6920 customer_5 -19.45908811905855
resNode: customer_3 deliver_cap: 57.69641364372421 cap_limit: 40
9362 customer_5 ('customer_5', 'customer_1')
6920 customer_5 -19.45908811905855
resNode: customer_1 deliver_cap: 48.3461811547312 cap_limit: 40
9363 customer_5 ('customer_5', 'depot_t')
6920 customer_5 -19.45908811905855
resNode: depot_t deliver_cap: 31.850083513182675 cap_limit: 40
9364 customer_5 ('customer_5', 'customer_2')
6920 customer_5 -19.45908811905855
resNode: customer_2 deliver_cap: 35.78749078481869 cap_limit: 40
9365 customer_5 ('customer_5', 'customer_4')
6920 customer_5 -19.45908811905855
resNode: customer_4 deliver_cap: 57.487509487538944 cap_limit: 40
9366 customer_2 ('customer_2', 'customer_3')
6929 customer_2 -19.399690322292045
resNode: customer_3 deliver_cap: 59.71440385003866 cap_limit: 40
9367 customer_2 ('customer_2', 'customer_1')
6929 customer_2 -19.399690322292045
resNode: customer_1 deliver_cap: 48.346181154731205 cap_limit: 40
9368 customer_2 ('customer_2', 'depot_t')
6929 customer_2 -19.399690322292045
resNode: depot_t deliver_cap: 32.292744393208764 cap_limit: 40
9369 customer_2 ('customer_2', 'customer_4')
6929 customer_2 -19.399690322292045
resNode: customer_4 deliver_cap: 59.505499693853395 cap_limit: 40
9370 customer_2 ('customer_2', 'customer_5')
6929 customer_2 -19.399690322292045
resNode: customer_5 deliver_cap: 43.66809941586102 cap_limit: 40
9371 customer_2 ('customer_2', 'customer_3')
6953 customer_2 -15.930198379999409
resNode: customer_3 deliver_cap: 59.714403850038664 cap_limit: 40
9372 customer_2 ('customer_2', 'customer_1')
6953 customer_2 -15.930198379999409
resNode: customer_1 deliver_cap: 48.34618115473121 cap_limit: 40
9373 customer_2 ('customer_2', 'depot_t')
6953 customer_2 -15.930198379999409
resNode: depot_t deliver_cap: 32.29274439320877 cap_limit: 40
9374 customer_2 ('customer_2', 'customer_4')
6953 customer_2 -15.930198379999409
resNode: customer_4 deliver_cap: 59.505499693853395 cap_limit: 40
9375 customer_2 ('customer_2', 'customer_5')
6953 customer_2 -15.930198379999409
resNode: customer_5 deliver_cap: 43.66809941586103 cap_limit: 40
9376 customer_5 ('customer_5', 'customer_3')
6955 customer_5 -24.525964926199048
resNode: customer_3 deliver_cap: 68.80839820844082 cap_limit: 40
9377 customer_5 ('customer_5', 'customer_1')
6955 customer_5 -24.525964926199048
resNode: customer_1 deliver_cap: 59.4968019499098 cap_limit: 40
9378 customer_5 ('customer_5', 'depot_t')
6955 customer_5 -24.525964926199048
resNode: depot_t deliver_cap: 39.944314393408995 cap_limit: 40
9379 customer_5 ('customer_5', 'customer_2')
6955 customer_5 -24.525964926199048
resNode: customer_2 deliver_cap: 44.246963643587456 cap_limit: 40
9380 customer_5 ('customer_5', 'customer_4')
6955 customer_5 -24.525964926199048
resNode: customer_4 deliver_cap: 68.56262861292875 cap_limit: 40
9381 customer_1 ('customer_1', 'customer_3')
6957 customer_1 -15.339965411078795
resNode: customer_3 deliver_cap: 55.80126298901757 cap_limit: 40
9382 customer_1 ('customer_1', 'depot_t')
6957 customer_1 -15.339965411078795
resNode: depot_t deliver_cap: 33.23124144304593 cap_limit: 40
9383 customer_1 ('customer_1', 'customer_2')
6957 customer_1 -15.339965411078795
resNode: customer_2 deliver_cap: 35.787490784818694 cap_limit: 40
9384 customer_1 ('customer_1', 'customer_4')
6957 customer_1 -15.339965411078795
resNode: customer_4 deliver_cap: 55.277270541462364 cap_limit: 40
9385 customer_1 ('customer_1', 'customer_5')
6957 customer_1 -15.339965411078795
resNode: customer_5 deliver_cap: 43.66809941586103 cap_limit: 40
9386 customer_5 ('customer_5', 'customer_3')
6960 customer_5 -18.343490223691326
resNode: customer_3 deliver_cap: 52.31125358084274 cap_limit: 40
9387 customer_5 ('customer_5', 'customer_1')
6960 customer_5 -18.343490223691326
resNode: customer_1 deliver_cap: 45.47422901645144 cap_limit: 40
9388 customer_5 ('customer_5', 'depot_t')
6960 customer_5 -18.343490223691326
resNode: depot_t deliver_cap: 26.74659869133054 cap_limit: 40
9389 customer_5 ('customer_5', 'customer_2')
6960 customer_5 -18.343490223691326
resNode: customer_2 deliver_cap: 30.224390710129104 cap_limit: 40
9390 customer_5 ('customer_5', 'customer_4')
6960 customer_5 -18.343490223691326
resNode: customer_4 deliver_cap: 52.06548398533066 cap_limit: 40
9391 customer_5 ('customer_5', 'customer_3')
7015 customer_5 -19.488580696065952
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9392 customer_5 ('customer_5', 'customer_1')
7015 customer_5 -19.488580696065952
resNode: customer_1 deliver_cap: 59.42593662300047 cap_limit: 40
9393 customer_5 ('customer_5', 'depot_t')
7015 customer_5 -19.488580696065952
resNode: depot_t deliver_cap: 37.39208742530091 cap_limit: 40
9394 customer_5 ('customer_5', 'customer_2')
7015 customer_5 -19.488580696065952
resNode: customer_2 deliver_cap: 41.4849503802683 cap_limit: 40
9395 customer_5 ('customer_5', 'customer_4')
7015 customer_5 -19.488580696065952
resNode: customer_4 deliver_cap: 66.69117679497003 cap_limit: 40
9396 customer_2 ('customer_2', 'customer_3')
7049 customer_2 -17.559292870670625
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9397 customer_2 ('customer_2', 'customer_1')
7049 customer_2 -17.559292870670625
resNode: customer_1 deliver_cap: 57.051830497924634 cap_limit: 40
9398 customer_2 ('customer_2', 'depot_t')
7049 customer_2 -17.559292870670625
resNode: depot_t deliver_cap: 35.78365250805547 cap_limit: 40
9399 customer_2 ('customer_2', 'customer_4')
7049 customer_2 -17.559292870670625
resNode: customer_4 deliver_cap: 66.69117679497003 cap_limit: 40
9400 customer_2 ('customer_2', 'customer_5')
7049 customer_2 -17.559292870670625
resNode: customer_5 deliver_cap: 45.264105830627415 cap_limit: 40
9401 customer_5 ('customer_5', 'customer_3')
7080 customer_5 -23.786764651754787
resNode: customer_3 deliver_cap: 65.96910196390313 cap_limit: 40
9402 customer_5 ('customer_5', 'customer_1')
7080 customer_5 -23.786764651754787
resNode: customer_1 deliver_cap: 57.08340014205277 cap_limit: 40
9403 customer_5 ('customer_5', 'depot_t')
7080 customer_5 -23.786764651754787
resNode: depot_t deliver_cap: 37.67287739777885 cap_limit: 40
9404 customer_5 ('customer_5', 'customer_2')
7080 customer_5 -23.786764651754787
resNode: customer_2 deliver_cap: 41.83356183573043 cap_limit: 40
9405 customer_5 ('customer_5', 'customer_4')
7080 customer_5 -23.786764651754787
resNode: customer_4 deliver_cap: 65.72333236839106 cap_limit: 40
9406 customer_2 ('customer_2', 'customer_3')
7094 customer_2 -23.582841965909076
resNode: customer_3 deliver_cap: 68.34320808897895 cap_limit: 40
9407 customer_2 ('customer_2', 'customer_1')
7094 customer_2 -23.582841965909076
resNode: customer_1 deliver_cap: 57.083400142052774 cap_limit: 40
9408 customer_2 ('customer_2', 'depot_t')
7094 customer_2 -23.582841965909076
resNode: depot_t deliver_cap: 38.21769078858019 cap_limit: 40
9409 customer_2 ('customer_2', 'customer_4')
7094 customer_2 -23.582841965909076
resNode: customer_4 deliver_cap: 68.09743849346688 cap_limit: 40
9410 customer_2 ('customer_2', 'customer_5')
7094 customer_2 -23.582841965909076
resNode: customer_5 deliver_cap: 49.46520287229938 cap_limit: 40
9411 customer_2 ('customer_2', 'customer_3')
7118 customer_2 -11.58435499584817
resNode: customer_3 deliver_cap: 61.567947654360474 cap_limit: 40
9412 customer_2 ('customer_2', 'customer_1')
7118 customer_2 -11.58435499584817
resNode: customer_1 deliver_cap: 47.72236930417726 cap_limit: 40
9413 customer_2 ('customer_2', 'depot_t')
7118 customer_2 -11.58435499584817
resNode: depot_t deliver_cap: 33.69155816577348 cap_limit: 40
9414 customer_2 ('customer_2', 'customer_4')
7118 customer_2 -11.58435499584817
resNode: customer_4 deliver_cap: 61.395908937502014 cap_limit: 40
9415 customer_2 ('customer_2', 'customer_5')
7118 customer_2 -11.58435499584817
resNode: customer_5 deliver_cap: 48.353344002684764 cap_limit: 40
9416 customer_2 ('customer_2', 'customer_3')
7124 customer_2 -17.86666475823433
resNode: customer_3 deliver_cap: 61.52923119457267 cap_limit: 40
9417 customer_2 ('customer_2', 'customer_1')
7124 customer_2 -17.86666475823433
resNode: customer_1 deliver_cap: 49.840744850229804 cap_limit: 40
9418 customer_2 ('customer_2', 'depot_t')
7124 customer_2 -17.86666475823433
resNode: depot_t deliver_cap: 33.68055353902889 cap_limit: 40
9419 customer_2 ('customer_2', 'customer_4')
7124 customer_2 -17.86666475823433
resNode: customer_4 deliver_cap: 61.320327038387404 cap_limit: 40
9420 customer_2 ('customer_2', 'customer_5')
7124 customer_2 -17.86666475823433
resNode: customer_5 deliver_cap: 45.48292676039503 cap_limit: 40
9421 customer_2 ('customer_2', 'customer_3')
7173 customer_2 -13.402252567788763
resNode: customer_3 deliver_cap: 61.529231194572674 cap_limit: 40
9422 customer_2 ('customer_2', 'customer_1')
7173 customer_2 -13.402252567788763
resNode: customer_1 deliver_cap: 49.84074485022981 cap_limit: 40
9423 customer_2 ('customer_2', 'depot_t')
7173 customer_2 -13.402252567788763
resNode: depot_t deliver_cap: 33.6805535390289 cap_limit: 40
9424 customer_2 ('customer_2', 'customer_4')
7173 customer_2 -13.402252567788763
resNode: customer_4 deliver_cap: 61.320327038387404 cap_limit: 40
9425 customer_2 ('customer_2', 'customer_5')
7173 customer_2 -13.402252567788763
resNode: customer_5 deliver_cap: 45.48292676039504 cap_limit: 40
9426 customer_2 ('customer_2', 'customer_3')
7184 customer_2 -16.182014303702253
resNode: customer_3 deliver_cap: 56.82045069948799 cap_limit: 40
9427 customer_2 ('customer_2', 'customer_1')
7184 customer_2 -16.182014303702253
resNode: customer_1 deliver_cap: 47.28905636098545 cap_limit: 40
9428 customer_2 ('customer_2', 'depot_t')
7184 customer_2 -16.182014303702253
resNode: depot_t deliver_cap: 28.999484876987424 cap_limit: 40
9429 customer_2 ('customer_2', 'customer_4')
7184 customer_2 -16.182014303702253
resNode: customer_4 deliver_cap: 56.57468110397591 cap_limit: 40
9430 customer_2 ('customer_2', 'customer_5')
7184 customer_2 -16.182014303702253
resNode: customer_5 deliver_cap: 37.942445482808424 cap_limit: 40
9431 customer_5 ('customer_5', 'customer_3')
7215 customer_5 -21.272563296082673
resNode: customer_3 deliver_cap: 68.56938307693441 cap_limit: 40
9432 customer_5 ('customer_5', 'customer_1')
7215 customer_5 -21.272563296082673
resNode: customer_1 deliver_cap: 59.29363908812936 cap_limit: 40
9433 customer_5 ('customer_5', 'depot_t')
7215 customer_5 -21.272563296082673
resNode: depot_t deliver_cap: 39.75310228820387 cap_limit: 40
9434 customer_5 ('customer_5', 'customer_2')
7215 customer_5 -21.272563296082673
resNode: customer_2 deliver_cap: 44.043800781807015 cap_limit: 40

7384 customer_2 -15.930198379999403
resNode: customer_3 deliver_cap: 59.71440385003866 cap_limit: 40
9492 customer_2 ('customer_2', 'customer_1')
7384 customer_2 -15.930198379999403
resNode: customer_1 deliver_cap: 48.346181154731205 cap_limit: 40
9493 customer_2 ('customer_2', 'depot_t')
7384 customer_2 -15.930198379999403
resNode: depot_t deliver_cap: 32.292744393208764 cap_limit: 40
9494 customer_2 ('customer_2', 'customer_4')
7384 customer_2 -15.930198379999403
resNode: customer_4 deliver_cap: 59.505499693853395 cap_limit: 40
9495 customer_2 ('customer_2', 'customer_5')
7384 customer_2 -15.930198379999403
resNode: customer_5 deliver_cap: 43.66809941586102 cap_limit: 40
9496 customer_2 ('customer_2', 'customer_3')
7408 customer_2 -12.460706437706767
resNode: customer_3 deliver_cap: 59.714403850038664 cap_limit: 40
9497 customer_2 ('customer_2', 'customer_1')
7408 customer_2 -12.460706437706767
resNode: customer_1 deliver_cap: 48.34618115473121 cap_limit: 40
9498 customer_2 ('customer_2', 'depot_t')
7408 customer_2 -12.460706437706767
resNode: depot_t deliver_cap: 32.29274439320877 cap_limit: 40
9499 customer_2 ('customer_2', 'customer_4')
7408 customer_2 -12.460706437706767
resNode: customer_4 deliver_cap: 59.505499693853395 cap_limit: 40
9500 customer_2 ('customer_2', 'customer_5')
7408 customer_2 -12.460706437706767
resNode: customer_5 deliver_cap: 43.66809941586103 cap_limit: 40
9501 customer_5 ('customer_5', 'customer_3')
7410 customer_5 -21.056472983906406
resNode: customer_3 deliver_cap: 68.80839820844082 cap_limit: 40
9502 customer_5 ('customer_5', 'customer_1')
7410 customer_5 -21.056472983906406
resNode: customer_1 deliver_cap: 59.4968019499098 cap_limit: 40
9503 customer_5 ('customer_5', 'depot_t')
7410 customer_5 -21.056472983906406
resNode: depot_t deliver_cap: 39.944314393408995 cap_limit: 40
9504 customer_5 ('customer_5', 'customer_2')
7410 customer_5 -21.056472983906406
resNode: customer_2 deliver_cap: 44.246963643587456 cap_limit: 40
9505 customer_5 ('customer_5', 'customer_4')
7410 customer_5 -21.056472983906406
resNode: customer_4 deliver_cap: 68.56262861292875 cap_limit: 40
9506 customer_1 ('customer_1', 'customer_3')
7412 customer_1 -11.870473468786154
resNode: customer_3 deliver_cap: 55.80126298901757 cap_limit: 40
9507 customer_1 ('customer_1', 'depot_t')
7412 customer_1 -11.870473468786154
resNode: depot_t deliver_cap: 33.23124144304593 cap_limit: 40
9508 customer_1 ('customer_1', 'customer_2')
7412 customer_1 -11.870473468786154
resNode: customer_2 deliver_cap: 35.787490784818694 cap_limit: 40
9509 customer_1 ('customer_1', 'customer_4')
7412 customer_1 -11.870473468786154
resNode: customer_4 deliver_cap: 55.277270541462364 cap_limit: 40
9510 customer_1 ('customer_1', 'customer_5')
7412 customer_1 -11.870473468786154
resNode: customer_5 deliver_cap: 43.66809941586103 cap_limit: 40
9511 customer_5 ('customer_5', 'customer_3')
7415 customer_5 -14.873998281398682
resNode: customer_3 deliver_cap: 52.31125358084274 cap_limit: 40
9512 customer_5 ('customer_5', 'customer_1')
7415 customer_5 -14.873998281398682
resNode: customer_1 deliver_cap: 45.47422901645144 cap_limit: 40
9513 customer_5 ('customer_5', 'depot_t')
7415 customer_5 -14.873998281398682
resNode: depot_t deliver_cap: 26.74659869133054 cap_limit: 40
9514 customer_5 ('customer_5', 'customer_2')
7415 customer_5 -14.873998281398682
resNode: customer_2 deliver_cap: 30.224390710129104 cap_limit: 40
9515 customer_5 ('customer_5', 'customer_4')
7415 customer_5 -14.873998281398682
resNode: customer_4 deliver_cap: 52.06548398533066 cap_limit: 40
9516 customer_2 ('customer_2', 'customer_3')
7439 customer_2 -19.17350242252255
resNode: customer_3 deliver_cap: 68.34320808897894 cap_limit: 40
9517 customer_2 ('customer_2', 'customer_1')
7439 customer_2 -19.17350242252255
resNode: customer_1 deliver_cap: 57.08340014205277 cap_limit: 40
9518 customer_2 ('customer_2', 'depot_t')
7439 customer_2 -19.17350242252255
resNode: depot_t deliver_cap: 38.217690788580185 cap_limit: 40
9519 customer_2 ('customer_2', 'customer_4')
7439 customer_2 -19.17350242252255
resNode: customer_4 deliver_cap: 68.09743849346687 cap_limit: 40
9520 customer_2 ('customer_2', 'customer_5')
7439 customer_2 -19.17350242252255
resNode: customer_5 deliver_cap: 49.46520287229937 cap_limit: 40
9521 customer_5 ('customer_5', 'customer_3')
7455 customer_5 -21.71126719851328
resNode: customer_3 deliver_cap: 68.8083982084408 cap_limit: 40
9522 customer_5 ('customer_5', 'customer_1')
7455 customer_5 -21.71126719851328
resNode: customer_1 deliver_cap: 59.49680194990979 cap_limit: 40
9523 customer_5 ('customer_5', 'depot_t')
7455 customer_5 -21.71126719851328
resNode: depot_t deliver_cap: 39.94431439340899 cap_limit: 40
9524 customer_5 ('customer_5', 'customer_2')
7455 customer_5 -21.71126719851328
resNode: customer_2 deliver_cap: 44.24696364358745 cap_limit: 40
9525 customer_5 ('customer_5', 'customer_4')
7455 customer_5 -21.71126719851328
resNode: customer_4 deliver_cap: 68.56262861292873 cap_limit: 40
9526 customer_2 ('customer_2', 'customer_3')
7468 customer_2 -12.290643420933739
resNode: customer_3 deliver_cap: 59.714403850038664 cap_limit: 40
9527 customer_2 ('customer_2', 'customer_1')
7468 customer_2 -12.290643420933739
resNode: customer_1 deliver_cap: 48.34618115473121 cap_limit: 40
9528 customer_2 ('customer_2', 'depot_t')
7468 customer_2 -12.290643420933739
resNode: depot_t deliver_cap: 32.29274439320877 cap_limit: 40
9529 customer_2 ('customer_2', 'customer_4')
7468 customer_2 -12.290643420933739
resNode: customer_4 deliver_cap: 59.505499693853395 cap_limit: 40
9530 customer_2 ('customer_2', 'customer_5')
7468 customer_2 -12.290643420933739
resNode: customer_5 deliver_cap: 43.66809941586103 cap_limit: 40
9531 customer_5 ('customer_5', 'customer_3')
7470 customer_5 -20.88640996713338
resNode: customer_3 deliver_cap: 68.80839820844082 cap_limit: 40
9532 customer_5 ('customer_5', 'customer_1')
7470 customer_5 -20.88640996713338
resNode: customer_1 deliver_cap: 59.4968019499098 cap_limit: 40
9533 customer_5 ('customer_5', 'depot_t')
7470 customer_5 -20.88640996713338
resNode: depot_t deliver_cap: 39.944314393408995 cap_limit: 40
9534 customer_5 ('customer_5', 'customer_2')
7470 customer_5 -20.88640996713338
resNode: customer_2 deliver_cap: 44.246963643587456 cap_limit: 40
9535 customer_5 ('customer_5', 'customer_4')
7470 customer_5 -20.88640996713338
resNode: customer_4 deliver_cap: 68.56262861292875 cap_limit: 40
9536 customer_2 ('customer_2', 'customer_3')
7479 customer_2 -14.670075595552962
resNode: customer_3 deliver_cap: 54.68535970591857 cap_limit: 40
9537 customer_2 ('customer_2', 'customer_1')
7479 customer_2 -14.670075595552962
resNode: customer_1 deliver_cap: 45.47422901645144 cap_limit: 40
9538 customer_2 ('customer_2', 'depot_t')
7479 customer_2 -14.670075595552962
resNode: depot_t deliver_cap: 27.291412082131885 cap_limit: 40
9539 customer_2 ('customer_2', 'customer_4')
7479 customer_2 -14.670075595552962
resNode: customer_4 deliver_cap: 54.439590110406485 cap_limit: 40
9540 customer_2 ('customer_2', 'customer_5')
7479 customer_2 -14.670075595552962
resNode: customer_5 deliver_cap: 35.807354489239 cap_limit: 40
9541 customer_5 ('customer_5', 'customer_3')
7490 customer_5 -16.369799594119403
resNode: customer_3 deliver_cap: 66.58556366690927 cap_limit: 40
9542 customer_5 ('customer_5', 'customer_1')
7490 customer_5 -16.369799594119403
resNode: customer_1 deliver_cap: 57.60739258960798 cap_limit: 40
9543 customer_5 ('customer_5', 'depot_t')
7490 customer_5 -16.369799594119403
resNode: depot_t deliver_cap: 38.166046760183754 cap_limit: 40
9544 customer_5 ('customer_5', 'customer_2')
7490 customer_5 -16.369799594119403
resNode: customer_2 deliver_cap: 42.35755428328564 cap_limit: 40
9545 customer_5 ('customer_5', 'customer_4')
7490 customer_5 -16.369799594119403
resNode: customer_4 deliver_cap: 66.3397940713972 cap_limit: 40
9546 customer_2 ('customer_2', 'customer_3')
7494 customer_2 -16.33593992504671
resNode: customer_3 deliver_cap: 68.95966979198508 cap_limit: 40
9547 customer_2 ('customer_2', 'customer_1')
7494 customer_2 -16.33593992504671
resNode: customer_1 deliver_cap: 57.607392589607976 cap_limit: 40
9548 customer_2 ('customer_2', 'depot_t')
7494 customer_2 -16.33593992504671
resNode: depot_t deliver_cap: 38.71086015098509 cap_limit: 40
9549 customer_2 ('customer_2', 'customer_4')
7494 customer_2 -16.33593992504671
resNode: customer_4 deliver_cap: 68.713900196473 cap_limit: 40
9550 customer_2 ('customer_2', 'customer_5')
7494 customer_2 -16.33593992504671
resNode: customer_5 deliver_cap: 50.0816645753055 cap_limit: 40
9551 customer_2 ('customer_2', 'customer_3')
7503 customer_2 -8.804612021393606
resNode: customer_3 deliver_cap: 61.738135350757936 cap_limit: 40
9552 customer_2 ('customer_2', 'customer_1')
7503 customer_2 -8.804612021393606
resNode: customer_1 deliver_cap: 50.012783567088256 cap_limit: 40
9553 customer_2 ('customer_2', 'depot_t')
7503 customer_2 -8.804612021393606
resNode: depot_t deliver_cap: 33.840303776111746 cap_limit: 40
9554 customer_2 ('customer_2', 'customer_4')
7503 customer_2 -8.804612021393606
resNode: customer_4 deliver_cap: 61.529231194572674 cap_limit: 40
9555 customer_2 ('customer_2', 'customer_5')
7503 customer_2 -8.804612021393606
resNode: customer_5 deliver_cap: 45.6918309165803 cap_limit: 40
9556 customer_2 ('customer_2', 'customer_3')
7514 customer_2 -11.630455556465611
resNode: customer_3 deliver_cap: 57.066220295000065 cap_limit: 40
9557 customer_2 ('customer_2', 'customer_1')
7514 customer_2 -11.630455556465611
resNode: customer_1 deliver_cap: 47.49796051717072 cap_limit: 40
9558 customer_2 ('customer_2', 'depot_t')
7514 customer_2 -11.630455556465611
resNode: depot_t deliver_cap: 29.196100553397084 cap_limit: 40
9559 customer_2 ('customer_2', 'customer_4')
7514 customer_2 -11.630455556465611
resNode: customer_4 deliver_cap: 56.82045069948799 cap_limit: 40
9560 customer_2 ('customer_2', 'customer_5')
7514 customer_2 -11.630455556465611
resNode: customer_5 deliver_cap: 38.188215078320496 cap_limit: 40
9561 customer_5 ('customer_5', 'customer_3')
7530 customer_5 -14.334366686909966
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9562 customer_5 ('customer_5', 'customer_1')
7530 customer_5 -14.334366686909966
resNode: customer_1 deliver_cap: 59.42593662300047 cap_limit: 40
9563 customer_5 ('customer_5', 'depot_t')
7530 customer_5 -14.334366686909966
resNode: depot_t deliver_cap: 37.39208742530091 cap_limit: 40
9564 customer_5 ('customer_5', 'customer_2')
7530 customer_5 -14.334366686909966
resNode: customer_2 deliver_cap: 41.4849503802683 cap_limit: 40
9565 customer_5 ('customer_5', 'customer_4')
7530 customer_5 -14.334366686909966
resNode: customer_4 deliver_cap: 66.69117679497003 cap_limit: 40
9566 customer_2 ('customer_2', 'customer_3')
7534 customer_2 -13.168668409556624
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9567 customer_2 ('customer_2', 'customer_1')
7534 customer_2 -13.168668409556624
resNode: customer_1 deliver_cap: 57.051830497924634 cap_limit: 40
9568 customer_2 ('customer_2', 'depot_t')
7534 customer_2 -13.168668409556624
resNode: depot_t deliver_cap: 35.78365250805547 cap_limit: 40
9569 customer_2 ('customer_2', 'customer_4')
7534 customer_2 -13.168668409556624
resNode: customer_4 deliver_cap: 66.69117679497003 cap_limit: 40
9570 customer_2 ('customer_2', 'customer_5')
7534 customer_2 -13.168668409556624
resNode: customer_5 deliver_cap: 45.264105830627415 cap_limit: 40
9571 customer_5 ('customer_5', 'customer_3')
7545 customer_5 -15.960929254723808
resNode: customer_3 deliver_cap: 61.23551343800867 cap_limit: 40
9572 customer_5 ('customer_5', 'customer_1')
7545 customer_5 -15.960929254723808
resNode: customer_1 deliver_cap: 54.436111934478504 cap_limit: 40
9573 customer_5 ('customer_5', 'depot_t')
7545 customer_5 -15.960929254723808
resNode: depot_t deliver_cap: 32.65175397120505 cap_limit: 40
9574 customer_5 ('customer_5', 'customer_2')
7545 customer_5 -15.960929254723808
resNode: customer_2 deliver_cap: 36.49512569174635 cap_limit: 40
9575 customer_5 ('customer_5', 'customer_4')
7545 customer_5 -15.960929254723808
resNode: customer_4 deliver_cap: 60.95287840316978 cap_limit: 40
9576 customer_2 ('customer_2', 'customer_3')
7548 customer_2 -11.906642049370804
resNode: customer_3 deliver_cap: 67.93442656217412 cap_limit: 40
9577 customer_2 ('customer_2', 'customer_1')
7548 customer_2 -11.906642049370804
resNode: customer_1 deliver_cap: 55.115611623548645 cap_limit: 40
9578 customer_2 ('customer_2', 'depot_t')
7548 customer_2 -11.906642049370804
resNode: depot_t deliver_cap: 38.578644114253535 cap_limit: 40
9579 customer_2 ('customer_2', 'customer_4')
7548 customer_2 -11.906642049370804
resNode: customer_4 deliver_cap: 67.72552240598885 cap_limit: 40
9580 customer_2 ('customer_2', 'customer_5')
7548 customer_2 -11.906642049370804
resNode: customer_5 deliver_cap: 51.88812212799649 cap_limit: 40
9581 customer_5 ('customer_5', 'customer_3')
7555 customer_5 -18.20483700598611
resNode: customer_3 deliver_cap: 66.58556366690927 cap_limit: 40
9582 customer_5 ('customer_5', 'customer_1')
7555 customer_5 -18.20483700598611
resNode: customer_1 deliver_cap: 57.60739258960798 cap_limit: 40
9583 customer_5 ('customer_5', 'depot_t')
7555 customer_5 -18.20483700598611
resNode: depot_t deliver_cap: 38.166046760183754 cap_limit: 40
9584 customer_5 ('customer_5', 'customer_2')
7555 customer_5 -18.20483700598611
resNode: customer_2 deliver_cap: 42.35755428328564 cap_limit: 40
9585 customer_5 ('customer_5', 'customer_4')
7555 customer_5 -18.20483700598611
resNode: customer_4 deliver_cap: 66.3397940713972 cap_limit: 40
9586 customer_2 ('customer_2', 'customer_3')
7564 customer_2 -17.102629580629298
resNode: customer_3 deliver_cap: 66.58556366690925 cap_limit: 40
9587 customer_2 ('customer_2', 'customer_1')
7564 customer_2 -17.102629580629298
resNode: customer_1 deliver_cap: 55.58940238329353 cap_limit: 40
9588 customer_2 ('customer_2', 'depot_t')
7564 customer_2 -17.102629580629298
resNode: depot_t deliver_cap: 36.811575250924434 cap_limit: 40
9589 customer_2 ('customer_2', 'customer_4')
7564 customer_2 -17.102629580629298
resNode: customer_4 deliver_cap: 66.33979407139718 cap_limit: 40
9590 customer_2 ('customer_2', 'customer_5')
7564 customer_2 -17.102629580629298
resNode: customer_5 deliver_cap: 47.70755845022968 cap_limit: 40
9591 customer_2 ('customer_2', 'customer_3')
7568 customer_2 -11.38122369017122
resNode: customer_3 deliver_cap: 61.738135350757936 cap_limit: 40
9592 customer_2 ('customer_2', 'customer_1')
7568 customer_2 -11.38122369017122
resNode: customer_1 deliver_cap: 50.012783567088256 cap_limit: 40
9593 customer_2 ('customer_2', 'depot_t')
7568 customer_2 -11.38122369017122
resNode: depot_t deliver_cap: 33.840303776111746 cap_limit: 40
9594 customer_2 ('customer_2', 'customer_4')
7568 customer_2 -11.38122369017122
resNode: customer_4 deliver_cap: 61.529231194572674 cap_limit: 40
9595 customer_2 ('customer_2', 'customer_5')
7568 customer_2 -11.38122369017122
resNode: customer_5 deliver_cap: 45.6918309165803 cap_limit: 40
9596 customer_5 ('customer_5', 'customer_3')
7570 customer_5 -19.473759146793313
resNode: customer_3 deliver_cap: 68.81515267244649 cap_limit: 40
9597 customer_5 ('customer_5', 'customer_1')
7570 customer_5 -19.473759146793313
resNode: customer_1 deliver_cap: 59.50254324431462 cap_limit: 40
9598 customer_5 ('customer_5', 'depot_t')
7570 customer_5 -19.473759146793313
resNode: depot_t deliver_cap: 39.949717964613534 cap_limit: 40
9599 customer_5 ('customer_5', 'customer_2')
7570 customer_5 -19.473759146793313
resNode: customer_2 deliver_cap: 44.25270493799228 cap_limit: 40
9600 customer_5 ('customer_5', 'customer_4')
7570 customer_5 -19.473759146793313
resNode: customer_4 deliver_cap: 68.56938307693441 cap_limit: 40
9601 customer_2 ('customer_2', 'customer_3')
7573 customer_2 -5.927886554849541
resNode: customer_3 deliver_cap: 48.52538271954322 cap_limit: 40
9602 customer_2 ('customer_2', 'customer_1')
7573 customer_2 -5.927886554849541
resNode: customer_1 deliver_cap: 37.47463971253514 cap_limit: 40
9603 customer_2 ('customer_2', 'depot_t')
7573 customer_2 -5.927886554849541
resNode: depot_t deliver_cap: 24.375440355189724 cap_limit: 40
9604 customer_2 ('customer_2', 'customer_4')
7573 customer_2 -5.927886554849541
resNode: customer_4 deliver_cap: 48.35334400268476 cap_limit: 40
9605 customer_2 ('customer_2', 'customer_5')
7573 customer_2 -5.927886554849541
resNode: customer_5 deliver_cap: 35.310779067867514 cap_limit: 40
9606 customer_5 ('customer_5', 'customer_3')
7575 customer_5 -14.339881714006104
resNode: customer_3 deliver_cap: 57.69641364372422 cap_limit: 40
9607 customer_5 ('customer_5', 'customer_1')
7575 customer_5 -14.339881714006104
resNode: customer_1 deliver_cap: 48.34618115473121 cap_limit: 40
9608 customer_5 ('customer_5', 'depot_t')
7575 customer_5 -14.339881714006104
resNode: depot_t deliver_cap: 31.85008351318268 cap_limit: 40
9609 customer_5 ('customer_5', 'customer_2')
7575 customer_5 -14.339881714006104
resNode: customer_2 deliver_cap: 35.787490784818694 cap_limit: 40
9610 customer_5 ('customer_5', 'customer_4')
7575 customer_5 -14.339881714006104
resNode: customer_4 deliver_cap: 57.48750948753896 cap_limit: 40
9611 customer_2 ('customer_2', 'customer_3')
7579 customer_2 -11.345382290825711
resNode: customer_3 deliver_cap: 61.529231194572674 cap_limit: 40
9612 customer_2 ('customer_2', 'customer_1')
7579 customer_2 -11.345382290825711
resNode: customer_1 deliver_cap: 49.84074485022981 cap_limit: 40
9613 customer_2 ('customer_2', 'depot_t')
7579 customer_2 -11.345382290825711
resNode: depot_t deliver_cap: 33.6805535390289 cap_limit: 40
9614 customer_2 ('customer_2', 'customer_4')
7579 customer_2 -11.345382290825711
resNode: customer_4 deliver_cap: 61.320327038387404 cap_limit: 40
9615 customer_2 ('customer_2', 'customer_5')
7579 customer_2 -11.345382290825711
resNode: customer_5 deliver_cap: 45.48292676039504 cap_limit: 40
9616 customer_5 ('customer_5', 'customer_3')
7580 customer_5 -19.391835948289284
resNode: customer_3 deliver_cap: 68.56938307693441 cap_limit: 40
9617 customer_5 ('customer_5', 'customer_1')
7580 customer_5 -19.391835948289284
resNode: customer_1 deliver_cap: 59.29363908812936 cap_limit: 40
9618 customer_5 ('customer_5', 'depot_t')
7580 customer_5 -19.391835948289284
resNode: depot_t deliver_cap: 39.75310228820387 cap_limit: 40
9619 customer_5 ('customer_5', 'customer_2')
7580 customer_5 -19.391835948289284
resNode: customer_2 deliver_cap: 44.043800781807015 cap_limit: 40
9620 customer_5 ('customer_5', 'customer_4')
7580 customer_5 -19.391835948289284
resNode: customer_4 deliver_cap: 68.32361348142234 cap_limit: 40
9621 customer_3 ('customer_3', 'customer_1')
7581 customer_3 -15.698158103457395
resNode: customer_1 deliver_cap: 55.58940238329354 cap_limit: 40
9622 customer_3 ('customer_3', 'depot_t')
7581 customer_3 -15.698158103457395
resNode: depot_t deliver_cap: 39.949717964613534 cap_limit: 40
9623 customer_3 ('customer_3', 'customer_2')
7581 customer_3 -15.698158103457395
resNode: customer_2 deliver_cap: 44.25270493799228 cap_limit: 40
9624 customer_3 ('customer_3', 'customer_4')
7581 customer_3 -15.698158103457395
resNode: customer_4 deliver_cap: 54.92697214428887 cap_limit: 40
9625 customer_3 ('customer_3', 'customer_5')
7581 customer_3 -15.698158103457395
resNode: customer_5 deliver_cap: 49.93714745576692 cap_limit: 40
9626 customer_1 ('customer_1', 'customer_3')
7582 customer_1 -11.215679254179275
resNode: customer_3 deliver_cap: 55.80126298901757 cap_limit: 40
9627 customer_1 ('customer_1', 'depot_t')
7582 customer_1 -11.215679254179275
resNode: depot_t deliver_cap: 33.23124144304593 cap_limit: 40
9628 customer_1 ('customer_1', 'customer_2')
7582 customer_1 -11.215679254179275
resNode: customer_2 deliver_cap: 35.787490784818694 cap_limit: 40
9629 customer_1 ('customer_1', 'customer_4')

resNode: customer_1 deliver_cap: 45.47422901645143 cap_limit: 40
9673 customer_5 ('customer_5', 'depot_t')
7620 customer_5 -14.049141050018772
resNode: depot_t deliver_cap: 26.746598691330536 cap_limit: 40
9674 customer_5 ('customer_5', 'customer_2')
7620 customer_5 -14.049141050018772
resNode: customer_2 deliver_cap: 30.2243907101291 cap_limit: 40
9675 customer_5 ('customer_5', 'customer_4')
7620 customer_5 -14.049141050018772
resNode: customer_4 deliver_cap: 52.06548398533066 cap_limit: 40
9676 customer_5 ('customer_5', 'customer_3')
7635 customer_5 -14.285212767807547
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9677 customer_5 ('customer_5', 'customer_1')
7635 customer_5 -14.285212767807547
resNode: customer_1 deliver_cap: 59.42593662300045 cap_limit: 40
9678 customer_5 ('customer_5', 'depot_t')
7635 customer_5 -14.285212767807547
resNode: depot_t deliver_cap: 37.3920874253009 cap_limit: 40
9679 customer_5 ('customer_5', 'customer_2')
7635 customer_5 -14.285212767807547
resNode: customer_2 deliver_cap: 41.484950380268295 cap_limit: 40
9680 customer_5 ('customer_5', 'customer_4')
7635 customer_5 -14.285212767807547
resNode: customer_4 deliver_cap: 66.69117679497 cap_limit: 40
9681 customer_2 ('customer_2', 'customer_3')
7644 customer_2 -13.119514490454208
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9682 customer_2 ('customer_2', 'customer_1')
7644 customer_2 -13.119514490454208
resNode: customer_1 deliver_cap: 57.051830497924634 cap_limit: 40
9683 customer_2 ('customer_2', 'depot_t')
7644 customer_2 -13.119514490454208
resNode: depot_t deliver_cap: 35.78365250805547 cap_limit: 40
9684 customer_2 ('customer_2', 'customer_4')
7644 customer_2 -13.119514490454208
resNode: customer_4 deliver_cap: 66.69117679497003 cap_limit: 40
9685 customer_2 ('customer_2', 'customer_5')
7644 customer_2 -13.119514490454208
resNode: customer_5 deliver_cap: 45.264105830627415 cap_limit: 40
9686 customer_5 ('customer_5', 'customer_3')
7650 customer_5 -16.077953382317144
resNode: customer_3 deliver_cap: 65.96910196390313 cap_limit: 40
9687 customer_5 ('customer_5', 'customer_1')
7650 customer_5 -16.077953382317144
resNode: customer_1 deliver_cap: 57.08340014205277 cap_limit: 40
9688 customer_5 ('customer_5', 'depot_t')
7650 customer_5 -16.077953382317144
resNode: depot_t deliver_cap: 37.67287739777885 cap_limit: 40
9689 customer_5 ('customer_5', 'customer_2')
7650 customer_5 -16.077953382317144
resNode: customer_2 deliver_cap: 41.83356183573043 cap_limit: 40
9690 customer_5 ('customer_5', 'customer_4')
7650 customer_5 -16.077953382317144
resNode: customer_4 deliver_cap: 65.72333236839106 cap_limit: 40
9691 customer_2 ('customer_2', 'customer_3')
7654 customer_2 -16.044093713244457
resNode: customer_3 deliver_cap: 68.34320808897895 cap_limit: 40
9692 customer_2 ('customer_2', 'customer_1')
7654 customer_2 -16.044093713244457
resNode: customer_1 deliver_cap: 57.083400142052774 cap_limit: 40
9693 customer_2 ('customer_2', 'depot_t')
7654 customer_2 -16.044093713244457
resNode: depot_t deliver_cap: 38.21769078858019 cap_limit: 40
9694 customer_2 ('customer_2', 'customer_4')
7654 customer_2 -16.044093713244457
resNode: customer_4 deliver_cap: 68.09743849346688 cap_limit: 40
9695 customer_2 ('customer_2', 'customer_5')
7654 customer_2 -16.044093713244457
resNode: customer_5 deliver_cap: 49.46520287229938 cap_limit: 40
9696 customer_2 ('customer_2', 'customer_3')
7663 customer_2 -8.744193662496883
resNode: customer_3 deliver_cap: 61.52923119457267 cap_limit: 40
9697 customer_2 ('customer_2', 'customer_1')
7663 customer_2 -8.744193662496883
resNode: customer_1 deliver_cap: 49.840744850229804 cap_limit: 40
9698 customer_2 ('customer_2', 'depot_t')
7663 customer_2 -8.744193662496883
resNode: depot_t deliver_cap: 33.68055353902889 cap_limit: 40
9699 customer_2 ('customer_2', 'customer_4')
7663 customer_2 -8.744193662496883
resNode: customer_4 deliver_cap: 61.320327038387404 cap_limit: 40
9700 customer_2 ('customer_2', 'customer_5')
7663 customer_2 -8.744193662496883
resNode: customer_5 deliver_cap: 45.48292676039503 cap_limit: 40
9701 customer_2 ('customer_2', 'customer_3')
7674 customer_2 -11.523955398410376
resNode: customer_3 deliver_cap: 56.820450699487985 cap_limit: 40
9702 customer_2 ('customer_2', 'customer_1')
7674 customer_2 -11.523955398410376
resNode: customer_1 deliver_cap: 47.28905636098545 cap_limit: 40
9703 customer_2 ('customer_2', 'depot_t')
7674 customer_2 -11.523955398410376
resNode: depot_t deliver_cap: 28.99948487698742 cap_limit: 40
9704 customer_2 ('customer_2', 'customer_4')
7674 customer_2 -11.523955398410376
resNode: customer_4 deliver_cap: 56.57468110397591 cap_limit: 40
9705 customer_2 ('customer_2', 'customer_5')
7674 customer_2 -11.523955398410376
resNode: customer_5 deliver_cap: 37.942445482808424 cap_limit: 40
9706 customer_5 ('customer_5', 'customer_3')
7685 customer_5 -15.808347297510059
resNode: customer_3 deliver_cap: 60.95287840316978 cap_limit: 40
9707 customer_5 ('customer_5', 'customer_1')
7685 customer_5 -15.808347297510059
resNode: customer_1 deliver_cap: 54.190342338966424 cap_limit: 40
9708 customer_5 ('customer_5', 'depot_t')
7685 customer_5 -15.808347297510059
resNode: depot_t deliver_cap: 32.41827285546857 cap_limit: 40
9709 customer_5 ('customer_5', 'customer_2')
7685 customer_5 -15.808347297510059
resNode: customer_2 deliver_cap: 36.24935609623427 cap_limit: 40
9710 customer_5 ('customer_5', 'customer_4')
7685 customer_5 -15.808347297510059
resNode: customer_4 deliver_cap: 60.67024336833089 cap_limit: 40
9711 customer_2 ('customer_2', 'customer_3')
7688 customer_2 -8.824532903002858
resNode: customer_3 deliver_cap: 66.58556366690927 cap_limit: 40
9712 customer_2 ('customer_2', 'customer_1')
7688 customer_2 -8.824532903002858
resNode: customer_1 deliver_cap: 55.58940238329354 cap_limit: 40
9713 customer_2 ('customer_2', 'depot_t')
7688 customer_2 -8.824532903002858
resNode: depot_t deliver_cap: 36.81157525092444 cap_limit: 40
9714 customer_2 ('customer_2', 'customer_4')
7688 customer_2 -8.824532903002858
resNode: customer_4 deliver_cap: 66.3397940713972 cap_limit: 40
9715 customer_2 ('customer_2', 'customer_5')
7688 customer_2 -8.824532903002858
resNode: customer_5 deliver_cap: 47.70755845022969 cap_limit: 40
9716 customer_5 ('customer_5', 'customer_3')
7695 customer_5 -12.185328211387896
resNode: customer_3 deliver_cap: 61.23551343800867 cap_limit: 40
9717 customer_5 ('customer_5', 'customer_1')
7695 customer_5 -12.185328211387896
resNode: customer_1 deliver_cap: 54.436111934478504 cap_limit: 40
9718 customer_5 ('customer_5', 'depot_t')
7695 customer_5 -12.185328211387896
resNode: depot_t deliver_cap: 32.65175397120505 cap_limit: 40
9719 customer_5 ('customer_5', 'customer_2')
7695 customer_5 -12.185328211387896
resNode: customer_2 deliver_cap: 36.49512569174635 cap_limit: 40
9720 customer_5 ('customer_5', 'customer_4')
7695 customer_5 -12.185328211387896
resNode: customer_4 deliver_cap: 60.95287840316978 cap_limit: 40
9721 customer_2 ('customer_2', 'customer_3')
7699 customer_2 -8.39510242851632
resNode: customer_3 deliver_cap: 66.97381182980891 cap_limit: 40
9722 customer_2 ('customer_2', 'customer_1')
7699 customer_2 -8.39510242851632
resNode: customer_1 deliver_cap: 57.051830497924634 cap_limit: 40
9723 customer_2 ('customer_2', 'depot_t')
7699 customer_2 -8.39510242851632
resNode: depot_t deliver_cap: 35.78365250805547 cap_limit: 40
9724 customer_2 ('customer_2', 'customer_4')
7699 customer_2 -8.39510242851632
resNode: customer_4 deliver_cap: 66.69117679497003 cap_limit: 40
9725 customer_2 ('customer_2', 'customer_5')
7699 customer_2 -8.39510242851632
resNode: customer_5 deliver_cap: 45.264105830627415 cap_limit: 40
9726 customer_5 ('customer_5', 'customer_3')
7700 customer_5 -13.629210414363667
resNode: customer_3 deliver_cap: 70.74619435403284 cap_limit: 40
9727 customer_5 ('customer_5', 'customer_1')
7700 customer_5 -13.629210414363667
resNode: customer_1 deliver_cap: 63.94918721520912 cap_limit: 40
9728 customer_5 ('customer_5', 'depot_t')
7700 customer_5 -13.629210414363667
resNode: depot_t deliver_cap: 39.09635871506488 cap_limit: 40
9729 customer_5 ('customer_5', 'customer_2')
7700 customer_5 -13.629210414363667
resNode: customer_2 deliver_cap: 43.31705303606714 cap_limit: 40
9730 customer_5 ('customer_5', 'customer_4')
7700 customer_5 -13.629210414363667
resNode: customer_4 deliver_cap: 70.42669387986713 cap_limit: 40
9731 customer_2 ('customer_2', 'customer_3')
7704 customer_2 -11.019629934034555
resNode: customer_3 deliver_cap: 61.23551343800867 cap_limit: 40
9732 customer_2 ('customer_2', 'customer_1')
7704 customer_2 -11.019629934034555
resNode: customer_1 deliver_cap: 52.062005809402685 cap_limit: 40
9733 customer_2 ('customer_2', 'depot_t')
7704 customer_2 -11.019629934034555
resNode: depot_t deliver_cap: 31.043319053959614 cap_limit: 40
9734 customer_2 ('customer_2', 'customer_4')
7704 customer_2 -11.019629934034555
resNode: customer_4 deliver_cap: 60.95287840316978 cap_limit: 40
9735 customer_2 ('customer_2', 'customer_5')
7704 customer_2 -11.019629934034555
resNode: customer_5 deliver_cap: 39.525807438827165 cap_limit: 40
9736 customer_2 ('customer_2', 'customer_3')
7708 customer_2 -11.846623377407475
resNode: customer_3 deliver_cap: 68.95966979198508 cap_limit: 40
9737 customer_2 ('customer_2', 'customer_1')
7708 customer_2 -11.846623377407475
resNode: customer_1 deliver_cap: 57.60739258960798 cap_limit: 40
9738 customer_2 ('customer_2', 'depot_t')
7708 customer_2 -11.846623377407475
resNode: depot_t deliver_cap: 38.7108601509851 cap_limit: 40
9739 customer_2 ('customer_2', 'customer_4')
7708 customer_2 -11.846623377407475
resNode: customer_4 deliver_cap: 68.713900196473 cap_limit: 40
9740 customer_2 ('customer_2', 'customer_5')
7708 customer_2 -11.846623377407475
resNode: customer_5 deliver_cap: 50.08166457530551 cap_limit: 40
9741 customer_1 ('customer_1', 'customer_3')
7712 customer_1 -7.576124295113605
resNode: customer_3 deliver_cap: 55.80126298901757 cap_limit: 40
9742 customer_1 ('customer_1', 'depot_t')
7712 customer_1 -7.576124295113605
resNode: depot_t deliver_cap: 33.231241443045924 cap_limit: 40
9743 customer_1 ('customer_1', 'customer_2')
7712 customer_1 -7.576124295113605
resNode: customer_2 deliver_cap: 35.787490784818694 cap_limit: 40
9744 customer_1 ('customer_1', 'customer_4')
7712 customer_1 -7.576124295113605
resNode: customer_4 deliver_cap: 55.277270541462364 cap_limit: 40
9745 customer_1 ('customer_1', 'customer_5')
7712 customer_1 -7.576124295113605
resNode: customer_5 deliver_cap: 43.66809941586102 cap_limit: 40
9746 customer_5 ('customer_5', 'customer_3')
7715 customer_5 -10.579649107726132
resNode: customer_3 deliver_cap: 52.31125358084274 cap_limit: 40
9747 customer_5 ('customer_5', 'customer_1')
7715 customer_5 -10.579649107726132
resNode: customer_1 deliver_cap: 45.47422901645143 cap_limit: 40
9748 customer_5 ('customer_5', 'depot_t')
7715 customer_5 -10.579649107726132
resNode: depot_t deliver_cap: 26.746598691330536 cap_limit: 40
9749 customer_5 ('customer_5', 'customer_2')
7715 customer_5 -10.579649107726132
resNode: customer_2 deliver_cap: 30.2243907101291 cap_limit: 40
9750 customer_5 ('customer_5', 'customer_4')
7715 customer_5 -10.579649107726132
resNode: customer_4 deliver_cap: 52.06548398533066 cap_limit: 40
9751 customer_2 ('customer_2', 'customer_3')
7719 customer_2 -11.634754169857937
resNode: customer_3 deliver_cap: 68.34320808897897 cap_limit: 40
9752 customer_2 ('customer_2', 'customer_1')
7719 customer_2 -11.634754169857937
resNode: customer_1 deliver_cap: 57.08340014205278 cap_limit: 40
9753 customer_2 ('customer_2', 'depot_t')
7719 customer_2 -11.634754169857937
resNode: depot_t deliver_cap: 38.2176907885802 cap_limit: 40
9754 customer_2 ('customer_2', 'customer_4')
7719 customer_2 -11.634754169857937
resNode: customer_4 deliver_cap: 68.09743849346688 cap_limit: 40
9755 customer_2 ('customer_2', 'customer_5')
7719 customer_2 -11.634754169857937
resNode: customer_5 deliver_cap: 49.465202872299386 cap_limit: 40
9756 customer_2 ('customer_2', 'customer_3')
7724 customer_2 -10.545789438653443
resNode: customer_3 deliver_cap: 54.68535970591856 cap_limit: 40
9757 customer_2 ('customer_2', 'customer_1')
7724 customer_2 -10.545789438653443
resNode: customer_1 deliver_cap: 45.47422901645144 cap_limit: 40
9758 customer_2 ('customer_2', 'depot_t')
7724 customer_2 -10.545789438653443
resNode: depot_t deliver_cap: 27.29141208213188 cap_limit: 40
9759 customer_2 ('customer_2', 'customer_4')
7724 customer_2 -10.545789438653443
resNode: customer_4 deliver_cap: 54.439590110406485 cap_limit: 40
9760 customer_2 ('customer_2', 'customer_5')
7724 customer_2 -10.545789438653443
resNode: customer_5 deliver_cap: 35.807354489238996 cap_limit: 40
9761 customer_1 ('customer_1', 'customer_3')
7726 customer_1 -8.931844569657384
resNode: customer_3 deliver_cap: 64.35597466137204 cap_limit: 40
9762 customer_1 ('customer_1', 'depot_t')
7726 customer_1 -8.931844569657384
resNode: depot_t deliver_cap: 39.86593344309237 cap_limit: 40
9763 customer_1 ('customer_1', 'customer_2')
7726 customer_1 -8.931844569657384
resNode: customer_2 deliver_cap: 42.357554283285644 cap_limit: 40
9764 customer_1 ('customer_1', 'customer_4')
7726 customer_1 -8.931844569657384
resNode: customer_4 deliver_cap: 63.73951295836592 cap_limit: 40
9765 customer_1 ('customer_1', 'customer_5')
7726 customer_1 -8.931844569657384
resNode: customer_5 deliver_cap: 50.081664575305524 cap_limit: 40
9766 customer_2 ('customer_2', 'customer_3')
7728 customer_2 -6.9109542522957135
resNode: customer_3 deliver_cap: 57.06622029500005 cap_limit: 40
9767 customer_2 ('customer_2', 'customer_1')
7728 customer_2 -6.9109542522957135
resNode: customer_1 deliver_cap: 47.49796051717071 cap_limit: 40
9768 customer_2 ('customer_2', 'depot_t')
7728 customer_2 -6.9109542522957135
resNode: depot_t deliver_cap: 29.196100553397077 cap_limit: 40
9769 customer_2 ('customer_2', 'customer_4')
7728 customer_2 -6.9109542522957135
resNode: customer_4 deliver_cap: 56.82045069948798 cap_limit: 40
9770 customer_2 ('customer_2', 'customer_5')
7728 customer_2 -6.9109542522957135
resNode: customer_5 deliver_cap: 38.18821507832049 cap_limit: 40
9771 customer_4 ('customer_4', 'customer_3')
7729 customer_4 -9.130998758651568
resNode: customer_3 deliver_cap: 51.28503925726653 cap_limit: 40
9772 customer_4 ('customer_4', 'customer_1')
7729 customer_4 -9.130998758651568
resNode: customer_1 deliver_cap: 54.451549384893354 cap_limit: 40
9773 customer_4 ('customer_4', 'depot_t')
7729 customer_4 -9.130998758651568
resNode: depot_t deliver_cap: 37.3920874253009 cap_limit: 40
9774 customer_4 ('customer_4', 'customer_2')
7729 customer_4 -9.130998758651568
resNode: customer_2 deliver_cap: 41.484950380268295 cap_limit: 40
9775 customer_4 ('customer_4', 'customer_5')
7729 customer_4 -9.130998758651568
resNode: customer_5 deliver_cap: 45.2641058306274 cap_limit: 40
9776 customer_5 ('customer_5', 'customer_3')
7730 customer_5 -12.0050174985959
resNode: customer_3 deliver_cap: 61.23551343800867 cap_limit: 40
9777 customer_5 ('customer_5', 'customer_1')
7730 customer_5 -12.0050174985959
resNode: customer_1 deliver_cap: 54.436111934478504 cap_limit: 40
9778 customer_5 ('customer_5', 'depot_t')
7730 customer_5 -12.0050174985959
resNode: depot_t deliver_cap: 32.65175397120505 cap_limit: 40
9779 customer_5 ('customer_5', 'customer_2')
7730 customer_5 -12.0050174985959
resNode: customer_2 deliver_cap: 36.49512569174635 cap_limit: 40
9780 customer_5 ('customer_5', 'customer_4')
7730 customer_5 -12.0050174985959
resNode: customer_4 deliver_cap: 60.95287840316978 cap_limit: 40
9781 customer_3 ('customer_3', 'customer_1')
7731 customer_3 -10.341910310796933
resNode: customer_1 deliver_cap: 53.6942517285869 cap_limit: 40
9782 customer_3 ('customer_3', 'depot_t')
7731 customer_3 -10.341910310796933
resNode: depot_t deliver_cap: 38.166046760183754 cap_limit: 40
9783 customer_3 ('customer_3', 'customer_2')
7731 customer_3 -10.341910310796933
resNode: customer_2 deliver_cap: 42.35755428328564 cap_limit: 40
9784 customer_3 ('customer_3', 'customer_4')
7731 customer_3 -10.341910310796933
resNode: customer_4 deliver_cap: 52.69738313875165 cap_limit: 40
9785 customer_3 ('customer_3', 'customer_5')
7731 customer_3 -10.341910310796933
resNode: customer_5 deliver_cap: 47.70755845022969 cap_limit: 40
9786 customer_2 ('customer_2', 'customer_3')
7733 customer_2 -4.252239947821232
resNode: customer_3 deliver_cap: 45.6918309165803 cap_limit: 40
9787 customer_2 ('customer_2', 'customer_1')
7733 customer_2 -4.252239947821232
resNode: customer_1 deliver_cap: 36.79817991541255 cap_limit: 40
9788 customer_2 ('customer_2', 'depot_t')
7733 customer_2 -4.252239947821232
resNode: depot_t deliver_cap: 21.569600385270025 cap_limit: 40
9789 customer_2 ('customer_2', 'customer_4')
7733 customer_2 -4.252239947821232
resNode: customer_4 deliver_cap: 45.48292676039504 cap_limit: 40
9790 customer_2 ('customer_2', 'customer_5')
7733 customer_2 -4.252239947821232
resNode: customer_5 deliver_cap: 29.645526482402673 cap_limit: 40
9791 customer_4 ('customer_4', 'customer_3')
7734 customer_4 -10.160864188397703
resNode: customer_3 deliver_cap: 52.32669103125758 cap_limit: 40
9792 customer_4 ('customer_4', 'customer_1')
7734 customer_4 -10.160864188397703
resNode: customer_1 deliver_cap: 52.85517098966174 cap_limit: 40
9793 customer_4 ('customer_4', 'depot_t')
7734 customer_4 -10.160864188397703
resNode: depot_t deliver_cap: 37.67287739777885 cap_limit: 40
9794 customer_4 ('customer_4', 'customer_2')
7734 customer_4 -10.160864188397703
resNode: customer_2 deliver_cap: 41.83356183573043 cap_limit: 40
9795 customer_4 ('customer_4', 'customer_5')
7734 customer_4 -10.160864188397703
resNode: customer_5 deliver_cap: 47.09109674722356 cap_limit: 40
9796 customer_5 ('customer_5', 'customer_3')
7735 customer_5 -9.754791876346228
resNode: customer_3 deliver_cap: 52.31125358084274 cap_limit: 40
9797 customer_5 ('customer_5', 'customer_1')
7735 customer_5 -9.754791876346228
resNode: customer_1 deliver_cap: 45.47422901645143 cap_limit: 40
9798 customer_5 ('customer_5', 'depot_t')
7735 customer_5 -9.754791876346228
resNode: depot_t deliver_cap: 26.746598691330536 cap_limit: 40
9799 customer_5 ('customer_5', 'customer_2')
7735 customer_5 -9.754791876346228
resNode: customer_2 deliver_cap: 30.2243907101291 cap_limit: 40
9800 customer_5 ('customer_5', 'customer_4')
7735 customer_5 -9.754791876346228
resNode: customer_4 deliver_cap: 52.06548398533066 cap_limit: 40
9801 customer_3 ('customer_3', 'customer_1')
7736 customer_3 -9.081844839549152
resNode: customer_1 deliver_cap: 54.82224149238742 cap_limit: 40
9802 customer_3 ('customer_3', 'depot_t')
7736 customer_3 -9.081844839549152
resNode: depot_t deliver_cap: 37.3920874253009 cap_limit: 40
9803 customer_3 ('customer_3', 'customer_2')
7736 customer_3 -9.081844839549152
resNode: customer_2 deliver_cap: 41.484950380268295 cap_limit: 40
9804 customer_3 ('customer_3', 'customer_4')
7736 customer_3 -9.081844839549152
resNode: customer_4 deliver_cap: 51.00240422242765 cap_limit: 40
9805 customer_3 ('customer_3', 'customer_5')
7736 customer_3 -9.081844839549152
resNode: customer_5 deliver_cap: 45.264105830627415 cap_limit: 40
9806 customer_1 ('customer_1', 'customer_3')
7737 customer_1 -8.794113783606658
resNode: customer_3 deliver_cap: 63.739512958365914 cap_limit: 40
9807 customer_1 ('customer_1', 'depot_t')
7737 customer_1 -8.794113783606658
resNode: depot_t deliver_cap: 39.37276408068747 cap_limit: 40
9808 customer_1 ('customer_1', 'customer_2')
7737 customer_1 -8.794113783606658
resNode: customer_2 deliver_cap: 41.833561835730436 cap_limit: 40
9809 customer_1 ('customer_1', 'customer_4')
7737 customer_1 -8.794113783606658
resNode: customer_4 deliver_cap: 63.12305125535978 cap_limit: 40
9810 customer_1 ('customer_1', 'customer_5')
7737 customer_1 -8.794113783606658
resNode: customer_5 deliver_cap: 49.46520287229938 cap_limit: 40

7798 customer_2 -11.106066905206152
resNode: customer_5 deliver_cap: 53.259280335147906 cap_limit: 40
9881 customer_2 ('customer_2', 'customer_3')
7804 customer_2 -15.601200753197478
resNode: customer_3 deliver_cap: 65.96910196390313 cap_limit: 40
9882 customer_2 ('customer_2', 'customer_1')
7804 customer_2 -15.601200753197478
resNode: customer_1 deliver_cap: 55.065409935738316 cap_limit: 40
9883 customer_2 ('customer_2', 'depot_t')
7804 customer_2 -15.601200753197478
resNode: depot_t deliver_cap: 36.31840588851953 cap_limit: 40
9884 customer_2 ('customer_2', 'customer_4')
7804 customer_2 -15.601200753197478
resNode: customer_4 deliver_cap: 65.72333236839106 cap_limit: 40
9885 customer_2 ('customer_2', 'customer_5')
7804 customer_2 -15.601200753197478
resNode: customer_5 deliver_cap: 47.09109674722355 cap_limit: 40
9886 customer_5 ('customer_5', 'customer_3')
7820 customer_5 -17.54611617184917
resNode: customer_3 deliver_cap: 68.5693830769344 cap_limit: 40
9887 customer_5 ('customer_5', 'customer_1')
7820 customer_5 -17.54611617184917
resNode: customer_1 deliver_cap: 59.29363908812934 cap_limit: 40
9888 customer_5 ('customer_5', 'depot_t')
7820 customer_5 -17.54611617184917
resNode: depot_t deliver_cap: 39.75310228820386 cap_limit: 40
9889 customer_5 ('customer_5', 'customer_2')
7820 customer_5 -17.54611617184917
resNode: customer_2 deliver_cap: 44.04380078180701 cap_limit: 40
9890 customer_5 ('customer_5', 'customer_4')
7820 customer_5 -17.54611617184917
resNode: customer_4 deliver_cap: 68.32361348142231 cap_limit: 40
9891 customer_5 ('customer_5', 'customer_3')
7840 customer_5 -15.976369530526455
resNode: customer_3 deliver_cap: 60.95287840316978 cap_limit: 40
9892 customer_5 ('customer_5', 'customer_1')
7840 customer_5 -15.976369530526455
resNode: customer_1 deliver_cap: 54.19034233896643 cap_limit: 40
9893 customer_5 ('customer_5', 'depot_t')
7840 customer_5 -15.976369530526455
resNode: depot_t deliver_cap: 32.41827285546858 cap_limit: 40
9894 customer_5 ('customer_5', 'customer_2')
7840 customer_5 -15.976369530526455
resNode: customer_2 deliver_cap: 36.24935609623427 cap_limit: 40
9895 customer_5 ('customer_5', 'customer_4')
7840 customer_5 -15.976369530526455
resNode: customer_4 deliver_cap: 60.67024336833089 cap_limit: 40
9896 customer_2 ('customer_2', 'customer_3')
7848 customer_2 -12.56694317491911
resNode: customer_3 deliver_cap: 68.5693830769344 cap_limit: 40
9897 customer_2 ('customer_2', 'customer_1')
7848 customer_2 -12.56694317491911
resNode: customer_1 deliver_cap: 57.2756488818149 cap_limit: 40
9898 customer_2 ('customer_2', 'depot_t')
7848 customer_2 -12.56694317491911
resNode: depot_t deliver_cap: 38.39863077894455 cap_limit: 40
9899 customer_2 ('customer_2', 'customer_4')
7848 customer_2 -12.56694317491911
resNode: customer_4 deliver_cap: 68.32361348142231 cap_limit: 40
9900 customer_2 ('customer_2', 'customer_5')
7848 customer_2 -12.56694317491911
resNode: customer_5 deliver_cap: 49.69137786025483 cap_limit: 40
9901 customer_2 ('customer_2', 'customer_3')
7854 customer_2 -14.047081705131127
resNode: customer_3 deliver_cap: 60.95287840316978 cap_limit: 40
9902 customer_2 ('customer_2', 'customer_1')
7854 customer_2 -14.047081705131127
resNode: customer_1 deliver_cap: 51.816236213890605 cap_limit: 40
9903 customer_2 ('customer_2', 'depot_t')
7854 customer_2 -14.047081705131127
resNode: depot_t deliver_cap: 30.80983793822314 cap_limit: 40
9904 customer_2 ('customer_2', 'customer_4')
7854 customer_2 -14.047081705131127
resNode: customer_4 deliver_cap: 60.67024336833089 cap_limit: 40
9905 customer_2 ('customer_2', 'customer_5')
7854 customer_2 -14.047081705131127
resNode: customer_5 deliver_cap: 39.243172403988275 cap_limit: 40
9906 customer_2 ('customer_2', 'customer_3')
7874 customer_2 -19.236048916403533
resNode: customer_3 deliver_cap: 68.92086462436917 cap_limit: 40
9907 customer_2 ('customer_2', 'customer_1')
7874 customer_2 -19.236048916403533
resNode: customer_1 deliver_cap: 58.744919884498785 cap_limit: 40
9908 customer_2 ('customer_2', 'depot_t')
7874 customer_2 -19.236048916403533
resNode: depot_t deliver_cap: 37.39208742530091 cap_limit: 40
9909 customer_2 ('customer_2', 'customer_4')
7874 customer_2 -19.236048916403533
resNode: customer_4 deliver_cap: 68.6382295895303 cap_limit: 40
9910 customer_2 ('customer_2', 'customer_5')
7874 customer_2 -19.236048916403533
resNode: customer_5 deliver_cap: 47.21115862518768 cap_limit: 40
9911 customer_2 ('customer_2', 'customer_3')
7893 customer_2 -15.576199809192222
resNode: customer_3 deliver_cap: 69.15716611005297 cap_limit: 40
9912 customer_2 ('customer_2', 'customer_1')
7893 customer_2 -15.576199809192222
resNode: customer_1 deliver_cap: 53.68532666222137 cap_limit: 40
9913 customer_2 ('customer_2', 'depot_t')
7893 customer_2 -15.576199809192222
resNode: depot_t deliver_cap: 39.11242849126812 cap_limit: 40
9914 customer_2 ('customer_2', 'customer_4')
7893 customer_2 -15.576199809192222
resNode: customer_4 deliver_cap: 68.98512739319452 cap_limit: 40
9915 customer_2 ('customer_2', 'customer_5')
7893 customer_2 -15.576199809192222
resNode: customer_5 deliver_cap: 55.94256245837727 cap_limit: 40
9916 customer_2 ('customer_2', 'customer_3')
7919 customer_2 -24.239511861167284
resNode: customer_3 deliver_cap: 67.66219135047726 cap_limit: 40
9917 customer_2 ('customer_2', 'customer_1')
7919 customer_2 -24.239511861167284
resNode: customer_1 deliver_cap: 56.50453591432633 cap_limit: 40
9918 customer_2 ('customer_2', 'depot_t')
7919 customer_2 -24.239511861167284
resNode: depot_t deliver_cap: 37.67287739777884 cap_limit: 40
9919 customer_2 ('customer_2', 'customer_4')
7919 customer_2 -24.239511861167284
resNode: customer_4 deliver_cap: 67.4164217549652 cap_limit: 40
9920 customer_2 ('customer_2', 'customer_5')
7919 customer_2 -24.239511861167284
resNode: customer_5 deliver_cap: 48.78418613379769 cap_limit: 40
9921 customer_5 ('customer_5', 'customer_3')
8005 customer_5 -21.88138253433315
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
9922 customer_5 ('customer_5', 'customer_1')
8005 customer_5 -21.88138253433315
resNode: customer_1 deliver_cap: 55.88343172554058 cap_limit: 40
9923 customer_5 ('customer_5', 'depot_t')
8005 customer_5 -21.88138253433315
resNode: depot_t deliver_cap: 34.02670777271402 cap_limit: 40
9924 customer_5 ('customer_5', 'customer_2')
8005 customer_5 -21.88138253433315
resNode: customer_2 deliver_cap: 37.942445482808424 cap_limit: 40
9925 customer_5 ('customer_5', 'customer_4')
8005 customer_5 -21.88138253433315
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
9926 customer_2 ('customer_2', 'customer_3')
8024 customer_2 -21.85532456114673
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
9927 customer_2 ('customer_2', 'customer_1')
8024 customer_2 -21.85532456114673
resNode: customer_1 deliver_cap: 58.71477486040292 cap_limit: 40
9928 customer_2 ('customer_2', 'depot_t')
8024 customer_2 -21.85532456114673
resNode: depot_t deliver_cap: 39.75310228820386 cap_limit: 40
9929 customer_2 ('customer_2', 'customer_4')
8024 customer_2 -21.85532456114673
resNode: customer_4 deliver_cap: 70.01670286799646 cap_limit: 40
9930 customer_2 ('customer_2', 'customer_5')
8024 customer_2 -21.85532456114673
resNode: customer_5 deliver_cap: 51.38446724682897 cap_limit: 40
9931 customer_2 ('customer_2', 'customer_3')
8038 customer_2 -17.390912370701166
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
9932 customer_2 ('customer_2', 'customer_1')
8038 customer_2 -17.390912370701166
resNode: customer_1 deliver_cap: 58.714774860402926 cap_limit: 40
9933 customer_2 ('customer_2', 'depot_t')
8038 customer_2 -17.390912370701166
resNode: depot_t deliver_cap: 39.75310228820387 cap_limit: 40
9934 customer_2 ('customer_2', 'customer_4')
8038 customer_2 -17.390912370701166
resNode: customer_4 deliver_cap: 70.01670286799649 cap_limit: 40
9935 customer_2 ('customer_2', 'customer_5')
8038 customer_2 -17.390912370701166
resNode: customer_5 deliver_cap: 51.384467246828976 cap_limit: 40
9936 customer_2 ('customer_2', 'customer_3')
8044 customer_2 -19.188505160895836
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
9937 customer_2 ('customer_2', 'customer_1')
8044 customer_2 -19.188505160895836
resNode: customer_1 deliver_cap: 53.50932560046475 cap_limit: 40
9938 customer_2 ('customer_2', 'depot_t')
8044 customer_2 -19.188505160895836
resNode: depot_t deliver_cap: 32.41827285546858 cap_limit: 40
9939 customer_2 ('customer_2', 'customer_4')
8044 customer_2 -19.188505160895836
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
9940 customer_2 ('customer_2', 'customer_5')
8044 customer_2 -19.188505160895836
resNode: customer_5 deliver_cap: 41.190225198548546 cap_limit: 40
9941 customer_2 ('customer_2', 'customer_3')
8069 customer_2 -18.25995455451967
resNode: customer_3 deliver_cap: 70.50824205902062 cap_limit: 40
9942 customer_2 ('customer_2', 'customer_1')
8069 customer_2 -18.25995455451967
resNode: customer_1 deliver_cap: 58.92367901658818 cap_limit: 40
9943 customer_2 ('customer_2', 'depot_t')
8069 customer_2 -18.25995455451967
resNode: depot_t deliver_cap: 39.94971796461352 cap_limit: 40
9944 customer_2 ('customer_2', 'customer_4')
8069 customer_2 -18.25995455451967
resNode: customer_4 deliver_cap: 70.26247246350854 cap_limit: 40
9945 customer_2 ('customer_2', 'customer_5')
8069 customer_2 -18.25995455451967
resNode: customer_5 deliver_cap: 51.63023684234104 cap_limit: 40
9946 customer_2 ('customer_2', 'customer_3')
8083 customer_2 -13.795542364074104
resNode: customer_3 deliver_cap: 70.50824205902062 cap_limit: 40
9947 customer_2 ('customer_2', 'customer_1')
8083 customer_2 -13.795542364074104
resNode: customer_1 deliver_cap: 58.92367901658819 cap_limit: 40
9948 customer_2 ('customer_2', 'depot_t')
8083 customer_2 -13.795542364074104
resNode: depot_t deliver_cap: 39.94971796461353 cap_limit: 40
9949 customer_2 ('customer_2', 'customer_4')
8083 customer_2 -13.795542364074104
resNode: customer_4 deliver_cap: 70.26247246350854 cap_limit: 40
9950 customer_2 ('customer_2', 'customer_5')
8083 customer_2 -13.795542364074104
resNode: customer_5 deliver_cap: 51.63023684234105 cap_limit: 40
9951 customer_2 ('customer_2', 'customer_3')
8089 customer_2 -15.639216953427287
resNode: customer_3 deliver_cap: 63.18256623256893 cap_limit: 40
9952 customer_2 ('customer_2', 'customer_1')
8089 customer_2 -15.639216953427287
resNode: customer_1 deliver_cap: 53.755095195976835 cap_limit: 40
9953 customer_2 ('customer_2', 'depot_t')
8089 customer_2 -15.639216953427287
resNode: depot_t deliver_cap: 32.65175397120505 cap_limit: 40
9954 customer_2 ('customer_2', 'customer_4')
8089 customer_2 -15.639216953427287
resNode: customer_4 deliver_cap: 62.89993119773004 cap_limit: 40
9955 customer_2 ('customer_2', 'customer_5')
8089 customer_2 -15.639216953427287
resNode: customer_5 deliver_cap: 41.472860233387436 cap_limit: 40
9956 customer_2 ('customer_2', 'customer_3')
8109 customer_2 -16.543241326819818
resNode: customer_3 deliver_cap: 72.94721055657922 cap_limit: 40
9957 customer_2 ('customer_2', 'customer_1')
8109 customer_2 -16.543241326819818
resNode: customer_1 deliver_cap: 63.16601796593219 cap_limit: 40
9958 customer_2 ('customer_2', 'depot_t')
8109 customer_2 -16.543241326819818
resNode: depot_t deliver_cap: 39.09635871506487 cap_limit: 40
9959 customer_2 ('customer_2', 'customer_4')
8109 customer_2 -16.543241326819818
resNode: customer_4 deliver_cap: 72.62771008241351 cap_limit: 40
9960 customer_2 ('customer_2', 'customer_5')
8109 customer_2 -16.543241326819818
resNode: customer_5 deliver_cap: 48.40580377489579 cap_limit: 40
9961 customer_5 ('customer_5', 'customer_3')
8120 customer_5 -18.728007974075464
resNode: customer_3 deliver_cap: 66.4604384615007 cap_limit: 40
9962 customer_5 ('customer_5', 'customer_1')
8120 customer_5 -18.728007974075464
resNode: customer_1 deliver_cap: 60.15794161796915 cap_limit: 40
9963 customer_5 ('customer_5', 'depot_t')
8120 customer_5 -18.728007974075464
resNode: depot_t deliver_cap: 35.46994988292229 cap_limit: 40
9964 customer_5 ('customer_5', 'customer_2')
8120 customer_5 -18.728007974075464
resNode: customer_2 deliver_cap: 39.52580743882717 cap_limit: 40
9965 customer_5 ('customer_5', 'customer_4')
8120 customer_5 -18.728007974075464
resNode: customer_4 deliver_cap: 66.140937987335 cap_limit: 40
9966 customer_2 ('customer_2', 'customer_3')
8163 customer_2 -11.102234163330742
resNode: customer_3 deliver_cap: 59.596672241910696 cap_limit: 40
9967 customer_2 ('customer_2', 'customer_1')
8163 customer_2 -11.102234163330742
resNode: customer_1 deliver_cap: 46.17351005153816 cap_limit: 40
9968 customer_2 ('customer_2', 'depot_t')
8163 customer_2 -11.102234163330742
resNode: depot_t deliver_cap: 32.28350429973793 cap_limit: 40
9969 customer_2 ('customer_2', 'customer_4')
8163 customer_2 -11.102234163330742
resNode: customer_4 deliver_cap: 59.424633525052236 cap_limit: 40
9970 customer_2 ('customer_2', 'customer_5')
8163 customer_2 -11.102234163330742
resNode: customer_5 deliver_cap: 46.382068590234994 cap_limit: 40
9971 customer_2 ('customer_2', 'customer_3')
8174 customer_2 -16.856523725953572
resNode: customer_3 deliver_cap: 59.13553962231223 cap_limit: 40
9972 customer_2 ('customer_2', 'customer_1')
8174 customer_2 -16.856523725953572
resNode: customer_1 deliver_cap: 47.869469437780026 cap_limit: 40
9973 customer_2 ('customer_2', 'depot_t')
8174 customer_2 -16.856523725953572
resNode: depot_t deliver_cap: 31.850083513182675 cap_limit: 40
9974 customer_2 ('customer_2', 'customer_4')
8174 customer_2 -16.856523725953572
resNode: customer_4 deliver_cap: 58.92663546612696 cap_limit: 40
9975 customer_2 ('customer_2', 'customer_5')
8174 customer_2 -16.856523725953572
resNode: customer_5 deliver_cap: 43.089235188134595 cap_limit: 40
9976 customer_5 ('customer_5', 'customer_3')
8190 customer_5 -25.154536616911116
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
9977 customer_5 ('customer_5', 'customer_1')
8190 customer_5 -25.154536616911116
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
9978 customer_5 ('customer_5', 'depot_t')
8190 customer_5 -25.154536616911116
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
9979 customer_5 ('customer_5', 'customer_2')
8190 customer_5 -25.154536616911116
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
9980 customer_5 ('customer_5', 'customer_4')
8190 customer_5 -25.154536616911116
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
9981 customer_5 ('customer_5', 'customer_3')
8215 customer_5 -21.685044674618474
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
9982 customer_5 ('customer_5', 'customer_1')
8215 customer_5 -21.685044674618474
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
9983 customer_5 ('customer_5', 'depot_t')
8215 customer_5 -21.685044674618474
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
9984 customer_5 ('customer_5', 'customer_2')
8215 customer_5 -21.685044674618474
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
9985 customer_5 ('customer_5', 'customer_4')
8215 customer_5 -21.685044674618474
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
9986 customer_2 ('customer_2', 'customer_3')
8219 customer_2 -21.65118500554578
resNode: customer_3 deliver_cap: 70.50148759501495 cap_limit: 40
9987 customer_2 ('customer_2', 'customer_1')
8219 customer_2 -21.65118500554578
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
9988 customer_2 ('customer_2', 'depot_t')
8219 customer_2 -21.65118500554578
resNode: depot_t deliver_cap: 39.94431439340899 cap_limit: 40
9989 customer_2 ('customer_2', 'customer_4')
8219 customer_2 -21.65118500554578
resNode: customer_4 deliver_cap: 70.25571799950286 cap_limit: 40
9990 customer_2 ('customer_2', 'customer_5')
8219 customer_2 -21.65118500554578
resNode: customer_5 deliver_cap: 51.623482378335375 cap_limit: 40
9991 customer_2 ('customer_2', 'customer_3')
8228 customer_2 -12.392111535508002
resNode: customer_3 deliver_cap: 59.13553962231224 cap_limit: 40
9992 customer_2 ('customer_2', 'customer_1')
8228 customer_2 -12.392111535508002
resNode: customer_1 deliver_cap: 47.86946943778003 cap_limit: 40
9993 customer_2 ('customer_2', 'depot_t')
8228 customer_2 -12.392111535508002
resNode: depot_t deliver_cap: 31.85008351318268 cap_limit: 40
9994 customer_2 ('customer_2', 'customer_4')
8228 customer_2 -12.392111535508002
resNode: customer_4 deliver_cap: 58.926635466126974 cap_limit: 40
9995 customer_2 ('customer_2', 'customer_5')
8228 customer_2 -12.392111535508002
resNode: customer_5 deliver_cap: 43.0892351881346 cap_limit: 40
9996 customer_5 ('customer_5', 'customer_3')
8230 customer_5 -20.860187443238573
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
9997 customer_5 ('customer_5', 'customer_1')
8230 customer_5 -20.860187443238573
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
9998 customer_5 ('customer_5', 'depot_t')
8230 customer_5 -20.860187443238573
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
9999 customer_5 ('customer_5', 'customer_2')
8230 customer_5 -20.860187443238573
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
10000 customer_5 ('customer_5', 'customer_4')
8230 customer_5 -20.860187443238573
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
10001 customer_2 ('customer_2', 'customer_3')
8239 customer_2 -14.643853071658157
resNode: customer_3 deliver_cap: 54.00434296741689 cap_limit: 40
10002 customer_2 ('customer_2', 'customer_1')
8239 customer_2 -14.643853071658157
resNode: customer_1 deliver_cap: 44.89536478872501 cap_limit: 40
10003 customer_2 ('customer_2', 'depot_t')
8239 customer_2 -14.643853071658157
resNode: depot_t deliver_cap: 26.74659869133054 cap_limit: 40
10004 customer_2 ('customer_2', 'customer_4')
8239 customer_2 -14.643853071658157
resNode: customer_4 deliver_cap: 53.758573371904816 cap_limit: 40
10005 customer_2 ('customer_2', 'customer_5')
8239 customer_2 -14.643853071658157
resNode: customer_5 deliver_cap: 35.12633775073732 cap_limit: 40
10006 customer_2 ('customer_2', 'customer_3')
8269 customer_2 -22.30597922015266
resNode: customer_3 deliver_cap: 70.50148759501495 cap_limit: 40
10007 customer_2 ('customer_2', 'customer_1')
8269 customer_2 -22.30597922015266
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10008 customer_2 ('customer_2', 'depot_t')
8269 customer_2 -22.30597922015266
resNode: depot_t deliver_cap: 39.94431439340899 cap_limit: 40
10009 customer_2 ('customer_2', 'customer_4')
8269 customer_2 -22.30597922015266
resNode: customer_4 deliver_cap: 70.25571799950286 cap_limit: 40
10010 customer_2 ('customer_2', 'customer_5')
8269 customer_2 -22.30597922015266
resNode: customer_5 deliver_cap: 51.623482378335375 cap_limit: 40
10011 customer_5 ('customer_5', 'customer_3')
8285 customer_5 -21.51498165784545
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
10012 customer_5 ('customer_5', 'customer_1')
8285 customer_5 -21.51498165784545
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10013 customer_5 ('customer_5', 'depot_t')
8285 customer_5 -21.51498165784545
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
10014 customer_5 ('customer_5', 'customer_2')
8285 customer_5 -21.51498165784545
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
10015 customer_5 ('customer_5', 'customer_4')
8285 customer_5 -21.51498165784545
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
10016 customer_2 ('customer_2', 'customer_3')
8289 customer_2 -21.481121988772756
resNode: customer_3 deliver_cap: 70.50148759501495 cap_limit: 40
10017 customer_2 ('customer_2', 'customer_1')
8289 customer_2 -21.481121988772756
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10018 customer_2 ('customer_2', 'depot_t')

10081 customer_2 ('customer_2', 'customer_3')
8469 customer_2 -19.97459721335334
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
10082 customer_2 ('customer_2', 'customer_1')
8469 customer_2 -19.97459721335334
resNode: customer_1 deliver_cap: 58.71477486040292 cap_limit: 40
10083 customer_2 ('customer_2', 'depot_t')
8469 customer_2 -19.97459721335334
resNode: depot_t deliver_cap: 39.75310228820386 cap_limit: 40
10084 customer_2 ('customer_2', 'customer_4')
8469 customer_2 -19.97459721335334
resNode: customer_4 deliver_cap: 70.01670286799646 cap_limit: 40
10085 customer_2 ('customer_2', 'customer_5')
8469 customer_2 -19.97459721335334
resNode: customer_5 deliver_cap: 51.38446724682897 cap_limit: 40
10086 customer_2 ('customer_2', 'customer_3')
8473 customer_2 -16.293207848297058
resNode: customer_3 deliver_cap: 70.50824205902062 cap_limit: 40
10087 customer_2 ('customer_2', 'customer_1')
8473 customer_2 -16.293207848297058
resNode: customer_1 deliver_cap: 58.92367901658819 cap_limit: 40
10088 customer_2 ('customer_2', 'depot_t')
8473 customer_2 -16.293207848297058
resNode: depot_t deliver_cap: 39.94971796461353 cap_limit: 40
10089 customer_2 ('customer_2', 'customer_4')
8473 customer_2 -16.293207848297058
resNode: customer_4 deliver_cap: 70.26247246350854 cap_limit: 40
10090 customer_2 ('customer_2', 'customer_5')
8473 customer_2 -16.293207848297058
resNode: customer_5 deliver_cap: 51.63023684234105 cap_limit: 40
10091 customer_2 ('customer_2', 'customer_3')
8478 customer_2 -11.737317320901127
resNode: customer_3 deliver_cap: 59.13553962231224 cap_limit: 40
10092 customer_2 ('customer_2', 'customer_1')
8478 customer_2 -11.737317320901127
resNode: customer_1 deliver_cap: 47.86946943778003 cap_limit: 40
10093 customer_2 ('customer_2', 'depot_t')
8478 customer_2 -11.737317320901127
resNode: depot_t deliver_cap: 31.85008351318268 cap_limit: 40
10094 customer_2 ('customer_2', 'customer_4')
8478 customer_2 -11.737317320901127
resNode: customer_4 deliver_cap: 58.926635466126974 cap_limit: 40
10095 customer_2 ('customer_2', 'customer_5')
8478 customer_2 -11.737317320901127
resNode: customer_5 deliver_cap: 43.0892351881346 cap_limit: 40
10096 customer_5 ('customer_5', 'customer_3')
8480 customer_5 -20.205393228631696
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
10097 customer_5 ('customer_5', 'customer_1')
8480 customer_5 -20.205393228631696
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10098 customer_5 ('customer_5', 'depot_t')
8480 customer_5 -20.205393228631696
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
10099 customer_5 ('customer_5', 'customer_2')
8480 customer_5 -20.205393228631696
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
10100 customer_5 ('customer_5', 'customer_4')
8480 customer_5 -20.205393228631696
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
10101 customer_1 ('customer_1', 'customer_3')
8482 customer_1 -11.14708435198051
resNode: customer_3 deliver_cap: 55.222398761291146 cap_limit: 40
10102 customer_1 ('customer_1', 'depot_t')
8482 customer_1 -11.14708435198051
resNode: depot_t deliver_cap: 32.788580563019835 cap_limit: 40
10103 customer_1 ('customer_1', 'customer_2')
8482 customer_1 -11.14708435198051
resNode: customer_2 deliver_cap: 35.310779067867514 cap_limit: 40
10104 customer_1 ('customer_1', 'customer_4')
8482 customer_1 -11.14708435198051
resNode: customer_4 deliver_cap: 54.698406313735944 cap_limit: 40
10105 customer_1 ('customer_1', 'customer_5')
8482 customer_1 -11.14708435198051
resNode: customer_5 deliver_cap: 43.0892351881346 cap_limit: 40
10106 customer_5 ('customer_5', 'customer_3')
8485 customer_5 -14.022918526123975
resNode: customer_3 deliver_cap: 51.630236842341056 cap_limit: 40
10107 customer_5 ('customer_5', 'customer_1')
8485 customer_5 -14.022918526123975
resNode: customer_1 deliver_cap: 44.89536478872501 cap_limit: 40
10108 customer_5 ('customer_5', 'depot_t')
8485 customer_5 -14.022918526123975
resNode: depot_t deliver_cap: 26.201785300529195 cap_limit: 40
10109 customer_5 ('customer_5', 'customer_2')
8485 customer_5 -14.022918526123975
resNode: customer_2 deliver_cap: 29.645526482402676 cap_limit: 40
10110 customer_5 ('customer_5', 'customer_4')
8485 customer_5 -14.022918526123975
resNode: customer_4 deliver_cap: 51.38446724682899 cap_limit: 40
10111 customer_2 ('customer_2', 'customer_3')
8489 customer_2 -16.248150089119846
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
10112 customer_2 ('customer_2', 'customer_1')
8489 customer_2 -16.248150089119846
resNode: customer_1 deliver_cap: 58.71477486040292 cap_limit: 40
10113 customer_2 ('customer_2', 'depot_t')
8489 customer_2 -16.248150089119846
resNode: depot_t deliver_cap: 39.75310228820386 cap_limit: 40
10114 customer_2 ('customer_2', 'customer_4')
8489 customer_2 -16.248150089119846
resNode: customer_4 deliver_cap: 70.01670286799646 cap_limit: 40
10115 customer_2 ('customer_2', 'customer_5')
8489 customer_2 -16.248150089119846
resNode: customer_5 deliver_cap: 51.38446724682897 cap_limit: 40
10116 customer_2 ('customer_2', 'customer_3')
8509 customer_2 -18.322422667247842
resNode: customer_3 deliver_cap: 67.66219135047727 cap_limit: 40
10117 customer_2 ('customer_2', 'customer_1')
8509 customer_2 -18.322422667247842
resNode: customer_1 deliver_cap: 56.50453591432634 cap_limit: 40
10118 customer_2 ('customer_2', 'depot_t')
8509 customer_2 -18.322422667247842
resNode: depot_t deliver_cap: 37.67287739777885 cap_limit: 40
10119 customer_2 ('customer_2', 'customer_4')
8509 customer_2 -18.322422667247842
resNode: customer_4 deliver_cap: 67.4164217549652 cap_limit: 40
10120 customer_2 ('customer_2', 'customer_5')
8509 customer_2 -18.322422667247842
resNode: customer_5 deliver_cap: 48.784186133797704 cap_limit: 40
10121 customer_5 ('customer_5', 'customer_3')
8525 customer_5 -20.860187443238573
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
10122 customer_5 ('customer_5', 'customer_1')
8525 customer_5 -20.860187443238573
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10123 customer_5 ('customer_5', 'depot_t')
8525 customer_5 -20.860187443238573
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
10124 customer_5 ('customer_5', 'customer_2')
8525 customer_5 -20.860187443238573
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
10125 customer_5 ('customer_5', 'customer_4')
8525 customer_5 -20.860187443238573
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
10126 customer_2 ('customer_2', 'customer_3')
8529 customer_2 -20.82632777416588
resNode: customer_3 deliver_cap: 70.50148759501495 cap_limit: 40
10127 customer_2 ('customer_2', 'customer_1')
8529 customer_2 -20.82632777416588
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10128 customer_2 ('customer_2', 'depot_t')
8529 customer_2 -20.82632777416588
resNode: depot_t deliver_cap: 39.94431439340899 cap_limit: 40
10129 customer_2 ('customer_2', 'customer_4')
8529 customer_2 -20.82632777416588
resNode: customer_4 deliver_cap: 70.25571799950286 cap_limit: 40
10130 customer_2 ('customer_2', 'customer_5')
8529 customer_2 -20.82632777416588
resNode: customer_5 deliver_cap: 51.623482378335375 cap_limit: 40
10131 customer_2 ('customer_2', 'customer_3')
8538 customer_2 -11.567254304128099
resNode: customer_3 deliver_cap: 59.13553962231224 cap_limit: 40
10132 customer_2 ('customer_2', 'customer_1')
8538 customer_2 -11.567254304128099
resNode: customer_1 deliver_cap: 47.86946943778003 cap_limit: 40
10133 customer_2 ('customer_2', 'depot_t')
8538 customer_2 -11.567254304128099
resNode: depot_t deliver_cap: 31.85008351318268 cap_limit: 40
10134 customer_2 ('customer_2', 'customer_4')
8538 customer_2 -11.567254304128099
resNode: customer_4 deliver_cap: 58.926635466126974 cap_limit: 40
10135 customer_2 ('customer_2', 'customer_5')
8538 customer_2 -11.567254304128099
resNode: customer_5 deliver_cap: 43.0892351881346 cap_limit: 40
10136 customer_5 ('customer_5', 'customer_3')
8540 customer_5 -20.035330211858668
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
10137 customer_5 ('customer_5', 'customer_1')
8540 customer_5 -20.035330211858668
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10138 customer_5 ('customer_5', 'depot_t')
8540 customer_5 -20.035330211858668
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
10139 customer_5 ('customer_5', 'customer_2')
8540 customer_5 -20.035330211858668
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
10140 customer_5 ('customer_5', 'customer_4')
8540 customer_5 -20.035330211858668
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
10141 customer_2 ('customer_2', 'customer_3')
8549 customer_2 -13.818995840278255
resNode: customer_3 deliver_cap: 54.00434296741689 cap_limit: 40
10142 customer_2 ('customer_2', 'customer_1')
8549 customer_2 -13.818995840278255
resNode: customer_1 deliver_cap: 44.89536478872501 cap_limit: 40
10143 customer_2 ('customer_2', 'depot_t')
8549 customer_2 -13.818995840278255
resNode: depot_t deliver_cap: 26.74659869133054 cap_limit: 40
10144 customer_2 ('customer_2', 'customer_4')
8549 customer_2 -13.818995840278255
resNode: customer_4 deliver_cap: 53.758573371904816 cap_limit: 40
10145 customer_2 ('customer_2', 'customer_5')
8549 customer_2 -13.818995840278255
resNode: customer_5 deliver_cap: 35.12633775073732 cap_limit: 40
10146 customer_2 ('customer_2', 'customer_3')
8564 customer_2 -14.032680988145136
resNode: customer_3 deliver_cap: 68.92086462436917 cap_limit: 40
10147 customer_2 ('customer_2', 'customer_1')
8564 customer_2 -14.032680988145136
resNode: customer_1 deliver_cap: 58.744919884498785 cap_limit: 40
10148 customer_2 ('customer_2', 'depot_t')
8564 customer_2 -14.032680988145136
resNode: depot_t deliver_cap: 37.39208742530091 cap_limit: 40
10149 customer_2 ('customer_2', 'customer_4')
8564 customer_2 -14.032680988145136
resNode: customer_4 deliver_cap: 68.6382295895303 cap_limit: 40
10150 customer_2 ('customer_2', 'customer_5')
8564 customer_2 -14.032680988145136
resNode: customer_5 deliver_cap: 47.21115862518768 cap_limit: 40
10151 customer_2 ('customer_2', 'customer_3')
8584 customer_2 -16.530700591729644
resNode: customer_3 deliver_cap: 67.66219135047727 cap_limit: 40
10152 customer_2 ('customer_2', 'customer_1')
8584 customer_2 -16.530700591729644
resNode: customer_1 deliver_cap: 56.50453591432634 cap_limit: 40
10153 customer_2 ('customer_2', 'depot_t')
8584 customer_2 -16.530700591729644
resNode: depot_t deliver_cap: 37.67287739777885 cap_limit: 40
10154 customer_2 ('customer_2', 'customer_4')
8584 customer_2 -16.530700591729644
resNode: customer_4 deliver_cap: 67.4164217549652 cap_limit: 40
10155 customer_2 ('customer_2', 'customer_5')
8584 customer_2 -16.530700591729644
resNode: customer_5 deliver_cap: 48.784186133797704 cap_limit: 40
10156 customer_5 ('customer_5', 'customer_3')
8620 customer_5 -17.223323629041275
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
10157 customer_5 ('customer_5', 'customer_1')
8620 customer_5 -17.223323629041275
resNode: customer_1 deliver_cap: 55.88343172554058 cap_limit: 40
10158 customer_5 ('customer_5', 'depot_t')
8620 customer_5 -17.223323629041275
resNode: depot_t deliver_cap: 34.02670777271402 cap_limit: 40
10159 customer_5 ('customer_5', 'customer_2')
8620 customer_5 -17.223323629041275
resNode: customer_2 deliver_cap: 37.942445482808424 cap_limit: 40
10160 customer_5 ('customer_5', 'customer_4')
8620 customer_5 -17.223323629041275
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
10161 customer_2 ('customer_2', 'customer_3')
8628 customer_2 -13.496443013451273
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
10162 customer_2 ('customer_2', 'customer_1')
8628 customer_2 -13.496443013451273
resNode: customer_1 deliver_cap: 58.714774860402926 cap_limit: 40
10163 customer_2 ('customer_2', 'depot_t')
8628 customer_2 -13.496443013451273
resNode: depot_t deliver_cap: 39.75310228820387 cap_limit: 40
10164 customer_2 ('customer_2', 'customer_4')
8628 customer_2 -13.496443013451273
resNode: customer_4 deliver_cap: 70.01670286799649 cap_limit: 40
10165 customer_2 ('customer_2', 'customer_5')
8628 customer_2 -13.496443013451273
resNode: customer_5 deliver_cap: 51.384467246828976 cap_limit: 40
10166 customer_2 ('customer_2', 'customer_3')
8634 customer_2 -15.294035803645944
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
10167 customer_2 ('customer_2', 'customer_1')
8634 customer_2 -15.294035803645944
resNode: customer_1 deliver_cap: 53.50932560046475 cap_limit: 40
10168 customer_2 ('customer_2', 'depot_t')
8634 customer_2 -15.294035803645944
resNode: depot_t deliver_cap: 32.41827285546858 cap_limit: 40
10169 customer_2 ('customer_2', 'customer_4')
8634 customer_2 -15.294035803645944
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
10170 customer_2 ('customer_2', 'customer_5')
8634 customer_2 -15.294035803645944
resNode: customer_5 deliver_cap: 41.190225198548546 cap_limit: 40
10171 customer_2 ('customer_2', 'customer_3')
8648 customer_2 -9.839630607946194
resNode: customer_3 deliver_cap: 70.50824205902062 cap_limit: 40
10172 customer_2 ('customer_2', 'customer_1')
8648 customer_2 -9.839630607946194
resNode: customer_1 deliver_cap: 58.92367901658819 cap_limit: 40
10173 customer_2 ('customer_2', 'depot_t')
8648 customer_2 -9.839630607946194
resNode: depot_t deliver_cap: 39.94971796461353 cap_limit: 40
10174 customer_2 ('customer_2', 'customer_4')
8648 customer_2 -9.839630607946194
resNode: customer_4 deliver_cap: 70.26247246350854 cap_limit: 40
10175 customer_2 ('customer_2', 'customer_5')
8648 customer_2 -9.839630607946194
resNode: customer_5 deliver_cap: 51.63023684234105 cap_limit: 40
10176 customer_2 ('customer_2', 'customer_3')
8654 customer_2 -11.683305197299378
resNode: customer_3 deliver_cap: 63.18256623256893 cap_limit: 40
10177 customer_2 ('customer_2', 'customer_1')
8654 customer_2 -11.683305197299378
resNode: customer_1 deliver_cap: 53.755095195976835 cap_limit: 40
10178 customer_2 ('customer_2', 'depot_t')
8654 customer_2 -11.683305197299378
resNode: depot_t deliver_cap: 32.65175397120505 cap_limit: 40
10179 customer_2 ('customer_2', 'customer_4')
8654 customer_2 -11.683305197299378
resNode: customer_4 deliver_cap: 62.89993119773004 cap_limit: 40
10180 customer_2 ('customer_2', 'customer_5')
8654 customer_2 -11.683305197299378
resNode: customer_5 deliver_cap: 41.472860233387436 cap_limit: 40
10181 customer_2 ('customer_2', 'customer_3')
8664 customer_2 -12.86705249464539
resNode: customer_3 deliver_cap: 72.94721055657922 cap_limit: 40
10182 customer_2 ('customer_2', 'customer_1')
8664 customer_2 -12.86705249464539
resNode: customer_1 deliver_cap: 63.16601796593219 cap_limit: 40
10183 customer_2 ('customer_2', 'depot_t')
8664 customer_2 -12.86705249464539
resNode: depot_t deliver_cap: 39.09635871506487 cap_limit: 40
10184 customer_2 ('customer_2', 'customer_4')
8664 customer_2 -12.86705249464539
resNode: customer_4 deliver_cap: 72.62771008241351 cap_limit: 40
10185 customer_2 ('customer_2', 'customer_5')
8664 customer_2 -12.86705249464539
resNode: customer_5 deliver_cap: 48.40580377489579 cap_limit: 40
10186 customer_5 ('customer_5', 'customer_3')
8670 customer_5 -15.535685765989538
resNode: customer_3 deliver_cap: 66.4604384615007 cap_limit: 40
10187 customer_5 ('customer_5', 'customer_1')
8670 customer_5 -15.535685765989538
resNode: customer_1 deliver_cap: 60.15794161796915 cap_limit: 40
10188 customer_5 ('customer_5', 'depot_t')
8670 customer_5 -15.535685765989538
resNode: depot_t deliver_cap: 35.46994988292229 cap_limit: 40
10189 customer_5 ('customer_5', 'customer_2')
8670 customer_5 -15.535685765989538
resNode: customer_2 deliver_cap: 39.52580743882717 cap_limit: 40
10190 customer_5 ('customer_5', 'customer_4')
8670 customer_5 -15.535685765989538
resNode: customer_4 deliver_cap: 66.140937987335 cap_limit: 40
10191 customer_2 ('customer_2', 'customer_3')
8688 customer_2 -8.097762361835454
resNode: customer_3 deliver_cap: 59.13553962231223 cap_limit: 40
10192 customer_2 ('customer_2', 'customer_1')
8688 customer_2 -8.097762361835454
resNode: customer_1 deliver_cap: 47.869469437780026 cap_limit: 40
10193 customer_2 ('customer_2', 'depot_t')
8688 customer_2 -8.097762361835454
resNode: depot_t deliver_cap: 31.850083513182675 cap_limit: 40
10194 customer_2 ('customer_2', 'customer_4')
8688 customer_2 -8.097762361835454
resNode: customer_4 deliver_cap: 58.92663546612696 cap_limit: 40
10195 customer_2 ('customer_2', 'customer_5')
8688 customer_2 -8.097762361835454
resNode: customer_5 deliver_cap: 43.089235188134595 cap_limit: 40
10196 customer_5 ('customer_5', 'customer_3')
8690 customer_5 -16.565838269566026
resNode: customer_3 deliver_cap: 68.12738146993912 cap_limit: 40
10197 customer_5 ('customer_5', 'customer_1')
8690 customer_5 -16.565838269566026
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10198 customer_5 ('customer_5', 'depot_t')
8690 customer_5 -16.565838269566026
resNode: depot_t deliver_cap: 39.39950100260764 cap_limit: 40
10199 customer_5 ('customer_5', 'customer_2')
8690 customer_5 -16.565838269566026
resNode: customer_2 deliver_cap: 43.66809941586102 cap_limit: 40
10200 customer_5 ('customer_5', 'customer_4')
8690 customer_5 -16.565838269566026
resNode: customer_4 deliver_cap: 67.88161187442705 cap_limit: 40
10201 customer_2 ('customer_2', 'customer_3')
8699 customer_2 -10.349503897985613
resNode: customer_3 deliver_cap: 54.004342967416875 cap_limit: 40
10202 customer_2 ('customer_2', 'customer_1')
8699 customer_2 -10.349503897985613
resNode: customer_1 deliver_cap: 44.89536478872501 cap_limit: 40
10203 customer_2 ('customer_2', 'depot_t')
8699 customer_2 -10.349503897985613
resNode: depot_t deliver_cap: 26.746598691330536 cap_limit: 40
10204 customer_2 ('customer_2', 'customer_4')
8699 customer_2 -10.349503897985613
resNode: customer_4 deliver_cap: 53.7585733719048 cap_limit: 40
10205 customer_2 ('customer_2', 'customer_5')
8699 customer_2 -10.349503897985613
resNode: customer_5 deliver_cap: 35.126337750737314 cap_limit: 40
10206 customer_2 ('customer_2', 'customer_3')
8713 customer_2 -13.887343889580599
resNode: customer_3 deliver_cap: 70.50148759501495 cap_limit: 40
10207 customer_2 ('customer_2', 'customer_1')
8713 customer_2 -13.887343889580599
resNode: customer_1 deliver_cap: 58.91793772218337 cap_limit: 40
10208 customer_2 ('customer_2', 'depot_t')
8713 customer_2 -13.887343889580599
resNode: depot_t deliver_cap: 39.94431439340899 cap_limit: 40
10209 customer_2 ('customer_2', 'customer_4')
8713 customer_2 -13.887343889580599
resNode: customer_4 deliver_cap: 70.25571799950286 cap_limit: 40
10210 customer_2 ('customer_2', 'customer_5')
8713 customer_2 -13.887343889580599
resNode: customer_5 deliver_cap: 51.623482378335375 cap_limit: 40
10211 customer_5 ('customer_5', 'customer_3')
8720 customer_5 -15.738073558311598
resNode: customer_3 deliver_cap: 60.44457655512521 cap_limit: 40
10212 customer_5 ('customer_5', 'customer_1')
8720 customer_5 -15.738073558311598
resNode: customer_1 deliver_cap: 53.748340731971155 cap_limit: 40
10213 customer_5 ('customer_5', 'depot_t')
8720 customer_5 -15.738073558311598
resNode: depot_t deliver_cap: 31.998371328823065 cap_limit: 40
10214 customer_5 ('customer_5', 'customer_2')
8720 customer_5 -15.738073558311598
resNode: customer_2 deliver_cap: 35.807354489238996 cap_limit: 40
10215 customer_5 ('customer_5', 'customer_4')
8720 customer_5 -15.738073558311598
resNode: customer_4 deliver_cap: 60.161941520286334 cap_limit: 40
10216 customer_2 ('customer_2', 'customer_3')
8723 customer_2 -8.990443193493036
resNode: customer_3 deliver_cap: 68.27865305348341 cap_limit: 40
10217 customer_2 ('customer_2', 'customer_1')
8723 customer_2 -8.990443193493036
resNode: customer_1 deliver_cap: 57.028528361881555 cap_limit: 40

8754 customer_2 -10.613611397810203
resNode: customer_5 deliver_cap: 48.784186133797704 cap_limit: 40
10256 customer_2 ('customer_2', 'customer_3')
8759 customer_2 -9.524646666605708
resNode: customer_3 deliver_cap: 54.004342967416875 cap_limit: 40
10257 customer_2 ('customer_2', 'customer_1')
8759 customer_2 -9.524646666605708
resNode: customer_1 deliver_cap: 44.89536478872501 cap_limit: 40
10258 customer_2 ('customer_2', 'depot_t')
8759 customer_2 -9.524646666605708
resNode: depot_t deliver_cap: 26.746598691330536 cap_limit: 40
10259 customer_2 ('customer_2', 'customer_4')
8759 customer_2 -9.524646666605708
resNode: customer_4 deliver_cap: 53.7585733719048 cap_limit: 40
10260 customer_2 ('customer_2', 'customer_5')
8759 customer_2 -9.524646666605708
resNode: customer_5 deliver_cap: 35.126337750737314 cap_limit: 40
10261 customer_2 ('customer_2', 'customer_3')
8763 customer_2 -8.829313059886738
resNode: customer_3 deliver_cap: 68.92086462436917 cap_limit: 40
10262 customer_2 ('customer_2', 'customer_1')
8763 customer_2 -8.829313059886738
resNode: customer_1 deliver_cap: 58.744919884498785 cap_limit: 40
10263 customer_2 ('customer_2', 'depot_t')
8763 customer_2 -8.829313059886738
resNode: depot_t deliver_cap: 37.39208742530091 cap_limit: 40
10264 customer_2 ('customer_2', 'customer_4')
8763 customer_2 -8.829313059886738
resNode: customer_4 deliver_cap: 68.6382295895303 cap_limit: 40
10265 customer_2 ('customer_2', 'customer_5')
8763 customer_2 -8.829313059886738
resNode: customer_5 deliver_cap: 47.21115862518768 cap_limit: 40
10266 customer_2 ('customer_2', 'customer_3')
8768 customer_2 -8.821889322292002
resNode: customer_3 deliver_cap: 67.66219135047729 cap_limit: 40
10267 customer_2 ('customer_2', 'customer_1')
8768 customer_2 -8.821889322292002
resNode: customer_1 deliver_cap: 56.504535914326354 cap_limit: 40
10268 customer_2 ('customer_2', 'depot_t')
8768 customer_2 -8.821889322292002
resNode: depot_t deliver_cap: 37.672877397778855 cap_limit: 40
10269 customer_2 ('customer_2', 'customer_4')
8768 customer_2 -8.821889322292002
resNode: customer_4 deliver_cap: 67.41642175496521 cap_limit: 40
10270 customer_2 ('customer_2', 'customer_5')
8768 customer_2 -8.821889322292002
resNode: customer_5 deliver_cap: 48.78418613379771 cap_limit: 40
10271 customer_5 ('customer_5', 'customer_3')
8775 customer_5 -12.565264723749396
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
10272 customer_5 ('customer_5', 'customer_1')
8775 customer_5 -12.565264723749396
resNode: customer_1 deliver_cap: 55.88343172554058 cap_limit: 40
10273 customer_5 ('customer_5', 'depot_t')
8775 customer_5 -12.565264723749396
resNode: depot_t deliver_cap: 34.02670777271402 cap_limit: 40
10274 customer_5 ('customer_5', 'customer_2')
8775 customer_5 -12.565264723749396
resNode: customer_2 deliver_cap: 37.942445482808424 cap_limit: 40
10275 customer_5 ('customer_5', 'customer_4')
8775 customer_5 -12.565264723749396
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
10276 customer_2 ('customer_2', 'customer_3')
8779 customer_2 -11.399566446396053
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
10277 customer_2 ('customer_2', 'customer_1')
8779 customer_2 -11.399566446396053
resNode: customer_1 deliver_cap: 53.50932560046475 cap_limit: 40
10278 customer_2 ('customer_2', 'depot_t')
8779 customer_2 -11.399566446396053
resNode: depot_t deliver_cap: 32.41827285546858 cap_limit: 40
10279 customer_2 ('customer_2', 'customer_4')
8779 customer_2 -11.399566446396053
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
10280 customer_2 ('customer_2', 'customer_5')
8779 customer_2 -11.399566446396053
resNode: customer_5 deliver_cap: 41.190225198548546 cap_limit: 40
10281 customer_2 ('customer_2', 'customer_3')
8783 customer_2 -7.72739344117147
resNode: customer_3 deliver_cap: 63.18256623256893 cap_limit: 40
10282 customer_2 ('customer_2', 'customer_1')
8783 customer_2 -7.72739344117147
resNode: customer_1 deliver_cap: 53.755095195976835 cap_limit: 40
10283 customer_2 ('customer_2', 'depot_t')
8783 customer_2 -7.72739344117147
resNode: depot_t deliver_cap: 32.65175397120505 cap_limit: 40
10284 customer_2 ('customer_2', 'customer_4')
8783 customer_2 -7.72739344117147
resNode: customer_4 deliver_cap: 62.89993119773004 cap_limit: 40
10285 customer_2 ('customer_2', 'customer_5')
8783 customer_2 -7.72739344117147
resNode: customer_5 deliver_cap: 41.472860233387436 cap_limit: 40
10286 customer_5 ('customer_5', 'customer_3')
8785 customer_5 -12.34336355790361
resNode: customer_3 deliver_cap: 66.46043846150069 cap_limit: 40
10287 customer_5 ('customer_5', 'customer_1')
8785 customer_5 -12.34336355790361
resNode: customer_1 deliver_cap: 60.15794161796915 cap_limit: 40
10288 customer_5 ('customer_5', 'depot_t')
8785 customer_5 -12.34336355790361
resNode: depot_t deliver_cap: 35.46994988292229 cap_limit: 40
10289 customer_5 ('customer_5', 'customer_2')
8785 customer_5 -12.34336355790361
resNode: customer_2 deliver_cap: 39.525807438827165 cap_limit: 40
10290 customer_5 ('customer_5', 'customer_4')
8785 customer_5 -12.34336355790361
resNode: customer_4 deliver_cap: 66.140937987335 cap_limit: 40
10291 customer_2 ('customer_2', 'customer_3')
8788 customer_2 -6.055154724313068
resNode: customer_3 deliver_cap: 54.004342967416875 cap_limit: 40
10292 customer_2 ('customer_2', 'customer_1')
8788 customer_2 -6.055154724313068
resNode: customer_1 deliver_cap: 44.89536478872501 cap_limit: 40
10293 customer_2 ('customer_2', 'depot_t')
8788 customer_2 -6.055154724313068
resNode: depot_t deliver_cap: 26.746598691330536 cap_limit: 40
10294 customer_2 ('customer_2', 'customer_4')
8788 customer_2 -6.055154724313068
resNode: customer_4 deliver_cap: 53.7585733719048 cap_limit: 40
10295 customer_2 ('customer_2', 'customer_5')
8788 customer_2 -6.055154724313068
resNode: customer_5 deliver_cap: 35.126337750737314 cap_limit: 40
10296 customer_5 ('customer_5', 'customer_3')
8790 customer_5 -11.613787401412083
resNode: customer_3 deliver_cap: 60.44457655512521 cap_limit: 40
10297 customer_5 ('customer_5', 'customer_1')
8790 customer_5 -11.613787401412083
resNode: customer_1 deliver_cap: 53.748340731971155 cap_limit: 40
10298 customer_5 ('customer_5', 'depot_t')
8790 customer_5 -11.613787401412083
resNode: depot_t deliver_cap: 31.998371328823065 cap_limit: 40
10299 customer_5 ('customer_5', 'customer_2')
8790 customer_5 -11.613787401412083
resNode: customer_2 deliver_cap: 35.807354489238996 cap_limit: 40
10300 customer_5 ('customer_5', 'customer_4')
8790 customer_5 -11.613787401412083
resNode: customer_4 deliver_cap: 60.161941520286334 cap_limit: 40
10301 customer_3 ('customer_3', 'customer_1')
8791 customer_3 -7.949191457690835
resNode: customer_1 deliver_cap: 51.525506190439614 cap_limit: 40
10302 customer_3 ('customer_3', 'depot_t')
8791 customer_3 -7.949191457690835
resNode: depot_t deliver_cap: 34.260188888450486 cap_limit: 40
10303 customer_3 ('customer_3', 'customer_2')
8791 customer_3 -7.949191457690835
resNode: customer_2 deliver_cap: 38.188215078320496 cap_limit: 40
10304 customer_3 ('customer_3', 'customer_4')
8791 customer_3 -7.949191457690835
resNode: customer_4 deliver_cap: 47.21115862518768 cap_limit: 40
10305 customer_3 ('customer_3', 'customer_5')
8791 customer_3 -7.949191457690835
resNode: customer_5 deliver_cap: 41.472860233387436 cap_limit: 40
10306 customer_1 ('customer_1', 'customer_3')
8792 customer_1 -5.5190658159599835
resNode: customer_3 deliver_cap: 49.40064783680384 cap_limit: 40
10307 customer_1 ('customer_1', 'depot_t')
8792 customer_1 -5.5190658159599835
resNode: depot_t deliver_cap: 27.901671983437808 cap_limit: 40
10308 customer_1 ('customer_1', 'customer_2')
8792 customer_1 -5.5190658159599835
resNode: customer_2 deliver_cap: 29.645526482402673 cap_limit: 40
10309 customer_1 ('customer_1', 'customer_4')
8792 customer_1 -5.5190658159599835
resNode: customer_4 deliver_cap: 48.78418613379772 cap_limit: 40
10310 customer_1 ('customer_1', 'customer_5')
8792 customer_1 -5.5190658159599835
resNode: customer_5 deliver_cap: 35.126337750737314 cap_limit: 40
10311 customer_4 ('customer_4', 'customer_3')
8794 customer_4 -7.907205818457523
resNode: customer_3 deliver_cap: 47.21115862518768 cap_limit: 40
10312 customer_4 ('customer_4', 'customer_1')
8794 customer_4 -7.907205818457523
resNode: customer_1 deliver_cap: 50.90904448743348 cap_limit: 40
10313 customer_4 ('customer_4', 'depot_t')
8794 customer_4 -7.907205818457523
resNode: depot_t deliver_cap: 34.02670777271402 cap_limit: 40
10314 customer_4 ('customer_4', 'customer_2')
8794 customer_4 -7.907205818457523
resNode: customer_2 deliver_cap: 37.942445482808424 cap_limit: 40
10315 customer_4 ('customer_4', 'customer_5')
8794 customer_4 -7.907205818457523
resNode: customer_5 deliver_cap: 41.190225198548546 cap_limit: 40
10316 customer_5 ('customer_5', 'customer_3')
8795 customer_5 -4.8126697753694305
resNode: customer_3 deliver_cap: 41.472860233387436 cap_limit: 40
10317 customer_5 ('customer_5', 'customer_1')
8795 customer_5 -4.8126697753694305
resNode: customer_1 deliver_cap: 37.251196104373086 cap_limit: 40
10318 customer_5 ('customer_5', 'depot_t')
8795 customer_5 -4.8126697753694305
resNode: depot_t deliver_cap: 16.3260839326049 cap_limit: 40
10319 customer_5 ('customer_5', 'customer_2')
8795 customer_5 -4.8126697753694305
resNode: customer_2 deliver_cap: 19.310209861640928 cap_limit: 40
10320 customer_5 ('customer_5', 'customer_4')
8795 customer_5 -4.8126697753694305
resNode: customer_4 deliver_cap: 41.190225198548546 cap_limit: 40
10321 customer_2 ('customer_2', 'customer_3')
8799 customer_2 -7.673119322162552
resNode: customer_3 deliver_cap: 62.89993119773004 cap_limit: 40
10322 customer_2 ('customer_2', 'customer_1')
8799 customer_2 -7.673119322162552
resNode: customer_1 deliver_cap: 53.50932560046475 cap_limit: 40
10323 customer_2 ('customer_2', 'depot_t')
8799 customer_2 -7.673119322162552
resNode: depot_t deliver_cap: 32.41827285546857 cap_limit: 40
10324 customer_2 ('customer_2', 'customer_4')
8799 customer_2 -7.673119322162552
resNode: customer_4 deliver_cap: 62.61729616289115 cap_limit: 40
10325 customer_2 ('customer_2', 'customer_5')
8799 customer_2 -7.673119322162552
resNode: customer_5 deliver_cap: 41.19022519854854 cap_limit: 40
10326 customer_5 ('customer_5', 'customer_3')
8800 customer_5 -12.243007639736174
resNode: customer_3 deliver_cap: 66.14093798733498 cap_limit: 40
10327 customer_5 ('customer_5', 'customer_1')
8800 customer_5 -12.243007639736174
resNode: customer_1 deliver_cap: 59.875306583130254 cap_limit: 40
10328 customer_5 ('customer_5', 'depot_t')
8800 customer_5 -12.243007639736174
resNode: depot_t deliver_cap: 35.199603327859 cap_limit: 40
10329 customer_5 ('customer_5', 'customer_2')
8800 customer_5 -12.243007639736174
resNode: customer_2 deliver_cap: 39.243172403988275 cap_limit: 40
10330 customer_5 ('customer_5', 'customer_4')
8800 customer_5 -12.243007639736174
resNode: customer_4 deliver_cap: 65.82143751316929 cap_limit: 40
10331 customer_2 ('customer_2', 'customer_3')
8809 customer_2 -12.817898575542973
resNode: customer_3 deliver_cap: 72.94721055657922 cap_limit: 40
10332 customer_2 ('customer_2', 'customer_1')
8809 customer_2 -12.817898575542973
resNode: customer_1 deliver_cap: 63.16601796593219 cap_limit: 40
10333 customer_2 ('customer_2', 'depot_t')
8809 customer_2 -12.817898575542973
resNode: depot_t deliver_cap: 39.09635871506487 cap_limit: 40
10334 customer_2 ('customer_2', 'customer_4')
8809 customer_2 -12.817898575542973
resNode: customer_4 deliver_cap: 72.62771008241351 cap_limit: 40
10335 customer_2 ('customer_2', 'customer_5')
8809 customer_2 -12.817898575542973
resNode: customer_5 deliver_cap: 48.40580377489579 cap_limit: 40
10336 customer_2 ('customer_2', 'customer_3')
8823 customer_2 -9.769995889217775
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
10337 customer_2 ('customer_2', 'customer_1')
8823 customer_2 -9.769995889217775
resNode: customer_1 deliver_cap: 58.714774860402926 cap_limit: 40
10338 customer_2 ('customer_2', 'depot_t')
8823 customer_2 -9.769995889217775
resNode: depot_t deliver_cap: 39.75310228820387 cap_limit: 40
10339 customer_2 ('customer_2', 'customer_4')
8823 customer_2 -9.769995889217775
resNode: customer_4 deliver_cap: 70.01670286799649 cap_limit: 40
10340 customer_2 ('customer_2', 'customer_5')
8823 customer_2 -9.769995889217775
resNode: customer_5 deliver_cap: 51.384467246828976 cap_limit: 40
10341 customer_2 ('customer_2', 'customer_3')
8829 customer_2 -11.567588679412443
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
10342 customer_2 ('customer_2', 'customer_1')
8829 customer_2 -11.567588679412443
resNode: customer_1 deliver_cap: 53.50932560046475 cap_limit: 40
10343 customer_2 ('customer_2', 'depot_t')
8829 customer_2 -11.567588679412443
resNode: depot_t deliver_cap: 32.41827285546858 cap_limit: 40
10344 customer_2 ('customer_2', 'customer_4')
8829 customer_2 -11.567588679412443
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
10345 customer_2 ('customer_2', 'customer_5')
8829 customer_2 -11.567588679412443
resNode: customer_5 deliver_cap: 41.190225198548546 cap_limit: 40
10346 customer_5 ('customer_5', 'customer_3')
8835 customer_5 -15.373887448944084
resNode: customer_3 deliver_cap: 66.140937987335 cap_limit: 40
10347 customer_5 ('customer_5', 'customer_1')
8835 customer_5 -15.373887448944084
resNode: customer_1 deliver_cap: 59.875306583130254 cap_limit: 40
10348 customer_5 ('customer_5', 'depot_t')
8835 customer_5 -15.373887448944084
resNode: depot_t deliver_cap: 35.19960332785901 cap_limit: 40
10349 customer_5 ('customer_5', 'customer_2')
8835 customer_5 -15.373887448944084
resNode: customer_2 deliver_cap: 39.24317240398828 cap_limit: 40
10350 customer_5 ('customer_5', 'customer_4')
8835 customer_5 -15.373887448944084
resNode: customer_4 deliver_cap: 65.82143751316929 cap_limit: 40
10351 customer_2 ('customer_2', 'customer_3')
8854 customer_2 -16.4940874077174
resNode: customer_3 deliver_cap: 72.94721055657922 cap_limit: 40
10352 customer_2 ('customer_2', 'customer_1')
8854 customer_2 -16.4940874077174
resNode: customer_1 deliver_cap: 63.16601796593219 cap_limit: 40
10353 customer_2 ('customer_2', 'depot_t')
8854 customer_2 -16.4940874077174
resNode: depot_t deliver_cap: 39.09635871506487 cap_limit: 40
10354 customer_2 ('customer_2', 'customer_4')
8854 customer_2 -16.4940874077174
resNode: customer_4 deliver_cap: 72.62771008241351 cap_limit: 40
10355 customer_2 ('customer_2', 'customer_5')
8854 customer_2 -16.4940874077174
resNode: customer_5 deliver_cap: 48.40580377489579 cap_limit: 40
10356 customer_2 ('customer_2', 'customer_3')
8879 customer_2 -18.128877436913235
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
10357 customer_2 ('customer_2', 'customer_1')
8879 customer_2 -18.128877436913235
resNode: customer_1 deliver_cap: 58.71477486040292 cap_limit: 40
10358 customer_2 ('customer_2', 'depot_t')
8879 customer_2 -18.128877436913235
resNode: depot_t deliver_cap: 39.75310228820386 cap_limit: 40
10359 customer_2 ('customer_2', 'customer_4')
8879 customer_2 -18.128877436913235
resNode: customer_4 deliver_cap: 70.01670286799646 cap_limit: 40
10360 customer_2 ('customer_2', 'customer_5')
8879 customer_2 -18.128877436913235
resNode: customer_5 deliver_cap: 51.38446724682897 cap_limit: 40
10361 customer_2 ('customer_2', 'customer_3')
8893 customer_2 -13.664465246467664
resNode: customer_3 deliver_cap: 70.26247246350854 cap_limit: 40
10362 customer_2 ('customer_2', 'customer_1')
8893 customer_2 -13.664465246467664
resNode: customer_1 deliver_cap: 58.714774860402926 cap_limit: 40
10363 customer_2 ('customer_2', 'depot_t')
8893 customer_2 -13.664465246467664
resNode: depot_t deliver_cap: 39.75310228820387 cap_limit: 40
10364 customer_2 ('customer_2', 'customer_4')
8893 customer_2 -13.664465246467664
resNode: customer_4 deliver_cap: 70.01670286799649 cap_limit: 40
10365 customer_2 ('customer_2', 'customer_5')
8893 customer_2 -13.664465246467664
resNode: customer_5 deliver_cap: 51.384467246828976 cap_limit: 40
10366 customer_2 ('customer_2', 'customer_3')
8899 customer_2 -15.462058036662336
resNode: customer_3 deliver_cap: 62.89993119773005 cap_limit: 40
10367 customer_2 ('customer_2', 'customer_1')
8899 customer_2 -15.462058036662336
resNode: customer_1 deliver_cap: 53.50932560046475 cap_limit: 40
10368 customer_2 ('customer_2', 'depot_t')
8899 customer_2 -15.462058036662336
resNode: depot_t deliver_cap: 32.41827285546858 cap_limit: 40
10369 customer_2 ('customer_2', 'customer_4')
8899 customer_2 -15.462058036662336
resNode: customer_4 deliver_cap: 62.617296162891165 cap_limit: 40
10370 customer_2 ('customer_2', 'customer_5')
8899 customer_2 -15.462058036662336
resNode: customer_5 deliver_cap: 41.190225198548546 cap_limit: 40
10371 customer_5 ('customer_5', 'customer_3')
8910 customer_5 -18.50476725815199
resNode: customer_3 deliver_cap: 66.140937987335 cap_limit: 40
10372 customer_5 ('customer_5', 'customer_1')
8910 customer_5 -18.50476725815199
resNode: customer_1 deliver_cap: 59.875306583130254 cap_limit: 40
10373 customer_5 ('customer_5', 'depot_t')
8910 customer_5 -18.50476725815199
resNode: depot_t deliver_cap: 35.19960332785901 cap_limit: 40
10374 customer_5 ('customer_5', 'customer_2')
8910 customer_5 -18.50476725815199
resNode: customer_2 deliver_cap: 39.24317240398828 cap_limit: 40
10375 customer_5 ('customer_5', 'customer_4')
8910 customer_5 -18.50476725815199
resNode: customer_4 deliver_cap: 65.82143751316929 cap_limit: 40
10376 customer_2 ('customer_2', 'customer_3')
8924 customer_2 -23.851980365543
resNode: customer_3 deliver_cap: 70.51117161788906 cap_limit: 40
10377 customer_2 ('customer_2', 'customer_1')
8924 customer_2 -23.851980365543
resNode: customer_1 deliver_cap: 60.45169508299608 cap_limit: 40
10378 customer_2 ('customer_2', 'depot_t')
8924 customer_2 -23.851980365543
resNode: depot_t deliver_cap: 38.188215078320496 cap_limit: 40
10379 customer_2 ('customer_2', 'customer_4')
8924 customer_2 -23.851980365543
resNode: customer_4 deliver_cap: 70.21624810327455 cap_limit: 40
10380 customer_2 ('customer_2', 'customer_5')
8924 customer_2 -23.851980365543
resNode: customer_5 deliver_cap: 47.857565357873575 cap_limit: 40
10381 customer_2 ('customer_2', 'customer_3')
8953 customer_2 -16.909382361147024
resNode: customer_3 deliver_cap: 62.56420997349345 cap_limit: 40
10382 customer_2 ('customer_2', 'customer_1')
8953 customer_2 -16.909382361147024
resNode: customer_1 deliver_cap: 46.389337444695734 cap_limit: 40
10383 customer_2 ('customer_2', 'depot_t')
8953 customer_2 -16.909382361147024
resNode: depot_t deliver_cap: 33.481035474360816 cap_limit: 40
10384 customer_2 ('customer_2', 'customer_4')
8953 customer_2 -16.909382361147024
resNode: customer_4 deliver_cap: 62.41674821618621 cap_limit: 40
10385 customer_2 ('customer_2', 'customer_5')
8953 customer_2 -16.909382361147024
resNode: customer_5 deliver_cap: 51.237406843485715 cap_limit: 40
10386 customer_2 ('customer_2', 'customer_3')
8959 customer_2 -26.640765192916177
resNode: customer_3 deliver_cap: 66.53010237862456 cap_limit: 40
10387 customer_2 ('customer_2', 'customer_1')
8959 customer_2 -26.640765192916177
resNode: customer_1 deliver_cap: 52.51232185566717 cap_limit: 40
10388 customer_2 ('customer_2', 'depot_t')
8959 customer_2 -26.640765192916177
resNode: depot_t deliver_cap: 37.47463971253514 cap_limit: 40
10389 customer_2 ('customer_2', 'customer_4')
8959 customer_2 -26.640765192916177
resNode: customer_4 deliver_cap: 66.3457751819905 cap_limit: 40
10390 customer_2 ('customer_2', 'customer_5')
8959 customer_2 -26.640765192916177
resNode: customer_5 deliver_cap: 52.37159846611488 cap_limit: 40
10391 customer_2 ('customer_2', 'customer_3')
8973 customer_2 -22.1763530024706
resNode: customer_3 deliver_cap: 66.53010237862456 cap_limit: 40
10392 customer_2 ('customer_2', 'customer_1')
8973 customer_2 -22.1763530024706

resNode: depot_t deliver_cap: 35.31077906786751 cap_limit: 40
10464 customer_5 ('customer_5', 'customer_2')
9185 customer_5 -25.713060036073202
resNode: customer_2 deliver_cap: 39.42662133794201 cap_limit: 40
10465 customer_5 ('customer_5', 'customer_4')
9185 customer_5 -25.713060036073202
resNode: customer_4 deliver_cap: 62.16858514630898 cap_limit: 40
10466 customer_2 ('customer_2', 'customer_3')
9203 customer_2 -19.533997429306105
resNode: customer_3 deliver_cap: 65.447221167274 cap_limit: 40
10467 customer_2 ('customer_2', 'customer_1')
9203 customer_2 -19.533997429306105
resNode: customer_1 deliver_cap: 51.64601688658672 cap_limit: 40
10468 customer_2 ('customer_2', 'depot_t')
9203 customer_2 -19.533997429306105
resNode: depot_t deliver_cap: 36.680526824211384 cap_limit: 40
10469 customer_2 ('customer_2', 'customer_4')
9203 customer_2 -19.533997429306105
resNode: customer_4 deliver_cap: 65.26289397063994 cap_limit: 40
10470 customer_2 ('customer_2', 'customer_5')
9203 customer_2 -19.533997429306105
resNode: customer_5 deliver_cap: 51.28871725476431 cap_limit: 40
10471 customer_2 ('customer_2', 'customer_3')
9209 customer_2 -25.49211193176494
resNode: customer_3 deliver_cap: 64.52647329483807 cap_limit: 40
10472 customer_2 ('customer_2', 'customer_1')
9209 customer_2 -25.49211193176494
resNode: customer_1 deliver_cap: 52.88236101999113 cap_limit: 40
10473 customer_2 ('customer_2', 'depot_t')
9209 customer_2 -25.49211193176494
resNode: depot_t deliver_cap: 35.78749078481868 cap_limit: 40
10474 customer_2 ('customer_2', 'customer_4')
9209 customer_2 -25.49211193176494
resNode: customer_4 deliver_cap: 64.30528065887721 cap_limit: 40
10475 customer_2 ('customer_2', 'customer_5')
9209 customer_2 -25.49211193176494
resNode: customer_5 deliver_cap: 47.53626859982646 cap_limit: 40
10476 customer_2 ('customer_2', 'customer_3')
9238 customer_2 -16.06450548701347
resNode: customer_3 deliver_cap: 65.447221167274 cap_limit: 40
10477 customer_2 ('customer_2', 'customer_1')
9238 customer_2 -16.06450548701347
resNode: customer_1 deliver_cap: 51.64601688658672 cap_limit: 40
10478 customer_2 ('customer_2', 'depot_t')
9238 customer_2 -16.06450548701347
resNode: depot_t deliver_cap: 36.680526824211384 cap_limit: 40
10479 customer_2 ('customer_2', 'customer_4')
9238 customer_2 -16.06450548701347
resNode: customer_4 deliver_cap: 65.26289397063994 cap_limit: 40
10480 customer_2 ('customer_2', 'customer_5')
9238 customer_2 -16.06450548701347
resNode: customer_5 deliver_cap: 51.288717254764315 cap_limit: 40
10481 customer_2 ('customer_2', 'customer_3')
9244 customer_2 -22.022619989472304
resNode: customer_3 deliver_cap: 64.52647329483808 cap_limit: 40
10482 customer_2 ('customer_2', 'customer_1')
9244 customer_2 -22.022619989472304
resNode: customer_1 deliver_cap: 52.88236101999114 cap_limit: 40
10483 customer_2 ('customer_2', 'depot_t')
9244 customer_2 -22.022619989472304
resNode: depot_t deliver_cap: 35.78749078481869 cap_limit: 40
10484 customer_2 ('customer_2', 'customer_4')
9244 customer_2 -22.022619989472304
resNode: customer_4 deliver_cap: 64.30528065887721 cap_limit: 40
10485 customer_2 ('customer_2', 'customer_5')
9244 customer_2 -22.022619989472304
resNode: customer_5 deliver_cap: 47.536268599826464 cap_limit: 40
10486 customer_1 ('customer_1', 'customer_3')
9262 customer_1 -14.613319246334598
resNode: customer_3 deliver_cap: 61.99444981931422 cap_limit: 40
10487 customer_1 ('customer_1', 'depot_t')
9262 customer_1 -14.613319246334598
resNode: depot_t deliver_cap: 37.47463971253514 cap_limit: 40
10488 customer_1 ('customer_1', 'customer_2')
9262 customer_1 -14.613319246334598
resNode: customer_2 deliver_cap: 40.88142514094743 cap_limit: 40
10489 customer_1 ('customer_1', 'customer_4')
9262 customer_1 -14.613319246334598
resNode: customer_4 deliver_cap: 61.53210354205962 cap_limit: 40
10490 customer_1 ('customer_1', 'customer_5')
9262 customer_1 -14.613319246334598
resNode: customer_5 deliver_cap: 51.28871725476432 cap_limit: 40
10491 customer_5 ('customer_5', 'customer_3')
9265 customer_5 -21.24864784562763
resNode: customer_3 deliver_cap: 62.389777782269846 cap_limit: 40
10492 customer_5 ('customer_5', 'customer_1')
9265 customer_5 -21.24864784562763
resNode: customer_1 deliver_cap: 52.88236101999114 cap_limit: 40
10493 customer_5 ('customer_5', 'depot_t')
9265 customer_5 -21.24864784562763
resNode: depot_t deliver_cap: 35.310779067867514 cap_limit: 40
10494 customer_5 ('customer_5', 'customer_2')
9265 customer_5 -21.24864784562763
resNode: customer_2 deliver_cap: 39.42662133794202 cap_limit: 40
10495 customer_5 ('customer_5', 'customer_4')
9265 customer_5 -21.24864784562763
resNode: customer_4 deliver_cap: 62.16858514630898 cap_limit: 40
10496 customer_2 ('customer_2', 'customer_3')
9269 customer_2 -21.197762758092402
resNode: customer_3 deliver_cap: 64.52647329483808 cap_limit: 40
10497 customer_2 ('customer_2', 'customer_1')
9269 customer_2 -21.197762758092402
resNode: customer_1 deliver_cap: 52.882361019991144 cap_limit: 40
10498 customer_2 ('customer_2', 'depot_t')
9269 customer_2 -21.197762758092402
resNode: depot_t deliver_cap: 35.787490784818694 cap_limit: 40
10499 customer_2 ('customer_2', 'customer_4')
9269 customer_2 -21.197762758092402
resNode: customer_4 deliver_cap: 64.30528065887722 cap_limit: 40
10500 customer_2 ('customer_2', 'customer_5')
9269 customer_2 -21.197762758092402
resNode: customer_5 deliver_cap: 47.53626859982647 cap_limit: 40
10501 customer_2 ('customer_2', 'customer_3')
9288 customer_2 -17.72827081579976
resNode: customer_3 deliver_cap: 64.52647329483808 cap_limit: 40
10502 customer_2 ('customer_2', 'customer_1')
9288 customer_2 -17.72827081579976
resNode: customer_1 deliver_cap: 52.882361019991144 cap_limit: 40
10503 customer_2 ('customer_2', 'depot_t')
9288 customer_2 -17.72827081579976
resNode: depot_t deliver_cap: 35.787490784818694 cap_limit: 40
10504 customer_2 ('customer_2', 'customer_4')
9288 customer_2 -17.72827081579976
resNode: customer_4 deliver_cap: 64.30528065887722 cap_limit: 40
10505 customer_2 ('customer_2', 'customer_5')
9288 customer_2 -17.72827081579976
resNode: customer_5 deliver_cap: 47.53626859982647 cap_limit: 40
10506 customer_1 ('customer_1', 'customer_3')
9292 customer_1 -17.15608586706832
resNode: customer_3 deliver_cap: 60.38314767728635 cap_limit: 40
10507 customer_1 ('customer_1', 'depot_t')
9292 customer_1 -17.15608586706832
resNode: depot_t deliver_cap: 36.798179915412554 cap_limit: 40
10508 customer_1 ('customer_1', 'customer_2')
9292 customer_1 -17.15608586706832
resNode: customer_2 deliver_cap: 39.426621337942024 cap_limit: 40
10509 customer_1 ('customer_1', 'customer_4')
9292 customer_1 -17.15608586706832
resNode: customer_4 deliver_cap: 59.828332144580834 cap_limit: 40
10510 customer_1 ('customer_1', 'customer_5')
9292 customer_1 -17.15608586706832
resNode: customer_5 deliver_cap: 47.53626859982647 cap_limit: 40
10511 customer_5 ('customer_5', 'customer_3')
9295 customer_5 -20.20918425162734
resNode: customer_3 deliver_cap: 56.44284995577567 cap_limit: 40
10512 customer_5 ('customer_5', 'customer_1')
9295 customer_5 -20.20918425162734
resNode: customer_1 deliver_cap: 49.44864111809867 cap_limit: 40
10513 customer_5 ('customer_5', 'depot_t')
9295 customer_5 -20.20918425162734
resNode: depot_t deliver_cap: 29.645526482402676 cap_limit: 40
10514 customer_5 ('customer_5', 'customer_2')
9295 customer_5 -20.20918425162734
resNode: customer_2 deliver_cap: 33.30175349963973 cap_limit: 40
10515 customer_5 ('customer_5', 'customer_4')
9295 customer_5 -20.20918425162734
resNode: customer_4 deliver_cap: 56.18479188048799 cap_limit: 40
10516 customer_2 ('customer_2', 'customer_3')
9358 customer_2 -15.894442470240442
resNode: customer_3 deliver_cap: 65.447221167274 cap_limit: 40
10517 customer_2 ('customer_2', 'customer_1')
9358 customer_2 -15.894442470240442
resNode: customer_1 deliver_cap: 51.64601688658672 cap_limit: 40
10518 customer_2 ('customer_2', 'depot_t')
9358 customer_2 -15.894442470240442
resNode: depot_t deliver_cap: 36.680526824211384 cap_limit: 40
10519 customer_2 ('customer_2', 'customer_4')
9358 customer_2 -15.894442470240442
resNode: customer_4 deliver_cap: 65.26289397063994 cap_limit: 40
10520 customer_2 ('customer_2', 'customer_5')
9358 customer_2 -15.894442470240442
resNode: customer_5 deliver_cap: 51.288717254764315 cap_limit: 40
10521 customer_2 ('customer_2', 'customer_3')
9364 customer_2 -21.852556972699276
resNode: customer_3 deliver_cap: 64.52647329483808 cap_limit: 40
10522 customer_2 ('customer_2', 'customer_1')
9364 customer_2 -21.852556972699276
resNode: customer_1 deliver_cap: 52.88236101999114 cap_limit: 40
10523 customer_2 ('customer_2', 'depot_t')
9364 customer_2 -21.852556972699276
resNode: depot_t deliver_cap: 35.78749078481869 cap_limit: 40
10524 customer_2 ('customer_2', 'customer_4')
9364 customer_2 -21.852556972699276
resNode: customer_4 deliver_cap: 64.30528065887721 cap_limit: 40
10525 customer_2 ('customer_2', 'customer_5')
9364 customer_2 -21.852556972699276
resNode: customer_5 deliver_cap: 47.536268599826464 cap_limit: 40
10526 customer_2 ('customer_2', 'customer_3')
9383 customer_2 -17.38814478225371
resNode: customer_3 deliver_cap: 64.52647329483808 cap_limit: 40
10527 customer_2 ('customer_2', 'customer_1')
9383 customer_2 -17.38814478225371
resNode: customer_1 deliver_cap: 52.882361019991144 cap_limit: 40
10528 customer_2 ('customer_2', 'depot_t')
9383 customer_2 -17.38814478225371
resNode: depot_t deliver_cap: 35.787490784818694 cap_limit: 40
10529 customer_2 ('customer_2', 'customer_4')
9383 customer_2 -17.38814478225371
resNode: customer_4 deliver_cap: 64.30528065887722 cap_limit: 40
10530 customer_2 ('customer_2', 'customer_5')
9383 customer_2 -17.38814478225371
resNode: customer_5 deliver_cap: 47.53626859982647 cap_limit: 40
10531 customer_2 ('customer_2', 'customer_3')
9389 customer_2 -19.84371125823987
resNode: customer_3 deliver_cap: 58.935661387105284 cap_limit: 40
10532 customer_2 ('customer_2', 'customer_1')
9389 customer_2 -19.84371125823987
resNode: customer_1 deliver_cap: 49.44864111809868 cap_limit: 40
10533 customer_2 ('customer_2', 'depot_t')
9389 customer_2 -19.84371125823987
resNode: depot_t deliver_cap: 30.224390710129104 cap_limit: 40
10534 customer_2 ('customer_2', 'customer_4')
9389 customer_2 -19.84371125823987
resNode: customer_4 deliver_cap: 58.67760331181761 cap_limit: 40
10535 customer_2 ('customer_2', 'customer_5')
9389 customer_2 -19.84371125823987
resNode: customer_5 deliver_cap: 39.113755909591745 cap_limit: 40
10536 customer_5 ('customer_5', 'customer_3')
9430 customer_5 -24.03996395449154
resNode: customer_3 deliver_cap: 68.18454083938559 cap_limit: 40
10537 customer_5 ('customer_5', 'customer_1')
9430 customer_5 -24.03996395449154
resNode: customer_1 deliver_cap: 60.90870458313516 cap_limit: 40
10538 customer_5 ('customer_5', 'depot_t')
9430 customer_5 -24.03996395449154
resNode: depot_t deliver_cap: 37.942445482808424 cap_limit: 40
10539 customer_5 ('customer_5', 'customer_2')
9430 customer_5 -24.03996395449154
resNode: customer_2 deliver_cap: 42.0706690282664 cap_limit: 40
10540 customer_5 ('customer_5', 'customer_4')
9430 customer_5 -24.03996395449154
resNode: customer_4 deliver_cap: 67.8896173247711 cap_limit: 40
10541 customer_2 ('customer_2', 'customer_3')
9439 customer_2 -21.325922963722054
resNode: customer_3 deliver_cap: 68.18454083938559 cap_limit: 40
10542 customer_2 ('customer_2', 'customer_1')
9439 customer_2 -21.325922963722054
resNode: customer_1 deliver_cap: 58.415893151805555 cap_limit: 40
10543 customer_2 ('customer_2', 'depot_t')
9439 customer_2 -21.325922963722054
resNode: depot_t deliver_cap: 36.24935609623428 cap_limit: 40
10544 customer_2 ('customer_2', 'customer_4')
9439 customer_2 -21.325922963722054
resNode: customer_4 deliver_cap: 67.8896173247711 cap_limit: 40
10545 customer_2 ('customer_2', 'customer_5')
9439 customer_2 -21.325922963722054
resNode: customer_5 deliver_cap: 45.53093457937011 cap_limit: 40
10546 customer_2 ('customer_2', 'customer_3')
9454 customer_2 -17.779706876197412
resNode: customer_3 deliver_cap: 68.47946435400007 cap_limit: 40
10547 customer_2 ('customer_2', 'customer_1')
9454 customer_2 -17.779706876197412
resNode: customer_1 deliver_cap: 58.673951227093234 cap_limit: 40
10548 customer_2 ('customer_2', 'depot_t')
9454 customer_2 -17.779706876197412
resNode: depot_t deliver_cap: 36.49512569174635 cap_limit: 40
10549 customer_2 ('customer_2', 'customer_4')
9454 customer_2 -17.779706876197412
resNode: customer_4 deliver_cap: 68.18454083938559 cap_limit: 40
10550 customer_2 ('customer_2', 'customer_5')
9454 customer_2 -17.779706876197412
resNode: customer_5 deliver_cap: 45.8258580939846 cap_limit: 40
10551 customer_5 ('customer_5', 'customer_3')
9475 customer_5 -21.240348108731833
resNode: customer_3 deliver_cap: 71.8851679489667 cap_limit: 40
10552 customer_5 ('customer_5', 'customer_1')
9475 customer_5 -21.240348108731833
resNode: customer_1 deliver_cap: 65.3233343213742 cap_limit: 40
10553 customer_5 ('customer_5', 'depot_t')
9475 customer_5 -21.240348108731833
resNode: depot_t deliver_cap: 39.525807438827165 cap_limit: 40
10554 customer_5 ('customer_5', 'customer_2')
9475 customer_5 -21.240348108731833
resNode: customer_2 deliver_cap: 43.79415083009562 cap_limit: 40
10555 customer_5 ('customer_5', 'customer_4')
9475 customer_5 -21.240348108731833
resNode: customer_4 deliver_cap: 71.5533789950254 cap_limit: 40
10556 customer_2 ('customer_2', 'customer_3')
9483 customer_2 -12.424950527947802
resNode: customer_3 deliver_cap: 65.447221167274 cap_limit: 40
10557 customer_2 ('customer_2', 'customer_1')
9483 customer_2 -12.424950527947802
resNode: customer_1 deliver_cap: 51.64601688658672 cap_limit: 40
10558 customer_2 ('customer_2', 'depot_t')
9483 customer_2 -12.424950527947802
resNode: depot_t deliver_cap: 36.680526824211384 cap_limit: 40
10559 customer_2 ('customer_2', 'customer_4')
9483 customer_2 -12.424950527947802
resNode: customer_4 deliver_cap: 65.26289397063994 cap_limit: 40
10560 customer_2 ('customer_2', 'customer_5')
9483 customer_2 -12.424950527947802
resNode: customer_5 deliver_cap: 51.288717254764315 cap_limit: 40
10561 customer_2 ('customer_2', 'customer_3')
9489 customer_2 -18.383065030406634
resNode: customer_3 deliver_cap: 64.52647329483808 cap_limit: 40
10562 customer_2 ('customer_2', 'customer_1')
9489 customer_2 -18.383065030406634
resNode: customer_1 deliver_cap: 52.88236101999114 cap_limit: 40
10563 customer_2 ('customer_2', 'depot_t')
9489 customer_2 -18.383065030406634
resNode: depot_t deliver_cap: 35.78749078481869 cap_limit: 40
10564 customer_2 ('customer_2', 'customer_4')
9489 customer_2 -18.383065030406634
resNode: customer_4 deliver_cap: 64.30528065887721 cap_limit: 40
10565 customer_2 ('customer_2', 'customer_5')
9489 customer_2 -18.383065030406634
resNode: customer_5 deliver_cap: 47.536268599826464 cap_limit: 40
10566 customer_2 ('customer_2', 'customer_3')
9508 customer_2 -13.918652839961068
resNode: customer_3 deliver_cap: 64.52647329483808 cap_limit: 40
10567 customer_2 ('customer_2', 'customer_1')
9508 customer_2 -13.918652839961068
resNode: customer_1 deliver_cap: 52.882361019991144 cap_limit: 40
10568 customer_2 ('customer_2', 'depot_t')
9508 customer_2 -13.918652839961068
resNode: depot_t deliver_cap: 35.787490784818694 cap_limit: 40
10569 customer_2 ('customer_2', 'customer_4')
9508 customer_2 -13.918652839961068
resNode: customer_4 deliver_cap: 64.30528065887722 cap_limit: 40
10570 customer_2 ('customer_2', 'customer_5')
9508 customer_2 -13.918652839961068
resNode: customer_5 deliver_cap: 47.53626859982647 cap_limit: 40
10571 customer_2 ('customer_2', 'customer_3')
9514 customer_2 -16.37421931594723
resNode: customer_3 deliver_cap: 58.935661387105284 cap_limit: 40
10572 customer_2 ('customer_2', 'customer_1')
9514 customer_2 -16.37421931594723
resNode: customer_1 deliver_cap: 49.44864111809868 cap_limit: 40
10573 customer_2 ('customer_2', 'depot_t')
9514 customer_2 -16.37421931594723
resNode: depot_t deliver_cap: 30.224390710129104 cap_limit: 40
10574 customer_2 ('customer_2', 'customer_4')
9514 customer_2 -16.37421931594723
resNode: customer_4 deliver_cap: 58.67760331181761 cap_limit: 40
10575 customer_2 ('customer_2', 'customer_5')
9514 customer_2 -16.37421931594723
resNode: customer_5 deliver_cap: 39.113755909591745 cap_limit: 40
10576 customer_5 ('customer_5', 'customer_3')
9540 customer_5 -21.994252497949894
resNode: customer_3 deliver_cap: 65.62243164710227 cap_limit: 40
10577 customer_5 ('customer_5', 'customer_1')
9540 customer_5 -21.994252497949894
resNode: customer_1 deliver_cap: 58.66685903988727 cap_limit: 40
10578 customer_5 ('customer_5', 'depot_t')
9540 customer_5 -21.994252497949894
resNode: depot_t deliver_cap: 35.807354489239 cap_limit: 40
10579 customer_5 ('customer_5', 'customer_2')
9540 customer_5 -21.994252497949894
resNode: customer_2 deliver_cap: 39.82882348501851 cap_limit: 40
10580 customer_5 ('customer_5', 'customer_4')
9540 customer_5 -21.994252497949894
resNode: customer_4 deliver_cap: 65.3275081324878 cap_limit: 40
10581 customer_5 ('customer_5', 'customer_3')
9560 customer_5 -19.549847606132914
resNode: customer_3 deliver_cap: 68.47946435400007 cap_limit: 40
10582 customer_5 ('customer_5', 'customer_1')
9560 customer_5 -19.549847606132914
resNode: customer_1 deliver_cap: 61.16676265842285 cap_limit: 40
10583 customer_5 ('customer_5', 'depot_t')
9560 customer_5 -19.549847606132914
resNode: depot_t deliver_cap: 38.188215078320496 cap_limit: 40
10584 customer_5 ('customer_5', 'customer_2')
9560 customer_5 -19.549847606132914
resNode: customer_2 deliver_cap: 42.32872710355408 cap_limit: 40
10585 customer_5 ('customer_5', 'customer_4')
9560 customer_5 -19.549847606132914
resNode: customer_4 deliver_cap: 68.18454083938559 cap_limit: 40
10586 customer_2 ('customer_2', 'customer_3')
9574 customer_2 -17.59939616340541
resNode: customer_3 deliver_cap: 68.47946435400007 cap_limit: 40
10587 customer_2 ('customer_2', 'customer_1')
9574 customer_2 -17.59939616340541
resNode: customer_1 deliver_cap: 58.67395122709323 cap_limit: 40
10588 customer_2 ('customer_2', 'depot_t')
9574 customer_2 -17.59939616340541
resNode: depot_t deliver_cap: 36.49512569174635 cap_limit: 40
10589 customer_2 ('customer_2', 'customer_4')
9574 customer_2 -17.59939616340541
resNode: customer_4 deliver_cap: 68.18454083938559 cap_limit: 40
10590 customer_2 ('customer_2', 'customer_5')
9574 customer_2 -17.59939616340541
resNode: customer_5 deliver_cap: 45.82585809398459 cap_limit: 40
10591 customer_1 ('customer_1', 'customer_3')
9602 customer_1 -10.148907055889028
resNode: customer_3 deliver_cap: 61.99444981931422 cap_limit: 40
10592 customer_1 ('customer_1', 'depot_t')
9602 customer_1 -10.148907055889028
resNode: depot_t deliver_cap: 37.47463971253514 cap_limit: 40
10593 customer_1 ('customer_1', 'customer_2')
9602 customer_1 -10.148907055889028
resNode: customer_2 deliver_cap: 40.88142514094743 cap_limit: 40
10594 customer_1 ('customer_1', 'customer_4')
9602 customer_1 -10.148907055889028
resNode: customer_4 deliver_cap: 61.53210354205962 cap_limit: 40
10595 customer_1 ('customer_1', 'customer_5')
9602 customer_1 -10.148907055889028
resNode: customer_5 deliver_cap: 51.28871725476432 cap_limit: 40
10596 customer_5 ('customer_5', 'customer_3')
9605 customer_5 -16.78423565518206
resNode: customer_3 deliver_cap: 62.389777782269846 cap_limit: 40
10597 customer_5 ('customer_5', 'customer_1')
9605 customer_5 -16.78423565518206
resNode: customer_1 deliver_cap: 52.88236101999114 cap_limit: 40
10598 customer_5 ('customer_5', 'depot_t')
9605 customer_5 -16.78423565518206
resNode: depot_t deliver_cap: 35.310779067867514 cap_limit: 40
10599 customer_5 ('customer_5', 'customer_2')
9605 customer_5 -16.78423565518206
resNode: customer_2 deliver_cap: 39.42662133794202 cap_limit: 40
10600 customer_5 ('customer_5', 'customer_4')
9605 customer_5 -16.78423565518206
resNode: customer_4 deliver_cap: 62.16858514630898 cap_limit: 40

9770 customer_5 -14.830346301963019
resNode: customer_3 deliver_cap: 68.47946435400007 cap_limit: 40
10667 customer_5 ('customer_5', 'customer_1')
9770 customer_5 -14.830346301963019
resNode: customer_1 deliver_cap: 61.16676265842284 cap_limit: 40
10668 customer_5 ('customer_5', 'depot_t')
9770 customer_5 -14.830346301963019
resNode: depot_t deliver_cap: 38.18821507832049 cap_limit: 40
10669 customer_5 ('customer_5', 'customer_2')
9770 customer_5 -14.830346301963019
resNode: customer_2 deliver_cap: 42.32872710355407 cap_limit: 40
10670 customer_5 ('customer_5', 'customer_4')
9770 customer_5 -14.830346301963019
resNode: customer_4 deliver_cap: 68.18454083938556 cap_limit: 40
10671 customer_2 ('customer_2', 'customer_3')
9779 customer_2 -13.643484407277501
resNode: customer_3 deliver_cap: 68.47946435400007 cap_limit: 40
10672 customer_2 ('customer_2', 'customer_1')
9779 customer_2 -13.643484407277501
resNode: customer_1 deliver_cap: 58.67395122709323 cap_limit: 40
10673 customer_2 ('customer_2', 'depot_t')
9779 customer_2 -13.643484407277501
resNode: depot_t deliver_cap: 36.49512569174635 cap_limit: 40
10674 customer_2 ('customer_2', 'customer_4')
9779 customer_2 -13.643484407277501
resNode: customer_4 deliver_cap: 68.18454083938559 cap_limit: 40
10675 customer_2 ('customer_2', 'customer_5')
9779 customer_2 -13.643484407277501
resNode: customer_5 deliver_cap: 45.82585809398459 cap_limit: 40
10676 customer_1 ('customer_1', 'customer_3')
9787 customer_1 -8.227261486177177
resNode: customer_3 deliver_cap: 60.383147677286345 cap_limit: 40
10677 customer_1 ('customer_1', 'depot_t')
9787 customer_1 -8.227261486177177
resNode: depot_t deliver_cap: 36.79817991541255 cap_limit: 40
10678 customer_1 ('customer_1', 'customer_2')
9787 customer_1 -8.227261486177177
resNode: customer_2 deliver_cap: 39.42662133794202 cap_limit: 40
10679 customer_1 ('customer_1', 'customer_4')
9787 customer_1 -8.227261486177177
resNode: customer_4 deliver_cap: 59.828332144580834 cap_limit: 40
10680 customer_1 ('customer_1', 'customer_5')
9787 customer_1 -8.227261486177177
resNode: customer_5 deliver_cap: 47.53626859982647 cap_limit: 40
10681 customer_5 ('customer_5', 'customer_3')
9790 customer_5 -11.280359870736199
resNode: customer_3 deliver_cap: 56.442849955775664 cap_limit: 40
10682 customer_5 ('customer_5', 'customer_1')
9790 customer_5 -11.280359870736199
resNode: customer_1 deliver_cap: 49.44864111809867 cap_limit: 40
10683 customer_5 ('customer_5', 'depot_t')
9790 customer_5 -11.280359870736199
resNode: depot_t deliver_cap: 29.645526482402673 cap_limit: 40
10684 customer_5 ('customer_5', 'customer_2')
9790 customer_5 -11.280359870736199
resNode: customer_2 deliver_cap: 33.30175349963973 cap_limit: 40
10685 customer_5 ('customer_5', 'customer_4')
9790 customer_5 -11.280359870736199
resNode: customer_4 deliver_cap: 56.18479188048799 cap_limit: 40
10686 customer_2 ('customer_2', 'customer_3')
9799 customer_2 -11.255012910894775
resNode: customer_3 deliver_cap: 58.935661387105284 cap_limit: 40
10687 customer_2 ('customer_2', 'customer_1')
9799 customer_2 -11.255012910894775
resNode: customer_1 deliver_cap: 49.44864111809867 cap_limit: 40
10688 customer_2 ('customer_2', 'depot_t')
9799 customer_2 -11.255012910894775
resNode: depot_t deliver_cap: 30.2243907101291 cap_limit: 40
10689 customer_2 ('customer_2', 'customer_4')
9799 customer_2 -11.255012910894775
resNode: customer_4 deliver_cap: 58.67760331181761 cap_limit: 40
10690 customer_2 ('customer_2', 'customer_5')
9799 customer_2 -11.255012910894775
resNode: customer_5 deliver_cap: 39.11375590959174 cap_limit: 40
10691 customer_5 ('customer_5', 'customer_3')
9815 customer_5 -14.723846143907792
resNode: customer_3 deliver_cap: 68.18454083938558 cap_limit: 40
10692 customer_5 ('customer_5', 'customer_1')
9815 customer_5 -14.723846143907792
resNode: customer_1 deliver_cap: 60.90870458313516 cap_limit: 40
10693 customer_5 ('customer_5', 'depot_t')
9815 customer_5 -14.723846143907792
resNode: depot_t deliver_cap: 37.942445482808424 cap_limit: 40
10694 customer_5 ('customer_5', 'customer_2')
9815 customer_5 -14.723846143907792
resNode: customer_2 deliver_cap: 42.070669028266394 cap_limit: 40
10695 customer_5 ('customer_5', 'customer_4')
9815 customer_5 -14.723846143907792
resNode: customer_4 deliver_cap: 67.8896173247711 cap_limit: 40
10696 customer_2 ('customer_2', 'customer_3')
9819 customer_2 -13.536984249222268
resNode: customer_3 deliver_cap: 68.18454083938558 cap_limit: 40
10697 customer_2 ('customer_2', 'customer_1')
9819 customer_2 -13.536984249222268
resNode: customer_1 deliver_cap: 58.41589315180554 cap_limit: 40
10698 customer_2 ('customer_2', 'depot_t')
9819 customer_2 -13.536984249222268
resNode: depot_t deliver_cap: 36.24935609623427 cap_limit: 40
10699 customer_2 ('customer_2', 'customer_4')
9819 customer_2 -13.536984249222268
resNode: customer_4 deliver_cap: 67.8896173247711 cap_limit: 40
10700 customer_2 ('customer_2', 'customer_5')
9819 customer_2 -13.536984249222268
resNode: customer_5 deliver_cap: 45.5309345793701 cap_limit: 40
10701 customer_2 ('customer_2', 'customer_3')
9823 customer_2 -9.867883363941585
resNode: customer_3 deliver_cap: 68.47946435400007 cap_limit: 40
10702 customer_2 ('customer_2', 'customer_1')
9823 customer_2 -9.867883363941585
resNode: customer_1 deliver_cap: 58.67395122709323 cap_limit: 40
10703 customer_2 ('customer_2', 'depot_t')
9823 customer_2 -9.867883363941585
resNode: depot_t deliver_cap: 36.495125691746345 cap_limit: 40
10704 customer_2 ('customer_2', 'customer_4')
9823 customer_2 -9.867883363941585
resNode: customer_4 deliver_cap: 68.18454083938556 cap_limit: 40
10705 customer_2 ('customer_2', 'customer_5')
9823 customer_2 -9.867883363941585
resNode: customer_5 deliver_cap: 45.82585809398459 cap_limit: 40
10706 customer_5 ('customer_5', 'customer_3')
9825 customer_5 -14.855703692559983
resNode: customer_3 deliver_cap: 71.8851679489667 cap_limit: 40
10707 customer_5 ('customer_5', 'customer_1')
9825 customer_5 -14.855703692559983
resNode: customer_1 deliver_cap: 65.3233343213742 cap_limit: 40
10708 customer_5 ('customer_5', 'depot_t')
9825 customer_5 -14.855703692559983
resNode: depot_t deliver_cap: 39.525807438827165 cap_limit: 40
10709 customer_5 ('customer_5', 'customer_2')
9825 customer_5 -14.855703692559983
resNode: customer_2 deliver_cap: 43.79415083009562 cap_limit: 40
10710 customer_5 ('customer_5', 'customer_4')
9825 customer_5 -14.855703692559983
resNode: customer_4 deliver_cap: 71.5533789950254 cap_limit: 40
10711 customer_2 ('customer_2', 'customer_3')
9828 customer_2 -7.785520968602136
resNode: customer_3 deliver_cap: 58.935661387105284 cap_limit: 40
10712 customer_2 ('customer_2', 'customer_1')
9828 customer_2 -7.785520968602136
resNode: customer_1 deliver_cap: 49.44864111809867 cap_limit: 40
10713 customer_2 ('customer_2', 'depot_t')
9828 customer_2 -7.785520968602136
resNode: depot_t deliver_cap: 30.2243907101291 cap_limit: 40
10714 customer_2 ('customer_2', 'customer_4')
9828 customer_2 -7.785520968602136
resNode: customer_4 deliver_cap: 58.67760331181761 cap_limit: 40
10715 customer_2 ('customer_2', 'customer_5')
9828 customer_2 -7.785520968602136
resNode: customer_5 deliver_cap: 39.11375590959174 cap_limit: 40
10716 customer_5 ('customer_5', 'customer_3')
9830 customer_5 -13.745680184150856
resNode: customer_3 deliver_cap: 65.62243164710227 cap_limit: 40
10717 customer_5 ('customer_5', 'customer_1')
9830 customer_5 -13.745680184150856
resNode: customer_1 deliver_cap: 58.66685903988727 cap_limit: 40
10718 customer_5 ('customer_5', 'depot_t')
9830 customer_5 -13.745680184150856
resNode: depot_t deliver_cap: 35.807354489238996 cap_limit: 40
10719 customer_5 ('customer_5', 'customer_2')
9830 customer_5 -13.745680184150856
resNode: customer_2 deliver_cap: 39.8288234850185 cap_limit: 40
10720 customer_5 ('customer_5', 'customer_4')
9830 customer_5 -13.745680184150856
resNode: customer_4 deliver_cap: 65.3275081324878 cap_limit: 40
10721 customer_3 ('customer_3', 'customer_1')
9831 customer_3 -10.110844997793127
resNode: customer_1 deliver_cap: 56.33288277127915 cap_limit: 40
10722 customer_3 ('customer_3', 'depot_t')
9831 customer_3 -10.110844997793127
resNode: depot_t deliver_cap: 38.18821507832049 cap_limit: 40
10723 customer_3 ('customer_3', 'customer_2')
9831 customer_3 -10.110844997793127
resNode: customer_2 deliver_cap: 42.32872710355407 cap_limit: 40
10724 customer_3 ('customer_3', 'customer_4')
9831 customer_3 -10.110844997793127
resNode: customer_4 deliver_cap: 51.81364772021093 cap_limit: 40
10725 customer_3 ('customer_3', 'customer_5')
9831 customer_3 -10.110844997793127
resNode: customer_5 deliver_cap: 45.82585809398459 cap_limit: 40
10726 customer_1 ('customer_1', 'customer_3')
9832 customer_1 -7.267480080438225
resNode: customer_3 deliver_cap: 54.10178149996159 cap_limit: 40
10727 customer_1 ('customer_1', 'depot_t')
9832 customer_1 -7.267480080438225
resNode: depot_t deliver_cap: 31.451656082993075 cap_limit: 40
10728 customer_1 ('customer_1', 'customer_2')
9832 customer_1 -7.267480080438225
resNode: customer_2 deliver_cap: 33.30175349963973 cap_limit: 40
10729 customer_1 ('customer_1', 'customer_4')
9832 customer_1 -7.267480080438225
resNode: customer_4 deliver_cap: 53.454496711805156 cap_limit: 40
10730 customer_1 ('customer_1', 'customer_5')
9832 customer_1 -7.267480080438225
resNode: customer_5 deliver_cap: 39.11375590959174 cap_limit: 40
10731 customer_4 ('customer_4', 'customer_3')
9834 customer_4 -10.065787238615915
resNode: customer_3 deliver_cap: 51.81364772021093 cap_limit: 40
10732 customer_4 ('customer_4', 'customer_1')
9834 customer_4 -10.065787238615915
resNode: customer_1 deliver_cap: 55.68559798312271 cap_limit: 40
10733 customer_4 ('customer_4', 'depot_t')
9834 customer_4 -10.065787238615915
resNode: depot_t deliver_cap: 37.942445482808424 cap_limit: 40
10734 customer_4 ('customer_4', 'customer_2')
9834 customer_4 -10.065787238615915
resNode: customer_2 deliver_cap: 42.070669028266394 cap_limit: 40
10735 customer_4 ('customer_4', 'customer_5')
9834 customer_4 -10.065787238615915
resNode: customer_5 deliver_cap: 45.5309345793701 cap_limit: 40
10736 customer_5 ('customer_5', 'customer_3')
9835 customer_5 -6.73834825026323
resNode: customer_3 deliver_cap: 45.82585809398459 cap_limit: 40
10737 customer_5 ('customer_5', 'customer_1')
9835 customer_5 -6.73834825026323
resNode: customer_1 deliver_cap: 41.3448571809093 cap_limit: 40
10738 customer_5 ('customer_5', 'depot_t')
9835 customer_5 -6.73834825026323
resNode: depot_t deliver_cap: 19.310209861640928 cap_limit: 40
10739 customer_5 ('customer_5', 'customer_2')
9835 customer_5 -6.73834825026323
resNode: customer_2 deliver_cap: 22.506821626040534 cap_limit: 40
10740 customer_5 ('customer_5', 'customer_4')
9835 customer_5 -6.73834825026323
resNode: customer_4 deliver_cap: 45.5309345793701 cap_limit: 40
10741 customer_2 ('customer_2', 'customer_3')
9839 customer_2 -9.81053712498877
resNode: customer_3 deliver_cap: 68.18454083938558 cap_limit: 40
10742 customer_2 ('customer_2', 'customer_1')
9839 customer_2 -9.81053712498877
resNode: customer_1 deliver_cap: 58.41589315180554 cap_limit: 40
10743 customer_2 ('customer_2', 'depot_t')
9839 customer_2 -9.81053712498877
resNode: depot_t deliver_cap: 36.24935609623427 cap_limit: 40
10744 customer_2 ('customer_2', 'customer_4')
9839 customer_2 -9.81053712498877
resNode: customer_4 deliver_cap: 67.8896173247711 cap_limit: 40
10745 customer_2 ('customer_2', 'customer_5')
9839 customer_2 -9.81053712498877
resNode: customer_5 deliver_cap: 45.5309345793701 cap_limit: 40
10746 customer_5 ('customer_5', 'customer_3')
9840 customer_5 -14.752275654448649
resNode: customer_3 deliver_cap: 71.5533789950254 cap_limit: 40
10747 customer_5 ('customer_5', 'customer_1')
9840 customer_5 -14.752275654448649
resNode: customer_1 deliver_cap: 65.02841080675971 cap_limit: 40
10748 customer_5 ('customer_5', 'depot_t')
9840 customer_5 -14.752275654448649
resNode: depot_t deliver_cap: 39.243172403988275 cap_limit: 40
10749 customer_5 ('customer_5', 'customer_2')
9840 customer_5 -14.752275654448649
resNode: customer_2 deliver_cap: 43.49922731548112 cap_limit: 40
10750 customer_5 ('customer_5', 'customer_4')
9840 customer_5 -14.752275654448649
resNode: customer_4 deliver_cap: 71.22159004108408 cap_limit: 40
10751 customer_2 ('customer_2', 'customer_3')
9859 customer_2 -13.705006482238664
resNode: customer_3 deliver_cap: 68.18454083938558 cap_limit: 40
10752 customer_2 ('customer_2', 'customer_1')
9859 customer_2 -13.705006482238664
resNode: customer_1 deliver_cap: 58.415893151805555 cap_limit: 40
10753 customer_2 ('customer_2', 'depot_t')
9859 customer_2 -13.705006482238664
resNode: depot_t deliver_cap: 36.24935609623427 cap_limit: 40
10754 customer_2 ('customer_2', 'customer_4')
9859 customer_2 -13.705006482238664
resNode: customer_4 deliver_cap: 67.8896173247711 cap_limit: 40
10755 customer_2 ('customer_2', 'customer_5')
9859 customer_2 -13.705006482238664
resNode: customer_5 deliver_cap: 45.530934579370104 cap_limit: 40
10756 customer_5 ('customer_5', 'customer_3')
9865 customer_5 -17.883155463656554
resNode: customer_3 deliver_cap: 71.5533789950254 cap_limit: 40
10757 customer_5 ('customer_5', 'customer_1')
9865 customer_5 -17.883155463656554
resNode: customer_1 deliver_cap: 65.02841080675971 cap_limit: 40
10758 customer_5 ('customer_5', 'depot_t')
9865 customer_5 -17.883155463656554
resNode: depot_t deliver_cap: 39.243172403988275 cap_limit: 40
10759 customer_5 ('customer_5', 'customer_2')
9865 customer_5 -17.883155463656554
resNode: customer_2 deliver_cap: 43.49922731548112 cap_limit: 40
10760 customer_5 ('customer_5', 'customer_4')
9865 customer_5 -17.883155463656554
resNode: customer_4 deliver_cap: 71.22159004108408 cap_limit: 40
10761 customer_2 ('customer_2', 'customer_3')
9894 customer_2 -17.599475839488555
resNode: customer_3 deliver_cap: 68.18454083938558 cap_limit: 40
10762 customer_2 ('customer_2', 'customer_1')
9894 customer_2 -17.599475839488555
resNode: customer_1 deliver_cap: 58.415893151805555 cap_limit: 40
10763 customer_2 ('customer_2', 'depot_t')
9894 customer_2 -17.599475839488555
resNode: depot_t deliver_cap: 36.24935609623427 cap_limit: 40
10764 customer_2 ('customer_2', 'customer_4')
9894 customer_2 -17.599475839488555
resNode: customer_4 deliver_cap: 67.8896173247711 cap_limit: 40
10765 customer_2 ('customer_2', 'customer_5')
9894 customer_2 -17.599475839488555
resNode: customer_5 deliver_cap: 45.530934579370104 cap_limit: 40
10766 customer_5 ('customer_5', 'customer_3')
9905 customer_5 -21.01403527286446
resNode: customer_3 deliver_cap: 71.5533789950254 cap_limit: 40
10767 customer_5 ('customer_5', 'customer_1')
9905 customer_5 -21.01403527286446
resNode: customer_1 deliver_cap: 65.02841080675971 cap_limit: 40
10768 customer_5 ('customer_5', 'depot_t')
9905 customer_5 -21.01403527286446
resNode: depot_t deliver_cap: 39.243172403988275 cap_limit: 40
10769 customer_5 ('customer_5', 'customer_2')
9905 customer_5 -21.01403527286446
resNode: customer_2 deliver_cap: 43.49922731548112 cap_limit: 40
10770 customer_5 ('customer_5', 'customer_4')
9905 customer_5 -21.01403527286446
resNode: customer_4 deliver_cap: 71.22159004108408 cap_limit: 40
10771 customer_2 ('customer_2', 'customer_3')
9924 customer_2 -23.61030692995613
resNode: customer_3 deliver_cap: 70.21624810327455 cap_limit: 40
10772 customer_2 ('customer_2', 'customer_1')
9924 customer_2 -23.61030692995613
resNode: customer_1 deliver_cap: 60.19363700770841 cap_limit: 40
10773 customer_2 ('customer_2', 'depot_t')
9924 customer_2 -23.61030692995613
resNode: depot_t deliver_cap: 37.942445482808424 cap_limit: 40
10774 customer_2 ('customer_2', 'customer_4')
9924 customer_2 -23.61030692995613
resNode: customer_4 deliver_cap: 69.92132458866007 cap_limit: 40
10775 customer_2 ('customer_2', 'customer_5')
9924 customer_2 -23.61030692995613
resNode: customer_5 deliver_cap: 47.56264184325909 cap_limit: 40
10776 customer_2 ('customer_2', 'customer_3')
9964 customer_2 -20.31335342391617
resNode: customer_3 deliver_cap: 74.1708386208418 cap_limit: 40
10777 customer_2 ('customer_2', 'customer_1')
9964 customer_2 -20.31335342391617
resNode: customer_1 deliver_cap: 64.50611423517219 cap_limit: 40
10778 customer_2 ('customer_2', 'depot_t')
9964 customer_2 -20.31335342391617
resNode: depot_t deliver_cap: 39.52580743882717 cap_limit: 40
10779 customer_2 ('customer_2', 'customer_4')
9964 customer_2 -20.31335342391617
resNode: customer_4 deliver_cap: 73.83904966690051 cap_limit: 40
10780 customer_2 ('customer_2', 'customer_5')
9964 customer_2 -20.31335342391617
resNode: customer_5 deliver_cap: 48.68553157832439 cap_limit: 40
10781 customer_5 ('customer_5', 'customer_3')
10005 customer_5 -21.797775789429668
resNode: customer_3 deliver_cap: 64.80521156090026 cap_limit: 40
10782 customer_5 ('customer_5', 'customer_1')
10005 customer_5 -21.797775789429668
resNode: customer_1 deliver_cap: 57.95179146446051 cap_limit: 40
10783 customer_5 ('customer_5', 'depot_t')
10005 customer_5 -21.797775789429668
resNode: depot_t deliver_cap: 35.12633775073732 cap_limit: 40
10784 customer_5 ('customer_5', 'customer_2')
10005 customer_5 -21.797775789429668
resNode: customer_2 deliver_cap: 39.113755909591745 cap_limit: 40
10785 customer_5 ('customer_5', 'customer_4')
10005 customer_5 -21.797775789429668
resNode: customer_4 deliver_cap: 64.51028804628578 cap_limit: 40
10786 customer_2 ('customer_2', 'customer_3')
10029 customer_2 -21.45784092373601
resNode: customer_3 deliver_cap: 67.65413891099125 cap_limit: 40
10787 customer_2 ('customer_2', 'customer_1')
10029 customer_2 -21.45784092373601
resNode: customer_1 deliver_cap: 57.95179146446051 cap_limit: 40
10788 customer_2 ('customer_2', 'depot_t')
10029 customer_2 -21.45784092373601
resNode: depot_t deliver_cap: 35.807354489239 cap_limit: 40
10789 customer_2 ('customer_2', 'customer_4')
10029 customer_2 -21.45784092373601
resNode: customer_4 deliver_cap: 67.35921539637675 cap_limit: 40
10790 customer_2 ('customer_2', 'customer_5')
10029 customer_2 -21.45784092373601
resNode: customer_5 deliver_cap: 45.00053265097577 cap_limit: 40
10791 customer_2 ('customer_2', 'customer_3')
10039 customer_2 -19.1324790613731
resNode: customer_3 deliver_cap: 70.51117161788905 cap_limit: 40
10792 customer_2 ('customer_2', 'customer_1')
10039 customer_2 -19.1324790613731
resNode: customer_1 deliver_cap: 60.45169508299608 cap_limit: 40
10793 customer_2 ('customer_2', 'depot_t')
10039 customer_2 -19.1324790613731
resNode: depot_t deliver_cap: 38.188215078320496 cap_limit: 40
10794 customer_2 ('customer_2', 'customer_4')
10039 customer_2 -19.1324790613731
resNode: customer_4 deliver_cap: 70.21624810327455 cap_limit: 40
10795 customer_2 ('customer_2', 'customer_5')
10039 customer_2 -19.1324790613731
resNode: customer_5 deliver_cap: 47.85756535787357 cap_limit: 40
10796 customer_2 ('customer_2', 'customer_3')
10068 customer_2 -11.78668850345487
resNode: customer_3 deliver_cap: 64.93645861339775 cap_limit: 40
10797 customer_2 ('customer_2', 'customer_1')
10068 customer_2 -11.78668850345487
resNode: customer_1 deliver_cap: 51.23740684348571 cap_limit: 40
10798 customer_2 ('customer_2', 'depot_t')
10068 customer_2 -11.78668850345487
resNode: depot_t deliver_cap: 36.30596761803546 cap_limit: 40
10799 customer_2 ('customer_2', 'customer_4')
10068 customer_2 -11.78668850345487
resNode: customer_4 deliver_cap: 64.75213141676367 cap_limit: 40
10800 customer_2 ('customer_2', 'customer_5')
10068 customer_2 -11.78668850345487
resNode: customer_5 deliver_cap: 50.77795470088805 cap_limit: 40
10801 customer_2 ('customer_2', 'customer_3')
10074 customer_2 -17.617112367444633
resNode: customer_3 deliver_cap: 63.91355823018657 cap_limit: 40
10802 customer_2 ('customer_2', 'customer_1')
10074 customer_2 -17.617112367444633
resNode: customer_1 deliver_cap: 52.37159846611488 cap_limit: 40
10803 customer_2 ('customer_2', 'depot_t')
10074 customer_2 -17.617112367444633

10214 customer_2 -17.33355476683649
resNode: customer_5 deliver_cap: 45.00053265097577 cap_limit: 40
10841 customer_2 ('customer_2', 'customer_3')
10224 customer_2 -14.412977757203212
resNode: customer_3 deliver_cap: 70.51117161788905 cap_limit: 40
10842 customer_2 ('customer_2', 'customer_1')
10224 customer_2 -14.412977757203212
resNode: customer_1 deliver_cap: 60.45169508299608 cap_limit: 40
10843 customer_2 ('customer_2', 'depot_t')
10224 customer_2 -14.412977757203212
resNode: depot_t deliver_cap: 38.188215078320496 cap_limit: 40
10844 customer_2 ('customer_2', 'customer_4')
10224 customer_2 -14.412977757203212
resNode: customer_4 deliver_cap: 70.21624810327455 cap_limit: 40
10845 customer_2 ('customer_2', 'customer_5')
10224 customer_2 -14.412977757203212
resNode: customer_5 deliver_cap: 47.85756535787357 cap_limit: 40
10846 customer_2 ('customer_2', 'customer_3')
10243 customer_2 -8.688287986553497
resNode: customer_3 deliver_cap: 63.913558230186574 cap_limit: 40
10847 customer_2 ('customer_2', 'customer_1')
10243 customer_2 -8.688287986553497
resNode: customer_1 deliver_cap: 52.37159846611489 cap_limit: 40
10848 customer_2 ('customer_2', 'depot_t')
10243 customer_2 -8.688287986553497
resNode: depot_t deliver_cap: 35.310779067867514 cap_limit: 40
10849 customer_2 ('customer_2', 'customer_4')
10243 customer_2 -8.688287986553497
resNode: customer_4 deliver_cap: 63.692365594225706 cap_limit: 40
10850 customer_2 ('customer_2', 'customer_5')
10243 customer_2 -8.688287986553497
resNode: customer_5 deliver_cap: 46.92335353517496 cap_limit: 40
10851 customer_2 ('customer_2', 'customer_3')
10249 customer_2 -11.016163824070594
resNode: customer_3 deliver_cap: 58.22059381167852 cap_limit: 40
10852 customer_2 ('customer_2', 'customer_1')
10249 customer_2 -11.016163824070594
resNode: customer_1 deliver_cap: 48.835726053447154 cap_limit: 40
10853 customer_2 ('customer_2', 'depot_t')
10249 customer_2 -11.016163824070594
resNode: depot_t deliver_cap: 29.645526482402673 cap_limit: 40
10854 customer_2 ('customer_2', 'customer_4')
10249 customer_2 -11.016163824070594
resNode: customer_4 deliver_cap: 57.962535736390834 cap_limit: 40
10855 customer_2 ('customer_2', 'customer_5')
10249 customer_2 -11.016163824070594
resNode: customer_5 deliver_cap: 38.39868833416497 cap_limit: 40
10856 customer_5 ('customer_5', 'customer_3')
10260 customer_5 -16.67856938437722
resNode: customer_3 deliver_cap: 64.80521156090026 cap_limit: 40
10857 customer_5 ('customer_5', 'customer_1')
10260 customer_5 -16.67856938437722
resNode: customer_1 deliver_cap: 57.951791464460506 cap_limit: 40
10858 customer_5 ('customer_5', 'depot_t')
10260 customer_5 -16.67856938437722
resNode: depot_t deliver_cap: 35.126337750737314 cap_limit: 40
10859 customer_5 ('customer_5', 'customer_2')
10260 customer_5 -16.67856938437722
resNode: customer_2 deliver_cap: 39.11375590959174 cap_limit: 40
10860 customer_5 ('customer_5', 'customer_4')
10260 customer_5 -16.67856938437722
resNode: customer_4 deliver_cap: 64.51028804628575 cap_limit: 40
10861 customer_2 ('customer_2', 'customer_3')
10274 customer_2 -14.294189119372376
resNode: customer_3 deliver_cap: 70.21624810327455 cap_limit: 40
10862 customer_2 ('customer_2', 'customer_1')
10274 customer_2 -14.294189119372376
resNode: customer_1 deliver_cap: 60.1936370077084 cap_limit: 40
10863 customer_2 ('customer_2', 'depot_t')
10274 customer_2 -14.294189119372376
resNode: depot_t deliver_cap: 37.942445482808424 cap_limit: 40
10864 customer_2 ('customer_2', 'customer_4')
10274 customer_2 -14.294189119372376
resNode: customer_4 deliver_cap: 69.92132458866007 cap_limit: 40
10865 customer_2 ('customer_2', 'customer_5')
10274 customer_2 -14.294189119372376
resNode: customer_5 deliver_cap: 47.56264184325908 cap_limit: 40
10866 customer_2 ('customer_2', 'customer_3')
10289 customer_2 -13.928709007744315
resNode: customer_3 deliver_cap: 74.17083862084179 cap_limit: 40
10867 customer_2 ('customer_2', 'customer_1')
10289 customer_2 -13.928709007744315
resNode: customer_1 deliver_cap: 64.50611423517219 cap_limit: 40
10868 customer_2 ('customer_2', 'depot_t')
10289 customer_2 -13.928709007744315
resNode: depot_t deliver_cap: 39.525807438827165 cap_limit: 40
10869 customer_2 ('customer_2', 'customer_4')
10289 customer_2 -13.928709007744315
resNode: customer_4 deliver_cap: 73.83904966690048 cap_limit: 40
10870 customer_2 ('customer_2', 'customer_5')
10289 customer_2 -13.928709007744315
resNode: customer_5 deliver_cap: 48.68553157832438 cap_limit: 40
10871 customer_5 ('customer_5', 'customer_3')
10295 customer_5 -13.20907744208458
resNode: customer_3 deliver_cap: 64.80521156090026 cap_limit: 40
10872 customer_5 ('customer_5', 'customer_1')
10295 customer_5 -13.20907744208458
resNode: customer_1 deliver_cap: 57.951791464460506 cap_limit: 40
10873 customer_5 ('customer_5', 'depot_t')
10295 customer_5 -13.20907744208458
resNode: depot_t deliver_cap: 35.126337750737314 cap_limit: 40
10874 customer_5 ('customer_5', 'customer_2')
10295 customer_5 -13.20907744208458
resNode: customer_2 deliver_cap: 39.11375590959174 cap_limit: 40
10875 customer_5 ('customer_5', 'customer_4')
10295 customer_5 -13.20907744208458
resNode: customer_4 deliver_cap: 64.51028804628575 cap_limit: 40
10876 customer_2 ('customer_2', 'customer_3')
10299 customer_2 -13.209268609936974
resNode: customer_3 deliver_cap: 67.65413891099125 cap_limit: 40
10877 customer_2 ('customer_2', 'customer_1')
10299 customer_2 -13.209268609936974
resNode: customer_1 deliver_cap: 57.951791464460506 cap_limit: 40
10878 customer_2 ('customer_2', 'depot_t')
10299 customer_2 -13.209268609936974
resNode: depot_t deliver_cap: 35.807354489238996 cap_limit: 40
10879 customer_2 ('customer_2', 'customer_4')
10299 customer_2 -13.209268609936974
resNode: customer_4 deliver_cap: 67.35921539637675 cap_limit: 40
10880 customer_2 ('customer_2', 'customer_5')
10299 customer_2 -13.209268609936974
resNode: customer_5 deliver_cap: 45.00053265097577 cap_limit: 40
10881 customer_2 ('customer_2', 'customer_3')
10303 customer_2 -9.693476453033322
resNode: customer_3 deliver_cap: 70.51117161788905 cap_limit: 40
10882 customer_2 ('customer_2', 'customer_1')
10303 customer_2 -9.693476453033322
resNode: customer_1 deliver_cap: 60.45169508299608 cap_limit: 40
10883 customer_2 ('customer_2', 'depot_t')
10303 customer_2 -9.693476453033322
resNode: depot_t deliver_cap: 38.188215078320496 cap_limit: 40
10884 customer_2 ('customer_2', 'customer_4')
10303 customer_2 -9.693476453033322
resNode: customer_4 deliver_cap: 70.21624810327455 cap_limit: 40
10885 customer_2 ('customer_2', 'customer_5')
10303 customer_2 -9.693476453033322
resNode: customer_5 deliver_cap: 47.85756535787357 cap_limit: 40
10886 customer_2 ('customer_2', 'customer_3')
10308 customer_2 -6.551751633625022
resNode: customer_3 deliver_cap: 58.22059381167852 cap_limit: 40
10887 customer_2 ('customer_2', 'customer_1')
10308 customer_2 -6.551751633625022
resNode: customer_1 deliver_cap: 48.835726053447154 cap_limit: 40
10888 customer_2 ('customer_2', 'depot_t')
10308 customer_2 -6.551751633625022
resNode: depot_t deliver_cap: 29.645526482402673 cap_limit: 40
10889 customer_2 ('customer_2', 'customer_4')
10308 customer_2 -6.551751633625022
resNode: customer_4 deliver_cap: 57.962535736390834 cap_limit: 40
10890 customer_2 ('customer_2', 'customer_5')
10308 customer_2 -6.551751633625022
resNode: customer_5 deliver_cap: 38.39868833416497 cap_limit: 40
10891 customer_5 ('customer_5', 'customer_3')
10310 customer_5 -12.384220210704676
resNode: customer_3 deliver_cap: 64.80521156090026 cap_limit: 40
10892 customer_5 ('customer_5', 'customer_1')
10310 customer_5 -12.384220210704676
resNode: customer_1 deliver_cap: 57.951791464460506 cap_limit: 40
10893 customer_5 ('customer_5', 'depot_t')
10310 customer_5 -12.384220210704676
resNode: depot_t deliver_cap: 35.126337750737314 cap_limit: 40
10894 customer_5 ('customer_5', 'customer_2')
10310 customer_5 -12.384220210704676
resNode: customer_2 deliver_cap: 39.11375590959174 cap_limit: 40
10895 customer_5 ('customer_5', 'customer_4')
10310 customer_5 -12.384220210704676
resNode: customer_4 deliver_cap: 64.51028804628575 cap_limit: 40
10896 customer_2 ('customer_2', 'customer_3')
10314 customer_2 -9.636130214080504
resNode: customer_3 deliver_cap: 70.21624810327455 cap_limit: 40
10897 customer_2 ('customer_2', 'customer_1')
10314 customer_2 -9.636130214080504
resNode: customer_1 deliver_cap: 60.1936370077084 cap_limit: 40
10898 customer_2 ('customer_2', 'depot_t')
10314 customer_2 -9.636130214080504
resNode: depot_t deliver_cap: 37.942445482808424 cap_limit: 40
10899 customer_2 ('customer_2', 'customer_4')
10314 customer_2 -9.636130214080504
resNode: customer_4 deliver_cap: 69.92132458866007 cap_limit: 40
10900 customer_2 ('customer_2', 'customer_5')
10314 customer_2 -9.636130214080504
resNode: customer_5 deliver_cap: 47.56264184325908 cap_limit: 40
10901 customer_1 ('customer_1', 'customer_3')
10317 customer_1 -9.445942856820981
resNode: customer_3 deliver_cap: 62.1297047542556 cap_limit: 40
10902 customer_1 ('customer_1', 'depot_t')
10317 customer_1 -9.445942856820981
resNode: depot_t deliver_cap: 37.251196104373086 cap_limit: 40
10903 customer_1 ('customer_1', 'customer_2')
10317 customer_1 -9.445942856820981
resNode: customer_2 deliver_cap: 39.11375590959174 cap_limit: 40
10904 customer_1 ('customer_1', 'customer_4')
10317 customer_1 -9.445942856820981
resNode: customer_4 deliver_cap: 61.389950710648236 cap_limit: 40
10905 customer_1 ('customer_1', 'customer_5')
10317 customer_1 -9.445942856820981
resNode: customer_5 deliver_cap: 45.00053265097577 cap_limit: 40
10906 customer_2 ('customer_2', 'customer_3')
10319 customer_2 -5.377079444669443
resNode: customer_3 deliver_cap: 47.85756535787357 cap_limit: 40
10907 customer_2 ('customer_2', 'customer_1')
10319 customer_2 -5.377079444669443
resNode: customer_1 deliver_cap: 40.629789605482536 cap_limit: 40
10908 customer_2 ('customer_2', 'depot_t')
10319 customer_2 -5.377079444669443
resNode: depot_t deliver_cap: 19.310209861640928 cap_limit: 40
10909 customer_2 ('customer_2', 'customer_4')
10319 customer_2 -5.377079444669443
resNode: customer_4 deliver_cap: 47.56264184325908 cap_limit: 40
10910 customer_2 ('customer_2', 'customer_5')
10319 customer_2 -5.377079444669443
resNode: customer_5 deliver_cap: 25.20395909785809 cap_limit: 40
10911 customer_2 ('customer_2', 'customer_3')
10329 customer_2 -13.812992489857374
resNode: customer_3 deliver_cap: 73.83904966690048 cap_limit: 40
10912 customer_2 ('customer_2', 'customer_1')
10329 customer_2 -13.812992489857374
resNode: customer_1 deliver_cap: 64.21119072055771 cap_limit: 40
10913 customer_2 ('customer_2', 'depot_t')
10329 customer_2 -13.812992489857374
resNode: depot_t deliver_cap: 39.243172403988275 cap_limit: 40
10914 customer_2 ('customer_2', 'customer_4')
10329 customer_2 -13.812992489857374
resNode: customer_4 deliver_cap: 73.50726071295918 cap_limit: 40
10915 customer_2 ('customer_2', 'customer_5')
10329 customer_2 -13.812992489857374
resNode: customer_5 deliver_cap: 48.353742624383074 cap_limit: 40
10916 customer_2 ('customer_2', 'customer_3')
10349 customer_2 -16.943872299065287
resNode: customer_3 deliver_cap: 73.8390496669005 cap_limit: 40
10917 customer_2 ('customer_2', 'customer_1')
10349 customer_2 -16.943872299065287
resNode: customer_1 deliver_cap: 64.21119072055771 cap_limit: 40
10918 customer_2 ('customer_2', 'depot_t')
10349 customer_2 -16.943872299065287
resNode: depot_t deliver_cap: 39.24317240398828 cap_limit: 40
10919 customer_2 ('customer_2', 'customer_4')
10349 customer_2 -16.943872299065287
resNode: customer_4 deliver_cap: 73.5072607129592 cap_limit: 40
10920 customer_2 ('customer_2', 'customer_5')
10349 customer_2 -16.943872299065287
resNode: customer_5 deliver_cap: 48.35374262438308 cap_limit: 40
10921 customer_2 ('customer_2', 'customer_3')
10374 customer_2 -20.074752108273195
resNode: customer_3 deliver_cap: 73.8390496669005 cap_limit: 40
10922 customer_2 ('customer_2', 'customer_1')
10374 customer_2 -20.074752108273195
resNode: customer_1 deliver_cap: 64.21119072055771 cap_limit: 40
10923 customer_2 ('customer_2', 'depot_t')
10374 customer_2 -20.074752108273195
resNode: depot_t deliver_cap: 39.24317240398828 cap_limit: 40
10924 customer_2 ('customer_2', 'customer_4')
10374 customer_2 -20.074752108273195
resNode: customer_4 deliver_cap: 73.5072607129592 cap_limit: 40
10925 customer_2 ('customer_2', 'customer_5')
10374 customer_2 -20.074752108273195
resNode: customer_5 deliver_cap: 48.35374262438308 cap_limit: 40
10926 customer_2 ('customer_2', 'customer_3')
10438 customer_2 -17.116696276401605
resNode: customer_3 deliver_cap: 67.77789413795124 cap_limit: 40
10927 customer_2 ('customer_2', 'customer_1')
10438 customer_2 -17.116696276401605
resNode: customer_1 deliver_cap: 51.54370827188415 cap_limit: 40
10928 customer_2 ('customer_2', 'depot_t')
10438 customer_2 -17.116696276401605
resNode: depot_t deliver_cap: 37.666164908655915 cap_limit: 40
10929 customer_2 ('customer_2', 'customer_4')
10438 customer_2 -17.116696276401605
resNode: customer_4 deliver_cap: 67.61814390086839 cap_limit: 40
10930 customer_2 ('customer_2', 'customer_5')
10438 customer_2 -17.116696276401605
resNode: customer_5 deliver_cap: 55.507190747109526 cap_limit: 40
10931 customer_2 ('customer_2', 'customer_3')
10464 customer_2 -28.22332972008025
resNode: customer_3 deliver_cap: 69.4829269011509 cap_limit: 40
10932 customer_2 ('customer_2', 'customer_1')
10464 customer_2 -28.22332972008025
resNode: customer_1 deliver_cap: 57.562925046764484 cap_limit: 40
10933 customer_2 ('customer_2', 'depot_t')
10464 customer_2 -28.22332972008025
resNode: depot_t deliver_cap: 39.42662133794201 cap_limit: 40
10934 customer_2 ('customer_2', 'customer_4')
10464 customer_2 -28.22332972008025
resNode: customer_4 deliver_cap: 69.24944578541444 cap_limit: 40
10935 customer_2 ('customer_2', 'customer_5')
10464 customer_2 -28.22332972008025
resNode: customer_5 deliver_cap: 51.54882194530531 cap_limit: 40
10936 customer_2 ('customer_2', 'customer_3')
10494 customer_2 -23.758917529634683
resNode: customer_3 deliver_cap: 69.48292690115092 cap_limit: 40
10937 customer_2 ('customer_2', 'customer_1')
10494 customer_2 -23.758917529634683
resNode: customer_1 deliver_cap: 57.56292504676449 cap_limit: 40
10938 customer_2 ('customer_2', 'depot_t')
10494 customer_2 -23.758917529634683
resNode: depot_t deliver_cap: 39.42662133794202 cap_limit: 40
10939 customer_2 ('customer_2', 'customer_4')
10494 customer_2 -23.758917529634683
resNode: customer_4 deliver_cap: 69.24944578541444 cap_limit: 40
10940 customer_2 ('customer_2', 'customer_5')
10494 customer_2 -23.758917529634683
resNode: customer_5 deliver_cap: 51.54882194530532 cap_limit: 40
10941 customer_2 ('customer_2', 'customer_3')
10508 customer_2 -19.294505339189115
resNode: customer_3 deliver_cap: 69.48292690115092 cap_limit: 40
10942 customer_2 ('customer_2', 'customer_1')
10508 customer_2 -19.294505339189115
resNode: customer_1 deliver_cap: 57.5629250467645 cap_limit: 40
10943 customer_2 ('customer_2', 'depot_t')
10508 customer_2 -19.294505339189115
resNode: depot_t deliver_cap: 39.426621337942024 cap_limit: 40
10944 customer_2 ('customer_2', 'customer_4')
10508 customer_2 -19.294505339189115
resNode: customer_4 deliver_cap: 69.24944578541445 cap_limit: 40
10945 customer_2 ('customer_2', 'customer_5')
10508 customer_2 -19.294505339189115
resNode: customer_5 deliver_cap: 51.548821945305335 cap_limit: 40
10946 customer_2 ('customer_2', 'customer_3')
10514 customer_2 -21.826206116542217
resNode: customer_3 deliver_cap: 63.33034722980542 cap_limit: 40
10947 customer_2 ('customer_2', 'customer_1')
10514 customer_2 -21.826206116542217
resNode: customer_1 deliver_cap: 53.56743738125932 cap_limit: 40
10948 customer_2 ('customer_2', 'depot_t')
10514 customer_2 -21.826206116542217
resNode: depot_t deliver_cap: 33.30175349963973 cap_limit: 40
10949 customer_2 ('customer_2', 'customer_4')
10514 customer_2 -21.826206116542217
resNode: customer_4 deliver_cap: 63.06000067474214 cap_limit: 40
10950 customer_2 ('customer_2', 'customer_5')
10514 customer_2 -21.826206116542217
resNode: customer_5 deliver_cap: 42.564541491457895 cap_limit: 40
10951 customer_5 ('customer_5', 'customer_3')
10535 customer_5 -27.5500121817525
resNode: customer_3 deliver_cap: 70.16150165131582 cap_limit: 40
10952 customer_5 ('customer_5', 'customer_1')
10535 customer_5 -27.5500121817525
resNode: customer_1 deliver_cap: 63.04874477081512 cap_limit: 40
10953 customer_5 ('customer_5', 'depot_t')
10535 customer_5 -27.5500121817525
resNode: depot_t deliver_cap: 39.113755909591745 cap_limit: 40
10954 customer_5 ('customer_5', 'customer_2')
10535 customer_5 -27.5500121817525
resNode: customer_2 deliver_cap: 43.31365990380974 cap_limit: 40
10955 customer_5 ('customer_5', 'customer_4')
10535 customer_5 -27.5500121817525
resNode: customer_4 deliver_cap: 69.85428965692573 cap_limit: 40
10956 customer_5 ('customer_5', 'customer_3')
10575 customer_5 -24.080520239459858
resNode: customer_3 deliver_cap: 70.16150165131582 cap_limit: 40
10957 customer_5 ('customer_5', 'customer_1')
10575 customer_5 -24.080520239459858
resNode: customer_1 deliver_cap: 63.04874477081512 cap_limit: 40
10958 customer_5 ('customer_5', 'depot_t')
10575 customer_5 -24.080520239459858
resNode: depot_t deliver_cap: 39.113755909591745 cap_limit: 40
10959 customer_5 ('customer_5', 'customer_2')
10575 customer_5 -24.080520239459858
resNode: customer_2 deliver_cap: 43.31365990380974 cap_limit: 40
10960 customer_5 ('customer_5', 'customer_4')
10575 customer_5 -24.080520239459858
resNode: customer_4 deliver_cap: 69.85428965692573 cap_limit: 40
10961 customer_2 ('customer_2', 'customer_3')
10579 customer_2 -23.74909808299747
resNode: customer_3 deliver_cap: 73.1291343076606 cap_limit: 40
10962 customer_2 ('customer_2', 'customer_1')
10579 customer_2 -23.74909808299747
resNode: customer_1 deliver_cap: 63.04874477081512 cap_limit: 40
10963 customer_2 ('customer_2', 'depot_t')
10579 customer_2 -23.74909808299747
resNode: depot_t deliver_cap: 39.82882348501851 cap_limit: 40
10964 customer_2 ('customer_2', 'customer_4')
10579 customer_2 -23.74909808299747
resNode: customer_4 deliver_cap: 72.82192231327052 cap_limit: 40
10965 customer_2 ('customer_2', 'customer_5')
10579 customer_2 -23.74909808299747
resNode: customer_5 deliver_cap: 49.53162778681114 cap_limit: 40
10966 customer_2 ('customer_2', 'customer_3')
10599 customer_2 -19.29450533918911
resNode: customer_3 deliver_cap: 69.48292690115092 cap_limit: 40
10967 customer_2 ('customer_2', 'customer_1')
10599 customer_2 -19.29450533918911
resNode: customer_1 deliver_cap: 57.56292504676449 cap_limit: 40
10968 customer_2 ('customer_2', 'depot_t')
10599 customer_2 -19.29450533918911
resNode: depot_t deliver_cap: 39.42662133794202 cap_limit: 40
10969 customer_2 ('customer_2', 'customer_4')
10599 customer_2 -19.29450533918911
resNode: customer_4 deliver_cap: 69.24944578541444 cap_limit: 40
10970 customer_2 ('customer_2', 'customer_5')
10599 customer_2 -19.29450533918911
resNode: customer_5 deliver_cap: 51.54882194530532 cap_limit: 40
10971 customer_2 ('customer_2', 'customer_3')
10613 customer_2 -14.830093148743545
resNode: customer_3 deliver_cap: 69.48292690115092 cap_limit: 40
10972 customer_2 ('customer_2', 'customer_1')
10613 customer_2 -14.830093148743545
resNode: customer_1 deliver_cap: 57.5629250467645 cap_limit: 40
10973 customer_2 ('customer_2', 'depot_t')
10613 customer_2 -14.830093148743545
resNode: depot_t deliver_cap: 39.426621337942024 cap_limit: 40
10974 customer_2 ('customer_2', 'customer_4')
10613 customer_2 -14.830093148743545
resNode: customer_4 deliver_cap: 69.24944578541445 cap_limit: 40
10975 customer_2 ('customer_2', 'customer_5')
10613 customer_2 -14.830093148743545
resNode: customer_5 deliver_cap: 51.548821945305335 cap_limit: 40
10976 customer_2 ('customer_2', 'customer_3')
10619 customer_2 -17.361793926096645

resNode: customer_3 deliver_cap: 72.2778633845335 cap_limit: 40
11047 customer_2 ('customer_2', 'customer_1')
10819 customer_2 -22.685200596940987
resNode: customer_1 deliver_cap: 62.29962635846327 cap_limit: 40
11048 customer_2 ('customer_2', 'depot_t')
10819 customer_2 -22.685200596940987
resNode: depot_t deliver_cap: 39.113755909591745 cap_limit: 40
11049 customer_2 ('customer_2', 'customer_4')
10819 customer_2 -22.685200596940987
resNode: customer_4 deliver_cap: 71.9706513901434 cap_limit: 40
11050 customer_2 ('customer_2', 'customer_5')
10819 customer_2 -22.685200596940987
resNode: customer_5 deliver_cap: 48.68035686368405 cap_limit: 40
11051 customer_2 ('customer_2', 'customer_3')
10834 customer_2 -19.215708654648346
resNode: customer_3 deliver_cap: 72.27786338453349 cap_limit: 40
11052 customer_2 ('customer_2', 'customer_1')
10834 customer_2 -19.215708654648346
resNode: customer_1 deliver_cap: 62.29962635846327 cap_limit: 40
11053 customer_2 ('customer_2', 'depot_t')
10834 customer_2 -19.215708654648346
resNode: depot_t deliver_cap: 39.11375590959174 cap_limit: 40
11054 customer_2 ('customer_2', 'customer_4')
10834 customer_2 -19.215708654648346
resNode: customer_4 deliver_cap: 71.9706513901434 cap_limit: 40
11055 customer_2 ('customer_2', 'customer_5')
10834 customer_2 -19.215708654648346
resNode: customer_5 deliver_cap: 48.68035686368404 cap_limit: 40
11056 customer_5 ('customer_5', 'customer_3')
10855 customer_5 -18.552210562957804
resNode: customer_3 deliver_cap: 69.31023072818871 cap_limit: 40
11057 customer_5 ('customer_5', 'customer_1')
10855 customer_5 -18.552210562957804
resNode: customer_1 deliver_cap: 62.29962635846326 cap_limit: 40
11058 customer_5 ('customer_5', 'depot_t')
10855 customer_5 -18.552210562957804
resNode: depot_t deliver_cap: 38.39868833416497 cap_limit: 40
11059 customer_5 ('customer_5', 'customer_2')
10855 customer_5 -18.552210562957804
resNode: customer_2 deliver_cap: 42.564541491457895 cap_limit: 40
11060 customer_5 ('customer_5', 'customer_4')
10855 customer_5 -18.552210562957804
resNode: customer_4 deliver_cap: 69.00301873379861 cap_limit: 40
11061 customer_2 ('customer_2', 'customer_3')
10859 customer_2 -18.39085142326844
resNode: customer_3 deliver_cap: 72.27786338453349 cap_limit: 40
11062 customer_2 ('customer_2', 'customer_1')
10859 customer_2 -18.39085142326844
resNode: customer_1 deliver_cap: 62.29962635846327 cap_limit: 40
11063 customer_2 ('customer_2', 'depot_t')
10859 customer_2 -18.39085142326844
resNode: depot_t deliver_cap: 39.11375590959174 cap_limit: 40
11064 customer_2 ('customer_2', 'customer_4')
10859 customer_2 -18.39085142326844
resNode: customer_4 deliver_cap: 71.9706513901434 cap_limit: 40
11065 customer_2 ('customer_2', 'customer_5')
10859 customer_2 -18.39085142326844
resNode: customer_5 deliver_cap: 48.68035686368404 cap_limit: 40
11066 customer_2 ('customer_2', 'customer_3')
10874 customer_2 -14.9213594809758
resNode: customer_3 deliver_cap: 72.27786338453349 cap_limit: 40
11067 customer_2 ('customer_2', 'customer_1')
10874 customer_2 -14.9213594809758
resNode: customer_1 deliver_cap: 62.29962635846327 cap_limit: 40
11068 customer_2 ('customer_2', 'depot_t')
10874 customer_2 -14.9213594809758
resNode: depot_t deliver_cap: 39.11375590959174 cap_limit: 40
11069 customer_2 ('customer_2', 'customer_4')
10874 customer_2 -14.9213594809758
resNode: customer_4 deliver_cap: 71.9706513901434 cap_limit: 40
11070 customer_2 ('customer_2', 'customer_5')
10874 customer_2 -14.9213594809758
resNode: customer_5 deliver_cap: 48.68035686368404 cap_limit: 40
11071 customer_5 ('customer_5', 'customer_3')
10890 customer_5 -14.08779837251223
resNode: customer_3 deliver_cap: 69.31023072818871 cap_limit: 40
11072 customer_5 ('customer_5', 'customer_1')
10890 customer_5 -14.08779837251223
resNode: customer_1 deliver_cap: 62.29962635846326 cap_limit: 40
11073 customer_5 ('customer_5', 'depot_t')
10890 customer_5 -14.08779837251223
resNode: depot_t deliver_cap: 38.39868833416497 cap_limit: 40
11074 customer_5 ('customer_5', 'customer_2')
10890 customer_5 -14.08779837251223
resNode: customer_2 deliver_cap: 42.564541491457895 cap_limit: 40
11075 customer_5 ('customer_5', 'customer_4')
10890 customer_5 -14.08779837251223
resNode: customer_4 deliver_cap: 69.00301873379861 cap_limit: 40
11076 customer_2 ('customer_2', 'customer_3')
10894 customer_2 -14.096502249595897
resNode: customer_3 deliver_cap: 72.27786338453349 cap_limit: 40
11077 customer_2 ('customer_2', 'customer_1')
10894 customer_2 -14.096502249595897
resNode: customer_1 deliver_cap: 62.29962635846327 cap_limit: 40
11078 customer_2 ('customer_2', 'depot_t')
10894 customer_2 -14.096502249595897
resNode: depot_t deliver_cap: 39.11375590959174 cap_limit: 40
11079 customer_2 ('customer_2', 'customer_4')
10894 customer_2 -14.096502249595897
resNode: customer_4 deliver_cap: 71.9706513901434 cap_limit: 40
11080 customer_2 ('customer_2', 'customer_5')
10894 customer_2 -14.096502249595897
resNode: customer_5 deliver_cap: 48.68035686368404 cap_limit: 40
11081 customer_2 ('customer_2', 'customer_3')
10903 customer_2 -10.627010307303257
resNode: customer_3 deliver_cap: 72.27786338453349 cap_limit: 40
11082 customer_2 ('customer_2', 'customer_1')
10903 customer_2 -10.627010307303257
resNode: customer_1 deliver_cap: 62.29962635846327 cap_limit: 40
11083 customer_2 ('customer_2', 'depot_t')
10903 customer_2 -10.627010307303257
resNode: depot_t deliver_cap: 39.11375590959174 cap_limit: 40
11084 customer_2 ('customer_2', 'customer_4')
10903 customer_2 -10.627010307303257
resNode: customer_4 deliver_cap: 71.9706513901434 cap_limit: 40
11085 customer_2 ('customer_2', 'customer_5')
10903 customer_2 -10.627010307303257
resNode: customer_5 deliver_cap: 48.68035686368404 cap_limit: 40
11086 customer_5 ('customer_5', 'customer_3')
10910 customer_5 -9.0848970061391
resNode: customer_3 deliver_cap: 55.833826250852496 cap_limit: 40
11087 customer_5 ('customer_5', 'customer_1')
10910 customer_5 -9.0848970061391
resNode: customer_1 deliver_cap: 51.33642980572874 cap_limit: 40
11088 customer_5 ('customer_5', 'depot_t')
10910 customer_5 -9.0848970061391
resNode: depot_t deliver_cap: 25.20395909785809 cap_limit: 40
11089 customer_5 ('customer_5', 'customer_2')
10910 customer_5 -9.0848970061391
resNode: customer_2 deliver_cap: 28.910197002313552 cap_limit: 40
11090 customer_5 ('customer_5', 'customer_4')
10910 customer_5 -9.0848970061391
resNode: customer_4 deliver_cap: 55.48974881713559 cap_limit: 40
11091 customer_5 ('customer_5', 'customer_3')
11035 customer_5 -11.7223180632967
resNode: customer_3 deliver_cap: 60.90893608686909 cap_limit: 40
11092 customer_5 ('customer_5', 'customer_1')
11035 customer_5 -11.7223180632967
resNode: customer_1 deliver_cap: 56.1522028576844 cap_limit: 40
11093 customer_5 ('customer_5', 'depot_t')
11035 customer_5 -11.7223180632967
resNode: depot_t deliver_cap: 28.910197002313552 cap_limit: 40
11094 customer_5 ('customer_5', 'customer_2')
11035 customer_5 -11.7223180632967
resNode: customer_2 deliver_cap: 32.828920742132595 cap_limit: 40
11095 customer_5 ('customer_5', 'customer_4')
11035 customer_5 -11.7223180632967
resNode: customer_4 deliver_cap: 60.55257017337657 cap_limit: 40
11096 customer_2 ('customer_2', 'customer_3')
11089 customer_2 -10.020732056304466
resNode: customer_3 deliver_cap: 63.3639156974016 cap_limit: 40
11097 customer_2 ('customer_2', 'customer_1')
11089 customer_2 -10.020732056304466
resNode: customer_1 deliver_cap: 55.266881097632215 cap_limit: 40
11098 customer_2 ('customer_2', 'depot_t')
11089 customer_2 -10.020732056304466
resNode: depot_t deliver_cap: 28.910197002313552 cap_limit: 40
11099 customer_2 ('customer_2', 'customer_4')
11089 customer_2 -10.020732056304466
resNode: customer_4 deliver_cap: 63.0075497839091 cap_limit: 40
11100 customer_2 ('customer_2', 'customer_5')
11089 customer_2 -10.020732056304466
resNode: customer_5 deliver_cap: 35.990808133216234 cap_limit: 40
11101 customer_2 ('customer_2', 'customer_3')
11094 customer_2 -12.817517489984752
resNode: customer_3 deliver_cap: 68.73616583811048 cap_limit: 40
11102 customer_2 ('customer_2', 'customer_1')
11094 customer_2 -12.817517489984752
resNode: customer_1 deliver_cap: 60.26108914802636 cap_limit: 40
11103 customer_2 ('customer_2', 'depot_t')
11094 customer_2 -12.817517489984752
resNode: depot_t deliver_cap: 32.828920742132595 cap_limit: 40
11104 customer_2 ('customer_2', 'customer_4')
11094 customer_2 -12.817517489984752
resNode: customer_4 deliver_cap: 68.36751144484238 cap_limit: 40
11105 customer_2 ('customer_2', 'customer_5')
11094 customer_2 -12.817517489984752
resNode: customer_5 deliver_cap: 40.419158013091135 cap_limit: 40
11106 customer_5 ('customer_5', 'customer_3')
11100 customer_5 -14.788854639487486
resNode: customer_3 deliver_cap: 72.10376613842251 cap_limit: 40
11107 customer_5 ('customer_5', 'customer_1')
11100 customer_5 -14.788854639487486
resNode: customer_1 deliver_cap: 67.33063737718938 cap_limit: 40
11108 customer_5 ('customer_5', 'depot_t')
11100 customer_5 -14.788854639487486
resNode: depot_t deliver_cap: 35.990808133216234 cap_limit: 40
11109 customer_5 ('customer_5', 'customer_2')
11100 customer_5 -14.788854639487486
resNode: customer_2 deliver_cap: 40.419158013091135 cap_limit: 40
11110 customer_5 ('customer_5', 'customer_4')
11100 customer_5 -14.788854639487486
resNode: customer_4 deliver_cap: 71.6982463058276 cap_limit: 40

In [501]:
reward[s_0]

-1.119773023916526

In [505]:
a = pd.Series(reward)

In [506]:
b = a[a>0]
b

<__main__.SPPState object at 0x7f7f6b98a100>    0.263652
<__main__.SPPState object at 0x7f7f59ec8f40>    0.263652
<__main__.SPPState object at 0x7f7f6b984100>    0.013681
<__main__.SPPState object at 0x7f7f78e8b760>    0.013681
dtype: float64

In [465]:
def reconstructPath(_last_state, _prev_dict):
    curr_state = _last_state
    path = [curr_state.resNode]
    while curr_state.resNode != depot_s[0]:
#         print('currNode:',curr_state.resNode )
        prev_state = _prev_dict[curr_state]
        path = [prev_state.resNode] + path
        curr_state = prev_state
#         print('nextNode:',curr_state.resNode )
    return path

In [507]:
for s in b.index:
    print(reconstructPath(s,prev), s.label)

['depot_s', 'customer_2', 'customer_1'] 17
['depot_s', 'customer_2', 'customer_1', 'depot_t'] 77
['depot_s', 'customer_2', 'customer_5', 'customer_2'] 89
['depot_s', 'customer_2', 'customer_5', 'customer_2', 'depot_t'] 363

In [407]:
class SPPState:
    def __init__(self, _resNode, _accDemand, _accDistance, _nodeVisited, _label):
        self.resNode = _resNode
        self.accDemand = _accDemand
        self.accDistance = _accDistance
        self.nodeVisited = _nodeVisited
        self.label = _label
        
    def checkFeasibility(self, _total_demand, _max_vehicle_per_route, _return_cost):
        deliver_cap = _state.accDemand*(_state.accDistance+_return_cost)
        if deliver_cap <= _total_demand*_max_vehicle_per_route: return True
        else: return False

def checkFeasibility(_state, _total_demand, _max_vehicle_per_route,_return_cost):
    deliver_cap = _state.accDemand*(_state.accDistance+_return_cost)
    limit_cap = _total_demand*_max_vehicle_per_route
    print('resNode:',_state.resNode,'deliver_cap:',deliver_cap,'cap_limit:',limit_cap )
    if deliver_cap <=limit_cap: return True
    else: return False

In [230]:
arcs_ss[arcs_ss.str.contains(currState.resNode)].apply(lambda x: tuple(x.split(',')))

11     (depot_s, customer_9)
29    (depot_s, customer_10)
45     (depot_s, customer_3)
59     (depot_s, customer_8)
71     (depot_s, customer_1)
81     (depot_s, customer_7)
90     (depot_s, customer_2)
92     (depot_s, customer_4)
94     (depot_s, customer_6)
96     (depot_s, customer_5)
dtype: object

In [494]:
phaseII_model.route_cost[(phaseII_model.route_cost>1.68) & (phaseII_model.route_cost<1.683)]

route[19]    1.681487
dtype: float64

In [500]:
# phaseII_model.init_routes_df.set_index('labels')['route[19]']

## (XX) Class and functions

In [2]:
MODULE_DIR = '/Users/ravitpichayavet/Documents/GaTechOR/GraduateResearch/CTC_CVRP/Modules'
GUROBI_LICENSE_DIR = '/Users/ravitpichayavet/gurobi.lic'
# INSTANCE_PATH = MODULE_DIR+'Combine_variables/Experiment/'

import sys
sys.path.insert(0,MODULE_DIR)

import visualize_sol as vis_sol
import initialize_path as init_path
import random_instance as rand_inst
import utility as util
import branch_and_price as bnp
import model as md

import numpy as np
from gurobipy import *
import os
os.environ['GRB_LICENSE_FILE'] = GUROBI_LICENSE_DIR


from itertools import combinations,permutations 
import random 
import pandas as pd
import itertools
import plotly.graph_objects as go
import networkx as nx
import plotly.offline as py 
import pickle as pk
import nltk
import time
import copy

from matplotlib import pyplot as plt
from sklearn.datasets.samples_generator import make_blobs
from sklearn.cluster import KMeans
from scipy.spatial import distance
import logging
# logging.basicConfig(filename='myapp.log',filemode='w',format='%(message)s',level=logging.INFO)
# print = logging.info

### Create instances

In [3]:
def rand_dis_mat(nodes, service_region_len = 20):
    # random the nodes position
    no_nodes = len(nodes)
    _distance_matrix=dict()
    _nodes_position = dict()
    rand_seed = np.random.uniform(low=-1.5,high=0)
    for i in range(no_nodes):
        if nodes[i]!=depot[0]:
            _nodes_position[nodes[i]] = list(np.random.rand(2)*service_region_len)
#     print(nodes_position)
    _nodes_position[depot[0]] = [service_region_len/2,service_region_len/2]
#     print(nodes_position)
    for i in range(no_nodes):
        for j in range(no_nodes):
            if i>j:
                point_i = np.array(_nodes_position[nodes[i]])
                point_j = np.array(_nodes_position[nodes[j]])
                t_dist_rand = np.linalg.norm(point_i-point_j,ord=1)
                _distance_matrix[(nodes[i],nodes[j])] = t_dist_rand
                _distance_matrix[(nodes[j],nodes[i])] = t_dist_rand
    return _distance_matrix, _nodes_position

def random_customer_demand(customers):
    demand = np.random.randint(1,6,len(customers)).tolist()
    customer_demand = pd.Series(demand,index = customers)
    return customer_demand

def merge_depot_arcs_var(a_var,depot,depot_s,depot_t):
    '''INPUT: ['depot_s,customer_1,T','customer_2,depot_t,T']
    OUTPUT: ['depot,customer_1,T','customer_2,depot,T']'''
    new_a_var =[]
    for a in a_var:
        v = a.split(',')
        if len(v)>1:
            if v[0]==depot_s[0] or v[0]==depot_t[0]:v[0]=depot[0]
            if v[1]==depot_s[0] or v[1]==depot_t[0]:v[1]=depot[0]
        else:
            if v[0]==depot_s[0] or v[0]==depot_t[0]:v[0] = depot[0]
        new_a_var.append(','.join(v))
    return new_a_var  

def prep_for_plot(route_df,optimal_route_df,_arcs):
    reformatted_arcs=[]
    for idx in optimal_route_df.index:
        sample_r = route_df.loc[:][idx]
        sample_arcs = sample_r[sample_r.index.isin(_arcs)][sample_r==1]
        reformatted_arcs += [merge_depot_arcs_var([t],depot,depot_s,depot_t) for t in sample_arcs.index.to_list()]
    return reformatted_arcs

In [4]:
class InitialRouteGenerator:
    def __init__(self, no_truck, no_dock, no_customer, customer_demand, constant_dict, distance_matrix):
        # CONSTANTs
        self.no_truck = no_truck
        self.no_dock = no_dock
        self.no_customer = no_customer
        self.customer_demand = customer_demand
        self.distance_matrix = distance_matrix
        self.truck_capacity = constant_dict['truck_capacity']
        self.fixed_setup_time = constant_dict['fixed_setup_time']

    def generateNodeSet(self):
        self.docking,self.customers,self.depot,self.depot_s,self.depot_t,self.all_depot,self.nodes,self.arcs=vis_sol.create_nodes(self.no_dock,self.no_customer)
        self.arcs = [','.join(list(l)) for l in self.arcs]
        self.arcs = self.splitDepotArcsVar(self.arcs,self.depot,self.depot_s,self.depot_t)
        return self.docking,self.customers,self.depot,self.depot_s,self.depot_t,self.all_depot,self.nodes,self.arcs  
    
    def generateArcs(self):
        #Not nesessary as arcs already generated with nodeSet
        nodes = set()
        nodes = list(nodes.union(set(self.docking),set(self.customers),set(self.depot)))
        no_node = len(nodes)
        node_combi = list(combinations(nodes,2))
        arc_permute = [list(permutations(list(c))) for c in node_combi ]
        sh = np.shape(arc_permute)
        arc_permute = np.reshape(arc_permute,(sh[0]*sh[1],sh[2])).tolist()
        arc_permute = [','.join(list(l)) for l in arc_permute]
        print(arc_permute)
        arc_permute = self.splitDepotArcsVar(arc_permute,self.depot,self.depot_s,self.depot_t)
        print("Finished creating truck_arcs:",len(arc_permute))
        return arc_permute
    
    def splitDepotArcsVar(self,a_var,depot,depot_s,depot_t):
        '''INPUT: ['depot,customer_1,T','customer_2,depot,T']
        OUTPUT:['depot_s,customer_1,T','customer_2,depot_t,T'] '''
        new_a_var =[]
        for a in a_var:
            v = a.split(',')
            if len(v)>1:
                if v[0]==depot[0]: v[0]=depot_s[0]
                if v[1]==depot[0]: v[1]=depot_t[0]
            new_a_var.append(','.join(v))
        return new_a_var
    
    def mergeDepotArcsVar(self,a_var,depot,depot_s,depot_t):
        '''INPUT: ['depot_s,customer_1,T','customer_2,depot_t,T']
        OUTPUT: ['depot,customer_1,T','customer_2,depot,T']'''
        new_a_var =[]
        for a in a_var:
            v = a.split(',')
            if len(v)>1:
                if v[0]==depot_s[0] or v[0]==depot_t[0]:v[0]=depot[0]
                if v[1]==depot_s[0] or v[1]==depot_t[0]:v[1]=depot[0]
            else:
                if v[0]==depot_s[0] or v[0]==depot_t[0]:v[0] = depot[0]
            new_a_var.append(','.join(v))
        return new_a_var    
    
    def generateAllCombiNodes(self,max_visited_nodes=None,str_node=None,end_node=None):
        '''THIS FUNCTION WILL GENERATE ALL POSSIBLE COMBINATIONS OF INPUT NODE LIST'''
        all_combi_nodes = []
        for i in range(1,max_visited_nodes+1):
            combination_set = list(combinations(self.customers,i))
            permutation_set = [list(permutations(list(c))) for c in combination_set ]
        #     print(permutation_set,np.shape(permutation_set))
            sh = np.shape(permutation_set)
        #     print(np.reshape(permutation_set,(sh[0]*sh[1],sh[2])))
            re_perm_set = np.reshape(permutation_set,(sh[0]*sh[1],sh[2])).tolist()
            all_combi_nodes = all_combi_nodes+re_perm_set
        # ADD depot 
        if (str_node is not None) and (end_node is not None):
            all_combi_nodes = [str_node+p+end_node for p in all_combi_nodes]
        else:all_combi_nodes = [p for p in all_combi_nodes]
        return all_combi_nodes
    
    def generateSetOfArcsFromNodesCombi(self,all_combi_nodes,added_type=''):
        '''THIS FUNCTION WILL GENERATE ARCS LIST BY CREATING BIGRAMS OF INPUT COMBI NODES''' 
        node2arcs = []
        for r in all_combi_nodes:    
            if len(r)==1: arc_list = [r]
            else: arc_list = list(nltk.bigrams(r))
            if added_type!='':arc_list = [','.join(list(a)+[added_type]) for a in arc_list]
            else:arc_list = [','.join(a) for a in arc_list]
            node2arcs.append(arc_list)
        return node2arcs
    
    def generateRoutes(self,initRouteDf,truck_cap_limit,
                       max_visited_nodes=None, max_vehicles_per_route=None, 
                       clustered=None, nbInitRoute=None,
                       mode='all',drone_cap_limit=None):
        if max_visited_nodes is None: max_visited_nodes=len(self.customers)
        if max_vehicles_per_route is None: max_vehicles_per_route=len(self.customers)
        self.all_combi_nodes=list()
        self.routes_arcs=list()
        t1 = time.time()
        _all_combi_nodes = self.generateAllCombiNodes(max_visited_nodes,self.depot_s,self.depot_t)
        self.all_combi_nodes+= _all_combi_nodes
        self.routes_arcs += self.generateSetOfArcsFromNodesCombi(_all_combi_nodes,'')
        
        if nbInitRoute is None: nbInitRoute = len(self.all_combi_nodes)
        print('nbInitRoute is set to',nbInitRoute)
        
        previous_cols = initRouteDf.columns[initRouteDf.columns.str.contains('r')].shape[0]
        ## ADD NEW COL TO DATAFRAME
        counter = 0
        for idx in range(len(self.all_combi_nodes)):
            if ((idx/len(self.all_combi_nodes))*100 % 10)==0: 
                print('progress:',idx,'/',len(self.all_combi_nodes))
            if idx>nbInitRoute: break
            lr_route = self.calculateLr(self.routes_arcs[idx])
            qr_route = pd.Series(self.all_combi_nodes[idx]).apply(lambda x: self.customer_demand[x]).sum()
            veh_min = int(np.ceil(qr_route*lr_route/self.truck_capacity))
            
            if veh_min > max_vehicles_per_route: continue
            else:
                for veh_no in range(veh_min,max_vehicles_per_route+1):
                    if veh_no < veh_min: continue
                    else:
                        self.addNewCol(initRouteDf, lr_route, veh_no,self.all_combi_nodes[idx],self.routes_arcs[idx],'route['+str(counter)+']')
                        counter += 1; #print(veh_no,veh_min)
        initRouteDf['labels']=init_path.splitDepotArcsVar(initRouteDf.labels,self.depot,[self.all_depot[0]],[self.all_depot[1]])
        self.init_routes_df = initRouteDf.copy()
#         self.init_routes_df = self.init_routes_df.set_index('labels')
        print('#Feasible Cols:', len(initRouteDf.columns)-1)
        print('Elased-time:',time.time()-t1)
    
    def generateBasicInitialPatterns(self,nbInitRoute,initRouteDf):
        columns = ['PathCoeff']
        path = pd.DataFrame(index = range(nbInitRoute), columns = columns)
        path['PathCoeff']=[initRouteDf[initRouteDf.columns[idx]].values for idx in range(nbInitRoute)]
        return path
    
    
    def addNewCol(self, df, col_cost, veh_no, nodes, arcs, var_name=None):
        # SET DEFAULT AS INDEXING
        coeff = nodes+arcs
        if var_name is None:
            var_name = df.columns.shape[0]
        df[var_name]= np.in1d(df.labels,coeff).astype(int)
        df.loc[df['labels']=='m',var_name] = veh_no
        df.loc[df['labels']=='lr',var_name] = col_cost
    
    
    def calculateLr(self, route_arcs):
        formatted_routes = self.mergeDepotArcsVar(route_arcs,self.depot,self.depot_s,self.depot_t)
        lr = self.fixed_setup_time+(pd.Series(formatted_routes).apply(lambda x:self.distance_matrix[tuple(x.split(','))]).sum()/20)
        return lr

### Phase_I Class

In [5]:
class phaseIModel:
    def __init__(self, _init_route, _initializer,
                 _distance_matrix,constant_dict,
                 extra_constr=None, _model_name = "PhaseI"):
        
        self.init_route = _init_route.copy()
        self.route_coeff = _init_route['PathCoeff'].values
        
        self.depot = _initializer.depot
        self.depot_s = _initializer.depot_s
        self.depot_t = _initializer.depot_t
        self.all_depot = _initializer.all_depot
        self.customers = _initializer.customers
        self.nodes = _initializer.nodes
        self.arcs = _initializer.arcs
    

        self.coeff_series = _initializer.init_routes_df['labels']
        self.depot_index = self.coeff_series[self.coeff_series.isin(self.all_depot)].index.values
        self.depot_s_index = self.coeff_series[self.coeff_series.isin(self.depot_s)].index.values
        self.depot_t_index = self.coeff_series[self.coeff_series.isin(self.depot_t)].index.values
        self.customer_index = self.coeff_series[self.coeff_series.isin(self.customers)].index.values
        self.nodes_index = self.coeff_series[self.coeff_series.isin(self.nodes)].index.values
        self.arcs_index = self.coeff_series[self.coeff_series.str.contains(',')].index.values
        self.veh_no_index = self.coeff_series.loc[self.coeff_series=='m'].index.values
        self.lr_index = self.coeff_series.loc[self.coeff_series=='lr'].index.values
    
        self.constant_dict = constant_dict
        self.vehicle_capacity = constant_dict['truck_capacity']
        self.fixed_setup_time = constant_dict['fixed_setup_time']
        self.truck_speed = constant_dict['truck_speed']
        self.distance_matrix = distance_matrix
        
        self.route_index = pd.Series(self.init_route.index).index.values
        self.model = Model(_model_name)

    def buildModel(self):
        self.generateVariables()
        self.generateConstraints()
        self.generateObjective()
        self.model.update()
        
    def generateVariables(self):
        self.route = self.model.addVars(self.route_index, lb=0,
                                       vtype=GRB.BINARY, name='route')
        print('Finish generating variables!')
        
    def generateConstraints(self):          
        const1 = ( quicksum(self.route_coeff[rt][i]*self.route[rt] for rt in self.route_index) ==1 \
                             for i in self.customer_index )
        self.model.addConstrs( const1,name='customer_coverage' )
        print('Finish generating constrains!')
        
    def generateObjective(self):
        # Minimize the total cost of the used rolls
        self.model.setObjective( quicksum(self.route[rt]*(self.route_coeff[rt][self.veh_no_index[0]]) for rt in self.route_index) ,
                                sense=GRB.MINIMIZE)
        print('Finish generating objective!')
        
    def solveModel(self, timeLimit = None,GAP=None):
        self.model.setParam('SolutionNumber',2)
        self.model.setParam(GRB.Param.PoolSearchMode, 2)
        self.model.setParam('TImeLimit', timeLimit)
        self.model.setParam('MIPGap',GAP)
        self.model.optimize()

### Phase_II Class

In [6]:
class phaseIIModel:
    def __init__(self, _init_route, _initializer,
                 _distance_matrix,constant_dict,
                 extra_constr=None, _model_name = "PhaseI"):
        
        self.init_route = _init_route.copy()
        self.route_coeff = _init_route['PathCoeff'].values
        self.init_routes_df = _initializer.init_routes_df
        
        self.depot = _initializer.depot
        self.depot_s = _initializer.depot_s
        self.depot_t = _initializer.depot_t
        self.all_depot = _initializer.all_depot
        self.customers = _initializer.customers
        self.nodes = _initializer.nodes
        self.arcs = _initializer.arcs
        self.route_cost = []
    

        self.coeff_series = _initializer.init_routes_df['labels']
        self.depot_index = self.coeff_series[self.coeff_series.isin(self.all_depot)].index.values
        self.depot_s_index = self.coeff_series[self.coeff_series.isin(self.depot_s)].index.values
        self.depot_t_index = self.coeff_series[self.coeff_series.isin(self.depot_t)].index.values
        self.customer_index = self.coeff_series[self.coeff_series.isin(self.customers)].index.values
        self.nodes_index = self.coeff_series[self.coeff_series.isin(self.nodes)].index.values
        self.arcs_index = self.coeff_series[self.coeff_series.str.contains(',')].index.values
        self.veh_no_index = self.coeff_series.loc[self.coeff_series=='m'].index.values
        self.lr_index = self.coeff_series.loc[self.coeff_series=='lr'].index.values
    
        self.constant_dict = constant_dict
        self.vehicle_capacity = constant_dict['truck_capacity']
        self.fixed_setup_time = constant_dict['fixed_setup_time']
        self.truck_speed = constant_dict['truck_speed']
        self.distance_matrix = distance_matrix
        self.customer_demand = _initializer.customer_demand
        self.max_vehicles = constant_dict['max_vehicles']
        
        self.route_index = pd.Series(self.init_route.index).index.values
        self.model = Model(_model_name)

    def buildModel(self):
        self.generateVariables()
        self.generateConstraints()
        self.generateCostOfRoutes()
        self.generateObjective()
        self.model.update()
        
    def generateVariables(self):
        self.route = self.model.addVars(self.route_index, lb=0,
                                       vtype=GRB.BINARY, name='route')
        print('Finish generating variables!')
        
    def generateConstraints(self):          
        const1 = ( quicksum(self.route_coeff[rt][i]*self.route[rt] for rt in self.route_index) >=1 \
                             for i in self.customer_index )
        self.model.addConstrs( const1,name='customer_coverage' )
        
        const2 = (quicksum(self.route[rt]*(self.route_coeff[rt][self.veh_no_index[0]]) for rt in self.route_index)==self.max_vehicles)
        self.model.addConstr(const2,name='vehicles_usage' )
        print('Finish generating constrains!')
    
    def generateCostOfRoutes(self):
        t1=time.time()
        self.route_cost = self.init_routes_df.set_index('labels').apply(lambda col: self.calculateCostOfRoute(col),axis=0)
        print('Finish generating cost vector!....Elapsed-time:',time.time()-t1)
    def calculateCostOfRoute(self, route):
        visiting_nodes = pd.Series(route[self.customer_index][route==1].index)
        visiting_arcs = pd.Series(route[self.arcs_index][route==1].index)
        next_node = ['depot_s']
#         print(route)
        route_cost = 0
        qr = visiting_nodes.apply(lambda x: self.customer_demand[x]).sum()
        avg_waiting = qr*route['lr']/(2*route['m'])
        while next_node[0]!='depot_t':
            selecting_node = next_node.pop(0)
#             print(selecting_node)
            arc = visiting_arcs[visiting_arcs.str.contains(selecting_node+',')].values[0].split(',')
            node_j = arc[1]
            next_node.append(node_j)
            qj = self.customer_demand[node_j]
            formatted_arc = tuple(merge_depot_arcs_var([','.join(arc)],self.depot,
                                                          self.depot_s,self.depot_t)[0].split(','))
            traveling_time_carrying_pkg = qr*(self.distance_matrix[formatted_arc])/self.constant_dict['truck_speed']
#             print(arc, qj, self.distance_matrix[formatted_arc])
#             print(traveling_time_carrying_pkg)
            route_cost+=traveling_time_carrying_pkg
            qr = qr-qj
    
#         print(avg_waiting,route_cost)
        route_cost += avg_waiting
#         print(route_cost)
        return route_cost
        
    def generateObjective(self):
        # Minimize the total cost of the used rolls
        self.model.setObjective( quicksum(self.route[rt]*(self.route_cost[rt]) for rt in self.route_index) ,
                                sense=GRB.MINIMIZE)
        print('Finish generating objective!')
        
    def solveModel(self, timeLimit = None,GAP=None):
        self.model.setParam('SolutionNumber',2)
        self.model.setParam(GRB.Param.PoolSearchMode, 2)
        self.model.setParam('TImeLimit', timeLimit)
        self.model.setParam('MIPGap',GAP)
        self.model.optimize()
        
    ##RELAXATION
    def solveRelaxedModel(self):
        #Relax integer variables to continous variables
        self.relaxedModel = self.model.relax()
        self.relaxedModel.optimize()
        
    def getRelaxSolution(self):
        a = pd.Series(self.relaxedModel.getAttr('X'))
        return a[a>0]

    def getDuals(self):
        return self.relaxedModel.getAttr('Pi',self.model.getConstrs())